# Error Analysis: Agreement

- **Question:** How much does high model agreement and incorrect majority vote exist within each class (tp, fn, tn, fp)?

In [ ]:
import os
import sys

import pandas as pd

notebook_dir = os.getcwd()

sys.path.append(os.path.join(notebook_dir, '../'))

from metrics import EvaluationMetric
from data_processing import DataProcessing

In [2]:
pd.set_option('max_colwidth', 800)
# pd.set_option('display.max_columns', None)
# pd.set_option('display.max_columns', 40)
# pd.set_option('display.max_rows', None)

## Load Data

In [3]:
base_data_path = DataProcessing.load_base_data_path(notebook_dir)
# combine_data_path = os.path.join(base_data_path, 'financial_phrase_bank/combined_generated_fin_phrase_bank')
train_data = os.path.join(base_data_path, 'classification_results/train_synthetic-v1_2026-03-23/seed3')

In [4]:
# model_results_path = os.path.join(combine_data_path, 'inference_chronicle2050_2026-03-07_21-51-47.csv')
test_data = os.path.join(train_data, 'external_fpb-maya-binary-imbalanced-96d-v1/', 'ml_classifiers_fpb-maya-binary-imbalanced-96d-v1.csv')

model_results_df = DataProcessing.load_from_file(test_data, 'csv', sep=',')
cols_to_drop = ["Dataset Name", "Author Type", "maya_label"]
compare_y_vs_yhats_df = DataProcessing.drop_df_columns(model_results_df, cols_to_drop)
compare_y_vs_yhats_df

,Base Sentence,Sentence Label,Base Sentence Embedding,perceptron,sgd_classifier,logistic_regression,ridge_classifier,decision_tree_classifier,random_forest_classifier,gradient_boosting_classifier,support_vector_machine_classifier,x_gradient_boosting_classifier
0,With the new production plant the company would increase its capacity to meet the expected increase in demand and would improve the use of raw materials and therefore increase the production profitability .,1,[-1.22568220e-01 2.48624131e-01 -4.82655168e-02 -1.09789923e-01\n -8.58348906e-02 3.63291465e-02 -1.27964811e-02 7.17335939e-02\n -1.18364163e-01 2.27930522e+00 -3.32476139e-01 -1.46164745e-02\n 1.25499114e-01 7.25146085e-02 6.57393187e-02 -5.76901138e-02\n -2.05907249e-03 1.51917112e+00 -3.29480022e-01 -4.57408801e-02\n 2.22120117e-02 1.05339624e-01 -4.22692373e-02 -1.23566784e-01\n -5.79119613e-03 6.18153140e-02 -5.48806489e-02 2.96797305e-02\n -1.07008472e-01 -9.98812243e-02 -9.39770564e-02 3.87728140e-02\n -5.82127571e-02 7.14930072e-02 9.65250358e-02 -3.75642404e-02\n 7.18023349e-03 6.21852428e-02 7.68979266e-02 -1.69069305e-01\n 1.44475931e-03 7.71993026e-02 3.41709815e-02 -1.10992551e-01\n -1.81387588e-02 -8.61631632e-02 -2.34903637e-02 6.00658916e-02\n -3....,1,1,1,1,0,1,1,1,1
1,"According to the company 's updated strategy for the years 2009-2012 , Basware targets a long-term net sales growth in the range of 20 % -40 % with an operating profit margin of 10 % -20 % of net sales .",1,[-2.63320029e-01 3.28540474e-01 4.48558182e-02 -1.09422831e-02\n 3.39385755e-02 -1.25387803e-01 2.09340192e-02 8.32975954e-02\n 1.10356383e-01 1.74510765e+00 -3.98153275e-01 1.41264707e-01\n -8.98099765e-02 -1.47727029e-02 5.77163734e-02 -5.09223454e-02\n -4.27257568e-02 1.41277170e+00 -2.09747717e-01 1.56779997e-02\n -3.64826852e-03 5.97854443e-02 -7.89400712e-02 -1.39893517e-02\n 1.13595366e-01 9.83026922e-02 -5.14178127e-02 7.06899390e-02\n 2.47105230e-02 1.06609218e-01 -4.19648038e-03 -1.85196903e-02\n -1.48957130e-02 9.90139246e-02 1.10973224e-01 -2.59710420e-02\n -6.08825274e-02 4.48305123e-02 4.36691009e-02 -9.27021950e-02\n 6.36729002e-02 1.98753644e-02 2.10891932e-01 -8.54000822e-02\n 4.67465706e-02 -2.04764325e-02 -3.69948000e-02 1.16207667e-01\n 1....,1,1,0,0,1,1,1,0,1
2,TeliaSonera TLSN said the offer is in line with its strategy to increase its ownership in core business holdings and would strengthen Eesti Telekom 's offering to its customers .,1,[ 1.15080299e-02 1.98225155e-01 1.95062440e-02 -5.97744621e-02\n 1.75585955e-01 -1.25474662e-01 -3.72287892e-02 -2.83286646e-02\n -3.56662273e-02 1.96045303e+00 -2.79843062e-01 -1.04898110e-01\n 4.49508205e-02 1.31481076e-02 6.55795187e-02 -4.11130209e-03\n -5.56710083e-03 1.11790729e+00 -1.21459611e-01 -9.75316912e-02\n 2.18506586e-02 1.38311490e-01 9.17155594e-02 -5.85136563e-02\n 1.03342809e-01 7.32071251e-02 -3.92427929e-02 1.13294438e-01\n -1.07247204e-01 5.58346435e-02 -9.28281173e-02 5.48683619e-03\n -1.84886660e-02 5.24056628e-02 4.05881368e-02 -8.35432187e-02\n 1.13391867e-02 2.78038122e-02 -5.44880610e-03 -1.02035753e-01\n -6.69988245e-02 7.79658780e-02 5.37769347e-02 -1.39616817e-01\n 2.96867881e-02 1.13102477e-02 -3.53476144e-02 -1.88835058e-02\n -4....,1,1,1,1,1,1,1,1,1
3,"STORA ENSO , NORSKE SKOG , M-REAL , UPM-KYMMENE Credit Suisse First Boston ( CFSB ) raised the fair value for shares in four of the largest Nordic forestry groups .",1,[-5.94305294e-03 1.57299116e-01 -1.01663664e-01 -4.74716797e-02\n 1.79840446e-01 2.63532978e-02 4.07044962e-02 -3.17418873e-02\n -1.32127828e-03 1.28309309e+00 -3.01563025e-01 4.19499092e-02\n 4.76229452e-02 -1.16947450e-01 -1.42535036e-02 2.37643998e-02\n -3.57760116e-02 8.38545859e-01 -5.43218441e-02 2.42432952e-03\n 7.67285563e-03 4.88467440e-02 4.74129207e-02 -2.67546187e-04\n 6.47759363e-02 7.66171236e-03 -7.71588413e-03 6.14660196e-02\n 9.25298501e-03 1.29891783e-01 6.76145032e-02 -7.35822739e-03\n 3.22291143e-02 1.50113806e-01 1.32441163e-01 -9.81159508e-03\n -1.39411157e-02 1.04931206e-03 -1.90248825e-02 -9.27351974e-03\n -2.62032263e-02 7.86117762e-02 8.33134279e-02 2.64521260e-02\n -1.58701912e-02 9.79095325e-03 3.53994928e-02 -1.72072705e-02\n 7....,0,0,0,0,1,0,0,0,0
4,The company also estimates the already carried out investments to lead to an increase in its net sales for 2010 from 2009 when they reached EUR 141.7 million .,1,[-9.75671411e-02 2.17742935e-01 -5.24893478e-02 2.29859371e-02\n 1.95262451e-02 -3.96593288e-02 -2.93270722e-02 1.45730842e-02\n 8.01267326e-02 2.14558053e+00 -3.02207738e-01 7.73812085e-02\n 9.75400433e-02 -5.86019419e-02 2.85570417e-02 -6.01695329e-02\n -6.48141513e-03 1.10976875e+00 -1.62209153e-01 -2.63800696e-02\n 6.90186918e-02 5.40496930e-02 -4.89046909e-02 -1.06065851e-02\n 3.81638743e-02 8.63624960e-02 -1.46540195e-01 -7.51399994e-02\n -5.42312972e-02 -2.43689902e-02 3.15490589e-02 -7.77387097e-02\n -1.04405805e-01 1.55526847e-01 2.55947262e-02 -2.01004483e-02\n -4.33546826e-02 2.11381875e-02 9.09157470e-02 -9.94266123e-02\n -5.63282613e-03 7.87854865e-02 1.45106107e-01 -1.49363369e-01\n 2.86051352e-02 -9.17335041e-03 -3.88870686e-02 -1.43906018e-02\n 2....,1,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
4841,LONDON MarketWatch -- Share prices ended lower in London Monday as a rebound in bank stocks failed to offset broader weakness for the FTSE 100 .,0,[-9.97306556e-02 1.64349496e-01 1.71351619e-02 7.13192746e-02\n 1.75899908e-01 -1.15603261e-01 -8.73757303e-02 -3.37601155e-02\n 5.58915287e-02 1.69525981e+00 -4.03638840e-01 3.41098830e-02\n 1.48271397e-01 -5.36716953e-02 4.27423716e-02 3.00230049e-02\n -4.06325832e-02 1.12422264e+00 -4.39298190e-02 1.07508982e-02\n -7.20263198e-02 5.96804582e-02 4.38548550e-02 -1.71869665e-01\n 5.18397167e-02 1.47482648e-01 -3.61646675e-02 8.63183811e-02\n -4.57509570e-02 6.86240196e-02 -7.81383812e-02 6.77803857e-03\n 1.96492635e-02 3.25613059e-02 8.09665844e-02 1.05558559e-01\n 1.15658459e-03 3.71128581e-02 -1.13167958e-02 -6.61973208e-02\n -1.17063336e-02 -1.49593409e-02 1.30228832e-01 1.75232589e-02\n 3.42527404e-02 4.42111705e-05 1.07453475e-02 -6.22191653e-02\n 2....,0,0,0,0,0,0,1,0,0
4842,"Rinkuskiai 's beer sales fell by 6.5 per cent to 4.16 million litres , while Kauno Alus ' beer sales jumped by 6.9 per cent to 2.48 million litres .",0,[-1.98924989e-01 3.00148040e-01 1.01390548e-01 -1.25840604e-01\n 3.24619608e-03 -1.00019135e-01 -1.24527112e-01 -5.24022356e-02\n 1.37367668e-02 1.35610378e+00 -2.27968454e-01 1.58202261e-01\n -7.28038773e-02 -4.16742004e-02 1.74741030e-01 -2.46515095e-01\n 3.43543403e-02 9.48214471e-01 -9.90116820e-02 -1.46733001e-01\n -5.03083616e-02 7.97276795e-02 2.76607871e-02 2.14223936e-02\n 8.79974142e-02 -9.17081013e-02 -1.13138795e-01 5.91326691e-02\n 1.20140046e-01 -3.84076685e-02 -3.18211094e-02 -1.06555417e-01\n -4.91127931e-02 -3.66714634e-02 2.47359928e-03 -6.18500356e-03\n -1.42085582e-01 -3.00514344e-02 5.16138040e-02 3.66412327e-02\n -6.68754056e-02 -4.96820062e-02 1.96969017e-01 -2.14436855e-02\n 3.49904411e-02 8.42073932e-02 5.88495322e-02 2.23803204e-02\n -1....,0,0,0,0,1,0,0,0,0
4843,"Operating profit fell to EUR 35.4 mn from EUR 68.8 mn in 2007 , including vessel sales gain of EUR 12.3 mn .",0,[-1.26625523e-01 2.81394184e-01 1.47076428e-01 -8.27063471e-02\n 1.89998314e-01 -1.95341870e-01 4.09874618e-02 4.50612567e-02\n 1.91018894e-01 1.17237604e+00 -3.50073159e-01 1.32276177e-01\n 1.80098731e-02 -3.21719684e-02 1.55063599e-01 -1.11439444e-01\n 5.50558940e-02 1.04285705e+00 -1.20266512e-01 4.59595509e-02\n 1.10065266e-01 5.54235131e-02 -1.12656087e-01 -1.29508138e-01\n 1.33550599e-01 9.51396152e-02 -5.79518043e-02 -1.48020387e-01\n -5.75628951e-02 1.92942038e-01 5.40777408e-02 -1.02687180e-01\n -9.71201211e-02 7.68551379e-02 1.51430340e-02 -7.59296939e-02\n -1.33880302e-01 -6.48121685e-02 8.27361941e-02 1.65923476e-01\n -6.65841550e-02 -5.17907441e-02 1.25316873e-01 -8.98319855e-02\n -1.09120391e-01 8.51464048e-02 9.52818319e-02 8.35352391e-02\n 2....,0,0,0,0,0,0,0,0,0
4844,"Net sales of the Paper segment decreased to EUR 221.6 mn in the second quarter of 2009 from EUR 241.1 mn in the second quarter of 2008 , while operating profit excluding non-recurring items rose to EUR 8.0 mn from EUR 7.6 mn .",0,[-1.32034168e-01 2.24063978e-01 3.11533064e-02 1.04350876e-02\n 1.56703591e-01 -1.01873629e-01 2.23107524e-02 5.80221787e-02\n 1.09591357e-01 1.37637448e+00 -3.08786511e-01 6.17817082e-02\n 9.21739489e-02 -4.09597717e-02 1.86670780e-01 -2.55621858e-02\n 5.35475016e-02 1.13686538e+00 -8.73383507e-02 -2.77639553e-02\n 4.91071157e-02 6.25430942e-02 -9.91906524e-02 -4.09849957e-02\n 1.23337105e-01 8.61576125e-02 -1.24529265e-01 -8.46296623e-02\n -1.07371166e-01 1.51070386e-01 1.05449930e-02 -4.81814779e-02\n -1.36766464e-01 9.01109204e-02 2.72464938e-02 1.43071718e-03\n -1.20931201e-01 2.54633697e-03 1.08788302e-02 3.64606492e-02\n 3.07067460e-03 8.49255845e-02 1.09374307e-01 -5.65562025e-02\n -2.14073937e-02 4.81035821e-02 1.16443343e-01 5.90736568e-02\n 1....,0,0,0,0,0,0,0,0,0
4845,"Sales in Finland decreased by 10.5 % in January , while sales outside Finland dropped by 17 % .",0,[-2.11000890e-01 3.38408977e-01 2.79511586e-02 -6.04719371e-02\n 1.00033201e-01 -1.23005114e-01 -2.58821696e-02 -3.29742618e-02\n 2.08791532e-02 1.56804836e+00 -3.97868901e-01 1.73305854e-01\n -1.92171901e-01 3.62741612e-02 -4.00141208e-03 -1.44216970e-01\n 8.82210955e-02 1.20483148e+00 -1.19249322e-01 -2.27035824e-02\n -7.42047001e-03 2.96443445e-03 4.77242656e-02 -5.48094772e-02\n 4.66798693e-02 -3.94312143e-02 -1.53847948e-01 6.67186901e-02\n -3.74379009e-02 5.33582866e-02 -5.51761575e-02 -1.21744961e-01\n -1.30150259e-01 6.22810051e-02 4.27318439e-02 9.83037148e-03\n -2.44952291e-02 -3.26079540e-02 1.40232638e-01 -1.30875155e-01\n 1.03321888e-01 -7.45608285e-02 1.20164745e-01 1.58372801e-02\n 2.28052661e-02 8.12419355e-02 4.02745716e-02 -6.35905340e-02\n 1....,0,0,0,0,0,0,0,0,0

In [5]:
model_col_names = compare_y_vs_yhats_df.columns.to_list()[3:]
model_col_names, len(model_col_names)

(['perceptron',
  'sgd_classifier',
  'logistic_regression',
  'ridge_classifier',
  'decision_tree_classifier',
  'random_forest_classifier',
  'gradient_boosting_classifier',
  'support_vector_machine_classifier',
  'x_gradient_boosting_classifier'],
 9)

# Fleiss Kappa

In [6]:
kappa, freq_table, df = EvaluationMetric.get_fleiss_kappa(compare_y_vs_yhats_df, model_col_names, per_row_agreement=True, per_row_entropy=True)
kappa

np.float64(0.584504172677864)

In [7]:
freq_table

Value            0  1
Subject to Rate
0                1  8
1                3  6
2                0  9
3                8  1
4                7  2
...             .. ..
4841             8  1
4842             8  1
4843             9  0
4844             9  0
4845             9  0

[4846 rows x 2 columns]

In [8]:
df

,Base Sentence,Sentence Label,Base Sentence Embedding,perceptron,sgd_classifier,logistic_regression,ridge_classifier,decision_tree_classifier,random_forest_classifier,gradient_boosting_classifier,support_vector_machine_classifier,x_gradient_boosting_classifier,Per Row Agreement,Per Row Entropy
0,With the new production plant the company would increase its capacity to meet the expected increase in demand and would improve the use of raw materials and therefore increase the production profitability .,1,[-1.22568220e-01 2.48624131e-01 -4.82655168e-02 -1.09789923e-01\n -8.58348906e-02 3.63291465e-02 -1.27964811e-02 7.17335939e-02\n -1.18364163e-01 2.27930522e+00 -3.32476139e-01 -1.46164745e-02\n 1.25499114e-01 7.25146085e-02 6.57393187e-02 -5.76901138e-02\n -2.05907249e-03 1.51917112e+00 -3.29480022e-01 -4.57408801e-02\n 2.22120117e-02 1.05339624e-01 -4.22692373e-02 -1.23566784e-01\n -5.79119613e-03 6.18153140e-02 -5.48806489e-02 2.96797305e-02\n -1.07008472e-01 -9.98812243e-02 -9.39770564e-02 3.87728140e-02\n -5.82127571e-02 7.14930072e-02 9.65250358e-02 -3.75642404e-02\n 7.18023349e-03 6.21852428e-02 7.68979266e-02 -1.69069305e-01\n 1.44475931e-03 7.71993026e-02 3.41709815e-02 -1.10992551e-01\n -1.81387588e-02 -8.61631632e-02 -2.34903637e-02 6.00658916e-02\n -3....,1,1,1,1,0,1,1,1,1,0.888889,0.503258
1,"According to the company 's updated strategy for the years 2009-2012 , Basware targets a long-term net sales growth in the range of 20 % -40 % with an operating profit margin of 10 % -20 % of net sales .",1,[-2.63320029e-01 3.28540474e-01 4.48558182e-02 -1.09422831e-02\n 3.39385755e-02 -1.25387803e-01 2.09340192e-02 8.32975954e-02\n 1.10356383e-01 1.74510765e+00 -3.98153275e-01 1.41264707e-01\n -8.98099765e-02 -1.47727029e-02 5.77163734e-02 -5.09223454e-02\n -4.27257568e-02 1.41277170e+00 -2.09747717e-01 1.56779997e-02\n -3.64826852e-03 5.97854443e-02 -7.89400712e-02 -1.39893517e-02\n 1.13595366e-01 9.83026922e-02 -5.14178127e-02 7.06899390e-02\n 2.47105230e-02 1.06609218e-01 -4.19648038e-03 -1.85196903e-02\n -1.48957130e-02 9.90139246e-02 1.10973224e-01 -2.59710420e-02\n -6.08825274e-02 4.48305123e-02 4.36691009e-02 -9.27021950e-02\n 6.36729002e-02 1.98753644e-02 2.10891932e-01 -8.54000822e-02\n 4.67465706e-02 -2.04764325e-02 -3.69948000e-02 1.16207667e-01\n 1....,1,1,0,0,1,1,1,0,1,0.666667,0.918296
2,TeliaSonera TLSN said the offer is in line with its strategy to increase its ownership in core business holdings and would strengthen Eesti Telekom 's offering to its customers .,1,[ 1.15080299e-02 1.98225155e-01 1.95062440e-02 -5.97744621e-02\n 1.75585955e-01 -1.25474662e-01 -3.72287892e-02 -2.83286646e-02\n -3.56662273e-02 1.96045303e+00 -2.79843062e-01 -1.04898110e-01\n 4.49508205e-02 1.31481076e-02 6.55795187e-02 -4.11130209e-03\n -5.56710083e-03 1.11790729e+00 -1.21459611e-01 -9.75316912e-02\n 2.18506586e-02 1.38311490e-01 9.17155594e-02 -5.85136563e-02\n 1.03342809e-01 7.32071251e-02 -3.92427929e-02 1.13294438e-01\n -1.07247204e-01 5.58346435e-02 -9.28281173e-02 5.48683619e-03\n -1.84886660e-02 5.24056628e-02 4.05881368e-02 -8.35432187e-02\n 1.13391867e-02 2.78038122e-02 -5.44880610e-03 -1.02035753e-01\n -6.69988245e-02 7.79658780e-02 5.37769347e-02 -1.39616817e-01\n 2.96867881e-02 1.13102477e-02 -3.53476144e-02 -1.88835058e-02\n -4....,1,1,1,1,1,1,1,1,1,1.000000,-0.000000
3,"STORA ENSO , NORSKE SKOG , M-REAL , UPM-KYMMENE Credit Suisse First Boston ( CFSB ) raised the fair value for shares in four of the largest Nordic forestry groups .",1,[-5.94305294e-03 1.57299116e-01 -1.01663664e-01 -4.74716797e-02\n 1.79840446e-01 2.63532978e-02 4.07044962e-02 -3.17418873e-02\n -1.32127828e-03 1.28309309e+00 -3.01563025e-01 4.19499092e-02\n 4.76229452e-02 -1.16947450e-01 -1.42535036e-02 2.37643998e-02\n -3.57760116e-02 8.38545859e-01 -5.43218441e-02 2.42432952e-03\n 7.67285563e-03 4.88467440e-02 4.74129207e-02 -2.67546187e-04\n 6.47759363e-02 7.66171236e-03 -7.71588413e-03 6.14660196e-02\n 9.25298501e-03 1.29891783e-01 6.76145032e-02 -7.35822739e-03\n 3.22291143e-02 1.50113806e-01 1.32441163e-01 -9.81159508e-03\n -1.39411157e-02 1.04931206e-03 -1.90248825e-02 -9.27351974e-03\n -2.62032263e-02 7.86117762e-02 8.33134279e-02 2.64521260e-02\n -1.58701912e-02 9.79095325e-03 3.53994928e-02 -1.72072705e-02\n 7....,0,0,0,0,1,0,0,0,0,0.888889,0.503258
4,The company also estimates the already carried out investments to lead to an increase in its net sales for 2010 from 2009 when they reached EUR 141.7 million .,1,[-9.75671411e-02 2.17742935e-01 -5.24893478e-02 2.29859371e-02\n 1.95262451e-02 -3.96593288e-02 -2.93270722e-02 1.45730842e-02\n 8.01267326e-02 2.14558053e+00 -3.02207738e-01 7.73812085e-02\n 9.75400433e-02 -5.86019419e-02 2.85570417e-02 -6.01695329e-02\n -6.48141513e-03 1.10976875e+00 -1.62209153e-01 -2.63800696e-02\n 6.90186918e-02 5.40496930e-02 -4.89046909e-02 -1.06065851e-02\n 3.81638743e-02 8.63624960e-02 -1.46540195e-01 -7.51399994e-02\n -5.42312972e-02 -2.43689902e-02 3.15490589e-02 -7.77387097e-02\n -1.04405805e-01 1.55526847e-01 2.55947262e-02 -2.01004483e-02\n -4.33546826e-02 2.11381875e-02 9.09157470e-02 -9.94266123e-02\n -5.63282613e-03 7.87854865e-02 1.45106107e-01 -1.49363369e-01\n 2.86051352e-02 -9.17335041e-03 -3.88870686e-02 -1.43906018e-02\n 2....,1,0,0,0,1,0,0,0,0,0.777778,0.764205
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4841,LONDON MarketWatch -- Share prices ended lower in London Monday as a rebound in bank stocks failed to offset broader weakness for the FTSE 100 .,0,[-9.97306556e-02 1.64349496e-01 1.71351619e-02 7.13192746e-02\n 1.75899908e-01 -1.15603261e-01 -8.73757303e-02 -3.37601155e-02\n 5.58915287e-02 1.69525981e+00 -4.03638840e-01 3.41098830e-02\n 1.48271397e-01 -5.36716953e-02 4.27423716e-02 3.00230049e-02\n -4.06325832e-02 1.12422264e+00 -4.39298190e-02 1.07508982e-02\n -7.20263198e-02 5.96804582e-02 4.38548550e-02 -1.71869665e-01\n 5.18397167e-02 1.47482648e-01 -3.61646675e-02 8.63183811e-02\n -4.57509570e-02 6.86240196e-02 -7.81383812e-02 6.77803857e-03\n 1.96492635e-02 3.25613059e-02 8.09665844e-02 1.05558559e-01\n 1.15658459e-03 3.71128581e-02 -1.13167958e-02 -6.61973208e-02\n -1.17063336e-02 -1.49593409e-02 1.30228832e-01 1.75232589e-02\n 3.42527404e-02 4.42111705e-05 1.07453475e-02 -6.22191653e-02\n 2....,0,0,0,0,0,0,1,0,0,0.888889,0.503258
4842,"Rinkuskiai 's beer sales fell by 6.5 per cent to 4.16 million litres , while Kauno Alus ' beer sales jumped by 6.9 per cent to 2.48 million litres .",0,[-1.98924989e-01 3.00148040e-01 1.01390548e-01 -1.25840604e-01\n 3.24619608e-03 -1.00019135e-01 -1.24527112e-01 -5.24022356e-02\n 1.37367668e-02 1.35610378e+00 -2.27968454e-01 1.58202261e-01\n -7.28038773e-02 -4.16742004e-02 1.74741030e-01 -2.46515095e-01\n 3.43543403e-02 9.48214471e-01 -9.90116820e-02 -1.46733001e-01\n -5.03083616e-02 7.97276795e-02 2.76607871e-02 2.14223936e-02\n 8.79974142e-02 -9.17081013e-02 -1.13138795e-01 5.91326691e-02\n 1.20140046e-01 -3.84076685e-02 -3.18211094e-02 -1.06555417e-01\n -4.91127931e-02 -3.66714634e-02 2.47359928e-03 -6.18500356e-03\n -1.42085582e-01 -3.00514344e-02 5.16138040e-02 3.66412327e-02\n -6.68754056e-02 -4.96820062e-02 1.96969017e-01 -2.14436855e-02\n 3.49904411e-02 8.42073932e-02 5.88495322e-02 2.23803204e-02\n -1....,0,0,0,0,1,0,0,0,0,0.888889,0.503258
4843,"Operating profit fell to EUR 35.4 mn from EUR 68.8 mn in 2007 , including vessel sales gain of EUR 12.3 mn .",0,[-1.26625523e-01 2.81394184e-01 1.47076428e-01 -8.27063471e-02\n 1.89998314e-01 -1.95341870e-01 4.09874618e-02 4.50612567e-02\n 1.91018894e-01 1.17237604e+00 -3.50073159e-01 1.32276177e-01\n 1.80098731e-02 -3.21719684e-02 1.55063599e-01 -1.11439444e-01\n 5.50558940e-02 1.04285705e+00 -1.20266512e-01 4.59595509e-02\n 1.10065266e-01 5.54235131e-02 -1.12656087e-01 -1.29508138e-01\n 1.33550599e-01 9.51396152e-02 -5.79518043e-02 -1.48020387e-01\n -5.75628951e-02 1.92942038e-01 5.40777408e-02 -1.02687180e-01\n -9.71201211e-02 7.68551379e-02 1.51430340e-02 -7.59296939e-02\n -1.33880302e-01 -6.48121685e-02 8.27361941e-02 1.65923476e-01\n -6.65841550e-02 -5.17907441e-02 1.25316873e-01 -8.98319855e-02\n -1.09120391e-01 8.51464048e-02 9.52818319e-02 8.35352391e-02\n 2....,0,0,0,0,0,0,0,0,0,1.000000,-0.000000
4844,"Net sales of the Paper segment decreased to EUR 221.6 mn in the second quarter of 2009 from EUR 241.1 mn in the second quarter of 2008 , while operating profit excluding non-recurring items rose to EUR 8.0 mn from EUR 7.6 mn .",0,[-1.32034168e-01 2.24063978e-01 3.11533064e-02 1.04350876e-02\n 1.56703591e-01 -1.01873629e-01 2.23107524e-02 5.80221787e-02\n 1.09591357e-01 1.37637448e+00 -3.08786511e-01 6.17817082e-02\n 9.21739489e-02 -4.09597717e-02 1.86670780e-01 -2.55621858e-02\n 5.35475016e-02 1.13686538e+00 -8.73383507e-02 -2.77639553e-02\n 4.91071157e-02 6.25430942e-02 -9.91906524e-02 -4.09849957e-02\n 1.23337105e-01 8.61576125e-02 -1.24529265e-01 -8.46296623e-02\n -1.07371166e-01 1.51070386e-01 1.05449930e-02 -4.81814779e-02\n -1.36766464e-01 9.01109204e-02 2.72464938e-02 1.43071718e-03\n -1.20931201e-01 2.54633697e-03 1.08788302e-02 3.64606492e-02\n 3.07067460e-03 8.49255845e-02 1.09374307e-01 -5.65562025e-02\n -2.14073937e-02 4.81035821e-02 1.16443343e-01 5.90736568e-02\n 1....,0,0,0,0,0,0,0,0,0,1.000000,-0.000000
4845,"Sales in Finland decreased by 10.5 % in January , while sales outside Finland dropped by 17 % .",0,[-2.11000890e-01 3.38408977e-01 2.79511586e-02 -6.04719371e-02\n 1.00033201e-01 -1.23005114e-01 -2.58821696e-02 -3.29742618e-02\n 2.08791532e-02 1.56804836e+00 -3.97868901e-01 1.73305854e-01\n -1.92171901e-01 3.62741612e-02 -4.00141208e-03 -1.44216970e-01\n 8.82210955e-02 1.20483148e+00 -1.19249322e-01 -2.27035824e-02\n -7.42047001e-03 2.96443445e-03 4.77242656e-02 -5.48094772e-02\n 4.66798693e-02 -3.94312143e-02 -1.53847948e-01 6.67186901e-02\n -3.74379009e-02 5.33582866e-02 -5.51761575e-02 -1.21744961e-01\n -1.30150259e-01 6.22810051e-02 4.27318439e-02 9.83037148e-03\n -2.44952291e-02 -3.26079540e-02 1.40232638e-01 -1.30875155e-01\n 1.03321888e-01 -7.45608285e-02 1.20164745e-01 1.58372801e-02\n 2.28052661e-02 8.12419355e-02 4.02745716e-02 -6.35905340e-02\n 1....,0,0,0,0,0,0,0,0,0,1.000000,-0.000000

## Agreement vs Accuracy

In [9]:
df.sort_values('Per Row Agreement')

,Base Sentence,Sentence Label,Base Sentence Embedding,perceptron,sgd_classifier,logistic_regression,ridge_classifier,decision_tree_classifier,random_forest_classifier,gradient_boosting_classifier,support_vector_machine_classifier,x_gradient_boosting_classifier,Per Row Agreement,Per Row Entropy
1608,"More than 200 volunteers from Fiskars , the garden tool company , Home Depot ( NYSE : HD ) , the city of Baltimore and the neighborhood are working right now to create a garden sanctuary - in a single day .",0,[ 7.33330622e-02 1.70536935e-01 -1.05055071e-01 -9.27682891e-02\n 1.16301388e-01 -2.94546802e-02 -8.43675584e-02 -6.58421665e-02\n -1.20317480e-02 1.92156053e+00 -2.59946615e-01 -1.78106111e-02\n 7.36174267e-03 -1.50048792e-01 -9.99810025e-02 6.83083315e-04\n -9.91168246e-02 1.28165269e+00 -9.15850028e-02 -5.38569801e-02\n -7.41658956e-02 2.42707692e-02 -4.58216900e-03 -3.72172855e-02\n 5.48002832e-02 2.08101403e-02 -2.74861418e-02 7.09659560e-03\n 8.13909769e-02 3.58131267e-02 8.44486207e-02 2.68686730e-02\n -3.38754691e-02 1.12683013e-01 1.47177428e-01 -1.60475150e-02\n -3.07587776e-02 3.41642350e-02 -2.47308817e-02 -3.36268693e-02\n -4.06011157e-02 1.32395297e-01 5.91087900e-03 -6.08450100e-02\n -1.63931977e-02 1.38296541e-02 -1.23775356e-01 -6.07134327e-02\n -2....,1,0,0,0,1,0,1,0,1,0.555556,0.991076
2454,Glaston also has efficiency measures in all other units .,0,[-5.44147305e-02 2.81955004e-01 3.26600000e-02 -2.52683997e-01\n -6.09933063e-02 -1.47656202e-01 -3.74872983e-02 -7.77665973e-02\n 2.63455920e-02 1.92757988e+00 -1.29553407e-01 1.74676180e-02\n 6.34661019e-02 -1.66434795e-01 -5.77557012e-02 1.61574986e-02\n 1.18946299e-01 1.39123893e+00 -3.11110616e-01 -8.83898064e-02\n -1.47491187e-01 6.43514022e-02 6.73142001e-02 -1.01677395e-01\n 3.67385000e-02 5.16016968e-02 -8.59215036e-02 -2.02491004e-02\n -6.74302876e-02 -1.51215177e-02 -4.23020031e-03 -2.73193773e-02\n -6.83227926e-02 1.56509578e-02 3.03589012e-02 -2.03596503e-01\n -2.83755958e-02 3.78564000e-02 -2.22252011e-02 -1.24170110e-01\n -8.10137987e-02 2.69373003e-02 3.95515002e-02 -6.81006089e-02\n 6.01615384e-02 6.21043965e-02 -6.48890063e-02 9.21756029e-02\n -7....,1,1,0,1,0,0,0,1,0,0.555556,0.991076
3882,The contract value amounts to EUR 2.4 million .,0,[-8.44723359e-02 2.42537335e-01 -6.19784407e-02 8.61356035e-03\n -2.07242221e-02 -9.54612121e-02 -1.20998412e-01 -9.38423723e-02\n 1.49799556e-01 1.64396560e+00 -2.95026451e-01 2.23468989e-01\n 1.78099453e-01 7.19385520e-02 1.36371523e-01 -1.08036324e-01\n -1.19739681e-01 1.36112881e+00 -8.06920454e-02 -7.97697753e-02\n 7.11305588e-02 2.05949191e-02 -9.80700031e-02 -7.69026577e-02\n -2.64662169e-02 -2.55054943e-02 -1.89908162e-01 -8.35453346e-02\n -1.09233363e-02 5.71729951e-02 3.41438130e-02 -8.99034441e-02\n 3.80022125e-03 8.48700926e-02 8.69457796e-02 -4.57578897e-02\n -4.19744523e-03 -1.04036503e-01 -3.01163271e-02 1.46020338e-01\n 3.02903317e-02 1.73600674e-01 2.45469302e-01 -6.25775680e-02\n -2.48308480e-01 -7.61114061e-02 -2.56793275e-02 1.89318601e-02\n -1....,1,1,1,0,0,1,0,0,0,0.555556,0.991076
3405,The Notice in its entirety with other proposals from the Nomination Committee and the Board will be published at least four weeks before 28 April on the company 's website and in Post - och Inrikes Tidningar and Dagens Industri .,0,[ 1.02807314e-03 7.56883249e-02 9.53746121e-03 -1.54629247e-02\n -2.15468872e-02 4.22595702e-02 2.70982254e-02 -1.48251712e-01\n 7.48778582e-02 1.97362924e+00 -2.75078624e-01 1.99439004e-02\n 5.03618829e-02 -9.42621976e-02 -4.70406376e-02 -2.61814091e-02\n -9.61461011e-03 9.39250112e-01 -9.56600681e-02 -5.24881482e-02\n 3.37991305e-02 8.68598744e-03 -3.50362062e-02 -8.88782293e-02\n 8.23030993e-02 1.08665571e-01 -1.25181958e-01 -4.69130464e-02\n -5.17236665e-02 3.10851950e-02 -2.84404587e-02 9.42103341e-02\n -6.11502379e-02 1.20129503e-01 -2.48949304e-02 -5.74668385e-02\n -7.01584518e-02 2.66484320e-02 -2.34509557e-02 -1.62413865e-02\n -4.10941318e-02 1.15074962e-01 -8.46722275e-02 -6.62047341e-02\n -2.22615376e-02 4.50724326e-02 -7.23193064e-02 -2.55251452e-02\n 2....,1,1,1,1,0,0,0,1,0,0.555556,0.991076
4373,"The contract also includes cutting and edging wagon parts at Ruukki 's steel service centres in Seinajoki and Raahe , from where they will be delivered to VR for welding and assembly .",0,[ 6.19654022e-02 1.86650783e-01 2.76827849e-02 -8.36778209e-02\n 1.68344751e-01 -1.10338189e-01 5.29852398e-02 2.13227482e-04\n -9.96541530e-02 1.79654694e+00 -9.15710554e-02 3.01406682e-02\n 6.57109395e-02 -1.23633198e-01 -1.29536077e-01 -7.00297728e-02\n -3.38413045e-02 1.27066100e+00 -1.55938223e-01 -5.51118050e-03\n -4.98338379e-02 -3.72138955e-02 -6.57847524e-02 -5.66448830e-02\n 3.78533453e-02 8.39823857e-02 -1.14473879e-01 -1.06554389e-01\n -1.88998524e-02 -1.49027118e-02 -7.37430304e-02 3.17091122e-03\n -5.76208569e-02 9.51914117e-02 1.33033358e-02 -1.25443175e-01\n -6.08273149e-02 8.11055228e-02 7.09747672e-02 -4.47040908e-02\n -2.58703344e-02 1.35997608e-01 -4.96957963e-03 -8.22305530e-02\n 5.39481547e-03 1.37534989e-02 -1.17660977e-01 -1.21246673e-01\n -3....,1,0,0,1,0,0,1,1,1,0.555556,0.991076
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1316,`` The additional flight linking Mumbai with Helsinki was dictated by the strong traffic demand between Asia and Europe .,0,[-6.74781874e-02 6.17626160e-02 -9.22389999e-02 -5.91843799e-02\n 2.47571349e-01 1.03154764e-01 -4.83266590e-03 7.19318241e-02\n -3.49019580e-02 1.75506139e+00 -3.31094205e-01 -9.55263749e-05\n 4.07504775e-02 7.65890926e-02 -6.46592677e-02 -9.18357596e-02\n -1.44960821e-01 1.17060614e+00 4.10555936e-02 -4.49290761e-04\n 2.47628577e-02 6.14247099e-02 -1.46741383e-02 3.69437598e-03\n 8.54226947e-02 -8.59165266e-02 -5.44854812e-02 2.05872860e-02\n -1.54892663e-02 1.17592469e-01 1.74677875e-02 3.83309163e-02\n 5.10295182e-02 1.00410283e-01 1.48180975e-02 -3.43048610e-02\n 8.91220011e-03 3.53915766e-02 -6.58184662e-02 -1.08028241e-01\n 1.24745436e-01 -1.06662944e-01 -1.93862785e-02 -1.28462866e-01\n -2.10933797e-02 -7.25929067e-02 -3.73739488e-02 -1.12009741e-01\n -7....,0,0,0,0,0,0,0,0,0,1.000000,-0.000000
1318,"`` The new structure provides better communication , faster decision-making and cost savings , '' Proha said .",0,[-1.67575926e-01 2.89347738e-01 -8.41348544e-02 -1.12778082e-01\n 9.52482820e-02 6.63067773e-02 4.29923087e-02 -9.30637270e-02\n -4.32444327e-02 1.79503489e+00 -1.63219571e-01 7.36489668e-02\n 1.19787760e-01 4.24017832e-02 -1.45271808e-01 -1.19477637e-01\n -1.37608692e-01 1.32550275e+00 -2.07878470e-01 -1.54899713e-03\n -8.75990912e-02 1.25338003e-01 1.35474745e-02 -1.10898390e-01\n 7.19951466e-02 5.69650494e-02 1.53390113e-02 -5.80634847e-02\n 1.14742689e-01 -1.17068566e-01 -1.10342965e-01 -3.97571400e-02\n 1.01906799e-01 1.83048658e-02 1.10283308e-01 -9.55005735e-02\n 5.49211204e-02 8.23904425e-02 -2.79828086e-02 -1.14264145e-01\n 2.08368879e-02 -3.89914736e-02 9.18735042e-02 -1.05962887e-01\n -8.97831991e-02 -6.20216765e-02 -1.28038853e-01 -9.49390978e-02\n -4....,1,1,1,1,1,1,1,1,1,1.000000,-0.000000
3246,"Stockholm , 3 March 2011 About Cybercom The Cybercom Group is a high-tech consultancy that offers global sourcing for end-to-end solutions .",0,[-6.17026910e-02 3.15032303e-01 -2.09554229e-02 4.51530404e-02\n 2.33328819e-01 -6.68910667e-02 6.96154907e-02 -1.64092332e-03\n -1.75691713e-02 1.60597670e+00 -3.12905282e-01 -1.91640425e-02\n 5.33392839e-02 -8.91074091e-02 -1.40833274e-01 -4.21882048e-02\n -2.49918662e-02 1.24201703e+00 -7.71285444e-02 5.70071749e-02\n 1.79647189e-02 2.74232533e-02 2.86985887e-03 -6.03288375e-02\n 5.13633415e-02 8.19584280e-02 -2.99005508e-02 2.77020801e-02\n 9.24107712e-03 8.19484964e-02 1.34983687e-02 5.94468974e-02\n 3.54548879e-02 1.15115143e-01 1.30710289e-01 1.51113803e-02\n 2.02055592e-02 3.76544781e-02 -1.53413815e-02 -1.37166634e-01\n 1.18324850e-02 4.57948707e-02 6.36628568e-02 -1.28626958e-01\n -4.81350794e-02 3.10167279e-02 -9.27141905e-02 -8.07479862e-03\n -1....,1,1,1,1,1,1,1,1,1,1.000000,-0.000000
1299,"The original name Componenta +_m+_l , as a subsidiary of the Finnish Componenta Group , has been changed to +_m+_l Components and the company has seen a 63 % growth in Q1 2010 , in comparison to Q1 2009 .",0,[-3.23984772e-02 1.68068036e-01 -1.09308787e-01 -9.06792134e-02\n 8.56325105e-02 5.45185581e-02 1.72077343e-02 -3.99987139e-02\n -4.72221412e-02 1.53599966e+00 -2.48542681e-01 8.10818896e-02\n 4.55994941e-02 -3.00073698e-02 1.14775030e-02 -3.95212732e-02\n -9.36259925e-02 1.13931572e+00 -1.73073500e-01 -3.20621394e-02\n -7.43999658e-03 4.05395217e-02 -3.64012979e-02 -2.09243763e-02\n 1.67893879e-02 7.61772990e-02 -7.20326826e-02 -1.69702992e-03\n 7.75978640e-02 1.20573565e-01 6.35174941e-03 1.92680489e-02\n 2.27563170e-04 9.28264856e-02 8.56278688e-02 -4.23721336e-02\n 3.46819758e-02 1.26826614e-02 -2.31371392e-02 -1.50739804e-01\n 4.66624461e-02 8.79886299e-02 1.57490790e-01 -1.48510281e-02\n -2.62475256e-02 -3.50089557e-02 5.16027026e-03 -3.02658919e-02\n 6....,0,0,0,0,0,0,0,0,0,1.000000,-0.000000
4845,"Sales in Finland decreased by 10.5 % in January , while sales outside Finland dropped by 17 % .",0,[-2.11000890e-01 3.38408977e-01 2.79511586e-02 -6.04719371e-02\n 1.00033201e-01 -1.23005114e-01 -2.58821696e-02 -3.29742618e-02\n 2.08791532e-02 1.56804836e+00 -3.97868901e-01 1.73305854e-01\n -1.92171901e-01 3.62741612e-02 -4.00141208e-03 -1.44216970e-01\n 8.82210955e-02 1.20483148e+00 -1.19249322e-01 -2.27035824e-02\n -7.42047001e-03 2.96443445e-03 4.77242656e-02 -5.48094772e-02\n 4.66798693e-02 -3.94312143e-02 -1.53847948e-01 6.67186901e-02\n -3.74379009e-02 5.33582866e-02 -5.51761575e-02 -1.21744961e-01\n -1.30150259e-01 6.22810051e-02 4.27318439e-02 9.83037148e-03\n -2.44952291e-02 -3.26079540e-02 1.40232638e-01 -1.30875155e-01\n 1.03321888e-01 -7.45608285e-02 1.20164745e-01 1.58372801e-02\n 2.28052661e-02 8.12419355e-02 4.02745716e-02 -6.35905340e-02\n 1....,0,0,0,0,0,0,0,0,0,1.000000,-0.000000

In [10]:
df.loc[:, ['Base Sentence', 'Sentence Label', 'Per Row Agreement']].sort_values('Per Row Agreement')

,Base Sentence,Sentence Label,Per Row Agreement
1608,"More than 200 volunteers from Fiskars , the garden tool company , Home Depot ( NYSE : HD ) , the city of Baltimore and the neighborhood are working right now to create a garden sanctuary - in a single day .",0,0.555556
2454,Glaston also has efficiency measures in all other units .,0,0.555556
3882,The contract value amounts to EUR 2.4 million .,0,0.555556
3405,The Notice in its entirety with other proposals from the Nomination Committee and the Board will be published at least four weeks before 28 April on the company 's website and in Post - och Inrikes Tidningar and Dagens Industri .,0,0.555556
4373,"The contract also includes cutting and edging wagon parts at Ruukki 's steel service centres in Seinajoki and Raahe , from where they will be delivered to VR for welding and assembly .",0,0.555556
...,...,...,...
1316,`` The additional flight linking Mumbai with Helsinki was dictated by the strong traffic demand between Asia and Europe .,0,1.000000
1318,"`` The new structure provides better communication , faster decision-making and cost savings , '' Proha said .",0,1.000000
3246,"Stockholm , 3 March 2011 About Cybercom The Cybercom Group is a high-tech consultancy that offers global sourcing for end-to-end solutions .",0,1.000000
1299,"The original name Componenta +_m+_l , as a subsidiary of the Finnish Componenta Group , has been changed to +_m+_l Components and the company has seen a 63 % growth in Q1 2010 , in comparison to Q1 2009 .",0,1.000000
4845,"Sales in Finland decreased by 10.5 % in January , while sales outside Finland dropped by 17 % .",0,1.000000

In [11]:
df['Majority Vote'] = df[model_col_names].mode(axis=1)
df

,Base Sentence,Sentence Label,Base Sentence Embedding,perceptron,sgd_classifier,logistic_regression,ridge_classifier,decision_tree_classifier,random_forest_classifier,gradient_boosting_classifier,support_vector_machine_classifier,x_gradient_boosting_classifier,Per Row Agreement,Per Row Entropy,Majority Vote
0,With the new production plant the company would increase its capacity to meet the expected increase in demand and would improve the use of raw materials and therefore increase the production profitability .,1,[-1.22568220e-01 2.48624131e-01 -4.82655168e-02 -1.09789923e-01\n -8.58348906e-02 3.63291465e-02 -1.27964811e-02 7.17335939e-02\n -1.18364163e-01 2.27930522e+00 -3.32476139e-01 -1.46164745e-02\n 1.25499114e-01 7.25146085e-02 6.57393187e-02 -5.76901138e-02\n -2.05907249e-03 1.51917112e+00 -3.29480022e-01 -4.57408801e-02\n 2.22120117e-02 1.05339624e-01 -4.22692373e-02 -1.23566784e-01\n -5.79119613e-03 6.18153140e-02 -5.48806489e-02 2.96797305e-02\n -1.07008472e-01 -9.98812243e-02 -9.39770564e-02 3.87728140e-02\n -5.82127571e-02 7.14930072e-02 9.65250358e-02 -3.75642404e-02\n 7.18023349e-03 6.21852428e-02 7.68979266e-02 -1.69069305e-01\n 1.44475931e-03 7.71993026e-02 3.41709815e-02 -1.10992551e-01\n -1.81387588e-02 -8.61631632e-02 -2.34903637e-02 6.00658916e-02\n -3....,1,1,1,1,0,1,1,1,1,0.888889,0.503258,1
1,"According to the company 's updated strategy for the years 2009-2012 , Basware targets a long-term net sales growth in the range of 20 % -40 % with an operating profit margin of 10 % -20 % of net sales .",1,[-2.63320029e-01 3.28540474e-01 4.48558182e-02 -1.09422831e-02\n 3.39385755e-02 -1.25387803e-01 2.09340192e-02 8.32975954e-02\n 1.10356383e-01 1.74510765e+00 -3.98153275e-01 1.41264707e-01\n -8.98099765e-02 -1.47727029e-02 5.77163734e-02 -5.09223454e-02\n -4.27257568e-02 1.41277170e+00 -2.09747717e-01 1.56779997e-02\n -3.64826852e-03 5.97854443e-02 -7.89400712e-02 -1.39893517e-02\n 1.13595366e-01 9.83026922e-02 -5.14178127e-02 7.06899390e-02\n 2.47105230e-02 1.06609218e-01 -4.19648038e-03 -1.85196903e-02\n -1.48957130e-02 9.90139246e-02 1.10973224e-01 -2.59710420e-02\n -6.08825274e-02 4.48305123e-02 4.36691009e-02 -9.27021950e-02\n 6.36729002e-02 1.98753644e-02 2.10891932e-01 -8.54000822e-02\n 4.67465706e-02 -2.04764325e-02 -3.69948000e-02 1.16207667e-01\n 1....,1,1,0,0,1,1,1,0,1,0.666667,0.918296,1
2,TeliaSonera TLSN said the offer is in line with its strategy to increase its ownership in core business holdings and would strengthen Eesti Telekom 's offering to its customers .,1,[ 1.15080299e-02 1.98225155e-01 1.95062440e-02 -5.97744621e-02\n 1.75585955e-01 -1.25474662e-01 -3.72287892e-02 -2.83286646e-02\n -3.56662273e-02 1.96045303e+00 -2.79843062e-01 -1.04898110e-01\n 4.49508205e-02 1.31481076e-02 6.55795187e-02 -4.11130209e-03\n -5.56710083e-03 1.11790729e+00 -1.21459611e-01 -9.75316912e-02\n 2.18506586e-02 1.38311490e-01 9.17155594e-02 -5.85136563e-02\n 1.03342809e-01 7.32071251e-02 -3.92427929e-02 1.13294438e-01\n -1.07247204e-01 5.58346435e-02 -9.28281173e-02 5.48683619e-03\n -1.84886660e-02 5.24056628e-02 4.05881368e-02 -8.35432187e-02\n 1.13391867e-02 2.78038122e-02 -5.44880610e-03 -1.02035753e-01\n -6.69988245e-02 7.79658780e-02 5.37769347e-02 -1.39616817e-01\n 2.96867881e-02 1.13102477e-02 -3.53476144e-02 -1.88835058e-02\n -4....,1,1,1,1,1,1,1,1,1,1.000000,-0.000000,1
3,"STORA ENSO , NORSKE SKOG , M-REAL , UPM-KYMMENE Credit Suisse First Boston ( CFSB ) raised the fair value for shares in four of the largest Nordic forestry groups .",1,[-5.94305294e-03 1.57299116e-01 -1.01663664e-01 -4.74716797e-02\n 1.79840446e-01 2.63532978e-02 4.07044962e-02 -3.17418873e-02\n -1.32127828e-03 1.28309309e+00 -3.01563025e-01 4.19499092e-02\n 4.76229452e-02 -1.16947450e-01 -1.42535036e-02 2.37643998e-02\n -3.57760116e-02 8.38545859e-01 -5.43218441e-02 2.42432952e-03\n 7.67285563e-03 4.88467440e-02 4.74129207e-02 -2.67546187e-04\n 6.47759363e-02 7.66171236e-03 -7.71588413e-03 6.14660196e-02\n 9.25298501e-03 1.29891783e-01 6.76145032e-02 -7.35822739e-03\n 3.22291143e-02 1.50113806e-01 1.32441163e-01 -9.81159508e-03\n -1.39411157e-02 1.04931206e-03 -1.90248825e-02 -9.27351974e-03\n -2.62032263e-02 7.86117762e-02 8.33134279e-02 2.64521260e-02\n -1.58701912e-02 9.79095325e-03 3.53994928e-02 -1.72072705e-02\n 7....,0,0,0,0,1,0,0,0,0,0.888889,0.503258,0
4,The company also estimates the already carried out investments to lead to an increase in its net sales for 2010 from 2009 when they reached EUR 141.7 million .,1,[-9.75671411e-02 2.17742935e-01 -5.24893478e-02 2.29859371e-02\n 1.95262451e-02 -3.96593288e-02 -2.93270722e-02 1.45730842e-02\n 8.01267326e-02 2.14558053e+00 -3.02207738e-01 7.73812085e-02\n 9.75400433e-02 -5.86019419e-02 2.85570417e-02 -6.01695329e-02\n -6.48141513e-03 1.10976875e+00 -1.62209153e-01 -2.63800696e-02\n 6.90186918e-02 5.40496930e-02 -4.89046909e-02 -1.06065851e-02\n 3.81638743e-02 8.63624960e-02 -1.46540195e-01 -7.51399994e-02\n -5.42312972e-02 -2.43689902e-02 3.15490589e-02 -7.77387097e-02\n -1.04405805e-01 1.55526847e-01 2.55947262e-02 -2.01004483e-02\n -4.33546826e-02 2.11381875e-02 9.09157470e-02 -9.94266123e-02\n -5.63282613e-03 7.87854865e-02 1.45106107e-01 -1.49363369e-01\n 2.86051352e-02 -9.17335041e-03 -3.88870686e-02 -1.43906018e-02\n 2....,1,0,0,0,1,0,0,0,0,0.777778,0.764205,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4841,LONDON MarketWatch -- Share prices ended lower in London Monday as a rebound in bank stocks failed to offset broader weakness for the FTSE 100 .,0,[-9.97306556e-02 1.64349496e-01 1.71351619e-02 7.13192746e-02\n 1.75899908e-01 -1.15603261e-01 -8.73757303e-02 -3.37601155e-02\n 5.58915287e-02 1.69525981e+00 -4.03638840e-01 3.41098830e-02\n 1.48271397e-01 -5.36716953e-02 4.27423716e-02 3.00230049e-02\n -4.06325832e-02 1.12422264e+00 -4.39298190e-02 1.07508982e-02\n -7.20263198e-02 5.96804582e-02 4.38548550e-02 -1.71869665e-01\n 5.18397167e-02 1.47482648e-01 -3.61646675e-02 8.63183811e-02\n -4.57509570e-02 6.86240196e-02 -7.81383812e-02 6.77803857e-03\n 1.96492635e-02 3.25613059e-02 8.09665844e-02 1.05558559e-01\n 1.15658459e-03 3.71128581e-02 -1.13167958e-02 -6.61973208e-02\n -1.17063336e-02 -1.49593409e-02 1.30228832e-01 1.75232589e-02\n 3.42527404e-02 4.42111705e-05 1.07453475e-02 -6.22191653e-02\n 2....,0,0,0,0,0,0,1,0,0,0.888889,0.503258,0
4842,"Rinkuskiai 's beer sales fell by 6.5 per cent to 4.16 million litres , while Kauno Alus ' beer sales jumped by 6.9 per cent to 2.48 million litres .",0,[-1.98924989e-01 3.00148040e-01 1.01390548e-01 -1.25840604e-01\n 3.24619608e-03 -1.00019135e-01 -1.24527112e-01 -5.24022356e-02\n 1.37367668e-02 1.35610378e+00 -2.27968454e-01 1.58202261e-01\n -7.28038773e-02 -4.16742004e-02 1.74741030e-01 -2.46515095e-01\n 3.43543403e-02 9.48214471e-01 -9.90116820e-02 -1.46733001e-01\n -5.03083616e-02 7.97276795e-02 2.76607871e-02 2.14223936e-02\n 8.79974142e-02 -9.17081013e-02 -1.13138795e-01 5.91326691e-02\n 1.20140046e-01 -3.84076685e-02 -3.18211094e-02 -1.06555417e-01\n -4.91127931e-02 -3.66714634e-02 2.47359928e-03 -6.18500356e-03\n -1.42085582e-01 -3.00514344e-02 5.16138040e-02 3.66412327e-02\n -6.68754056e-02 -4.96820062e-02 1.96969017e-01 -2.14436855e-02\n 3.49904411e-02 8.42073932e-02 5.88495322e-02 2.23803204e-02\n -1....,0,0,0,0,1,0,0,0,0,0.888889,0.503258,0
4843,"Operating profit fell to EUR 35.4 mn from EUR 68.8 mn in 2007 , including vessel sales gain of EUR 12.3 mn .",0,[-1.26625523e-01 2.81394184e-01 1.47076428e-01 -8.27063471e-02\n 1.89998314e-01 -1.95341870e-01 4.09874618e-02 4.50612567e-02\n 1.91018894e-01 1.17237604e+00 -3.50073159e-01 1.32276177e-01\n 1.80098731e-02 -3.21719684e-02 1.55063599e-01 -1.11439444e-01\n 5.50558940e-02 1.04285705e+00 -1.20266512e-01 4.59595509e-02\n 1.10065266e-01 5.54235131e-02 -1.12656087e-01 -1.29508138e-01\n 1.33550599e-01 9.51396152e-02 -5.79518043e-02 -1.48020387e-01\n -5.75628951e-02 1.92942038e-01 5.40777408e-02 -1.02687180e-01\n -9.71201211e-02 7.68551379e-02 1.51430340e-02 -7.59296939e-02\n -1.33880302e-01 -6.48121685e-02 8.27361941e-02 1.65923476e-01\n -6.65841550e-02 -5.17907441e-02 1.25316873e-01 -8.98319855e-02\n -1.09120391e-01 8.51464048e-02 9.52818319e-02 8.35352391e-02\n 2....,0,0,0,0,0,0,0,0,0,1.000000,-0.000000,0
4844,"Net sales of the Paper segment decreased to EUR 221.6 mn in the second quarter of 2009 from EUR 241.1 mn in the second quarter of 2008 , while operating profit excluding non-recurring items rose to EUR 8.0 mn from EUR 7.6 mn .",0,[-1.32034168e-01 2.24063978e-01 3.11533064e-02 1.04350876e-02\n 1.56703591e-01 -1.01873629e-01 2.23107524e-02 5.80221787e-02\n 1.09591357e-01 1.37637448e+00 -3.08786511e-01 6.17817082e-02\n 9.21739489e-02 -4.09597717e-02 1.86670780e-01 -2.55621858e-02\n 5.35475016e-02 1.13686538e+00 -8.73383507e-02 -2.77639553e-02\n 4.91071157e-02 6.25430942e-02 -9.91906524e-02 -4.09849957e-02\n 1.23337105e-01 8.61576125e-02 -1.24529265e-01 -8.46296623e-02\n -1.07371166e-01 1.51070386e-01 1.05449930e-02 -4.81814779e-02\n -1.36766464e-01 9.01109204e-02 2.72464938e-02 1.43071718e-03\n -1.20931201e-01 2.54633697e-03 1.08788302e-02 3.64606492e-02\n 3.07067460e-03 8.49255845e-02 1.09374307e-01 -5.65562025e-02\n -2.14073937e-02 4.81035821e-02 1.16443343e-01 5.90736568e-02\n 1....,0,0,0,0,0,0,0,0,0,1.000000,-0.000000,0
4845,"Sales in Finland decreased by 10.5 % in January , while sales outside Finland dropped by 17 % .",0,[-2.11000890e-01 3.38408977e-01 2.79511586e-02 -6.04719371e-02\n 1.00033201e-01 -1.23005114e-01 -2.58821696e-02 -3.29742618e-02\n 2.08791532e-02 1.56804836e+00 -3.97868901e-01 1.73305854e-01\n -1.92171901e-01 3.62741612e-02 -4.00141208e-03 -1.44216970e-01\n 8.82210955e-02 1.20483148e+00 -1.19249322e-01 -2.27035824e-02\n -7.42047001e-03 2.96443445e-03 4.77242656e-02 -5.48094772e-02\n 4.66798693e-02 -3.94312143e-02 -1.53847948e-01 6.67186901e-02\n -3.74379009e-02 5.33582866e-02 -5.51761575e-02 -1.21744961e-01\n -1.30150259e-01 6.22810051e-02 4.27318439e-02 9.83037148e-03\n -2.44952291e-02 -3.26079540e-02 1.40232638e-01 -1.30875155e-01\n 1.03321888e-01 -7.45608285e-02 1.20164745e-01 1.58372801e-02\n 2.28052661e-02 8.12419355e-02 4.02745716e-02 -6.35905340e-02\n 1....,0,0,0,0,0,0,0,0,0,1.000000,-0.000000,0

In [12]:
def classification_of_mv_sentence(df):
    copy_df = df.copy()
    copy_df['Class'] = None

    for idx, row in copy_df.iterrows():
        y = row['Sentence Label']
        y_hat = row['Majority Vote']

        # y = 1 (positive class)
        if y == 1:
            if y_hat == 1:  # TP
                copy_df.loc[idx, 'Class'] = "TP"
            else:  # FN
                copy_df.loc[idx, 'Class'] = "FN"

        # y = 0 (negative class)
        elif y == 0:
            if y_hat == 0:  # TN
                copy_df.loc[idx, 'Class'] = "TN"
            else:  # FP
                copy_df.loc[idx, 'Class'] = "FP"

    return copy_df

In [13]:
mv_with_class_df = classification_of_mv_sentence(df)
mv_with_class_df

,Base Sentence,Sentence Label,Base Sentence Embedding,perceptron,sgd_classifier,logistic_regression,ridge_classifier,decision_tree_classifier,random_forest_classifier,gradient_boosting_classifier,support_vector_machine_classifier,x_gradient_boosting_classifier,Per Row Agreement,Per Row Entropy,Majority Vote,Class
0,With the new production plant the company would increase its capacity to meet the expected increase in demand and would improve the use of raw materials and therefore increase the production profitability .,1,[-1.22568220e-01 2.48624131e-01 -4.82655168e-02 -1.09789923e-01\n -8.58348906e-02 3.63291465e-02 -1.27964811e-02 7.17335939e-02\n -1.18364163e-01 2.27930522e+00 -3.32476139e-01 -1.46164745e-02\n 1.25499114e-01 7.25146085e-02 6.57393187e-02 -5.76901138e-02\n -2.05907249e-03 1.51917112e+00 -3.29480022e-01 -4.57408801e-02\n 2.22120117e-02 1.05339624e-01 -4.22692373e-02 -1.23566784e-01\n -5.79119613e-03 6.18153140e-02 -5.48806489e-02 2.96797305e-02\n -1.07008472e-01 -9.98812243e-02 -9.39770564e-02 3.87728140e-02\n -5.82127571e-02 7.14930072e-02 9.65250358e-02 -3.75642404e-02\n 7.18023349e-03 6.21852428e-02 7.68979266e-02 -1.69069305e-01\n 1.44475931e-03 7.71993026e-02 3.41709815e-02 -1.10992551e-01\n -1.81387588e-02 -8.61631632e-02 -2.34903637e-02 6.00658916e-02\n -3....,1,1,1,1,0,1,1,1,1,0.888889,0.503258,1,TP
1,"According to the company 's updated strategy for the years 2009-2012 , Basware targets a long-term net sales growth in the range of 20 % -40 % with an operating profit margin of 10 % -20 % of net sales .",1,[-2.63320029e-01 3.28540474e-01 4.48558182e-02 -1.09422831e-02\n 3.39385755e-02 -1.25387803e-01 2.09340192e-02 8.32975954e-02\n 1.10356383e-01 1.74510765e+00 -3.98153275e-01 1.41264707e-01\n -8.98099765e-02 -1.47727029e-02 5.77163734e-02 -5.09223454e-02\n -4.27257568e-02 1.41277170e+00 -2.09747717e-01 1.56779997e-02\n -3.64826852e-03 5.97854443e-02 -7.89400712e-02 -1.39893517e-02\n 1.13595366e-01 9.83026922e-02 -5.14178127e-02 7.06899390e-02\n 2.47105230e-02 1.06609218e-01 -4.19648038e-03 -1.85196903e-02\n -1.48957130e-02 9.90139246e-02 1.10973224e-01 -2.59710420e-02\n -6.08825274e-02 4.48305123e-02 4.36691009e-02 -9.27021950e-02\n 6.36729002e-02 1.98753644e-02 2.10891932e-01 -8.54000822e-02\n 4.67465706e-02 -2.04764325e-02 -3.69948000e-02 1.16207667e-01\n 1....,1,1,0,0,1,1,1,0,1,0.666667,0.918296,1,TP
2,TeliaSonera TLSN said the offer is in line with its strategy to increase its ownership in core business holdings and would strengthen Eesti Telekom 's offering to its customers .,1,[ 1.15080299e-02 1.98225155e-01 1.95062440e-02 -5.97744621e-02\n 1.75585955e-01 -1.25474662e-01 -3.72287892e-02 -2.83286646e-02\n -3.56662273e-02 1.96045303e+00 -2.79843062e-01 -1.04898110e-01\n 4.49508205e-02 1.31481076e-02 6.55795187e-02 -4.11130209e-03\n -5.56710083e-03 1.11790729e+00 -1.21459611e-01 -9.75316912e-02\n 2.18506586e-02 1.38311490e-01 9.17155594e-02 -5.85136563e-02\n 1.03342809e-01 7.32071251e-02 -3.92427929e-02 1.13294438e-01\n -1.07247204e-01 5.58346435e-02 -9.28281173e-02 5.48683619e-03\n -1.84886660e-02 5.24056628e-02 4.05881368e-02 -8.35432187e-02\n 1.13391867e-02 2.78038122e-02 -5.44880610e-03 -1.02035753e-01\n -6.69988245e-02 7.79658780e-02 5.37769347e-02 -1.39616817e-01\n 2.96867881e-02 1.13102477e-02 -3.53476144e-02 -1.88835058e-02\n -4....,1,1,1,1,1,1,1,1,1,1.000000,-0.000000,1,TP
3,"STORA ENSO , NORSKE SKOG , M-REAL , UPM-KYMMENE Credit Suisse First Boston ( CFSB ) raised the fair value for shares in four of the largest Nordic forestry groups .",1,[-5.94305294e-03 1.57299116e-01 -1.01663664e-01 -4.74716797e-02\n 1.79840446e-01 2.63532978e-02 4.07044962e-02 -3.17418873e-02\n -1.32127828e-03 1.28309309e+00 -3.01563025e-01 4.19499092e-02\n 4.76229452e-02 -1.16947450e-01 -1.42535036e-02 2.37643998e-02\n -3.57760116e-02 8.38545859e-01 -5.43218441e-02 2.42432952e-03\n 7.67285563e-03 4.88467440e-02 4.74129207e-02 -2.67546187e-04\n 6.47759363e-02 7.66171236e-03 -7.71588413e-03 6.14660196e-02\n 9.25298501e-03 1.29891783e-01 6.76145032e-02 -7.35822739e-03\n 3.22291143e-02 1.50113806e-01 1.32441163e-01 -9.81159508e-03\n -1.39411157e-02 1.04931206e-03 -1.90248825e-02 -9.27351974e-03\n -2.62032263e-02 7.86117762e-02 8.33134279e-02 2.64521260e-02\n -1.58701912e-02 9.79095325e-03 3.53994928e-02 -1.72072705e-02\n 7....,0,0,0,0,1,0,0,0,0,0.888889,0.503258,0,FN
4,The company also estimates the already carried out investments to lead to an increase in its net sales for 2010 from 2009 when they reached EUR 141.7 million .,1,[-9.75671411e-02 2.17742935e-01 -5.24893478e-02 2.29859371e-02\n 1.95262451e-02 -3.96593288e-02 -2.93270722e-02 1.45730842e-02\n 8.01267326e-02 2.14558053e+00 -3.02207738e-01 7.73812085e-02\n 9.75400433e-02 -5.86019419e-02 2.85570417e-02 -6.01695329e-02\n -6.48141513e-03 1.10976875e+00 -1.62209153e-01 -2.63800696e-02\n 6.90186918e-02 5.40496930e-02 -4.89046909e-02 -1.06065851e-02\n 3.81638743e-02 8.63624960e-02 -1.46540195e-01 -7.51399994e-02\n -5.42312972e-02 -2.43689902e-02 3.15490589e-02 -7.77387097e-02\n -1.04405805e-01 1.55526847e-01 2.55947262e-02 -2.01004483e-02\n -4.33546826e-02 2.11381875e-02 9.09157470e-02 -9.94266123e-02\n -5.63282613e-03 7.87854865e-02 1.45106107e-01 -1.49363369e-01\n 2.86051352e-02 -9.17335041e-03 -3.88870686e-02 -1.43906018e-02\n 2....,1,0,0,0,1,0,0,0,0,0.777778,0.764205,0,FN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4841,LONDON MarketWatch -- Share prices ended lower in London Monday as a rebound in bank stocks failed to offset broader weakness for the FTSE 100 .,0,[-9.97306556e-02 1.64349496e-01 1.71351619e-02 7.13192746e-02\n 1.75899908e-01 -1.15603261e-01 -8.73757303e-02 -3.37601155e-02\n 5.58915287e-02 1.69525981e+00 -4.03638840e-01 3.41098830e-02\n 1.48271397e-01 -5.36716953e-02 4.27423716e-02 3.00230049e-02\n -4.06325832e-02 1.12422264e+00 -4.39298190e-02 1.07508982e-02\n -7.20263198e-02 5.96804582e-02 4.38548550e-02 -1.71869665e-01\n 5.18397167e-02 1.47482648e-01 -3.61646675e-02 8.63183811e-02\n -4.57509570e-02 6.86240196e-02 -7.81383812e-02 6.77803857e-03\n 1.96492635e-02 3.25613059e-02 8.09665844e-02 1.05558559e-01\n 1.15658459e-03 3.71128581e-02 -1.13167958e-02 -6.61973208e-02\n -1.17063336e-02 -1.49593409e-02 1.30228832e-01 1.75232589e-02\n 3.42527404e-02 4.42111705e-05 1.07453475e-02 -6.22191653e-02\n 2....,0,0,0,0,0,0,1,0,0,0.888889,0.503258,0,TN
4842,"Rinkuskiai 's beer sales fell by 6.5 per cent to 4.16 million litres , while Kauno Alus ' beer sales jumped by 6.9 per cent to 2.48 million litres .",0,[-1.98924989e-01 3.00148040e-01 1.01390548e-01 -1.25840604e-01\n 3.24619608e-03 -1.00019135e-01 -1.24527112e-01 -5.24022356e-02\n 1.37367668e-02 1.35610378e+00 -2.27968454e-01 1.58202261e-01\n -7.28038773e-02 -4.16742004e-02 1.74741030e-01 -2.46515095e-01\n 3.43543403e-02 9.48214471e-01 -9.90116820e-02 -1.46733001e-01\n -5.03083616e-02 7.97276795e-02 2.76607871e-02 2.14223936e-02\n 8.79974142e-02 -9.17081013e-02 -1.13138795e-01 5.91326691e-02\n 1.20140046e-01 -3.84076685e-02 -3.18211094e-02 -1.06555417e-01\n -4.91127931e-02 -3.66714634e-02 2.47359928e-03 -6.18500356e-03\n -1.42085582e-01 -3.00514344e-02 5.16138040e-02 3.66412327e-02\n -6.68754056e-02 -4.96820062e-02 1.96969017e-01 -2.14436855e-02\n 3.49904411e-02 8.42073932e-02 5.88495322e-02 2.23803204e-02\n -1....,0,0,0,0,1,0,0,0,0,0.888889,0.503258,0,TN
4843,"Operating profit fell to EUR 35.4 mn from EUR 68.8 mn in 2007 , including vessel sales gain of EUR 12.3 mn .",0,[-1.26625523e-01 2.81394184e-01 1.47076428e-01 -8.27063471e-02\n 1.89998314e-01 -1.95341870e-01 4.09874618e-02 4.50612567e-02\n 1.91018894e-01 1.17237604e+00 -3.50073159e-01 1.32276177e-01\n 1.80098731e-02 -3.21719684e-02 1.55063599e-01 -1.11439444e-01\n 5.50558940e-02 1.04285705e+00 -1.20266512e-01 4.59595509e-02\n 1.10065266e-01 5.54235131e-02 -1.12656087e-01 -1.29508138e-01\n 1.33550599e-01 9.51396152e-02 -5.79518043e-02 -1.48020387e-01\n -5.75628951e-02 1.92942038e-01 5.40777408e-02 -1.02687180e-01\n -9.71201211e-02 7.68551379e-02 1.51430340e-02 -7.59296939e-02\n -1.33880302e-01 -6.48121685e-02 8.27361941e-02 1.65923476e-01\n -6.65841550e-02 -5.17907441e-02 1.25316873e-01 -8.98319855e-02\n -1.09120391e-01 8.51464048e-02 9.52818319e-02 8.35352391e-02\n 2....,0,0,0,0,0,0,0,0,0,1.000000,-0.000000,0,TN
4844,"Net sales of the Paper segment decreased to EUR 221.6 mn in the second quarter of 2009 from EUR 241.1 mn in the second quarter of 2008 , while operating profit excluding non-recurring items rose to EUR 8.0 mn from EUR 7.6 mn .",0,[-1.32034168e-01 2.24063978e-01 3.11533064e-02 1.04350876e-02\n 1.56703591e-01 -1.01873629e-01 2.23107524e-02 5.80221787e-02\n 1.09591357e-01 1.37637448e+00 -3.08786511e-01 6.17817082e-02\n 9.21739489e-02 -4.09597717e-02 1.86670780e-01 -2.55621858e-02\n 5.35475016e-02 1.13686538e+00 -8.73383507e-02 -2.77639553e-02\n 4.91071157e-02 6.25430942e-02 -9.91906524e-02 -4.09849957e-02\n 1.23337105e-01 8.61576125e-02 -1.24529265e-01 -8.46296623e-02\n -1.07371166e-01 1.51070386e-01 1.05449930e-02 -4.81814779e-02\n -1.36766464e-01 9.01109204e-02 2.72464938e-02 1.43071718e-03\n -1.20931201e-01 2.54633697e-03 1.08788302e-02 3.64606492e-02\n 3.07067460e-03 8.49255845e-02 1.09374307e-01 -5.65562025e-02\n -2.14073937e-02 4.81035821e-02 1.16443343e-01 5.90736568e-02\n 1....,0,0,0,0,0,0,0,0,0,1.000000,-0.000000,0,TN
4845,"Sales in Finland decreased by 10.5 % in January , while sales outside Finland dropped by 17 % .",0,[-2.11000890e-01 3.38408977e-01 2.79511586e-02 -6.04719371e-02\n 1.00033201e-01 -1.23005114e-01 -2.58821696e-02 -3.29742618e-02\n 2.08791532e-02 1.56804836e+00 -3.97868901e-01 1.73305854e-01\n -1.92171901e-01 3.62741612e-02 -4.00141208e-03 -1.44216970e-01\n 8.82210955e-02 1.20483148e+00 -1.19249322e-01 -2.27035824e-02\n -7.42047001e-03 2.96443445e-03 4.77242656e-02 -5.48094772e-02\n 4.66798693e-02 -3.94312143e-02 -1.53847948e-01 6.67186901e-02\n -3.74379009e-02 5.33582866e-02 -5.51761575e-02 -1.21744961e-01\n -1.30150259e-01 6.22810051e-02 4.27318439e-02 9.83037148e-03\n -2.44952291e-02 -3.26079540e-02 1.40232638e-01 -1.30875155e-01\n 1.03321888e-01 -7.45608285e-02 1.20164745e-01 1.58372801e-02\n 2.28052661e-02 8.12419355e-02 4.02745716e-02 -6.35905340e-02\n 1....,0,0,0,0,0,0,0,0,0,1.000000,-0.000000,0,TN

In [14]:
filt_tp = (mv_with_class_df.sort_values('Per Row Agreement')['Class'] == "TP")
tp_df = mv_with_class_df.sort_values('Per Row Agreement')[filt_tp]
tp_df

,Base Sentence,Sentence Label,Base Sentence Embedding,perceptron,sgd_classifier,logistic_regression,ridge_classifier,decision_tree_classifier,random_forest_classifier,gradient_boosting_classifier,support_vector_machine_classifier,x_gradient_boosting_classifier,Per Row Agreement,Per Row Entropy,Majority Vote,Class
324,Benefon will turn the Salo unit into a B2B business unit and establish a B2C business unit in the UK .,1,[ 3.17047127e-02 2.54010916e-01 2.66646706e-02 -8.98220539e-02\n 2.47216731e-01 -1.41379833e-01 -1.32205874e-01 -2.60502964e-01\n 9.77145731e-02 1.74046540e+00 -2.14166641e-01 -6.69671446e-02\n 5.12699112e-02 -1.01837359e-01 1.07280955e-01 -5.28857075e-02\n -5.17494790e-02 1.32295120e+00 -1.38368502e-01 4.57233340e-02\n 5.04857711e-02 1.68504454e-02 -1.27858907e-01 4.18722294e-02\n 1.18191659e-01 2.87653636e-02 -9.99637246e-02 2.92128581e-03\n 5.54620568e-03 3.99110131e-02 -1.36005521e-01 -3.18131000e-02\n 4.08898517e-02 1.34345606e-01 1.49497494e-01 -1.55318514e-01\n 8.41611028e-02 -1.63055807e-02 -7.12054968e-03 -2.56415755e-01\n 1.02532059e-02 1.80105790e-01 2.71458589e-02 -1.52608365e-01\n -2.19237600e-02 5.51413409e-02 -1.71460006e-02 -9.02438238e-02\n -5....,1,1,1,1,0,0,0,1,0,0.555556,0.991076,1,TP
244,"Fiskars , a 360-year-old global business best known for its orange-handled scissors , expects to derive synergies of EUR5 million a year by consolidating certain parts of the housewares division where the two compete .",1,[-5.43840155e-02 1.83178782e-01 -7.86715448e-02 -8.83297548e-02\n 1.22977711e-01 -9.32820141e-02 -5.76512180e-02 4.80963439e-02\n -3.02713681e-02 1.79774916e+00 -1.50829956e-01 4.71261665e-02\n 1.68358758e-02 -1.20749995e-01 -3.44181769e-02 -7.89736807e-02\n -1.25420894e-02 1.07219005e+00 -8.26019235e-03 2.35656518e-02\n -2.96772420e-02 2.39293352e-02 -4.39278111e-02 -4.43516634e-02\n 1.10149011e-01 2.59316079e-02 -8.03109854e-02 6.64480729e-03\n 4.43488061e-02 7.73969889e-02 2.64088940e-02 1.17111392e-01\n 4.55237813e-02 8.26763138e-02 1.18422069e-01 8.56383983e-03\n 6.45944700e-02 7.40951449e-02 1.97560228e-02 -3.47819254e-02\n -7.26155564e-02 1.55509025e-01 1.06238507e-01 -6.00441024e-02\n 1.45055726e-02 -9.41508729e-03 -7.84238502e-02 -1.18888356e-02\n -1....,1,1,1,1,0,0,0,1,0,0.555556,0.991076,1,TP
294,The optimization of the steel components heating process will reduce the energy consumption .,1,[-1.01751991e-01 3.11783731e-01 9.86715704e-02 -4.65209894e-02\n -2.66848654e-01 3.54909003e-02 9.22392588e-03 9.34863612e-02\n -1.17732346e-01 1.78863716e+00 -3.13360006e-01 -7.00885057e-03\n 1.56394094e-01 -2.85957884e-02 -6.45217821e-02 -1.72120720e-01\n 4.87821689e-03 2.00056410e+00 -3.28441799e-01 4.32697162e-02\n 1.62975281e-01 -5.13662659e-02 -5.68715632e-02 -1.95038289e-01\n -1.12748779e-01 -5.17622493e-02 4.35220040e-02 4.40770350e-02\n -1.81789994e-01 -7.22221518e-03 -6.63548633e-02 -3.56887802e-02\n -6.94968700e-02 1.29899040e-01 1.54005736e-01 -1.90507825e-02\n 1.13671422e-02 7.65635818e-02 2.49082208e-01 -1.71266586e-01\n -9.75828618e-03 1.50945649e-01 -9.28549934e-03 -1.47958919e-01\n -8.86786431e-02 -5.70783578e-02 -1.38887435e-01 -1.45009443e-01\n -1....,1,1,1,1,0,0,0,1,0,0.555556,0.991076,1,TP
290,The company expects net sales to significantly increase from 2009 .,1,[-2.26858437e-01 3.13411713e-01 -8.44321772e-02 -3.14092748e-02\n 1.69444513e-02 -7.11297989e-02 -1.33607723e-02 1.77686345e-02\n 8.56646523e-02 2.15992737e+00 -4.64580655e-01 8.74905065e-02\n 6.60192743e-02 -4.41736449e-03 7.86105469e-02 -9.82092507e-03\n 1.51217524e-02 1.35942173e+00 -1.86223879e-01 3.82578149e-02\n 4.52837460e-02 1.19356729e-01 -4.28434573e-02 -1.98719054e-02\n -1.16397254e-02 1.47624627e-01 -1.71729505e-01 -5.87220415e-02\n -1.12408251e-01 -2.84318607e-02 -6.95631653e-02 -1.29970998e-01\n -1.75088271e-01 1.55306563e-01 4.66129072e-02 1.15940638e-01\n -8.70002657e-02 1.01292759e-01 9.49133635e-02 -2.11028382e-01\n 9.67136398e-02 3.29157226e-02 3.00649732e-01 -4.59294543e-02\n 1.32954530e-02 -9.26422328e-02 1.02711536e-01 4.68556136e-02\n 5....,1,1,1,1,1,0,0,0,0,0.555556,0.991076,1,TP
272,"The 50-50 joint venture , to be called Nokia Siemens Networks , will be comprised of Nokia 's network business group and Siemens ' carrier-related operations , creating estimated synergies of 1.5 billion euros ( $ 1.9 billion ) by 2010 , Nokia said .",1,[-4.26201187e-02 2.99418658e-01 4.40723263e-02 -5.42420372e-02\n 3.36864814e-02 -5.73286898e-02 -8.78636464e-02 -5.16627915e-02\n 1.36070326e-02 1.59678483e+00 -2.69297332e-01 1.11508459e-01\n 1.26454085e-01 -8.50072652e-02 -6.78057149e-02 -4.51867543e-02\n -9.62093323e-02 1.33926857e+00 -1.32417560e-01 -4.11773212e-02\n -3.49836680e-03 1.25418901e-01 -8.69333968e-02 -2.09261049e-02\n 1.41776651e-01 -2.67939437e-02 -1.15492754e-01 -9.62311029e-02\n 1.45969197e-01 8.05974081e-02 7.45382532e-02 -2.84562763e-02\n 3.67162540e-03 1.51152983e-01 -3.63314478e-03 -6.04186952e-02\n -3.83487009e-02 9.29077491e-02 3.18871364e-02 5.00011072e-02\n -6.26747534e-02 1.05902106e-01 1.73040316e-01 2.10643318e-02\n -1.37418792e-01 -1.05550364e-02 -4.90813404e-02 -5.57146333e-02\n -5....,1,1,0,0,0,0,1,1,1,0.555556,0.991076,1,TP
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
333,Karppinen expects the consolidation trend to continue in the Finnish market .,1,[-2.19375025e-02 1.02144919e-01 -9.02965069e-02 1.94116926e-03\n 1.92656949e-01 -2.06337631e-01 5.25471568e-03 3.72944996e-02\n 1.45151675e-01 1.96412182e+00 -4.56138760e-01 -8.49930868e-02\n 1.27252340e-01 8.34346041e-02 2.74621714e-02 -2.55031642e-02\n -5.36920093e-02 1.02792501e+00 -7.09655881e-02 -3.97486649e-02\n 4.72868346e-02 3.79691855e-03 6.02673329e-02 -3.14585008e-02\n -4.54398282e-02 1.60708338e-01 -1.14483416e-01 1.24090826e-02\n -1.43235251e-01 3.07225604e-02 8.46033636e-03 -5.31171672e-02\n 1.11175030e-02 -9.22291633e-03 2.71951675e-01 1.65355299e-02\n 7.32719153e-02 7.14432299e-02 1.06216520e-01 -2.34132055e-02\n -5.66058755e-02 3.26985568e-02 8.92034993e-02 -1.03354752e-01\n -2.94255093e-04 5.26577197e-02 1.84533745e-03 -3.48291211e-02\n -9....,1,1,1,1,1,1,1,1,1,1.000000,-0.000000,1,TP
335,"Kaupthing forecasts that Finnish-Swedish Stora Enso will close its mill in Reisholz , in Germany .",1,[ 4.69210036e-02 2.09595725e-01 -2.49261409e-03 -4.78333309e-02\n 1.64395168e-01 -9.20725465e-02 8.46950039e-02 -1.37623847e-02\n -8.67844746e-03 1.19312048e+00 -3.70380998e-01 -4.40137796e-02\n 3.61039233e-03 -1.05284885e-01 4.29156087e-02 -1.59754939e-02\n 6.02370501e-02 7.91779935e-01 7.97478408e-02 -1.14350453e-01\n 1.45426944e-01 9.51396748e-02 1.62752166e-01 -3.71798351e-02\n -2.62490008e-02 5.07802889e-02 -1.29987895e-01 -3.16227134e-03\n 5.51393926e-02 6.94828928e-02 3.02530024e-02 2.52622366e-03\n -1.19225331e-01 1.28477156e-01 1.00520618e-01 2.39588115e-02\n 1.19423285e-01 6.48626611e-02 -6.40048981e-02 4.86679748e-03\n -4.43671122e-02 8.45528170e-02 2.00200584e-02 3.63442451e-02\n -6.88123927e-02 1.92485973e-02 3.36591676e-02 -1.94217578e-01\n -3....,1,1,1,1,1,1,1,1,1,1.000000,-0.000000,1,TP
337,( A spokesperson told WWD to expect a 50-50 mix of clothing and home decor . ),1,[-3.95202152e-02 2.43004918e-01 -5.81596829e-02 8.12975094e-02\n 9.23523679e-02 -6.06341176e-02 -2.46848650e-02 -1.36139214e-01\n -5.72475940e-02 1.65333211e+00 -2.13354141e-01 5.48796393e-02\n -7.28130415e-02 -5.07659465e-02 -6.36023507e-02 -5.03462143e-02\n -4.16136347e-02 1.05375838e+00 -1.33422017e-01 -5.84656931e-02\n -9.30862650e-02 6.79787472e-02 -5.08136302e-02 -4.03228365e-02\n 8.22425187e-02 -1.73902623e-02 -1.43583342e-01 2.70098634e-02\n 6.41263798e-02 -6.04295842e-02 1.16677899e-02 2.78967991e-02\n -1.78620704e-02 8.83089006e-02 8.71007964e-02 -3.92164700e-02\n -1.37373887e-03 6.09740391e-02 5.49964011e-02 -3.39234583e-02\n 1.15762360e-01 1.18510321e-01 1.58712685e-01 -1.98925018e-01\n 7.08081713e-03 -2.41090590e-03 -1.20706342e-01 7.40677938e-02\n 7....,1,1,1,1,1,1,1,1,1,1.000000,-0.000000,1,TP
340,"Nordstjernan will make the offer in approximately one month , in September 2007 .",1,[-2.26629265e-02 2.86764294e-01 4.10352163e-02 -8.19671303e-02\n 1.33614495e-01 -1.15608215e-01 -4.90760095e-02 -4.04291414e-02\n 9.07040089e-02 2.00720859e+00 -3.08685273e-01 1.46492004e-01\n 1.00847177e-01 -5.30672781e-02 -5.00494242e-02 1.09589333e-02\n -1.18973898e-02 1.19943273e+00 -1.44823894e-01 -9.10091400e-02\n -8.52897093e-02 -6.84030028e-03 2.99071614e-02 -3.48976441e-02\n 8.11697915e-02 2.12426446e-02 -1.64266229e-01 -7.51878694e-02\n 8.20898563e-02 5.58234714e-02 -3.35973389e-02 -4.54345010e-02\n -6.14054464e-02 1.57896608e-01 1.65337101e-02 -7.71542788e-02\n 4.61235642e-04 3.13899554e-02 1.36561515e-02 1.44061102e-02\n -5.66829257e-02 1.10135011e-01 1.28061637e-01 -1.69718891e-01\n -6.37307912e-02 7.01533556e-02 -1.14112414e-01 -1.06948145e-01\n 4....,1,1,1,1,1,1,1,1,1,1.000000,-0.000000,1,TP
315,`` It wo n't happen overnight .,1,[-1.22501768e-01 1.78075001e-01 -2.11360499e-01 -2.12700129e-01\n 2.33933002e-01 7.79333785e-02 -1.06749378e-01 -6.58304989e-02\n 4.23352495e-02 2.10926247e+00 -1.99235871e-01 7.98551738e-02\n 7.26698637e-02 1.75489023e-01 -1.61523744e-01 -7.33201280e-02\n -1.00070164e-01 9.76530075e-01 -1.42450005e-01 1.30448133e-01\n -1.12739243e-01 1.20955795e-01 -5.19781224e-02 1.79789990e-01\n 2.88933758e-02 -4.20721248e-02 -7.17912465e-02 -1.54902369e-01\n 2.73123741e-01 -3.01595867e-01 -2.09134877e-01 -1.16864130e-01\n 8.87878239e-02 -4.51635011e-02 9.87199992e-02 1.17415868e-01\n 3.21246266e-01 2.92808235e-01 -5.10806292e-02 1.25192488e-02\n 1.99389961e-02 -2.00495005e-01 2.10104838e-01 -1.73329622e-01\n 3.56090032e-02 1.05911214e-02 -1.54674754e-01 -1.59627870e-01\n -2....,1,1,1,1,1,1,1,1,1,1.000000,-0.000000,1,TP

In [15]:
filt_fn = (mv_with_class_df.sort_values('Per Row Agreement')['Class'] == "FN")
fn_df = mv_with_class_df.sort_values('Per Row Agreement')[filt_fn]
fn_df

,Base Sentence,Sentence Label,Base Sentence Embedding,perceptron,sgd_classifier,logistic_regression,ridge_classifier,decision_tree_classifier,random_forest_classifier,gradient_boosting_classifier,support_vector_machine_classifier,x_gradient_boosting_classifier,Per Row Agreement,Per Row Entropy,Majority Vote,Class
328,"Fortum expects its annual capital expenditure in the next four to five years to be within a range of EUR 0.8-1 .2 billion , as earlier announced .",1,[ 3.26928683e-02 1.75547540e-01 2.08492968e-02 -3.33412364e-02\n 1.40001252e-01 -1.98151127e-01 -8.25202912e-02 3.76284309e-02\n 7.31529370e-02 1.98778260e+00 -2.61846244e-01 5.66410311e-02\n 7.54261911e-02 -1.03096226e-02 7.15147033e-02 -6.75401613e-02\n 2.58597974e-02 1.16413295e+00 -7.53300041e-02 -3.72618027e-02\n -4.49417345e-02 5.21710366e-02 -1.03509210e-01 -8.56122896e-02\n 4.51312475e-02 2.68220324e-02 -1.51119694e-01 2.90953764e-03\n 4.30858023e-02 1.21889047e-01 -8.13003536e-03 -3.90196890e-02\n 8.28068238e-03 7.12200925e-02 6.58092424e-02 -1.64665319e-02\n 2.77578039e-03 3.17012742e-02 2.21567210e-02 3.48664671e-02\n -1.84658403e-03 8.14495310e-02 1.13700762e-01 -4.73974384e-02\n -8.41988698e-02 -2.80627366e-02 -6.22033663e-02 1.27459271e-02\n -8....,1,1,0,1,0,0,0,1,0,0.555556,0.991076,0,FN
325,Both sources said Nokia would unveil its new phone code-named `` Tube '' on Oct. 2 at an analyst and media event in London .,1,[-5.70019707e-04 1.63759336e-01 -1.60603039e-02 4.50008251e-02\n 2.50451744e-01 6.70751848e-04 6.27807081e-02 -2.01060027e-01\n -6.57054409e-02 1.66100204e+00 -2.72595912e-01 -3.15064602e-02\n 6.57061115e-02 -1.56517103e-01 -1.06657103e-01 -8.55285674e-02\n -7.43746161e-02 1.18078923e+00 -1.33015230e-01 -1.01303414e-01\n -4.72443327e-02 9.93473902e-02 -2.93970983e-02 1.94853719e-03\n 1.64426178e-01 6.90761507e-02 -1.14966616e-01 7.31038908e-03\n 9.92616266e-02 7.30847642e-02 2.65994277e-02 -4.50456403e-02\n 1.35970667e-01 1.41332999e-01 -3.90277966e-03 -3.14897150e-02\n -6.22817455e-03 5.68776503e-02 -5.24910279e-02 -1.06096603e-01\n 1.98341869e-02 -2.03721342e-03 3.66353355e-02 -7.44680241e-02\n -4.98922281e-02 1.60225648e-02 -6.64451793e-02 -1.29067615e-01\n -1....,1,1,1,1,0,0,0,0,0,0.555556,0.991076,0,FN
323,"Based on the design of previous handsets , the Nokia E72 and Nokia E63 this Symbian-based model is promised to offer direct access to over 90 per cent of the world s corporate email through Mail for Exchange and IBM Lotus Notes Traveler .",1,[ 1.97055712e-02 1.52519628e-01 -3.27539295e-02 -2.06458173e-03\n 6.91078678e-02 -2.31530927e-02 4.27214168e-02 -1.21156484e-01\n 5.34274690e-02 1.63638973e+00 -2.67192364e-01 8.31607953e-02\n 2.48427242e-02 -1.09966591e-01 -2.88961772e-02 -7.00337673e-03\n -2.17080161e-01 1.34823954e+00 -1.07127927e-01 -1.25912875e-01\n -6.98572863e-03 6.77475184e-02 -1.32122971e-02 -3.21705826e-02\n 7.61769190e-02 6.73561022e-02 -8.72111320e-02 -8.21944326e-02\n 7.42962360e-02 1.60273835e-01 1.00109309e-01 -5.20569310e-02\n -1.69700366e-02 7.87494928e-02 -1.06126498e-02 -6.62426874e-02\n -1.74583957e-01 -6.87835738e-02 -4.02305834e-02 -7.87044168e-02\n -1.26068965e-01 3.59861888e-02 5.89109138e-02 -8.56912360e-02\n -8.88182148e-02 1.25945091e-01 -5.30048199e-02 7.71032134e-03\n 2....,1,1,1,0,0,0,1,0,0,0.555556,0.991076,0,FN
383,The annual value of the contracts is estimated at USD 2mn over the next three years .,1,[-2.95342915e-02 2.28968993e-01 4.06456068e-02 -1.18348233e-01\n 6.63878843e-02 -1.01279847e-01 -3.31766467e-04 1.31641226e-02\n 1.40690848e-01 2.03194594e+00 -1.63363934e-01 1.13396585e-01\n 1.76325127e-01 -3.62232924e-02 7.51299039e-02 -4.11251048e-03\n -6.25401214e-02 1.10859525e+00 -1.53926596e-01 -7.71225318e-02\n -1.53152901e-03 2.38875989e-02 -1.63890928e-01 1.07250186e-02\n 8.23474079e-02 3.63384783e-02 -2.02299535e-01 -6.95389733e-02\n 4.41429997e-03 1.95722789e-01 1.44336313e-01 -7.22504873e-03\n 1.16366461e-01 1.36247516e-01 6.56481972e-03 4.86636423e-02\n -7.74354115e-02 2.01527681e-02 8.61393809e-02 6.91239387e-02\n -4.30126488e-03 1.48161158e-01 8.36177841e-02 -1.70943066e-01\n -5.81985302e-02 -4.33215834e-02 -1.07462071e-01 -7.49513656e-02\n -1....,1,0,0,1,1,0,0,1,0,0.555556,0.991076,0,FN
376,It is estimated that the consolidated turnover of Kausta Guder will reach Lt 53mn US$ 22.53 mn EUR 15.35 mn in 2007 .,1,[-1.18819959e-01 2.23854348e-01 8.59419182e-02 -1.11924171e-01\n 1.32368475e-01 -9.36144516e-02 3.31544355e-02 1.48114320e-02\n 1.50670394e-01 1.12557435e+00 -2.88352966e-01 6.85278252e-02\n 2.45356075e-02 -6.66298121e-02 6.90485463e-02 -2.88046952e-02\n 6.59996048e-02 8.29284310e-01 -7.12021887e-02 -5.50598688e-02\n 1.13230450e-02 -8.20433535e-03 -2.42446847e-02 -6.67513087e-02\n 9.05213878e-02 9.54721272e-02 -1.41844958e-01 -3.21204998e-02\n -5.78026334e-03 1.21633366e-01 1.52095323e-02 -9.35516134e-02\n -2.69319750e-02 7.62543455e-02 -1.68905612e-02 -2.44831424e-02\n -3.62030864e-02 6.80907518e-02 3.10078450e-02 4.70336303e-02\n 9.77573730e-03 3.92760942e-03 9.46670845e-02 1.89583201e-03\n -1.83385517e-02 -7.70155787e-02 -2.18074210e-03 2.71416549e-03\n -2....,1,0,0,0,1,0,1,0,1,0.555556,0.991076,0,FN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
249,"The estimated turnover of the new company is LVL 2,5 million EEK 40 million .",1,[-1.09045329e-02 3.30839604e-01 -1.87706482e-02 -2.28168160e-01\n -5.81773603e-03 -1.07296973e-01 -2.68594027e-02 1.81513373e-02\n 1.34348378e-01 1.71257472e+00 -2.93339580e-01 4.44942005e-02\n 9.99749973e-02 2.73867324e-02 1.14599600e-01 1.59346666e-02\n 2.14848686e-02 1.18247736e+00 -1.18487738e-01 -1.24887392e-01\n -1.49445971e-02 1.02929831e-01 -1.45172879e-01 -1.48172453e-01\n 1.02266073e-01 -7.74805248e-03 -1.70615003e-01 7.79614085e-03\n 7.05284700e-02 1.24156550e-01 6.77895173e-02 -7.56886676e-02\n -3.30666429e-03 1.32192507e-01 9.24943984e-02 1.01936609e-01\n -1.40759453e-01 1.08817190e-01 1.18044622e-01 5.42925335e-02\n 3.09655331e-02 1.50922671e-01 1.33286625e-01 -1.03411727e-01\n -6.76029921e-02 -9.48458537e-02 -1.50321662e-01 2.47439044e-03\n -6....,0,0,0,0,0,0,0,0,0,1.000000,-0.000000,0,FN
368,"Based on the 2005 calendar year the combined company had EUR15 .8 bn in pro forma annual revenues and is expected to start operations with 60,000 employees .",1,[-5.46246879e-02 1.00728326e-01 4.04572263e-02 -9.34086442e-02\n 8.52317549e-03 -1.13946922e-01 1.69126447e-02 5.19575402e-02\n 1.12505212e-01 1.98530006e+00 -3.49228889e-01 1.13005206e-01\n 4.67283130e-02 -6.14861660e-02 -4.10598982e-03 -5.99017777e-02\n 3.58542940e-03 1.15076852e+00 -1.87894240e-01 2.16009119e-03\n 1.25670005e-02 2.74375081e-02 -9.36296508e-02 4.87486683e-02\n 1.33315474e-01 8.26191381e-02 -2.07006544e-01 -6.28931746e-02\n 1.10863760e-01 2.80408915e-02 -5.82700111e-02 -1.40484408e-01\n -1.74259655e-02 3.39310355e-02 -1.88742485e-02 -1.89466140e-04\n -2.06300188e-02 -9.43599567e-02 3.82653251e-03 -4.92445715e-02\n -2.91317701e-02 9.34525058e-02 2.03939319e-01 -6.49573747e-03\n -2.09716801e-02 3.91709879e-02 -1.54755712e-02 -4.82038185e-02\n -2....,0,0,0,0,0,0,0,0,0,1.000000,-0.000000,0,FN
369,"By the end of 2006 , the number of joint branch offices will total 170 .",1,[ 6.94238171e-02 1.21978745e-01 3.38263735e-02 -9.96856689e-02\n 8.66579264e-02 -7.67649189e-02 -2.97136456e-02 5.32581471e-03\n 7.88938776e-02 2.14697528e+00 -2.63056487e-01 8.98499936e-02\n 1.70133561e-01 -1.79630920e-01 -4.84232828e-02 -1.20122917e-02\n -1.02573939e-01 1.38210952e+00 -8.41551796e-02 -2.93255635e-02\n -1.09209996e-02 6.48265854e-02 -6.92028627e-02 3.30950022e-02\n 8.40703398e-02 -3.57541926e-02 -1.40679136e-01 -5.42518795e-02\n -3.87025364e-02 1.65488943e-01 9.09841582e-02 5.68260737e-02\n -4.56806347e-02 9.30435061e-02 -4.67624608e-03 -7.09286891e-03\n -1.35298878e-01 1.51227415e-01 2.81740222e-02 -4.35903780e-02\n -5.35743162e-02 2.03575656e-01 9.13679376e-02 -4.88918498e-02\n 1.15100682e-01 8.92831106e-03 -4.63579521e-02 7.58985057e-02\n -5....,0,0,0,0,0,0,0,0,0,1.000000,-0.000000,0,FN
377,"Konecranes has previously communicated an estimated reduction of about 1,600 employees on group level in 2009 .",1,[-9.93478820e-02 2.74430215e-01 -5.12495125e-03 -6.65011778e-02\n -8.36602375e-02 3.10758781e-02 -8.24953541e-02 1.71248224e-02\n 7.48742837e-03 2.04251289e+00 -2.31542587e-01 8.19252282e-02\n -1.89704131e-02 -7.54402354e-02 -4.16727969e-03 -6.12613186e-03\n -3.71061265e-04 1.20872402e+00 -2.51262933e-01 -8.53220448e-02\n 1.05994160e-03 1.97700560e-02 -1.67911109e-02 2.24291794e-02\n 9.82625932e-02 -4.74776141e-03 -6.77938759e-02 7.08250925e-02\n 2.69569899e-03 1.46449879e-02 3.55821736e-02 -1.51203433e-02\n 2.33674105e-02 5.91171756e-02 -5.21621667e-02 -1.87339392e-02\n -1.37671068e-01 4.87861186e-02 -5.79202361e-03 -5.68323433e-02\n 8.71488899e-02 6.19448200e-02 6.25257045e-02 -1.55005930e-02\n 2.83422973e-02 -6.94744661e-02 -4.19660583e-02 1.00240037e-02\n 6....,0,0,0,0,0,0,0,0,0,1.000000,-0.000000,0,FN
343,"Subscribers of China Unicom , the nation 's second largest mobile phone operator after China Mobile , are expected to release pictures , videos and blog on the Internet via mobile phones as of March 2008 .",1,[-7.43332952e-02 2.10007906e-01 -8.48207846e-02 -2.26373952e-02\n 1.62073970e-01 -1.94411464e-02 1.17924795e-01 -1.47007450e-01\n -3.67642902e-02 1.89828753e+00 -2.80938089e-01 -6.51913807e-02\n 1.29113793e-01 -1.11208245e-01 -1.44859731e-01 -4.98027168e-02\n -1.77509382e-01 1.25944054e+00 -1.15877651e-01 -1.95285939e-02\n -2.20439658e-02 1.98709518e-01 -1.76479965e-02 -4.59314957e-02\n 1.08343758e-01 7.52719045e-02 -1.20526366e-01 -7.80929625e-02\n 2.71024182e-02 1.05296761e-01 1.91538185e-01 -1.02129318e-01\n -2.44323798e-02 1.66431382e-01 -4.62953225e-02 -4.45550308e-02\n -6.70305267e-02 -7.21675315e-05 4.60525192e-02 -7.55855739e-02\n -1.18231503e-02 3.01912148e-02 9.27354991e-02 4.05419199e-03\n -1.18771479e-01 2.97592226e-02 -1.24346659e-01 -4.21048999e-02\n 9....,0,0,0,0,0,0,0,0,0,1.000000,-0.000000,0,FN

In [16]:
# Total prediction class (TP + FN)
prediction_class_total = len(tp_df) + len(fn_df)

# TP percentage
tp_percentage = round(len(tp_df) / prediction_class_total * 100, 2)

# FN percentage
fn_percentage = round(len(fn_df) / prediction_class_total * 100, 2)

print(f"Recall for Prediction Class Total (TP + FN): {prediction_class_total}")
print(f"TP: {len(tp_df)} ({tp_percentage}%)")
print(f"FN: {len(fn_df)} ({fn_percentage}%)")

Recall for Prediction Class Total (TP + FN): 458
TP: 388 (84.72%)
FN: 70 (15.28%)