# Error Analysis: Prediction Structure

- **Question:** Does future-related syntactic structure reliably indicate a prediction?

In [ ]:
import os
import sys

import pandas as pd

notebook_dir = os.getcwd()

sys.path.append(os.path.join(notebook_dir, '../'))

from data_processing import DataProcessing
from feature_extraction import SpacyFeatureExtraction

In [2]:
pd.set_option('max_colwidth', 800)
# pd.set_option('display.max_columns', None)
# pd.set_option('display.max_columns', 40)
# pd.set_option('display.max_rows', None)

## Load Data

In [3]:
base_data_path = DataProcessing.load_base_data_path(notebook_dir)
# combine_data_path = os.path.join(base_data_path, 'financial_phrase_bank/combined_generated_fin_phrase_bank')
train_data = os.path.join(base_data_path, 'classification_results/train_synthetic-v1_2026-03-23/seed3')

In [4]:
# model_results_path = os.path.join(combine_data_path, 'inference_chronicle2050_2026-03-07_21-51-47.csv')
test_data = os.path.join(train_data, 'external_fpb-maya-binary-imbalanced-96d-v1/', 'ml_classifiers_fpb-maya-binary-imbalanced-96d-v1.csv')

model_results_df = DataProcessing.load_from_file(test_data, 'csv', sep=',')
cols_to_drop = ["Dataset Name", "Author Type", "maya_label"]
compare_y_vs_yhats_df = DataProcessing.drop_df_columns(model_results_df, cols_to_drop)
compare_y_vs_yhats_df

,Base Sentence,Sentence Label,Base Sentence Embedding,perceptron,sgd_classifier,logistic_regression,ridge_classifier,decision_tree_classifier,random_forest_classifier,gradient_boosting_classifier,support_vector_machine_classifier,x_gradient_boosting_classifier
0,With the new production plant the company would increase its capacity to meet the expected increase in demand and would improve the use of raw materials and therefore increase the production profitability .,1,[-1.22568220e-01 2.48624131e-01 -4.82655168e-02 -1.09789923e-01\n -8.58348906e-02 3.63291465e-02 -1.27964811e-02 7.17335939e-02\n -1.18364163e-01 2.27930522e+00 -3.32476139e-01 -1.46164745e-02\n 1.25499114e-01 7.25146085e-02 6.57393187e-02 -5.76901138e-02\n -2.05907249e-03 1.51917112e+00 -3.29480022e-01 -4.57408801e-02\n 2.22120117e-02 1.05339624e-01 -4.22692373e-02 -1.23566784e-01\n -5.79119613e-03 6.18153140e-02 -5.48806489e-02 2.96797305e-02\n -1.07008472e-01 -9.98812243e-02 -9.39770564e-02 3.87728140e-02\n -5.82127571e-02 7.14930072e-02 9.65250358e-02 -3.75642404e-02\n 7.18023349e-03 6.21852428e-02 7.68979266e-02 -1.69069305e-01\n 1.44475931e-03 7.71993026e-02 3.41709815e-02 -1.10992551e-01\n -1.81387588e-02 -8.61631632e-02 -2.34903637e-02 6.00658916e-02\n -3....,1,1,1,1,0,1,1,1,1
1,"According to the company 's updated strategy for the years 2009-2012 , Basware targets a long-term net sales growth in the range of 20 % -40 % with an operating profit margin of 10 % -20 % of net sales .",1,[-2.63320029e-01 3.28540474e-01 4.48558182e-02 -1.09422831e-02\n 3.39385755e-02 -1.25387803e-01 2.09340192e-02 8.32975954e-02\n 1.10356383e-01 1.74510765e+00 -3.98153275e-01 1.41264707e-01\n -8.98099765e-02 -1.47727029e-02 5.77163734e-02 -5.09223454e-02\n -4.27257568e-02 1.41277170e+00 -2.09747717e-01 1.56779997e-02\n -3.64826852e-03 5.97854443e-02 -7.89400712e-02 -1.39893517e-02\n 1.13595366e-01 9.83026922e-02 -5.14178127e-02 7.06899390e-02\n 2.47105230e-02 1.06609218e-01 -4.19648038e-03 -1.85196903e-02\n -1.48957130e-02 9.90139246e-02 1.10973224e-01 -2.59710420e-02\n -6.08825274e-02 4.48305123e-02 4.36691009e-02 -9.27021950e-02\n 6.36729002e-02 1.98753644e-02 2.10891932e-01 -8.54000822e-02\n 4.67465706e-02 -2.04764325e-02 -3.69948000e-02 1.16207667e-01\n 1....,1,1,0,0,1,1,1,0,1
2,TeliaSonera TLSN said the offer is in line with its strategy to increase its ownership in core business holdings and would strengthen Eesti Telekom 's offering to its customers .,1,[ 1.15080299e-02 1.98225155e-01 1.95062440e-02 -5.97744621e-02\n 1.75585955e-01 -1.25474662e-01 -3.72287892e-02 -2.83286646e-02\n -3.56662273e-02 1.96045303e+00 -2.79843062e-01 -1.04898110e-01\n 4.49508205e-02 1.31481076e-02 6.55795187e-02 -4.11130209e-03\n -5.56710083e-03 1.11790729e+00 -1.21459611e-01 -9.75316912e-02\n 2.18506586e-02 1.38311490e-01 9.17155594e-02 -5.85136563e-02\n 1.03342809e-01 7.32071251e-02 -3.92427929e-02 1.13294438e-01\n -1.07247204e-01 5.58346435e-02 -9.28281173e-02 5.48683619e-03\n -1.84886660e-02 5.24056628e-02 4.05881368e-02 -8.35432187e-02\n 1.13391867e-02 2.78038122e-02 -5.44880610e-03 -1.02035753e-01\n -6.69988245e-02 7.79658780e-02 5.37769347e-02 -1.39616817e-01\n 2.96867881e-02 1.13102477e-02 -3.53476144e-02 -1.88835058e-02\n -4....,1,1,1,1,1,1,1,1,1
3,"STORA ENSO , NORSKE SKOG , M-REAL , UPM-KYMMENE Credit Suisse First Boston ( CFSB ) raised the fair value for shares in four of the largest Nordic forestry groups .",1,[-5.94305294e-03 1.57299116e-01 -1.01663664e-01 -4.74716797e-02\n 1.79840446e-01 2.63532978e-02 4.07044962e-02 -3.17418873e-02\n -1.32127828e-03 1.28309309e+00 -3.01563025e-01 4.19499092e-02\n 4.76229452e-02 -1.16947450e-01 -1.42535036e-02 2.37643998e-02\n -3.57760116e-02 8.38545859e-01 -5.43218441e-02 2.42432952e-03\n 7.67285563e-03 4.88467440e-02 4.74129207e-02 -2.67546187e-04\n 6.47759363e-02 7.66171236e-03 -7.71588413e-03 6.14660196e-02\n 9.25298501e-03 1.29891783e-01 6.76145032e-02 -7.35822739e-03\n 3.22291143e-02 1.50113806e-01 1.32441163e-01 -9.81159508e-03\n -1.39411157e-02 1.04931206e-03 -1.90248825e-02 -9.27351974e-03\n -2.62032263e-02 7.86117762e-02 8.33134279e-02 2.64521260e-02\n -1.58701912e-02 9.79095325e-03 3.53994928e-02 -1.72072705e-02\n 7....,0,0,0,0,1,0,0,0,0
4,The company also estimates the already carried out investments to lead to an increase in its net sales for 2010 from 2009 when they reached EUR 141.7 million .,1,[-9.75671411e-02 2.17742935e-01 -5.24893478e-02 2.29859371e-02\n 1.95262451e-02 -3.96593288e-02 -2.93270722e-02 1.45730842e-02\n 8.01267326e-02 2.14558053e+00 -3.02207738e-01 7.73812085e-02\n 9.75400433e-02 -5.86019419e-02 2.85570417e-02 -6.01695329e-02\n -6.48141513e-03 1.10976875e+00 -1.62209153e-01 -2.63800696e-02\n 6.90186918e-02 5.40496930e-02 -4.89046909e-02 -1.06065851e-02\n 3.81638743e-02 8.63624960e-02 -1.46540195e-01 -7.51399994e-02\n -5.42312972e-02 -2.43689902e-02 3.15490589e-02 -7.77387097e-02\n -1.04405805e-01 1.55526847e-01 2.55947262e-02 -2.01004483e-02\n -4.33546826e-02 2.11381875e-02 9.09157470e-02 -9.94266123e-02\n -5.63282613e-03 7.87854865e-02 1.45106107e-01 -1.49363369e-01\n 2.86051352e-02 -9.17335041e-03 -3.88870686e-02 -1.43906018e-02\n 2....,1,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
4841,LONDON MarketWatch -- Share prices ended lower in London Monday as a rebound in bank stocks failed to offset broader weakness for the FTSE 100 .,0,[-9.97306556e-02 1.64349496e-01 1.71351619e-02 7.13192746e-02\n 1.75899908e-01 -1.15603261e-01 -8.73757303e-02 -3.37601155e-02\n 5.58915287e-02 1.69525981e+00 -4.03638840e-01 3.41098830e-02\n 1.48271397e-01 -5.36716953e-02 4.27423716e-02 3.00230049e-02\n -4.06325832e-02 1.12422264e+00 -4.39298190e-02 1.07508982e-02\n -7.20263198e-02 5.96804582e-02 4.38548550e-02 -1.71869665e-01\n 5.18397167e-02 1.47482648e-01 -3.61646675e-02 8.63183811e-02\n -4.57509570e-02 6.86240196e-02 -7.81383812e-02 6.77803857e-03\n 1.96492635e-02 3.25613059e-02 8.09665844e-02 1.05558559e-01\n 1.15658459e-03 3.71128581e-02 -1.13167958e-02 -6.61973208e-02\n -1.17063336e-02 -1.49593409e-02 1.30228832e-01 1.75232589e-02\n 3.42527404e-02 4.42111705e-05 1.07453475e-02 -6.22191653e-02\n 2....,0,0,0,0,0,0,1,0,0
4842,"Rinkuskiai 's beer sales fell by 6.5 per cent to 4.16 million litres , while Kauno Alus ' beer sales jumped by 6.9 per cent to 2.48 million litres .",0,[-1.98924989e-01 3.00148040e-01 1.01390548e-01 -1.25840604e-01\n 3.24619608e-03 -1.00019135e-01 -1.24527112e-01 -5.24022356e-02\n 1.37367668e-02 1.35610378e+00 -2.27968454e-01 1.58202261e-01\n -7.28038773e-02 -4.16742004e-02 1.74741030e-01 -2.46515095e-01\n 3.43543403e-02 9.48214471e-01 -9.90116820e-02 -1.46733001e-01\n -5.03083616e-02 7.97276795e-02 2.76607871e-02 2.14223936e-02\n 8.79974142e-02 -9.17081013e-02 -1.13138795e-01 5.91326691e-02\n 1.20140046e-01 -3.84076685e-02 -3.18211094e-02 -1.06555417e-01\n -4.91127931e-02 -3.66714634e-02 2.47359928e-03 -6.18500356e-03\n -1.42085582e-01 -3.00514344e-02 5.16138040e-02 3.66412327e-02\n -6.68754056e-02 -4.96820062e-02 1.96969017e-01 -2.14436855e-02\n 3.49904411e-02 8.42073932e-02 5.88495322e-02 2.23803204e-02\n -1....,0,0,0,0,1,0,0,0,0
4843,"Operating profit fell to EUR 35.4 mn from EUR 68.8 mn in 2007 , including vessel sales gain of EUR 12.3 mn .",0,[-1.26625523e-01 2.81394184e-01 1.47076428e-01 -8.27063471e-02\n 1.89998314e-01 -1.95341870e-01 4.09874618e-02 4.50612567e-02\n 1.91018894e-01 1.17237604e+00 -3.50073159e-01 1.32276177e-01\n 1.80098731e-02 -3.21719684e-02 1.55063599e-01 -1.11439444e-01\n 5.50558940e-02 1.04285705e+00 -1.20266512e-01 4.59595509e-02\n 1.10065266e-01 5.54235131e-02 -1.12656087e-01 -1.29508138e-01\n 1.33550599e-01 9.51396152e-02 -5.79518043e-02 -1.48020387e-01\n -5.75628951e-02 1.92942038e-01 5.40777408e-02 -1.02687180e-01\n -9.71201211e-02 7.68551379e-02 1.51430340e-02 -7.59296939e-02\n -1.33880302e-01 -6.48121685e-02 8.27361941e-02 1.65923476e-01\n -6.65841550e-02 -5.17907441e-02 1.25316873e-01 -8.98319855e-02\n -1.09120391e-01 8.51464048e-02 9.52818319e-02 8.35352391e-02\n 2....,0,0,0,0,0,0,0,0,0
4844,"Net sales of the Paper segment decreased to EUR 221.6 mn in the second quarter of 2009 from EUR 241.1 mn in the second quarter of 2008 , while operating profit excluding non-recurring items rose to EUR 8.0 mn from EUR 7.6 mn .",0,[-1.32034168e-01 2.24063978e-01 3.11533064e-02 1.04350876e-02\n 1.56703591e-01 -1.01873629e-01 2.23107524e-02 5.80221787e-02\n 1.09591357e-01 1.37637448e+00 -3.08786511e-01 6.17817082e-02\n 9.21739489e-02 -4.09597717e-02 1.86670780e-01 -2.55621858e-02\n 5.35475016e-02 1.13686538e+00 -8.73383507e-02 -2.77639553e-02\n 4.91071157e-02 6.25430942e-02 -9.91906524e-02 -4.09849957e-02\n 1.23337105e-01 8.61576125e-02 -1.24529265e-01 -8.46296623e-02\n -1.07371166e-01 1.51070386e-01 1.05449930e-02 -4.81814779e-02\n -1.36766464e-01 9.01109204e-02 2.72464938e-02 1.43071718e-03\n -1.20931201e-01 2.54633697e-03 1.08788302e-02 3.64606492e-02\n 3.07067460e-03 8.49255845e-02 1.09374307e-01 -5.65562025e-02\n -2.14073937e-02 4.81035821e-02 1.16443343e-01 5.90736568e-02\n 1....,0,0,0,0,0,0,0,0,0
4845,"Sales in Finland decreased by 10.5 % in January , while sales outside Finland dropped by 17 % .",0,[-2.11000890e-01 3.38408977e-01 2.79511586e-02 -6.04719371e-02\n 1.00033201e-01 -1.23005114e-01 -2.58821696e-02 -3.29742618e-02\n 2.08791532e-02 1.56804836e+00 -3.97868901e-01 1.73305854e-01\n -1.92171901e-01 3.62741612e-02 -4.00141208e-03 -1.44216970e-01\n 8.82210955e-02 1.20483148e+00 -1.19249322e-01 -2.27035824e-02\n -7.42047001e-03 2.96443445e-03 4.77242656e-02 -5.48094772e-02\n 4.66798693e-02 -3.94312143e-02 -1.53847948e-01 6.67186901e-02\n -3.74379009e-02 5.33582866e-02 -5.51761575e-02 -1.21744961e-01\n -1.30150259e-01 6.22810051e-02 4.27318439e-02 9.83037148e-03\n -2.44952291e-02 -3.26079540e-02 1.40232638e-01 -1.30875155e-01\n 1.03321888e-01 -7.45608285e-02 1.20164745e-01 1.58372801e-02\n 2.28052661e-02 8.12419355e-02 4.02745716e-02 -6.35905340e-02\n 1....,0,0,0,0,0,0,0,0,0

In [5]:
model_col_names = compare_y_vs_yhats_df.columns.to_list()[3:]
model_col_names, len(model_col_names)

(['perceptron',
  'sgd_classifier',
  'logistic_regression',
  'ridge_classifier',
  'decision_tree_classifier',
  'random_forest_classifier',
  'gradient_boosting_classifier',
  'support_vector_machine_classifier',
  'x_gradient_boosting_classifier'],
 9)

In [6]:
compare_y_vs_mv_df = compare_y_vs_yhats_df[model_col_names].mode(axis=1)
compare_y_vs_yhats_df['Majority Vote'] = compare_y_vs_mv_df
compare_y_vs_yhats_df

,Base Sentence,Sentence Label,Base Sentence Embedding,perceptron,sgd_classifier,logistic_regression,ridge_classifier,decision_tree_classifier,random_forest_classifier,gradient_boosting_classifier,support_vector_machine_classifier,x_gradient_boosting_classifier,Majority Vote
0,With the new production plant the company would increase its capacity to meet the expected increase in demand and would improve the use of raw materials and therefore increase the production profitability .,1,[-1.22568220e-01 2.48624131e-01 -4.82655168e-02 -1.09789923e-01\n -8.58348906e-02 3.63291465e-02 -1.27964811e-02 7.17335939e-02\n -1.18364163e-01 2.27930522e+00 -3.32476139e-01 -1.46164745e-02\n 1.25499114e-01 7.25146085e-02 6.57393187e-02 -5.76901138e-02\n -2.05907249e-03 1.51917112e+00 -3.29480022e-01 -4.57408801e-02\n 2.22120117e-02 1.05339624e-01 -4.22692373e-02 -1.23566784e-01\n -5.79119613e-03 6.18153140e-02 -5.48806489e-02 2.96797305e-02\n -1.07008472e-01 -9.98812243e-02 -9.39770564e-02 3.87728140e-02\n -5.82127571e-02 7.14930072e-02 9.65250358e-02 -3.75642404e-02\n 7.18023349e-03 6.21852428e-02 7.68979266e-02 -1.69069305e-01\n 1.44475931e-03 7.71993026e-02 3.41709815e-02 -1.10992551e-01\n -1.81387588e-02 -8.61631632e-02 -2.34903637e-02 6.00658916e-02\n -3....,1,1,1,1,0,1,1,1,1,1
1,"According to the company 's updated strategy for the years 2009-2012 , Basware targets a long-term net sales growth in the range of 20 % -40 % with an operating profit margin of 10 % -20 % of net sales .",1,[-2.63320029e-01 3.28540474e-01 4.48558182e-02 -1.09422831e-02\n 3.39385755e-02 -1.25387803e-01 2.09340192e-02 8.32975954e-02\n 1.10356383e-01 1.74510765e+00 -3.98153275e-01 1.41264707e-01\n -8.98099765e-02 -1.47727029e-02 5.77163734e-02 -5.09223454e-02\n -4.27257568e-02 1.41277170e+00 -2.09747717e-01 1.56779997e-02\n -3.64826852e-03 5.97854443e-02 -7.89400712e-02 -1.39893517e-02\n 1.13595366e-01 9.83026922e-02 -5.14178127e-02 7.06899390e-02\n 2.47105230e-02 1.06609218e-01 -4.19648038e-03 -1.85196903e-02\n -1.48957130e-02 9.90139246e-02 1.10973224e-01 -2.59710420e-02\n -6.08825274e-02 4.48305123e-02 4.36691009e-02 -9.27021950e-02\n 6.36729002e-02 1.98753644e-02 2.10891932e-01 -8.54000822e-02\n 4.67465706e-02 -2.04764325e-02 -3.69948000e-02 1.16207667e-01\n 1....,1,1,0,0,1,1,1,0,1,1
2,TeliaSonera TLSN said the offer is in line with its strategy to increase its ownership in core business holdings and would strengthen Eesti Telekom 's offering to its customers .,1,[ 1.15080299e-02 1.98225155e-01 1.95062440e-02 -5.97744621e-02\n 1.75585955e-01 -1.25474662e-01 -3.72287892e-02 -2.83286646e-02\n -3.56662273e-02 1.96045303e+00 -2.79843062e-01 -1.04898110e-01\n 4.49508205e-02 1.31481076e-02 6.55795187e-02 -4.11130209e-03\n -5.56710083e-03 1.11790729e+00 -1.21459611e-01 -9.75316912e-02\n 2.18506586e-02 1.38311490e-01 9.17155594e-02 -5.85136563e-02\n 1.03342809e-01 7.32071251e-02 -3.92427929e-02 1.13294438e-01\n -1.07247204e-01 5.58346435e-02 -9.28281173e-02 5.48683619e-03\n -1.84886660e-02 5.24056628e-02 4.05881368e-02 -8.35432187e-02\n 1.13391867e-02 2.78038122e-02 -5.44880610e-03 -1.02035753e-01\n -6.69988245e-02 7.79658780e-02 5.37769347e-02 -1.39616817e-01\n 2.96867881e-02 1.13102477e-02 -3.53476144e-02 -1.88835058e-02\n -4....,1,1,1,1,1,1,1,1,1,1
3,"STORA ENSO , NORSKE SKOG , M-REAL , UPM-KYMMENE Credit Suisse First Boston ( CFSB ) raised the fair value for shares in four of the largest Nordic forestry groups .",1,[-5.94305294e-03 1.57299116e-01 -1.01663664e-01 -4.74716797e-02\n 1.79840446e-01 2.63532978e-02 4.07044962e-02 -3.17418873e-02\n -1.32127828e-03 1.28309309e+00 -3.01563025e-01 4.19499092e-02\n 4.76229452e-02 -1.16947450e-01 -1.42535036e-02 2.37643998e-02\n -3.57760116e-02 8.38545859e-01 -5.43218441e-02 2.42432952e-03\n 7.67285563e-03 4.88467440e-02 4.74129207e-02 -2.67546187e-04\n 6.47759363e-02 7.66171236e-03 -7.71588413e-03 6.14660196e-02\n 9.25298501e-03 1.29891783e-01 6.76145032e-02 -7.35822739e-03\n 3.22291143e-02 1.50113806e-01 1.32441163e-01 -9.81159508e-03\n -1.39411157e-02 1.04931206e-03 -1.90248825e-02 -9.27351974e-03\n -2.62032263e-02 7.86117762e-02 8.33134279e-02 2.64521260e-02\n -1.58701912e-02 9.79095325e-03 3.53994928e-02 -1.72072705e-02\n 7....,0,0,0,0,1,0,0,0,0,0
4,The company also estimates the already carried out investments to lead to an increase in its net sales for 2010 from 2009 when they reached EUR 141.7 million .,1,[-9.75671411e-02 2.17742935e-01 -5.24893478e-02 2.29859371e-02\n 1.95262451e-02 -3.96593288e-02 -2.93270722e-02 1.45730842e-02\n 8.01267326e-02 2.14558053e+00 -3.02207738e-01 7.73812085e-02\n 9.75400433e-02 -5.86019419e-02 2.85570417e-02 -6.01695329e-02\n -6.48141513e-03 1.10976875e+00 -1.62209153e-01 -2.63800696e-02\n 6.90186918e-02 5.40496930e-02 -4.89046909e-02 -1.06065851e-02\n 3.81638743e-02 8.63624960e-02 -1.46540195e-01 -7.51399994e-02\n -5.42312972e-02 -2.43689902e-02 3.15490589e-02 -7.77387097e-02\n -1.04405805e-01 1.55526847e-01 2.55947262e-02 -2.01004483e-02\n -4.33546826e-02 2.11381875e-02 9.09157470e-02 -9.94266123e-02\n -5.63282613e-03 7.87854865e-02 1.45106107e-01 -1.49363369e-01\n 2.86051352e-02 -9.17335041e-03 -3.88870686e-02 -1.43906018e-02\n 2....,1,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4841,LONDON MarketWatch -- Share prices ended lower in London Monday as a rebound in bank stocks failed to offset broader weakness for the FTSE 100 .,0,[-9.97306556e-02 1.64349496e-01 1.71351619e-02 7.13192746e-02\n 1.75899908e-01 -1.15603261e-01 -8.73757303e-02 -3.37601155e-02\n 5.58915287e-02 1.69525981e+00 -4.03638840e-01 3.41098830e-02\n 1.48271397e-01 -5.36716953e-02 4.27423716e-02 3.00230049e-02\n -4.06325832e-02 1.12422264e+00 -4.39298190e-02 1.07508982e-02\n -7.20263198e-02 5.96804582e-02 4.38548550e-02 -1.71869665e-01\n 5.18397167e-02 1.47482648e-01 -3.61646675e-02 8.63183811e-02\n -4.57509570e-02 6.86240196e-02 -7.81383812e-02 6.77803857e-03\n 1.96492635e-02 3.25613059e-02 8.09665844e-02 1.05558559e-01\n 1.15658459e-03 3.71128581e-02 -1.13167958e-02 -6.61973208e-02\n -1.17063336e-02 -1.49593409e-02 1.30228832e-01 1.75232589e-02\n 3.42527404e-02 4.42111705e-05 1.07453475e-02 -6.22191653e-02\n 2....,0,0,0,0,0,0,1,0,0,0
4842,"Rinkuskiai 's beer sales fell by 6.5 per cent to 4.16 million litres , while Kauno Alus ' beer sales jumped by 6.9 per cent to 2.48 million litres .",0,[-1.98924989e-01 3.00148040e-01 1.01390548e-01 -1.25840604e-01\n 3.24619608e-03 -1.00019135e-01 -1.24527112e-01 -5.24022356e-02\n 1.37367668e-02 1.35610378e+00 -2.27968454e-01 1.58202261e-01\n -7.28038773e-02 -4.16742004e-02 1.74741030e-01 -2.46515095e-01\n 3.43543403e-02 9.48214471e-01 -9.90116820e-02 -1.46733001e-01\n -5.03083616e-02 7.97276795e-02 2.76607871e-02 2.14223936e-02\n 8.79974142e-02 -9.17081013e-02 -1.13138795e-01 5.91326691e-02\n 1.20140046e-01 -3.84076685e-02 -3.18211094e-02 -1.06555417e-01\n -4.91127931e-02 -3.66714634e-02 2.47359928e-03 -6.18500356e-03\n -1.42085582e-01 -3.00514344e-02 5.16138040e-02 3.66412327e-02\n -6.68754056e-02 -4.96820062e-02 1.96969017e-01 -2.14436855e-02\n 3.49904411e-02 8.42073932e-02 5.88495322e-02 2.23803204e-02\n -1....,0,0,0,0,1,0,0,0,0,0
4843,"Operating profit fell to EUR 35.4 mn from EUR 68.8 mn in 2007 , including vessel sales gain of EUR 12.3 mn .",0,[-1.26625523e-01 2.81394184e-01 1.47076428e-01 -8.27063471e-02\n 1.89998314e-01 -1.95341870e-01 4.09874618e-02 4.50612567e-02\n 1.91018894e-01 1.17237604e+00 -3.50073159e-01 1.32276177e-01\n 1.80098731e-02 -3.21719684e-02 1.55063599e-01 -1.11439444e-01\n 5.50558940e-02 1.04285705e+00 -1.20266512e-01 4.59595509e-02\n 1.10065266e-01 5.54235131e-02 -1.12656087e-01 -1.29508138e-01\n 1.33550599e-01 9.51396152e-02 -5.79518043e-02 -1.48020387e-01\n -5.75628951e-02 1.92942038e-01 5.40777408e-02 -1.02687180e-01\n -9.71201211e-02 7.68551379e-02 1.51430340e-02 -7.59296939e-02\n -1.33880302e-01 -6.48121685e-02 8.27361941e-02 1.65923476e-01\n -6.65841550e-02 -5.17907441e-02 1.25316873e-01 -8.98319855e-02\n -1.09120391e-01 8.51464048e-02 9.52818319e-02 8.35352391e-02\n 2....,0,0,0,0,0,0,0,0,0,0
4844,"Net sales of the Paper segment decreased to EUR 221.6 mn in the second quarter of 2009 from EUR 241.1 mn in the second quarter of 2008 , while operating profit excluding non-recurring items rose to EUR 8.0 mn from EUR 7.6 mn .",0,[-1.32034168e-01 2.24063978e-01 3.11533064e-02 1.04350876e-02\n 1.56703591e-01 -1.01873629e-01 2.23107524e-02 5.80221787e-02\n 1.09591357e-01 1.37637448e+00 -3.08786511e-01 6.17817082e-02\n 9.21739489e-02 -4.09597717e-02 1.86670780e-01 -2.55621858e-02\n 5.35475016e-02 1.13686538e+00 -8.73383507e-02 -2.77639553e-02\n 4.91071157e-02 6.25430942e-02 -9.91906524e-02 -4.09849957e-02\n 1.23337105e-01 8.61576125e-02 -1.24529265e-01 -8.46296623e-02\n -1.07371166e-01 1.51070386e-01 1.05449930e-02 -4.81814779e-02\n -1.36766464e-01 9.01109204e-02 2.72464938e-02 1.43071718e-03\n -1.20931201e-01 2.54633697e-03 1.08788302e-02 3.64606492e-02\n 3.07067460e-03 8.49255845e-02 1.09374307e-01 -5.65562025e-02\n -2.14073937e-02 4.81035821e-02 1.16443343e-01 5.90736568e-02\n 1....,0,0,0,0,0,0,0,0,0,0
4845,"Sales in Finland decreased by 10.5 % in January , while sales outside Finland dropped by 17 % .",0,[-2.11000890e-01 3.38408977e-01 2.79511586e-02 -6.04719371e-02\n 1.00033201e-01 -1.23005114e-01 -2.58821696e-02 -3.29742618e-02\n 2.08791532e-02 1.56804836e+00 -3.97868901e-01 1.73305854e-01\n -1.92171901e-01 3.62741612e-02 -4.00141208e-03 -1.44216970e-01\n 8.82210955e-02 1.20483148e+00 -1.19249322e-01 -2.27035824e-02\n -7.42047001e-03 2.96443445e-03 4.77242656e-02 -5.48094772e-02\n 4.66798693e-02 -3.94312143e-02 -1.53847948e-01 6.67186901e-02\n -3.74379009e-02 5.33582866e-02 -5.51761575e-02 -1.21744961e-01\n -1.30150259e-01 6.22810051e-02 4.27318439e-02 9.83037148e-03\n -2.44952291e-02 -3.26079540e-02 1.40232638e-01 -1.30875155e-01\n 1.03321888e-01 -7.45608285e-02 1.20164745e-01 1.58372801e-02\n 2.28052661e-02 8.12419355e-02 4.02745716e-02 -6.35905340e-02\n 1....,0,0,0,0,0,0,0,0,0,0

In [7]:
model_col_names

['perceptron',
 'sgd_classifier',
 'logistic_regression',
 'ridge_classifier',
 'decision_tree_classifier',
 'random_forest_classifier',
 'gradient_boosting_classifier',
 'support_vector_machine_classifier',
 'x_gradient_boosting_classifier']

In [8]:
meta_data = compare_y_vs_yhats_df.iloc[:, 2:-1]
meta_data

,Base Sentence Embedding,perceptron,sgd_classifier,logistic_regression,ridge_classifier,decision_tree_classifier,random_forest_classifier,gradient_boosting_classifier,support_vector_machine_classifier,x_gradient_boosting_classifier
0,[-1.22568220e-01 2.48624131e-01 -4.82655168e-02 -1.09789923e-01\n -8.58348906e-02 3.63291465e-02 -1.27964811e-02 7.17335939e-02\n -1.18364163e-01 2.27930522e+00 -3.32476139e-01 -1.46164745e-02\n 1.25499114e-01 7.25146085e-02 6.57393187e-02 -5.76901138e-02\n -2.05907249e-03 1.51917112e+00 -3.29480022e-01 -4.57408801e-02\n 2.22120117e-02 1.05339624e-01 -4.22692373e-02 -1.23566784e-01\n -5.79119613e-03 6.18153140e-02 -5.48806489e-02 2.96797305e-02\n -1.07008472e-01 -9.98812243e-02 -9.39770564e-02 3.87728140e-02\n -5.82127571e-02 7.14930072e-02 9.65250358e-02 -3.75642404e-02\n 7.18023349e-03 6.21852428e-02 7.68979266e-02 -1.69069305e-01\n 1.44475931e-03 7.71993026e-02 3.41709815e-02 -1.10992551e-01\n -1.81387588e-02 -8.61631632e-02 -2.34903637e-02 6.00658916e-02\n -3....,1,1,1,1,0,1,1,1,1
1,[-2.63320029e-01 3.28540474e-01 4.48558182e-02 -1.09422831e-02\n 3.39385755e-02 -1.25387803e-01 2.09340192e-02 8.32975954e-02\n 1.10356383e-01 1.74510765e+00 -3.98153275e-01 1.41264707e-01\n -8.98099765e-02 -1.47727029e-02 5.77163734e-02 -5.09223454e-02\n -4.27257568e-02 1.41277170e+00 -2.09747717e-01 1.56779997e-02\n -3.64826852e-03 5.97854443e-02 -7.89400712e-02 -1.39893517e-02\n 1.13595366e-01 9.83026922e-02 -5.14178127e-02 7.06899390e-02\n 2.47105230e-02 1.06609218e-01 -4.19648038e-03 -1.85196903e-02\n -1.48957130e-02 9.90139246e-02 1.10973224e-01 -2.59710420e-02\n -6.08825274e-02 4.48305123e-02 4.36691009e-02 -9.27021950e-02\n 6.36729002e-02 1.98753644e-02 2.10891932e-01 -8.54000822e-02\n 4.67465706e-02 -2.04764325e-02 -3.69948000e-02 1.16207667e-01\n 1....,1,1,0,0,1,1,1,0,1
2,[ 1.15080299e-02 1.98225155e-01 1.95062440e-02 -5.97744621e-02\n 1.75585955e-01 -1.25474662e-01 -3.72287892e-02 -2.83286646e-02\n -3.56662273e-02 1.96045303e+00 -2.79843062e-01 -1.04898110e-01\n 4.49508205e-02 1.31481076e-02 6.55795187e-02 -4.11130209e-03\n -5.56710083e-03 1.11790729e+00 -1.21459611e-01 -9.75316912e-02\n 2.18506586e-02 1.38311490e-01 9.17155594e-02 -5.85136563e-02\n 1.03342809e-01 7.32071251e-02 -3.92427929e-02 1.13294438e-01\n -1.07247204e-01 5.58346435e-02 -9.28281173e-02 5.48683619e-03\n -1.84886660e-02 5.24056628e-02 4.05881368e-02 -8.35432187e-02\n 1.13391867e-02 2.78038122e-02 -5.44880610e-03 -1.02035753e-01\n -6.69988245e-02 7.79658780e-02 5.37769347e-02 -1.39616817e-01\n 2.96867881e-02 1.13102477e-02 -3.53476144e-02 -1.88835058e-02\n -4....,1,1,1,1,1,1,1,1,1
3,[-5.94305294e-03 1.57299116e-01 -1.01663664e-01 -4.74716797e-02\n 1.79840446e-01 2.63532978e-02 4.07044962e-02 -3.17418873e-02\n -1.32127828e-03 1.28309309e+00 -3.01563025e-01 4.19499092e-02\n 4.76229452e-02 -1.16947450e-01 -1.42535036e-02 2.37643998e-02\n -3.57760116e-02 8.38545859e-01 -5.43218441e-02 2.42432952e-03\n 7.67285563e-03 4.88467440e-02 4.74129207e-02 -2.67546187e-04\n 6.47759363e-02 7.66171236e-03 -7.71588413e-03 6.14660196e-02\n 9.25298501e-03 1.29891783e-01 6.76145032e-02 -7.35822739e-03\n 3.22291143e-02 1.50113806e-01 1.32441163e-01 -9.81159508e-03\n -1.39411157e-02 1.04931206e-03 -1.90248825e-02 -9.27351974e-03\n -2.62032263e-02 7.86117762e-02 8.33134279e-02 2.64521260e-02\n -1.58701912e-02 9.79095325e-03 3.53994928e-02 -1.72072705e-02\n 7....,0,0,0,0,1,0,0,0,0
4,[-9.75671411e-02 2.17742935e-01 -5.24893478e-02 2.29859371e-02\n 1.95262451e-02 -3.96593288e-02 -2.93270722e-02 1.45730842e-02\n 8.01267326e-02 2.14558053e+00 -3.02207738e-01 7.73812085e-02\n 9.75400433e-02 -5.86019419e-02 2.85570417e-02 -6.01695329e-02\n -6.48141513e-03 1.10976875e+00 -1.62209153e-01 -2.63800696e-02\n 6.90186918e-02 5.40496930e-02 -4.89046909e-02 -1.06065851e-02\n 3.81638743e-02 8.63624960e-02 -1.46540195e-01 -7.51399994e-02\n -5.42312972e-02 -2.43689902e-02 3.15490589e-02 -7.77387097e-02\n -1.04405805e-01 1.55526847e-01 2.55947262e-02 -2.01004483e-02\n -4.33546826e-02 2.11381875e-02 9.09157470e-02 -9.94266123e-02\n -5.63282613e-03 7.87854865e-02 1.45106107e-01 -1.49363369e-01\n 2.86051352e-02 -9.17335041e-03 -3.88870686e-02 -1.43906018e-02\n 2....,1,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...
4841,[-9.97306556e-02 1.64349496e-01 1.71351619e-02 7.13192746e-02\n 1.75899908e-01 -1.15603261e-01 -8.73757303e-02 -3.37601155e-02\n 5.58915287e-02 1.69525981e+00 -4.03638840e-01 3.41098830e-02\n 1.48271397e-01 -5.36716953e-02 4.27423716e-02 3.00230049e-02\n -4.06325832e-02 1.12422264e+00 -4.39298190e-02 1.07508982e-02\n -7.20263198e-02 5.96804582e-02 4.38548550e-02 -1.71869665e-01\n 5.18397167e-02 1.47482648e-01 -3.61646675e-02 8.63183811e-02\n -4.57509570e-02 6.86240196e-02 -7.81383812e-02 6.77803857e-03\n 1.96492635e-02 3.25613059e-02 8.09665844e-02 1.05558559e-01\n 1.15658459e-03 3.71128581e-02 -1.13167958e-02 -6.61973208e-02\n -1.17063336e-02 -1.49593409e-02 1.30228832e-01 1.75232589e-02\n 3.42527404e-02 4.42111705e-05 1.07453475e-02 -6.22191653e-02\n 2....,0,0,0,0,0,0,1,0,0
4842,[-1.98924989e-01 3.00148040e-01 1.01390548e-01 -1.25840604e-01\n 3.24619608e-03 -1.00019135e-01 -1.24527112e-01 -5.24022356e-02\n 1.37367668e-02 1.35610378e+00 -2.27968454e-01 1.58202261e-01\n -7.28038773e-02 -4.16742004e-02 1.74741030e-01 -2.46515095e-01\n 3.43543403e-02 9.48214471e-01 -9.90116820e-02 -1.46733001e-01\n -5.03083616e-02 7.97276795e-02 2.76607871e-02 2.14223936e-02\n 8.79974142e-02 -9.17081013e-02 -1.13138795e-01 5.91326691e-02\n 1.20140046e-01 -3.84076685e-02 -3.18211094e-02 -1.06555417e-01\n -4.91127931e-02 -3.66714634e-02 2.47359928e-03 -6.18500356e-03\n -1.42085582e-01 -3.00514344e-02 5.16138040e-02 3.66412327e-02\n -6.68754056e-02 -4.96820062e-02 1.96969017e-01 -2.14436855e-02\n 3.49904411e-02 8.42073932e-02 5.88495322e-02 2.23803204e-02\n -1....,0,0,0,0,1,0,0,0,0
4843,[-1.26625523e-01 2.81394184e-01 1.47076428e-01 -8.27063471e-02\n 1.89998314e-01 -1.95341870e-01 4.09874618e-02 4.50612567e-02\n 1.91018894e-01 1.17237604e+00 -3.50073159e-01 1.32276177e-01\n 1.80098731e-02 -3.21719684e-02 1.55063599e-01 -1.11439444e-01\n 5.50558940e-02 1.04285705e+00 -1.20266512e-01 4.59595509e-02\n 1.10065266e-01 5.54235131e-02 -1.12656087e-01 -1.29508138e-01\n 1.33550599e-01 9.51396152e-02 -5.79518043e-02 -1.48020387e-01\n -5.75628951e-02 1.92942038e-01 5.40777408e-02 -1.02687180e-01\n -9.71201211e-02 7.68551379e-02 1.51430340e-02 -7.59296939e-02\n -1.33880302e-01 -6.48121685e-02 8.27361941e-02 1.65923476e-01\n -6.65841550e-02 -5.17907441e-02 1.25316873e-01 -8.98319855e-02\n -1.09120391e-01 8.51464048e-02 9.52818319e-02 8.35352391e-02\n 2....,0,0,0,0,0,0,0,0,0
4844,[-1.32034168e-01 2.24063978e-01 3.11533064e-02 1.04350876e-02\n 1.56703591e-01 -1.01873629e-01 2.23107524e-02 5.80221787e-02\n 1.09591357e-01 1.37637448e+00 -3.08786511e-01 6.17817082e-02\n 9.21739489e-02 -4.09597717e-02 1.86670780e-01 -2.55621858e-02\n 5.35475016e-02 1.13686538e+00 -8.73383507e-02 -2.77639553e-02\n 4.91071157e-02 6.25430942e-02 -9.91906524e-02 -4.09849957e-02\n 1.23337105e-01 8.61576125e-02 -1.24529265e-01 -8.46296623e-02\n -1.07371166e-01 1.51070386e-01 1.05449930e-02 -4.81814779e-02\n -1.36766464e-01 9.01109204e-02 2.72464938e-02 1.43071718e-03\n -1.20931201e-01 2.54633697e-03 1.08788302e-02 3.64606492e-02\n 3.07067460e-03 8.49255845e-02 1.09374307e-01 -5.65562025e-02\n -2.14073937e-02 4.81035821e-02 1.16443343e-01 5.90736568e-02\n 1....,0,0,0,0,0,0,0,0,0
4845,[-2.11000890e-01 3.38408977e-01 2.79511586e-02 -6.04719371e-02\n 1.00033201e-01 -1.23005114e-01 -2.58821696e-02 -3.29742618e-02\n 2.08791532e-02 1.56804836e+00 -3.97868901e-01 1.73305854e-01\n -1.92171901e-01 3.62741612e-02 -4.00141208e-03 -1.44216970e-01\n 8.82210955e-02 1.20483148e+00 -1.19249322e-01 -2.27035824e-02\n -7.42047001e-03 2.96443445e-03 4.77242656e-02 -5.48094772e-02\n 4.66798693e-02 -3.94312143e-02 -1.53847948e-01 6.67186901e-02\n -3.74379009e-02 5.33582866e-02 -5.51761575e-02 -1.21744961e-01\n -1.30150259e-01 6.22810051e-02 4.27318439e-02 9.83037148e-03\n -2.44952291e-02 -3.26079540e-02 1.40232638e-01 -1.30875155e-01\n 1.03321888e-01 -7.45608285e-02 1.20164745e-01 1.58372801e-02\n 2.28052661e-02 8.12419355e-02 4.02745716e-02 -6.35905340e-02\n 1....,0,0,0,0,0,0,0,0,0

In [9]:
meta_data = compare_y_vs_yhats_df.iloc[:, 3:-1]
compare_y_vs_yhats_df['Meta Data'] = meta_data.to_dict(orient='records')
compare_y_vs_yhats_df
y_vs_yhats_df = DataProcessing.drop_df_columns(compare_y_vs_yhats_df, meta_data.columns.to_list())
y_vs_yhats_df

,Base Sentence,Sentence Label,Base Sentence Embedding,Majority Vote,Meta Data
0,With the new production plant the company would increase its capacity to meet the expected increase in demand and would improve the use of raw materials and therefore increase the production profitability .,1,[-1.22568220e-01 2.48624131e-01 -4.82655168e-02 -1.09789923e-01\n -8.58348906e-02 3.63291465e-02 -1.27964811e-02 7.17335939e-02\n -1.18364163e-01 2.27930522e+00 -3.32476139e-01 -1.46164745e-02\n 1.25499114e-01 7.25146085e-02 6.57393187e-02 -5.76901138e-02\n -2.05907249e-03 1.51917112e+00 -3.29480022e-01 -4.57408801e-02\n 2.22120117e-02 1.05339624e-01 -4.22692373e-02 -1.23566784e-01\n -5.79119613e-03 6.18153140e-02 -5.48806489e-02 2.96797305e-02\n -1.07008472e-01 -9.98812243e-02 -9.39770564e-02 3.87728140e-02\n -5.82127571e-02 7.14930072e-02 9.65250358e-02 -3.75642404e-02\n 7.18023349e-03 6.21852428e-02 7.68979266e-02 -1.69069305e-01\n 1.44475931e-03 7.71993026e-02 3.41709815e-02 -1.10992551e-01\n -1.81387588e-02 -8.61631632e-02 -2.34903637e-02 6.00658916e-02\n -3....,1,"{'perceptron': 1, 'sgd_classifier': 1, 'logistic_regression': 1, 'ridge_classifier': 1, 'decision_tree_classifier': 0, 'random_forest_classifier': 1, 'gradient_boosting_classifier': 1, 'support_vector_machine_classifier': 1, 'x_gradient_boosting_classifier': 1}"
1,"According to the company 's updated strategy for the years 2009-2012 , Basware targets a long-term net sales growth in the range of 20 % -40 % with an operating profit margin of 10 % -20 % of net sales .",1,[-2.63320029e-01 3.28540474e-01 4.48558182e-02 -1.09422831e-02\n 3.39385755e-02 -1.25387803e-01 2.09340192e-02 8.32975954e-02\n 1.10356383e-01 1.74510765e+00 -3.98153275e-01 1.41264707e-01\n -8.98099765e-02 -1.47727029e-02 5.77163734e-02 -5.09223454e-02\n -4.27257568e-02 1.41277170e+00 -2.09747717e-01 1.56779997e-02\n -3.64826852e-03 5.97854443e-02 -7.89400712e-02 -1.39893517e-02\n 1.13595366e-01 9.83026922e-02 -5.14178127e-02 7.06899390e-02\n 2.47105230e-02 1.06609218e-01 -4.19648038e-03 -1.85196903e-02\n -1.48957130e-02 9.90139246e-02 1.10973224e-01 -2.59710420e-02\n -6.08825274e-02 4.48305123e-02 4.36691009e-02 -9.27021950e-02\n 6.36729002e-02 1.98753644e-02 2.10891932e-01 -8.54000822e-02\n 4.67465706e-02 -2.04764325e-02 -3.69948000e-02 1.16207667e-01\n 1....,1,"{'perceptron': 1, 'sgd_classifier': 1, 'logistic_regression': 0, 'ridge_classifier': 0, 'decision_tree_classifier': 1, 'random_forest_classifier': 1, 'gradient_boosting_classifier': 1, 'support_vector_machine_classifier': 0, 'x_gradient_boosting_classifier': 1}"
2,TeliaSonera TLSN said the offer is in line with its strategy to increase its ownership in core business holdings and would strengthen Eesti Telekom 's offering to its customers .,1,[ 1.15080299e-02 1.98225155e-01 1.95062440e-02 -5.97744621e-02\n 1.75585955e-01 -1.25474662e-01 -3.72287892e-02 -2.83286646e-02\n -3.56662273e-02 1.96045303e+00 -2.79843062e-01 -1.04898110e-01\n 4.49508205e-02 1.31481076e-02 6.55795187e-02 -4.11130209e-03\n -5.56710083e-03 1.11790729e+00 -1.21459611e-01 -9.75316912e-02\n 2.18506586e-02 1.38311490e-01 9.17155594e-02 -5.85136563e-02\n 1.03342809e-01 7.32071251e-02 -3.92427929e-02 1.13294438e-01\n -1.07247204e-01 5.58346435e-02 -9.28281173e-02 5.48683619e-03\n -1.84886660e-02 5.24056628e-02 4.05881368e-02 -8.35432187e-02\n 1.13391867e-02 2.78038122e-02 -5.44880610e-03 -1.02035753e-01\n -6.69988245e-02 7.79658780e-02 5.37769347e-02 -1.39616817e-01\n 2.96867881e-02 1.13102477e-02 -3.53476144e-02 -1.88835058e-02\n -4....,1,"{'perceptron': 1, 'sgd_classifier': 1, 'logistic_regression': 1, 'ridge_classifier': 1, 'decision_tree_classifier': 1, 'random_forest_classifier': 1, 'gradient_boosting_classifier': 1, 'support_vector_machine_classifier': 1, 'x_gradient_boosting_classifier': 1}"
3,"STORA ENSO , NORSKE SKOG , M-REAL , UPM-KYMMENE Credit Suisse First Boston ( CFSB ) raised the fair value for shares in four of the largest Nordic forestry groups .",1,[-5.94305294e-03 1.57299116e-01 -1.01663664e-01 -4.74716797e-02\n 1.79840446e-01 2.63532978e-02 4.07044962e-02 -3.17418873e-02\n -1.32127828e-03 1.28309309e+00 -3.01563025e-01 4.19499092e-02\n 4.76229452e-02 -1.16947450e-01 -1.42535036e-02 2.37643998e-02\n -3.57760116e-02 8.38545859e-01 -5.43218441e-02 2.42432952e-03\n 7.67285563e-03 4.88467440e-02 4.74129207e-02 -2.67546187e-04\n 6.47759363e-02 7.66171236e-03 -7.71588413e-03 6.14660196e-02\n 9.25298501e-03 1.29891783e-01 6.76145032e-02 -7.35822739e-03\n 3.22291143e-02 1.50113806e-01 1.32441163e-01 -9.81159508e-03\n -1.39411157e-02 1.04931206e-03 -1.90248825e-02 -9.27351974e-03\n -2.62032263e-02 7.86117762e-02 8.33134279e-02 2.64521260e-02\n -1.58701912e-02 9.79095325e-03 3.53994928e-02 -1.72072705e-02\n 7....,0,"{'perceptron': 0, 'sgd_classifier': 0, 'logistic_regression': 0, 'ridge_classifier': 0, 'decision_tree_classifier': 1, 'random_forest_classifier': 0, 'gradient_boosting_classifier': 0, 'support_vector_machine_classifier': 0, 'x_gradient_boosting_classifier': 0}"
4,The company also estimates the already carried out investments to lead to an increase in its net sales for 2010 from 2009 when they reached EUR 141.7 million .,1,[-9.75671411e-02 2.17742935e-01 -5.24893478e-02 2.29859371e-02\n 1.95262451e-02 -3.96593288e-02 -2.93270722e-02 1.45730842e-02\n 8.01267326e-02 2.14558053e+00 -3.02207738e-01 7.73812085e-02\n 9.75400433e-02 -5.86019419e-02 2.85570417e-02 -6.01695329e-02\n -6.48141513e-03 1.10976875e+00 -1.62209153e-01 -2.63800696e-02\n 6.90186918e-02 5.40496930e-02 -4.89046909e-02 -1.06065851e-02\n 3.81638743e-02 8.63624960e-02 -1.46540195e-01 -7.51399994e-02\n -5.42312972e-02 -2.43689902e-02 3.15490589e-02 -7.77387097e-02\n -1.04405805e-01 1.55526847e-01 2.55947262e-02 -2.01004483e-02\n -4.33546826e-02 2.11381875e-02 9.09157470e-02 -9.94266123e-02\n -5.63282613e-03 7.87854865e-02 1.45106107e-01 -1.49363369e-01\n 2.86051352e-02 -9.17335041e-03 -3.88870686e-02 -1.43906018e-02\n 2....,0,"{'perceptron': 1, 'sgd_classifier': 0, 'logistic_regression': 0, 'ridge_classifier': 0, 'decision_tree_classifier': 1, 'random_forest_classifier': 0, 'gradient_boosting_classifier': 0, 'support_vector_machine_classifier': 0, 'x_gradient_boosting_classifier': 0}"
...,...,...,...,...,...
4841,LONDON MarketWatch -- Share prices ended lower in London Monday as a rebound in bank stocks failed to offset broader weakness for the FTSE 100 .,0,[-9.97306556e-02 1.64349496e-01 1.71351619e-02 7.13192746e-02\n 1.75899908e-01 -1.15603261e-01 -8.73757303e-02 -3.37601155e-02\n 5.58915287e-02 1.69525981e+00 -4.03638840e-01 3.41098830e-02\n 1.48271397e-01 -5.36716953e-02 4.27423716e-02 3.00230049e-02\n -4.06325832e-02 1.12422264e+00 -4.39298190e-02 1.07508982e-02\n -7.20263198e-02 5.96804582e-02 4.38548550e-02 -1.71869665e-01\n 5.18397167e-02 1.47482648e-01 -3.61646675e-02 8.63183811e-02\n -4.57509570e-02 6.86240196e-02 -7.81383812e-02 6.77803857e-03\n 1.96492635e-02 3.25613059e-02 8.09665844e-02 1.05558559e-01\n 1.15658459e-03 3.71128581e-02 -1.13167958e-02 -6.61973208e-02\n -1.17063336e-02 -1.49593409e-02 1.30228832e-01 1.75232589e-02\n 3.42527404e-02 4.42111705e-05 1.07453475e-02 -6.22191653e-02\n 2....,0,"{'perceptron': 0, 'sgd_classifier': 0, 'logistic_regression': 0, 'ridge_classifier': 0, 'decision_tree_classifier': 0, 'random_forest_classifier': 0, 'gradient_boosting_classifier': 1, 'support_vector_machine_classifier': 0, 'x_gradient_boosting_classifier': 0}"
4842,"Rinkuskiai 's beer sales fell by 6.5 per cent to 4.16 million litres , while Kauno Alus ' beer sales jumped by 6.9 per cent to 2.48 million litres .",0,[-1.98924989e-01 3.00148040e-01 1.01390548e-01 -1.25840604e-01\n 3.24619608e-03 -1.00019135e-01 -1.24527112e-01 -5.24022356e-02\n 1.37367668e-02 1.35610378e+00 -2.27968454e-01 1.58202261e-01\n -7.28038773e-02 -4.16742004e-02 1.74741030e-01 -2.46515095e-01\n 3.43543403e-02 9.48214471e-01 -9.90116820e-02 -1.46733001e-01\n -5.03083616e-02 7.97276795e-02 2.76607871e-02 2.14223936e-02\n 8.79974142e-02 -9.17081013e-02 -1.13138795e-01 5.91326691e-02\n 1.20140046e-01 -3.84076685e-02 -3.18211094e-02 -1.06555417e-01\n -4.91127931e-02 -3.66714634e-02 2.47359928e-03 -6.18500356e-03\n -1.42085582e-01 -3.00514344e-02 5.16138040e-02 3.66412327e-02\n -6.68754056e-02 -4.96820062e-02 1.96969017e-01 -2.14436855e-02\n 3.49904411e-02 8.42073932e-02 5.88495322e-02 2.23803204e-02\n -1....,0,"{'perceptron': 0, 'sgd_classifier': 0, 'logistic_regression': 0, 'ridge_classifier': 0, 'decision_tree_classifier': 1, 'random_forest_classifier': 0, 'gradient_boosting_classifier': 0, 'support_vector_machine_classifier': 0, 'x_gradient_boosting_classifier': 0}"
4843,"Operating profit fell to EUR 35.4 mn from EUR 68.8 mn in 2007 , including vessel sales gain of EUR 12.3 mn .",0,[-1.26625523e-01 2.81394184e-01 1.47076428e-01 -8.27063471e-02\n 1.89998314e-01 -1.95341870e-01 4.09874618e-02 4.50612567e-02\n 1.91018894e-01 1.17237604e+00 -3.50073159e-01 1.32276177e-01\n 1.80098731e-02 -3.21719684e-02 1.55063599e-01 -1.11439444e-01\n 5.50558940e-02 1.04285705e+00 -1.20266512e-01 4.59595509e-02\n 1.10065266e-01 5.54235131e-02 -1.12656087e-01 -1.29508138e-01\n 1.33550599e-01 9.51396152e-02 -5.79518043e-02 -1.48020387e-01\n -5.75628951e-02 1.92942038e-01 5.40777408e-02 -1.02687180e-01\n -9.71201211e-02 7.68551379e-02 1.51430340e-02 -7.59296939e-02\n -1.33880302e-01 -6.48121685e-02 8.27361941e-02 1.65923476e-01\n -6.65841550e-02 -5.17907441e-02 1.25316873e-01 -8.98319855e-02\n -1.09120391e-01 8.51464048e-02 9.52818319e-02 8.35352391e-02\n 2....,0,"{'perceptron': 0, 'sgd_classifier': 0, 'logistic_regression': 0, 'ridge_classifier': 0, 'decision_tree_classifier': 0, 'random_forest_classifier': 0, 'gradient_boosting_classifier': 0, 'support_vector_machine_classifier': 0, 'x_gradient_boosting_classifier': 0}"
4844,"Net sales of the Paper segment decreased to EUR 221.6 mn in the second quarter of 2009 from EUR 241.1 mn in the second quarter of 2008 , while operating profit excluding non-recurring items rose to EUR 8.0 mn from EUR 7.6 mn .",0,[-1.32034168e-01 2.24063978e-01 3.11533064e-02 1.04350876e-02\n 1.56703591e-01 -1.01873629e-01 2.23107524e-02 5.80221787e-02\n 1.09591357e-01 1.37637448e+00 -3.08786511e-01 6.17817082e-02\n 9.21739489e-02 -4.09597717e-02 1.86670780e-01 -2.55621858e-02\n 5.35475016e-02 1.13686538e+00 -8.73383507e-02 -2.77639553e-02\n 4.91071157e-02 6.25430942e-02 -9.91906524e-02 -4.09849957e-02\n 1.23337105e-01 8.61576125e-02 -1.24529265e-01 -8.46296623e-02\n -1.07371166e-01 1.51070386e-01 1.05449930e-02 -4.81814779e-02\n -1.36766464e-01 9.01109204e-02 2.72464938e-02 1.43071718e-03\n -1.20931201e-01 2.54633697e-03 1.08788302e-02 3.64606492e-02\n 3.07067460e-03 8.49255845e-02 1.09374307e-01 -5.65562025e-02\n -2.14073937e-02 4.81035821e-02 1.16443343e-01 5.90736568e-02\n 1....,0,"{'perceptron': 0, 'sgd_classifier': 0, 'logistic_regression': 0, 'ridge_classifier': 0, 'decision_tree_classifier': 0, 'random_forest_classifier': 0, 'gradient_boosting_classifier': 0, 'support_vector_machine_classifier': 0, 'x_gradient_boosting_classifier': 0}"
4845,"Sales in Finland decreased by 10.5 % in January , while sales outside Finland dropped by 17 % .",0,[-2.11000890e-01 3.38408977e-01 2.79511586e-02 -6.04719371e-02\n 1.00033201e-01 -1.23005114e-01 -2.58821696e-02 -3.29742618e-02\n 2.08791532e-02 1.56804836e+00 -3.97868901e-01 1.73305854e-01\n -1.92171901e-01 3.62741612e-02 -4.00141208e-03 -1.44216970e-01\n 8.82210955e-02 1.20483148e+00 -1.19249322e-01 -2.27035824e-02\n -7.42047001e-03 2.96443445e-03 4.77242656e-02 -5.48094772e-02\n 4.66798693e-02 -3.94312143e-02 -1.53847948e-01 6.67186901e-02\n -3.74379009e-02 5.33582866e-02 -5.51761575e-02 -1.21744961e-01\n -1.30150259e-01 6.22810051e-02 4.27318439e-02 9.83037148e-03\n -2.44952291e-02 -3.26079540e-02 1.40232638e-01 -1.30875155e-01\n 1.03321888e-01 -7.45608285e-02 1.20164745e-01 1.58372801e-02\n 2.28052661e-02 8.12419355e-02 4.02745716e-02 -6.35905340e-02\n 1....,0,"{'perceptron': 0, 'sgd_classifier': 0, 'logistic_regression': 0, 'ridge_classifier': 0, 'decision_tree_classifier': 0, 'random_forest_classifier': 0, 'gradient_boosting_classifier': 0, 'support_vector_machine_classifier': 0, 'x_gradient_boosting_classifier': 0}"

## Get class of each sentence

- [ ] True Label vs Majority Vote
- [ ] True Label vs Each Model

## True Label vs Majority Vote

In [10]:
def classification_of_mv_sentence(df):
    copy_df = df.copy()
    copy_df['Class'] = None

    for idx, row in copy_df.iterrows():
        y = row['Sentence Label']
        y_hat = row['Majority Vote']

        # y = 1 (positive class)
        if y == 1:
            if y_hat == 1:  # TP
                copy_df.loc[idx, 'Class'] = "TP"
            else:  # FN
                copy_df.loc[idx, 'Class'] = "FN"

        # y = 0 (negative class)
        elif y == 0:
            if y_hat == 0:  # TN
                copy_df.loc[idx, 'Class'] = "TN"
            else:  # FP
                copy_df.loc[idx, 'Class'] = "FP"

    return copy_df

In [11]:
mv_with_class_df = classification_of_mv_sentence(y_vs_yhats_df)
mv_with_class_df

,Base Sentence,Sentence Label,Base Sentence Embedding,Majority Vote,Meta Data,Class
0,With the new production plant the company would increase its capacity to meet the expected increase in demand and would improve the use of raw materials and therefore increase the production profitability .,1,[-1.22568220e-01 2.48624131e-01 -4.82655168e-02 -1.09789923e-01\n -8.58348906e-02 3.63291465e-02 -1.27964811e-02 7.17335939e-02\n -1.18364163e-01 2.27930522e+00 -3.32476139e-01 -1.46164745e-02\n 1.25499114e-01 7.25146085e-02 6.57393187e-02 -5.76901138e-02\n -2.05907249e-03 1.51917112e+00 -3.29480022e-01 -4.57408801e-02\n 2.22120117e-02 1.05339624e-01 -4.22692373e-02 -1.23566784e-01\n -5.79119613e-03 6.18153140e-02 -5.48806489e-02 2.96797305e-02\n -1.07008472e-01 -9.98812243e-02 -9.39770564e-02 3.87728140e-02\n -5.82127571e-02 7.14930072e-02 9.65250358e-02 -3.75642404e-02\n 7.18023349e-03 6.21852428e-02 7.68979266e-02 -1.69069305e-01\n 1.44475931e-03 7.71993026e-02 3.41709815e-02 -1.10992551e-01\n -1.81387588e-02 -8.61631632e-02 -2.34903637e-02 6.00658916e-02\n -3....,1,"{'perceptron': 1, 'sgd_classifier': 1, 'logistic_regression': 1, 'ridge_classifier': 1, 'decision_tree_classifier': 0, 'random_forest_classifier': 1, 'gradient_boosting_classifier': 1, 'support_vector_machine_classifier': 1, 'x_gradient_boosting_classifier': 1}",TP
1,"According to the company 's updated strategy for the years 2009-2012 , Basware targets a long-term net sales growth in the range of 20 % -40 % with an operating profit margin of 10 % -20 % of net sales .",1,[-2.63320029e-01 3.28540474e-01 4.48558182e-02 -1.09422831e-02\n 3.39385755e-02 -1.25387803e-01 2.09340192e-02 8.32975954e-02\n 1.10356383e-01 1.74510765e+00 -3.98153275e-01 1.41264707e-01\n -8.98099765e-02 -1.47727029e-02 5.77163734e-02 -5.09223454e-02\n -4.27257568e-02 1.41277170e+00 -2.09747717e-01 1.56779997e-02\n -3.64826852e-03 5.97854443e-02 -7.89400712e-02 -1.39893517e-02\n 1.13595366e-01 9.83026922e-02 -5.14178127e-02 7.06899390e-02\n 2.47105230e-02 1.06609218e-01 -4.19648038e-03 -1.85196903e-02\n -1.48957130e-02 9.90139246e-02 1.10973224e-01 -2.59710420e-02\n -6.08825274e-02 4.48305123e-02 4.36691009e-02 -9.27021950e-02\n 6.36729002e-02 1.98753644e-02 2.10891932e-01 -8.54000822e-02\n 4.67465706e-02 -2.04764325e-02 -3.69948000e-02 1.16207667e-01\n 1....,1,"{'perceptron': 1, 'sgd_classifier': 1, 'logistic_regression': 0, 'ridge_classifier': 0, 'decision_tree_classifier': 1, 'random_forest_classifier': 1, 'gradient_boosting_classifier': 1, 'support_vector_machine_classifier': 0, 'x_gradient_boosting_classifier': 1}",TP
2,TeliaSonera TLSN said the offer is in line with its strategy to increase its ownership in core business holdings and would strengthen Eesti Telekom 's offering to its customers .,1,[ 1.15080299e-02 1.98225155e-01 1.95062440e-02 -5.97744621e-02\n 1.75585955e-01 -1.25474662e-01 -3.72287892e-02 -2.83286646e-02\n -3.56662273e-02 1.96045303e+00 -2.79843062e-01 -1.04898110e-01\n 4.49508205e-02 1.31481076e-02 6.55795187e-02 -4.11130209e-03\n -5.56710083e-03 1.11790729e+00 -1.21459611e-01 -9.75316912e-02\n 2.18506586e-02 1.38311490e-01 9.17155594e-02 -5.85136563e-02\n 1.03342809e-01 7.32071251e-02 -3.92427929e-02 1.13294438e-01\n -1.07247204e-01 5.58346435e-02 -9.28281173e-02 5.48683619e-03\n -1.84886660e-02 5.24056628e-02 4.05881368e-02 -8.35432187e-02\n 1.13391867e-02 2.78038122e-02 -5.44880610e-03 -1.02035753e-01\n -6.69988245e-02 7.79658780e-02 5.37769347e-02 -1.39616817e-01\n 2.96867881e-02 1.13102477e-02 -3.53476144e-02 -1.88835058e-02\n -4....,1,"{'perceptron': 1, 'sgd_classifier': 1, 'logistic_regression': 1, 'ridge_classifier': 1, 'decision_tree_classifier': 1, 'random_forest_classifier': 1, 'gradient_boosting_classifier': 1, 'support_vector_machine_classifier': 1, 'x_gradient_boosting_classifier': 1}",TP
3,"STORA ENSO , NORSKE SKOG , M-REAL , UPM-KYMMENE Credit Suisse First Boston ( CFSB ) raised the fair value for shares in four of the largest Nordic forestry groups .",1,[-5.94305294e-03 1.57299116e-01 -1.01663664e-01 -4.74716797e-02\n 1.79840446e-01 2.63532978e-02 4.07044962e-02 -3.17418873e-02\n -1.32127828e-03 1.28309309e+00 -3.01563025e-01 4.19499092e-02\n 4.76229452e-02 -1.16947450e-01 -1.42535036e-02 2.37643998e-02\n -3.57760116e-02 8.38545859e-01 -5.43218441e-02 2.42432952e-03\n 7.67285563e-03 4.88467440e-02 4.74129207e-02 -2.67546187e-04\n 6.47759363e-02 7.66171236e-03 -7.71588413e-03 6.14660196e-02\n 9.25298501e-03 1.29891783e-01 6.76145032e-02 -7.35822739e-03\n 3.22291143e-02 1.50113806e-01 1.32441163e-01 -9.81159508e-03\n -1.39411157e-02 1.04931206e-03 -1.90248825e-02 -9.27351974e-03\n -2.62032263e-02 7.86117762e-02 8.33134279e-02 2.64521260e-02\n -1.58701912e-02 9.79095325e-03 3.53994928e-02 -1.72072705e-02\n 7....,0,"{'perceptron': 0, 'sgd_classifier': 0, 'logistic_regression': 0, 'ridge_classifier': 0, 'decision_tree_classifier': 1, 'random_forest_classifier': 0, 'gradient_boosting_classifier': 0, 'support_vector_machine_classifier': 0, 'x_gradient_boosting_classifier': 0}",FN
4,The company also estimates the already carried out investments to lead to an increase in its net sales for 2010 from 2009 when they reached EUR 141.7 million .,1,[-9.75671411e-02 2.17742935e-01 -5.24893478e-02 2.29859371e-02\n 1.95262451e-02 -3.96593288e-02 -2.93270722e-02 1.45730842e-02\n 8.01267326e-02 2.14558053e+00 -3.02207738e-01 7.73812085e-02\n 9.75400433e-02 -5.86019419e-02 2.85570417e-02 -6.01695329e-02\n -6.48141513e-03 1.10976875e+00 -1.62209153e-01 -2.63800696e-02\n 6.90186918e-02 5.40496930e-02 -4.89046909e-02 -1.06065851e-02\n 3.81638743e-02 8.63624960e-02 -1.46540195e-01 -7.51399994e-02\n -5.42312972e-02 -2.43689902e-02 3.15490589e-02 -7.77387097e-02\n -1.04405805e-01 1.55526847e-01 2.55947262e-02 -2.01004483e-02\n -4.33546826e-02 2.11381875e-02 9.09157470e-02 -9.94266123e-02\n -5.63282613e-03 7.87854865e-02 1.45106107e-01 -1.49363369e-01\n 2.86051352e-02 -9.17335041e-03 -3.88870686e-02 -1.43906018e-02\n 2....,0,"{'perceptron': 1, 'sgd_classifier': 0, 'logistic_regression': 0, 'ridge_classifier': 0, 'decision_tree_classifier': 1, 'random_forest_classifier': 0, 'gradient_boosting_classifier': 0, 'support_vector_machine_classifier': 0, 'x_gradient_boosting_classifier': 0}",FN
...,...,...,...,...,...,...
4841,LONDON MarketWatch -- Share prices ended lower in London Monday as a rebound in bank stocks failed to offset broader weakness for the FTSE 100 .,0,[-9.97306556e-02 1.64349496e-01 1.71351619e-02 7.13192746e-02\n 1.75899908e-01 -1.15603261e-01 -8.73757303e-02 -3.37601155e-02\n 5.58915287e-02 1.69525981e+00 -4.03638840e-01 3.41098830e-02\n 1.48271397e-01 -5.36716953e-02 4.27423716e-02 3.00230049e-02\n -4.06325832e-02 1.12422264e+00 -4.39298190e-02 1.07508982e-02\n -7.20263198e-02 5.96804582e-02 4.38548550e-02 -1.71869665e-01\n 5.18397167e-02 1.47482648e-01 -3.61646675e-02 8.63183811e-02\n -4.57509570e-02 6.86240196e-02 -7.81383812e-02 6.77803857e-03\n 1.96492635e-02 3.25613059e-02 8.09665844e-02 1.05558559e-01\n 1.15658459e-03 3.71128581e-02 -1.13167958e-02 -6.61973208e-02\n -1.17063336e-02 -1.49593409e-02 1.30228832e-01 1.75232589e-02\n 3.42527404e-02 4.42111705e-05 1.07453475e-02 -6.22191653e-02\n 2....,0,"{'perceptron': 0, 'sgd_classifier': 0, 'logistic_regression': 0, 'ridge_classifier': 0, 'decision_tree_classifier': 0, 'random_forest_classifier': 0, 'gradient_boosting_classifier': 1, 'support_vector_machine_classifier': 0, 'x_gradient_boosting_classifier': 0}",TN
4842,"Rinkuskiai 's beer sales fell by 6.5 per cent to 4.16 million litres , while Kauno Alus ' beer sales jumped by 6.9 per cent to 2.48 million litres .",0,[-1.98924989e-01 3.00148040e-01 1.01390548e-01 -1.25840604e-01\n 3.24619608e-03 -1.00019135e-01 -1.24527112e-01 -5.24022356e-02\n 1.37367668e-02 1.35610378e+00 -2.27968454e-01 1.58202261e-01\n -7.28038773e-02 -4.16742004e-02 1.74741030e-01 -2.46515095e-01\n 3.43543403e-02 9.48214471e-01 -9.90116820e-02 -1.46733001e-01\n -5.03083616e-02 7.97276795e-02 2.76607871e-02 2.14223936e-02\n 8.79974142e-02 -9.17081013e-02 -1.13138795e-01 5.91326691e-02\n 1.20140046e-01 -3.84076685e-02 -3.18211094e-02 -1.06555417e-01\n -4.91127931e-02 -3.66714634e-02 2.47359928e-03 -6.18500356e-03\n -1.42085582e-01 -3.00514344e-02 5.16138040e-02 3.66412327e-02\n -6.68754056e-02 -4.96820062e-02 1.96969017e-01 -2.14436855e-02\n 3.49904411e-02 8.42073932e-02 5.88495322e-02 2.23803204e-02\n -1....,0,"{'perceptron': 0, 'sgd_classifier': 0, 'logistic_regression': 0, 'ridge_classifier': 0, 'decision_tree_classifier': 1, 'random_forest_classifier': 0, 'gradient_boosting_classifier': 0, 'support_vector_machine_classifier': 0, 'x_gradient_boosting_classifier': 0}",TN
4843,"Operating profit fell to EUR 35.4 mn from EUR 68.8 mn in 2007 , including vessel sales gain of EUR 12.3 mn .",0,[-1.26625523e-01 2.81394184e-01 1.47076428e-01 -8.27063471e-02\n 1.89998314e-01 -1.95341870e-01 4.09874618e-02 4.50612567e-02\n 1.91018894e-01 1.17237604e+00 -3.50073159e-01 1.32276177e-01\n 1.80098731e-02 -3.21719684e-02 1.55063599e-01 -1.11439444e-01\n 5.50558940e-02 1.04285705e+00 -1.20266512e-01 4.59595509e-02\n 1.10065266e-01 5.54235131e-02 -1.12656087e-01 -1.29508138e-01\n 1.33550599e-01 9.51396152e-02 -5.79518043e-02 -1.48020387e-01\n -5.75628951e-02 1.92942038e-01 5.40777408e-02 -1.02687180e-01\n -9.71201211e-02 7.68551379e-02 1.51430340e-02 -7.59296939e-02\n -1.33880302e-01 -6.48121685e-02 8.27361941e-02 1.65923476e-01\n -6.65841550e-02 -5.17907441e-02 1.25316873e-01 -8.98319855e-02\n -1.09120391e-01 8.51464048e-02 9.52818319e-02 8.35352391e-02\n 2....,0,"{'perceptron': 0, 'sgd_classifier': 0, 'logistic_regression': 0, 'ridge_classifier': 0, 'decision_tree_classifier': 0, 'random_forest_classifier': 0, 'gradient_boosting_classifier': 0, 'support_vector_machine_classifier': 0, 'x_gradient_boosting_classifier': 0}",TN
4844,"Net sales of the Paper segment decreased to EUR 221.6 mn in the second quarter of 2009 from EUR 241.1 mn in the second quarter of 2008 , while operating profit excluding non-recurring items rose to EUR 8.0 mn from EUR 7.6 mn .",0,[-1.32034168e-01 2.24063978e-01 3.11533064e-02 1.04350876e-02\n 1.56703591e-01 -1.01873629e-01 2.23107524e-02 5.80221787e-02\n 1.09591357e-01 1.37637448e+00 -3.08786511e-01 6.17817082e-02\n 9.21739489e-02 -4.09597717e-02 1.86670780e-01 -2.55621858e-02\n 5.35475016e-02 1.13686538e+00 -8.73383507e-02 -2.77639553e-02\n 4.91071157e-02 6.25430942e-02 -9.91906524e-02 -4.09849957e-02\n 1.23337105e-01 8.61576125e-02 -1.24529265e-01 -8.46296623e-02\n -1.07371166e-01 1.51070386e-01 1.05449930e-02 -4.81814779e-02\n -1.36766464e-01 9.01109204e-02 2.72464938e-02 1.43071718e-03\n -1.20931201e-01 2.54633697e-03 1.08788302e-02 3.64606492e-02\n 3.07067460e-03 8.49255845e-02 1.09374307e-01 -5.65562025e-02\n -2.14073937e-02 4.81035821e-02 1.16443343e-01 5.90736568e-02\n 1....,0,"{'perceptron': 0, 'sgd_classifier': 0, 'logistic_regression': 0, 'ridge_classifier': 0, 'decision_tree_classifier': 0, 'random_forest_classifier': 0, 'gradient_boosting_classifier': 0, 'support_vector_machine_classifier': 0, 'x_gradient_boosting_classifier': 0}",TN
4845,"Sales in Finland decreased by 10.5 % in January , while sales outside Finland dropped by 17 % .",0,[-2.11000890e-01 3.38408977e-01 2.79511586e-02 -6.04719371e-02\n 1.00033201e-01 -1.23005114e-01 -2.58821696e-02 -3.29742618e-02\n 2.08791532e-02 1.56804836e+00 -3.97868901e-01 1.73305854e-01\n -1.92171901e-01 3.62741612e-02 -4.00141208e-03 -1.44216970e-01\n 8.82210955e-02 1.20483148e+00 -1.19249322e-01 -2.27035824e-02\n -7.42047001e-03 2.96443445e-03 4.77242656e-02 -5.48094772e-02\n 4.66798693e-02 -3.94312143e-02 -1.53847948e-01 6.67186901e-02\n -3.74379009e-02 5.33582866e-02 -5.51761575e-02 -1.21744961e-01\n -1.30150259e-01 6.22810051e-02 4.27318439e-02 9.83037148e-03\n -2.44952291e-02 -3.26079540e-02 1.40232638e-01 -1.30875155e-01\n 1.03321888e-01 -7.45608285e-02 1.20164745e-01 1.58372801e-02\n 2.28052661e-02 8.12419355e-02 4.02745716e-02 -6.35905340e-02\n 1....,0,"{'perceptron': 0, 'sgd_classifier': 0, 'logistic_regression': 0, 'ridge_classifier': 0, 'decision_tree_classifier': 0, 'random_forest_classifier': 0, 'gradient_boosting_classifier': 0, 'support_vector_machine_classifier': 0, 'x_gradient_boosting_classifier': 0}",TN

| $ y $ | $ y_{hat} $ | Outcome |
|----------------|----------------|----------|
| 1              | 1              | **TP**   |
| 1              | 0              | **FN**  (miss out) |
| 0              | 0              | **TN**   |
| 0              | 1              | **FP**  (inflate) |

**Confusion Matrix (sklearn-style layout)**

| y \ y_hat |   0   |   1   |
|-----------|-------|-------|
| **0**     |  TN   |  FP  (inflate) |
| **1**     |  FN  (miss out) |  TP   |

## Linguistic Features

### Structures of a prediction

|  |   Investigation of Future Reference Expression in Trend Info by Nakajima et al., (2014)   |   spaCy   |
|-----------|-------|-------|
| 1     |  [Action]*[State Change]   |  AUX + VERB |

In [12]:
aux_verb_sentences = []
disable_components = []

class_names = mv_with_class_df['Class'].unique()

for class_name in class_names:
    print(f"\t\tCLASS: {class_name}")
    filt_class_name = (mv_with_class_df['Class'] == class_name)
    class_df = mv_with_class_df[filt_class_name]

    # EXTRACT FEATURES
    spacy_fe = SpacyFeatureExtraction(class_df, 'Base Sentence')
    # ner_df = spacy_fe.extract_ner_features(disable_components, visualize=False)
    pos_df = spacy_fe.extract_pos_features(disable_components, visualize=False)
    # print(pos_df['Term'].value_counts())
    # print(pos_df['Dependency'].value_counts())
    # print(pos_df['POS Label'].value_counts())

    # Future-related contains :: spaCy
    aux_sentences = set(pos_df[pos_df['POS Label'] == 'AUX']['Sentence'].tolist())
    verb_sentences = set(pos_df[pos_df['POS Label'] == 'VERB']['Sentence'].tolist())
    class_aux_verb_sentences = aux_sentences & verb_sentences

    for sentence in class_aux_verb_sentences:
        aux_verb_sentences.append({
            'Class': class_name,
            'Sentence': sentence
        })

    percentage_aux_verb_within_class = round(len(class_aux_verb_sentences) / len(class_df) * 100, 2)
    print(f"\n\t\tCLASS: {class_name}")
    print(f"Number of sentences with AUX + VERB: {len(class_aux_verb_sentences)} out of {len(class_df)} = {percentage_aux_verb_within_class}%")
    for sentence in list(class_aux_verb_sentences)[:3]:
        print(f"  - {sentence}")
    print("#" * 50)
    print()

		CLASS: TP

==================================================
EXTRACTING POS FEATURES
==================================================

Extracting POS Features: 100%|██████████| 388/388 [00:01<00:00, 305.16doc/s]

==================================================
DONE EXTRACTING POS FEATURES
==================================================

		CLASS: TP
Number of sentences with AUX + VERB: 319 out of 388 = 82.22%
  - Master of Mayawas jointly developed by Nokia Siemens Networks and UFA - FremantleMedia , and will be actively advertised by Maxis in the end of May 2007 .
  - The acquisition will considerably increase Kemira 's sales and market position in the Russian metal industry coatings market .
  - The share sale , to foreign and Finnish investors , is expected to raise some euro300 million ( US$ 380 million ) .
##################################################

		CLASS: FN

==================================================
EXTRACTING POS FEATURES
==================================================

Extracting POS Features: 100%|██████████| 70/70 [00:00<00:00, 264.28doc/s]

==================================================
DONE EXTRACTING POS FEATURES
==================================================

		CLASS: FN
Number of sentences with AUX + VERB: 50 out of 70 = 71.43%
  - The office space will rise above the remodeled Cannon Street underground station .
  - `` We are proud to welcome another distribution facility to north Mississippi and the region known as the logistics center of the United States , '' said Gray Swoope , executive director of MDA .
  - Mr. Atul Chopra , Chief Operating Officer & President , Tecnotree elaborated '' I am eager to see the continued success of the former Tecnomen , bringing Lifetree product to MENA , under the Tecnotree umbrella .
##################################################

		CLASS: FP

==================================================
EXTRACTING POS FEATURES
==================================================

Extracting POS Features: 100%|██████████| 1852/1852 [00:06<00:00, 295.04doc/s]

==================================================
DONE EXTRACTING POS FEATURES
==================================================

		CLASS: FP
Number of sentences with AUX + VERB: 1311 out of 1852 = 70.79%
  - Olvi has posted a strong set of figures for the first six months of this year .
  - Incap Contract Manufacturing will carry out the manufacturing for these agreements at its factory in Tumkur , near Bangalore .
  - The shares shall be repurchased through public trading , for which reason the shares are repurchased otherwise than in proportion to the holdings of the shareholders .
##################################################

		CLASS: TN

==================================================
EXTRACTING POS FEATURES
==================================================

Extracting POS Features: 100%|██████████| 2536/2536 [00:08<00:00, 283.43doc/s]

==================================================
DONE EXTRACTING POS FEATURES
==================================================

		CLASS: TN
Number of sentences with AUX + VERB: 1054 out of 2536 = 41.56%
  - The new factory working model and reorganisations would decrease Nokian Tyres ' costs in the factory by EUR 30 million ( USD 38.7 m ) .
  - The repurchase of the bonds was executed in the open market in accordance with section 7 f of the terms and conditions of the Convertible Bonds .
  - Sales in Latin America increased by 42 % to EUR 432mn , and a total of 8.7 mn mobile devices were sold in the area , representing an increase of 32 % from the corresponding period in 2009 .
##################################################

## Takeaways

1. **TP (correct predictions):** 82.22% contain AUX + VERB, so the future-related structure is a strong but NOT a full indicator of a prediction because ~18% are correctly identified without this structure.

2. **FN (missed predictions):** 71.43% contain AUX + VERB, yet the model still misclassified them as non-predictions. This suggests the models may have failed learning the explicit future-related structure in some cases.

3. **FP (inflated predictions):** 70.79% contain AUX + VERB — too close to FN. This shows that AUX + VERB alone $\nrightarrow$ prediction.

4. **TN (correct non-predictions):** 41.56% contain AUX + VERB — the lowest of all, so most non-predictions do NOT carry future-related structure.

In [13]:
# Create dataframe
aux_verb_df = pd.DataFrame(aux_verb_sentences)
aux_verb_df

,Class,Sentence
0,TP,"Master of Mayawas jointly developed by Nokia Siemens Networks and UFA - FremantleMedia , and will be actively advertised by Maxis in the end of May 2007 ."
1,TP,The acquisition will considerably increase Kemira 's sales and market position in the Russian metal industry coatings market .
2,TP,"The share sale , to foreign and Finnish investors , is expected to raise some euro300 million ( US$ 380 million ) ."
3,TP,"Later on , about 150 Finnish-made houses will be build in the area ."
4,TP,"In addition to fireplace exports , demand for lining stone has exceeded the level of the earlier part of the year and will continue to be clearly brisker for the remainder of the year ."
...,...,...
2729,TN,"POYRY PLC Additional information by : Martin Kuzaj , President , Industry Business Group , Finland Tel. +358 10 33 21179 Sanna Paivaniemi , Director , Investor Relations , Poyry PLC , Finland Tel. +358 10 33 23002 Poyry is a global consulting and engineering company dedicated to balanced sustainability ."
2730,TN,"The brokerage said 2006 has seen a ` true turning point ' in European steel base prices , with better pricing seen carrying through the second quarter of 2006 ."
2731,TN,"Asimilar agreement was signed between China Mobile Ltd. ( SEHK : 0941 and NYSE : CHL ) , the largest mobile carrier , and theGPS and social networking service provider , promoting GyPSii service before Beijing 2008 Olympic Games , according to thelatest news ."
2732,TN,"MILAN ( AFX ) - The Italian shipping group Grimaldi has increased its stake in the Finnish company Finnlines to 35.4 pct from the 30.5 pct held in June , according to news agency ANSA ."
2733,TN,"In the method the smelt spouts 2 are separated from the working area 6 by a shielding wall 8 , 10 arranged movable in relation to the smelt spouts ."

In [14]:
aux_verb_df['Class'].value_counts()

Class
FP    1311
TN    1054
TP     319
FN      50
Name: count, dtype: int64

In [15]:
filt_nav = aux_verb_df['Class'] == "TP"
tp_nav_df = aux_verb_df[filt_nav]
tp_nav_df

,Class,Sentence
0,TP,"Master of Mayawas jointly developed by Nokia Siemens Networks and UFA - FremantleMedia , and will be actively advertised by Maxis in the end of May 2007 ."
1,TP,The acquisition will considerably increase Kemira 's sales and market position in the Russian metal industry coatings market .
2,TP,"The share sale , to foreign and Finnish investors , is expected to raise some euro300 million ( US$ 380 million ) ."
3,TP,"Later on , about 150 Finnish-made houses will be build in the area ."
4,TP,"In addition to fireplace exports , demand for lining stone has exceeded the level of the earlier part of the year and will continue to be clearly brisker for the remainder of the year ."
...,...,...
314,TP,"According shipping company Viking Line , the EU decision will have a significant financial impact ."
315,TP,"She will succeed Krister Kylas , who has decided to leave TeliaSonera ."
316,TP,TomTom has given assurances that it will continue to sell maps to competitors if it wins EU approval .
317,TP,"H+_kan Dahlstr+ï¿½m , head of mobility services at TeliaSonera , has forecast that mobile data volume on the TeliaSonera network in Sweden will rise eight-fold to 200,000 TB by 2014 ."
318,TP,As an overall effect of the above-mentioned measures Glaston will recognize non-recurring expenses of EUR 12 million in the fourth quarter of 2008 .

In [16]:
filt_nav = aux_verb_df['Class'] == "FN"
fn_nav_df = aux_verb_df[filt_nav]
fn_nav_df

,Class,Sentence
319,FN,The office space will rise above the remodeled Cannon Street underground station .
320,FN,"`` We are proud to welcome another distribution facility to north Mississippi and the region known as the logistics center of the United States , '' said Gray Swoope , executive director of MDA ."
321,FN,"Mr. Atul Chopra , Chief Operating Officer & President , Tecnotree elaborated '' I am eager to see the continued success of the former Tecnomen , bringing Lifetree product to MENA , under the Tecnotree umbrella ."
322,FN,"Reporting in accordance with the merged business operations will start as of January 1 , 2011 ."
323,FN,"Arto Ryymin , born 1964 , will replace Juhani Kaisanlahti who has worked as acting EVP , Healthcare & Welfare since August 2007 ."
324,FN,"UPM said the move will lower net profit by x20ac 385 million US$ 520 million in the second quarter , mainly due to impairment charges ."
325,FN,"The machine will have an annual production capacity of 200,000 tonnes of super-calendered magazine paper and other paper grades based on recovered fiber , Stora Enso said ."
326,FN,"By the end of 2006 , the number of joint branch offices will total 170 ."
327,FN,"Cencorp 's net sales in the first quarter is estimated to be EUR0.9-1 .2 m , as compared to EUR4 .5 m in the first quarter 2008 ."
328,FN,The transactions would increase earnings per share in the first quarter by some EUR0 .28 .
329,FN,Elcoteq expects its net sales for the last quarter of 2010 to be on the level of the third quarter .
330,FN,"Thus the group 's balance sheet will have about EUR 25.8 million of goodwill , the company added ."
331,FN,EBIT excluding non-recurring items was estimated to increase from 2009 .
332,FN,It is estimated that the consolidated turnover of Kausta Guder will reach Lt 53mn US$ 22.53 mn EUR 15.35 mn in 2007 .
333,FN,"An additional amount , capped at EUR12m , is payable in cash upon the achievement of certain financial performance targets in 2007 ."
334,FN,"LLC , a voice and data management solution provider to wireless companies with operations worldwide , will be transferring its U.S. deployment operations to the Finnish mobile giant , which includes civil works and site acquisition services ."
335,FN,"Deliveries of Nokia 1112 , Nokia 2310 and Nokia 2610 are expected to start in the second quarter of 2006 ."
336,FN,"The estimated turnover of the new company is LVL 2,5 million EEK 40 million ."
337,FN,"The train is expected to cross the Russian territory in 9 days , reaching the Vostochny port ."
338,FN,"Based on the 2005 calendar year the combined company had EUR15 .8 bn in pro forma annual revenues and is expected to start operations with 60,000 employees ."
339,FN,The plant would use palm oil certified by the Roundtable on Sustainable Palm Oil ( RSPO ) .
340,FN,"The construction of a large woodworking facility in the Sheksna district of the Vologda Region , in northwest Russia , will begin in 2009 , and the plant will start production in 2011 ."
341,FN,"Based on the design of previous handsets , the Nokia E72 and Nokia E63 this Symbian-based model is promised to offer direct access to over 90 per cent of the world s corporate email through Mail for Exchange and IBM Lotus Notes Traveler ."
342,FN,"Earnings per share EPS are seen at EUR 0.56 , up from EUR 0.38 ."
343,FN,Finnish KCI Konecranes has raised its net sales growth estimate for 2006 from over 25 % to over 35 % .
344,FN,"The transaction , which includes US$ 1.5 billion euro1 billion in cash , vendor notes and share purchases , is expected to be completed in the first quarter of 2008 , the Finnish-Swedish paper maker said ."
345,FN,"Fortum expects its annual capital expenditure in the next four to five years to be within a range of EUR 0.8-1 .2 billion , as earlier announced ."
346,FN,"`` The implementation of these programs has had , and will have , negative impacts on 2006 and 2007 earnings , '' Mr Meiklejohn said ."
347,FN,Both sources said Nokia would unveil its new phone code-named `` Tube '' on Oct. 2 at an analyst and media event in London .
348,FN,"As a result of the merger , the largest professional electronics and telecommunications technology contract manufacturing center in Finland will be formed in Sievi ."
349,FN,"Subscribers of China Unicom , the nation 's second largest mobile phone operator after China Mobile , are expected to release pictures , videos and blog on the Internet via mobile phones as of March 2008 ."
350,FN,"Konecranes has previously communicated an estimated reduction of about 1,600 employees on group level in 2009 ."
351,FN,"Finnish soapstone processing and fireplaces maker Tulikivi Oyj said on February 26 , 2007 it would cut less than 20 jobs from its fireplace sales organization , production facilities and its subsidiary Kermansavi Oy ."
352,FN,"The Innova 2 building will be located close to downtown , in the immediate vicinity of Paviljonki and the travel center , and within walking distance from the heart of the city thanks to the trade fair bridge ."
353,FN,As a result of the negotiations the employment of 130 blue - and white-collar employees at the Oulu plant would be terminated .
354,FN,"Demonstrations of the broad capabilities of the Mobility Business Suite will be organized during the 3GSM World Congress in Barcelona , from February 12th to 15th ."
355,FN,Stora Enso Oyj said its second-quarter result would fall by half compared with the same period in 2007 .
356,FN,The annual value of the contracts is estimated at USD 2mn over the next three years .
357,FN,The estimated annual value of the frame agreement is about EUR 50mn .
358,FN,It has sold one half of its business operations and will enter the Helsinki Stock Exchange via the back door through an innovative buyout arrangement with Kasola .
359,FN,The deliveries started in April 2006 and will be completed in 2007 .
360,FN,"According to Scanfil , demand for telecommunications network products has fluctuated significantly in the third quarter of 2006 , and the situation is expected to remain unstable for the rest of the year ."
361,FN,"Furthermore , the company will sell the warehouse and office buildings in Loudeac and Saint Marcel and lease new joint premises for these operations in Morvillars ."
362,FN,The value of the deal is estimated at between SEK25m and SEK50m .
363,FN,The value of the three-year contract is estimated at EUR40m .
364,FN,Alfa group will have 43.9 % of voting stock in the new company and Telenor 35.4 % with a free float of 20.7 % .
365,FN,"CapMan Plc Press Release 31 March 2008 Jukka Ruuska , President of the OMX Nordic Exchanges and the Stockholm Stock Exchange , will transfer to CapMan effective no later than September 2008 ."
366,FN,"The relocation of Ragot has already started and will be completed in the next few weeks , with the Waterqueen and Tortue moves planned for mid-2008 and VMC Europe during the third quarter of 2008 ."
367,FN,"Net sales will , however , increase from 2005 ."
368,FN,"On the other hand , Montevideo said that having the two mills working in the area will generate jobs ."