# Error Analysis: Identify characteristics of misclassified sentences

- For the sentences that were incorrectly classified, what are the characteristics in them?
- For the ones that are classified as a prediction, do our prediction properties exist?

---

## TODOs

1. Majority Vote (mv): to get the ultimate $ y_{hat} $ label
    1. Do models (mv) tend to be correct or incorrect?
2. Fliess Kappa: to measure agreement
    1. Do models tend to agree and be correct or incorrect?
3. K-Means: plotting where

In [1]:
import os
import sys

import numpy as np
import pandas as pd



notebook_dir = os.getcwd()

sys.path.append(os.path.join(notebook_dir, '../'))

from data_processing import DataProcessing
from data_visualizing import DataVisualizing
from feature_extraction import SpacyFeatureExtraction

In [2]:
pd.set_option('max_colwidth', 800)
# pd.set_option('display.max_columns', None)
# pd.set_option('display.max_columns', 40)
# pd.set_option('display.max_rows', None)

## Load Data

In [3]:
base_data_path = DataProcessing.load_base_data_path(notebook_dir)
# combine_data_path = os.path.join(base_data_path, 'financial_phrase_bank/combined_generated_fin_phrase_bank')
train_data = os.path.join(base_data_path, 'classification_results/train_synthetic-v1_2026-03-23/seed3')

In [4]:
# model_results_path = os.path.join(combine_data_path, 'inference_chronicle2050_2026-03-07_21-51-47.csv')
test_data = os.path.join(train_data, 'external_fpb-maya-binary-imbalanced-96d-v1/', 'ml_classifiers_fpb-maya-binary-imbalanced-96d-v1.csv')

model_results_df = DataProcessing.load_from_file(test_data, 'csv', sep=',')
cols_to_drop = ["Dataset Name", "Author Type", "maya_label"]
compare_y_vs_yhats_df = DataProcessing.drop_df_columns(model_results_df, cols_to_drop)
compare_y_vs_yhats_df

,Base Sentence,Sentence Label,Base Sentence Embedding,perceptron,sgd_classifier,logistic_regression,ridge_classifier,decision_tree_classifier,random_forest_classifier,gradient_boosting_classifier,support_vector_machine_classifier,x_gradient_boosting_classifier
0,With the new production plant the company would increase its capacity to meet the expected increase in demand and would improve the use of raw materials and therefore increase the production profitability .,1,[-1.22568220e-01 2.48624131e-01 -4.82655168e-02 -1.09789923e-01\n -8.58348906e-02 3.63291465e-02 -1.27964811e-02 7.17335939e-02\n -1.18364163e-01 2.27930522e+00 -3.32476139e-01 -1.46164745e-02\n 1.25499114e-01 7.25146085e-02 6.57393187e-02 -5.76901138e-02\n -2.05907249e-03 1.51917112e+00 -3.29480022e-01 -4.57408801e-02\n 2.22120117e-02 1.05339624e-01 -4.22692373e-02 -1.23566784e-01\n -5.79119613e-03 6.18153140e-02 -5.48806489e-02 2.96797305e-02\n -1.07008472e-01 -9.98812243e-02 -9.39770564e-02 3.87728140e-02\n -5.82127571e-02 7.14930072e-02 9.65250358e-02 -3.75642404e-02\n 7.18023349e-03 6.21852428e-02 7.68979266e-02 -1.69069305e-01\n 1.44475931e-03 7.71993026e-02 3.41709815e-02 -1.10992551e-01\n -1.81387588e-02 -8.61631632e-02 -2.34903637e-02 6.00658916e-02\n -3....,1,1,1,1,0,1,1,1,1
1,"According to the company 's updated strategy for the years 2009-2012 , Basware targets a long-term net sales growth in the range of 20 % -40 % with an operating profit margin of 10 % -20 % of net sales .",1,[-2.63320029e-01 3.28540474e-01 4.48558182e-02 -1.09422831e-02\n 3.39385755e-02 -1.25387803e-01 2.09340192e-02 8.32975954e-02\n 1.10356383e-01 1.74510765e+00 -3.98153275e-01 1.41264707e-01\n -8.98099765e-02 -1.47727029e-02 5.77163734e-02 -5.09223454e-02\n -4.27257568e-02 1.41277170e+00 -2.09747717e-01 1.56779997e-02\n -3.64826852e-03 5.97854443e-02 -7.89400712e-02 -1.39893517e-02\n 1.13595366e-01 9.83026922e-02 -5.14178127e-02 7.06899390e-02\n 2.47105230e-02 1.06609218e-01 -4.19648038e-03 -1.85196903e-02\n -1.48957130e-02 9.90139246e-02 1.10973224e-01 -2.59710420e-02\n -6.08825274e-02 4.48305123e-02 4.36691009e-02 -9.27021950e-02\n 6.36729002e-02 1.98753644e-02 2.10891932e-01 -8.54000822e-02\n 4.67465706e-02 -2.04764325e-02 -3.69948000e-02 1.16207667e-01\n 1....,1,1,0,0,1,1,1,0,1
2,TeliaSonera TLSN said the offer is in line with its strategy to increase its ownership in core business holdings and would strengthen Eesti Telekom 's offering to its customers .,1,[ 1.15080299e-02 1.98225155e-01 1.95062440e-02 -5.97744621e-02\n 1.75585955e-01 -1.25474662e-01 -3.72287892e-02 -2.83286646e-02\n -3.56662273e-02 1.96045303e+00 -2.79843062e-01 -1.04898110e-01\n 4.49508205e-02 1.31481076e-02 6.55795187e-02 -4.11130209e-03\n -5.56710083e-03 1.11790729e+00 -1.21459611e-01 -9.75316912e-02\n 2.18506586e-02 1.38311490e-01 9.17155594e-02 -5.85136563e-02\n 1.03342809e-01 7.32071251e-02 -3.92427929e-02 1.13294438e-01\n -1.07247204e-01 5.58346435e-02 -9.28281173e-02 5.48683619e-03\n -1.84886660e-02 5.24056628e-02 4.05881368e-02 -8.35432187e-02\n 1.13391867e-02 2.78038122e-02 -5.44880610e-03 -1.02035753e-01\n -6.69988245e-02 7.79658780e-02 5.37769347e-02 -1.39616817e-01\n 2.96867881e-02 1.13102477e-02 -3.53476144e-02 -1.88835058e-02\n -4....,1,1,1,1,1,1,1,1,1
3,"STORA ENSO , NORSKE SKOG , M-REAL , UPM-KYMMENE Credit Suisse First Boston ( CFSB ) raised the fair value for shares in four of the largest Nordic forestry groups .",1,[-5.94305294e-03 1.57299116e-01 -1.01663664e-01 -4.74716797e-02\n 1.79840446e-01 2.63532978e-02 4.07044962e-02 -3.17418873e-02\n -1.32127828e-03 1.28309309e+00 -3.01563025e-01 4.19499092e-02\n 4.76229452e-02 -1.16947450e-01 -1.42535036e-02 2.37643998e-02\n -3.57760116e-02 8.38545859e-01 -5.43218441e-02 2.42432952e-03\n 7.67285563e-03 4.88467440e-02 4.74129207e-02 -2.67546187e-04\n 6.47759363e-02 7.66171236e-03 -7.71588413e-03 6.14660196e-02\n 9.25298501e-03 1.29891783e-01 6.76145032e-02 -7.35822739e-03\n 3.22291143e-02 1.50113806e-01 1.32441163e-01 -9.81159508e-03\n -1.39411157e-02 1.04931206e-03 -1.90248825e-02 -9.27351974e-03\n -2.62032263e-02 7.86117762e-02 8.33134279e-02 2.64521260e-02\n -1.58701912e-02 9.79095325e-03 3.53994928e-02 -1.72072705e-02\n 7....,0,0,0,0,1,0,0,0,0
4,The company also estimates the already carried out investments to lead to an increase in its net sales for 2010 from 2009 when they reached EUR 141.7 million .,1,[-9.75671411e-02 2.17742935e-01 -5.24893478e-02 2.29859371e-02\n 1.95262451e-02 -3.96593288e-02 -2.93270722e-02 1.45730842e-02\n 8.01267326e-02 2.14558053e+00 -3.02207738e-01 7.73812085e-02\n 9.75400433e-02 -5.86019419e-02 2.85570417e-02 -6.01695329e-02\n -6.48141513e-03 1.10976875e+00 -1.62209153e-01 -2.63800696e-02\n 6.90186918e-02 5.40496930e-02 -4.89046909e-02 -1.06065851e-02\n 3.81638743e-02 8.63624960e-02 -1.46540195e-01 -7.51399994e-02\n -5.42312972e-02 -2.43689902e-02 3.15490589e-02 -7.77387097e-02\n -1.04405805e-01 1.55526847e-01 2.55947262e-02 -2.01004483e-02\n -4.33546826e-02 2.11381875e-02 9.09157470e-02 -9.94266123e-02\n -5.63282613e-03 7.87854865e-02 1.45106107e-01 -1.49363369e-01\n 2.86051352e-02 -9.17335041e-03 -3.88870686e-02 -1.43906018e-02\n 2....,1,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
4841,LONDON MarketWatch -- Share prices ended lower in London Monday as a rebound in bank stocks failed to offset broader weakness for the FTSE 100 .,0,[-9.97306556e-02 1.64349496e-01 1.71351619e-02 7.13192746e-02\n 1.75899908e-01 -1.15603261e-01 -8.73757303e-02 -3.37601155e-02\n 5.58915287e-02 1.69525981e+00 -4.03638840e-01 3.41098830e-02\n 1.48271397e-01 -5.36716953e-02 4.27423716e-02 3.00230049e-02\n -4.06325832e-02 1.12422264e+00 -4.39298190e-02 1.07508982e-02\n -7.20263198e-02 5.96804582e-02 4.38548550e-02 -1.71869665e-01\n 5.18397167e-02 1.47482648e-01 -3.61646675e-02 8.63183811e-02\n -4.57509570e-02 6.86240196e-02 -7.81383812e-02 6.77803857e-03\n 1.96492635e-02 3.25613059e-02 8.09665844e-02 1.05558559e-01\n 1.15658459e-03 3.71128581e-02 -1.13167958e-02 -6.61973208e-02\n -1.17063336e-02 -1.49593409e-02 1.30228832e-01 1.75232589e-02\n 3.42527404e-02 4.42111705e-05 1.07453475e-02 -6.22191653e-02\n 2....,0,0,0,0,0,0,1,0,0
4842,"Rinkuskiai 's beer sales fell by 6.5 per cent to 4.16 million litres , while Kauno Alus ' beer sales jumped by 6.9 per cent to 2.48 million litres .",0,[-1.98924989e-01 3.00148040e-01 1.01390548e-01 -1.25840604e-01\n 3.24619608e-03 -1.00019135e-01 -1.24527112e-01 -5.24022356e-02\n 1.37367668e-02 1.35610378e+00 -2.27968454e-01 1.58202261e-01\n -7.28038773e-02 -4.16742004e-02 1.74741030e-01 -2.46515095e-01\n 3.43543403e-02 9.48214471e-01 -9.90116820e-02 -1.46733001e-01\n -5.03083616e-02 7.97276795e-02 2.76607871e-02 2.14223936e-02\n 8.79974142e-02 -9.17081013e-02 -1.13138795e-01 5.91326691e-02\n 1.20140046e-01 -3.84076685e-02 -3.18211094e-02 -1.06555417e-01\n -4.91127931e-02 -3.66714634e-02 2.47359928e-03 -6.18500356e-03\n -1.42085582e-01 -3.00514344e-02 5.16138040e-02 3.66412327e-02\n -6.68754056e-02 -4.96820062e-02 1.96969017e-01 -2.14436855e-02\n 3.49904411e-02 8.42073932e-02 5.88495322e-02 2.23803204e-02\n -1....,0,0,0,0,1,0,0,0,0
4843,"Operating profit fell to EUR 35.4 mn from EUR 68.8 mn in 2007 , including vessel sales gain of EUR 12.3 mn .",0,[-1.26625523e-01 2.81394184e-01 1.47076428e-01 -8.27063471e-02\n 1.89998314e-01 -1.95341870e-01 4.09874618e-02 4.50612567e-02\n 1.91018894e-01 1.17237604e+00 -3.50073159e-01 1.32276177e-01\n 1.80098731e-02 -3.21719684e-02 1.55063599e-01 -1.11439444e-01\n 5.50558940e-02 1.04285705e+00 -1.20266512e-01 4.59595509e-02\n 1.10065266e-01 5.54235131e-02 -1.12656087e-01 -1.29508138e-01\n 1.33550599e-01 9.51396152e-02 -5.79518043e-02 -1.48020387e-01\n -5.75628951e-02 1.92942038e-01 5.40777408e-02 -1.02687180e-01\n -9.71201211e-02 7.68551379e-02 1.51430340e-02 -7.59296939e-02\n -1.33880302e-01 -6.48121685e-02 8.27361941e-02 1.65923476e-01\n -6.65841550e-02 -5.17907441e-02 1.25316873e-01 -8.98319855e-02\n -1.09120391e-01 8.51464048e-02 9.52818319e-02 8.35352391e-02\n 2....,0,0,0,0,0,0,0,0,0
4844,"Net sales of the Paper segment decreased to EUR 221.6 mn in the second quarter of 2009 from EUR 241.1 mn in the second quarter of 2008 , while operating profit excluding non-recurring items rose to EUR 8.0 mn from EUR 7.6 mn .",0,[-1.32034168e-01 2.24063978e-01 3.11533064e-02 1.04350876e-02\n 1.56703591e-01 -1.01873629e-01 2.23107524e-02 5.80221787e-02\n 1.09591357e-01 1.37637448e+00 -3.08786511e-01 6.17817082e-02\n 9.21739489e-02 -4.09597717e-02 1.86670780e-01 -2.55621858e-02\n 5.35475016e-02 1.13686538e+00 -8.73383507e-02 -2.77639553e-02\n 4.91071157e-02 6.25430942e-02 -9.91906524e-02 -4.09849957e-02\n 1.23337105e-01 8.61576125e-02 -1.24529265e-01 -8.46296623e-02\n -1.07371166e-01 1.51070386e-01 1.05449930e-02 -4.81814779e-02\n -1.36766464e-01 9.01109204e-02 2.72464938e-02 1.43071718e-03\n -1.20931201e-01 2.54633697e-03 1.08788302e-02 3.64606492e-02\n 3.07067460e-03 8.49255845e-02 1.09374307e-01 -5.65562025e-02\n -2.14073937e-02 4.81035821e-02 1.16443343e-01 5.90736568e-02\n 1....,0,0,0,0,0,0,0,0,0
4845,"Sales in Finland decreased by 10.5 % in January , while sales outside Finland dropped by 17 % .",0,[-2.11000890e-01 3.38408977e-01 2.79511586e-02 -6.04719371e-02\n 1.00033201e-01 -1.23005114e-01 -2.58821696e-02 -3.29742618e-02\n 2.08791532e-02 1.56804836e+00 -3.97868901e-01 1.73305854e-01\n -1.92171901e-01 3.62741612e-02 -4.00141208e-03 -1.44216970e-01\n 8.82210955e-02 1.20483148e+00 -1.19249322e-01 -2.27035824e-02\n -7.42047001e-03 2.96443445e-03 4.77242656e-02 -5.48094772e-02\n 4.66798693e-02 -3.94312143e-02 -1.53847948e-01 6.67186901e-02\n -3.74379009e-02 5.33582866e-02 -5.51761575e-02 -1.21744961e-01\n -1.30150259e-01 6.22810051e-02 4.27318439e-02 9.83037148e-03\n -2.44952291e-02 -3.26079540e-02 1.40232638e-01 -1.30875155e-01\n 1.03321888e-01 -7.45608285e-02 1.20164745e-01 1.58372801e-02\n 2.28052661e-02 8.12419355e-02 4.02745716e-02 -6.35905340e-02\n 1....,0,0,0,0,0,0,0,0,0

In [5]:
model_col_names = compare_y_vs_yhats_df.columns.to_list()[3:]
model_col_names, len(model_col_names)

(['perceptron',
  'sgd_classifier',
  'logistic_regression',
  'ridge_classifier',
  'decision_tree_classifier',
  'random_forest_classifier',
  'gradient_boosting_classifier',
  'support_vector_machine_classifier',
  'x_gradient_boosting_classifier'],
 9)

In [6]:
compare_y_vs_mv_df = compare_y_vs_yhats_df[model_col_names].mode(axis=1)
compare_y_vs_yhats_df['Majority Vote'] = compare_y_vs_mv_df
compare_y_vs_yhats_df

,Base Sentence,Sentence Label,Base Sentence Embedding,perceptron,sgd_classifier,logistic_regression,ridge_classifier,decision_tree_classifier,random_forest_classifier,gradient_boosting_classifier,support_vector_machine_classifier,x_gradient_boosting_classifier,Majority Vote
0,With the new production plant the company would increase its capacity to meet the expected increase in demand and would improve the use of raw materials and therefore increase the production profitability .,1,[-1.22568220e-01 2.48624131e-01 -4.82655168e-02 -1.09789923e-01\n -8.58348906e-02 3.63291465e-02 -1.27964811e-02 7.17335939e-02\n -1.18364163e-01 2.27930522e+00 -3.32476139e-01 -1.46164745e-02\n 1.25499114e-01 7.25146085e-02 6.57393187e-02 -5.76901138e-02\n -2.05907249e-03 1.51917112e+00 -3.29480022e-01 -4.57408801e-02\n 2.22120117e-02 1.05339624e-01 -4.22692373e-02 -1.23566784e-01\n -5.79119613e-03 6.18153140e-02 -5.48806489e-02 2.96797305e-02\n -1.07008472e-01 -9.98812243e-02 -9.39770564e-02 3.87728140e-02\n -5.82127571e-02 7.14930072e-02 9.65250358e-02 -3.75642404e-02\n 7.18023349e-03 6.21852428e-02 7.68979266e-02 -1.69069305e-01\n 1.44475931e-03 7.71993026e-02 3.41709815e-02 -1.10992551e-01\n -1.81387588e-02 -8.61631632e-02 -2.34903637e-02 6.00658916e-02\n -3....,1,1,1,1,0,1,1,1,1,1
1,"According to the company 's updated strategy for the years 2009-2012 , Basware targets a long-term net sales growth in the range of 20 % -40 % with an operating profit margin of 10 % -20 % of net sales .",1,[-2.63320029e-01 3.28540474e-01 4.48558182e-02 -1.09422831e-02\n 3.39385755e-02 -1.25387803e-01 2.09340192e-02 8.32975954e-02\n 1.10356383e-01 1.74510765e+00 -3.98153275e-01 1.41264707e-01\n -8.98099765e-02 -1.47727029e-02 5.77163734e-02 -5.09223454e-02\n -4.27257568e-02 1.41277170e+00 -2.09747717e-01 1.56779997e-02\n -3.64826852e-03 5.97854443e-02 -7.89400712e-02 -1.39893517e-02\n 1.13595366e-01 9.83026922e-02 -5.14178127e-02 7.06899390e-02\n 2.47105230e-02 1.06609218e-01 -4.19648038e-03 -1.85196903e-02\n -1.48957130e-02 9.90139246e-02 1.10973224e-01 -2.59710420e-02\n -6.08825274e-02 4.48305123e-02 4.36691009e-02 -9.27021950e-02\n 6.36729002e-02 1.98753644e-02 2.10891932e-01 -8.54000822e-02\n 4.67465706e-02 -2.04764325e-02 -3.69948000e-02 1.16207667e-01\n 1....,1,1,0,0,1,1,1,0,1,1
2,TeliaSonera TLSN said the offer is in line with its strategy to increase its ownership in core business holdings and would strengthen Eesti Telekom 's offering to its customers .,1,[ 1.15080299e-02 1.98225155e-01 1.95062440e-02 -5.97744621e-02\n 1.75585955e-01 -1.25474662e-01 -3.72287892e-02 -2.83286646e-02\n -3.56662273e-02 1.96045303e+00 -2.79843062e-01 -1.04898110e-01\n 4.49508205e-02 1.31481076e-02 6.55795187e-02 -4.11130209e-03\n -5.56710083e-03 1.11790729e+00 -1.21459611e-01 -9.75316912e-02\n 2.18506586e-02 1.38311490e-01 9.17155594e-02 -5.85136563e-02\n 1.03342809e-01 7.32071251e-02 -3.92427929e-02 1.13294438e-01\n -1.07247204e-01 5.58346435e-02 -9.28281173e-02 5.48683619e-03\n -1.84886660e-02 5.24056628e-02 4.05881368e-02 -8.35432187e-02\n 1.13391867e-02 2.78038122e-02 -5.44880610e-03 -1.02035753e-01\n -6.69988245e-02 7.79658780e-02 5.37769347e-02 -1.39616817e-01\n 2.96867881e-02 1.13102477e-02 -3.53476144e-02 -1.88835058e-02\n -4....,1,1,1,1,1,1,1,1,1,1
3,"STORA ENSO , NORSKE SKOG , M-REAL , UPM-KYMMENE Credit Suisse First Boston ( CFSB ) raised the fair value for shares in four of the largest Nordic forestry groups .",1,[-5.94305294e-03 1.57299116e-01 -1.01663664e-01 -4.74716797e-02\n 1.79840446e-01 2.63532978e-02 4.07044962e-02 -3.17418873e-02\n -1.32127828e-03 1.28309309e+00 -3.01563025e-01 4.19499092e-02\n 4.76229452e-02 -1.16947450e-01 -1.42535036e-02 2.37643998e-02\n -3.57760116e-02 8.38545859e-01 -5.43218441e-02 2.42432952e-03\n 7.67285563e-03 4.88467440e-02 4.74129207e-02 -2.67546187e-04\n 6.47759363e-02 7.66171236e-03 -7.71588413e-03 6.14660196e-02\n 9.25298501e-03 1.29891783e-01 6.76145032e-02 -7.35822739e-03\n 3.22291143e-02 1.50113806e-01 1.32441163e-01 -9.81159508e-03\n -1.39411157e-02 1.04931206e-03 -1.90248825e-02 -9.27351974e-03\n -2.62032263e-02 7.86117762e-02 8.33134279e-02 2.64521260e-02\n -1.58701912e-02 9.79095325e-03 3.53994928e-02 -1.72072705e-02\n 7....,0,0,0,0,1,0,0,0,0,0
4,The company also estimates the already carried out investments to lead to an increase in its net sales for 2010 from 2009 when they reached EUR 141.7 million .,1,[-9.75671411e-02 2.17742935e-01 -5.24893478e-02 2.29859371e-02\n 1.95262451e-02 -3.96593288e-02 -2.93270722e-02 1.45730842e-02\n 8.01267326e-02 2.14558053e+00 -3.02207738e-01 7.73812085e-02\n 9.75400433e-02 -5.86019419e-02 2.85570417e-02 -6.01695329e-02\n -6.48141513e-03 1.10976875e+00 -1.62209153e-01 -2.63800696e-02\n 6.90186918e-02 5.40496930e-02 -4.89046909e-02 -1.06065851e-02\n 3.81638743e-02 8.63624960e-02 -1.46540195e-01 -7.51399994e-02\n -5.42312972e-02 -2.43689902e-02 3.15490589e-02 -7.77387097e-02\n -1.04405805e-01 1.55526847e-01 2.55947262e-02 -2.01004483e-02\n -4.33546826e-02 2.11381875e-02 9.09157470e-02 -9.94266123e-02\n -5.63282613e-03 7.87854865e-02 1.45106107e-01 -1.49363369e-01\n 2.86051352e-02 -9.17335041e-03 -3.88870686e-02 -1.43906018e-02\n 2....,1,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4841,LONDON MarketWatch -- Share prices ended lower in London Monday as a rebound in bank stocks failed to offset broader weakness for the FTSE 100 .,0,[-9.97306556e-02 1.64349496e-01 1.71351619e-02 7.13192746e-02\n 1.75899908e-01 -1.15603261e-01 -8.73757303e-02 -3.37601155e-02\n 5.58915287e-02 1.69525981e+00 -4.03638840e-01 3.41098830e-02\n 1.48271397e-01 -5.36716953e-02 4.27423716e-02 3.00230049e-02\n -4.06325832e-02 1.12422264e+00 -4.39298190e-02 1.07508982e-02\n -7.20263198e-02 5.96804582e-02 4.38548550e-02 -1.71869665e-01\n 5.18397167e-02 1.47482648e-01 -3.61646675e-02 8.63183811e-02\n -4.57509570e-02 6.86240196e-02 -7.81383812e-02 6.77803857e-03\n 1.96492635e-02 3.25613059e-02 8.09665844e-02 1.05558559e-01\n 1.15658459e-03 3.71128581e-02 -1.13167958e-02 -6.61973208e-02\n -1.17063336e-02 -1.49593409e-02 1.30228832e-01 1.75232589e-02\n 3.42527404e-02 4.42111705e-05 1.07453475e-02 -6.22191653e-02\n 2....,0,0,0,0,0,0,1,0,0,0
4842,"Rinkuskiai 's beer sales fell by 6.5 per cent to 4.16 million litres , while Kauno Alus ' beer sales jumped by 6.9 per cent to 2.48 million litres .",0,[-1.98924989e-01 3.00148040e-01 1.01390548e-01 -1.25840604e-01\n 3.24619608e-03 -1.00019135e-01 -1.24527112e-01 -5.24022356e-02\n 1.37367668e-02 1.35610378e+00 -2.27968454e-01 1.58202261e-01\n -7.28038773e-02 -4.16742004e-02 1.74741030e-01 -2.46515095e-01\n 3.43543403e-02 9.48214471e-01 -9.90116820e-02 -1.46733001e-01\n -5.03083616e-02 7.97276795e-02 2.76607871e-02 2.14223936e-02\n 8.79974142e-02 -9.17081013e-02 -1.13138795e-01 5.91326691e-02\n 1.20140046e-01 -3.84076685e-02 -3.18211094e-02 -1.06555417e-01\n -4.91127931e-02 -3.66714634e-02 2.47359928e-03 -6.18500356e-03\n -1.42085582e-01 -3.00514344e-02 5.16138040e-02 3.66412327e-02\n -6.68754056e-02 -4.96820062e-02 1.96969017e-01 -2.14436855e-02\n 3.49904411e-02 8.42073932e-02 5.88495322e-02 2.23803204e-02\n -1....,0,0,0,0,1,0,0,0,0,0
4843,"Operating profit fell to EUR 35.4 mn from EUR 68.8 mn in 2007 , including vessel sales gain of EUR 12.3 mn .",0,[-1.26625523e-01 2.81394184e-01 1.47076428e-01 -8.27063471e-02\n 1.89998314e-01 -1.95341870e-01 4.09874618e-02 4.50612567e-02\n 1.91018894e-01 1.17237604e+00 -3.50073159e-01 1.32276177e-01\n 1.80098731e-02 -3.21719684e-02 1.55063599e-01 -1.11439444e-01\n 5.50558940e-02 1.04285705e+00 -1.20266512e-01 4.59595509e-02\n 1.10065266e-01 5.54235131e-02 -1.12656087e-01 -1.29508138e-01\n 1.33550599e-01 9.51396152e-02 -5.79518043e-02 -1.48020387e-01\n -5.75628951e-02 1.92942038e-01 5.40777408e-02 -1.02687180e-01\n -9.71201211e-02 7.68551379e-02 1.51430340e-02 -7.59296939e-02\n -1.33880302e-01 -6.48121685e-02 8.27361941e-02 1.65923476e-01\n -6.65841550e-02 -5.17907441e-02 1.25316873e-01 -8.98319855e-02\n -1.09120391e-01 8.51464048e-02 9.52818319e-02 8.35352391e-02\n 2....,0,0,0,0,0,0,0,0,0,0
4844,"Net sales of the Paper segment decreased to EUR 221.6 mn in the second quarter of 2009 from EUR 241.1 mn in the second quarter of 2008 , while operating profit excluding non-recurring items rose to EUR 8.0 mn from EUR 7.6 mn .",0,[-1.32034168e-01 2.24063978e-01 3.11533064e-02 1.04350876e-02\n 1.56703591e-01 -1.01873629e-01 2.23107524e-02 5.80221787e-02\n 1.09591357e-01 1.37637448e+00 -3.08786511e-01 6.17817082e-02\n 9.21739489e-02 -4.09597717e-02 1.86670780e-01 -2.55621858e-02\n 5.35475016e-02 1.13686538e+00 -8.73383507e-02 -2.77639553e-02\n 4.91071157e-02 6.25430942e-02 -9.91906524e-02 -4.09849957e-02\n 1.23337105e-01 8.61576125e-02 -1.24529265e-01 -8.46296623e-02\n -1.07371166e-01 1.51070386e-01 1.05449930e-02 -4.81814779e-02\n -1.36766464e-01 9.01109204e-02 2.72464938e-02 1.43071718e-03\n -1.20931201e-01 2.54633697e-03 1.08788302e-02 3.64606492e-02\n 3.07067460e-03 8.49255845e-02 1.09374307e-01 -5.65562025e-02\n -2.14073937e-02 4.81035821e-02 1.16443343e-01 5.90736568e-02\n 1....,0,0,0,0,0,0,0,0,0,0
4845,"Sales in Finland decreased by 10.5 % in January , while sales outside Finland dropped by 17 % .",0,[-2.11000890e-01 3.38408977e-01 2.79511586e-02 -6.04719371e-02\n 1.00033201e-01 -1.23005114e-01 -2.58821696e-02 -3.29742618e-02\n 2.08791532e-02 1.56804836e+00 -3.97868901e-01 1.73305854e-01\n -1.92171901e-01 3.62741612e-02 -4.00141208e-03 -1.44216970e-01\n 8.82210955e-02 1.20483148e+00 -1.19249322e-01 -2.27035824e-02\n -7.42047001e-03 2.96443445e-03 4.77242656e-02 -5.48094772e-02\n 4.66798693e-02 -3.94312143e-02 -1.53847948e-01 6.67186901e-02\n -3.74379009e-02 5.33582866e-02 -5.51761575e-02 -1.21744961e-01\n -1.30150259e-01 6.22810051e-02 4.27318439e-02 9.83037148e-03\n -2.44952291e-02 -3.26079540e-02 1.40232638e-01 -1.30875155e-01\n 1.03321888e-01 -7.45608285e-02 1.20164745e-01 1.58372801e-02\n 2.28052661e-02 8.12419355e-02 4.02745716e-02 -6.35905340e-02\n 1....,0,0,0,0,0,0,0,0,0,0

In [7]:
model_col_names

['perceptron',
 'sgd_classifier',
 'logistic_regression',
 'ridge_classifier',
 'decision_tree_classifier',
 'random_forest_classifier',
 'gradient_boosting_classifier',
 'support_vector_machine_classifier',
 'x_gradient_boosting_classifier']

In [8]:
meta_data = compare_y_vs_yhats_df.iloc[:, 2:-1]
meta_data

,Base Sentence Embedding,perceptron,sgd_classifier,logistic_regression,ridge_classifier,decision_tree_classifier,random_forest_classifier,gradient_boosting_classifier,support_vector_machine_classifier,x_gradient_boosting_classifier
0,[-1.22568220e-01 2.48624131e-01 -4.82655168e-02 -1.09789923e-01\n -8.58348906e-02 3.63291465e-02 -1.27964811e-02 7.17335939e-02\n -1.18364163e-01 2.27930522e+00 -3.32476139e-01 -1.46164745e-02\n 1.25499114e-01 7.25146085e-02 6.57393187e-02 -5.76901138e-02\n -2.05907249e-03 1.51917112e+00 -3.29480022e-01 -4.57408801e-02\n 2.22120117e-02 1.05339624e-01 -4.22692373e-02 -1.23566784e-01\n -5.79119613e-03 6.18153140e-02 -5.48806489e-02 2.96797305e-02\n -1.07008472e-01 -9.98812243e-02 -9.39770564e-02 3.87728140e-02\n -5.82127571e-02 7.14930072e-02 9.65250358e-02 -3.75642404e-02\n 7.18023349e-03 6.21852428e-02 7.68979266e-02 -1.69069305e-01\n 1.44475931e-03 7.71993026e-02 3.41709815e-02 -1.10992551e-01\n -1.81387588e-02 -8.61631632e-02 -2.34903637e-02 6.00658916e-02\n -3....,1,1,1,1,0,1,1,1,1
1,[-2.63320029e-01 3.28540474e-01 4.48558182e-02 -1.09422831e-02\n 3.39385755e-02 -1.25387803e-01 2.09340192e-02 8.32975954e-02\n 1.10356383e-01 1.74510765e+00 -3.98153275e-01 1.41264707e-01\n -8.98099765e-02 -1.47727029e-02 5.77163734e-02 -5.09223454e-02\n -4.27257568e-02 1.41277170e+00 -2.09747717e-01 1.56779997e-02\n -3.64826852e-03 5.97854443e-02 -7.89400712e-02 -1.39893517e-02\n 1.13595366e-01 9.83026922e-02 -5.14178127e-02 7.06899390e-02\n 2.47105230e-02 1.06609218e-01 -4.19648038e-03 -1.85196903e-02\n -1.48957130e-02 9.90139246e-02 1.10973224e-01 -2.59710420e-02\n -6.08825274e-02 4.48305123e-02 4.36691009e-02 -9.27021950e-02\n 6.36729002e-02 1.98753644e-02 2.10891932e-01 -8.54000822e-02\n 4.67465706e-02 -2.04764325e-02 -3.69948000e-02 1.16207667e-01\n 1....,1,1,0,0,1,1,1,0,1
2,[ 1.15080299e-02 1.98225155e-01 1.95062440e-02 -5.97744621e-02\n 1.75585955e-01 -1.25474662e-01 -3.72287892e-02 -2.83286646e-02\n -3.56662273e-02 1.96045303e+00 -2.79843062e-01 -1.04898110e-01\n 4.49508205e-02 1.31481076e-02 6.55795187e-02 -4.11130209e-03\n -5.56710083e-03 1.11790729e+00 -1.21459611e-01 -9.75316912e-02\n 2.18506586e-02 1.38311490e-01 9.17155594e-02 -5.85136563e-02\n 1.03342809e-01 7.32071251e-02 -3.92427929e-02 1.13294438e-01\n -1.07247204e-01 5.58346435e-02 -9.28281173e-02 5.48683619e-03\n -1.84886660e-02 5.24056628e-02 4.05881368e-02 -8.35432187e-02\n 1.13391867e-02 2.78038122e-02 -5.44880610e-03 -1.02035753e-01\n -6.69988245e-02 7.79658780e-02 5.37769347e-02 -1.39616817e-01\n 2.96867881e-02 1.13102477e-02 -3.53476144e-02 -1.88835058e-02\n -4....,1,1,1,1,1,1,1,1,1
3,[-5.94305294e-03 1.57299116e-01 -1.01663664e-01 -4.74716797e-02\n 1.79840446e-01 2.63532978e-02 4.07044962e-02 -3.17418873e-02\n -1.32127828e-03 1.28309309e+00 -3.01563025e-01 4.19499092e-02\n 4.76229452e-02 -1.16947450e-01 -1.42535036e-02 2.37643998e-02\n -3.57760116e-02 8.38545859e-01 -5.43218441e-02 2.42432952e-03\n 7.67285563e-03 4.88467440e-02 4.74129207e-02 -2.67546187e-04\n 6.47759363e-02 7.66171236e-03 -7.71588413e-03 6.14660196e-02\n 9.25298501e-03 1.29891783e-01 6.76145032e-02 -7.35822739e-03\n 3.22291143e-02 1.50113806e-01 1.32441163e-01 -9.81159508e-03\n -1.39411157e-02 1.04931206e-03 -1.90248825e-02 -9.27351974e-03\n -2.62032263e-02 7.86117762e-02 8.33134279e-02 2.64521260e-02\n -1.58701912e-02 9.79095325e-03 3.53994928e-02 -1.72072705e-02\n 7....,0,0,0,0,1,0,0,0,0
4,[-9.75671411e-02 2.17742935e-01 -5.24893478e-02 2.29859371e-02\n 1.95262451e-02 -3.96593288e-02 -2.93270722e-02 1.45730842e-02\n 8.01267326e-02 2.14558053e+00 -3.02207738e-01 7.73812085e-02\n 9.75400433e-02 -5.86019419e-02 2.85570417e-02 -6.01695329e-02\n -6.48141513e-03 1.10976875e+00 -1.62209153e-01 -2.63800696e-02\n 6.90186918e-02 5.40496930e-02 -4.89046909e-02 -1.06065851e-02\n 3.81638743e-02 8.63624960e-02 -1.46540195e-01 -7.51399994e-02\n -5.42312972e-02 -2.43689902e-02 3.15490589e-02 -7.77387097e-02\n -1.04405805e-01 1.55526847e-01 2.55947262e-02 -2.01004483e-02\n -4.33546826e-02 2.11381875e-02 9.09157470e-02 -9.94266123e-02\n -5.63282613e-03 7.87854865e-02 1.45106107e-01 -1.49363369e-01\n 2.86051352e-02 -9.17335041e-03 -3.88870686e-02 -1.43906018e-02\n 2....,1,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...
4841,[-9.97306556e-02 1.64349496e-01 1.71351619e-02 7.13192746e-02\n 1.75899908e-01 -1.15603261e-01 -8.73757303e-02 -3.37601155e-02\n 5.58915287e-02 1.69525981e+00 -4.03638840e-01 3.41098830e-02\n 1.48271397e-01 -5.36716953e-02 4.27423716e-02 3.00230049e-02\n -4.06325832e-02 1.12422264e+00 -4.39298190e-02 1.07508982e-02\n -7.20263198e-02 5.96804582e-02 4.38548550e-02 -1.71869665e-01\n 5.18397167e-02 1.47482648e-01 -3.61646675e-02 8.63183811e-02\n -4.57509570e-02 6.86240196e-02 -7.81383812e-02 6.77803857e-03\n 1.96492635e-02 3.25613059e-02 8.09665844e-02 1.05558559e-01\n 1.15658459e-03 3.71128581e-02 -1.13167958e-02 -6.61973208e-02\n -1.17063336e-02 -1.49593409e-02 1.30228832e-01 1.75232589e-02\n 3.42527404e-02 4.42111705e-05 1.07453475e-02 -6.22191653e-02\n 2....,0,0,0,0,0,0,1,0,0
4842,[-1.98924989e-01 3.00148040e-01 1.01390548e-01 -1.25840604e-01\n 3.24619608e-03 -1.00019135e-01 -1.24527112e-01 -5.24022356e-02\n 1.37367668e-02 1.35610378e+00 -2.27968454e-01 1.58202261e-01\n -7.28038773e-02 -4.16742004e-02 1.74741030e-01 -2.46515095e-01\n 3.43543403e-02 9.48214471e-01 -9.90116820e-02 -1.46733001e-01\n -5.03083616e-02 7.97276795e-02 2.76607871e-02 2.14223936e-02\n 8.79974142e-02 -9.17081013e-02 -1.13138795e-01 5.91326691e-02\n 1.20140046e-01 -3.84076685e-02 -3.18211094e-02 -1.06555417e-01\n -4.91127931e-02 -3.66714634e-02 2.47359928e-03 -6.18500356e-03\n -1.42085582e-01 -3.00514344e-02 5.16138040e-02 3.66412327e-02\n -6.68754056e-02 -4.96820062e-02 1.96969017e-01 -2.14436855e-02\n 3.49904411e-02 8.42073932e-02 5.88495322e-02 2.23803204e-02\n -1....,0,0,0,0,1,0,0,0,0
4843,[-1.26625523e-01 2.81394184e-01 1.47076428e-01 -8.27063471e-02\n 1.89998314e-01 -1.95341870e-01 4.09874618e-02 4.50612567e-02\n 1.91018894e-01 1.17237604e+00 -3.50073159e-01 1.32276177e-01\n 1.80098731e-02 -3.21719684e-02 1.55063599e-01 -1.11439444e-01\n 5.50558940e-02 1.04285705e+00 -1.20266512e-01 4.59595509e-02\n 1.10065266e-01 5.54235131e-02 -1.12656087e-01 -1.29508138e-01\n 1.33550599e-01 9.51396152e-02 -5.79518043e-02 -1.48020387e-01\n -5.75628951e-02 1.92942038e-01 5.40777408e-02 -1.02687180e-01\n -9.71201211e-02 7.68551379e-02 1.51430340e-02 -7.59296939e-02\n -1.33880302e-01 -6.48121685e-02 8.27361941e-02 1.65923476e-01\n -6.65841550e-02 -5.17907441e-02 1.25316873e-01 -8.98319855e-02\n -1.09120391e-01 8.51464048e-02 9.52818319e-02 8.35352391e-02\n 2....,0,0,0,0,0,0,0,0,0
4844,[-1.32034168e-01 2.24063978e-01 3.11533064e-02 1.04350876e-02\n 1.56703591e-01 -1.01873629e-01 2.23107524e-02 5.80221787e-02\n 1.09591357e-01 1.37637448e+00 -3.08786511e-01 6.17817082e-02\n 9.21739489e-02 -4.09597717e-02 1.86670780e-01 -2.55621858e-02\n 5.35475016e-02 1.13686538e+00 -8.73383507e-02 -2.77639553e-02\n 4.91071157e-02 6.25430942e-02 -9.91906524e-02 -4.09849957e-02\n 1.23337105e-01 8.61576125e-02 -1.24529265e-01 -8.46296623e-02\n -1.07371166e-01 1.51070386e-01 1.05449930e-02 -4.81814779e-02\n -1.36766464e-01 9.01109204e-02 2.72464938e-02 1.43071718e-03\n -1.20931201e-01 2.54633697e-03 1.08788302e-02 3.64606492e-02\n 3.07067460e-03 8.49255845e-02 1.09374307e-01 -5.65562025e-02\n -2.14073937e-02 4.81035821e-02 1.16443343e-01 5.90736568e-02\n 1....,0,0,0,0,0,0,0,0,0
4845,[-2.11000890e-01 3.38408977e-01 2.79511586e-02 -6.04719371e-02\n 1.00033201e-01 -1.23005114e-01 -2.58821696e-02 -3.29742618e-02\n 2.08791532e-02 1.56804836e+00 -3.97868901e-01 1.73305854e-01\n -1.92171901e-01 3.62741612e-02 -4.00141208e-03 -1.44216970e-01\n 8.82210955e-02 1.20483148e+00 -1.19249322e-01 -2.27035824e-02\n -7.42047001e-03 2.96443445e-03 4.77242656e-02 -5.48094772e-02\n 4.66798693e-02 -3.94312143e-02 -1.53847948e-01 6.67186901e-02\n -3.74379009e-02 5.33582866e-02 -5.51761575e-02 -1.21744961e-01\n -1.30150259e-01 6.22810051e-02 4.27318439e-02 9.83037148e-03\n -2.44952291e-02 -3.26079540e-02 1.40232638e-01 -1.30875155e-01\n 1.03321888e-01 -7.45608285e-02 1.20164745e-01 1.58372801e-02\n 2.28052661e-02 8.12419355e-02 4.02745716e-02 -6.35905340e-02\n 1....,0,0,0,0,0,0,0,0,0

In [9]:
meta_data = compare_y_vs_yhats_df.iloc[:, 3:-1]
compare_y_vs_yhats_df['Meta Data'] = meta_data.to_dict(orient='records')
compare_y_vs_yhats_df
y_vs_yhats_df = DataProcessing.drop_df_columns(compare_y_vs_yhats_df, meta_data.columns.to_list())
y_vs_yhats_df

,Base Sentence,Sentence Label,Base Sentence Embedding,Majority Vote,Meta Data
0,With the new production plant the company would increase its capacity to meet the expected increase in demand and would improve the use of raw materials and therefore increase the production profitability .,1,[-1.22568220e-01 2.48624131e-01 -4.82655168e-02 -1.09789923e-01\n -8.58348906e-02 3.63291465e-02 -1.27964811e-02 7.17335939e-02\n -1.18364163e-01 2.27930522e+00 -3.32476139e-01 -1.46164745e-02\n 1.25499114e-01 7.25146085e-02 6.57393187e-02 -5.76901138e-02\n -2.05907249e-03 1.51917112e+00 -3.29480022e-01 -4.57408801e-02\n 2.22120117e-02 1.05339624e-01 -4.22692373e-02 -1.23566784e-01\n -5.79119613e-03 6.18153140e-02 -5.48806489e-02 2.96797305e-02\n -1.07008472e-01 -9.98812243e-02 -9.39770564e-02 3.87728140e-02\n -5.82127571e-02 7.14930072e-02 9.65250358e-02 -3.75642404e-02\n 7.18023349e-03 6.21852428e-02 7.68979266e-02 -1.69069305e-01\n 1.44475931e-03 7.71993026e-02 3.41709815e-02 -1.10992551e-01\n -1.81387588e-02 -8.61631632e-02 -2.34903637e-02 6.00658916e-02\n -3....,1,"{'perceptron': 1, 'sgd_classifier': 1, 'logistic_regression': 1, 'ridge_classifier': 1, 'decision_tree_classifier': 0, 'random_forest_classifier': 1, 'gradient_boosting_classifier': 1, 'support_vector_machine_classifier': 1, 'x_gradient_boosting_classifier': 1}"
1,"According to the company 's updated strategy for the years 2009-2012 , Basware targets a long-term net sales growth in the range of 20 % -40 % with an operating profit margin of 10 % -20 % of net sales .",1,[-2.63320029e-01 3.28540474e-01 4.48558182e-02 -1.09422831e-02\n 3.39385755e-02 -1.25387803e-01 2.09340192e-02 8.32975954e-02\n 1.10356383e-01 1.74510765e+00 -3.98153275e-01 1.41264707e-01\n -8.98099765e-02 -1.47727029e-02 5.77163734e-02 -5.09223454e-02\n -4.27257568e-02 1.41277170e+00 -2.09747717e-01 1.56779997e-02\n -3.64826852e-03 5.97854443e-02 -7.89400712e-02 -1.39893517e-02\n 1.13595366e-01 9.83026922e-02 -5.14178127e-02 7.06899390e-02\n 2.47105230e-02 1.06609218e-01 -4.19648038e-03 -1.85196903e-02\n -1.48957130e-02 9.90139246e-02 1.10973224e-01 -2.59710420e-02\n -6.08825274e-02 4.48305123e-02 4.36691009e-02 -9.27021950e-02\n 6.36729002e-02 1.98753644e-02 2.10891932e-01 -8.54000822e-02\n 4.67465706e-02 -2.04764325e-02 -3.69948000e-02 1.16207667e-01\n 1....,1,"{'perceptron': 1, 'sgd_classifier': 1, 'logistic_regression': 0, 'ridge_classifier': 0, 'decision_tree_classifier': 1, 'random_forest_classifier': 1, 'gradient_boosting_classifier': 1, 'support_vector_machine_classifier': 0, 'x_gradient_boosting_classifier': 1}"
2,TeliaSonera TLSN said the offer is in line with its strategy to increase its ownership in core business holdings and would strengthen Eesti Telekom 's offering to its customers .,1,[ 1.15080299e-02 1.98225155e-01 1.95062440e-02 -5.97744621e-02\n 1.75585955e-01 -1.25474662e-01 -3.72287892e-02 -2.83286646e-02\n -3.56662273e-02 1.96045303e+00 -2.79843062e-01 -1.04898110e-01\n 4.49508205e-02 1.31481076e-02 6.55795187e-02 -4.11130209e-03\n -5.56710083e-03 1.11790729e+00 -1.21459611e-01 -9.75316912e-02\n 2.18506586e-02 1.38311490e-01 9.17155594e-02 -5.85136563e-02\n 1.03342809e-01 7.32071251e-02 -3.92427929e-02 1.13294438e-01\n -1.07247204e-01 5.58346435e-02 -9.28281173e-02 5.48683619e-03\n -1.84886660e-02 5.24056628e-02 4.05881368e-02 -8.35432187e-02\n 1.13391867e-02 2.78038122e-02 -5.44880610e-03 -1.02035753e-01\n -6.69988245e-02 7.79658780e-02 5.37769347e-02 -1.39616817e-01\n 2.96867881e-02 1.13102477e-02 -3.53476144e-02 -1.88835058e-02\n -4....,1,"{'perceptron': 1, 'sgd_classifier': 1, 'logistic_regression': 1, 'ridge_classifier': 1, 'decision_tree_classifier': 1, 'random_forest_classifier': 1, 'gradient_boosting_classifier': 1, 'support_vector_machine_classifier': 1, 'x_gradient_boosting_classifier': 1}"
3,"STORA ENSO , NORSKE SKOG , M-REAL , UPM-KYMMENE Credit Suisse First Boston ( CFSB ) raised the fair value for shares in four of the largest Nordic forestry groups .",1,[-5.94305294e-03 1.57299116e-01 -1.01663664e-01 -4.74716797e-02\n 1.79840446e-01 2.63532978e-02 4.07044962e-02 -3.17418873e-02\n -1.32127828e-03 1.28309309e+00 -3.01563025e-01 4.19499092e-02\n 4.76229452e-02 -1.16947450e-01 -1.42535036e-02 2.37643998e-02\n -3.57760116e-02 8.38545859e-01 -5.43218441e-02 2.42432952e-03\n 7.67285563e-03 4.88467440e-02 4.74129207e-02 -2.67546187e-04\n 6.47759363e-02 7.66171236e-03 -7.71588413e-03 6.14660196e-02\n 9.25298501e-03 1.29891783e-01 6.76145032e-02 -7.35822739e-03\n 3.22291143e-02 1.50113806e-01 1.32441163e-01 -9.81159508e-03\n -1.39411157e-02 1.04931206e-03 -1.90248825e-02 -9.27351974e-03\n -2.62032263e-02 7.86117762e-02 8.33134279e-02 2.64521260e-02\n -1.58701912e-02 9.79095325e-03 3.53994928e-02 -1.72072705e-02\n 7....,0,"{'perceptron': 0, 'sgd_classifier': 0, 'logistic_regression': 0, 'ridge_classifier': 0, 'decision_tree_classifier': 1, 'random_forest_classifier': 0, 'gradient_boosting_classifier': 0, 'support_vector_machine_classifier': 0, 'x_gradient_boosting_classifier': 0}"
4,The company also estimates the already carried out investments to lead to an increase in its net sales for 2010 from 2009 when they reached EUR 141.7 million .,1,[-9.75671411e-02 2.17742935e-01 -5.24893478e-02 2.29859371e-02\n 1.95262451e-02 -3.96593288e-02 -2.93270722e-02 1.45730842e-02\n 8.01267326e-02 2.14558053e+00 -3.02207738e-01 7.73812085e-02\n 9.75400433e-02 -5.86019419e-02 2.85570417e-02 -6.01695329e-02\n -6.48141513e-03 1.10976875e+00 -1.62209153e-01 -2.63800696e-02\n 6.90186918e-02 5.40496930e-02 -4.89046909e-02 -1.06065851e-02\n 3.81638743e-02 8.63624960e-02 -1.46540195e-01 -7.51399994e-02\n -5.42312972e-02 -2.43689902e-02 3.15490589e-02 -7.77387097e-02\n -1.04405805e-01 1.55526847e-01 2.55947262e-02 -2.01004483e-02\n -4.33546826e-02 2.11381875e-02 9.09157470e-02 -9.94266123e-02\n -5.63282613e-03 7.87854865e-02 1.45106107e-01 -1.49363369e-01\n 2.86051352e-02 -9.17335041e-03 -3.88870686e-02 -1.43906018e-02\n 2....,0,"{'perceptron': 1, 'sgd_classifier': 0, 'logistic_regression': 0, 'ridge_classifier': 0, 'decision_tree_classifier': 1, 'random_forest_classifier': 0, 'gradient_boosting_classifier': 0, 'support_vector_machine_classifier': 0, 'x_gradient_boosting_classifier': 0}"
...,...,...,...,...,...
4841,LONDON MarketWatch -- Share prices ended lower in London Monday as a rebound in bank stocks failed to offset broader weakness for the FTSE 100 .,0,[-9.97306556e-02 1.64349496e-01 1.71351619e-02 7.13192746e-02\n 1.75899908e-01 -1.15603261e-01 -8.73757303e-02 -3.37601155e-02\n 5.58915287e-02 1.69525981e+00 -4.03638840e-01 3.41098830e-02\n 1.48271397e-01 -5.36716953e-02 4.27423716e-02 3.00230049e-02\n -4.06325832e-02 1.12422264e+00 -4.39298190e-02 1.07508982e-02\n -7.20263198e-02 5.96804582e-02 4.38548550e-02 -1.71869665e-01\n 5.18397167e-02 1.47482648e-01 -3.61646675e-02 8.63183811e-02\n -4.57509570e-02 6.86240196e-02 -7.81383812e-02 6.77803857e-03\n 1.96492635e-02 3.25613059e-02 8.09665844e-02 1.05558559e-01\n 1.15658459e-03 3.71128581e-02 -1.13167958e-02 -6.61973208e-02\n -1.17063336e-02 -1.49593409e-02 1.30228832e-01 1.75232589e-02\n 3.42527404e-02 4.42111705e-05 1.07453475e-02 -6.22191653e-02\n 2....,0,"{'perceptron': 0, 'sgd_classifier': 0, 'logistic_regression': 0, 'ridge_classifier': 0, 'decision_tree_classifier': 0, 'random_forest_classifier': 0, 'gradient_boosting_classifier': 1, 'support_vector_machine_classifier': 0, 'x_gradient_boosting_classifier': 0}"
4842,"Rinkuskiai 's beer sales fell by 6.5 per cent to 4.16 million litres , while Kauno Alus ' beer sales jumped by 6.9 per cent to 2.48 million litres .",0,[-1.98924989e-01 3.00148040e-01 1.01390548e-01 -1.25840604e-01\n 3.24619608e-03 -1.00019135e-01 -1.24527112e-01 -5.24022356e-02\n 1.37367668e-02 1.35610378e+00 -2.27968454e-01 1.58202261e-01\n -7.28038773e-02 -4.16742004e-02 1.74741030e-01 -2.46515095e-01\n 3.43543403e-02 9.48214471e-01 -9.90116820e-02 -1.46733001e-01\n -5.03083616e-02 7.97276795e-02 2.76607871e-02 2.14223936e-02\n 8.79974142e-02 -9.17081013e-02 -1.13138795e-01 5.91326691e-02\n 1.20140046e-01 -3.84076685e-02 -3.18211094e-02 -1.06555417e-01\n -4.91127931e-02 -3.66714634e-02 2.47359928e-03 -6.18500356e-03\n -1.42085582e-01 -3.00514344e-02 5.16138040e-02 3.66412327e-02\n -6.68754056e-02 -4.96820062e-02 1.96969017e-01 -2.14436855e-02\n 3.49904411e-02 8.42073932e-02 5.88495322e-02 2.23803204e-02\n -1....,0,"{'perceptron': 0, 'sgd_classifier': 0, 'logistic_regression': 0, 'ridge_classifier': 0, 'decision_tree_classifier': 1, 'random_forest_classifier': 0, 'gradient_boosting_classifier': 0, 'support_vector_machine_classifier': 0, 'x_gradient_boosting_classifier': 0}"
4843,"Operating profit fell to EUR 35.4 mn from EUR 68.8 mn in 2007 , including vessel sales gain of EUR 12.3 mn .",0,[-1.26625523e-01 2.81394184e-01 1.47076428e-01 -8.27063471e-02\n 1.89998314e-01 -1.95341870e-01 4.09874618e-02 4.50612567e-02\n 1.91018894e-01 1.17237604e+00 -3.50073159e-01 1.32276177e-01\n 1.80098731e-02 -3.21719684e-02 1.55063599e-01 -1.11439444e-01\n 5.50558940e-02 1.04285705e+00 -1.20266512e-01 4.59595509e-02\n 1.10065266e-01 5.54235131e-02 -1.12656087e-01 -1.29508138e-01\n 1.33550599e-01 9.51396152e-02 -5.79518043e-02 -1.48020387e-01\n -5.75628951e-02 1.92942038e-01 5.40777408e-02 -1.02687180e-01\n -9.71201211e-02 7.68551379e-02 1.51430340e-02 -7.59296939e-02\n -1.33880302e-01 -6.48121685e-02 8.27361941e-02 1.65923476e-01\n -6.65841550e-02 -5.17907441e-02 1.25316873e-01 -8.98319855e-02\n -1.09120391e-01 8.51464048e-02 9.52818319e-02 8.35352391e-02\n 2....,0,"{'perceptron': 0, 'sgd_classifier': 0, 'logistic_regression': 0, 'ridge_classifier': 0, 'decision_tree_classifier': 0, 'random_forest_classifier': 0, 'gradient_boosting_classifier': 0, 'support_vector_machine_classifier': 0, 'x_gradient_boosting_classifier': 0}"
4844,"Net sales of the Paper segment decreased to EUR 221.6 mn in the second quarter of 2009 from EUR 241.1 mn in the second quarter of 2008 , while operating profit excluding non-recurring items rose to EUR 8.0 mn from EUR 7.6 mn .",0,[-1.32034168e-01 2.24063978e-01 3.11533064e-02 1.04350876e-02\n 1.56703591e-01 -1.01873629e-01 2.23107524e-02 5.80221787e-02\n 1.09591357e-01 1.37637448e+00 -3.08786511e-01 6.17817082e-02\n 9.21739489e-02 -4.09597717e-02 1.86670780e-01 -2.55621858e-02\n 5.35475016e-02 1.13686538e+00 -8.73383507e-02 -2.77639553e-02\n 4.91071157e-02 6.25430942e-02 -9.91906524e-02 -4.09849957e-02\n 1.23337105e-01 8.61576125e-02 -1.24529265e-01 -8.46296623e-02\n -1.07371166e-01 1.51070386e-01 1.05449930e-02 -4.81814779e-02\n -1.36766464e-01 9.01109204e-02 2.72464938e-02 1.43071718e-03\n -1.20931201e-01 2.54633697e-03 1.08788302e-02 3.64606492e-02\n 3.07067460e-03 8.49255845e-02 1.09374307e-01 -5.65562025e-02\n -2.14073937e-02 4.81035821e-02 1.16443343e-01 5.90736568e-02\n 1....,0,"{'perceptron': 0, 'sgd_classifier': 0, 'logistic_regression': 0, 'ridge_classifier': 0, 'decision_tree_classifier': 0, 'random_forest_classifier': 0, 'gradient_boosting_classifier': 0, 'support_vector_machine_classifier': 0, 'x_gradient_boosting_classifier': 0}"
4845,"Sales in Finland decreased by 10.5 % in January , while sales outside Finland dropped by 17 % .",0,[-2.11000890e-01 3.38408977e-01 2.79511586e-02 -6.04719371e-02\n 1.00033201e-01 -1.23005114e-01 -2.58821696e-02 -3.29742618e-02\n 2.08791532e-02 1.56804836e+00 -3.97868901e-01 1.73305854e-01\n -1.92171901e-01 3.62741612e-02 -4.00141208e-03 -1.44216970e-01\n 8.82210955e-02 1.20483148e+00 -1.19249322e-01 -2.27035824e-02\n -7.42047001e-03 2.96443445e-03 4.77242656e-02 -5.48094772e-02\n 4.66798693e-02 -3.94312143e-02 -1.53847948e-01 6.67186901e-02\n -3.74379009e-02 5.33582866e-02 -5.51761575e-02 -1.21744961e-01\n -1.30150259e-01 6.22810051e-02 4.27318439e-02 9.83037148e-03\n -2.44952291e-02 -3.26079540e-02 1.40232638e-01 -1.30875155e-01\n 1.03321888e-01 -7.45608285e-02 1.20164745e-01 1.58372801e-02\n 2.28052661e-02 8.12419355e-02 4.02745716e-02 -6.35905340e-02\n 1....,0,"{'perceptron': 0, 'sgd_classifier': 0, 'logistic_regression': 0, 'ridge_classifier': 0, 'decision_tree_classifier': 0, 'random_forest_classifier': 0, 'gradient_boosting_classifier': 0, 'support_vector_machine_classifier': 0, 'x_gradient_boosting_classifier': 0}"

## Get class of each sentence

- [ ] True Label vs Majority Vote
- [ ] True Label vs Each Model

## True Label vs Majority Vote

In [10]:
def classification_of_mv_sentence(df):
    copy_df = df.copy()
    copy_df['Class'] = None

    for idx, row in copy_df.iterrows():
        y = row['Sentence Label']
        y_hat = row['Majority Vote']

        # y = 1 (positive class)
        if y == 1:
            if y_hat == 1:  # TP
                copy_df.loc[idx, 'Class'] = "TP"
            else:  # FN
                copy_df.loc[idx, 'Class'] = "FN"

        # y = 0 (negative class)
        elif y == 0:
            if y_hat == 0:  # TN
                copy_df.loc[idx, 'Class'] = "TN"
            else:  # FP
                copy_df.loc[idx, 'Class'] = "FP"

    return copy_df

In [11]:
mv_with_class_df = classification_of_mv_sentence(y_vs_yhats_df)
mv_with_class_df

,Base Sentence,Sentence Label,Base Sentence Embedding,Majority Vote,Meta Data,Class
0,With the new production plant the company would increase its capacity to meet the expected increase in demand and would improve the use of raw materials and therefore increase the production profitability .,1,[-1.22568220e-01 2.48624131e-01 -4.82655168e-02 -1.09789923e-01\n -8.58348906e-02 3.63291465e-02 -1.27964811e-02 7.17335939e-02\n -1.18364163e-01 2.27930522e+00 -3.32476139e-01 -1.46164745e-02\n 1.25499114e-01 7.25146085e-02 6.57393187e-02 -5.76901138e-02\n -2.05907249e-03 1.51917112e+00 -3.29480022e-01 -4.57408801e-02\n 2.22120117e-02 1.05339624e-01 -4.22692373e-02 -1.23566784e-01\n -5.79119613e-03 6.18153140e-02 -5.48806489e-02 2.96797305e-02\n -1.07008472e-01 -9.98812243e-02 -9.39770564e-02 3.87728140e-02\n -5.82127571e-02 7.14930072e-02 9.65250358e-02 -3.75642404e-02\n 7.18023349e-03 6.21852428e-02 7.68979266e-02 -1.69069305e-01\n 1.44475931e-03 7.71993026e-02 3.41709815e-02 -1.10992551e-01\n -1.81387588e-02 -8.61631632e-02 -2.34903637e-02 6.00658916e-02\n -3....,1,"{'perceptron': 1, 'sgd_classifier': 1, 'logistic_regression': 1, 'ridge_classifier': 1, 'decision_tree_classifier': 0, 'random_forest_classifier': 1, 'gradient_boosting_classifier': 1, 'support_vector_machine_classifier': 1, 'x_gradient_boosting_classifier': 1}",TP
1,"According to the company 's updated strategy for the years 2009-2012 , Basware targets a long-term net sales growth in the range of 20 % -40 % with an operating profit margin of 10 % -20 % of net sales .",1,[-2.63320029e-01 3.28540474e-01 4.48558182e-02 -1.09422831e-02\n 3.39385755e-02 -1.25387803e-01 2.09340192e-02 8.32975954e-02\n 1.10356383e-01 1.74510765e+00 -3.98153275e-01 1.41264707e-01\n -8.98099765e-02 -1.47727029e-02 5.77163734e-02 -5.09223454e-02\n -4.27257568e-02 1.41277170e+00 -2.09747717e-01 1.56779997e-02\n -3.64826852e-03 5.97854443e-02 -7.89400712e-02 -1.39893517e-02\n 1.13595366e-01 9.83026922e-02 -5.14178127e-02 7.06899390e-02\n 2.47105230e-02 1.06609218e-01 -4.19648038e-03 -1.85196903e-02\n -1.48957130e-02 9.90139246e-02 1.10973224e-01 -2.59710420e-02\n -6.08825274e-02 4.48305123e-02 4.36691009e-02 -9.27021950e-02\n 6.36729002e-02 1.98753644e-02 2.10891932e-01 -8.54000822e-02\n 4.67465706e-02 -2.04764325e-02 -3.69948000e-02 1.16207667e-01\n 1....,1,"{'perceptron': 1, 'sgd_classifier': 1, 'logistic_regression': 0, 'ridge_classifier': 0, 'decision_tree_classifier': 1, 'random_forest_classifier': 1, 'gradient_boosting_classifier': 1, 'support_vector_machine_classifier': 0, 'x_gradient_boosting_classifier': 1}",TP
2,TeliaSonera TLSN said the offer is in line with its strategy to increase its ownership in core business holdings and would strengthen Eesti Telekom 's offering to its customers .,1,[ 1.15080299e-02 1.98225155e-01 1.95062440e-02 -5.97744621e-02\n 1.75585955e-01 -1.25474662e-01 -3.72287892e-02 -2.83286646e-02\n -3.56662273e-02 1.96045303e+00 -2.79843062e-01 -1.04898110e-01\n 4.49508205e-02 1.31481076e-02 6.55795187e-02 -4.11130209e-03\n -5.56710083e-03 1.11790729e+00 -1.21459611e-01 -9.75316912e-02\n 2.18506586e-02 1.38311490e-01 9.17155594e-02 -5.85136563e-02\n 1.03342809e-01 7.32071251e-02 -3.92427929e-02 1.13294438e-01\n -1.07247204e-01 5.58346435e-02 -9.28281173e-02 5.48683619e-03\n -1.84886660e-02 5.24056628e-02 4.05881368e-02 -8.35432187e-02\n 1.13391867e-02 2.78038122e-02 -5.44880610e-03 -1.02035753e-01\n -6.69988245e-02 7.79658780e-02 5.37769347e-02 -1.39616817e-01\n 2.96867881e-02 1.13102477e-02 -3.53476144e-02 -1.88835058e-02\n -4....,1,"{'perceptron': 1, 'sgd_classifier': 1, 'logistic_regression': 1, 'ridge_classifier': 1, 'decision_tree_classifier': 1, 'random_forest_classifier': 1, 'gradient_boosting_classifier': 1, 'support_vector_machine_classifier': 1, 'x_gradient_boosting_classifier': 1}",TP
3,"STORA ENSO , NORSKE SKOG , M-REAL , UPM-KYMMENE Credit Suisse First Boston ( CFSB ) raised the fair value for shares in four of the largest Nordic forestry groups .",1,[-5.94305294e-03 1.57299116e-01 -1.01663664e-01 -4.74716797e-02\n 1.79840446e-01 2.63532978e-02 4.07044962e-02 -3.17418873e-02\n -1.32127828e-03 1.28309309e+00 -3.01563025e-01 4.19499092e-02\n 4.76229452e-02 -1.16947450e-01 -1.42535036e-02 2.37643998e-02\n -3.57760116e-02 8.38545859e-01 -5.43218441e-02 2.42432952e-03\n 7.67285563e-03 4.88467440e-02 4.74129207e-02 -2.67546187e-04\n 6.47759363e-02 7.66171236e-03 -7.71588413e-03 6.14660196e-02\n 9.25298501e-03 1.29891783e-01 6.76145032e-02 -7.35822739e-03\n 3.22291143e-02 1.50113806e-01 1.32441163e-01 -9.81159508e-03\n -1.39411157e-02 1.04931206e-03 -1.90248825e-02 -9.27351974e-03\n -2.62032263e-02 7.86117762e-02 8.33134279e-02 2.64521260e-02\n -1.58701912e-02 9.79095325e-03 3.53994928e-02 -1.72072705e-02\n 7....,0,"{'perceptron': 0, 'sgd_classifier': 0, 'logistic_regression': 0, 'ridge_classifier': 0, 'decision_tree_classifier': 1, 'random_forest_classifier': 0, 'gradient_boosting_classifier': 0, 'support_vector_machine_classifier': 0, 'x_gradient_boosting_classifier': 0}",FN
4,The company also estimates the already carried out investments to lead to an increase in its net sales for 2010 from 2009 when they reached EUR 141.7 million .,1,[-9.75671411e-02 2.17742935e-01 -5.24893478e-02 2.29859371e-02\n 1.95262451e-02 -3.96593288e-02 -2.93270722e-02 1.45730842e-02\n 8.01267326e-02 2.14558053e+00 -3.02207738e-01 7.73812085e-02\n 9.75400433e-02 -5.86019419e-02 2.85570417e-02 -6.01695329e-02\n -6.48141513e-03 1.10976875e+00 -1.62209153e-01 -2.63800696e-02\n 6.90186918e-02 5.40496930e-02 -4.89046909e-02 -1.06065851e-02\n 3.81638743e-02 8.63624960e-02 -1.46540195e-01 -7.51399994e-02\n -5.42312972e-02 -2.43689902e-02 3.15490589e-02 -7.77387097e-02\n -1.04405805e-01 1.55526847e-01 2.55947262e-02 -2.01004483e-02\n -4.33546826e-02 2.11381875e-02 9.09157470e-02 -9.94266123e-02\n -5.63282613e-03 7.87854865e-02 1.45106107e-01 -1.49363369e-01\n 2.86051352e-02 -9.17335041e-03 -3.88870686e-02 -1.43906018e-02\n 2....,0,"{'perceptron': 1, 'sgd_classifier': 0, 'logistic_regression': 0, 'ridge_classifier': 0, 'decision_tree_classifier': 1, 'random_forest_classifier': 0, 'gradient_boosting_classifier': 0, 'support_vector_machine_classifier': 0, 'x_gradient_boosting_classifier': 0}",FN
...,...,...,...,...,...,...
4841,LONDON MarketWatch -- Share prices ended lower in London Monday as a rebound in bank stocks failed to offset broader weakness for the FTSE 100 .,0,[-9.97306556e-02 1.64349496e-01 1.71351619e-02 7.13192746e-02\n 1.75899908e-01 -1.15603261e-01 -8.73757303e-02 -3.37601155e-02\n 5.58915287e-02 1.69525981e+00 -4.03638840e-01 3.41098830e-02\n 1.48271397e-01 -5.36716953e-02 4.27423716e-02 3.00230049e-02\n -4.06325832e-02 1.12422264e+00 -4.39298190e-02 1.07508982e-02\n -7.20263198e-02 5.96804582e-02 4.38548550e-02 -1.71869665e-01\n 5.18397167e-02 1.47482648e-01 -3.61646675e-02 8.63183811e-02\n -4.57509570e-02 6.86240196e-02 -7.81383812e-02 6.77803857e-03\n 1.96492635e-02 3.25613059e-02 8.09665844e-02 1.05558559e-01\n 1.15658459e-03 3.71128581e-02 -1.13167958e-02 -6.61973208e-02\n -1.17063336e-02 -1.49593409e-02 1.30228832e-01 1.75232589e-02\n 3.42527404e-02 4.42111705e-05 1.07453475e-02 -6.22191653e-02\n 2....,0,"{'perceptron': 0, 'sgd_classifier': 0, 'logistic_regression': 0, 'ridge_classifier': 0, 'decision_tree_classifier': 0, 'random_forest_classifier': 0, 'gradient_boosting_classifier': 1, 'support_vector_machine_classifier': 0, 'x_gradient_boosting_classifier': 0}",TN
4842,"Rinkuskiai 's beer sales fell by 6.5 per cent to 4.16 million litres , while Kauno Alus ' beer sales jumped by 6.9 per cent to 2.48 million litres .",0,[-1.98924989e-01 3.00148040e-01 1.01390548e-01 -1.25840604e-01\n 3.24619608e-03 -1.00019135e-01 -1.24527112e-01 -5.24022356e-02\n 1.37367668e-02 1.35610378e+00 -2.27968454e-01 1.58202261e-01\n -7.28038773e-02 -4.16742004e-02 1.74741030e-01 -2.46515095e-01\n 3.43543403e-02 9.48214471e-01 -9.90116820e-02 -1.46733001e-01\n -5.03083616e-02 7.97276795e-02 2.76607871e-02 2.14223936e-02\n 8.79974142e-02 -9.17081013e-02 -1.13138795e-01 5.91326691e-02\n 1.20140046e-01 -3.84076685e-02 -3.18211094e-02 -1.06555417e-01\n -4.91127931e-02 -3.66714634e-02 2.47359928e-03 -6.18500356e-03\n -1.42085582e-01 -3.00514344e-02 5.16138040e-02 3.66412327e-02\n -6.68754056e-02 -4.96820062e-02 1.96969017e-01 -2.14436855e-02\n 3.49904411e-02 8.42073932e-02 5.88495322e-02 2.23803204e-02\n -1....,0,"{'perceptron': 0, 'sgd_classifier': 0, 'logistic_regression': 0, 'ridge_classifier': 0, 'decision_tree_classifier': 1, 'random_forest_classifier': 0, 'gradient_boosting_classifier': 0, 'support_vector_machine_classifier': 0, 'x_gradient_boosting_classifier': 0}",TN
4843,"Operating profit fell to EUR 35.4 mn from EUR 68.8 mn in 2007 , including vessel sales gain of EUR 12.3 mn .",0,[-1.26625523e-01 2.81394184e-01 1.47076428e-01 -8.27063471e-02\n 1.89998314e-01 -1.95341870e-01 4.09874618e-02 4.50612567e-02\n 1.91018894e-01 1.17237604e+00 -3.50073159e-01 1.32276177e-01\n 1.80098731e-02 -3.21719684e-02 1.55063599e-01 -1.11439444e-01\n 5.50558940e-02 1.04285705e+00 -1.20266512e-01 4.59595509e-02\n 1.10065266e-01 5.54235131e-02 -1.12656087e-01 -1.29508138e-01\n 1.33550599e-01 9.51396152e-02 -5.79518043e-02 -1.48020387e-01\n -5.75628951e-02 1.92942038e-01 5.40777408e-02 -1.02687180e-01\n -9.71201211e-02 7.68551379e-02 1.51430340e-02 -7.59296939e-02\n -1.33880302e-01 -6.48121685e-02 8.27361941e-02 1.65923476e-01\n -6.65841550e-02 -5.17907441e-02 1.25316873e-01 -8.98319855e-02\n -1.09120391e-01 8.51464048e-02 9.52818319e-02 8.35352391e-02\n 2....,0,"{'perceptron': 0, 'sgd_classifier': 0, 'logistic_regression': 0, 'ridge_classifier': 0, 'decision_tree_classifier': 0, 'random_forest_classifier': 0, 'gradient_boosting_classifier': 0, 'support_vector_machine_classifier': 0, 'x_gradient_boosting_classifier': 0}",TN
4844,"Net sales of the Paper segment decreased to EUR 221.6 mn in the second quarter of 2009 from EUR 241.1 mn in the second quarter of 2008 , while operating profit excluding non-recurring items rose to EUR 8.0 mn from EUR 7.6 mn .",0,[-1.32034168e-01 2.24063978e-01 3.11533064e-02 1.04350876e-02\n 1.56703591e-01 -1.01873629e-01 2.23107524e-02 5.80221787e-02\n 1.09591357e-01 1.37637448e+00 -3.08786511e-01 6.17817082e-02\n 9.21739489e-02 -4.09597717e-02 1.86670780e-01 -2.55621858e-02\n 5.35475016e-02 1.13686538e+00 -8.73383507e-02 -2.77639553e-02\n 4.91071157e-02 6.25430942e-02 -9.91906524e-02 -4.09849957e-02\n 1.23337105e-01 8.61576125e-02 -1.24529265e-01 -8.46296623e-02\n -1.07371166e-01 1.51070386e-01 1.05449930e-02 -4.81814779e-02\n -1.36766464e-01 9.01109204e-02 2.72464938e-02 1.43071718e-03\n -1.20931201e-01 2.54633697e-03 1.08788302e-02 3.64606492e-02\n 3.07067460e-03 8.49255845e-02 1.09374307e-01 -5.65562025e-02\n -2.14073937e-02 4.81035821e-02 1.16443343e-01 5.90736568e-02\n 1....,0,"{'perceptron': 0, 'sgd_classifier': 0, 'logistic_regression': 0, 'ridge_classifier': 0, 'decision_tree_classifier': 0, 'random_forest_classifier': 0, 'gradient_boosting_classifier': 0, 'support_vector_machine_classifier': 0, 'x_gradient_boosting_classifier': 0}",TN
4845,"Sales in Finland decreased by 10.5 % in January , while sales outside Finland dropped by 17 % .",0,[-2.11000890e-01 3.38408977e-01 2.79511586e-02 -6.04719371e-02\n 1.00033201e-01 -1.23005114e-01 -2.58821696e-02 -3.29742618e-02\n 2.08791532e-02 1.56804836e+00 -3.97868901e-01 1.73305854e-01\n -1.92171901e-01 3.62741612e-02 -4.00141208e-03 -1.44216970e-01\n 8.82210955e-02 1.20483148e+00 -1.19249322e-01 -2.27035824e-02\n -7.42047001e-03 2.96443445e-03 4.77242656e-02 -5.48094772e-02\n 4.66798693e-02 -3.94312143e-02 -1.53847948e-01 6.67186901e-02\n -3.74379009e-02 5.33582866e-02 -5.51761575e-02 -1.21744961e-01\n -1.30150259e-01 6.22810051e-02 4.27318439e-02 9.83037148e-03\n -2.44952291e-02 -3.26079540e-02 1.40232638e-01 -1.30875155e-01\n 1.03321888e-01 -7.45608285e-02 1.20164745e-01 1.58372801e-02\n 2.28052661e-02 8.12419355e-02 4.02745716e-02 -6.35905340e-02\n 1....,0,"{'perceptron': 0, 'sgd_classifier': 0, 'logistic_regression': 0, 'ridge_classifier': 0, 'decision_tree_classifier': 0, 'random_forest_classifier': 0, 'gradient_boosting_classifier': 0, 'support_vector_machine_classifier': 0, 'x_gradient_boosting_classifier': 0}",TN

| $ y $ | $ y_{hat} $ | Outcome |
|----------------|----------------|----------|
| 1              | 1              | **TP**   |
| 1              | 0              | **FN**  (miss out) |
| 0              | 0              | **TN**   |
| 0              | 1              | **FP**  (inflate) |

**Confusion Matrix (sklearn-style layout)**

| y \ y_hat |   0   |   1   |
|-----------|-------|-------|
| **0**     |  TN   |  FP  (inflate) |
| **1**     |  FN  (miss out) |  TP   |

## Linguistic Features

In [12]:
pd.set_option('max_colwidth', 800)
# pd.set_option('display.max_columns', None)
# pd.set_option('display.max_columns', 40)
# pd.set_option('display.max_rows', None)

In [13]:
filt_tp = (mv_with_class_df['Class'] == 'TP')
tp_mv_df = mv_with_class_df[filt_tp]
tp_mv_df.head(3)

,Base Sentence,Sentence Label,Base Sentence Embedding,Majority Vote,Meta Data,Class
0,With the new production plant the company would increase its capacity to meet the expected increase in demand and would improve the use of raw materials and therefore increase the production profitability .,1,[-1.22568220e-01 2.48624131e-01 -4.82655168e-02 -1.09789923e-01\n -8.58348906e-02 3.63291465e-02 -1.27964811e-02 7.17335939e-02\n -1.18364163e-01 2.27930522e+00 -3.32476139e-01 -1.46164745e-02\n 1.25499114e-01 7.25146085e-02 6.57393187e-02 -5.76901138e-02\n -2.05907249e-03 1.51917112e+00 -3.29480022e-01 -4.57408801e-02\n 2.22120117e-02 1.05339624e-01 -4.22692373e-02 -1.23566784e-01\n -5.79119613e-03 6.18153140e-02 -5.48806489e-02 2.96797305e-02\n -1.07008472e-01 -9.98812243e-02 -9.39770564e-02 3.87728140e-02\n -5.82127571e-02 7.14930072e-02 9.65250358e-02 -3.75642404e-02\n 7.18023349e-03 6.21852428e-02 7.68979266e-02 -1.69069305e-01\n 1.44475931e-03 7.71993026e-02 3.41709815e-02 -1.10992551e-01\n -1.81387588e-02 -8.61631632e-02 -2.34903637e-02 6.00658916e-02\n -3....,1,"{'perceptron': 1, 'sgd_classifier': 1, 'logistic_regression': 1, 'ridge_classifier': 1, 'decision_tree_classifier': 0, 'random_forest_classifier': 1, 'gradient_boosting_classifier': 1, 'support_vector_machine_classifier': 1, 'x_gradient_boosting_classifier': 1}",TP
1,"According to the company 's updated strategy for the years 2009-2012 , Basware targets a long-term net sales growth in the range of 20 % -40 % with an operating profit margin of 10 % -20 % of net sales .",1,[-2.63320029e-01 3.28540474e-01 4.48558182e-02 -1.09422831e-02\n 3.39385755e-02 -1.25387803e-01 2.09340192e-02 8.32975954e-02\n 1.10356383e-01 1.74510765e+00 -3.98153275e-01 1.41264707e-01\n -8.98099765e-02 -1.47727029e-02 5.77163734e-02 -5.09223454e-02\n -4.27257568e-02 1.41277170e+00 -2.09747717e-01 1.56779997e-02\n -3.64826852e-03 5.97854443e-02 -7.89400712e-02 -1.39893517e-02\n 1.13595366e-01 9.83026922e-02 -5.14178127e-02 7.06899390e-02\n 2.47105230e-02 1.06609218e-01 -4.19648038e-03 -1.85196903e-02\n -1.48957130e-02 9.90139246e-02 1.10973224e-01 -2.59710420e-02\n -6.08825274e-02 4.48305123e-02 4.36691009e-02 -9.27021950e-02\n 6.36729002e-02 1.98753644e-02 2.10891932e-01 -8.54000822e-02\n 4.67465706e-02 -2.04764325e-02 -3.69948000e-02 1.16207667e-01\n 1....,1,"{'perceptron': 1, 'sgd_classifier': 1, 'logistic_regression': 0, 'ridge_classifier': 0, 'decision_tree_classifier': 1, 'random_forest_classifier': 1, 'gradient_boosting_classifier': 1, 'support_vector_machine_classifier': 0, 'x_gradient_boosting_classifier': 1}",TP
2,TeliaSonera TLSN said the offer is in line with its strategy to increase its ownership in core business holdings and would strengthen Eesti Telekom 's offering to its customers .,1,[ 1.15080299e-02 1.98225155e-01 1.95062440e-02 -5.97744621e-02\n 1.75585955e-01 -1.25474662e-01 -3.72287892e-02 -2.83286646e-02\n -3.56662273e-02 1.96045303e+00 -2.79843062e-01 -1.04898110e-01\n 4.49508205e-02 1.31481076e-02 6.55795187e-02 -4.11130209e-03\n -5.56710083e-03 1.11790729e+00 -1.21459611e-01 -9.75316912e-02\n 2.18506586e-02 1.38311490e-01 9.17155594e-02 -5.85136563e-02\n 1.03342809e-01 7.32071251e-02 -3.92427929e-02 1.13294438e-01\n -1.07247204e-01 5.58346435e-02 -9.28281173e-02 5.48683619e-03\n -1.84886660e-02 5.24056628e-02 4.05881368e-02 -8.35432187e-02\n 1.13391867e-02 2.78038122e-02 -5.44880610e-03 -1.02035753e-01\n -6.69988245e-02 7.79658780e-02 5.37769347e-02 -1.39616817e-01\n 2.96867881e-02 1.13102477e-02 -3.53476144e-02 -1.88835058e-02\n -4....,1,"{'perceptron': 1, 'sgd_classifier': 1, 'logistic_regression': 1, 'ridge_classifier': 1, 'decision_tree_classifier': 1, 'random_forest_classifier': 1, 'gradient_boosting_classifier': 1, 'support_vector_machine_classifier': 1, 'x_gradient_boosting_classifier': 1}",TP

Prediction words and synonyms

| **Class** | **High Prediction Words** | **Low Prediction Words** |
|---|---|---|
| **TP** | Model learned lexical markers ✅ | Model learned structural/contextual cues ✅ |
| **FP** | Possible annotation error ⚠️ or future-related but not predictive | Annotations good, model falsely triggered by non-lexical features |
| **TN** | Possible annotation error ⚠️ | Annotations good ✅ |
| **FN** | Annotation good, **model doesn't learn** ❗ | Annotations possibly bad ⚠️ |

In [14]:
class_for_strucuture = []
noun_aux_verb_sentences = []
disable_components = []
class_names = mv_with_class_df['Class'].unique()
for class_name in class_names:
    print(f"CLASS: {class_name}")
    filt_class_name = (mv_with_class_df['Class'] == class_name)
    class_df = mv_with_class_df[filt_class_name]
    # print(class_df)
    spacy_fe = SpacyFeatureExtraction(class_df, 'Base Sentence')
    # ner_df = spacy_fe.extract_ner_features(disable_components, visualize=False)
    pos_df = spacy_fe.extract_pos_features(disable_components, visualize=False)
    print(pos_df['Term'].value_counts())
    print(pos_df['Dependency'].value_counts())
    print(pos_df['POS Label'].value_counts())

    # Get sentences that contain NOUN + AUX + VERB
    # noun_sentences = set(pos_df[pos_df['POS Label'] == 'NOUN']['Sentence'].tolist())
    aux_sentences = set(pos_df[pos_df['POS Label'] == 'AUX']['Sentence'].tolist())
    verb_sentences = set(pos_df[pos_df['POS Label'] == 'VERB']['Sentence'].tolist())

    # Sentences that contain all three POS tags
    # class_noun_aux_verb_sentences = noun_sentences & aux_sentences & verb_sentences
    class_noun_aux_verb_sentences = aux_sentences & verb_sentences

    # Track class name and sentences
    for sentence in class_noun_aux_verb_sentences:
        noun_aux_verb_sentences.append({
            'Class': class_name,
            'Sentence': sentence
        })

    print(f"\nCLASS: {class_name}")
    print(f"Number of sentences with NOUN + AUX + VERB: {len(class_noun_aux_verb_sentences)}")
    for sentence in list(class_noun_aux_verb_sentences)[:3]:
        print(f"  - {sentence}")
    print()

CLASS: TP

==================================================
EXTRACTING POS FEATURES
==================================================

Extracting POS Features: 100%|██████████| 388/388 [00:01<00:00, 323.27doc/s]

==================================================
DONE EXTRACTING POS FEATURES
==================================================
Term
the           399
              388
.             385
to            280
,             251
             ...
Kalmar          1
Capitex         1
newspapers      1
Ignatius        1
RESULTS         1
Name: count, Length: 2099, dtype: int64
Dependency
prep         905
pobj         879
punct        823
det          692
compound     610
amod         547
nsubj        481
aux          473
ROOT         396
             388
dobj         305
nummod       222
advmod       206
conj         185
poss         165
cc           163
auxpass      151
xcomp        129
ccomp        127
nsubjpass    122
case          84
npadvmod      72
acomp         69
mark          62
advcl         57
nmod          55
quantmod      55
appos         52
relcl         47
attr          38
acl           31
pcomp         27
prt           17
agent         15
neg            9
dep            7
dative         4
csubj          3
expl           3
preconj        3
oprd           3
parataxis      2
predet         1
Name: count, dtype: int64
POS Label
NOUN     1725
ADP       945
VERB      839
PUNCT     806
PROPN     749
DET       702
ADJ       594
AUX       539
NUM       448
          388
PART      294
PRON      201
ADV       192
CCONJ     164
SCONJ      73
SYM        23
X           2
SPACE       1
Name: count, dtype: int64

CLASS: TP
Number of sentences with NOUN + AUX + VERB: 319
  - Net sales in 2007 are expected to be 10 % up on 2006 .
  - The actions are expected to deliver annual cost savings of some EUR15-20m .
  - Elisa will expand the use of this technology provided the pilot proves successful .

CLASS: FN

==================================================
EXTRACTING POS FEATURES
==================================================

Extracting POS Features: 100%|██████████| 70/70 [00:00<00:00, 280.53doc/s]

==================================================
DONE EXTRACTING POS FEATURES
==================================================
Term
the             95
,               71
                70
.               70
of              61
                ..
Innova           1
hotel            1
luxury           1
star             1
representing     1
Name: count, Length: 709, dtype: int64
Dependency
prep         224
pobj         219
punct        174
compound     167
det          142
amod         119
nsubj         78
ROOT          71
              70
nummod        64
dobj          57
aux           55
conj          44
cc            38
advmod        23
appos         23
poss          22
nmod          21
auxpass       21
nsubjpass     18
ccomp         17
quantmod      16
xcomp         14
npadvmod      11
advcl          8
acl            8
case           7
relcl          6
mark           4
acomp          4
attr           3
pcomp          3
agent          2
dep            2
prt            2
neg            1
oprd           1
parataxis      1
csubj          1
dative         1
Name: count, dtype: int64
POS Label
NOUN     333
ADP      224
PROPN    213
PUNCT    171
VERB     150
DET      142
NUM      142
ADJ      114
          70
AUX       67
CCONJ     38
PART      27
PRON      27
ADV       23
SYM       12
SCONJ      8
SPACE      1
Name: count, dtype: int64

CLASS: FN
Number of sentences with NOUN + AUX + VERB: 50
  - The Innova 2 building will be located close to downtown , in the immediate vicinity of Paviljonki and the travel center , and within walking distance from the heart of the city thanks to the trade fair bridge .
  - Both sources said Nokia would unveil its new phone code-named `` Tube '' on Oct. 2 at an analyst and media event in London .
  - The transactions would increase earnings per share in the first quarter by some EUR0 .28 .

CLASS: FP

==================================================
EXTRACTING POS FEATURES
==================================================

Extracting POS Features: 100%|██████████| 1852/1852 [00:05<00:00, 316.45doc/s]

==================================================
DONE EXTRACTING POS FEATURES
==================================================
Term
            1852
.           1831
the         1760
,           1351
to          1200
            ...
Backup         1
protects       1
stored         1
Higher         1
posting        1
Name: count, Length: 6821, dtype: int64
Dependency
punct        4870
compound     4362
prep         4263
pobj         4161
det          3405
amod         2570
nsubj        2401
ROOT         1921
             1852
dobj         1754
aux          1750
conj         1249
cc           1069
advmod       1003
nummod        931
poss          841
ccomp         520
appos         519
auxpass       462
xcomp         449
case          429
nsubjpass     400
nmod          368
npadvmod      358
acl           287
attr          279
relcl         277
advcl         262
mark          251
acomp         223
pcomp         155
quantmod      147
prt            88
neg            86
agent          80
dep            40
dative         37
predet         18
csubj          16
expl           15
oprd           15
preconj        13
parataxis      12
intj            8
meta            2
csubjpass       1
Name: count, dtype: int64
POS Label
NOUN     9655
PROPN    5203
PUNCT    4836
ADP      4469
VERB     3921
DET      3437
ADJ      2621
AUX      2087
         1852
NUM      1278
PRON     1232
PART     1221
CCONJ    1044
ADV       953
SCONJ     322
SYM        52
X          19
INTJ       12
SPACE       5
Name: count, dtype: int64

CLASS: FP
Number of sentences with NOUN + AUX + VERB: 1311
  - For the new shares subscribed with stock options all shareholder rights commence from the date on which they are entered into the Trade Register .
  - According to Sepp+ï¿½nen , the new technology UMTS900 solution network building costs are by one-third lower than that of the building of 3.5 G networks , operating at 2,100 MHz frequency .
  - According to Seikku , the retail sector in Finland is controlled by 3-4 large actors , while food manufacturers are still relatively small .

CLASS: TN

==================================================
EXTRACTING POS FEATURES
==================================================

Extracting POS Features: 100%|██████████| 2536/2536 [00:08<00:00, 296.74doc/s]

==================================================
DONE EXTRACTING POS FEATURES
==================================================
Term
,                      3011
                       2536
.                      2533
the                    2461
of                     1853
                       ...
www.upm-kymmene.com       1
thirty                    1
seventeen                 1
Free                      1
241.1                     1
Name: count, Length: 8761, dtype: int64
Dependency
pobj         7801
prep         7778
punct        7591
compound     7136
det          4300
amod         3843
nummod       3033
nsubj        2998
ROOT         2684
             2536
conj         2298
dobj         1724
cc           1620
nmod         1168
appos        1086
advmod       1066
poss          970
npadvmod      810
aux           759
case          562
auxpass       418
ccomp         393
nsubjpass     386
attr          371
advcl         352
acl           289
mark          242
quantmod      231
relcl         184
pcomp         136
agent         124
prt           107
acomp         105
dep            98
xcomp          95
dative         22
oprd           20
neg            17
parataxis      11
csubj           6
predet          5
intj            5
preconj         5
meta            4
expl            4
Name: count, dtype: int64
POS Label
NOUN     13446
PROPN    10353
ADP       7881
PUNCT     7501
NUM       4800
VERB      4589
DET       4327
ADJ       3566
          2536
CCONJ     1583
AUX       1563
ADV       1054
PRON       850
PART       748
SCONJ      307
SYM        223
SPACE       33
X           18
INTJ        15
Name: count, dtype: int64

CLASS: TN
Number of sentences with NOUN + AUX + VERB: 1054
  - TeliaSonera is the leading telecommunications company in the Nordic and Baltic regions .
  - W+ï¿½rtsil+ï¿½ 's aim is to serve the rapidly growing number of vessels and increasing marine activity in the Barents Sea region .
  - Operating loss before non-recurring items was EUR 0.9 mn , compared to a profit of EUR 11.5 mn in 2008 .

In [15]:
pos_df

,Sentence,Term,Lemma,POS Label,Detailed POS Label,Dependency,Shape,Is Alpha,Stop Word,Unique POS Label,...,Definite,Degree,SubCat,Animacy,Acc,Gen,Loc,Ins,Parat,Prep
0,"The international electronic industry company Elcoteq has laid off tens of employees from its Tallinn facility ; contrary to earlier layoffs the company contracted the ranks of its office workers , the daily Postimees reported .",The,the,DET,DT,det,Xxx,True,True,DET_1,...,[Def],,,,,,,,,
1,"The international electronic industry company Elcoteq has laid off tens of employees from its Tallinn facility ; contrary to earlier layoffs the company contracted the ranks of its office workers , the daily Postimees reported .",international,international,ADJ,JJ,amod,xxxx,True,False,ADJ_1,...,,[Pos],,,,,,,,
2,"The international electronic industry company Elcoteq has laid off tens of employees from its Tallinn facility ; contrary to earlier layoffs the company contracted the ranks of its office workers , the daily Postimees reported .",electronic,electronic,ADJ,JJ,amod,xxxx,True,False,ADJ_2,...,,[Pos],,,,,,,,
3,"The international electronic industry company Elcoteq has laid off tens of employees from its Tallinn facility ; contrary to earlier layoffs the company contracted the ranks of its office workers , the daily Postimees reported .",industry,industry,NOUN,NN,compound,xxxx,True,False,NOUN_1,...,,,,,,,,,,
4,"The international electronic industry company Elcoteq has laid off tens of employees from its Tallinn facility ; contrary to earlier layoffs the company contracted the ranks of its office workers , the daily Postimees reported .",company,company,NOUN,NN,nsubj,xxxx,True,False,NOUN_2,...,,,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65388,"Sales in Finland decreased by 10.5 % in January , while sales outside Finland dropped by 17 % .",by,by,ADP,IN,prep,xx,True,True,ADP_7881,...,,,,,,,,,,
65389,"Sales in Finland decreased by 10.5 % in January , while sales outside Finland dropped by 17 % .",17,17,NUM,CD,nummod,dd,False,False,NUM_4800,...,,,,,,,,,,
65390,"Sales in Finland decreased by 10.5 % in January , while sales outside Finland dropped by 17 % .",%,%,NOUN,NN,pobj,%,False,False,NOUN_13446,...,,,,,,,,,,
65391,"Sales in Finland decreased by 10.5 % in January , while sales outside Finland dropped by 17 % .",.,.,PUNCT,.,punct,.,False,False,PUNCT_7501,...,,,,,,,,,,
65392,,,,,,,,False,,,...,,,,,,,,,,

| **Lemma** | **Dependency** | **Context** | **Predictive?** |
|---|---|---|---|
| `expect` | `ROOT` or `ccomp` | "company **expects** net sales to increase" | ✅ Yes |
| `expect` | `advcl` | "better than **expected**" | ❌ No |
| `forecast` | `ROOT` | "Nokia **forecasts** revenue growth" | ✅ Yes |
| `forecast` | `pobj` | "ahead of **forecast** of 0.33 eur" | ❌ No |
| `project` | `ROOT` | "company **projects** growth" | ✅ Yes |
| `project` | `pobj` | "university **project** in Abu Dhabi" | ❌ No |

In [ ]:
# filt_p_w = (class_pos_df['Lemma'].str.lower().isin(p_w)) & (class_pos_df['Dependency'] == 'ROOT') COSIDER bc 

p_w = ["project", "expect", "forecast", "predict", "projection", "expectation", "forecasting", "prediction"]

# Check if any term in pos_df matches prediction words (case-insensitive)
filt_p_w = pos_df['Lemma'].str.lower().isin(p_w)
matched_p_w = pos_df[filt_p_w]
matched_p_w

,Sentence,Term,Lemma,POS Label,Detailed POS Label,Dependency,Shape,Is Alpha,Stop Word,Unique POS Label,...,Definite,Degree,SubCat,Animacy,Acc,Gen,Loc,Ins,Parat,Prep
420,"HELSINKI ( AFX ) - Shares closed higher , led by Nokia after it announced plans to team up with Sanyo to manufacture 3G handsets , and by Nokian Tyres after its fourth-quarter earnings report beat analysts ' expectations , dealers said .",expectations,expectation,NOUN,NNS,dobj,xxxx,True,False,NOUN_80,...,,,,,,,,,,
3326,"A structures BIM ( building information modeling ) software from Tekla , a model-based software provider , has been adopted for the construction management and delivery of a university project in Abu Dhabi .",project,project,NOUN,NN,pobj,xxxx,True,False,NOUN_672,...,,,,,,,,,,
7316,"Finnish Larox has signed a contract with the Talvivaara Project for the delivery of filters to the Talvivaara nickel mine in Sotkamo , in Finland .",Project,Project,PROPN,NNP,pobj,Xxxxx,True,False,PROPN_1130,...,,,,,,,,,,
7452,"EPS for the quarter came in at 0.36 eur , up from 0.33 eur a year ago and ahead of forecast of 0.33 eur .",forecast,forecast,NOUN,NN,pobj,xxxx,True,False,NOUN_1445,...,,,,,,,,,,
8862,"The mall is part of the Baltic Pearl development project in the city of St Petersburg , where Baltic Pearl CJSC , a subsidiary of Shanghai Foreign Joint Investment Company , is developing homes for 35,000 people .",project,project,NOUN,NN,pobj,xxxx,True,False,NOUN_1744,...,,,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64144,"According to the company , its operating profit , excluding non-recurring items , in the fourth quarter of 2009 was significantly better than expected , and also better than the figures for the fourth quarter of 2008 .",expected,expect,VERB,VBN,advcl,xxxx,True,False,VERB_4496,...,,,,,,,,,,
64168,`` I am extremely delighted with this project and the continuation of cooperation with Viking Line .,project,project,NOUN,NN,pobj,xxxx,True,False,NOUN_13168,...,,,,,,,,,,
64279,"- Demand for fireplace products was lower than expected , especially in Germany .",expected,expect,VERB,VBN,advcl,xxxx,True,False,VERB_4507,...,,,,,,,,,,
64584,Operating profit in the fourth quarter went down to EUR3m from EUR4 .2 m for the corresponding period of 2009 as it included costs of growth projects .,projects,project,NOUN,NNS,pobj,xxxx,True,False,NOUN_13263,...,,,,,,,,,,
64848,Mobile communication and wireless broadband provider Nokia Inc NYSE : NOK today set new financial targets and forecasts for Nokia and the mobile device industry and also for Nokia Siemens Networks and the mobile and fixed infrastructure and related services market .,forecasts,forecast,NOUN,NNS,conj,xxxx,True,False,NOUN_13329,...,,,,,,,,,,

In [46]:
filt_tp = (mv_with_class_df['Class'] == "TP")
tp_df = mv_with_class_df[filt_tp]
tp_df

,Base Sentence,Sentence Label,Base Sentence Embedding,Majority Vote,Meta Data,Class
0,With the new production plant the company would increase its capacity to meet the expected increase in demand and would improve the use of raw materials and therefore increase the production profitability .,1,[-1.22568220e-01 2.48624131e-01 -4.82655168e-02 -1.09789923e-01\n -8.58348906e-02 3.63291465e-02 -1.27964811e-02 7.17335939e-02\n -1.18364163e-01 2.27930522e+00 -3.32476139e-01 -1.46164745e-02\n 1.25499114e-01 7.25146085e-02 6.57393187e-02 -5.76901138e-02\n -2.05907249e-03 1.51917112e+00 -3.29480022e-01 -4.57408801e-02\n 2.22120117e-02 1.05339624e-01 -4.22692373e-02 -1.23566784e-01\n -5.79119613e-03 6.18153140e-02 -5.48806489e-02 2.96797305e-02\n -1.07008472e-01 -9.98812243e-02 -9.39770564e-02 3.87728140e-02\n -5.82127571e-02 7.14930072e-02 9.65250358e-02 -3.75642404e-02\n 7.18023349e-03 6.21852428e-02 7.68979266e-02 -1.69069305e-01\n 1.44475931e-03 7.71993026e-02 3.41709815e-02 -1.10992551e-01\n -1.81387588e-02 -8.61631632e-02 -2.34903637e-02 6.00658916e-02\n -3....,1,"{'perceptron': 1, 'sgd_classifier': 1, 'logistic_regression': 1, 'ridge_classifier': 1, 'decision_tree_classifier': 0, 'random_forest_classifier': 1, 'gradient_boosting_classifier': 1, 'support_vector_machine_classifier': 1, 'x_gradient_boosting_classifier': 1}",TP
1,"According to the company 's updated strategy for the years 2009-2012 , Basware targets a long-term net sales growth in the range of 20 % -40 % with an operating profit margin of 10 % -20 % of net sales .",1,[-2.63320029e-01 3.28540474e-01 4.48558182e-02 -1.09422831e-02\n 3.39385755e-02 -1.25387803e-01 2.09340192e-02 8.32975954e-02\n 1.10356383e-01 1.74510765e+00 -3.98153275e-01 1.41264707e-01\n -8.98099765e-02 -1.47727029e-02 5.77163734e-02 -5.09223454e-02\n -4.27257568e-02 1.41277170e+00 -2.09747717e-01 1.56779997e-02\n -3.64826852e-03 5.97854443e-02 -7.89400712e-02 -1.39893517e-02\n 1.13595366e-01 9.83026922e-02 -5.14178127e-02 7.06899390e-02\n 2.47105230e-02 1.06609218e-01 -4.19648038e-03 -1.85196903e-02\n -1.48957130e-02 9.90139246e-02 1.10973224e-01 -2.59710420e-02\n -6.08825274e-02 4.48305123e-02 4.36691009e-02 -9.27021950e-02\n 6.36729002e-02 1.98753644e-02 2.10891932e-01 -8.54000822e-02\n 4.67465706e-02 -2.04764325e-02 -3.69948000e-02 1.16207667e-01\n 1....,1,"{'perceptron': 1, 'sgd_classifier': 1, 'logistic_regression': 0, 'ridge_classifier': 0, 'decision_tree_classifier': 1, 'random_forest_classifier': 1, 'gradient_boosting_classifier': 1, 'support_vector_machine_classifier': 0, 'x_gradient_boosting_classifier': 1}",TP
2,TeliaSonera TLSN said the offer is in line with its strategy to increase its ownership in core business holdings and would strengthen Eesti Telekom 's offering to its customers .,1,[ 1.15080299e-02 1.98225155e-01 1.95062440e-02 -5.97744621e-02\n 1.75585955e-01 -1.25474662e-01 -3.72287892e-02 -2.83286646e-02\n -3.56662273e-02 1.96045303e+00 -2.79843062e-01 -1.04898110e-01\n 4.49508205e-02 1.31481076e-02 6.55795187e-02 -4.11130209e-03\n -5.56710083e-03 1.11790729e+00 -1.21459611e-01 -9.75316912e-02\n 2.18506586e-02 1.38311490e-01 9.17155594e-02 -5.85136563e-02\n 1.03342809e-01 7.32071251e-02 -3.92427929e-02 1.13294438e-01\n -1.07247204e-01 5.58346435e-02 -9.28281173e-02 5.48683619e-03\n -1.84886660e-02 5.24056628e-02 4.05881368e-02 -8.35432187e-02\n 1.13391867e-02 2.78038122e-02 -5.44880610e-03 -1.02035753e-01\n -6.69988245e-02 7.79658780e-02 5.37769347e-02 -1.39616817e-01\n 2.96867881e-02 1.13102477e-02 -3.53476144e-02 -1.88835058e-02\n -4....,1,"{'perceptron': 1, 'sgd_classifier': 1, 'logistic_regression': 1, 'ridge_classifier': 1, 'decision_tree_classifier': 1, 'random_forest_classifier': 1, 'gradient_boosting_classifier': 1, 'support_vector_machine_classifier': 1, 'x_gradient_boosting_classifier': 1}",TP
5,"The company still expects its turnover in 2010 to slightly increase from the level of 2009 , adding that `` market predictability is still too poor for trustworthy forecasts on the market development of the contract manufacturing business during the current year '' .",1,[-8.01109150e-02 2.36596152e-01 -5.08406200e-02 -5.91967329e-02\n 1.04830541e-01 -5.57341538e-02 4.63002734e-02 -7.99793098e-03\n 5.00161909e-02 2.16003442e+00 -3.25830907e-01 2.72772126e-02\n 5.99916726e-02 1.59362443e-02 1.50682740e-02 -5.99768125e-02\n -1.86955407e-02 1.20505536e+00 -1.61679640e-01 1.29278451e-02\n -3.52653414e-02 5.66716231e-02 -3.63632105e-02 -4.16581444e-02\n 5.95455319e-02 3.71346623e-02 -6.23186417e-02 1.79463835e-03\n -2.88256933e-03 -1.53720388e-02 -5.81578352e-02 -7.17658624e-02\n -3.74988429e-02 2.30221506e-02 6.13667704e-02 3.28951925e-02\n -1.52889658e-02 6.45012781e-02 3.34747620e-02 -5.69144934e-02\n 4.21757735e-02 3.62184793e-02 7.59416893e-02 -5.81586622e-02\n 2.79461760e-02 -6.79485649e-02 -5.53069077e-02 -4.56502773e-02\n -6....,1,"{'perceptron': 1, 'sgd_classifier': 1, 'logistic_regression': 1, 'ridge_classifier': 1, 'decision_tree_classifier': 0, 'random_forest_classifier': 1, 'gradient_boosting_classifier': 1, 'support_vector_machine_classifier': 1, 'x_gradient_boosting_classifier': 1}",TP
6,The acquisition will considerably increase Kemira 's sales and market position in the Russian metal industry coatings market .,1,[-1.40268207e-01 2.62877226e-01 7.93231372e-03 8.86395387e-03\n 1.33090064e-01 -1.39466971e-01 -3.46719511e-02 3.12540419e-02\n -1.35381594e-02 1.94855237e+00 -3.55075836e-01 -5.88611923e-02\n 1.07916631e-01 -1.01686619e-01 7.30645880e-02 -2.87176911e-02\n 7.84564763e-02 1.41555691e+00 -2.05467880e-01 1.11137405e-02\n 6.38890564e-02 4.91101183e-02 -3.80713530e-02 -2.13202432e-01\n 1.53977945e-02 1.16409265e-01 -8.72310102e-02 1.10443465e-01\n -1.49720788e-01 -1.11090122e-02 -1.13384956e-02 -2.72994228e-02\n -4.55622422e-03 1.11839272e-01 1.43418118e-01 -1.77296344e-02\n 9.79520380e-02 2.71633500e-03 1.36354595e-01 -9.91588011e-02\n 6.38762265e-02 -4.63984534e-03 8.94726366e-02 -1.16808668e-01\n -1.94695797e-02 -7.92093202e-02 -5.76880984e-02 -1.53986409e-01\n -1....,1,"{'perceptron': 1, 'sgd_classifier': 1, 'logistic_regression': 1, 'ridge_classifier': 1, 'decision_tree_classifier': 1, 'random_forest_classifier': 1, 'gradient_boosting_classifier': 1, 'support_vector_machine_classifier': 1, 'x_gradient_boosting_classifier': 1}",TP
...,...,...,...,...,...,...
449,- Net sales for the period are expected to fall well below that of last year and the result after non-recurring items is expected to be in the red .,1,[-8.35491568e-02 1.74877524e-01 -1.45196825e-01 -4.82006930e-03\n 6.23394623e-02 -1.14700764e-01 2.12556906e-02 3.89930382e-02\n 5.71866408e-02 2.25414515e+00 -2.10756734e-01 1.20626025e-01\n 4.13427204e-02 -8.13013911e-02 1.37749827e-02 -6.03617132e-02\n -7.00844172e-03 1.27165771e+00 -1.37619764e-01 -1.21111525e-02\n -5.20099327e-02 -3.89489979e-02 -1.14551105e-01 -6.84447074e-03\n 3.43069211e-02 7.21292794e-02 -1.71010613e-01 -4.37740199e-02\n -7.42981732e-02 4.03615423e-02 -9.13750604e-02 -2.01713443e-02\n -9.23616160e-03 8.53902996e-02 4.16183136e-02 9.04166996e-02\n -4.77619395e-02 5.23139387e-02 1.35975834e-02 -7.35252798e-02\n -1.08669279e-02 1.40048221e-01 1.18995987e-01 -6.80810362e-02\n 4.35065385e-03 1.83132775e-02 -7.01296851e-02 5.89403026e-02\n 4....,1,"{'perceptron': 1, 'sgd_classifier': 1, 'logistic_regression': 1, 'ridge_classifier': 1, 'decision_tree_classifier': 1, 'random_forest_classifier': 1, 'gradient_boosting_classifier': 1, 'support_vector_machine_classifier': 1, 'x_gradient_boosting_classifier': 1}",TP
450,"HELSINKI AFX - Kesko Corp is expected to report a lower second quarter EPS today due to tax charges , but other earnings lines are seen higher year-on-year , analysts said .",1,[-1.87278092e-01 2.34524801e-01 -1.10351175e-01 -1.12035619e-02\n 1.12474188e-01 -1.08608857e-01 2.42371205e-02 -4.57671247e-02\n -8.52811113e-02 1.92846823e+00 -1.51757121e-01 3.35961431e-02\n 1.01777248e-01 -1.61762051e-02 -1.55751273e-01 -1.68698076e-02\n 2.80520390e-03 9.87472653e-01 -7.03044012e-02 4.60346974e-03\n -3.84343378e-02 5.94458655e-02 1.36864744e-02 -9.73247066e-02\n 5.82338721e-02 9.53328460e-02 -1.41078159e-01 -2.38730554e-02\n 2.68500187e-02 4.03777659e-02 -8.47630054e-02 3.80122336e-03\n 3.54612879e-02 4.55406420e-02 4.13154438e-02 1.11670345e-01\n -6.22482039e-02 1.20000362e-01 -2.75798477e-02 -1.34728625e-01\n -3.94178033e-02 2.14527771e-02 1.01475112e-01 3.17193419e-02\n 2.20645554e-02 -6.89906068e-03 -4.68867831e-02 -9.73979682e-02\n 1....,1,"{'perceptron': 1, 'sgd_classifier': 1, 'logistic_regression': 1, 'ridge_classifier': 1, 'decision_tree_classifier': 1, 'random_forest_classifier': 1, 'gradient_boosting_classifier': 1, 'support_vector_machine_classifier': 1, 'x_gradient_boosting_classifier': 1}",TP
454,"Finnish Suominen Corporation that makes wipes , nonwovens , and flexible packaging , expects changes in the market situation to reduce sales of Suominen 's nonwovens and wet wipes from the previously estimated volumes .",1,[-7.12546930e-02 1.91423342e-01 -9.48487520e-02 -6.66781440e-02\n 1.18996250e-02 -2.84427521e-03 -2.92467494e-02 -7.89320618e-02\n 1.03791216e-02 1.76425302e+00 -1.53207615e-01 -5.94762387e-03\n 1.05014972e-01 -3.47590744e-02 -8.01404789e-02 -1.03053391e-01\n 1.70333143e-02 1.16122437e+00 -1.18970327e-01 -2.66303010e-02\n -6.28867522e-02 1.13025546e-01 -2.35239714e-02 -7.20139742e-02\n 3.00186016e-02 5.37111424e-02 -7.02564344e-02 -2.08823849e-02\n -4.38512024e-03 -1.38296694e-01 -2.19471343e-02 2.58289074e-04\n -9.51213688e-02 3.47092226e-02 1.08098716e-01 -4.43946347e-02\n 2.81006526e-02 2.67535029e-03 3.70422006e-02 -4.36210930e-02\n 4.40299585e-02 7.82010183e-02 4.18910980e-02 -1.55166350e-02\n -1.01831526e-01 -2.66389214e-02 -5.70112839e-02 4.29249689e-04\n 3....,1,"{'perceptron': 1, 'sgd_classifier': 1, 'logistic_regression': 1, 'ridge_classifier': 1, 'decision_tree_classifier': 0, 'random_forest_classifier': 1, 'gradient_boosting_classifier': 1, 'support_vector_machine_classifier': 1, 'x_gradient_boosting_classifier': 1}",TP
455,The net sales of the whole fiscal year 2008 will be lower than in 2007 and operating profit is estimated to be negative .,1,[-2.15959132e-01 2.41876766e-01 2.61752661e-02 -5.46340458e-02\n 2.23614331e-02 -8.86381939e-02 -1.01572899e-02 5.93509562e-02\n 1.25530437e-01 2.27500820e+00 -3.66276979e-01 1.39232576e-01\n 8.23947117e-02 -5.44000864e-02 2.41455529e-02 -6.53059268e-03\n -4.70587462e-02 1.36006749e+00 -2.51893312e-01 8.18898752e-02\n -1.67333689e-02 3.71401408e-03 -6.58917055e-02 5.14298826e-02\n 7.28507414e-02 2.94906665e-02 -1.69829905e-01 -8.03522095e-02\n -7.14486465e-02 5.70560060e-02 -8.47392306e-02 -5.59293739e-02\n -6.22268133e-02 8.15859139e-02 5.82795404e-02 1.14211654e-02\n -7.66408667e-02 5.73396981e-02 -2.73418110e-02 -8.35151449e-02\n 5.23026427e-03 1.71581030e-01 1.95276394e-01 -5.73360920e-03\n 6.17627464e-02 -6.51847348e-02 -1.99458711e-02 -8.17446411e-02\n 4....,1,"{'perceptron': 1, 'sgd_classifier': 1, 'logistic_regression': 1, 'ridge_classifier': 1, 'decision_tree_classifier': 1, 'random_forest_classifier': 1, 'gradient_boosting_classifier': 1, 'support_vector_machine_classifier': 1, 'x_gradient_boosting_classifier': 1}",TP
457,Repeats sees 2008 operating profit down y-y ( Reporting by Helsinki Newsroom ) Keywords : TECNOMEN-RESULTS,1,[-1.41439199e-01 1.78139731e-01 -1.27762944e-01 8.55224356e-02\n -2.68074032e-02 -2.75507532e-02 -8.95069987e-02 1.06929885e-02\n 8.28054827e-03 1.19909835e+00 -2.22982854e-01 1.22997284e-01\n -1.13301314e-01 -1.64714485e-01 -6.52322546e-02 -1.66982561e-02\n -1.26138002e-01 1.02284205e+00 -1.07507586e-01 -2.25867126e-02\n 3.07417512e-02 5.25910966e-02 7.28841051e-02 3.51193361e-02\n 1.55230433e-01 7.42465034e-02 -1.21129528e-01 -6.83583468e-02\n 1.01492748e-01 3.69950524e-03 -1.12686930e-02 2.80262642e-02\n -2.63586435e-02 4.51726373e-03 -3.92839778e-03 5.30510023e-02\n -5.46421716e-03 1.52594835e-01 -7.31348023e-02 -9.17828381e-02\n -2.66665081e-03 3.18934545e-02 7.64650777e-02 1.55075818e-01\n -3.15573253e-02 -3.13501023e-02 -4.38876078e-03 1.06920741e-01\n 5....,1,"{'perceptron': 1, 'sgd_classifier': 1, 'logistic_regression': 1, 'ridge_classifier': 1, 'decision_tree_classifier': 1, 'random_forest_classifier': 0, 'gradient_boosting_classifier': 0, 'support_vector_machine_classifier': 1, 'x_gradient_boosting_classifier': 0}",TP

In [56]:
class_pos_dfs = []
p_w = ["project", "expect", "forecast", "predict"]
class_names = mv_with_class_df['Class'].unique()

for class_name in class_names:
    print(f"CLASS: {class_name}")
    filt_class_name = (mv_with_class_df['Class'] == class_name)
    class_df = mv_with_class_df[filt_class_name].copy()

    # Extract POS features for THIS class only
    spacy_fe = SpacyFeatureExtraction(class_df, 'Base Sentence')
    pos_df = spacy_fe.extract_pos_features(disable_components=[], visualize=False)

    # Merge POS features with class DataFrame on sentence text
    class_pos_df = pos_df.merge(
        class_df[['Base Sentence', 'Class', 'Majority Vote', 'Sentence Label']],
        left_on='Sentence',
        right_on='Base Sentence',
        how='inner'
    )

    # Filter for prediction words
    filt_p_w = class_pos_df['Lemma'].str.lower().isin(p_w)
    pw_df = class_pos_df[filt_p_w]

    print(f"  Total rows: {len(class_pos_df)}")
    print(f"  Prediction word rows: {len(pw_df)}")
    print(pw_df[['Sentence', 'Term', 'Lemma', 'POS Label', 'Dependency']].to_string())

    class_pos_dfs.append(class_pos_df)

CLASS: TP

==================================================
EXTRACTING POS FEATURES
==================================================

Extracting POS Features: 100%|██████████| 388/388 [00:01<00:00, 324.09doc/s]

==================================================
DONE EXTRACTING POS FEATURES
==================================================
  Total rows: 8297
  Prediction word rows: 129
                                                                                                                                                                                                                                                                                                    Sentence       Term     Lemma POS Label Dependency
14                                                                                            With the new production plant the company would increase its capacity to meet the expected increase in demand and would improve the use of raw materials and therefore increase the production profitability .   expected    expect      VERB       amod
111                              The company still expects its turnover in 2010 to slightly increase from the level of 2009 , adding that `` market predictability is still too poor for trustworthy forecasts on the market development of the contract manufacturing business during the current year '' .    expects    expect      VERB       ROOT
137                              The company still expects its turnover in 2010 to slightly increase from the level of 2009 , adding that `` market predictability is still too poor for trustworthy forecasts on the market development of the contract manufacturing business during the current year '' .  forecasts  forecast      NOUN       pobj
210                                                                                                                                                                       Biohit already services many current Genesis customers and the customer base is expected to expand as a result of this agreement .   expected    expect      VERB      ccomp
281                                                                                                                                                                                                                                 The bank forecasts Finland 's GDP will grow by 2 % in 2010 and in 2011 .  forecasts  forecast      VERB       ROOT
298                                                                                                                                                                                                                                    Alma Media expects its net sales to increase as forecast previously .    expects    expect      VERB       ROOT
305                                                                                                                                                                                                                                    Alma Media expects its net sales to increase as forecast previously .   forecast  forecast      VERB      advcl
332                                                                                                                                                                                                           Metso expects its net sales to increase by about 10 % in 2008 , at comparable exchange rates .    expects    expect      VERB       ROOT
352                                                                                                                                                                                                                                 The company expects its net sales in 2008 to increase 5-10 % from 2007 .    expects    expect      VERB       ROOT
369                                                                                                                                                                                                        The company expects its net sales in the first half of 2008 to reach the previous year 's level .    expects    expect      VERB       ROOT
405                                                                                                                                                                                                                           Olvi expects sales and market share to increase in the first quarter of 2010 .    expects    expect      VERB       ROOT
456                                                                                                                                                                                                                    Ruukki forecast a 15-20 % annual sales growth and a positive pretax result for 2010 .   forecast  forecast      VERB       ROOT
525                                                                                                                                                                                              For the current year , Raute expects its net sales to increase and the operating result -- to be positive .    expects    expect      VERB       ROOT
698                                                                                                                                                                               According to A-Rehu 's Managing Director , Jouko Lahtinen , the project will stabilise costs and improve supply security .    project   project      NOUN      nsubj
716                                                                                          Actions to improve operational efficiency and adjust operations are expected to deliver annualised permanent cost savings of around EUR 4.5 million and will be effected mostly during the first half of 2010 .   expected    expect      VERB       ROOT
781                                                                                                                                                                                                                                           Net cash flow from operations is expected to remain positive .   expected    expect      VERB       ROOT
787                                                                                                                                                                                                Ponsse projects the forest machine markets to improve more than expected in 2010 from the previous year .   projects   project      VERB       ROOT
796                                                                                                                                                                                                Ponsse projects the forest machine markets to improve more than expected in 2010 from the previous year .   expected    expect      VERB      advcl
807                                                                                                                                                                                                                        The acquisition is expected to improve access to chrome ore resources in Turkey .   expected    expect      VERB       ROOT
1405                                                                                                                                                              However , sales volumes in the food industry are expected to remain at relatively good levels in Finland and in Scandinavia , Atria said .   expected    expect      VERB      ccomp
1761                                                                                                                   Lemminkainen Infra Oy 's subsidiary Lemminkainen Sverige AB will perform the construction work , which is expected to start in early 2011 and to be completed in the summer of 2013 .   expected    expect      VERB      relcl
1904                                                                                                                                                                                  The cooperation with airBaltic is expected to lead to the transfer of Finncomm to the ownership of airBaltic in time .   expected    expect      VERB       ROOT
2315                                                                                                                                                                                                                                        Construction is expected to be completed in the summer of 2011 .   expected    expect      VERB       ROOT
2435                                                                                                                                                                                                                                                     It is expected to be completed by the end of 2007 .   expected    expect      VERB       ROOT
2721                                                                                                                                                                                                            The Extraordinary General Meeting is expected to take place no later than 18 February 2011 .   expected    expect      VERB       ROOT
2737                                                                                                                                                                                                                    The first of the two project phases is expected to be completed by the end of 2012 .    project   project      NOUN   compound
2740                                                                                                                                                                                                                    The first of the two project phases is expected to be completed by the end of 2012 .   expected    expect      VERB       ROOT
2786                                                                                                                      The order includes a steel frame , load-bearing roof structures and partition wall elements , and Rautaruukki said it expects to complete installation as early as May next year .    expects    expect      VERB      ccomp
2798                                                                                                                                                                                                                                                       The project is expected to be completed in 2009 .    project   project      NOUN  nsubjpass
2800                                                                                                                                                                                                                                                       The project is expected to be completed in 2009 .   expected    expect      VERB       ROOT
2935                                                                                                                                                                                                                                               The transaction is expected to be completed next spring .   expected    expect      VERB       ROOT
3378                                                                                                                                                                                                    In the Baltics , the merger of the businesses of the two is expected to be completed in early 2008 .   expected    expect      VERB       ROOT
3431                                                                                                                                                  It is the last smartphone running Maemo 5 , which is to be replaced with MeeGo , a joint project between Nokia , Intel and the open source community .    project   project      NOUN      appos
3483                                                                                                                                                                                                                               NetCom expects to complete Turbo 3G deployment in these areas this year .    expects    expect      VERB       ROOT
3856                                                                                                                                                                                                                 The second-quarter net sales are expected to be on par with the first quarter of 2009 .   expected    expect      VERB       ROOT
4060                                                                                                          JP Morgan expects that Scala will lower Nobel Biocare 's growth forecast for 2007 from the current guidance of 23-25 pct , as well as the operating margin target from the current 34-35 pct .    expects    expect      VERB       ROOT
4069                                                                                                          JP Morgan expects that Scala will lower Nobel Biocare 's growth forecast for 2007 from the current guidance of 23-25 pct , as well as the operating margin target from the current 34-35 pct .   forecast  forecast      NOUN       dobj
4146                                                                    Under a memorandum of understanding MoU the parties will collaborate in preparing and implementing joint projects in the fields of combined power and heat generation , environmental protection and energy efficient technologies .   projects   project      NOUN       dobj
4170                                                                          For the full 2010 the company expects its net sales and operating result to improve from the previous year , saying that a positive operating result and its amount will depend on the order intake by the end of the summer .    expects    expect      VERB       ROOT
4236                                                                                                                                                                               Mr Lee said he hoped that Neste 's move will ` pave the way for more collaboration projects between our two countries ' .   projects   project      NOUN       pobj
4290                                                                                                                                                              The developers of that project predict that once it is completed in April 2009 , Skanssi will attract some 4.5 million visitors annually .    project   project      NOUN       pobj
4291                                                                                                                                                              The developers of that project predict that once it is completed in April 2009 , Skanssi will attract some 4.5 million visitors annually .    predict   predict      VERB       ROOT
4459                                                                                                                                                                                         The three year turn-around program is expected to ensure Salomon 's future competitiveness , the company said .   expected    expect      VERB      ccomp
4511                                                Technopolis said before the protocol was signed that the techno-park would be built at a site covering more than six hectares in the Neudorf special economic zone and that it planned to invest 200 million euros in the project until 2009 inclusive .    project   project      NOUN       pobj
4649                                                                                     Suominen Corporation estimates that the cost-cutting program that started in autumn 2005 , higher sales prices , and expected growth in volume of Wet Wipes , will make the company 's operations more profitable .   expected    expect      VERB      ccomp
4734                                                                                                                                                                                                     Talentum expects that the net sales of its core business will increase in 2008 , compared to 2007 .    expects    expect      VERB       ROOT
4788                                                                              Fiskars , a 360-year-old global business best known for its orange-handled scissors , expects to derive synergies of EUR5 million a year by consolidating certain parts of the housewares division where the two compete .    expects    expect      VERB       ROOT
4816                                                                                                                                                                                                                 Full-year net sales are expected to increase by approximately 10 % , the company said .   expected    expect      VERB      ccomp
4851                                                              in Q1 '10 19 April 2010 - Finnish forest machinery and equipment maker Ponsse Oyj HEL : PON1V said today that it expects to swing to a net profit of some EUR6 .3 m in the first quarter of 2010 , from an EUR9 .6 m loss a year earlier .    expects    expect      VERB      ccomp
4886                                                                                                                                                                                                                                               Net sales revenue per passenger is expected to increase .   expected    expect      VERB       ROOT
4928                                                                                                                                                         Via the move , the company aims annual savings of some EUR 3 million USD 4.3 m , the main part of which are expected to be realized this year .   expected    expect      VERB      advcl
4946                                                                                                                 H+_kan Dahlstr+ï¿½m , head of mobility services at TeliaSonera , has forecast that mobile data volume on the TeliaSonera network in Sweden will rise eight-fold to 200,000 TB by 2014 .   forecast  forecast      VERB       ROOT
4991                                                                                                                                                                                                                                       Cymed 's net sales are expected to amount to EUR 3.5 mn in 2006 .   expected    expect      VERB       ROOT
5004                                                                                                                                                                                                                                           However , he expects banks to provide alternative financing .    expects    expect      VERB       ROOT
5081                                                Jens Schulte-Bockum , Vodafone 's global director of terminals , said the company expects to sell one to two million of the Vodafone 125 and 225 models in the first year of launch , and potentially tens of millions over the lifetime of the device .    expects    expect      VERB      ccomp
5120                                                                                                                                                                                           M-real 's sales are expected to have increased by 4 % year-on-year to EUR609m in the second quarter of 2010 .   expected    expect      VERB       ROOT

Extracting POS Features: 100%|██████████| 70/70 [00:00<00:00, 276.64doc/s]

==================================================
DONE EXTRACTING POS FEATURES
==================================================
  Total rows: 1692
  Prediction word rows: 18
                                                                                                                                                                                                           Sentence       Term     Lemma POS Label Dependency
102                                                                                            Affecto expects its net sales for the whole 2010 to increase from the 2009 level when they reached EUR 103 million .    expects    expect      VERB       ROOT
157                                                                                       Vaisala also said it expects net sales of EUR 253.2 million for 2010 , compared with EUR 252.2 million recorded in 2009 .    expects    expect      VERB      ccomp
742   The transaction , which includes US$ 1.5 billion euro1 billion in cash , vendor notes and share purchases , is expected to be completed in the first quarter of 2008 , the Finnish-Swedish paper maker said .   expected    expect      VERB      ccomp
887                                                                                                                                                       For 2009 , Incap expects revenue of some EUR 70 million .    expects    expect      VERB       ROOT
935                                                                                             It projected revenue of $ 2.2 billion to $ 2.3 billion , slightly higher than analyst estimates of $ 2.19 billion .  projected   project      VERB       ROOT
963                                                                        OMEO ( www.omeo.se ) employs 55 and expects net sales of some 23 mln euro ( $ 29.8 mln ) for fiscal 2006-2007 , ending April 30 , 2007 .    expects    expect      VERB       conj
990                                                                                                                                          The company expects net sales of 65 mln euro ( $ 85.1 mln ) for 2006 .    expects    expect      VERB       ROOT
1007                                                                                                                                                 The company expects sales revenue of RMB8 .0 billion in 2009 .    expects    expect      VERB       ROOT
1028                                                                                                                                                        Aktia forecasts Finland 's inflation at 1.1 % in 2010 .  forecasts  forecast      VERB       ROOT
1123                                                                                                     Deliveries of Nokia 1112 , Nokia 2310 and Nokia 2610 are expected to start in the second quarter of 2006 .   expected    expect      VERB       ROOT
1134                                                             Fortum expects its annual capital expenditure in the next four to five years to be within a range of EUR 0.8-1 .2 billion , as earlier announced .    expects    expect      VERB       ROOT
1201  Subscribers of China Unicom , the nation 's second largest mobile phone operator after China Mobile , are expected to release pictures , videos and blog on the Internet via mobile phones as of March 2008 .   expected    expect      VERB       ROOT
1223                                                                                                                 The train is expected to cross the Russian territory in 9 days , reaching the Vostochny port .   expected    expect      VERB       ROOT
1243                                                                                                                      Analysts surveyed by Thomson Financial expected revenue of $ 69 million for the quarter .   expected    expect      VERB       ROOT
1273                                                  Based on the 2005 calendar year the combined company had EUR15 .8 bn in pro forma annual revenues and is expected to start operations with 60,000 employees .   expected    expect      VERB       conj
1298                                                                                                           Elcoteq expects its net sales for the last quarter of 2010 to be on the level of the third quarter .    expects    expect      VERB       ROOT
1320                                                                                           EQ Bank forecasts Olvi 's net sales at EUR 67mn in the second quarter of 2009 , and operating profit at EUR 6.4 mn .  forecasts  forecast      VERB       ROOT
1570  According to Scanfil , demand for telecommunications network products has fluctuated significantly in the third quarter of 2006 , and the situation is expected to remain unstable for the rest of the year .   expected    expect      VERB       conj
CLASS: FP

==================================================
EXTRACTING POS FEATURES
==================================================

Extracting POS Features: 100%|██████████| 1852/1852 [00:05<00:00, 312.82doc/s]

==================================================
DONE EXTRACTING POS FEATURES
==================================================
  Total rows: 42531
  Prediction word rows: 72
                                                                                                                                                                                                                                                                                       Sentence       Term     Lemma POS Label Dependency
450                                                                                                                                                                                                             An individual promotion also generated slightly higher-than-expected revenues .   expected    expect      VERB      pcomp
2149   `` Of course , we are in talks with all those coming up with new projects that involve material handling , '' Konecranes President and CEO Pekka Lundmark said , when asked whether it was talking to Reliance Industries for supplying equipment to its upcoming refinery in Jamnagar .   projects   project      NOUN       pobj
3054                                                                                                                                The offer of some 30 million shares aimed to raise more than  x20ac 500 million US$ 640 million , was expected to be completed by Oct. 9 , Outokumpu said .   expected    expect      VERB      ccomp
3507                               On January 29 , 2009 The largest Nordic bank Nordea and Finnish retail chain Stockmann launched a regionally unique cooperation project : they are the first to introduce a common MasterCard credit card enabling payments in different states and stores .    project   project      NOUN       dobj
4135                                                                                                                                                 Both loans will be used to finance strategic investments such as shopping center redevelopment projects and refinancing of maturing debt .   projects   project      NOUN       pobj
5299                                             Finnish steel maker Rautaruukki Oyj ( Ruukki ) said on July 7 , 2008 that it won a 9.0 mln euro ( $ 14.1 mln ) contract to supply and install steel superstructures for Partihallsforbindelsen bridge project in Gothenburg , western Sweden .    project   project      NOUN       pobj
5431                                                                                                                                                                                                               Industry Investment is very interested in Glaston 's solar energy projects .   projects   project      NOUN       pobj
5728                                                                                                                                                                                                                       That topped consensus forecasts for earnings of 0.21 euros a share .  forecasts  forecast      NOUN       dobj
5959                                                                                                                                               The pilot project proved that RIFD technology is ideal for our purposes '' , comments Olli Saarinen , Material Handling Supervisor at Yara .    project   project      NOUN      nsubj
7180                                                                                                              Metrics in QPR ScoreCard now support date , text and milestone-based values , which improve its support for managing projects around performance or process-related content .   projects   project      NOUN       dobj
9904                                                                                                                                                                                                     The company is presently examining whether the project would be financially feasible .    project   project      NOUN      nsubj
10358                                                                                    The scope of the project is to find the most cost-efficient method for phosphorous removal and to deliver the storing and dosing equipment , which can be used in continuous operation at the plants .    project   project      NOUN       pobj
11345                                                                                                                      A downloadable instruction sheet , instructional video , and project ideas for the award-winning Everywhere Punch TM Window System can be found at www.fiskars.com .    project   project      NOUN       conj
12378                                                                                                                 Product coverage : baked goods ; biscuits ; breakfast cereals Data coverage : market sizes historic and forecasts , company shares , brand shares and distribution data .  forecasts  forecast      NOUN       conj
12735                                                                                                                                                                          The deal strengthens Ramirent 's position especially in the industrial sector and in large investment projects .   projects   project      NOUN       pobj
13731                                                                              The seminar introduced modern , clean technologies and products , financial tools and sponsorship programs for energy and environment projects as well as the potential to develop clean energy in Vietnam .   projects   project      NOUN       pobj
13992                                                                                                EuroChem CFO Andrey Ilyin said : `` This facility marks another important step for EuroChem in securing the long-term financing necessary for our potash and other strategic projects '' .   projects   project      NOUN       conj
14183                                                                                                              Tieto offers Aktia a good foundation and the required support services for implementing the update project , ' says Juha Volotinen , responsible for Aktia 's web services .    project   project      NOUN       dobj
15407                                                                                                                                                                                                         Poyry has a good track record of major transportation projects in Latin America .   projects   project      NOUN       pobj
15857                                                                                                                                                    CDLI highlights the companies that provided the most comprehensive response to the Carbon Disclosure Project CDP information request .    Project   Project     PROPN   compound
15961                                                                                                                                       Founded in 1994 , the company uses a six-step , time-focused , collaborative project approach to improve financial institutions ' revenue streams .    project   project      NOUN   compound
16250                                                                                                                                              The social plan negotiations were part of the three year turn-around program which is expected to ensure Salomon 's future competitiveness .   expected    expect      VERB      relcl
16273                                                                                                                                  The tool is a patent pending design that allows consumers to lay out their entire project on a removable plate using multiple clear stamps of any kind .    project   project      NOUN       dobj
17585                                                                                                                                                 According to Olvi 's Managing Director Lasse Aho , the company has an ongoing MMX Plus project that aims to find growth outside Finland .    project   project      NOUN       conj
17655                                           Finnish elevators and escalators maker KONE Corporation said on Tuesday ( 18 March ) that it has received a major order from Sir Robert McAlpine to supply all elevators and escalators for the Watermark Place project in the City of London .    project   project      NOUN       pobj
18124                                                                                                         Metso will supply the equipment for two process lines at Northland Resources ' new Kaunisvaara iron ore project in Sweden which exploits Tapuli and Sahavaara iron ore deposits .    project   project      NOUN       pobj
18298                                                     Solvay S.A. has engaged Poyry to provide project management , engineering , procurement , and site services for a hydrogen peroxide production plant to be built by a Solvay-BASF joint venture at BASF 's Zandvliet site , Belgium .    project   project      NOUN   compound
18336                                                                                                                                                                                    Systeemitiimi 's sales and project resources will also be strengthened , director Paul Skogberg said .    project   project      NOUN       conj
18491                                                                                                                                                         The German subsidiary will produce software development services for Ixonos Telecommunications Business Unit 's client projects .   projects   project      NOUN       pobj
18741                                                                                                                                                                                    We can capitalize on our experience from a number of similar bridge projects in the Nordic countries .   projects   project      NOUN       pobj
19013                                                                                                                                         This assignment strengthens Poyry 's position as an international provider of engineering and project services to the chemical process industry .    project   project      NOUN       conj
19399                                                                                                                                                                                                                                 A total of $ 78 million will be invested in the project .    project   project      NOUN       pobj
19852                                                                                                                                                                                          According to Aktia Asset Management , Finnish analysts ' forecasts for 2009 are still too high .  forecasts  forecast      NOUN      nsubj
20644                                                                                                         facades in Riga 8 March 2010 - Finnish construction company YIT Oyj HEL : YTY1V said today that it will build the frame and the facades in a tower construction project in Riga .    project   project      NOUN       pobj
21127                                                                                                                                                                                                                          Kemira 's partner in the project is St. Petersburg Water Works .    project   project      NOUN       pobj
23931                                                                                                                       AHMS will also offer Hotel and Hotel Project Consultancy , Management Services , Brand Franchise , Training and Sales and Marketing services on a pan-India basis .    Project   Project     PROPN   compound
23987                                                                                                                                                                              Also Finnish Industry Investment , a government-owned investment company , will participate in the project .    project   project      NOUN       pobj
24821                                                                                                                                                                                          Depending on the market situation , such projects are sold after 1 to 3 years after completion .   projects   project      NOUN  nsubjpass
25727                                                                                                                            Implementation of the project will be carried out by the Finnish company YIT in association with the investment fund Evli Property Investment Russia ( EPI ) .    project   project      NOUN       pobj
28656                                                                                                                                                                    The company 's model is based on developer contracting construction projects and customer focused project management .   projects   project      NOUN       pobj
28660                                                                                                                                                                    The company 's model is based on developer contracting construction projects and customer focused project management .    project   project      NOUN   compound
28773                                                                                                                                                              The compnay also said that it would lower the price of development projects by about one third compared with last November .   projects   project      NOUN       pobj
28785                                                                                                                                        The construction project is scheduled to start in the second quarter of 2009 and the new building is scheduled to be in place by the end of 2010 .    project   project      NOUN  nsubjpass
29931                                                                                                              The Process Products orders are for the installation of separation-filtration equipment at three natural gas pipeline projects in China , South America , and Saudi Arabia .   projects   project      NOUN       pobj
29961                                                                                                                                                                                                                     The project also implies an underground parking lot for 56 vehicles .    project   project      NOUN      nsubj
30280                                                              The subject of the project is provide to the company like : Software programming and consultancy services , Computer-related services , Data services , Computer support and consultancy services , Internet services etc. .    project   project      NOUN       pobj
30354                                                                                                                                                                                         The total size of the complex is around 25,000 m2 and the project will be constructed in stages .    project   project      NOUN  nsubjpass
32138                                                                                                         Currently Alfred A Palmberg is putting the finishing touches to one of Finland 's biggest ever re-plumbing and bathroom refurbishment projects also in the district of Vuosaari .   projects   project      NOUN       pobj
32287                                                                                                                                                                                                                                    Financing of the project will come mainly from China .    project   project      NOUN       pobj
32465                                                                                                                                                                                                     Fortum is now considering taking part in nuclear energy projects outside of Finland .   projects   project      NOUN       pobj
32498                                                                                                                                                           Honkarakenne 's customer in this project is one of the biggest real estate companies in Kazakhstan , according to the company .    project   project      NOUN       pobj
33410                                                                                                      Risto Raty , Tekla 's executive vice president , said that Tekla Structures and ArchiCAD will cover the entire design and documentation workflow throughout a construction project .    project   project      NOUN       pobj
33961                                                                                                                                                                                      The contract includes an option to deliver an additional 75 ASCs in the next phases of the project .    project   project      NOUN       pobj
34723                                                                                                                                                                                      The retail chain launched in 2007 does not correspond to profit and sales forecasts of the company .  forecasts  forecast      NOUN       pobj
34777                                                                                                       The Stockmann department store will have a total floor space of over 8,000 square metres and Stockmann 's investment in the project will have a price tag of about EUR 12 million .    project   project      NOUN       pobj
34880                                                                                                                                                                                                                       The total investment of the project will be approximately EUR 36m .    project   project      NOUN       pobj
34915                                                                                                                                                                                  The total value of the project is about EUR53m , including the plots that will be transferred to Atria .    project   project      NOUN       pobj
35256                                                                                          Under the agreement , Larox will transfer 10 employees within engineering and documentation related to delivery projects and product maintenance in Finland to Etteplan as of January 1 , 2007 .   projects   project      NOUN       pobj
37864                                                                                                                                                                                               shock phase ' , consumers have once again started to plan and implement building projects .   projects   project      NOUN       dobj

Extracting POS Features: 100%|██████████| 2536/2536 [00:08<00:00, 297.55doc/s]

==================================================
DONE EXTRACTING POS FEATURES
==================================================
  Total rows: 63185
  Prediction word rows: 62
                                                                                                                                                                                                                                                                                    Sentence       Term     Lemma POS Label Dependency
3307                                                                         A structures BIM ( building information modeling ) software from Tekla , a model-based software provider , has been adopted for the construction management and delivery of a university project in Abu Dhabi .    project   project      NOUN       pobj
7143                                                                                                                                     Finnish Larox has signed a contract with the Talvivaara Project for the delivery of filters to the Talvivaara nickel mine in Sotkamo , in Finland .    Project   Project     PROPN       pobj
7273                                                                                                                                                                               EPS for the quarter came in at 0.36 eur , up from 0.33 eur a year ago and ahead of forecast of 0.33 eur .   forecast  forecast      NOUN       pobj
8625                                                                   The mall is part of the Baltic Pearl development project in the city of St Petersburg , where Baltic Pearl CJSC , a subsidiary of Shanghai Foreign Joint Investment Company , is developing homes for 35,000 people .    project   project      NOUN       pobj
9384                                                                The building owner and developer , Sun Hung Kai Properties Group , is one of the largest property companies in Hong Kong , developing all types of premium residential and commercial projects for sale and investment .   projects   project      NOUN       pobj
9858                                            Baltic Pearl CJSC , a subsidiary of Shanghai Foreign Joint Investment Company , is developing a project in St Petersburg , comprising about a million square meters of residential space , two hospitals and several schools and nurseries .    project   project      NOUN       dobj
11409                                                                                               The company has also supplied more than 200 MW of power generating equipment for a number of projects in Papua New Guinea , including 12 engines of the Wartsila 32 type to Lihir Gold .   projects   project      NOUN       pobj
13099                                              2009 3 February 2010 - Finland-based steel maker Rautaruukki Oyj ( HEL : RTRKS ) , or Ruukki , said today it slipped to a larger-than-expected pretax loss of EUR46m in the fourth quarter of 2009 from a year-earlier profit of EUR45m .   expected    expect      VERB      pcomp
13156                                                 ( ADPnews ) - Feb 3 , 2010 - Finland-based steel maker Rautaruukki Oyj ( HEL : RTRKS ) , or Ruukki , said today it slipped to a larger-than-expected pretax loss of EUR 46 million ( USD 64.5 m ) in the fourth quarter of 2009 from a   expected    expect      VERB      pcomp
13777                                                                              Neste Oil said it will build a biodiesel production facility in Rotterdam , the Netherlands , at an estimated cost of 670 million euros , naming France-based Technip as the project 's main contractor .    project   project      NOUN       poss
14815                                                                                                                                                                                                                     Demand was brisk as expected and order levels have remained high .   expected    expect      VERB      advcl
15401                              Adanac Molybdenum of Canada has ordered grinding technology for its molybdenum project in British Columbia , Canada , while Shalkiya Zinc of Kazakhstan has awarded a contract for grinding technology for the Shalkiya zinc-lead project in Kazakhstan .    project   project      NOUN       pobj
15426                              Adanac Molybdenum of Canada has ordered grinding technology for its molybdenum project in British Columbia , Canada , while Shalkiya Zinc of Kazakhstan has awarded a contract for grinding technology for the Shalkiya zinc-lead project in Kazakhstan .    project   project      NOUN       pobj
16275                                                                                                                    The Australian company Mirabela Nickel has awarded Outokumpu Technology a contract for grinding technology for its nickel sulfide project in Bahia State , Brazil .    project   project      NOUN       pobj
17106                                                                                                                                                                         Sales came in at 241 mln eur , compared with 211.4 mln , and also beating consensus forecasts of 235 mln eur .  forecasts  forecast      NOUN       dobj
17315                                                                                                                                                   The third order awarded to Outokumpu Technology is by Shalkiya Zinc of Kazakhstan for the Shalkiya zinc-lead project in Kazakhstan .    project   project      NOUN       pobj
18649                                                                  The Swedish subsidiary holds 1.0 % net smelter return `` NSR '' royalties over two advanced copper projects in northern Sweden - the Viscaria and Adak Projects - being developed by Avalon Minerals Ltd. ASX : AVI .   projects   project      NOUN       pobj
20745                                                                                                                                                                                                               Previously , the plant was expected to be completed by the end of 2008 .   expected    expect      VERB       ROOT
20770                                                                                                               Prothious Engineering ( www.prothious.com ) employs more than 1,000 and has a large portfolio of projects and an annual detailing capacity of more than 100,000 tonnes .   projects   project      NOUN       pobj
20896                          Russia 's top container shipping group , Fesco , and Finnish logistics company Nurminen Logistics have started a pilot project offering clients direct intermodal transportation service from Finland to Asia Pacific countries , Fesco said in a statement .    project   project      NOUN       dobj
20962                                                                                                                                                                            Shuweihat 2 got under way in July 2008 when the project was awarded to desalination and power contractors .    project   project      NOUN  nsubjpass
22150                                                                                                                                                                                                     The total value of the project is valued at SEK 30bn ( EUR 2.83 bn USD 3.81 bn ) .    project   project      NOUN       pobj
22192                                                                                                                                                                 The training modules aim at strengthening the public accounting abilities and fulfilling communal project management .    project   project      NOUN   compound
22379  ` Ruukki has experience of logistics construction , competence in project management and also has the best references in terms of steel frame production and installation , ' says Onodi Stefan , General Manager of Arxikon Construction Company SRL , which is Ruukki 's customer .    project   project      NOUN   compound
22731                                                                                                                                                                Further concrete cooperation is also carried out through various projects , doctoral theses and diploma dissertations .   projects   project      NOUN       pobj
23941                                                                                                                                                                                                         The total project duration is three years and it is valued at some EUR11 .5 m.    project   project      NOUN   compound
23960                                                                                                                                                                            The total scope of the project is about 38,000 square metres and it is valued at a total of around EUR75m .    project   project      NOUN       pobj
24604                                                                                                                                                          Affecto has helped SKAT to set up the platform and has previously delivered several Business Intelligence projects for SKAT .   projects   project      NOUN       dobj
26515                                                                                                                     The process , technology , project management , basic engineering and quality assurance within Forest Industry will be consolidated in Vantaa , southern Finland .    project   project      NOUN   compound
26633                                                                                            We have sound experience of project deliveries for large multi-purpose complexes and sports arenas '' , says Sami Eronen , SVP , Infrastructure and Northern Europe , Ruukki Construction .    project   project      NOUN   compound
27082                                                                                                                                                                                            An appeal concerning the project has been lodged at the Czech Ministry of the Environment .    project   project      NOUN       dobj
27105                                                                                                                                                              Aspocomp has a large factory in China and a factory building project in India that was halted due to financing problems .    project   project      NOUN       conj
27311                                                                                                                           Markets had been expecting a poor performance , and the company 's stock was up 6 percent at  x20ac 23.89 US$ 33.84 in early afternoon trading in Helsinki .  expecting    expect      VERB       ROOT
28158                                                                                                                           The decision of Tekes was based on , among other , the following grounds : the project has a significant impact on the business development of the company .    project   project      NOUN      nsubj
28421                                                                 Vaahto , which has entered the deal via its subsidiary Vaahto Pulp & Paper Machinery , will supply two of the units in the end of 2010 , while the remaining ones are expected for delivery in the beginning of 2011 .   expected    expect      VERB      advcl
28783                                                                                                                                                                                       Commencing the construction works of Pearl Plaza is a significant step in our Russian projects .   projects   project      NOUN       pobj
29679                                                                                                                                                                         It expects revenue between $ 8.4 billion and $ 8.7 billion , compared to analyst estimates of $ 8.67 billion .    expects    expect      VERB       ROOT
30717                                                                                                                                                                                                          The first quarter was as expected and was in line with analysts ' forecasts .   expected    expect      VERB      acomp
30725                                                                                                                                                                                                          The first quarter was as expected and was in line with analysts ' forecasts .  forecasts  forecast      NOUN       pobj
33283                                                                                                                                           Construction work on the Helsinki Music Centre is to start this autumn , with the total cost of the project estimated at 140 million euros .    project   project      NOUN       pobj
34214                                                               No price was given for the transaction , which merges two London companies that have worked together on a number of projects including delivery of timetables for Britain 's National Express East Coast rail networks .   projects   project      NOUN       pobj
42306                                                                                                                                            The firm 's services include copying , printing , CAD-modelling , digital printing , scanning , SokoPro project bank and courier services .    project   project      NOUN   compound
43661                                                                                                                                                                               The volume of investments in the two phases of the project is estimated at USD 300mn ( EUR 215.03 mn ) .    project   project      NOUN       pobj
44114                                                                                                                                              YIT acquired investment rights to a 10,000 square metre residential project in Yaroslavl and to a 16,400 square metre project in Moscow .    project   project      NOUN       pobj
44123                                                                                                                                              YIT acquired investment rights to a 10,000 square metre residential project in Yaroslavl and to a 16,400 square metre project in Moscow .    project   project      NOUN       pobj
47324                                                                                                                            One of the largest projects of the magazine division of SanomaWSOY - Sanoma Magazines International in 2006 became launch of the Russian magazine Gloriya .   projects   project      NOUN       pobj
48219                                                                                                                                                                                                                             The bridge is part of the highway 14 development project .    project   project      NOUN       pobj
49466                                                                                                                             The most significant capital expenditure items were in the global enterprise resource planning ERP project , product development and production machines .    project   project      NOUN       pobj
49536                                                                                                   The ongoing project where Tekla Structures is being used is the Vashi Exhibition Centre being developed by Insteel Engineers Pvt Ltd-IIVRCL Infrastructures & Projects Ltd & CIDCO .    project   project      NOUN      nsubj
53152                                                          Among the Scandinavian companies present in St. Petersburg , is also named the Swedish concern NCC , which implements projects in the field of asphalt production , road and housing construction ( project Swedish Krona ) .   projects   project      NOUN       dobj
53165                                                          Among the Scandinavian companies present in St. Petersburg , is also named the Swedish concern NCC , which implements projects in the field of asphalt production , road and housing construction ( project Swedish Krona ) .    project   project      NOUN      appos
53952                                                                                                                                                                      The project will be a 2 x 600 MW coal-fired power plant , located some 420 km south of Hanoi , the company said .    project   project      NOUN      nsubj
54742                                                                                                                                                     The pine oil project is related to the upgrade of the chemical recovery plant of UPM at its pulp mill in Kymi , southern Finland .    project   project      NOUN  nsubjpass
57171              PGE Belchatow runs the 4.44 GW Belchatow coal-fired power plant , and Fortum has intentions to start a CCS demonstration project jointly with Teollisuuden Voima Oyj ( TVO ) - another Finnish utility - at the their jointly owned 565MW Meri-Pori coal-fired facility .    project   project      NOUN       dobj
58070                                                                                                   Marubeni has participated in GHG - Green House Gas - emission reduction projects overseas , obtained emissions credit from its projects and has provided these to Japanese clients .   projects   project      NOUN       pobj
58078                                                                                                   Marubeni has participated in GHG - Green House Gas - emission reduction projects overseas , obtained emissions credit from its projects and has provided these to Japanese clients .   projects   project      NOUN       pobj
61800                                                                                                                                                                                                                        Talentum 's net sales in September were smaller than expected .   expected    expect      VERB      advcl
61979                                                             According to the company , its operating profit , excluding non-recurring items , in the fourth quarter of 2009 was significantly better than expected , and also better than the figures for the fourth quarter of 2008 .   expected    expect      VERB      advcl
62002                                                                                                                                                                                   `` I am extremely delighted with this project and the continuation of cooperation with Viking Line .    project   project      NOUN       pobj

In [57]:
class_pos_dfs[0]

,Sentence,Term,Lemma,POS Label,Detailed POS Label,Dependency,Shape,Is Alpha,Stop Word,Unique POS Label,...,Acc,Gen,Loc,Ins,Parat,Prep,Base Sentence,Class,Majority Vote,Sentence Label
0,With the new production plant the company would increase its capacity to meet the expected increase in demand and would improve the use of raw materials and therefore increase the production profitability .,With,with,ADP,IN,prep,Xxxx,True,True,ADP_1,...,,,,,,,With the new production plant the company would increase its capacity to meet the expected increase in demand and would improve the use of raw materials and therefore increase the production profitability .,TP,1,1
1,With the new production plant the company would increase its capacity to meet the expected increase in demand and would improve the use of raw materials and therefore increase the production profitability .,the,the,DET,DT,det,xxx,True,True,DET_1,...,,,,,,,With the new production plant the company would increase its capacity to meet the expected increase in demand and would improve the use of raw materials and therefore increase the production profitability .,TP,1,1
2,With the new production plant the company would increase its capacity to meet the expected increase in demand and would improve the use of raw materials and therefore increase the production profitability .,new,new,ADJ,JJ,amod,xxx,True,False,ADJ_1,...,,,,,,,With the new production plant the company would increase its capacity to meet the expected increase in demand and would improve the use of raw materials and therefore increase the production profitability .,TP,1,1
3,With the new production plant the company would increase its capacity to meet the expected increase in demand and would improve the use of raw materials and therefore increase the production profitability .,production,production,NOUN,NN,compound,xxxx,True,False,NOUN_1,...,,,,,,,With the new production plant the company would increase its capacity to meet the expected increase in demand and would improve the use of raw materials and therefore increase the production profitability .,TP,1,1
4,With the new production plant the company would increase its capacity to meet the expected increase in demand and would improve the use of raw materials and therefore increase the production profitability .,plant,plant,NOUN,NN,pobj,xxxx,True,False,NOUN_2,...,,,,,,,With the new production plant the company would increase its capacity to meet the expected increase in demand and would improve the use of raw materials and therefore increase the production profitability .,TP,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8292,Repeats sees 2008 operating profit down y-y ( Reporting by Helsinki Newsroom ) Keywords : TECNOMEN-RESULTS,Keywords,keyword,NOUN,NNS,ROOT,Xxxxx,True,False,NOUN_1723,...,,,,,,,Repeats sees 2008 operating profit down y-y ( Reporting by Helsinki Newsroom ) Keywords : TECNOMEN-RESULTS,TP,1,1
8293,Repeats sees 2008 operating profit down y-y ( Reporting by Helsinki Newsroom ) Keywords : TECNOMEN-RESULTS,:,:,PUNCT,:,punct,:,False,False,PUNCT_805,...,,,,,,,Repeats sees 2008 operating profit down y-y ( Reporting by Helsinki Newsroom ) Keywords : TECNOMEN-RESULTS,TP,1,1
8294,Repeats sees 2008 operating profit down y-y ( Reporting by Helsinki Newsroom ) Keywords : TECNOMEN-RESULTS,TECNOMEN,tecnomen,NOUN,NN,compound,XXXX,True,False,NOUN_1724,...,,,,,,,Repeats sees 2008 operating profit down y-y ( Reporting by Helsinki Newsroom ) Keywords : TECNOMEN-RESULTS,TP,1,1
8295,Repeats sees 2008 operating profit down y-y ( Reporting by Helsinki Newsroom ) Keywords : TECNOMEN-RESULTS,-,-,PUNCT,HYPH,punct,-,False,False,PUNCT_806,...,,,,,,,Repeats sees 2008 operating profit down y-y ( Reporting by Helsinki Newsroom ) Keywords : TECNOMEN-RESULTS,TP,1,1
8296,Repeats sees 2008 operating profit down y-y ( Reporting by Helsinki Newsroom ) Keywords : TECNOMEN-RESULTS,RESULTS,result,NOUN,NNS,appos,XXXX,True,False,NOUN_1725,...,,,,,,,Repeats sees 2008 operating profit down y-y ( Reporting by Helsinki Newsroom ) Keywords : TECNOMEN-RESULTS,TP,1,1

In [58]:
class_pos_dfs[1]

,Sentence,Term,Lemma,POS Label,Detailed POS Label,Dependency,Shape,Is Alpha,Stop Word,Unique POS Label,...,Acc,Gen,Loc,Ins,Parat,Prep,Base Sentence,Class,Majority Vote,Sentence Label
0,"STORA ENSO , NORSKE SKOG , M-REAL , UPM-KYMMENE Credit Suisse First Boston ( CFSB ) raised the fair value for shares in four of the largest Nordic forestry groups .",STORA,STORA,PROPN,NNP,compound,XXXX,True,False,PROPN_1,...,,,,,,,"STORA ENSO , NORSKE SKOG , M-REAL , UPM-KYMMENE Credit Suisse First Boston ( CFSB ) raised the fair value for shares in four of the largest Nordic forestry groups .",FN,0,1
1,"STORA ENSO , NORSKE SKOG , M-REAL , UPM-KYMMENE Credit Suisse First Boston ( CFSB ) raised the fair value for shares in four of the largest Nordic forestry groups .",ENSO,ENSO,PROPN,NNP,nsubj,XXXX,True,False,PROPN_2,...,,,,,,,"STORA ENSO , NORSKE SKOG , M-REAL , UPM-KYMMENE Credit Suisse First Boston ( CFSB ) raised the fair value for shares in four of the largest Nordic forestry groups .",FN,0,1
2,"STORA ENSO , NORSKE SKOG , M-REAL , UPM-KYMMENE Credit Suisse First Boston ( CFSB ) raised the fair value for shares in four of the largest Nordic forestry groups .",",",",",PUNCT,",",punct,",",False,False,PUNCT_1,...,,,,,,,"STORA ENSO , NORSKE SKOG , M-REAL , UPM-KYMMENE Credit Suisse First Boston ( CFSB ) raised the fair value for shares in four of the largest Nordic forestry groups .",FN,0,1
3,"STORA ENSO , NORSKE SKOG , M-REAL , UPM-KYMMENE Credit Suisse First Boston ( CFSB ) raised the fair value for shares in four of the largest Nordic forestry groups .",NORSKE,NORSKE,PROPN,NNP,compound,XXXX,True,False,PROPN_3,...,,,,,,,"STORA ENSO , NORSKE SKOG , M-REAL , UPM-KYMMENE Credit Suisse First Boston ( CFSB ) raised the fair value for shares in four of the largest Nordic forestry groups .",FN,0,1
4,"STORA ENSO , NORSKE SKOG , M-REAL , UPM-KYMMENE Credit Suisse First Boston ( CFSB ) raised the fair value for shares in four of the largest Nordic forestry groups .",SKOG,skog,NOUN,NN,appos,XXXX,True,False,NOUN_1,...,,,,,,,"STORA ENSO , NORSKE SKOG , M-REAL , UPM-KYMMENE Credit Suisse First Boston ( CFSB ) raised the fair value for shares in four of the largest Nordic forestry groups .",FN,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1687,"Operating profit excluding non-recurring items decreased to EUR 6.2 mn from EUR 16.8 mn in 2007 , representing 2.3 % of net sales .",%,%,NOUN,NN,dobj,%,False,False,NOUN_332,...,,,,,,,"Operating profit excluding non-recurring items decreased to EUR 6.2 mn from EUR 16.8 mn in 2007 , representing 2.3 % of net sales .",FN,0,1
1688,"Operating profit excluding non-recurring items decreased to EUR 6.2 mn from EUR 16.8 mn in 2007 , representing 2.3 % of net sales .",of,of,ADP,IN,prep,xx,True,True,ADP_224,...,,,,,,,"Operating profit excluding non-recurring items decreased to EUR 6.2 mn from EUR 16.8 mn in 2007 , representing 2.3 % of net sales .",FN,0,1
1689,"Operating profit excluding non-recurring items decreased to EUR 6.2 mn from EUR 16.8 mn in 2007 , representing 2.3 % of net sales .",net,net,ADJ,JJ,amod,xxx,True,False,ADJ_114,...,,,,,,,"Operating profit excluding non-recurring items decreased to EUR 6.2 mn from EUR 16.8 mn in 2007 , representing 2.3 % of net sales .",FN,0,1
1690,"Operating profit excluding non-recurring items decreased to EUR 6.2 mn from EUR 16.8 mn in 2007 , representing 2.3 % of net sales .",sales,sale,NOUN,NNS,pobj,xxxx,True,False,NOUN_333,...,,,,,,,"Operating profit excluding non-recurring items decreased to EUR 6.2 mn from EUR 16.8 mn in 2007 , representing 2.3 % of net sales .",FN,0,1
1691,"Operating profit excluding non-recurring items decreased to EUR 6.2 mn from EUR 16.8 mn in 2007 , representing 2.3 % of net sales .",.,.,PUNCT,.,punct,.,False,False,PUNCT_171,...,,,,,,,"Operating profit excluding non-recurring items decreased to EUR 6.2 mn from EUR 16.8 mn in 2007 , representing 2.3 % of net sales .",FN,0,1

In [59]:
class_pos_dfs[2]

,Sentence,Term,Lemma,POS Label,Detailed POS Label,Dependency,Shape,Is Alpha,Stop Word,Unique POS Label,...,Acc,Gen,Loc,Ins,Parat,Prep,Base Sentence,Class,Majority Vote,Sentence Label
0,"According to Gran , the company has no plans to move all production to Russia , although that is where the company is growing .",According,accord,VERB,VBG,prep,Xxxxx,True,False,VERB_1,...,,,,,,,"According to Gran , the company has no plans to move all production to Russia , although that is where the company is growing .",FP,1,0
1,"According to Gran , the company has no plans to move all production to Russia , although that is where the company is growing .",to,to,ADP,IN,prep,xx,True,True,ADP_1,...,,,,,,,"According to Gran , the company has no plans to move all production to Russia , although that is where the company is growing .",FP,1,0
2,"According to Gran , the company has no plans to move all production to Russia , although that is where the company is growing .",Gran,Gran,PROPN,NNP,pobj,Xxxx,True,False,PROPN_1,...,,,,,,,"According to Gran , the company has no plans to move all production to Russia , although that is where the company is growing .",FP,1,0
3,"According to Gran , the company has no plans to move all production to Russia , although that is where the company is growing .",",",",",PUNCT,",",punct,",",False,False,PUNCT_1,...,,,,,,,"According to Gran , the company has no plans to move all production to Russia , although that is where the company is growing .",FP,1,0
4,"According to Gran , the company has no plans to move all production to Russia , although that is where the company is growing .",the,the,DET,DT,det,xxx,True,True,DET_1,...,,,,,,,"According to Gran , the company has no plans to move all production to Russia , although that is where the company is growing .",FP,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42526,Hobby Hall 's sales decrease 26 pct due to implementing a new information system that involved changing in the principal of posting sales .,principal,principal,NOUN,NN,pobj,xxxx,True,False,NOUN_9654,...,,,,,,,Hobby Hall 's sales decrease 26 pct due to implementing a new information system that involved changing in the principal of posting sales .,FP,1,0
42527,Hobby Hall 's sales decrease 26 pct due to implementing a new information system that involved changing in the principal of posting sales .,of,of,ADP,IN,prep,xx,True,True,ADP_4469,...,,,,,,,Hobby Hall 's sales decrease 26 pct due to implementing a new information system that involved changing in the principal of posting sales .,FP,1,0
42528,Hobby Hall 's sales decrease 26 pct due to implementing a new information system that involved changing in the principal of posting sales .,posting,post,VERB,VBG,pcomp,xxxx,True,False,VERB_3921,...,,,,,,,Hobby Hall 's sales decrease 26 pct due to implementing a new information system that involved changing in the principal of posting sales .,FP,1,0
42529,Hobby Hall 's sales decrease 26 pct due to implementing a new information system that involved changing in the principal of posting sales .,sales,sale,NOUN,NNS,dobj,xxxx,True,False,NOUN_9655,...,,,,,,,Hobby Hall 's sales decrease 26 pct due to implementing a new information system that involved changing in the principal of posting sales .,FP,1,0
42530,Hobby Hall 's sales decrease 26 pct due to implementing a new information system that involved changing in the principal of posting sales .,.,.,PUNCT,.,punct,.,False,False,PUNCT_4836,...,,,,,,,Hobby Hall 's sales decrease 26 pct due to implementing a new information system that involved changing in the principal of posting sales .,FP,1,0

In [60]:
class_pos_dfs[3]

,Sentence,Term,Lemma,POS Label,Detailed POS Label,Dependency,Shape,Is Alpha,Stop Word,Unique POS Label,...,Acc,Gen,Loc,Ins,Parat,Prep,Base Sentence,Class,Majority Vote,Sentence Label
0,"The international electronic industry company Elcoteq has laid off tens of employees from its Tallinn facility ; contrary to earlier layoffs the company contracted the ranks of its office workers , the daily Postimees reported .",The,the,DET,DT,det,Xxx,True,True,DET_1,...,,,,,,,"The international electronic industry company Elcoteq has laid off tens of employees from its Tallinn facility ; contrary to earlier layoffs the company contracted the ranks of its office workers , the daily Postimees reported .",TN,0,0
1,"The international electronic industry company Elcoteq has laid off tens of employees from its Tallinn facility ; contrary to earlier layoffs the company contracted the ranks of its office workers , the daily Postimees reported .",international,international,ADJ,JJ,amod,xxxx,True,False,ADJ_1,...,,,,,,,"The international electronic industry company Elcoteq has laid off tens of employees from its Tallinn facility ; contrary to earlier layoffs the company contracted the ranks of its office workers , the daily Postimees reported .",TN,0,0
2,"The international electronic industry company Elcoteq has laid off tens of employees from its Tallinn facility ; contrary to earlier layoffs the company contracted the ranks of its office workers , the daily Postimees reported .",electronic,electronic,ADJ,JJ,amod,xxxx,True,False,ADJ_2,...,,,,,,,"The international electronic industry company Elcoteq has laid off tens of employees from its Tallinn facility ; contrary to earlier layoffs the company contracted the ranks of its office workers , the daily Postimees reported .",TN,0,0
3,"The international electronic industry company Elcoteq has laid off tens of employees from its Tallinn facility ; contrary to earlier layoffs the company contracted the ranks of its office workers , the daily Postimees reported .",industry,industry,NOUN,NN,compound,xxxx,True,False,NOUN_1,...,,,,,,,"The international electronic industry company Elcoteq has laid off tens of employees from its Tallinn facility ; contrary to earlier layoffs the company contracted the ranks of its office workers , the daily Postimees reported .",TN,0,0
4,"The international electronic industry company Elcoteq has laid off tens of employees from its Tallinn facility ; contrary to earlier layoffs the company contracted the ranks of its office workers , the daily Postimees reported .",company,company,NOUN,NN,nsubj,xxxx,True,False,NOUN_2,...,,,,,,,"The international electronic industry company Elcoteq has laid off tens of employees from its Tallinn facility ; contrary to earlier layoffs the company contracted the ranks of its office workers , the daily Postimees reported .",TN,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63180,"Sales in Finland decreased by 10.5 % in January , while sales outside Finland dropped by 17 % .",dropped,drop,VERB,VBD,advcl,xxxx,True,False,VERB_4589,...,,,,,,,"Sales in Finland decreased by 10.5 % in January , while sales outside Finland dropped by 17 % .",TN,0,0
63181,"Sales in Finland decreased by 10.5 % in January , while sales outside Finland dropped by 17 % .",by,by,ADP,IN,prep,xx,True,True,ADP_7881,...,,,,,,,"Sales in Finland decreased by 10.5 % in January , while sales outside Finland dropped by 17 % .",TN,0,0
63182,"Sales in Finland decreased by 10.5 % in January , while sales outside Finland dropped by 17 % .",17,17,NUM,CD,nummod,dd,False,False,NUM_4800,...,,,,,,,"Sales in Finland decreased by 10.5 % in January , while sales outside Finland dropped by 17 % .",TN,0,0
63183,"Sales in Finland decreased by 10.5 % in January , while sales outside Finland dropped by 17 % .",%,%,NOUN,NN,pobj,%,False,False,NOUN_13446,...,,,,,,,"Sales in Finland decreased by 10.5 % in January , while sales outside Finland dropped by 17 % .",TN,0,0
63184,"Sales in Finland decreased by 10.5 % in January , while sales outside Finland dropped by 17 % .",.,.,PUNCT,.,punct,.,False,False,PUNCT_7501,...,,,,,,,"Sales in Finland decreased by 10.5 % in January , while sales outside Finland dropped by 17 % .",TN,0,0

In [64]:
for class_pos_df in class_pos_dfs:
    class_name = class_pos_df['Class'].unique()[0]

    # Total unique sentences in class
    total_sentences = class_pos_df['Base Sentence'].nunique()

    # Sentences with predictive word (any dependency)
    filt_p_w = class_pos_df['Lemma'].str.lower().isin(p_w)
    pw_sentences = class_pos_df[filt_p_w]['Base Sentence'].nunique()
    percentage = (pw_sentences / total_sentences) * 100 if total_sentences > 0 else 0

    # Sentences with predictive word as ROOT
    filt_p_w_for_root = (
        class_pos_df['Lemma'].str.lower().isin(p_w) &
        (class_pos_df['Dependency'] == 'ROOT')
    )
    pw_root_sentences = class_pos_df[filt_p_w_for_root]['Base Sentence'].nunique()
    root_percentage = (pw_root_sentences / total_sentences) * 100 if total_sentences > 0 else 0

    print(f"CLASS: {class_name}")
    print(f"  Total Sentences: {total_sentences}")
    print(f"  Sentences with Predictive Word (Any Dependency): {pw_sentences}")
    print(f"  Percentage (Any Dependency): {percentage:.2f}%")
    print()
    print(f"  Sentences with Predictive Word (ROOT): {pw_root_sentences}")
    print(f"  Percentage (ROOT): {root_percentage:.2f}%")
    print()

CLASS: TP
  Total Sentences: 388
  Sentences with Predictive Word (Any Dependency): 119
  Percentage (Any Dependency): 30.67%

  Sentences with Predictive Word (ROOT): 89
  Percentage (ROOT): 22.94%

CLASS: FN
  Total Sentences: 70
  Sentences with Predictive Word (Any Dependency): 18
  Percentage (Any Dependency): 25.71%

  Sentences with Predictive Word (ROOT): 13
  Percentage (ROOT): 18.57%

CLASS: FP
  Total Sentences: 1849
  Sentences with Predictive Word (Any Dependency): 70
  Percentage (Any Dependency): 3.79%

  Sentences with Predictive Word (ROOT): 0
  Percentage (ROOT): 0.00%

CLASS: TN
  Total Sentences: 2531
  Sentences with Predictive Word (Any Dependency): 57
  Percentage (Any Dependency): 2.25%

  Sentences with Predictive Word (ROOT): 3
  Percentage (ROOT): 0.12%

| **Class** | **ROOT %** | **Interpretation** |
|---|---|---|
| **TP** | 22.94% | Model learns beyond lexical markers ✅ |
| **FN** | 18.57% | Model misses predictions despite explicit markers ❗ |
| **FP** | 0.00% | Model falsely triggered by non-lexical features ❗ |
| **TN** | 0.12% | Annotations correct, no lexical confusion ✅ |

---

| **Class** | **Total Sentences** | **Any Dependency Count** | **Any Dependency %** | **ROOT Count** | **ROOT %** |
|---|---|---|---|---|---|
| **TP** | 388 | 119 | 30.67% | 89 | 22.94% |
| **FN** | 70 | 18 | 25.71% | 13 | 18.57% |
| **FP** | 1849 | 70 | 3.79% | 0 | 0.00% |
| **TN** | 2531 | 57 | 2.25% | 3 | 0.12% |