> Code moved to `agreement.py`

> Run after ML and/or LLMs both classify on test set.
---

## Evaluation + Metrics

- PAPER: [Collective Reasoning Among LLMs: A Framework for Answer Validation Without Ground Truth](https://arxiv.org/pdf/2502.20758) by Davoudi et al., 2025

In [1]:
import os
import re
import sys
import warnings
import statsmodels

import numpy as np
import pandas as pd

from tqdm import tqdm
from statistics import mean
from json import loads, dumps

from statsmodels.stats.inter_rater import cohens_kappa, fleiss_kappa

# Get the current working directory of the notebook
notebook_dir = os.getcwd()
# Add the parent directory to the system path
sys.path.append(os.path.join(notebook_dir, '../'))

# import log_files
from metrics import EvaluationMetric
from data_visualizing import DataVisualizing
from data_processing import DataProcessing

In [2]:
get_metrics = EvaluationMetric()
get_metrics

## Load Data

In [3]:
base_data_path = DataProcessing.load_base_data_path(notebook_dir)
combine_data_path = os.path.join(base_data_path, 
                                 'classification_results',
                                 'synthetic-fpb-chronicle2050-yt-news-timebank-mf_climate_2026-04-25'
)
dir_files = os.listdir(combine_data_path)
dir_files

['seed3', 'averaged', 'seed7', 'seed33']

In [4]:
def load_seed_data(dataset_folder_path, dir_files):
    """
    Walk through all seed folders and load checkpoint, metrics, and test set files.

    Parameters
    ----------
    dataset_folder_path : str
        Base path to the experiment folder containing seed subfolders.
    dir_files : list of str
        List of folder/file names inside dataset_folder_path.

    Returns
    -------
    seed_ml_classifiers_map : dict
        {seed_value: df} one DataFrame per seed for ml_classifiers_in_domain.csv
    seed_llm_classifiers_map : dict
        {seed_value: df} one DataFrame per seed for llm_classifiers_in_domain.csv
    x_test_dfs : list of pd.DataFrame
        All x_y_test_set DataFrames per seed.
    """
    x_test_dfs = []
    seed_ml_classifiers_map = {}
    seed_llm_classifiers_map = {}

    for dir_file in sorted(dir_files):
        if "seed" not in dir_file:
            continue

        seed_path = os.path.join(dataset_folder_path, dir_file, 'in_domain')
        seed_path_files = os.listdir(seed_path)
        seed_value = int(re.search(r'\d+', dir_file).group())

        for seed_path_file in seed_path_files:

            if "ml_classifiers_in_domain" in seed_path_file:
                print(f"  ✓ Loading ML classifiers: {seed_path_file}")
                ml_path = os.path.join(seed_path, seed_path_file)
                df = DataProcessing.load_from_file(path=ml_path)
                seed_ml_classifiers_map[seed_value] = df

            elif "llm_classifiers_in_domain" in seed_path_file:
                print(f"  ✓ Loading LLM classifiers: {seed_path_file}")
                llm_path = os.path.join(seed_path, seed_path_file)
                df = DataProcessing.load_from_file(path=llm_path)
                seed_llm_classifiers_map[seed_value] = df

            if "x_y_test_set" in seed_path_file:
                print(f"  ✓ Loading test set: {seed_path_file}")
                x_test_path = os.path.join(seed_path, 'x_y_test_set.csv')
                x_test_df = DataProcessing.load_from_file(x_test_path)
                x_test_dfs.append(x_test_df)

    return seed_ml_classifiers_map, seed_llm_classifiers_map, x_test_dfs

In [5]:
seed_ml_classifiers_map, seed_llm_classifiers_map, x_test_dfs = load_seed_data(combine_data_path, dir_files)

  ✓ Loading test set: x_y_test_set.csv
  ✓ Loading LLM classifiers: llm_classifiers_in_domain.csv
  ✓ Loading ML classifiers: ml_classifiers_in_domain.csv
  ✓ Loading test set: x_y_test_set.csv
  ✓ Loading LLM classifiers: llm_classifiers_in_domain.csv
  ✓ Loading ML classifiers: ml_classifiers_in_domain.csv
  ✓ Loading test set: x_y_test_set.csv
  ✓ Loading LLM classifiers: llm_classifiers_in_domain.csv
  ✓ Loading ML classifiers: ml_classifiers_in_domain.csv

In [6]:
seed_ml_classifiers_map.keys()

dict_keys([3, 33, 7])

In [7]:
seed_ml_classifiers_map[3]

,Base Sentence,Ground Truth,Dataset Name,Base Sentence Embedding,perceptron,sgd_classifier,logistic_regression,ridge_classifier,decision_tree_classifier,random_forest_classifier,gradient_boosting_classifier,support_vector_machine_classifier,x_gradient_boosting_classifier
0,Finnish security and privacy software solution...,0,financial_phrasebank,[-1.35584414e-01 1.98702499e-01 1.52258351e-...,0,0,0,0,0,0,0,0,0
1,Gusty winds and rainfall will affect coastal l...,1,mf_climate,[ 8.05725157e-02 1.43171415e-01 -1.39406882e-...,1,1,1,1,1,1,1,1,1
2,"Its stock, which was as high as $18.75 a share...",0,timebank,[-1.59311950e-01 2.41325110e-01 -2.21736506e-...,0,0,0,0,0,0,0,0,0
3,Light rain and potential light snow in the nor...,1,mf_climate,[-6.28760681e-02 2.35710710e-01 -1.75071564e-...,1,1,1,1,1,1,1,1,1
4,"Active weather will persist, supported by high...",1,mf_climate,[-1.09333172e-01 1.60520568e-01 -1.75141625e-...,1,1,1,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7659,If the government succeeds in seizing Mr. Anta...,1,timebank,[-5.71714418e-06 1.56536445e-01 -1.28813758e-...,0,0,0,0,0,0,0,0,0
7660,A wet pattern with warmer temperatures is expe...,1,mf_climate,[-2.03686883e-03 1.31318465e-01 -1.05818056e-...,1,1,1,1,1,1,1,1,1
7661,"Heavy rain expected in the coastal Northeast, ...",1,mf_climate,[ 7.82528818e-02 1.88763067e-01 -8.92992094e-...,1,1,1,1,1,1,1,1,1
7662,A northern stream system will move through sou...,1,mf_climate,[-6.38406724e-02 1.94901422e-01 -2.60958578e-...,1,1,1,1,1,1,1,1,1
7663,Monsoonal moisture will contribute to thunders...,1,mf_climate,[-6.20057993e-02 1.45234957e-01 1.04440516e-...,1,1,1,1,1,1,1,1,1

In [16]:
col_names = seed_ml_classifiers_map[3].iloc[:, 4:].columns.to_list()
col_names

['perceptron',
 'sgd_classifier',
 'logistic_regression',
 'ridge_classifier',
 'decision_tree_classifier',
 'random_forest_classifier',
 'gradient_boosting_classifier',
 'support_vector_machine_classifier',
 'x_gradient_boosting_classifier']

## Fleiss Kappa

+ per model type
+ per seed

In [22]:
EvaluationMetric.get_fleiss_kappa(seed_ml_classifiers_map[3], col_names)[2]

,Base Sentence,Ground Truth,Dataset Name,Base Sentence Embedding,perceptron,sgd_classifier,logistic_regression,ridge_classifier,decision_tree_classifier,random_forest_classifier,gradient_boosting_classifier,support_vector_machine_classifier,x_gradient_boosting_classifier,Per Row Agreement,Per Row Entropy
0,Finnish security and privacy software solution...,0,financial_phrasebank,[-1.35584414e-01 1.98702499e-01 1.52258351e-...,0,0,0,0,0,0,0,0,0,1.0,-0.0
1,Gusty winds and rainfall will affect coastal l...,1,mf_climate,[ 8.05725157e-02 1.43171415e-01 -1.39406882e-...,1,1,1,1,1,1,1,1,1,1.0,-0.0
2,"Its stock, which was as high as $18.75 a share...",0,timebank,[-1.59311950e-01 2.41325110e-01 -2.21736506e-...,0,0,0,0,0,0,0,0,0,1.0,-0.0
3,Light rain and potential light snow in the nor...,1,mf_climate,[-6.28760681e-02 2.35710710e-01 -1.75071564e-...,1,1,1,1,1,1,1,1,1,1.0,-0.0
4,"Active weather will persist, supported by high...",1,mf_climate,[-1.09333172e-01 1.60520568e-01 -1.75141625e-...,1,1,1,1,1,1,1,1,1,1.0,-0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7659,If the government succeeds in seizing Mr. Anta...,1,timebank,[-5.71714418e-06 1.56536445e-01 -1.28813758e-...,0,0,0,0,0,0,0,0,0,1.0,-0.0
7660,A wet pattern with warmer temperatures is expe...,1,mf_climate,[-2.03686883e-03 1.31318465e-01 -1.05818056e-...,1,1,1,1,1,1,1,1,1,1.0,-0.0
7661,"Heavy rain expected in the coastal Northeast, ...",1,mf_climate,[ 7.82528818e-02 1.88763067e-01 -8.92992094e-...,1,1,1,1,1,1,1,1,1,1.0,-0.0
7662,A northern stream system will move through sou...,1,mf_climate,[-6.38406724e-02 1.94901422e-01 -2.60958578e-...,1,1,1,1,1,1,1,1,1,1.0,-0.0
7663,Monsoonal moisture will contribute to thunders...,1,mf_climate,[-6.20057993e-02 1.45234957e-01 1.04440516e-...,1,1,1,1,1,1,1,1,1,1.0,-0.0

In [ ]:
DataPlotting.plot_class_distribution(results_df, 'Dataset', class_names=['chronicle2050', 'financial phrasebank'])

## Performance Metrics

+ [x] ML only
+ [x] LLM only

In [ ]:
model_names = results_df.columns.to_list()[3:]
model_names

## Agreement Metrics

1. Cohen's Kappa: Intra (within each model category) on the predicted label
2. Majority Vote: Intra (within each model category) on the predicted label
3. Majority Vote: Inter
4. Cohen's Kappa: Inter (across each model category) on the majority vote labels

### Majority Vote

+ Need an odd number of columns for the `.mode(axis=1)` to work.

---

+ [x] ML only
+ [x] LLM only
+ [x] Combined

In [ ]:
majority_vote = results_df.loc[:, model_names[:3]].mode(axis=1)
results_df['Majority Vote'] = majority_vote
results_df

In [ ]:
filt_mv_predictions = (results_df['Majority Vote'] == 1)
predictions_df = results_df[filt_mv_predictions]
predictions_df

In [ ]:
predictions_df['Dataset'].value_counts()

In [ ]:
DataPlotting.plot_class_distribution(predictions_df, 'Dataset', class_names=['chronicle2050', 'financial phrasebank'])

### Cohen's Kappa

- How realiable are the raters?
    - Higher, then they tend to agree
    - Lower, the they tend to disagree
- Does NOT state if the raters are correct as in raters can say one thing and real value may be another. This deals with the validity.

---

1. Intra (within each model category) on the predicted labels
    - [x] ML: ML_i vs ML_j
        - ML_1 vs ML_2
        - ML_1 vs ML_3
        - ML_2 vs ML_3

In [ ]:
cohen_all_df = get_metrics.calculate_pairwise_cohens_kappa(results_df, model_names, 'ML', print_bool = False)
cohen_all_df.sort_values("Cohen's Kappa", ascending=False, inplace=True)
cohen_all_df.rename(columns={"Cohen's Kappa": "Cohen's Kappa (All)"}, inplace=True)
cohen_all_df

In [ ]:
cohen_predictions_df = get_metrics.calculate_pairwise_cohens_kappa(predictions_df, model_names, 'ML', print_bool = False)
cohen_predictions_df.sort_values("Cohen's Kappa", ascending=False, inplace=True)
cohen_predictions_df.rename(columns={"Cohen's Kappa": "Cohen's Kappa (Predictions)"}, inplace=True)
cohen_predictions_df

In [ ]:
cohen_df = DataProcessing.concat_dfs([cohen_all_df, cohen_predictions_df], axis=1, ignore_index=False)
cohen_df

### Fleiss’ Kappa

- How realiable are the raters?
    - Higher, then they tend to agree
    - Lower, the they tend to disagree
- Does NOT state if the raters are correct as in raters can say one thing and real value may be another. This deals with the validity.

---

1. Intra Model: Predicted Label 
    - [ ] 1. ML: ML_1 vs ML_2 vs ... vs ML_N, where N is odd

In [ ]:
fleiss = {}
fleiss_all_df = get_metrics.get_fleiss_kappa(results_df, model_names)
print("\nFleiss's Kappa (All):", round(fleiss_all_df, 2))
fleiss["Fleiss's Kappa (All)"] = float(round(fleiss_all_df, 2))

fleiss_predictions_df = get_metrics.get_fleiss_kappa(predictions_df, model_names)
print("\nFleiss's Kappa (Predictions Only):", round(fleiss_predictions_df, 2))
fleiss["Fleiss's Kappa (Predictions Only)"] = float(round(fleiss_predictions_df, 2))

fleiss_df = pd.DataFrame([fleiss])
fleiss_df

In [ ]:
fleiss_df = pd.DataFrame(fleiss)
fleiss_df

##  Reliability Metric

##  Confidence Intervals via Bootstrap

> ML > LLM > ML x LLM, why? Due to randomness of LLM?

In [ ]:
import numpy as np
import pandas as pd
from itertools import combinations
from collections import Counter

def pairwise_counts(y1, y2):
    # returns a, b, c, d = n11, n10, n01, n00
    y1 = np.asarray(y1).astype(int)
    y2 = np.asarray(y2).astype(int)
    a = np.sum((y1==1) & (y2==1))
    b = np.sum((y1==1) & (y2==0))
    c = np.sum((y1==0) & (y2==1))
    d = np.sum((y1==0) & (y2==0))
    return a, b, c, d

def kappa_from_counts(a,b,c,d):
    n = a+b+c+d
    po = (a+d)/n if n>0 else np.nan
    p1_1 = (a+b)/n
    p1_2 = (a+c)/n
    p0_1 = 1-p1_1
    p0_2 = 1-p1_2
    pe = p1_1*p1_2 + p0_1*p0_2
    if pe == 1:
        return np.nan, po, pe
    k = (po - pe) / (1 - pe)
    return k, po, pe

def positive_negative_agreement(a,b,c,d):
    pos_agree = (2*a) / (2*a + b + c) if (2*a + b + c) > 0 else np.nan
    neg_agree = (2*d) / (2*d + b + c) if (2*d + b + c) > 0 else np.nan
    return pos_agree, neg_agree

def pabak(po):
    # Prevalence-adjusted, bias-adjusted kappa (for binary, two-rater)
    return 2*po - 1

def gwets_ac1(y1, y2):
    # Simple AC1 for binary
    y1 = np.asarray(y1).astype(int)
    y2 = np.asarray(y2).astype(int)
    n = len(y1)
    po = np.mean(y1 == y2)
    pbar = 0.5*(np.mean(y1==1) + np.mean(y2==1))
    pe = 2*pbar*(1-pbar)
    if pe == 1:
        return np.nan, po, pe
    ac1 = (po - pe) / (1 - pe)
    return ac1, po, pe

def leave_two_out_majority(df, model_cols, exclude):
    cols = [c for c in model_cols if c not in exclude]
    # majority vote (ties break to 0)
    votes = df[cols].sum(axis=1)
    return (votes > (len(cols)/2)).astype(int)

def analyze(preds, model_cols, gold_col=None, boot_iters=0, random_state=0):
    rng = np.random.default_rng(random_state)
    results = []
    # All-items analysis
    for m1, m2 in combinations(model_cols, 2):
        a,b,c,d = pairwise_counts(preds[m1], preds[m2])
        k, po, pe = kappa_from_counts(a,b,c,d)
        ac1, po2, pe2 = gwets_ac1(preds[m1], preds[m2])
        pa, na = positive_negative_agreement(a,b,c,d)
        row = dict(scope='All', m1=m1, m2=m2, n=a+b+c+d, prevalence_m1=preds[m1].mean(),
                   prevalence_m2=preds[m2].mean(), kappa=k, po=po, pe=pe,
                   ac1=ac1, pabak=pabak(po), pos_agree=pa, neg_agree=na)
        results.append(row)

        # Leave-two-out Pred+ / Pred-
        pred_plus_mask  = leave_two_out_majority(preds, model_cols, exclude=[m1, m2]) == 1
        pred_minus_mask = leave_two_out_majority(preds, model_cols, exclude=[m1, m2]) == 0
        for scope, mask in [('Pred+', pred_plus_mask), ('Pred-', pred_minus_mask)]:
            if mask.sum() == 0: 
                continue
            a,b,c,d = pairwise_counts(preds.loc[mask, m1], preds.loc[mask, m2])
            k, po, pe = kappa_from_counts(a,b,c,d)
            ac1, po2, pe2 = gwets_ac1(preds.loc[mask, m1], preds.loc[mask, m2])
            pa, na = positive_negative_agreement(a,b,c,d)
            results.append(dict(scope=scope, m1=m1, m2=m2, n=mask.sum(),
                                prevalence_m1=preds.loc[mask, m1].mean(),
                                prevalence_m2=preds.loc[mask, m2].mean(),
                                kappa=k, po=po, pe=pe, ac1=ac1, pabak=pabak(po),
                                pos_agree=pa, neg_agree=na))
    return pd.DataFrame(results)

In [ ]:

df_results = analyze(
    preds=results_df,
    model_cols=model_names,
)
df_results