# Property Extraction

> y vs LLM

In [1]:
import os
import sys

# Get the current working directory of the notebook
notebook_dir = os.getcwd()
# print(notebook_dir)
# Add the parent directory to the system path
sys.path.append(os.path.join(notebook_dir, '../'))

from metrics import EvaluationMetric
from data_processing import DataProcessing
from feature_extraction import SpacyFeatureExtraction

In [2]:
base_data_path = DataProcessing.load_base_data_path(notebook_dir)
data_path = os.path.join(base_data_path, 'extract_prediction_properties/future-chronicle2050_fpb_synthethic-v1/openai/gpt-oss-120b/results.csv')
df = DataProcessing.load_from_file(data_path)
df

,Sentence,Raw Response,Model Name,No Property,Source,Target,Date,Outcome,Dataset Source
0,"By January 1st, 2037, Tesla will have been the...","{0: [""By"", ""will"", ""have"", ""been"", ""and"", ""thi...",openai/gpt-oss-120b,"By, will, have, been, and, this, will, be, usa...",Tesla,Tesla,"January 1st, 2037",first company with 1 million vehicles that are...,future-chronicle2050_fpb_synthethic-v1
1,An annual average temperature anomaly value ab...,"{\n ""0"": [""An"", ""above"", ""the"", ""will"", ""be"",...",openai/gpt-oss-120b,"An, above, the, will, be, published, in, the, ...",NaN,annual average temperature anomaly value,"2037, 2038",2.0C or higher,future-chronicle2050_fpb_synthethic-v1
2,Private Nonfarm business productivity growth w...,"{0: [""will"", ""from"", ""to""], 1: [], 2: [""Privat...",openai/gpt-oss-120b,"will, from, to",NaN,Private Nonfarm business productivity growth,"the first quarter (Q1) of 2020, the last quart...",average over 1.8 percent per year,future-chronicle2050_fpb_synthethic-v1
3,No Republican will be President of the USA bef...,"{0: [""will"", ""be"", ""before""], 1: [], 2: [""Repu...",openai/gpt-oss-120b,"will, be, before",NaN,Republican,"December 30, 2039","No, President of the USA",future-chronicle2050_fpb_synthethic-v1
4,The market capitalization of Berkshire Hathawa...,"{0: [""The"", ""of"", ""will"", ""be"", ""on""], 1: [], ...",openai/gpt-oss-120b,"The, of, will, be, on",NaN,"Berkshire Hathaway, Tesla",Warren Buffett's 100th birthday,"market capitalization, greater than",future-chronicle2050_fpb_synthethic-v1
...,...,...,...,...,...,...,...,...,...
95,I predict by the end of the 2020’s and into th...,"{\n ""0"": [""predict"", ""will"", ""be"", ""fought"", ...",openai/gpt-oss-120b,"predict, will, be, fought, over, the, rarest, ...",I,war,by the end of the 2020’s and into the 2030’s,Water,future-chronicle2050_fpb_synthethic-v1
96,"By the end of 2036, humans sent by SpaceX will...","{0: [""sent"", ""by"", ""will"", ""have""], 1: [""Space...",openai/gpt-oss-120b,"sent, by, will, have",SpaceX,humans,By the end of 2036,landed and walked on the surface of Mars,future-chronicle2050_fpb_synthethic-v1
97,"Within 10 years from now, free markets for the...","{0: [], 1: [], 2: [""stablecoin TerraUSD (UST)""...",openai/gpt-oss-120b,NaN,NaN,"stablecoin TerraUSD (UST), UST",Within 10 years from now,"free markets will no longer exist, more than 1...",future-chronicle2050_fpb_synthethic-v1
98,"By the year 2030, there will be successful re-...","{0: [""By"", ""the"", ""there"", ""will"", ""be"", ""of""]...",openai/gpt-oss-120b,"By, the, there, will, be, of",NaN,1990s 'classic' movies,year 2030,successful re-produced or remastered versions ...,future-chronicle2050_fpb_synthethic-v1
99,A manned mission to Mars will be underway or w...,"{0: [""A"", ""will be"", ""or"", ""will have"", ""posts...",openai/gpt-oss-120b,"A, will be, or, will have, posts, Prediction 1000",Long Bets,manned mission to Mars,by the time,"underway, actually arrived there",future-chronicle2050_fpb_synthethic-v1

In [3]:
y_df = df.copy()
y_hat_df = df.copy()

In [4]:
y_spacy_fe = SpacyFeatureExtraction(y_df, 'Source')
embed_source_y_df = y_spacy_fe.sentence_embeddings_extraction(attach_to_df=True)

y_hat_spacy_fe = SpacyFeatureExtraction(y_hat_df, 'Source')
embed_source_y_hat_df = y_hat_spacy_fe.sentence_embeddings_extraction(attach_to_df=True)

100%|██████████| 100/100 [00:00<00:00, 1780.13it/s]
100%|██████████| 100/100 [00:00<00:00, 1963.18it/s]

In [5]:
embed_source_y_df

,Sentence,Raw Response,Model Name,No Property,Source,Target,Date,Outcome,Dataset Source,Source Embedding
0,"By January 1st, 2037, Tesla will have been the...","{0: [""By"", ""will"", ""have"", ""been"", ""and"", ""thi...",openai/gpt-oss-120b,"By, will, have, been, and, this, will, be, usa...",Tesla,Tesla,"January 1st, 2037",first company with 1 million vehicles that are...,future-chronicle2050_fpb_synthethic-v1,"[0.029089, 0.71794, 0.31932, 0.39034, -0.74537..."
1,An annual average temperature anomaly value ab...,"{\n ""0"": [""An"", ""above"", ""the"", ""will"", ""be"",...",openai/gpt-oss-120b,"An, above, the, will, be, published, in, the, ...",NaN,annual average temperature anomaly value,"2037, 2038",2.0C or higher,future-chronicle2050_fpb_synthethic-v1,None
2,Private Nonfarm business productivity growth w...,"{0: [""will"", ""from"", ""to""], 1: [], 2: [""Privat...",openai/gpt-oss-120b,"will, from, to",NaN,Private Nonfarm business productivity growth,"the first quarter (Q1) of 2020, the last quart...",average over 1.8 percent per year,future-chronicle2050_fpb_synthethic-v1,None
3,No Republican will be President of the USA bef...,"{0: [""will"", ""be"", ""before""], 1: [], 2: [""Repu...",openai/gpt-oss-120b,"will, be, before",NaN,Republican,"December 30, 2039","No, President of the USA",future-chronicle2050_fpb_synthethic-v1,None
4,The market capitalization of Berkshire Hathawa...,"{0: [""The"", ""of"", ""will"", ""be"", ""on""], 1: [], ...",openai/gpt-oss-120b,"The, of, will, be, on",NaN,"Berkshire Hathaway, Tesla",Warren Buffett's 100th birthday,"market capitalization, greater than",future-chronicle2050_fpb_synthethic-v1,None
...,...,...,...,...,...,...,...,...,...,...
95,I predict by the end of the 2020’s and into th...,"{\n ""0"": [""predict"", ""will"", ""be"", ""fought"", ...",openai/gpt-oss-120b,"predict, will, be, fought, over, the, rarest, ...",I,war,by the end of the 2020’s and into the 2030’s,Water,future-chronicle2050_fpb_synthethic-v1,"[0.18733, 0.40595, -0.51174, -0.55482, 0.03971..."
96,"By the end of 2036, humans sent by SpaceX will...","{0: [""sent"", ""by"", ""will"", ""have""], 1: [""Space...",openai/gpt-oss-120b,"sent, by, will, have",SpaceX,humans,By the end of 2036,landed and walked on the surface of Mars,future-chronicle2050_fpb_synthethic-v1,"[-0.039272, -0.13725, 0.060076, 0.18352, -0.09..."
97,"Within 10 years from now, free markets for the...","{0: [], 1: [], 2: [""stablecoin TerraUSD (UST)""...",openai/gpt-oss-120b,NaN,NaN,"stablecoin TerraUSD (UST), UST",Within 10 years from now,"free markets will no longer exist, more than 1...",future-chronicle2050_fpb_synthethic-v1,None
98,"By the year 2030, there will be successful re-...","{0: [""By"", ""the"", ""there"", ""will"", ""be"", ""of""]...",openai/gpt-oss-120b,"By, the, there, will, be, of",NaN,1990s 'classic' movies,year 2030,successful re-produced or remastered versions ...,future-chronicle2050_fpb_synthethic-v1,None
99,A manned mission to Mars will be underway or w...,"{0: [""A"", ""will be"", ""or"", ""will have"", ""posts...",openai/gpt-oss-120b,"A, will be, or, will have, posts, Prediction 1000",Long Bets,manned mission to Mars,by the time,"underway, actually arrived there",future-chronicle2050_fpb_synthethic-v1,"[-0.12302001, 0.20293, -0.2046625, -0.2134915,..."

In [6]:
embed_source_y_hat_df

,Sentence,Raw Response,Model Name,No Property,Source,Target,Date,Outcome,Dataset Source,Source Embedding
0,"By January 1st, 2037, Tesla will have been the...","{0: [""By"", ""will"", ""have"", ""been"", ""and"", ""thi...",openai/gpt-oss-120b,"By, will, have, been, and, this, will, be, usa...",Tesla,Tesla,"January 1st, 2037",first company with 1 million vehicles that are...,future-chronicle2050_fpb_synthethic-v1,"[0.029089, 0.71794, 0.31932, 0.39034, -0.74537..."
1,An annual average temperature anomaly value ab...,"{\n ""0"": [""An"", ""above"", ""the"", ""will"", ""be"",...",openai/gpt-oss-120b,"An, above, the, will, be, published, in, the, ...",NaN,annual average temperature anomaly value,"2037, 2038",2.0C or higher,future-chronicle2050_fpb_synthethic-v1,None
2,Private Nonfarm business productivity growth w...,"{0: [""will"", ""from"", ""to""], 1: [], 2: [""Privat...",openai/gpt-oss-120b,"will, from, to",NaN,Private Nonfarm business productivity growth,"the first quarter (Q1) of 2020, the last quart...",average over 1.8 percent per year,future-chronicle2050_fpb_synthethic-v1,None
3,No Republican will be President of the USA bef...,"{0: [""will"", ""be"", ""before""], 1: [], 2: [""Repu...",openai/gpt-oss-120b,"will, be, before",NaN,Republican,"December 30, 2039","No, President of the USA",future-chronicle2050_fpb_synthethic-v1,None
4,The market capitalization of Berkshire Hathawa...,"{0: [""The"", ""of"", ""will"", ""be"", ""on""], 1: [], ...",openai/gpt-oss-120b,"The, of, will, be, on",NaN,"Berkshire Hathaway, Tesla",Warren Buffett's 100th birthday,"market capitalization, greater than",future-chronicle2050_fpb_synthethic-v1,None
...,...,...,...,...,...,...,...,...,...,...
95,I predict by the end of the 2020’s and into th...,"{\n ""0"": [""predict"", ""will"", ""be"", ""fought"", ...",openai/gpt-oss-120b,"predict, will, be, fought, over, the, rarest, ...",I,war,by the end of the 2020’s and into the 2030’s,Water,future-chronicle2050_fpb_synthethic-v1,"[0.18733, 0.40595, -0.51174, -0.55482, 0.03971..."
96,"By the end of 2036, humans sent by SpaceX will...","{0: [""sent"", ""by"", ""will"", ""have""], 1: [""Space...",openai/gpt-oss-120b,"sent, by, will, have",SpaceX,humans,By the end of 2036,landed and walked on the surface of Mars,future-chronicle2050_fpb_synthethic-v1,"[-0.039272, -0.13725, 0.060076, 0.18352, -0.09..."
97,"Within 10 years from now, free markets for the...","{0: [], 1: [], 2: [""stablecoin TerraUSD (UST)""...",openai/gpt-oss-120b,NaN,NaN,"stablecoin TerraUSD (UST), UST",Within 10 years from now,"free markets will no longer exist, more than 1...",future-chronicle2050_fpb_synthethic-v1,None
98,"By the year 2030, there will be successful re-...","{0: [""By"", ""the"", ""there"", ""will"", ""be"", ""of""]...",openai/gpt-oss-120b,"By, the, there, will, be, of",NaN,1990s 'classic' movies,year 2030,successful re-produced or remastered versions ...,future-chronicle2050_fpb_synthethic-v1,None
99,A manned mission to Mars will be underway or w...,"{0: [""A"", ""will be"", ""or"", ""will have"", ""posts...",openai/gpt-oss-120b,"A, will be, or, will have, posts, Prediction 1000",Long Bets,manned mission to Mars,by the time,"underway, actually arrived there",future-chronicle2050_fpb_synthethic-v1,"[-0.12302001, 0.20293, -0.2046625, -0.2134915,..."

In [7]:
import numpy as np
np.testing.assert_equal(len(embed_source_y_df), len(embed_source_y_hat_df))

In [12]:
len_dfs = len(embed_source_y_df)

#          y, y_hat
tps = [] # 1, 1 =>
fns = [] # 1, 0 => 
tns = [] # 0, 0 =>
fps = [] # 0, 1 =>
misc = []

for idx in range(len_dfs):
    # print(idx)
    y_embed = embed_source_y_df['Source Embedding'][idx]
    y_hat_embed = embed_source_y_hat_df['Source Embedding'][idx]

    if idx < 3:
        print(f"{type(y_embed)} vs {type(y_hat_embed)}")
    
    if y_embed is None and y_hat_embed is None:
        tns.append(idx)

    if y_embed is not None and y_hat_embed is None:
        fns.append(idx)

    if y_embed is None and y_hat_embed is not None:
        fps.append(idx)

    if y_embed is not None and y_hat_embed is not None:
        x_embeddings_reshaped = y_embed[idx].reshape(1, -1)
        y_embeddings_reshaped = y_hat_embed[idx].reshape(1, -1)
        cs = EvaluationMetric.get_cosine_similarity(x_embeddings_reshaped, y_embeddings_reshaped, per_row=False)
        if idx < 3:
            # print(f"{y_embed} vs {y_hat_embed} => {cs}")
            print(f"CS: {cs}")
            if cs == 1:
                tps.append(idx)
            else:
                misc.append(idx)

<class 'numpy.ndarray'> vs <class 'numpy.ndarray'>
CS: [[1.]]
<class 'NoneType'> vs <class 'NoneType'>
<class 'NoneType'> vs <class 'NoneType'>

In [16]:
len(tps), len(fns), len(tns), len(fps), len(misc)

(1, 0, 71, 0, 0)

In [14]:
tns

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 13,
 14,
 15,
 16,
 20,
 21,
 22,
 23,
 24,
 25,
 27,
 28,
 29,
 31,
 32,
 33,
 34,
 35,
 37,
 39,
 40,
 42,
 43,
 44,
 45,
 46,
 47,
 49,
 51,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 69,
 71,
 73,
 74,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 89,
 91,
 93,
 94,
 97,
 98]