In [9]:
import os
import sys

import numpy as np
import pandas as pd

from langchain_core.prompts import PipelinePromptTemplate, PromptTemplate

# Get the current working directory of the notebook
notebook_dir = os.getcwd()
# Add the parent directory to the system path
sys.path.append(os.path.join(notebook_dir, '../prediction_classification_experiments-v2/'))

import average_classification_results as acr

In [10]:
results_dir = os.path.join(notebook_dir, "../data/classification_results/")
results_dir

'/Users/detraviousjamaribrinkley/Documents/Development/research_labs/uf_ds/predictions/notebook_experiments/../data/classification_results/'

In [11]:
experiments = acr.collect_results(results_dir)
type(experiments)

============================================================
COLLECTING RESULTS
============================================================

Found 5 experiment directories

Processing: combined-synthetic-fin_phrase_bank-v5_2026-02-21
  Found unique seeds: [42]
    ✗ Missing: seed42/metrics_summary.csv

Processing: fpb-maya-binary-imbalanced-96d-v1_2026-02-17
  Found unique seeds: [7, 33, 40]
    ✓ Loaded: seed7/metrics_summary.csv
    ✓ Loaded: seed33/metrics_summary.csv
    ✓ Loaded: seed40/metrics_summary.csv

Processing: fpb-maya-binary-imbalanced-96d-v1_2026-02-21
  Found unique seeds: [42]
    ✓ Loaded: seed42/metrics_summary.csv

Processing: fpb-maya-binary-oversampled-96d-v1_2026-02-17
  Found unique seeds: [7, 33, 40]
    ✓ Loaded: seed7/metrics_summary.csv
    ✓ Loaded: seed33/metrics_summary.csv
    ✓ Loaded: seed40/metrics_summary.csv

Processing: fpb-maya-binary-undersampled-96d-v1_2026-02-17
  Found unique seeds: [7, 33, 40]
    ✓ Loaded: seed7/metrics_summary.csv
    ✓ Loaded: seed33/metrics_summary.csv
    ✓ Loaded: seed40/metrics_summary.csv

dict

In [12]:
combined_df = acr.save_averaged_results(results_dir, experiments)
type(combined_df), combined_df

==================================================
Averaging: fpb-maya-binary-imbalanced-96d-v1_2026-02-17
==================================================
Seeds used: 3
Seed details: ['seed7', 'seed33', 'seed40']

Mean metrics:
                                accuracy  precision_class_0  \
model
decision_tree_classifier        0.840893           0.921532
gradient_boosting_classifier    0.913402           0.921147
logistic_regression             0.916838           0.924724
perceptron                      0.870790           0.954395
random_forest_classifier        0.908247           0.909375
ridge_classifier                0.918900           0.922776
sgd_classifier                  0.921306           0.929101
x_gradient_boosting_classifier  0.917182           0.925361
mean_row                        0.900945           0.926051

                                precision_class_1  recall_class_0  \
model
decision_tree_classifier                 0.222895        0.900911
gradient_boosting_classifier             0.645062        0.988990
logistic_regression                      0.682696        0.988610
perceptron                               0.500757        0.903189
random_forest_classifier                 0.750000        0.998102
ridge_classifier                         0.774573        0.993546
sgd_classifier                           0.702742        0.988610
x_gradient_boosting_classifier           0.676199        0.988231
mean_row                                 0.619365        0.968774

                                recall_class_1  f1_class_0  f1_class_1  \
model
decision_tree_classifier              0.268116    0.911088    0.243129
gradient_boosting_classifier          0.192029    0.953864    0.295938
logistic_regression                   0.231884    0.955597    0.345234
perceptron                            0.561594    0.924080    0.456605
random_forest_classifier              0.050725    0.951674    0.094638
ridge_classifier                      0.206522    0.956854    0.326028
sgd_classifier                        0.278986    0.957903    0.392763
x_gradient_boosting_classifier        0.239130    0.955759    0.352467
mean_row                              0.253623    0.945852    0.313350

                                     auc
model
decision_tree_classifier        0.584514
gradient_boosting_classifier    0.590510
logistic_regression             0.610247
perceptron                      0.732392
random_forest_classifier        0.524413
ridge_classifier                0.600034
sgd_classifier                  0.633798
x_gradient_boosting_classifier  0.613681
mean_row                        0.611198

Std metrics:
                                accuracy  precision_class_0  \
model
decision_tree_classifier        0.014592           0.004568
gradient_boosting_classifier    0.005740           0.003196
logistic_regression             0.003903           0.003145
perceptron                      0.080070           0.027326
random_forest_classifier        0.003717           0.002069
ridge_classifier                0.006628           0.002893
sgd_classifier                  0.009579           0.010693
x_gradient_boosting_classifier  0.005085           0.004536
std_row                         0.026070           0.008523

                                precision_class_1  recall_class_0  \
model
decision_tree_classifier                 0.046093        0.012936
gradient_boosting_classifier             0.098137        0.002866
logistic_regression                      0.064723        0.003013
perceptron                               0.193959        0.118106
random_forest_classifier                 0.250000        0.002371
ridge_classifier                         0.139426        0.004312
sgd_classifier                           0.074521        0.002278
x_gradient_boosting_classifier           0.060340        0.001315
std_row                                  0.072935        0.040455

                                recall_class_1  f1_class_0  f1_class_1  \
model
decision_tree_classifier              0.038173    0.008552    0.042363
gradient_boosting_classifier          0.033207    0.003045    0.049744
logistic_regression                   0.034941    0.002066    0.041594
perceptron                            0.296748    0.053396    0.068143
random_forest_classifier              0.022627    0.001960    0.041444
ridge_classifier                      0.028758    0.003554    0.048270
sgd_classifier                        0.119235    0.004817    0.140924
x_gradient_boosting_classifier        0.049811    0.002617    0.061990
std_row                               0.093567    0.017664    0.033444

                                     auc
model
decision_tree_classifier        0.024264
gradient_boosting_classifier    0.018033
logistic_regression             0.017268
perceptron                      0.092655
random_forest_classifier        0.011950
ridge_classifier                0.016532
sgd_classifier                  0.058634
x_gradient_boosting_classifier  0.025038
std_row                         0.028136
Using file number: 12
Saving CSV file to: /Users/detraviousjamaribrinkley/Documents/Development/research_labs/uf_ds/predictions/notebook_experiments/../data/classification_results/averaged_results/fpb-maya-binary-imbalanced-96d-v1_2026-02-17_mean-v12.csv
Using file number: 12
Saving CSV file to: /Users/detraviousjamaribrinkley/Documents/Development/research_labs/uf_ds/predictions/notebook_experiments/../data/classification_results/averaged_results/fpb-maya-binary-imbalanced-96d-v1_2026-02-17_std-v12.csv
Using file number: 12
Saving CSV file to: /Users/detraviousjamaribrinkley/Documents/Development/research_labs/uf_ds/predictions/notebook_experiments/../data/classification_results/averaged_results/fpb-maya-binary-imbalanced-96d-v1_2026-02-17_mean_std-v12.csv
✓ Saved: fpb-maya-binary-imbalanced-96d-v1_2026-02-17_metadata-v12.json

==================================================
Averaging: fpb-maya-binary-imbalanced-96d-v1_2026-02-21
==================================================
Seeds used: 1
Seed details: ['seed42']

Mean metrics:
                                   accuracy  precision_class_0  \
model
support_vector_machine_classifier   0.91134           0.910788
mean_row                            0.91134           0.910788

                                   precision_class_1  recall_class_0  \
model
support_vector_machine_classifier                1.0             1.0
mean_row                                         1.0             1.0

                                   recall_class_1  f1_class_0  f1_class_1  \
model
support_vector_machine_classifier        0.065217    0.953312    0.122449
mean_row                                 0.065217    0.953312    0.122449

                                        auc
model
support_vector_machine_classifier  0.532609
mean_row                           0.532609

Std metrics:
                                   accuracy  precision_class_0  \
model
support_vector_machine_classifier       NaN                NaN
std_row                                 NaN                NaN

                                   precision_class_1  recall_class_0  \
model
support_vector_machine_classifier                NaN             NaN
std_row                                          NaN             NaN

                                   recall_class_1  f1_class_0  f1_class_1  auc
model
support_vector_machine_classifier             NaN         NaN         NaN  NaN
std_row                                       NaN         NaN         NaN  NaN
Using file number: 11
Saving CSV file to: /Users/detraviousjamaribrinkley/Documents/Development/research_labs/uf_ds/predictions/notebook_experiments/../data/classification_results/averaged_results/fpb-maya-binary-imbalanced-96d-v1_2026-02-21_mean-v11.csv
Using file number: 11
Saving CSV file to: /Users/detraviousjamaribrinkley/Documents/Development/research_labs/uf_ds/predictions/notebook_experiments/../data/classification_results/averaged_results/fpb-maya-binary-imbalanced-96d-v1_2026-02-21_std-v11.csv
Using file number: 11
Saving CSV file to: /Users/detraviousjamaribrinkley/Documents/Development/research_labs/uf_ds/predictions/notebook_experiments/../data/classification_results/averaged_results/fpb-maya-binary-imbalanced-96d-v1_2026-02-21_mean_std-v11.csv
✓ Saved: fpb-maya-binary-imbalanced-96d-v1_2026-02-21_metadata-v11.json

==================================================
Averaging: fpb-maya-binary-oversampled-96d-v1_2026-02-17
==================================================
Seeds used: 3
Seed details: ['seed7', 'seed33', 'seed40']

Mean metrics:
                                accuracy  precision_class_0  \
model
decision_tree_classifier        0.951405           1.000000
gradient_boosting_classifier    0.946849           0.984494
logistic_regression             0.864655           0.878008
perceptron                      0.827639           0.888465
random_forest_classifier        0.994875           1.000000
ridge_classifier                0.875285           0.898707
sgd_classifier                  0.879841           0.912526
x_gradient_boosting_classifier  0.987282           1.000000
mean_row                        0.915979           0.945275

                                precision_class_1  recall_class_0  \
model
decision_tree_classifier                 0.911475        0.902809
gradient_boosting_classifier             0.914839        0.908125
logistic_regression                      0.852276        0.847001
perceptron                               0.820908        0.790433
random_forest_classifier                 0.989859        0.989749
ridge_classifier                         0.854731        0.846241
sgd_classifier                           0.852556        0.840547
x_gradient_boosting_classifier           0.975207        0.974563
mean_row                                 0.896481        0.887434

                                recall_class_1  f1_class_0  f1_class_1  \
model
decision_tree_classifier              1.000000    0.948901    0.953673
gradient_boosting_classifier          0.985573    0.944694    0.948836
logistic_regression                   0.882308    0.862204    0.867013
perceptron                            0.864844    0.821262    0.826837
random_forest_classifier              1.000000    0.994847    0.994902
ridge_classifier                      0.904328    0.871587    0.878752
sgd_classifier                        0.919134    0.874823    0.884421
x_gradient_boosting_classifier        1.000000    0.987114    0.987445
mean_row                              0.944524    0.913179    0.917735

                                     auc
model
decision_tree_classifier        0.951405
gradient_boosting_classifier    0.946849
logistic_regression             0.864655
perceptron                      0.827639
random_forest_classifier        0.994875
ridge_classifier                0.875285
sgd_classifier                  0.879841
x_gradient_boosting_classifier  0.987282
mean_row                        0.915979

Std metrics:
                                accuracy  precision_class_0  \
model
decision_tree_classifier        0.005291           0.000000
gradient_boosting_classifier    0.001433           0.009116
logistic_regression             0.003617           0.000998
perceptron                      0.042996           0.146878
random_forest_classifier        0.001507           0.000000
ridge_classifier                0.005609           0.016131
sgd_classifier                  0.005432           0.010806
x_gradient_boosting_classifier  0.002302           0.000000
std_row                         0.014036           0.050434

                                precision_class_1  recall_class_0  \
model
decision_tree_classifier                 0.008745        0.010583
gradient_boosting_classifier             0.008927        0.011408
logistic_regression                      0.007482        0.009552
perceptron                               0.079929        0.133889
random_forest_classifier                 0.002948        0.003013
ridge_classifier                         0.003506        0.007113
sgd_classifier                           0.017122        0.023918
x_gradient_boosting_classifier           0.004382        0.004603
std_row                                  0.025971        0.044250

                                recall_class_1  f1_class_0  f1_class_1  \
model
decision_tree_classifier              0.000000    0.005864    0.004799
gradient_boosting_classifier          0.008624    0.002063    0.000906
logistic_regression                   0.002371    0.004528    0.002772
perceptron                            0.199614    0.030915    0.071291
random_forest_classifier              0.000000    0.001523    0.001490
ridge_classifier                      0.017681    0.004240    0.006858
sgd_classifier                        0.013135    0.008049    0.003202
x_gradient_boosting_classifier        0.000000    0.002360    0.002245
std_row                               0.068791    0.009727    0.024155

                                     auc
model
decision_tree_classifier        0.005291
gradient_boosting_classifier    0.001433
logistic_regression             0.003617
perceptron                      0.042996
random_forest_classifier        0.001507
ridge_classifier                0.005609
sgd_classifier                  0.005432
x_gradient_boosting_classifier  0.002302
std_row                         0.014036
Using file number: 12
Saving CSV file to: /Users/detraviousjamaribrinkley/Documents/Development/research_labs/uf_ds/predictions/notebook_experiments/../data/classification_results/averaged_results/fpb-maya-binary-oversampled-96d-v1_2026-02-17_mean-v12.csv
Using file number: 12
Saving CSV file to: /Users/detraviousjamaribrinkley/Documents/Development/research_labs/uf_ds/predictions/notebook_experiments/../data/classification_results/averaged_results/fpb-maya-binary-oversampled-96d-v1_2026-02-17_std-v12.csv
Using file number: 12
Saving CSV file to: /Users/detraviousjamaribrinkley/Documents/Development/research_labs/uf_ds/predictions/notebook_experiments/../data/classification_results/averaged_results/fpb-maya-binary-oversampled-96d-v1_2026-02-17_mean_std-v12.csv
✓ Saved: fpb-maya-binary-oversampled-96d-v1_2026-02-17_metadata-v12.json

==================================================
Averaging: fpb-maya-binary-undersampled-96d-v1_2026-02-17
==================================================
Seeds used: 3
Seed details: ['seed7', 'seed33', 'seed40']

Mean metrics:
                                accuracy  precision_class_0  \
model
decision_tree_classifier        0.590580           0.595411
gradient_boosting_classifier    0.766304           0.766178
logistic_regression             0.778986           0.788049
perceptron                      0.755435           0.852891
random_forest_classifier        0.759058           0.743461
ridge_classifier                0.778986           0.779599
sgd_classifier                  0.748188           0.699727
x_gradient_boosting_classifier  0.771739           0.761706
mean_row                        0.743659           0.748378

                                precision_class_1  recall_class_0  \
model
decision_tree_classifier                 0.586532        0.568841
gradient_boosting_classifier             0.770896        0.771739
logistic_regression                      0.774959        0.768116
perceptron                               0.718059        0.637681
random_forest_classifier                 0.781963        0.797101
ridge_classifier                         0.783032        0.782609
sgd_classifier                           0.844668        0.880435
x_gradient_boosting_classifier           0.784783        0.793478
mean_row                                 0.755612        0.750000

                                recall_class_1  f1_class_0  f1_class_1  \
model
decision_tree_classifier              0.612319    0.581496    0.598853
gradient_boosting_classifier          0.760870    0.767445    0.764203
logistic_regression                   0.789855    0.776320    0.780651
perceptron                            0.873188    0.715240    0.781021
random_forest_classifier              0.721014    0.767918    0.748314
ridge_classifier                      0.775362    0.779554    0.777476
sgd_classifier                        0.615942    0.777795    0.706389
x_gradient_boosting_classifier        0.750000    0.776619    0.766178
mean_row                              0.737319    0.742798    0.740386

                                     auc
model
decision_tree_classifier        0.590580
gradient_boosting_classifier    0.766304
logistic_regression             0.778986
perceptron                      0.755435
random_forest_classifier        0.759058
ridge_classifier                0.778986
sgd_classifier                  0.748188
x_gradient_boosting_classifier  0.771739
mean_row                        0.743659

Std metrics:
                                accuracy  precision_class_0  \
model
decision_tree_classifier        0.029932           0.034554
gradient_boosting_classifier    0.014379           0.039973
logistic_regression             0.012551           0.039055
perceptron                      0.030260           0.078889
random_forest_classifier        0.017470           0.038967
ridge_classifier                0.006276           0.035493
sgd_classifier                  0.022627           0.040937
x_gradient_boosting_classifier  0.010870           0.027337
std_row                         0.008827           0.015568

                                precision_class_1  recall_class_0  \
model
decision_tree_classifier                 0.026366        0.031378
gradient_boosting_classifier             0.025469        0.047379
logistic_regression                      0.027773        0.051368
perceptron                               0.076845        0.164965
random_forest_classifier                 0.021104        0.043929
ridge_classifier                         0.026835        0.049811
sgd_classifier                           0.049966        0.057516
x_gradient_boosting_classifier           0.014255        0.028758
std_row                                  0.020236        0.043772

                                recall_class_1  f1_class_0  f1_class_1  \
model
decision_tree_classifier              0.049014    0.028258    0.035346
gradient_boosting_classifier          0.065217    0.011642    0.024601
logistic_regression                   0.063690    0.012956    0.021738
perceptron                            0.108877    0.075624    0.009900
random_forest_classifier              0.072373    0.009552    0.032589
ridge_classifier                      0.061807    0.006519    0.019058
sgd_classifier                        0.102735    0.004221    0.055614
x_gradient_boosting_classifier        0.047379    0.005519    0.019806
std_row                               0.022851    0.023986    0.013936

                                     auc
model
decision_tree_classifier        0.029932
gradient_boosting_classifier    0.014379
logistic_regression             0.012551
perceptron                      0.030260
random_forest_classifier        0.017470
ridge_classifier                0.006276
sgd_classifier                  0.022627
x_gradient_boosting_classifier  0.010870
std_row                         0.008827
Using file number: 12
Saving CSV file to: /Users/detraviousjamaribrinkley/Documents/Development/research_labs/uf_ds/predictions/notebook_experiments/../data/classification_results/averaged_results/fpb-maya-binary-undersampled-96d-v1_2026-02-17_mean-v12.csv
Using file number: 12
Saving CSV file to: /Users/detraviousjamaribrinkley/Documents/Development/research_labs/uf_ds/predictions/notebook_experiments/../data/classification_results/averaged_results/fpb-maya-binary-undersampled-96d-v1_2026-02-17_std-v12.csv
Using file number: 12

(list,
 [{'experiment': 'fpb-maya-binary-imbalanced-96d-v1_2026-02-17',
   'version': 12,
   'n_seeds': 3,
   'seed_info': [{'seed': 7, 'folder': 'seed7', 'version': '0'},
    {'seed': 33, 'folder': 'seed33', 'version': '0'},
    {'seed': 40, 'folder': 'seed40', 'version': '0'}],
   'mean':                                 accuracy  precision_class_0  \
   model
   decision_tree_classifier        0.840893           0.921532
   gradient_boosting_classifier    0.913402           0.921147
   logistic_regression             0.916838           0.924724
   perceptron                      0.870790           0.954395
   random_forest_classifier        0.908247           0.909375
   ridge_classifier                0.918900           0.922776
   sgd_classifier                  0.921306           0.929101
   x_gradient_boosting_classifier  0.917182           0.925361
   mean_row                        0.900945           0.926051

                                   precision_class_1  recall_class_0  \
   model
   decision_tree_classifier                 0.222895        0.900911
   gradient_boosting_classifier             0.645062        0.988990
   logistic_regression                      0.682696        0.988610
   perceptron                               0.500757        0.903189
   random_forest_classifier                 0.750000        0.998102
   ridge_classifier                         0.774573        0.993546
   sgd_classifier                           0.702742        0.988610
   x_gradient_boosting_classifier           0.676199        0.988231
   mean_row                                 0.619365        0.968774

                                   recall_class_1  f1_class_0  f1_class_1  \
   model
   decision_tree_classifier              0.268116    0.911088    0.243129
   gradient_boosting_classifier          0.192029    0.953864    0.295938
   logistic_regression                   0.231884    0.955597    0.345234
   perceptron                            0.561594    0.924080    0.456605
   random_forest_classifier              0.050725    0.951674    0.094638
   ridge_classifier                      0.206522    0.956854    0.326028
   sgd_classifier                        0.278986    0.957903    0.392763
   x_gradient_boosting_classifier        0.239130    0.955759    0.352467
   mean_row                              0.253623    0.945852    0.313350

                                        auc
   model
   decision_tree_classifier        0.584514
   gradient_boosting_classifier    0.590510
   logistic_regression             0.610247
   perceptron                      0.732392
   random_forest_classifier        0.524413
   ridge_classifier                0.600034
   sgd_classifier                  0.633798
   x_gradient_boosting_classifier  0.613681
   mean_row                        0.611198  ,
   'std':                                 accuracy  precision_class_0  \
   model
   decision_tree_classifier        0.014592           0.004568
   gradient_boosting_classifier    0.005740           0.003196
   logistic_regression             0.003903           0.003145
   perceptron                      0.080070           0.027326
   random_forest_classifier        0.003717           0.002069
   ridge_classifier                0.006628           0.002893
   sgd_classifier                  0.009579           0.010693
   x_gradient_boosting_classifier  0.005085           0.004536
   std_row                         0.026070           0.008523

                                   precision_class_1  recall_class_0  \
   model
   decision_tree_classifier                 0.046093        0.012936
   gradient_boosting_classifier             0.098137        0.002866
   logistic_regression                      0.064723        0.003013
   perceptron                               0.193959        0.118106
   random_forest_classifier                 0.250000        0.002371
   ridge_classifier                         0.139426        0.004312
   sgd_classifier                           0.074521        0.002278
   x_gradient_boosting_classifier           0.060340        0.001315
   std_row                                  0.072935        0.040455

                                   recall_class_1  f1_class_0  f1_class_1  \
   model
   decision_tree_classifier              0.038173    0.008552    0.042363
   gradient_boosting_classifier          0.033207    0.003045    0.049744
   logistic_regression                   0.034941    0.002066    0.041594
   perceptron                            0.296748    0.053396    0.068143
   random_forest_classifier              0.022627    0.001960    0.041444
   ridge_classifier                      0.028758    0.003554    0.048270
   sgd_classifier                        0.119235    0.004817    0.140924
   x_gradient_boosting_classifier        0.049811    0.002617    0.061990
   std_row                               0.093567    0.017664    0.033444

                                        auc
   model
   decision_tree_classifier        0.024264
   gradient_boosting_classifier    0.018033
   logistic_regression             0.017268
   perceptron                      0.092655
   random_forest_classifier        0.011950
   ridge_classifier                0.016532
   sgd_classifier                  0.058634
   x_gradient_boosting_classifier  0.025038
   std_row                         0.028136  },
  {'experiment': 'fpb-maya-binary-imbalanced-96d-v1_2026-02-21',
   'version': 11,
   'n_seeds': 1,
   'seed_info': [{'seed': 42, 'folder': 'seed42', 'version': '0'}],
   'mean':                                    accuracy  precision_class_0  \
   model
   support_vector_machine_classifier   0.91134           0.910788
   mean_row                            0.91134           0.910788

                                      precision_class_1  recall_class_0  \
   model
   support_vector_machine_classifier                1.0             1.0
   mean_row                                         1.0             1.0

                                      recall_class_1  f1_class_0  f1_class_1  \
   model
   support_vector_machine_classifier        0.065217    0.953312    0.122449
   mean_row                                 0.065217    0.953312    0.122449

                                           auc
   model
   support_vector_machine_classifier  0.532609
   mean_row                           0.532609  ,
   'std':                                    accuracy  precision_class_0  \
   model
   support_vector_machine_classifier       NaN                NaN
   std_row                                 NaN                NaN

                                      precision_class_1  recall_class_0  \
   model
   support_vector_machine_classifier                NaN             NaN
   std_row                                          NaN             NaN

                                      recall_class_1  f1_class_0  f1_class_1  auc
   model
   support_vector_machine_classifier             NaN         NaN         NaN  NaN
   std_row                                       NaN         NaN         NaN  NaN  },
  {'experiment': 'fpb-maya-binary-oversampled-96d-v1_2026-02-17',
   'version': 12,
   'n_seeds': 3,
   'seed_info': [{'seed': 7, 'folder': 'seed7', 'version': '0'},
    {'seed': 33, 'folder': 'seed33', 'version': '0'},
    {'seed': 40, 'folder': 'seed40', 'version': '0'}],
   'mean':                                 accuracy  precision_class_0  \
   model
   decision_tree_classifier        0.951405           1.000000
   gradient_boosting_classifier    0.946849           0.984494
   logistic_regression             0.864655           0.878008
   perceptron                      0.827639           0.888465
   random_forest_classifier        0.994875           1.000000
   ridge_classifier                0.875285           0.898707
   sgd_classifier                  0.879841           0.912526
   x_gradient_boosting_classifier  0.987282           1.000000
   mean_row                        0.915979           0.945275

                                   precision_class_1  recall_class_0  \
   model
   decision_tree_classifier                 0.911475        0.902809
   gradient_boosting_classifier             0.914839        0.908125
   logistic_regression                      0.852276        0.847001
   perceptron                               0.820908        0.790433
   random_forest_classifier                 0.989859        0.989749
   ridge_classifier                         0.854731        0.846241
   sgd_classifier                           0.852556        0.840547
   x_gradient_boosting_classifier           0.975207        0.974563
   mean_row                                 0.896481        0.887434

                                   recall_class_1  f1_class_0  f1_class_1  \
   model
   decision_tree_classifier              1.000000    0.948901    0.953673
   gradient_boosting_classifier          0.985573    0.944694    0.948836
   logistic_regression                   0.882308    0.862204    0.867013
   perceptron                            0.864844    0.821262    0.826837
   random_forest_classifier              1.000000    0.994847    0.994902
   ridge_classifier                      0.904328    0.871587    0.878752
   sgd_classifier                        0.919134    0.874823    0.884421
   x_gradient_boosting_classifier        1.000000    0.987114    0.987445
   mean_row                              0.944524    0.913179    0.917735

                                        auc
   model
   decision_tree_classifier        0.951405
   gradient_boosting_classifier    0.946849
   logistic_regression             0.864655
   perceptron                      0.827639
   random_forest_classifier        0.994875
   ridge_classifier                0.875285
   sgd_classifier                  0.879841
   x_gradient_boosting_classifier  0.987282
   mean_row                        0.915979  ,
   'std':                                 accuracy  precision_class_0  \
   model
   decision_tree_classifier        0.005291           0.000000
   gradient_boosting_classifier    0.001433           0.009116
   logistic_regression             0.003617           0.000998
   perceptron                      0.042996           0.146878
   random_forest_classifier        0.001507           0.000000
   ridge_classifier                0.005609           0.016131
   sgd_classifier                  0.005432           0.010806
   x_gradient_boosting_classifier  0.002302           0.000000
   std_row                         0.014036           0.050434

                                   precision_class_1  recall_class_0  \
   model
   decision_tree_classifier                 0.008745        0.010583
   gradient_boosting_classifier             0.008927        0.011408
   logistic_regression                      0.007482        0.009552
   perceptron                               0.079929        0.133889
   random_forest_classifier                 0.002948        0.003013
   ridge_classifier                         0.003506        0.007113
   sgd_classifier                           0.017122        0.023918
   x_gradient_boosting_classifier           0.004382        0.004603
   std_row                                  0.025971        0.044250

                                   recall_class_1  f1_class_0  f1_class_1  \
   model
   decision_tree_classifier              0.000000    0.005864    0.004799
   gradient_boosting_classifier          0.008624    0.002063    0.000906
   logistic_regression                   0.002371    0.004528    0.002772
   perceptron                            0.199614    0.030915    0.071291
   random_forest_classifier              0.000000    0.001523    0.001490
   ridge_classifier                      0.017681    0.004240    0.006858
   sgd_classifier                        0.013135    0.008049    0.003202
   x_gradient_boosting_classifier        0.000000    0.002360    0.002245
   std_row                               0.068791    0.009727    0.024155

                                        auc
   model
   decision_tree_classifier        0.005291
   gradient_boosting_classifier    0.001433
   logistic_regression             0.003617
   perceptron                      0.042996
   random_forest_classifier        0.001507
   ridge_classifier                0.005609
   sgd_classifier                  0.005432
   x_gradient_boosting_classifier  0.002302
   std_row                         0.014036  },
  {'experiment': 'fpb-maya-binary-undersampled-96d-v1_2026-02-17',
   'version': 12,
   'n_seeds': 3,
   'seed_info': [{'seed': 7, 'folder': 'seed7', 'version': '0'},
    {'seed': 33, 'folder': 'seed33', 'version': '0'},
    {'seed': 40, 'folder': 'seed40', 'version': '0'}],
   'mean':                                 accuracy  precision_class_0  \
   model
   decision_tree_classifier        0.590580           0.595411
   gradient_boosting_classifier    0.766304           0.766178
   logistic_regression             0.778986           0.788049
   perceptron                      0.755435           0.852891
   random_forest_classifier        0.759058           0.743461
   ridge_classifier                0.778986           0.779599
   sgd_classifier                  0.748188           0.699727
   x_gradient_boosting_classifier  0.771739           0.761706
   mean_row                        0.743659           0.748378

                                   precision_class_1  recall_class_0  \
   model
   decision_tree_classifier                 0.586532        0.568841
   gradient_boosting_classifier             0.770896        0.771739
   logistic_regression                      0.774959        0.768116
   perceptron                               0.718059        0.637681
   random_forest_classifier                 0.781963        0.797101
   ridge_classifier                         0.783032        0.782609
   sgd_classifier                           0.844668        0.880435
   x_gradient_boosting_classifier           0.784783        0.793478
   mean_row                                 0.755612        0.750000

                                   recall_class_1  f1_class_0  f1_class_1  \
   model
   decision_tree_classifier              0.612319    0.581496    0.598853
   gradient_boosting_classifier          0.760870    0.767445    0.764203
   logistic_regression                   0.789855    0.776320    0.780651
   perceptron                            0.873188    0.715240    0.781021
   random_forest_classifier              0.721014    0.767918    0.748314
   ridge_classifier                      0.775362    0.779554    0.777476
   sgd_classifier                        0.615942    0.777795    0.706389
   x_gradient_boosting_classifier        0.750000    0.776619    0.766178
   mean_row                              0.737319    0.742798    0.740386

                                        auc
   model
   decision_tree_classifier        0.590580
   gradient_boosting_classifier    0.766304
   logistic_regression             0.778986
   perceptron                      0.755435
   random_forest_classifier        0.759058
   ridge_classifier                0.778986
   sgd_classifier                  0.748188
   x_gradient_boosting_classifier  0.771739
   mean_row                        0.743659  ,
   'std':                                 accuracy  precision_class_0  \
   model
   decision_tree_classifier        0.029932           0.034554
   gradient_boosting_classifier    0.014379           0.039973
   logistic_regression             0.012551           0.039055
   perceptron                      0.030260           0.078889
   random_forest_classifier        0.017470           0.038967
   ridge_classifier                0.006276           0.035493
   sgd_classifier                  0.022627           0.040937
   x_gradient_boosting_classifier  0.010870           0.027337
   std_row                         0.008827           0.015568

                                   precision_class_1  recall_class_0  \
   model
   decision_tree_classifier                 0.026366        0.031378
   gradient_boosting_classifier             0.025469        0.047379
   logistic_regression                      0.027773        0.051368
   perceptron                               0.076845        0.164965
   random_forest_classifier                 0.021104        0.043929
   ridge_classifier                         0.026835        0.049811
   sgd_classifier                           0.049966        0.057516
   x_gradient_boosting_classifier           0.014255        0.028758
   std_row                                  0.020236        0.043772

                                   recall_class_1  f1_class_0  f1_class_1  \
   model
   decision_tree_classifier              0.049014    0.028258    0.035346
   gradient_boosting_classifier          0.065217    0.011642    0.024601
   logistic_regression                   0.063690    0.012956    0.021738
   perceptron                            0.108877    0.075624    0.009900
   random_forest_classifier              0.072373    0.009552    0.032589
   ridge_classifier                      0.061807    0.006519    0.019058
   sgd_classifier                        0.102735    0.004221    0.055614
   x_gradient_boosting_classifier        0.047379    0.005519    0.019806
   std_row                               0.022851    0.023986    0.013936

                                        auc
   model
   decision_tree_classifier        0.029932
   gradient_boosting_classifier    0.014379
   logistic_regression             0.012551
   perceptron                      0.030260
   random_forest_classifier        0.017470
   ridge_classifier                0.006276
   sgd_classifier                  0.022627
   x_gradient_boosting_classifier  0.010870
   std_row                         0.008827  }])

In [13]:
# summaries[1]

In [14]:
# summaries[0]['mean']

In [15]:
combined_df

[{'experiment': 'fpb-maya-binary-imbalanced-96d-v1_2026-02-17',
  'version': 12,
  'n_seeds': 3,
  'seed_info': [{'seed': 7, 'folder': 'seed7', 'version': '0'},
   {'seed': 33, 'folder': 'seed33', 'version': '0'},
   {'seed': 40, 'folder': 'seed40', 'version': '0'}],
  'mean':                                 accuracy  precision_class_0  \
  model
  decision_tree_classifier        0.840893           0.921532
  gradient_boosting_classifier    0.913402           0.921147
  logistic_regression             0.916838           0.924724
  perceptron                      0.870790           0.954395
  random_forest_classifier        0.908247           0.909375
  ridge_classifier                0.918900           0.922776
  sgd_classifier                  0.921306           0.929101
  x_gradient_boosting_classifier  0.917182           0.925361
  mean_row                        0.900945           0.926051

                                  precision_class_1  recall_class_0  \
  model
  decision_tree_classifier                 0.222895        0.900911
  gradient_boosting_classifier             0.645062        0.988990
  logistic_regression                      0.682696        0.988610
  perceptron                               0.500757        0.903189
  random_forest_classifier                 0.750000        0.998102
  ridge_classifier                         0.774573        0.993546
  sgd_classifier                           0.702742        0.988610
  x_gradient_boosting_classifier           0.676199        0.988231
  mean_row                                 0.619365        0.968774

                                  recall_class_1  f1_class_0  f1_class_1  \
  model
  decision_tree_classifier              0.268116    0.911088    0.243129
  gradient_boosting_classifier          0.192029    0.953864    0.295938
  logistic_regression                   0.231884    0.955597    0.345234
  perceptron                            0.561594    0.924080    0.456605
  random_forest_classifier              0.050725    0.951674    0.094638
  ridge_classifier                      0.206522    0.956854    0.326028
  sgd_classifier                        0.278986    0.957903    0.392763
  x_gradient_boosting_classifier        0.239130    0.955759    0.352467
  mean_row                              0.253623    0.945852    0.313350

                                       auc
  model
  decision_tree_classifier        0.584514
  gradient_boosting_classifier    0.590510
  logistic_regression             0.610247
  perceptron                      0.732392
  random_forest_classifier        0.524413
  ridge_classifier                0.600034
  sgd_classifier                  0.633798
  x_gradient_boosting_classifier  0.613681
  mean_row                        0.611198  ,
  'std':                                 accuracy  precision_class_0  \
  model
  decision_tree_classifier        0.014592           0.004568
  gradient_boosting_classifier    0.005740           0.003196
  logistic_regression             0.003903           0.003145
  perceptron                      0.080070           0.027326
  random_forest_classifier        0.003717           0.002069
  ridge_classifier                0.006628           0.002893
  sgd_classifier                  0.009579           0.010693
  x_gradient_boosting_classifier  0.005085           0.004536
  std_row                         0.026070           0.008523

                                  precision_class_1  recall_class_0  \
  model
  decision_tree_classifier                 0.046093        0.012936
  gradient_boosting_classifier             0.098137        0.002866
  logistic_regression                      0.064723        0.003013
  perceptron                               0.193959        0.118106
  random_forest_classifier                 0.250000        0.002371
  ridge_classifier                         0.139426        0.004312
  sgd_classifier                           0.074521        0.002278
  x_gradient_boosting_classifier           0.060340        0.001315
  std_row                                  0.072935        0.040455

                                  recall_class_1  f1_class_0  f1_class_1  \
  model
  decision_tree_classifier              0.038173    0.008552    0.042363
  gradient_boosting_classifier          0.033207    0.003045    0.049744
  logistic_regression                   0.034941    0.002066    0.041594
  perceptron                            0.296748    0.053396    0.068143
  random_forest_classifier              0.022627    0.001960    0.041444
  ridge_classifier                      0.028758    0.003554    0.048270
  sgd_classifier                        0.119235    0.004817    0.140924
  x_gradient_boosting_classifier        0.049811    0.002617    0.061990
  std_row                               0.093567    0.017664    0.033444

                                       auc
  model
  decision_tree_classifier        0.024264
  gradient_boosting_classifier    0.018033
  logistic_regression             0.017268
  perceptron                      0.092655
  random_forest_classifier        0.011950
  ridge_classifier                0.016532
  sgd_classifier                  0.058634
  x_gradient_boosting_classifier  0.025038
  std_row                         0.028136  },
 {'experiment': 'fpb-maya-binary-imbalanced-96d-v1_2026-02-21',
  'version': 11,
  'n_seeds': 1,
  'seed_info': [{'seed': 42, 'folder': 'seed42', 'version': '0'}],
  'mean':                                    accuracy  precision_class_0  \
  model
  support_vector_machine_classifier   0.91134           0.910788
  mean_row                            0.91134           0.910788

                                     precision_class_1  recall_class_0  \
  model
  support_vector_machine_classifier                1.0             1.0
  mean_row                                         1.0             1.0

                                     recall_class_1  f1_class_0  f1_class_1  \
  model
  support_vector_machine_classifier        0.065217    0.953312    0.122449
  mean_row                                 0.065217    0.953312    0.122449

                                          auc
  model
  support_vector_machine_classifier  0.532609
  mean_row                           0.532609  ,
  'std':                                    accuracy  precision_class_0  \
  model
  support_vector_machine_classifier       NaN                NaN
  std_row                                 NaN                NaN

                                     precision_class_1  recall_class_0  \
  model
  support_vector_machine_classifier                NaN             NaN
  std_row                                          NaN             NaN

                                     recall_class_1  f1_class_0  f1_class_1  auc
  model
  support_vector_machine_classifier             NaN         NaN         NaN  NaN
  std_row                                       NaN         NaN         NaN  NaN  },
 {'experiment': 'fpb-maya-binary-oversampled-96d-v1_2026-02-17',
  'version': 12,
  'n_seeds': 3,
  'seed_info': [{'seed': 7, 'folder': 'seed7', 'version': '0'},
   {'seed': 33, 'folder': 'seed33', 'version': '0'},
   {'seed': 40, 'folder': 'seed40', 'version': '0'}],
  'mean':                                 accuracy  precision_class_0  \
  model
  decision_tree_classifier        0.951405           1.000000
  gradient_boosting_classifier    0.946849           0.984494
  logistic_regression             0.864655           0.878008
  perceptron                      0.827639           0.888465
  random_forest_classifier        0.994875           1.000000
  ridge_classifier                0.875285           0.898707
  sgd_classifier                  0.879841           0.912526
  x_gradient_boosting_classifier  0.987282           1.000000
  mean_row                        0.915979           0.945275

                                  precision_class_1  recall_class_0  \
  model
  decision_tree_classifier                 0.911475        0.902809
  gradient_boosting_classifier             0.914839        0.908125
  logistic_regression                      0.852276        0.847001
  perceptron                               0.820908        0.790433
  random_forest_classifier                 0.989859        0.989749
  ridge_classifier                         0.854731        0.846241
  sgd_classifier                           0.852556        0.840547
  x_gradient_boosting_classifier           0.975207        0.974563
  mean_row                                 0.896481        0.887434

                                  recall_class_1  f1_class_0  f1_class_1  \
  model
  decision_tree_classifier              1.000000    0.948901    0.953673
  gradient_boosting_classifier          0.985573    0.944694    0.948836
  logistic_regression                   0.882308    0.862204    0.867013
  perceptron                            0.864844    0.821262    0.826837
  random_forest_classifier              1.000000    0.994847    0.994902
  ridge_classifier                      0.904328    0.871587    0.878752
  sgd_classifier                        0.919134    0.874823    0.884421
  x_gradient_boosting_classifier        1.000000    0.987114    0.987445
  mean_row                              0.944524    0.913179    0.917735

                                       auc
  model
  decision_tree_classifier        0.951405
  gradient_boosting_classifier    0.946849
  logistic_regression             0.864655
  perceptron                      0.827639
  random_forest_classifier        0.994875
  ridge_classifier                0.875285
  sgd_classifier                  0.879841
  x_gradient_boosting_classifier  0.987282
  mean_row                        0.915979  ,
  'std':                                 accuracy  precision_class_0  \
  model
  decision_tree_classifier        0.005291           0.000000
  gradient_boosting_classifier    0.001433           0.009116
  logistic_regression             0.003617           0.000998
  perceptron                      0.042996           0.146878
  random_forest_classifier        0.001507           0.000000
  ridge_classifier                0.005609           0.016131
  sgd_classifier                  0.005432           0.010806
  x_gradient_boosting_classifier  0.002302           0.000000
  std_row                         0.014036           0.050434

                                  precision_class_1  recall_class_0  \
  model
  decision_tree_classifier                 0.008745        0.010583
  gradient_boosting_classifier             0.008927        0.011408
  logistic_regression                      0.007482        0.009552
  perceptron                               0.079929        0.133889
  random_forest_classifier                 0.002948        0.003013
  ridge_classifier                         0.003506        0.007113
  sgd_classifier                           0.017122        0.023918
  x_gradient_boosting_classifier           0.004382        0.004603
  std_row                                  0.025971        0.044250

                                  recall_class_1  f1_class_0  f1_class_1  \
  model
  decision_tree_classifier              0.000000    0.005864    0.004799
  gradient_boosting_classifier          0.008624    0.002063    0.000906
  logistic_regression                   0.002371    0.004528    0.002772
  perceptron                            0.199614    0.030915    0.071291
  random_forest_classifier              0.000000    0.001523    0.001490
  ridge_classifier                      0.017681    0.004240    0.006858
  sgd_classifier                        0.013135    0.008049    0.003202
  x_gradient_boosting_classifier        0.000000    0.002360    0.002245
  std_row                               0.068791    0.009727    0.024155

                                       auc
  model
  decision_tree_classifier        0.005291
  gradient_boosting_classifier    0.001433
  logistic_regression             0.003617
  perceptron                      0.042996
  random_forest_classifier        0.001507
  ridge_classifier                0.005609
  sgd_classifier                  0.005432
  x_gradient_boosting_classifier  0.002302
  std_row                         0.014036  },
 {'experiment': 'fpb-maya-binary-undersampled-96d-v1_2026-02-17',
  'version': 12,
  'n_seeds': 3,
  'seed_info': [{'seed': 7, 'folder': 'seed7', 'version': '0'},
   {'seed': 33, 'folder': 'seed33', 'version': '0'},
   {'seed': 40, 'folder': 'seed40', 'version': '0'}],
  'mean':                                 accuracy  precision_class_0  \
  model
  decision_tree_classifier        0.590580           0.595411
  gradient_boosting_classifier    0.766304           0.766178
  logistic_regression             0.778986           0.788049
  perceptron                      0.755435           0.852891
  random_forest_classifier        0.759058           0.743461
  ridge_classifier                0.778986           0.779599
  sgd_classifier                  0.748188           0.699727
  x_gradient_boosting_classifier  0.771739           0.761706
  mean_row                        0.743659           0.748378

                                  precision_class_1  recall_class_0  \
  model
  decision_tree_classifier                 0.586532        0.568841
  gradient_boosting_classifier             0.770896        0.771739
  logistic_regression                      0.774959        0.768116
  perceptron                               0.718059        0.637681
  random_forest_classifier                 0.781963        0.797101
  ridge_classifier                         0.783032        0.782609
  sgd_classifier                           0.844668        0.880435
  x_gradient_boosting_classifier           0.784783        0.793478
  mean_row                                 0.755612        0.750000

                                  recall_class_1  f1_class_0  f1_class_1  \
  model
  decision_tree_classifier              0.612319    0.581496    0.598853
  gradient_boosting_classifier          0.760870    0.767445    0.764203
  logistic_regression                   0.789855    0.776320    0.780651
  perceptron                            0.873188    0.715240    0.781021
  random_forest_classifier              0.721014    0.767918    0.748314
  ridge_classifier                      0.775362    0.779554    0.777476
  sgd_classifier                        0.615942    0.777795    0.706389
  x_gradient_boosting_classifier        0.750000    0.776619    0.766178
  mean_row                              0.737319    0.742798    0.740386

                                       auc
  model
  decision_tree_classifier        0.590580
  gradient_boosting_classifier    0.766304
  logistic_regression             0.778986
  perceptron                      0.755435
  random_forest_classifier        0.759058
  ridge_classifier                0.778986
  sgd_classifier                  0.748188
  x_gradient_boosting_classifier  0.771739
  mean_row                        0.743659  ,
  'std':                                 accuracy  precision_class_0  \
  model
  decision_tree_classifier        0.029932           0.034554
  gradient_boosting_classifier    0.014379           0.039973
  logistic_regression             0.012551           0.039055
  perceptron                      0.030260           0.078889
  random_forest_classifier        0.017470           0.038967
  ridge_classifier                0.006276           0.035493
  sgd_classifier                  0.022627           0.040937
  x_gradient_boosting_classifier  0.010870           0.027337
  std_row                         0.008827           0.015568

                                  precision_class_1  recall_class_0  \
  model
  decision_tree_classifier                 0.026366        0.031378
  gradient_boosting_classifier             0.025469        0.047379
  logistic_regression                      0.027773        0.051368
  perceptron                               0.076845        0.164965
  random_forest_classifier                 0.021104        0.043929
  ridge_classifier                         0.026835        0.049811
  sgd_classifier                           0.049966        0.057516
  x_gradient_boosting_classifier           0.014255        0.028758
  std_row                                  0.020236        0.043772

                                  recall_class_1  f1_class_0  f1_class_1  \
  model
  decision_tree_classifier              0.049014    0.028258    0.035346
  gradient_boosting_classifier          0.065217    0.011642    0.024601
  logistic_regression                   0.063690    0.012956    0.021738
  perceptron                            0.108877    0.075624    0.009900
  random_forest_classifier              0.072373    0.009552    0.032589
  ridge_classifier                      0.061807    0.006519    0.019058
  sgd_classifier                        0.102735    0.004221    0.055614
  x_gradient_boosting_classifier        0.047379    0.005519    0.019806
  std_row                               0.022851    0.023986    0.013936

                                       auc
  model
  decision_tree_classifier        0.029932
  gradient_boosting_classifier    0.014379
  logistic_regression             0.012551
  perceptron                      0.030260
  random_forest_classifier        0.017470
  ridge_classifier                0.006276
  sgd_classifier                  0.022627
  x_gradient_boosting_classifier  0.010870
  std_row                         0.008827  }]

In [16]:
numeric_cols = combined_df.select_dtypes(include=[np.number]).columns
numeric_cols

AttributeError: 'list' object has no attribute 'select_dtypes'

In [ ]:
combined_df.groupby('model')[numeric_cols]

In [ ]:

mean_df = combined_df.groupby('model')[numeric_cols].mean()
std_df = combined_df.groupby('model')[numeric_cols].std()

In [ ]:
mean_df

In [24]:
avg_rows_cols_dir = os.path.join(notebook_dir, '../data/classification_results/averaged_results/fpb-maya-binary-imbalanced-96d-v1_2026-02-17_mean-v11.csv')
df = pd.read_csv(avg_rows_cols_dir)
df

,accuracy,precision_class_0,precision_class_1,recall_class_0,recall_class_1,f1_class_0,f1_class_1,auc
0,0.840893,0.921532,0.222895,0.900911,0.268116,0.911088,0.243129,0.584514
1,0.913402,0.921147,0.645062,0.988990,0.192029,0.953864,0.295938,0.590510
2,0.916838,0.924724,0.682696,0.988610,0.231884,0.955597,0.345234,0.610247
3,0.870790,0.954395,0.500757,0.903189,0.561594,0.924080,0.456605,0.732392
4,0.908247,0.909375,0.750000,0.998102,0.050725,0.951674,0.094638,0.524413
5,0.918900,0.922776,0.774573,0.993546,0.206522,0.956854,0.326028,0.600034
6,0.921306,0.929101,0.702742,0.988610,0.278986,0.957903,0.392763,0.633798
7,0.917182,0.925361,0.676199,0.988231,0.239130,0.955759,0.352467,0.613681
8,0.900945,0.926051,0.619365,0.968774,0.253623,0.945852,0.313350,0.611198

In [25]:
df.mean().values.tolist()

[0.9009450171821306,
 0.9260513754295894,
 0.619365290807933,
 0.9687737281700834,
 0.253623188405797,
 0.9458524124026462,
 0.31335026639186636,
 0.6111984582879403]

In [26]:
(0.840893470790378 + 0.91340206185567 + 0.9168384879725084 + 0.8707903780068729 + 0.9082474226804124	+ 0.9189003436426116 + 0.9213058419243986 + 
0.9171821305841924)/8

0.9009450171821307

In [27]:
np.std([0.840893470790378, 0.91340206185567, 0.9168384879725084, 0.8707903780068729, 0.9082474226804124, 0.9189003436426116, 0.9213058419243986 , 0.9171821305841924])

np.float64(0.0273340373293411)

In [28]:
df.loc[8] = df.mean()
df

,accuracy,precision_class_0,precision_class_1,recall_class_0,recall_class_1,f1_class_0,f1_class_1,auc
0,0.840893,0.921532,0.222895,0.900911,0.268116,0.911088,0.243129,0.584514
1,0.913402,0.921147,0.645062,0.988990,0.192029,0.953864,0.295938,0.590510
2,0.916838,0.924724,0.682696,0.988610,0.231884,0.955597,0.345234,0.610247
3,0.870790,0.954395,0.500757,0.903189,0.561594,0.924080,0.456605,0.732392
4,0.908247,0.909375,0.750000,0.998102,0.050725,0.951674,0.094638,0.524413
5,0.918900,0.922776,0.774573,0.993546,0.206522,0.956854,0.326028,0.600034
6,0.921306,0.929101,0.702742,0.988610,0.278986,0.957903,0.392763,0.633798
7,0.917182,0.925361,0.676199,0.988231,0.239130,0.955759,0.352467,0.613681
8,0.900945,0.926051,0.619365,0.968774,0.253623,0.945852,0.313350,0.611198

In [29]:
df.loc[9] = df.std()
df

,accuracy,precision_class_0,precision_class_1,recall_class_0,recall_class_1,f1_class_0,f1_class_1,auc
0,0.840893,0.921532,0.222895,0.900911,0.268116,0.911088,0.243129,0.584514
1,0.913402,0.921147,0.645062,0.988990,0.192029,0.953864,0.295938,0.590510
2,0.916838,0.924724,0.682696,0.988610,0.231884,0.955597,0.345234,0.610247
3,0.870790,0.954395,0.500757,0.903189,0.561594,0.924080,0.456605,0.732392
4,0.908247,0.909375,0.750000,0.998102,0.050725,0.951674,0.094638,0.524413
5,0.918900,0.922776,0.774573,0.993546,0.206522,0.956854,0.326028,0.600034
6,0.921306,0.929101,0.702742,0.988610,0.278986,0.957903,0.392763,0.633798
7,0.917182,0.925361,0.676199,0.988231,0.239130,0.955759,0.352467,0.613681
8,0.900945,0.926051,0.619365,0.968774,0.253623,0.945852,0.313350,0.611198
9,0.027334,0.011980,0.168547,0.038657,0.133960,0.016733,0.101615,0.054775

In [31]:
avg_rows_cols_dir = os.path.join(notebook_dir, '../data/classification_results/averaged_results/fpb-maya-binary-undersampled-96d-v1_2026-02-17_mean_std-v13.csv')
df = pd.read_csv(avg_rows_cols_dir)
df

,model,accuracy,precision_class_0,precision_class_1,recall_class_0,recall_class_1,f1_class_0,f1_class_1,auc
0,decision_tree_classifier,0.5906 ± 0.0299,0.5954 ± 0.0346,0.5865 ± 0.0264,0.5688 ± 0.0314,0.6123 ± 0.0490,0.5815 ± 0.0283,0.5989 ± 0.0353,0.5906 ± 0.0299
1,gradient_boosting_classifier,0.7663 ± 0.0144,0.7662 ± 0.0400,0.7709 ± 0.0255,0.7717 ± 0.0474,0.7609 ± 0.0652,0.7674 ± 0.0116,0.7642 ± 0.0246,0.7663 ± 0.0144
2,logistic_regression,0.7790 ± 0.0126,0.7880 ± 0.0391,0.7750 ± 0.0278,0.7681 ± 0.0514,0.7899 ± 0.0637,0.7763 ± 0.0130,0.7807 ± 0.0217,0.7790 ± 0.0126
3,perceptron,0.7554 ± 0.0303,0.8529 ± 0.0789,0.7181 ± 0.0768,0.6377 ± 0.1650,0.8732 ± 0.1089,0.7152 ± 0.0756,0.7810 ± 0.0099,0.7554 ± 0.0303
4,random_forest_classifier,0.7591 ± 0.0175,0.7435 ± 0.0390,0.7820 ± 0.0211,0.7971 ± 0.0439,0.7210 ± 0.0724,0.7679 ± 0.0096,0.7483 ± 0.0326,0.7591 ± 0.0175
5,ridge_classifier,0.7790 ± 0.0063,0.7796 ± 0.0355,0.7830 ± 0.0268,0.7826 ± 0.0498,0.7754 ± 0.0618,0.7796 ± 0.0065,0.7775 ± 0.0191,0.7790 ± 0.0063
6,sgd_classifier,0.7482 ± 0.0226,0.6997 ± 0.0409,0.8447 ± 0.0500,0.8804 ± 0.0575,0.6159 ± 0.1027,0.7778 ± 0.0042,0.7064 ± 0.0556,0.7482 ± 0.0226
7,x_gradient_boosting_classifier,0.7717 ± 0.0109,0.7617 ± 0.0273,0.7848 ± 0.0143,0.7935 ± 0.0288,0.7500 ± 0.0474,0.7766 ± 0.0055,0.7662 ± 0.0198,0.7717 ± 0.0109
8,mean_row,0.7437 ± 0.0088,0.7484 ± 0.0156,0.7556 ± 0.0202,0.7500 ± 0.0438,0.7373 ± 0.0229,0.7428 ± 0.0240,0.7404 ± 0.0139,0.7437 ± 0.0088

In [33]:
(0.5906 + 0.7663 + 0.7790 + 0.7554 + 0.7591 + 0.7790 + 0.7482 + 0.7717)/8

0.7436625

In [39]:
# 0.5906 ± 0.0299

# 0.7663 ± 0.0144

# 0.7790 ± 0.0126

# 0.7554 ± 0.0303

# 0.7591 ± 0.0175

# 0.7790 ± 0.0063

# 0.7482 ± 0.0226

# 0.7717 ± 0.0109

# 0.7437 ± 0.0088


std_df = pd.DataFrame([0.5906, 0.7663, 0.7790, 0.7554, 0.7591, 0.7790, 0.7482, 0.7717]).std()
std_df

0    0.062816
dtype: float64