## Data Acquisition: News API

In [1]:
import os
import re
import sys
import html

import pandas as pd

from datetime import datetime
from dotenv import load_dotenv
load_dotenv()

from newsapi import NewsApiClient

# Get the current working directory of the notebook
notebook_dir = os.getcwd()
# Add the parent directory to the system path
sys.path.append(os.path.join(notebook_dir, '../'))

from data_processing import DataProcessing
from feature_extraction import SpacyFeatureExtraction

In [2]:
pd.set_option('max_colwidth', 800)
# pd.set_option('display.max_columns', None)
# pd.set_option('display.max_rows', None)

In [3]:
api_key = os.getenv('NEWS_API_KEY')

In [4]:
QUERY_CONFIGS = [
    {"query_domain": "finance", "query": "(earnings OR revenue OR inflation OR interest rates) AND (expected OR forecast OR outlook OR projected)"},
    {"query_domain": "health", "query": "(disease OR virus OR vaccine OR public health) AND (expected OR forecast OR projected OR prognosis)"},
    {"query_domain": "weather", "query": "(weather OR storm OR hurricane OR rainfall OR temperature) AND (forecast OR expected OR outlook)"},
    {"query_domain": "policy", "query": "(election OR vote OR polling OR legislation) AND (expected OR likely OR projected OR forecast)"},
    {"query_domain": "sports_nfl", "query": "NFL AND (playoffs OR draft OR season) AND (expected OR likely OR prediction OR forecast)"},
    {"query_domain": "sports_nba", "query": "NBA AND (playoffs OR finals OR season) AND (expected OR likely OR prediction OR forecast)"},
    {"query_domain": "sports_college", "query": "(NCAA OR college football OR March Madness) AND (expected OR likely OR prediction OR forecast)"},
]

list_num = 1

In [5]:
# query_string = "Tesla OR SAE Level 4 autonomy"
start_date = "2026-03-21"
end_date = "2026-03-28"
newsapi = NewsApiClient(api_key=api_key)
all_articles = newsapi.get_everything(
    q=QUERY_CONFIGS[list_num]['query'],
    language="en",
    from_param=start_date,
    to=end_date,
    sort_by="relevancy",
    page_size=100
)

In [6]:
all_articles.keys()

dict_keys(['status', 'totalResults', 'articles'])

In [7]:
len(all_articles['articles']), all_articles['articles']

(94,
 [{'source': {'id': None, 'name': 'Gizmodo.com'},
   'author': 'Ed Cara',
   'title': 'Finally, Some Good News in the Fight Against Lyme Disease',
   'description': 'Scientists found that the experimental vaccine was more than 70% effective at preventing Lyme disease in a trial of nearly 10,000 volunteers.',
   'url': 'https://gizmodo.com/finally-some-good-news-in-the-fight-against-lyme-disease-2000737417',
   'urlToImage': 'https://gizmodo.com/app/uploads/2021/11/f2d874f6239357ae44984bcae121ed56.jpg',
   'publishedAt': '2026-03-24T19:35:35Z',
   'content': 'Ticks and the many diseases they can spread to people are a growing public health threat. With any luck, though, humanity may soon have a new weapon to use against the dreaded bloodsucking menace. A … [+4580 chars]'},
  {'source': {'id': None, 'name': 'nj.com'},
   'author': 'Steve Strunsky',
   'title': 'Closed Catholic school getting a new purpose in crowded section of N.J.’s largest city',
   'description': 'Details of the school’s projected opening date, grade configuration, cost and other aspects. would be made public during a special meeting at 5 p.m. on March...',
   'url': 'https://www.nj.com/essex/2026/03/newark-plans-new-school-in-crowded-ironbound-section-on-site-of-shuttered-catholic-school.html',
   'urlToImage': 'https://s.yimg.com/ny/api/res/1.2/ixkGljWVL3jaFAYti6DobA--/YXBwaWQ9aGlnaGxhbmRlcjt3PTEyMDA7aD05MDA7Y2Y9d2VicA--/https://media.zenfs.com/en/nj_com_articles_950/4d78b16399dd7696152f78e2f4b9c112',
   'publishedAt': '2026-03-22T15:00:46Z',
   'content': 'The Newark Board of Education president said the district plans to open a new school on the site of a shuttered former parochial school in the citys Ironbound section, using a lease-purchase agreemen… [+6313 chars]'},
  {'source': {'id': None, 'name': 'Scientific American'},
   'author': 'Kendra Pierre-Louis, Andrea Thompson, Sushmita Pathak, Alex Sugiura',
   'title': 'Spring heat dome, a blow to RFK, Jr.’s health agenda, SpaceX Starlink milestone',
   'description': 'An unseasonal heat dome over parts of the U.S., a federal court ruling that blocks the CDC’s recent change to its recommended childhood vaccine schedule, new research on unsafe levels of lead in fast fashion',
   'url': 'https://www.scientificamerican.com/podcast/episode/spring-heat-dome-a-blow-to-rfk-jr-s-health-agenda-spacex-starlink-milestone/',
   'urlToImage': 'https://static.scientificamerican.com/dam/m/3557c42768a73913/original/2603_SQ_MON_MARCH_23.png?m=1774038209.608&w=1200',
   'publishedAt': '2026-03-23T10:00:00Z',
   'content': 'Kendra Pierre-Louis: For Scientific American’s Science Quickly, I’m Kendra Pierre-Louis, in for Rachel Feltman. You’re listening to our weekly science news roundup.\r\nIf you live in much of California… [+10640 chars]'},
  {'source': {'id': None, 'name': 'NPR'},
   'author': 'Aaron Bolton',
   'title': 'A $50 billion fund to help rural hospitals could actually lead to closures and cuts',
   'description': 'States are rolling out plans for their share of a $50 billion fund established by Congress to improve rural health care. In some states, the money may provoke rural hospitals to cut services.',
   'url': 'https://www.npr.org/2026/03/26/nx-s1-5760925/rural-health-transformation-fund-hospitals-montana',
   'urlToImage': 'https://npr.brightspotcdn.com/dims3/default/strip/false/crop/4032x2268+0+378/resize/1400/quality/85/format/jpeg/?url=http%3A%2F%2Fnpr-brightspot.s3.amazonaws.com%2Fc3%2Ffe%2F0b795951485a84cd8ec7ee284ea2%2Frht-03.jpg',
   'publishedAt': '2026-03-26T09:00:00Z',
   'content': "The emergency department at Big Sandy Medical Center in Montana is just one room, with a single curtain between two beds.\r\nIt's one of the many parts of the 25-bed rural hospital that need updating, … [+8493 chars]"},
  {'source': {'id': None, 'name': 'Gizmodo.com'},
   'author': 'James Pero',
   'title': 'Oura’s Next Smart Ring Just Leaked a Year Early',
   'description': 'If these images are real, this is the first look at the Oura Ring 5.',
   'url': 'https://gizmodo.com/ouras-next-smart-ring-just-leaked-a-year-early-2000737357',
   'urlToImage': 'https://gizmodo.com/app/uploads/2025/11/Oura-Ring-4-Ceramic-review-05-1200x675.jpg',
   'publishedAt': '2026-03-24T15:40:39Z',
   'content': 'The Oura Ring 5 isn’t expected to launch for another year, but a purported leak might have given us an early glimpse of what to expect. Android Headlines claims to have obtained renders of the new he… [+2151 chars]'},
  {'source': {'id': None, 'name': 'Vox'},
   'author': 'Shayna Korol',
   'title': 'The world’s deadliest infectious disease is on the rise in the US',
   'description': 'Something unusual happened at Archbishop Riordan High School last fall.\xa0 In September, a student in the Bay Area school went to see a health care provider for a cough that wouldn’t go away. But it wasn’t until two months later that the student got diagnosed: …',
   'url': 'https://www.vox.com/future-perfect/483649/world-tuberculosis-day-tb-rates-usa',
   'urlToImage': 'https://platform.vox.com/wp-content/uploads/sites/2/2026/03/gettyimages-463914123.jpg?quality=90&strip=all&crop=0%2C33.545799980514%2C100%2C32.908400038972&w=1200',
   'publishedAt': '2026-03-23T23:17:24Z',
   'content': 'Something unusual happened at Archbishop Riordan High School last fall.\r\nIn September, a student in the Bay Area school went to see a health care provider for a cough that wouldnt go away. But it was… [+13195 chars]'},
  {'source': {'id': None, 'name': 'CNET'},
   'author': 'Tyler Graham',
   'title': "A Historic Heat Dome Is Creeping Across the US. Here's How to Prepare",
   'description': 'After breaking heat records in 14 states, the heat wave pummeling the Southwest is moving eastward.',
   'url': 'https://www.cnet.com/home/energy-and-utilities/historic-heat-dome-creeping-across-us-how-prepare/',
   'urlToImage': 'https://www.cnet.com/a/img/resize/31c493cb4025dc5881ddac068be8f4f1585e9c08/hub/2026/03/24/ad6cda5b-0d31-4d8d-b33a-f8827bd9848b/gettyimages-2267101587.jpg?auto=webp&fit=crop&height=675&width=1200',
   'publishedAt': '2026-03-24T22:55:30Z',
   'content': "A massive heat wave has broken heat records in 14 states, including Arizona and California, reaching up to 112 degrees Fahrenheit in some areas. Now it's creeping eastward, according to the National … [+4047 chars]"},
  {'source': {'id': None, 'name': 'Science Daily'},
   'author': None,
   'title': 'Men are losing a key chromosome with age and it may be deadly',
   'description': 'Aging men often lose the Y chromosome in a growing number of their cells—and it may be far more dangerous than once believed. This loss has been linked to heart disease, cancer, Alzheimer’s, and shorter lifespans. Researchers suspect Y-less cells may grow fas…',
   'url': 'https://www.sciencedaily.com/releases/2026/03/260319044711.htm',
   'urlToImage': 'https://www.sciencedaily.com/images/1920/genetics-x-and-y-chromosomes-dna.webp',
   'publishedAt': '2026-03-21T00:56:14Z',
   'content': 'As men grow older, some of their cells gradually lose the Y chromosome. For a long time, scientists assumed this change would have little impact. The Y chromosome contains relatively few genes beyond… [+5385 chars]'},
  {'source': {'id': None, 'name': 'Android Central'},
   'author': 'nickodiaz@sbcglobal.net (Nickolas Diaz) , Nickolas Diaz',
   'title': 'Take a breath: purported Oura Ring 5 design details appear, but nothing is set in stone',
   'description': 'Could this be the Oura Ring 5? Early rumors claimed this is what might take place during its eventual launch.',
   'url': 'https://www.androidcentral.com/wearables/oura-ring/take-a-breath-purported-oura-ring-5-design-details-appear-but-nothing-is-set-in-stone',
   'urlToImage': 'https://cdn.mos.cms.futurecdn.net/8STciJxzEnfTqsRu6V4KTX-2560-80.jpg',
   'publishedAt': '2026-03-26T09:11:00Z',
   'content': 'What you need to know\r\n<ul><li>An intriguing rumor claims that Oura\'s Ring 5 is preparing a few changes, such as a "curvier," more ring-like design for the next model.</li><li>Its batter life might r… [+3439 chars]'},
  {'source': {'id': 'business-insider', 'name': 'Business Insider'},
   'author': 'Arielle Pardes',
   'title': 'Superpower wants to make you hotter, smarter, and healthier',
   'description': "'Do you think you're going to be the one dumb, ugly, tired person?' Inside a San Francisco startup's quest for peptide dominance.",
   'url': 'https://www.businessinsider.com/inside-superpower-peptide-startup-people-hotter-smarter-2026-3',
   'urlToImage': 'https://i.insider.com/69bcb745d387710cb9e46820?width=1200&format=jpeg',
   'publishedAt': '2026-03-22T08:11:01Z',
   'content': 'For the techno-optimized, nearly everything in life can be improved with the help of engineering. Bots can auto-swipe on Tinder and flirt with matches on your behalf. AI avatars can attend Zoom meeti… [+20953 chars]'},
  {'source': {'id': None, 'name': 'Science Daily'},
   'author': None,
   'title': 'New blood test could catch pancreatic cancer before it’s too late',
   'description': 'A new blood test could change the outlook for one of the deadliest cancers—pancreatic cancer—by catching it much earlier than ever before. Researchers identified two previously unknown proteins in the blood that, when combined with existing markers, dramatica…',
   'url': 'https://www.sciencedaily.com/releases/2026/03/260323005540.htm',
   'urlToImage': 'https://www.sciencedaily.com/images/1920/pancreatic-cancer-malignant-tumor-cell-inset.webp',
   'publishedAt': '2026-03-23T07:33:52Z',
   'content': 'Researchers supported by the National Institutes of Health (NIH) have created a new blood test designed to identify pancreatic ductal adenocarcinoma, one of the most lethal types of cancer. Because p… [+3173 chars]'},
  {'source': {'id': None, 'name': 'Abcnews.com'},
   'author': 'STEPHEN GROVES Associated Press',
   'title': 'House ethics panel finds Florida Rep. Cherfilus-McCormick committed 25 violations',
   'description': 'The House Ethics Committee has found Democratic congresswoman Sheila Cherfilus-McCormick of Florida committed numerous violations of House rules and ethics standards',
   'url': 'https://abcnews.com/US/wireStory/house-ethics-panel-finds-florida-congresswoman-cherfilus-mccormick-131468968',
   'urlToImage': 'https://i.abcnewsfe.com/a/1ffe5e98-bccf-44b8-96da-1c78d25e6c97/wirestory_516fe4e2159beda8c8576c736547b53d_16x9.jpg?w=1600',
   'publishedAt': '2026-03-27T14:11:28Z',
   'content': 'WASHINGTON -- The House Ethics Committee found Friday that Democratic Rep. Sheila Cherfilus-McCormick of Florida had committed numerous violations of House rules and ethics standards, a ruling that c… [+1484 chars]'},
  {'source': {'id': None, 'name': 'Android Central'},
   'author': 'patrick.farmer@futurenet.com (Patrick Farmer) , Patrick Farmer',
   'title': "Heads up! The Galaxy Watch 8 Classic just scored a $130 discount during Amazon's Big Spring Sale",
   'description': "Amazon's Big Spring Sale is live, and you can already score a straight 26% off the Galaxy Watch 8 Classic if you place your order today.",
   'url': 'https://www.androidcentral.com/wearables/samsung-galaxy-watch/heads-up-the-galaxy-watch-8-classic-just-scored-a-usd130-discount-during-amazons-big-spring-sale',
   'urlToImage': 'https://cdn.mos.cms.futurecdn.net/JJvqnaStEhfDsFrJVNRjL8-2560-80.jpg',
   'publishedAt': '2026-03-26T19:49:15Z',
   'content': "The Big Spring Sale is in full swing, and if you were hoping to take advantage of one of Amazon's many smartwatch deals, there's one discount that deserves some extra attention.\xa0\r\nThe Galaxy Watch 8 … [+1976 chars]"},
  {'source': {'id': None, 'name': 'Vox'},
   'author': 'Bryan Walsh',
   'title': 'The most successful health campaign in modern history',
   'description': 'How old am I? Old enough to have flown on planes that had ashtrays in the armrests. Old enough to remember restaurants with smoking sections separated from the nonsmoking section by, essentially, nothing. Old enough to remember when “smoking or non” was a que…',
   'url': 'https://www.vox.com/future-perfect/484165/smoking-tobacco-cancer-health-centers-for-disease-control',
   'urlToImage': 'https://platform.vox.com/wp-content/uploads/sites/2/2026/03/GettyImages-2209397059.jpg?quality=90&strip=all&crop=0%2C10.732984293194%2C100%2C78.534031413613&w=1200',
   'publishedAt': '2026-03-27T20:47:31Z',
   'content': 'How old am I? Old enough to have flown on planes that had ashtrays in the armrests. Old enough to remember restaurants with smoking sections separated from the nonsmoking section by, essentially, not… [+8893 chars]'},
  {'source': {'id': None, 'name': 'Fast Company'},
   'author': 'Heidi Mitchell',
   'title': 'The most innovative companies in wellness and personal care for 2026',
   'description': 'This year’s most innovative companies in wellness and personal care extend the category’s traditional definition in various ways. One is by focusing on community, which is inextricably linked to our health.\n\n\n\nDiplo’s Run Club, led by the eponymous globe-trot…',
   'url': 'https://www.fastcompany.com/91497320/wellness-personal-care-most-innovative-companies-2026-diplos-run-club-diplo-daxko-athletic-clubs-rally-hyperice-helight-gruns-gruns-scarlet-reddrop-willow-innovations',
   'urlToImage': 'https://images.fastcompany.com/image/upload/f_webp,q_auto,c_fit/wp-cms-2/2026/03/p-1b-2026-MIC-sectors-wellness-and-personal-care.jpg',
   'publishedAt': '2026-03-24T11:00:00Z',
   'content': 'This years most innovative companies in wellness and personal care extend the categorys traditional definition in various ways. One is by focusing on community, which is inextricably linked to our he… [+3308 chars]'},
  {'source': {'id': None, 'name': 'Grist'},
   'author': 'Zoya Teirstein',
   'title': 'The frantic, high-tech fight to stop climate-fueled dengue fever',
   'description': 'Scientists in Brazil and Peru may have found a way to beat mosquitoes at their own game. The U.S. may soon need to do the same.',
   'url': 'https://grist.org/health/the-fight-to-stop-climate-fueled-dengue-fever-mosquitoes/',
   'urlToImage': 'https://grist.org/wp-content/uploads/2026/03/dengue-final-2000x1125-1.jpg?quality=75&strip=all',
   'publishedAt': '2026-03-25T08:45:00Z',
   'content': 'This story was produced by Grist and co-published with Salud con lupa. It is part of the Grist series Vital Signs, exploring the ways climate change affects your health. This reporting initiative is … [+28077 chars]'},
  {'source': {'id': None, 'name': 'NPR'},
   'author': 'Julia Haney',
   'title': 'Crossing the line: Emotional abuse in college sports',
   'description': 'Researchers have found that athletes experience emotional abuse more than any other form of harm. Some athletes maintain that this kind of abuse by coaches can cause lasting, even irreparable damage.',
   'url': 'https://www.npr.org/2026/03/28/g-s1-114976/crossing-the-line-emotional-abuse-in-college-sports-marta-marija-galic',
   'urlToImage': 'https://npr.brightspotcdn.com/dims3/default/strip/false/crop/5313x2986+20+8/resize/1400/quality/85/format/jpeg/?url=http%3A%2F%2Fnpr-brightspot.s3.amazonaws.com%2Fe0%2F48%2Fa2cacfaf47d88ffc354c4db835ba%2Frebeccawang-santospiece-color-npr.jpg',
   'publishedAt': '2026-03-28T10:00:00Z',
   'content': 'To prepare herself for basketball practice, Marta Galic said, she spent a lot of time in the bathroom. She would splash cold water on her face, practice the Superman pose in the mirror and make sure … [+18974 chars]'},
  {'source': {'id': 'nbc-news', 'name': 'NBC News'},
   'author': 'Erika Edwards',
   'title': 'Covid and flu shots in limbo as Trump administration mulls appeal over vaccine panel',
   'description': 'After a federal judge blocked Health Secretary Robert F. Kennedy Jr.’s vaccine policies, the Justice Department has yet to appeal the decision — and ultimately may not.',
   'url': 'https://www.nbcnews.com/health/health-news/covid-flu-shots-limbo-trump-rfk-jr-vaccine-panel-appeal-rcna265131',
   'urlToImage': 'https://media-cldnry.s-nbcnews.com/image/upload/t_nbcnews-fp-1200-630,f_auto,q_auto:best/rockcms/2026-02/260218-moderna-rs-59fb4f.jpg',
   'publishedAt': '2026-03-27T15:14:23Z',
   'content': 'More than a week after a federal judge blocked Health and Human Services Secretary Robert F. Kennedy Jr.s overhaul of both the nations childhood vaccine schedule and a key vaccine advisory committee,… [+5242 chars]'},
  {'source': {'id': None, 'name': 'Jezebel'},
   'author': 'Danielle Han',
   'title': 'Sorry, What Did You Say RFK Jr. Did to a Dead Raccoon’s Penis?',
   'description': "The only thing the guy in charge of our country's health and well-being loves more than spreading measles is mutilating dead animals.",
   'url': 'https://www.jezebel.com/sorry-what-did-you-say-rfk-jr-did-to-a-raccoons-penis',
   'urlToImage': 'https://img.pastemagazine.com/wp-content/juploads/2026/03/Untitled-design-2-2.jpg',
   'publishedAt': '2026-03-24T12:49:59Z',
   'content': 'Its impossible to imagine a world without Robert F. Kennedy Jr.not just for launching the U.S. back to 1905, where everyone died of measles, but because every third headline about him is the most twi… [+2040 chars]'},
  {'source': {'id': 'nbc-news', 'name': 'NBC News'},
   'author': 'Erika Edwards',
   'title': 'Trump is expected to name a new CDC head. ‘We don’t need a TV personality," one expert said.',
   'description': 'As the Trump administration prepares to nominate a new director of the CDC, insiders say they worry the nominee will only further undermine trust in the nation’s top health agency.',
   'url': 'https://www.nbcnews.com/health/health-news/trump-cdc-director-nominate-vaccination-measles-rcna261938',
   'urlToImage': 'https://media-cldnry.s-nbcnews.com/image/upload/t_nbcnews-fp-1200-630,f_auto,q_auto:best/rockcms/2025-12/251201-cdc-mn-1300-5a5092.jpg',
   'publishedAt': '2026-03-24T21:39:26Z',
   'content': 'As the Trump administration prepares to nominate a new director of the Centers for Disease Control and Prevention, insiders say they worry the nominee will only further undermine trust in the nations… [+6153 chars]'},
  {'source': {'id': None, 'name': 'Github.com'},
   'author': 'CronusL-1141',
   'title': 'AI Team OS – Turn Claude Code into a Self-Managing AI Team',
   'description': 'AI Team OS — Multi-Agent Team Operating System for Claude Code. 40+ MCP tools, 22 agent templates, task wall, meeting system, dashboard. - CronusL-1141/AI-company',
   'url': 'https://github.com/CronusL-1141/AI-company',
   'urlToImage': 'https://opengraph.githubassets.com/1af14536054776a5a3f9b0ef5b9a29291797d25b5c775f3f2f282cfc9846f1f7/CronusL-1141/AI-company',
   'publishedAt': '2026-03-21T09:38:23Z',
   'content': "English | \r\nAI Team OS turns Claude Code into a self-driving AI company.\r\nYou're the Chairman. AI is the CEO. Set the vision the system executes, learns, and evolves autonomously.\r\nEvery AI coding as… [+15620 chars]"},
  {'source': {'id': None, 'name': 'GSMArena.com'},
   'author': 'Ro',
   'title': 'Perplexity can now answer medical questions based on your Apple Health data',
   'description': "Perplexity announced Perplexity Health, a feature that's specifically designed to answer medical questions in the most medically accurate and evidence-based way possible. The feature aggregates health data from different apps, devices and platforms. The AI as…",
   'url': 'https://www.gsmarena.com/perplexity_can_now_answer_medical_questions_based_on_your_apple_health_data-news-72055.php',
   'urlToImage': 'https://fdn.gsmarena.com/imgroot/news/26/03/perplexity-ai-apple-health/-952x498w6/gsmarena_000.jpg',
   'publishedAt': '2026-03-21T15:27:02Z',

In [8]:
df = pd.DataFrame(all_articles['articles'])
df

,source,author,title,description,url,urlToImage,publishedAt,content
0,"{'id': None, 'name': 'Gizmodo.com'}",Ed Cara,"Finally, Some Good News in the Fight Against Lyme Disease","Scientists found that the experimental vaccine was more than 70% effective at preventing Lyme disease in a trial of nearly 10,000 volunteers.",https://gizmodo.com/finally-some-good-news-in-the-fight-against-lyme-disease-2000737417,https://gizmodo.com/app/uploads/2021/11/f2d874f6239357ae44984bcae121ed56.jpg,2026-03-24T19:35:35Z,"Ticks and the many diseases they can spread to people are a growing public health threat. With any luck, though, humanity may soon have a new weapon to use against the dreaded bloodsucking menace. A … [+4580 chars]"
1,"{'id': None, 'name': 'nj.com'}",Steve Strunsky,Closed Catholic school getting a new purpose in crowded section of N.J.’s largest city,"Details of the school’s projected opening date, grade configuration, cost and other aspects. would be made public during a special meeting at 5 p.m. on March...",https://www.nj.com/essex/2026/03/newark-plans-new-school-in-crowded-ironbound-section-on-site-of-shuttered-catholic-school.html,https://s.yimg.com/ny/api/res/1.2/ixkGljWVL3jaFAYti6DobA--/YXBwaWQ9aGlnaGxhbmRlcjt3PTEyMDA7aD05MDA7Y2Y9d2VicA--/https://media.zenfs.com/en/nj_com_articles_950/4d78b16399dd7696152f78e2f4b9c112,2026-03-22T15:00:46Z,"The Newark Board of Education president said the district plans to open a new school on the site of a shuttered former parochial school in the citys Ironbound section, using a lease-purchase agreemen… [+6313 chars]"
2,"{'id': None, 'name': 'Scientific American'}","Kendra Pierre-Louis, Andrea Thompson, Sushmita Pathak, Alex Sugiura","Spring heat dome, a blow to RFK, Jr.’s health agenda, SpaceX Starlink milestone","An unseasonal heat dome over parts of the U.S., a federal court ruling that blocks the CDC’s recent change to its recommended childhood vaccine schedule, new research on unsafe levels of lead in fast fashion",https://www.scientificamerican.com/podcast/episode/spring-heat-dome-a-blow-to-rfk-jr-s-health-agenda-spacex-starlink-milestone/,https://static.scientificamerican.com/dam/m/3557c42768a73913/original/2603_SQ_MON_MARCH_23.png?m=1774038209.608&w=1200,2026-03-23T10:00:00Z,"Kendra Pierre-Louis: For Scientific American’s Science Quickly, I’m Kendra Pierre-Louis, in for Rachel Feltman. You’re listening to our weekly science news roundup.\r\nIf you live in much of California… [+10640 chars]"
3,"{'id': None, 'name': 'NPR'}",Aaron Bolton,A $50 billion fund to help rural hospitals could actually lead to closures and cuts,"States are rolling out plans for their share of a $50 billion fund established by Congress to improve rural health care. In some states, the money may provoke rural hospitals to cut services.",https://www.npr.org/2026/03/26/nx-s1-5760925/rural-health-transformation-fund-hospitals-montana,https://npr.brightspotcdn.com/dims3/default/strip/false/crop/4032x2268+0+378/resize/1400/quality/85/format/jpeg/?url=http%3A%2F%2Fnpr-brightspot.s3.amazonaws.com%2Fc3%2Ffe%2F0b795951485a84cd8ec7ee284ea2%2Frht-03.jpg,2026-03-26T09:00:00Z,"The emergency department at Big Sandy Medical Center in Montana is just one room, with a single curtain between two beds.\r\nIt's one of the many parts of the 25-bed rural hospital that need updating, … [+8493 chars]"
4,"{'id': None, 'name': 'Gizmodo.com'}",James Pero,Oura’s Next Smart Ring Just Leaked a Year Early,"If these images are real, this is the first look at the Oura Ring 5.",https://gizmodo.com/ouras-next-smart-ring-just-leaked-a-year-early-2000737357,https://gizmodo.com/app/uploads/2025/11/Oura-Ring-4-Ceramic-review-05-1200x675.jpg,2026-03-24T15:40:39Z,"The Oura Ring 5 isn’t expected to launch for another year, but a purported leak might have given us an early glimpse of what to expect. Android Headlines claims to have obtained renders of the new he… [+2151 chars]"
...,...,...,...,...,...,...,...,...
89,"{'id': None, 'name': 'Nesbitt.io'}",Andrew Nesbitt,How to Attract AI Bots to Your Open Source Project,A practical guide to getting the engagement your project deserves.,https://nesbitt.io/2026/03/21/how-to-attract-ai-bots-to-your-open-source-project.html,https://nesbitt.io/images/boxes.png,2026-03-21T20:58:01Z,I complained on Mastodon about not getting any AI-authored PRs on my open source projects. Mauro Pompilio responded by using Claude to write this post and opening a pull request to add it to my blog.… [+8884 chars]
90,"{'id': None, 'name': 'Grist'}",Miacel Spotted Elk,Modern agriculture is collapsing under climate change. Indigenous farming has answers.,A new global review reveals a critical “gap between advocacy and evidence” when it comes to scaling traditional agriculture to fight climate change.,https://grist.org/indigenous/modern-agriculture-is-collapsing-under-climate-change-indigenous-farming-has-answers/,https://grist.org/wp-content/uploads/2026/03/GettyImages-1404579129_a21a80.jpg?quality=75&strip=all,2026-03-26T08:15:00Z,"In the last five years, Indigenous agriculture has received attention in academia as an alternative model, though on a smaller scale, to modern farming systems. Research has shown that some tradition… [+4418 chars]"
91,"{'id': None, 'name': 'Science Daily'}",NaN,Scientists found a bug that generates its own heat in freezing cold,"Snow flies have an unexpected way of surviving freezing temperatures. They produce antifreeze proteins to block ice formation and can even generate their own heat. Scientists also found that their genes are unusually unique, and they feel less cold-related pa…",https://www.sciencedaily.com/releases/2026/03/260326011455.htm,https://www.sciencedaily.com/images/1920/snow-fly-chionea-alexandriana.webp,2026-03-26T05:26:31Z,"Snow flies might seem like ordinary insects, but their survival strategy is anything but typical.In a new study, scientists at Northwestern University investigated how these small, wingless insects, … [+6886 chars]"
92,"{'id': None, 'name': 'The Gadgeteer'}",Rei Padla,Ultrahuman’s Banned Smart Ring Is Back With a Point to Prove,"The Ultrahuman Ring Pro is officially available for pre-order in the United States, marking the end of a months-long import ban that kept the Indian smart ring maker out of its biggest market. US Customs and Border Protection cleared the device, and Ultrahuma…",https://the-gadgeteer.com/2026/03/25/ultrahumans-banned-smart-ring-is-back-with-a-point-to-prove/,https://the-gadgeteer.com/wp-content/uploads/2026/03/Ultrahuman-Ring-Pro-Mobile.jpg,2026-03-25T07:00:43Z,"If you buy something from a link in this article, we may earn a commission. Learn more\r\nThe Ultrahuman Ring Pro is officially available for pre-order in the United States, marking the end of a months… [+6724 chars]"
93,"{'id': None, 'name': 'Juancole.com'}",Truthdig,"U.S. Sanctions, War and Climate Inflict Heavy Mental Health Toll in Afghanistan","Across Afghanistan, thousands of young people, including university graduates and skilled workers, are struggling with prolonged unemployment.",https://www.juancole.com/2026/03/sanctions-climate-afghanistan.html,https://media.juancole.com/images/2024/08/informed-comment-logo-transparent-740x400-1.png,2026-03-28T04:04:45Z,"Editor’s Note: Women are barred from working as photographers in Afghanistan. As a result, Truthdig opted to use a pseudonym for the photographers to protect their identities.\r\nThe street market in t… [+11850 chars]"

In [9]:
df = df.rename(columns={
    "source": "Source Meta Data",
    "author": "Source",
    "publishedAt": "Date",
    "url": "URL",
    "urlToImage": "Image URL"
})

df["Query Domain"] = QUERY_CONFIGS[list_num]["query_domain"]

df

,Source Meta Data,Source,title,description,URL,Image URL,Date,content,Query Domain
0,"{'id': None, 'name': 'Gizmodo.com'}",Ed Cara,"Finally, Some Good News in the Fight Against Lyme Disease","Scientists found that the experimental vaccine was more than 70% effective at preventing Lyme disease in a trial of nearly 10,000 volunteers.",https://gizmodo.com/finally-some-good-news-in-the-fight-against-lyme-disease-2000737417,https://gizmodo.com/app/uploads/2021/11/f2d874f6239357ae44984bcae121ed56.jpg,2026-03-24T19:35:35Z,"Ticks and the many diseases they can spread to people are a growing public health threat. With any luck, though, humanity may soon have a new weapon to use against the dreaded bloodsucking menace. A … [+4580 chars]",health
1,"{'id': None, 'name': 'nj.com'}",Steve Strunsky,Closed Catholic school getting a new purpose in crowded section of N.J.’s largest city,"Details of the school’s projected opening date, grade configuration, cost and other aspects. would be made public during a special meeting at 5 p.m. on March...",https://www.nj.com/essex/2026/03/newark-plans-new-school-in-crowded-ironbound-section-on-site-of-shuttered-catholic-school.html,https://s.yimg.com/ny/api/res/1.2/ixkGljWVL3jaFAYti6DobA--/YXBwaWQ9aGlnaGxhbmRlcjt3PTEyMDA7aD05MDA7Y2Y9d2VicA--/https://media.zenfs.com/en/nj_com_articles_950/4d78b16399dd7696152f78e2f4b9c112,2026-03-22T15:00:46Z,"The Newark Board of Education president said the district plans to open a new school on the site of a shuttered former parochial school in the citys Ironbound section, using a lease-purchase agreemen… [+6313 chars]",health
2,"{'id': None, 'name': 'Scientific American'}","Kendra Pierre-Louis, Andrea Thompson, Sushmita Pathak, Alex Sugiura","Spring heat dome, a blow to RFK, Jr.’s health agenda, SpaceX Starlink milestone","An unseasonal heat dome over parts of the U.S., a federal court ruling that blocks the CDC’s recent change to its recommended childhood vaccine schedule, new research on unsafe levels of lead in fast fashion",https://www.scientificamerican.com/podcast/episode/spring-heat-dome-a-blow-to-rfk-jr-s-health-agenda-spacex-starlink-milestone/,https://static.scientificamerican.com/dam/m/3557c42768a73913/original/2603_SQ_MON_MARCH_23.png?m=1774038209.608&w=1200,2026-03-23T10:00:00Z,"Kendra Pierre-Louis: For Scientific American’s Science Quickly, I’m Kendra Pierre-Louis, in for Rachel Feltman. You’re listening to our weekly science news roundup.\r\nIf you live in much of California… [+10640 chars]",health
3,"{'id': None, 'name': 'NPR'}",Aaron Bolton,A $50 billion fund to help rural hospitals could actually lead to closures and cuts,"States are rolling out plans for their share of a $50 billion fund established by Congress to improve rural health care. In some states, the money may provoke rural hospitals to cut services.",https://www.npr.org/2026/03/26/nx-s1-5760925/rural-health-transformation-fund-hospitals-montana,https://npr.brightspotcdn.com/dims3/default/strip/false/crop/4032x2268+0+378/resize/1400/quality/85/format/jpeg/?url=http%3A%2F%2Fnpr-brightspot.s3.amazonaws.com%2Fc3%2Ffe%2F0b795951485a84cd8ec7ee284ea2%2Frht-03.jpg,2026-03-26T09:00:00Z,"The emergency department at Big Sandy Medical Center in Montana is just one room, with a single curtain between two beds.\r\nIt's one of the many parts of the 25-bed rural hospital that need updating, … [+8493 chars]",health
4,"{'id': None, 'name': 'Gizmodo.com'}",James Pero,Oura’s Next Smart Ring Just Leaked a Year Early,"If these images are real, this is the first look at the Oura Ring 5.",https://gizmodo.com/ouras-next-smart-ring-just-leaked-a-year-early-2000737357,https://gizmodo.com/app/uploads/2025/11/Oura-Ring-4-Ceramic-review-05-1200x675.jpg,2026-03-24T15:40:39Z,"The Oura Ring 5 isn’t expected to launch for another year, but a purported leak might have given us an early glimpse of what to expect. Android Headlines claims to have obtained renders of the new he… [+2151 chars]",health
...,...,...,...,...,...,...,...,...,...
89,"{'id': None, 'name': 'Nesbitt.io'}",Andrew Nesbitt,How to Attract AI Bots to Your Open Source Project,A practical guide to getting the engagement your project deserves.,https://nesbitt.io/2026/03/21/how-to-attract-ai-bots-to-your-open-source-project.html,https://nesbitt.io/images/boxes.png,2026-03-21T20:58:01Z,I complained on Mastodon about not getting any AI-authored PRs on my open source projects. Mauro Pompilio responded by using Claude to write this post and opening a pull request to add it to my blog.… [+8884 chars],health
90,"{'id': None, 'name': 'Grist'}",Miacel Spotted Elk,Modern agriculture is collapsing under climate change. Indigenous farming has answers.,A new global review reveals a critical “gap between advocacy and evidence” when it comes to scaling traditional agriculture to fight climate change.,https://grist.org/indigenous/modern-agriculture-is-collapsing-under-climate-change-indigenous-farming-has-answers/,https://grist.org/wp-content/uploads/2026/03/GettyImages-1404579129_a21a80.jpg?quality=75&strip=all,2026-03-26T08:15:00Z,"In the last five years, Indigenous agriculture has received attention in academia as an alternative model, though on a smaller scale, to modern farming systems. Research has shown that some tradition… [+4418 chars]",health
91,"{'id': None, 'name': 'Science Daily'}",NaN,Scientists found a bug that generates its own heat in freezing cold,"Snow flies have an unexpected way of surviving freezing temperatures. They produce antifreeze proteins to block ice formation and can even generate their own heat. Scientists also found that their genes are unusually unique, and they feel less cold-related pa…",https://www.sciencedaily.com/releases/2026/03/260326011455.htm,https://www.sciencedaily.com/images/1920/snow-fly-chionea-alexandriana.webp,2026-03-26T05:26:31Z,"Snow flies might seem like ordinary insects, but their survival strategy is anything but typical.In a new study, scientists at Northwestern University investigated how these small, wingless insects, … [+6886 chars]",health
92,"{'id': None, 'name': 'The Gadgeteer'}",Rei Padla,Ultrahuman’s Banned Smart Ring Is Back With a Point to Prove,"The Ultrahuman Ring Pro is officially available for pre-order in the United States, marking the end of a months-long import ban that kept the Indian smart ring maker out of its biggest market. US Customs and Border Protection cleared the device, and Ultrahuma…",https://the-gadgeteer.com/2026/03/25/ultrahumans-banned-smart-ring-is-back-with-a-point-to-prove/,https://the-gadgeteer.com/wp-content/uploads/2026/03/Ultrahuman-Ring-Pro-Mobile.jpg,2026-03-25T07:00:43Z,"If you buy something from a link in this article, we may earn a commission. Learn more\r\nThe Ultrahuman Ring Pro is officially available for pre-order in the United States, marking the end of a months… [+6724 chars]",health
93,"{'id': None, 'name': 'Juancole.com'}",Truthdig,"U.S. Sanctions, War and Climate Inflict Heavy Mental Health Toll in Afghanistan","Across Afghanistan, thousands of young people, including university graduates and skilled workers, are struggling with prolonged unemployment.",https://www.juancole.com/2026/03/sanctions-climate-afghanistan.html,https://media.juancole.com/images/2024/08/informed-comment-logo-transparent-740x400-1.png,2026-03-28T04:04:45Z,"Editor’s Note: Women are barred from working as photographers in Afghanistan. As a result, Truthdig opted to use a pseudonym for the photographers to protect their identities.\r\nThe street market in t… [+11850 chars]",health

In [10]:
def clean_base_sentence(text: str) -> str:
    if not isinstance(text, str):
        return text

    # Decode HTML entities (e.g., &lt;li&gt;)
    text = html.unescape(text)

    # Remove UL/LI tags but keep structure
    text = re.sub(r"</?ul>", "", text)
    text = re.sub(r"<li>", "", text)
    text = re.sub(r"</li>", " ", text)

    # Normalize newlines and carriage returns → space
    text = re.sub(r"[\r\n]+", " ", text)

    # Collapse multiple spaces
    text = re.sub(r"\s+", " ", text)

    return text.strip()

In [11]:
def build_prediction_dataframe(df, char_limit=500):
    """
    Builds a sentence-level dataframe from a preprocessed NewsAPI DataFrame.
    """

    df = df.reset_index(drop=True).copy()
    df["article_id"] = df.index

    prediction_keywords = [
        "expected", "forecast", "forecasted", "forecasting",
        "forecast estimate", "forecasted outcome", "projected",
        "projection", "predict", "predicted", "estimate",
        "expectation", "anticipation", "prognosis",
        "speculation", "foretelling", "prophecy", "guess"
    ]

    pattern = r"\b(" + "|".join(map(re.escape, prediction_keywords)) + r")\b"

    df["prediction_visible"] = (
        (
            df["title"].fillna("") +
            df["description"].fillna("") +
            df["content"].fillna("")
        )
        .str.lower()
        .str[:char_limit]
        .str.contains(pattern, regex=True)
    ).astype(int)

    parts = []
    for field, order in [("title", 0), ("description", 1), ("content", 2)]:
        tmp = df.copy()
        tmp["Base Sentence"] = tmp[field]
        tmp["Source_Field"] = field
        tmp["field_order"] = order
        parts.append(tmp)

    long_df = pd.concat(parts, ignore_index=True)

    # ✅ CLEAN TEXT FIRST
    long_df["Base Sentence"] = long_df["Base Sentence"].apply(clean_base_sentence)

    # ✅ SPLIT INTO SENTENCES HERE (USING self.nlp)
    sfe = SpacyFeatureExtraction(long_df, "Base Sentence")
    long_df = sfe.split_into_sentences()

    # ✅ LABEL PER SENTENCE (NOT PER BLOCK)
    long_df["Sentence Label"] = (
        long_df["Base Sentence"]
        .str.lower()
        .str.contains(pattern, regex=True)
        .astype(int)
    )

    long_df["Human Annotation"] = ""
    long_df["Human Reasoning"] = ""

    priority_cols = [
        "Base Sentence", "Sentence Label",
        "Human Annotation", "Human Reasoning",
        "Source", "Date"
    ]
    priority_cols = [c for c in priority_cols if c in long_df.columns]
    remaining_cols = [c for c in long_df.columns if c not in priority_cols]

    return long_df[priority_cols + remaining_cols]

In [12]:
final_df = build_prediction_dataframe(df)
final_df.head(3)

/var/folders/78/9z0b45fx1xqbwxh8vk97lcfh0000gn/T/ipykernel_56648/1523799737.py:27: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  .str.contains(pattern, regex=True)
/var/folders/78/9z0b45fx1xqbwxh8vk97lcfh0000gn/T/ipykernel_56648/1523799737.py:51: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  .str.contains(pattern, regex=True)

,Base Sentence,Sentence Label,Human Annotation,Human Reasoning,Source,Date,Source Meta Data,title,description,URL,Image URL,content,Query Domain,article_id,prediction_visible,Source_Field,field_order
0,"Finally, Some Good News in the Fight Against Lyme Disease",0,,,Ed Cara,2026-03-24T19:35:35Z,"{'id': None, 'name': 'Gizmodo.com'}","Finally, Some Good News in the Fight Against Lyme Disease","Scientists found that the experimental vaccine was more than 70% effective at preventing Lyme disease in a trial of nearly 10,000 volunteers.",https://gizmodo.com/finally-some-good-news-in-the-fight-against-lyme-disease-2000737417,https://gizmodo.com/app/uploads/2021/11/f2d874f6239357ae44984bcae121ed56.jpg,"Ticks and the many diseases they can spread to people are a growing public health threat. With any luck, though, humanity may soon have a new weapon to use against the dreaded bloodsucking menace. A … [+4580 chars]",health,0,0,title,0
1,Closed Catholic school getting a new purpose in crowded section of N.J.’s largest city,0,,,Steve Strunsky,2026-03-22T15:00:46Z,"{'id': None, 'name': 'nj.com'}",Closed Catholic school getting a new purpose in crowded section of N.J.’s largest city,"Details of the school’s projected opening date, grade configuration, cost and other aspects. would be made public during a special meeting at 5 p.m. on March...",https://www.nj.com/essex/2026/03/newark-plans-new-school-in-crowded-ironbound-section-on-site-of-shuttered-catholic-school.html,https://s.yimg.com/ny/api/res/1.2/ixkGljWVL3jaFAYti6DobA--/YXBwaWQ9aGlnaGxhbmRlcjt3PTEyMDA7aD05MDA7Y2Y9d2VicA--/https://media.zenfs.com/en/nj_com_articles_950/4d78b16399dd7696152f78e2f4b9c112,"The Newark Board of Education president said the district plans to open a new school on the site of a shuttered former parochial school in the citys Ironbound section, using a lease-purchase agreemen… [+6313 chars]",health,1,1,title,0
2,"Spring heat dome, a blow to RFK, Jr.’s health agenda, SpaceX Starlink milestone",0,,,"Kendra Pierre-Louis, Andrea Thompson, Sushmita Pathak, Alex Sugiura",2026-03-23T10:00:00Z,"{'id': None, 'name': 'Scientific American'}","Spring heat dome, a blow to RFK, Jr.’s health agenda, SpaceX Starlink milestone","An unseasonal heat dome over parts of the U.S., a federal court ruling that blocks the CDC’s recent change to its recommended childhood vaccine schedule, new research on unsafe levels of lead in fast fashion",https://www.scientificamerican.com/podcast/episode/spring-heat-dome-a-blow-to-rfk-jr-s-health-agenda-spacex-starlink-milestone/,https://static.scientificamerican.com/dam/m/3557c42768a73913/original/2603_SQ_MON_MARCH_23.png?m=1774038209.608&w=1200,"Kendra Pierre-Louis: For Scientific American’s Science Quickly, I’m Kendra Pierre-Louis, in for Rachel Feltman. You’re listening to our weekly science news roundup.\r\nIf you live in much of California… [+10640 chars]",health,2,0,title,0

In [13]:
predictions_df = final_df[final_df["Sentence Label"] == 1]
predictions_df.head(3)

,Base Sentence,Sentence Label,Human Annotation,Human Reasoning,Source,Date,Source Meta Data,title,description,URL,Image URL,content,Query Domain,article_id,prediction_visible,Source_Field,field_order
21,Trump is expected to name a new CDC head.,1,,,Erika Edwards,2026-03-24T21:39:26Z,"{'id': 'nbc-news', 'name': 'NBC News'}","Trump is expected to name a new CDC head. ‘We don’t need a TV personality,"" one expert said.","As the Trump administration prepares to nominate a new director of the CDC, insiders say they worry the nominee will only further undermine trust in the nation’s top health agency.",https://www.nbcnews.com/health/health-news/trump-cdc-director-nominate-vaccination-measles-rcna261938,"https://media-cldnry.s-nbcnews.com/image/upload/t_nbcnews-fp-1200-630,f_auto,q_auto:best/rockcms/2025-12/251201-cdc-mn-1300-5a5092.jpg","As the Trump administration prepares to nominate a new director of the Centers for Disease Control and Prevention, insiders say they worry the nominee will only further undermine trust in the nations… [+6153 chars]",health,19,1,title,0
81,"Employee Is Turned Down For The Role Of Supervisor, But She’s Still Expected To Do Tasks A Supervisor Should Do",1,,,Jayne Elliott,2026-03-24T18:55:05Z,"{'id': None, 'name': 'Twistedsifter.com'}","Employee Is Turned Down For The Role Of Supervisor, But She’s Still Expected To Do Tasks A Supervisor Should Do",Jaded employees won't go above and beyond.,http://twistedsifter.com/2026/03/employee-is-turned-down-for-the-role-of-supervisor-but-shes-still-expected-to-do-tasks-a-supervisor-should-do/,https://twistedsifter.com/wp-content/uploads/2026/02/Twisted-Sifter-17.png,"Shutterstock/Reddit\r\nImagine working for a company for awhile and hoping to get promoted to supervisor. If you were turned down for the promotion, would you be willing to take on extra tasks to be a … [+2785 chars]",health,72,1,title,0
93,"Mets projected lineup, rotation and keys to winning NL East",1,,,"Andrew Tredinnick, NorthJersey.com",2026-03-24T08:04:55Z,"{'id': None, 'name': 'NorthJersey.com'}","Mets projected lineup, rotation and keys to winning NL East",The Mets begin their 2026 'redemption tour' on Opening Day after a disappointing 2025 season. See the expected new lineup and rotation.,https://www.northjersey.com/story/sports/mlb/mets/2026/03/24/ny-mets-2026-preview-opening-day-lineup-rotation-predictions/89249791007/,https://s.yimg.com/ny/api/res/1.2/zsxORNdWfVeSB.BDPAT_0Q--/YXBwaWQ9aGlnaGxhbmRlcjt3PTEyMDA7aD04MDA7Y2Y9d2VicA--/https://media.zenfs.com/en/the-bergen-record/cd3358ba16b0cc83e81a48f238e60174,"The Mets' redemption tour begins on Thursday afternoon after a major bust in the 2025 season.\r\nAfter falling one win short of a playoff spot, Opening Day marks the start of a new era for the Mets aft… [+8944 chars]",health,82,1,title,0

In [14]:
predictions_df["Base Sentence"] = predictions_df["Base Sentence"].apply(clean_base_sentence)
predictions_df.head(3)

,Base Sentence,Sentence Label,Human Annotation,Human Reasoning,Source,Date,Source Meta Data,title,description,URL,Image URL,content,Query Domain,article_id,prediction_visible,Source_Field,field_order
21,Trump is expected to name a new CDC head.,1,,,Erika Edwards,2026-03-24T21:39:26Z,"{'id': 'nbc-news', 'name': 'NBC News'}","Trump is expected to name a new CDC head. ‘We don’t need a TV personality,"" one expert said.","As the Trump administration prepares to nominate a new director of the CDC, insiders say they worry the nominee will only further undermine trust in the nation’s top health agency.",https://www.nbcnews.com/health/health-news/trump-cdc-director-nominate-vaccination-measles-rcna261938,"https://media-cldnry.s-nbcnews.com/image/upload/t_nbcnews-fp-1200-630,f_auto,q_auto:best/rockcms/2025-12/251201-cdc-mn-1300-5a5092.jpg","As the Trump administration prepares to nominate a new director of the Centers for Disease Control and Prevention, insiders say they worry the nominee will only further undermine trust in the nations… [+6153 chars]",health,19,1,title,0
81,"Employee Is Turned Down For The Role Of Supervisor, But She’s Still Expected To Do Tasks A Supervisor Should Do",1,,,Jayne Elliott,2026-03-24T18:55:05Z,"{'id': None, 'name': 'Twistedsifter.com'}","Employee Is Turned Down For The Role Of Supervisor, But She’s Still Expected To Do Tasks A Supervisor Should Do",Jaded employees won't go above and beyond.,http://twistedsifter.com/2026/03/employee-is-turned-down-for-the-role-of-supervisor-but-shes-still-expected-to-do-tasks-a-supervisor-should-do/,https://twistedsifter.com/wp-content/uploads/2026/02/Twisted-Sifter-17.png,"Shutterstock/Reddit\r\nImagine working for a company for awhile and hoping to get promoted to supervisor. If you were turned down for the promotion, would you be willing to take on extra tasks to be a … [+2785 chars]",health,72,1,title,0
93,"Mets projected lineup, rotation and keys to winning NL East",1,,,"Andrew Tredinnick, NorthJersey.com",2026-03-24T08:04:55Z,"{'id': None, 'name': 'NorthJersey.com'}","Mets projected lineup, rotation and keys to winning NL East",The Mets begin their 2026 'redemption tour' on Opening Day after a disappointing 2025 season. See the expected new lineup and rotation.,https://www.northjersey.com/story/sports/mlb/mets/2026/03/24/ny-mets-2026-preview-opening-day-lineup-rotation-predictions/89249791007/,https://s.yimg.com/ny/api/res/1.2/zsxORNdWfVeSB.BDPAT_0Q--/YXBwaWQ9aGlnaGxhbmRlcjt3PTEyMDA7aD04MDA7Y2Y9d2VicA--/https://media.zenfs.com/en/the-bergen-record/cd3358ba16b0cc83e81a48f238e60174,"The Mets' redemption tour begins on Thursday afternoon after a major bust in the 2025 season.\r\nAfter falling one win short of a playoff spot, Opening Day marks the start of a new era for the Mets aft… [+8944 chars]",health,82,1,title,0

In [15]:
predictions_df

,Base Sentence,Sentence Label,Human Annotation,Human Reasoning,Source,Date,Source Meta Data,title,description,URL,Image URL,content,Query Domain,article_id,prediction_visible,Source_Field,field_order
21,Trump is expected to name a new CDC head.,1,,,Erika Edwards,2026-03-24T21:39:26Z,"{'id': 'nbc-news', 'name': 'NBC News'}","Trump is expected to name a new CDC head. ‘We don’t need a TV personality,"" one expert said.","As the Trump administration prepares to nominate a new director of the CDC, insiders say they worry the nominee will only further undermine trust in the nation’s top health agency.",https://www.nbcnews.com/health/health-news/trump-cdc-director-nominate-vaccination-measles-rcna261938,"https://media-cldnry.s-nbcnews.com/image/upload/t_nbcnews-fp-1200-630,f_auto,q_auto:best/rockcms/2025-12/251201-cdc-mn-1300-5a5092.jpg","As the Trump administration prepares to nominate a new director of the Centers for Disease Control and Prevention, insiders say they worry the nominee will only further undermine trust in the nations… [+6153 chars]",health,19,1,title,0
81,"Employee Is Turned Down For The Role Of Supervisor, But She’s Still Expected To Do Tasks A Supervisor Should Do",1,,,Jayne Elliott,2026-03-24T18:55:05Z,"{'id': None, 'name': 'Twistedsifter.com'}","Employee Is Turned Down For The Role Of Supervisor, But She’s Still Expected To Do Tasks A Supervisor Should Do",Jaded employees won't go above and beyond.,http://twistedsifter.com/2026/03/employee-is-turned-down-for-the-role-of-supervisor-but-shes-still-expected-to-do-tasks-a-supervisor-should-do/,https://twistedsifter.com/wp-content/uploads/2026/02/Twisted-Sifter-17.png,"Shutterstock/Reddit\r\nImagine working for a company for awhile and hoping to get promoted to supervisor. If you were turned down for the promotion, would you be willing to take on extra tasks to be a … [+2785 chars]",health,72,1,title,0
93,"Mets projected lineup, rotation and keys to winning NL East",1,,,"Andrew Tredinnick, NorthJersey.com",2026-03-24T08:04:55Z,"{'id': None, 'name': 'NorthJersey.com'}","Mets projected lineup, rotation and keys to winning NL East",The Mets begin their 2026 'redemption tour' on Opening Day after a disappointing 2025 season. See the expected new lineup and rotation.,https://www.northjersey.com/story/sports/mlb/mets/2026/03/24/ny-mets-2026-preview-opening-day-lineup-rotation-predictions/89249791007/,https://s.yimg.com/ny/api/res/1.2/zsxORNdWfVeSB.BDPAT_0Q--/YXBwaWQ9aGlnaGxhbmRlcjt3PTEyMDA7aD04MDA7Y2Y9d2VicA--/https://media.zenfs.com/en/the-bergen-record/cd3358ba16b0cc83e81a48f238e60174,"The Mets' redemption tour begins on Thursday afternoon after a major bust in the 2025 season.\r\nAfter falling one win short of a playoff spot, Opening Day marks the start of a new era for the Mets aft… [+8944 chars]",health,82,1,title,0
108,"Details of the school’s projected opening date, grade configuration, cost and other aspects.",1,,,Steve Strunsky,2026-03-22T15:00:46Z,"{'id': None, 'name': 'nj.com'}",Closed Catholic school getting a new purpose in crowded section of N.J.’s largest city,"Details of the school’s projected opening date, grade configuration, cost and other aspects. would be made public during a special meeting at 5 p.m. on March...",https://www.nj.com/essex/2026/03/newark-plans-new-school-in-crowded-ironbound-section-on-site-of-shuttered-catholic-school.html,https://s.yimg.com/ny/api/res/1.2/ixkGljWVL3jaFAYti6DobA--/YXBwaWQ9aGlnaGxhbmRlcjt3PTEyMDA7aD05MDA7Y2Y9d2VicA--/https://media.zenfs.com/en/nj_com_articles_950/4d78b16399dd7696152f78e2f4b9c112,"The Newark Board of Education president said the district plans to open a new school on the site of a shuttered former parochial school in the citys Ironbound section, using a lease-purchase agreemen… [+6313 chars]",health,1,1,description,1
177,"The administration is expected to soon name a new director, who will have their hands full.",1,,,Pien Huang,2026-03-25T16:01:04Z,"{'id': None, 'name': 'NPR'}",A leadership vacuum adds to strains on the CDC,"Low morale, staff turnover and budget issues have sapped the Centers for Disease Control and Prevention. The administration is expected to soon name a new director, who will have their hands full.",https://www.npr.org/2026/03/25/nx-s1-5760832/cdc-turmoil-director,https://npr.brightspotcdn.com/dims3/default/strip/false/crop/3000x1688+0+156/resize/1400/quality/85/format/jpeg/?url=http%3A%2F%2Fnpr-brightspot.s3.amazonaws.com%2F28%2F97%2F2861ce19409682a37db626377703%2Fgettyimages-457163926.jpg,"The Centers for Disease Control and Prevention is once again searching for a new leader.\r\nDuring the current Trump administration, the embattled agency tasked with protecting the nation's health has … [+14048 chars]",health,41,1,description,1
186,"Months away from the start of a huge shift in disability support for children, the workforce expected to deliver it has concerns about its readiness.",1,,,Nas Campanella and Evan Young,2026-03-27T19:17:36Z,"{'id': 'abc-news-au', 'name': 'ABC News (AU)'}",Do we actually have the workforce to help autistic kids thrive?,"Months away from the start of a huge shift in disability support for children, the workforce expected to deliver it has concerns about its readiness.",https://www.abc.net.au/news/2026-03-28/thriving-kids-therapist-teachers-workforce-questions/106442196,https://live-production.wcms.abc-cdn.net.au/8ffadf5cb72a3c7a3238ec224a438936?impolicy=wcms_watermark_news&cropH=1968&cropW=3499&xPos=3&yPos=0&width=862&height=485&imformat=generic,The workforce expected to deliver the National Disability Insurance Scheme (NDIS) alternative has warned it will fail without the right staff and called for urgent transparency on how the program wil… [+6898 chars],health,48,1,description,1
187,A new nominee for director of the Centers for Disease Control and Prevention is expected to be named this week.,1,,,Pien Huang,2026-03-24T19:59:36Z,"{'id': None, 'name': 'NPR'}",The search for a new CDC director nears a deadline,A new nominee for director of the Centers for Disease Control and Prevention is expected to be named this week. They would inherit a demoralized staff and a public health agency buffeted by change.,https://www.npr.org/2026/03/24/nx-s1-5757471/the-search-for-a-new-cdc-director-nears-a-deadline,https://media.npr.org/include/images/facebook-default-wide-s1400-c85.jpg,A new nominee for director of the Centers for Disease Control and Prevention is expected to be named this week. They would inherit a demoralized staff and a public health agency buffeted by change.,health,49,1,description,1
199,Good Morning America weatherman Sam Champion is sharing a positive forecast about his health.,1,,,Mike Vulpo,2026-03-23T17:45:29Z,"{'id': None, 'name': 'Us Weekly'}",GMA’s Sam Champion Shares Health Update After Heart Procedure,"Good Morning America weatherman Sam Champion is sharing a positive forecast about his health. “Thank you Dr. Stam Lerakis and Dr. Sharma and the WONDERFUL team of nurses at @mountsinaimedicalcenter Fuster Heart Hospital!” Champion, 64, wrote via Instagram on …",https://www.usmagazine.com/celebrity-news/news/gmas-sam-champion-hospitalized-for-health-procedure/,https://www.usmagazine.com/wp-content/uploads/2026/03/gma-sam-champion-hospital2.jpg?crop=0px%2C289px%2C1200px%2C630px&resize=1200%2C630&quality=86&strip=all,Good Morning America weatherman Sam Champion is sharing a positive forecast about his health.\r\n“Thank you Dr. Stam Lerakis and Dr. Sharma and the WONDERFUL team of nurses at @mountsinaimedicalcenter … [+2245 chars],health,55,1,description,1
219,"By closely monitoring fish throughout their lives, researchers found that simple behaviors in midlife—like movement and sleep—can predict lifespan.",1,,,NaN,2026-03-26T11:18:41Z,"{'id': None, 'name': 'Science Daily'}",What you do in midlife could reveal how long you’ll live,"By closely monitoring fish throughout their lives, researchers found that simple behaviors in midlife—like movement and sleep—can predict lifespan. Fish that stayed active and slept mostly at night tended to live longer, while those slowing down earlier lived…",https://www.sciencedaily.com/releases/2026/03/260325005914.htm,https://www.sciencedaily.com/images/1920/man-snoring-sleeping-in-bed.webp,"By the time animals reach midlife, their everyday habits can offer clues about how long they are likely to live.This conclusion comes from a new study supported by the Knight Initiative for Brain Res… [+9898 chars]",health,64,1,description,1
230,"Androgen activity in the male embryonic hindbrain prolongs hindbrain differentiation in male individuals and drives sex differences in the incidence and prognosis of posterior fossa type A (PFA) ependymoma, an aggressive childhood brain tumour.",1,,,"Jiao Zhang, Winnie Ong, Alexandra Rasnitsyn, Ricardo Daniel Gonzalez, Rodrigo Lopez Gutierrez, Polina Balin, Amr Saadeldin, Xiaochong Wu, Maria C. Vladoiu, Vicente Santa-Maria Lopez, Fernando Gonzalez-Salinas, Navneesh Yadav, Dinesh Mohanakrishnan, Kannan Boosi Narayana Rao, Raja Gopal Reddy Mooli, Hinda Najem, Sebastian Pacheco, Kaitlin Kharas, Cory Richman, David Przelicki, Evan Y. Wang, Haipeng Su, Rachel Naomi Curry, Runze Yang, Michelle Masayo Kameda-Smith, Bryn Livingston, David Scott, Zaili Luo, Mingyang Xia, Namal Abeysundara, Anders W. Erickson, Ncedile Mankahla, Lucas ZhongMing Hu, Chu Pan, Raul Suarez, Ning Huang, Yihao Wu, Hao Wang, Tajana Douglas, Jonelle Pallota, Steven Hébert, Karen Ng, Krystin Mantione, Heather Whetstone, Hassaan Maan, Hussein Lakkis, Juyeun Lee, Sadees...",2026-03-25T00:00:00Z,"{'id': None, 'name': 'Nature.com'}",Androgen activity in the male embryonic hindbrain drives lethal PFA ependymoma,"Androgen activity in the male embryonic hindbrain prolongs hindbrain differentiation in male individuals and drives sex differences in the incidence and prognosis of posterior fossa type A (PFA) ependymoma, an aggressive childhood brain tumour.",https://www.nature.com/articles/s41586-026-10264-6,https://media.springernature.com/m685/springer-static/image/art%3A10.1038%2Fs41586-026-10264-6/MediaObjects/41586_2026_10264_Fig1_HTML.png,Animal experiments\r\nAll animal work in this study was approved by the Animal Care Committee of The Centre for Phenogenomics (TCP) (AUP 25-0100H) and by the Institutional Animal Care and Use Committee… [+35408 chars],health,69,1,description,1
242,We finish off our Opening Day power rankings with a look at the 18 teams projected to finish at or above .500.,1,,,Jake Mailhot,2026-03-25T16:10:15Z,"{'id': None, 'name': 'Fangraphs.com'}",FanGraphs Power Rankings: Opening Day 2026 (No. 1–18),We finish off our Opening Day power rankings with a look at the 18 teams projected to finish at or above .500.,https://blogs.fangraphs.com/fangraphs-power-rankings-opening-day-2026-no-1-18/,https://blogs.fangraphs.com/wp-content/uploads/2026/03/Power-Rankings-Opening-Day-2.jpg,"Opening Day is upon us! Yesterday, I laid out what the best- and worst-case scenarios looked like for the 12 teams projected to finish under .500 in 2026. Today, we turn our attention to the teams in… [+25975 chars]",health,77,1,description,1
253,See the expected new lineup and rotation.,1,,,"Andrew Tredinnick, NorthJersey.com",2026-03-24T08:04:55Z,"{'id': None, 'name': 'NorthJersey.com'}","Mets projected lineup, rotation and keys to winning NL East",The Mets begin their 2026 'redemption tour' on Opening Day after a disappointing 2025 season. See the expected new lineup and rotation.,https://www.northjersey.com/story/sports/mlb/mets/2026/03/24/ny-mets-2026-preview-opening-day-lineup-rotation-predictions/89249791007/,https://s.yimg.com/ny/api/res/1.2/zsxORNdWfVeSB.BDPAT_0Q--/YXBwaWQ9aGlnaGxhbmRlcjt3PTEyMDA7aD04MDA7Y2Y9d2VicA--/https://media.zenfs.com/en/the-bergen-record/cd3358ba16b0cc83e81a48f238e60174,"The Mets' redemption tour begins on Thursday afternoon after a major bust in the 2025 season.\r\nAfter falling one win short of a playoff spot, Opening Day marks the start of a new era for the Mets aft… [+8944 chars]",health,82,1,description,1
281,"The Oura Ring 5 isn’t expected to launch for another year, but a purported leak might have given us an early glimpse of what to expect.",1,,,James Pero,2026-03-24T15:40:39Z,"{'id': None, 'name': 'Gizmodo.com'}",Oura’s Next Smart Ring Just Leaked a Year Early,"If these images are real, this is the first look at the Oura Ring 5.",https://gizmodo.com/ouras-next-smart-ring-just-leaked-a-year-early-2000737357,https://gizmodo.com/app/uploads/2025/11/Oura-Ring-4-Ceramic-review-05-1200x675.jpg,"The Oura Ring 5 isn’t expected to launch for another year, but a purported leak might have given us an early glimpse of what to expect. Android Headlines claims to have obtained renders of the new he… [+2151 chars]",health,4,1,content,2
344,The pricetag is expected to continue… [+8401 chars],1,,,Ryan Bort,2026-03-21T13:00:00Z,"{'id': None, 'name': 'Rolling Stone'}",Things the Money for Trump’s Iran War Could Have Paid for That Aren’t … War,"Donald Trump's war against Iran is costing billions of dollars, and the Pentagon wants Congress to approve even more taxpayer money for the campaign.",http://www.rollingstone.com/politics/politics-features/cost-iran-war-billions-spent-social-services-1235535112/,https://www.rollingstone.com/wp-content/uploads/2026/03/Cost-of-War-iran.jpg?crop=0px%2C93px%2C1798px%2C1014px&resize=1600%2C900,"The first six days of Donald Trump’s war against Iran cost a whopping $11.3 billion, according to a report from the Pentagon given to Congress earlier this month. The pricetag is expected to continue… [+8401 chars]",health,30,1,content,2
383,The workforce expected to deliver the National Disability Insurance Scheme (NDIS) alternative has warned it will fail without the right staff and called for urgent transparency on how the program wil… [+6898 chars],1,,,Nas Campanella and Evan Young,2026-03-27T19:17:36Z,"{'id': 'abc-news-au', 'name': 'ABC News (AU)'}",Do we actually have the workforce to help autistic kids thrive?,"Months away from the start of a huge shift in disability support for children, the workforce expected to deliver it has concerns about its readiness.",https://www.abc.net.au/news/2026-03-28/thriving-kids-therapist-teachers-workforce-questions/106442196,https://live-production.wcms.abc-cdn.net.au/8ffadf5cb72a3c7a3238ec224a438936?impolicy=wcms_watermark_news&cropH=1968&cropW=3499&xPos=3&yPos=0&width=862&height=485&imformat=generic,The workforce expected to deliver the National Disability Insurance Scheme (NDIS) alternative has warned it will fail without the right staff and called for urgent transparency on how the program wil… [+6898 chars],health,48,1,content,2
384,A new nominee for director of the Centers for Disease Control and Prevention is expected to be named this week.,1,,,Pien Huang,2026-03-24T19:59:36Z,"{'id': None, 'name': 'NPR'}",The search for a new CDC director nears a deadline,A new nominee for director of the Centers for Disease Control and Prevention is expected to be named this week. They would inherit a demoralized staff and a public health agency buffeted by change.,https://www.npr.org/2026/03/24/nx-s1-5757471/the-search-for-a-new-cdc-director-nears-a-deadline,https://media.npr.org/include/images/facebook-default-wide-s1400-c85.jpg,A new nominee for director of the Centers for Disease Control and Prevention is expected to be named this week. They would inherit a demoralized staff and a public health agency buffeted by change.,health,49,1,content,2
393,"""I kind of expected just to do [Saturday] but, making the final was nice.",1,,,BBC Sport,2026-03-23T08:15:53Z,"{'id': None, 'name': 'BBC News'}",'For my boy' - Kinsella makes GB gymnastics history,Alice Kinsella becomes the first British artistic gymnast to resume elite competition after giving birth.,https://www.bbc.com/sport/gymnastics/articles/c62k4gnd303o,https://ichef.bbci.co.uk/ace/branded_sport/1200/cpsprodpb/6efe/live/47f13b10-268a-11f1-82d0-fd391f4a7261.jpg,"""I kind of expected just to do [Saturday] but, making the final was nice.\r\n""I am doing it for my little boy, so being able to finish and look up to him in the crowd is an amazing feeling.""\r\nKinsella'… [+1255 chars]",health,53,1,content,2
398,Good Morning America weatherman Sam Champion is sharing a positive forecast about his health.,1,,,Mike Vulpo,2026-03-23T17:45:29Z,"{'id': None, 'name': 'Us Weekly'}",GMA’s Sam Champion Shares Health Update After Heart Procedure,"Good Morning America weatherman Sam Champion is sharing a positive forecast about his health. “Thank you Dr. Stam Lerakis and Dr. Sharma and the WONDERFUL team of nurses at @mountsinaimedicalcenter Fuster Heart Hospital!” Champion, 64, wrote via Instagram on …",https://www.usmagazine.com/celebrity-news/news/gmas-sam-champion-hospitalized-for-health-procedure/,https://www.usmagazine.com/wp-content/uploads/2026/03/gma-sam-champion-hospital2.jpg?crop=0px%2C289px%2C1200px%2C630px&resize=1200%2C630&quality=86&strip=all,Good Morning America weatherman Sam Champion is sharing a positive forecast about his health.\r\n“Thank you Dr. Stam Lerakis and Dr. Sharma and the WONDERFUL team of nurses at @mountsinaimedicalcenter … [+2245 chars],health,55,1,content,2
403,"Sotera Health logo CFO Jon Lyons reiterated constant-currency organic growth guidance of 5% to 6.5% for 2026, with Sterigenics expected to deliver mid to highsingledigit growth, Nordion low … [+8213 chars]",1,,,MarketBeat,2026-03-22T11:06:36Z,"{'id': None, 'name': 'MarketBeat'}","Sotera Health CFO Says Growth Story Intact, Sees 2026 Organic Growth of 5%-6.5% at KeyBanc Forum",Sotera Health (NASDAQ:SHC) Chief Financial Officer Jon Lyons told investors at the KeyBanc Healthcare Forum that the company’s core investment case remains...,https://www.marketbeat.com/instant-alerts/sotera-health-cfo-says-growth-story-intact-sees-2026-organic-growth-of-5-65-at-keybanc-forum-2026-03-22/?utm_source=yahoofinance&amp;utm_medium=yahoofinance,https://s.yimg.com/os/en/marketbeat_955/bd25a99cb4a886db6971d8c549d3deeb,"Sotera Health logo\r\n<ul><li>CFO Jon Lyons reiterated constant-currency organic growth guidance of 5% to 6.5% for 2026, with Sterigenics expected to deliver mid to highsingledigit growth, Nordion low … [+8213 chars]",health,57,1,content,2
430,"Your interpersonal skills stand out today, helping you accomplish far more than expected, says Ganesha.",1,,,Ganesha Speaks,2026-03-28T00:30:37Z,"{'id': None, 'name': 'The Indian Express'}","Aries Horoscope Today, 28 March 2026: Emotions could run ahead of reason, unsettling harmony and your own peace","Aries Horoscope Today, 28 March 2026: No windfall is indicated beyond your regular salary or business income. You’re also not inclined to chase extra work; the mood is to slow down and decompress.",https://indianexpress.com/article/horoscope/aries-horoscope-today-28-march-2026-daily-astrology-prediction-for-aries-career-finance-money-love-10603586/,https://images.indianexpress.com/2024/05/Aries-1.jpg,"Aries Horoscope Prediction Today, 28 March 2026: Your interpersonal skills stand out today, helping you accomplish far more than expected, says Ganesha. Your clarity of expression leaves a strong imp… [+1443 chars]",health,71,1,content,2

In [16]:
len(predictions_df)

21

In [ ]:
def build_query_package(
    *,
    query_string: str,
    query_domain: str, 
    start_date: str,
    end_date: str,
    df,
    final_df,
    predictions_df,
    language: str = "en",
    sort_by: str = "relevancy",
    page_size: int = None
):
    """
    Builds a query-aligned package and a deterministic filename prefix.
    """

    # -------------------------
    # Prefix from query
    # -------------------------
    base_prefix = (
        query_string.lower()
        .replace(" or ", "_")
        .replace(" and ", "_")
        .replace(" ", "_")
    )
    base_prefix = re.sub(r"[^a-z0-9_]", "", base_prefix)
    base_prefix = re.sub(r"_+", "_", base_prefix).strip("_")

    prefix = f"{base_prefix}_{start_date}_to_{end_date}"

    # -------------------------
    # Query metadata
    # -------------------------
    query_meta = {
        "query": query_string,
        "query_domain": query_domain,
        "language": language,
        "from_date": start_date,
        "to_date": end_date,
        "sort_by": sort_by,
        "page_size": page_size,
        "timestamp_utc": datetime.utcnow().isoformat()
    }

    # -------------------------
    # Full package
    # -------------------------
    package = {
        "query_meta": query_meta,
        "counts": {
            "num_raw_articles": len(df),
            "num_sentences": len(final_df),
            "num_potential_predictions": len(predictions_df)
        },
        "raw_articles": df.to_dict(orient="records"),
        "processed_sentences": final_df.to_dict(orient="records"),
        "potential_predictions": predictions_df.to_dict(orient="records")
    }

    return prefix, package

In [ ]:
prefix, query_package = build_query_package(
    query_string=QUERY_CONFIGS[list_num]["query"],
    query_domain=QUERY_CONFIGS[list_num]["query_domain"],
    start_date=start_date,
    end_date=end_date,
    df=df,
    final_df=final_df,
    predictions_df=predictions_df,
    page_size=7
)

In [ ]:
base_data_path = DataProcessing.load_base_data_path(notebook_dir)
save_path = os.path.join(base_data_path, 'news_api', 'annotators')

DataProcessing.save_to_file(
    data=predictions_df,
    path=save_path,
    prefix=f"{prefix}_predictions",
    save_file_type="csv"
)

In [ ]:
DataProcessing.save_to_file(
    data=query_package,
    path=save_path,
    prefix=f"{prefix}_full",
    save_file_type="json"
)