## Data Acquisition: News API

In [1]:
import os
import re
import sys
import html

import pandas as pd

from datetime import datetime
from dotenv import load_dotenv
load_dotenv()

from newsapi import NewsApiClient

# Get the current working directory of the notebook
notebook_dir = os.getcwd()
# Add the parent directory to the system path
sys.path.append(os.path.join(notebook_dir, '../'))

from data_processing import DataProcessing
from feature_extraction import SpacyFeatureExtraction

In [2]:
pd.set_option('max_colwidth', 800)
# pd.set_option('display.max_columns', None)
# pd.set_option('display.max_rows', None)

In [3]:
api_key = os.getenv('NEWS_API_KEY')

In [4]:
QUERY_CONFIGS = [
    {"query_domain": "finance", "query": "(earnings OR revenue OR inflation OR interest rates) AND (expected OR forecast OR outlook OR projected)"}, # 0
    {"query_domain": "health", "query": "(disease OR virus OR vaccine OR public health) AND (expected OR forecast OR projected OR prognosis)"},
    {"query_domain": "weather", "query": "(weather OR storm OR hurricane OR rainfall OR temperature) AND (forecast OR expected OR outlook)"},
    {"query_domain": "policy", "query": "(election OR vote OR polling OR legislation) AND (expected OR likely OR projected OR forecast)"},
    {"query_domain": "sports_nfl", "query": "NFL AND (playoffs OR draft OR season) AND (expected OR likely OR prediction OR forecast)"},
    {"query_domain": "sports_nba", "query": "NBA AND (playoffs OR finals OR season) AND (expected OR likely OR prediction OR forecast)"},
    {"query_domain": "sports_college", "query": "(NCAA OR college football OR March Madness) AND (expected OR likely OR prediction OR forecast)"}, 
    {"query_domain": "misc-tesla", "query": "Tesla OR SAE Level 4 autonomy"}, # 7

    {"query_domain": "finance", "query": "(stocks OR markets OR economy)"},
    {"query_domain": "health", "query": " (health officials OR doctors OR experts)"},
    {"query_domain": "weather", "query": "(storm OR heat OR cold OR rain)"},
    {"query_domain": "policy", "query": "(election OR court OR vote)"},
    {"query_domain": "sports_nfl", "query": "NFL"},
    {"query_domain": "sports_nba", "query": "NBA"},
    {"query_domain": "sports_college", "query": "(college football OR NCAA)"}, # 14
]

list_num = 9

# neeed 8 to 13

In [6]:
# query_string = "Tesla OR SAE Level 4 autonomy"
start_date = "2026-03-11"
end_date = "2026-04-09"
newsapi = NewsApiClient(api_key=api_key)
all_articles = newsapi.get_everything(
    q=QUERY_CONFIGS[list_num]['query'],
    language="en",
    from_param=start_date,
    to=end_date,
    sort_by="relevancy",
    page_size=100
)

In [7]:
all_articles.keys()

dict_keys(['status', 'totalResults', 'articles'])

In [8]:
len(all_articles['articles']), all_articles['articles']

(96,
 [{'source': {'id': None, 'name': 'Gizmodo.com'},
   'author': 'Matthew Phelan',
   'title': 'Some of the Most Hyped Gym Supplements Are Fake, Unregulated, or Both',
   'description': "Worse, a new survey of 375 sports medicine experts has uncovered that some of most popular and sketchiest products aren't even on their radar yet.",
   'url': 'https://gizmodo.com/some-of-the-most-hyped-gym-supplements-are-fake-unregulated-or-both-2000739118',
   'urlToImage': 'https://gizmodo.com/app/uploads/2026/03/multivitamin-1200x675.jpg',
   'publishedAt': '2026-03-27T19:05:43Z',
   'content': 'Doctors are only now starting to catch up on the weird, rapidly growing, and wildly unregulated world of underground bodybuilding supplements. Even with surging media attention on the rise of dubious… [+4820 chars]'},
  {'source': {'id': None, 'name': 'Gizmodo.com'},
   'author': 'Ed Cara',
   'title': 'Should You Be Taking Peptides?',
   'description': "From GLP-1s to anti-aging cocktails, peptides are being widely marketed as wellness boosters. Here's what experts say you should know before you buy in.",
   'url': 'https://gizmodo.com/should-you-be-taking-peptides-2000732422',
   'urlToImage': 'https://gizmodo.com/app/uploads/2026/03/peptides-pipette-dropper-Giz-Asks-1200x675.jpg',
   'publishedAt': '2026-03-12T14:00:01Z',
   'content': '“Peptides” has fast become one of the biggest buzzwords in the wellness world. And they’re likely to get even more public attention in the coming months and years.\r\nPeptides are simple chains of two … [+11438 chars]'},
  {'source': {'id': None, 'name': 'Gizmodo.com'},
   'author': 'Ed Cara',
   'title': 'In Medical First, a Single Therapy Knocked Out 3 Autoimmune Diseases at Once',
   'description': "CAR T-cell therapy could help tackle the most severe cases that haven't responded to other treatments, her doctors say. \n\nALT DEK: 14 months later, the woman still doesn't need any treatments for her conditions.",
   'url': 'https://gizmodo.com/in-medical-first-a-single-therapy-knocked-out-3-autoimmune-diseases-at-once-2000744222',
   'urlToImage': 'https://gizmodo.com/app/uploads/2026/04/B-cell-antibodies-1200x675.jpg',
   'publishedAt': '2026-04-09T15:00:25Z',
   'content': 'In recent years, CAR T-cell therapy has become a revolutionary, if risky, treatment for some late-stage cancers. Yet CAR T may also have another life as a near-miraculous intervention for certain imm… [+4476 chars]'},
  {'source': {'id': 'the-verge', 'name': 'The Verge'},
   'author': 'Victoria Song',
   'title': 'How the Apple Watch defined modern health tech',
   'description': "This is Optimizer, a weekly newsletter sent every Friday from Verge senior reviewer Victoria Song that dissects and discusses the latest gizmos and potions that swear they're going to change your life. Opt in for Optimizer here. You can trace the state of hea…",
   'url': 'https://www.theverge.com/column/906391/apple-watch-optimizer-apple-50-health-tech-wearables',
   'urlToImage': 'https://platform.theverge.com/wp-content/uploads/sites/2/2026/04/268248_APPLE_50_APPLE_WATCH_CVirginia.jpg?quality=90&strip=all&crop=0%2C10.732984293194%2C100%2C78.534031413613&w=1200',
   'publishedAt': '2026-04-03T12:52:14Z',
   'content': '<ul><li></li><li></li><li></li></ul>\r\nDigital health screeners werent a thing until the Apple Watch. Its shaped how we think about wearables ever since.\r\nby\r\nVictoria SongClose\r\nSenior Reviewer, Wear… [+12217 chars]'},
  {'source': {'id': 'business-insider', 'name': 'Business Insider'},
   'author': 'Jack Newsham',
   'title': "Medvi, the AI-powered telehealth company, is fueled by ads from doctors who don't appear to exist",
   'description': "Medvi's marketing has included seemingly fake doctors and prompted lawsuits.",
   'url': 'https://www.businessinsider.com/medvi-ai-weight-loss-millions-ai-advertising-legal-compliance-challenges-2026-4',
   'urlToImage': 'https://i.insider.com/69d0328ae762ed6cfe44a3fb?width=1200&format=jpeg',
   'publishedAt': '2026-04-06T23:14:50Z',
   'content': 'RICCARDO MILANI/Hans Lucas/AFP via Getty Images\r\n<ul><li>The New York Times reported that telehealth startup Medvi has over $1 billion in projected sales.</li><li>Founder Matthew Gallagher used AI to… [+7064 chars]'},
  {'source': {'id': None, 'name': 'NPR'},
   'author': 'Michal Ruprecht',
   'title': 'As parents clamor for a treatment touted for autism, doctors hesitate to prescribe it',
   'description': "After the leucovorin got public attention as a potential autism treatment, families rushed to get it. Many doctors are torn about prescribing an unproven drug but don't want to lose patients' trust.",
   'url': 'https://www.npr.org/2026/03/16/nx-s1-5742676/leucovorin-autism-parents-treatment-prescribe',
   'urlToImage': 'https://npr.brightspotcdn.com/dims3/default/strip/false/crop/4800x2700+0+0/resize/1400/quality/85/format/jpeg/?url=http%3A%2F%2Fnpr-brightspot.s3.amazonaws.com%2F54%2Fa5%2Ffc8cb83d4b37a72d055f3c59867a%2Ffinal.jpg',
   'publishedAt': '2026-03-16T09:00:00Z',
   'content': 'Swathi Balantrapu has been searching for a treatment for her 10-year-old son with autism.\r\nShe first tried applied behavior analysis therapy, or ABA therapy an evidence-based approach. She later purs… [+16245 chars]'},
  {'source': {'id': 'the-verge', 'name': 'The Verge'},
   'author': 'Robert Hart',
   'title': 'Fitbit’s AI health coach will soon be able to read your medical records',
   'description': "Would you share your medical records with a personal trainer? How about a virtual one? Google, which this week announced it is giving Fitbit's AI health coach the ability to read your medical records, is hoping the answer is yes, following rivals like Amazon,…",
   'url': 'https://www.theverge.com/ai-artificial-intelligence/897250/fitbits-ai-health-coach-reads-medical-records',
   'urlToImage': 'https://platform.theverge.com/wp-content/uploads/sites/2/2026/03/Fitbit_STK151_01.jpg?quality=90&strip=all&crop=0%2C10.732984293194%2C100%2C78.534031413613&w=1200',
   'publishedAt': '2026-03-19T12:27:23Z',
   'content': '<ul><li></li><li></li><li></li></ul>\r\nGoogle says the data will help the AI coach provide better advice, but that it cant diagnose, treat, or monitor conditions.\r\nGoogle says the data will help the A… [+4468 chars]'},
  {'source': {'id': None, 'name': 'Yahoo Entertainment'},
   'author': 'ALBERT STUMM',
   'title': 'Doctors want more women lifting weights. Experts say welcoming gyms and education would help',
   'description': 'During her first year of college, Elisabeth Bradley was inspired to try weightlifting after she followed a woman tracking her fitness transformation on...',
   'url': 'https://health.yahoo.com/wellness/fitness/articles/doctors-want-more-women-lifting-040152643.html',
   'urlToImage': 'https://s.yimg.com/ny/api/res/1.2/KhoVtZ2jIZgMB8NAnelEOQ--/YXBwaWQ9aGlnaGxhbmRlcjt3PTEyMDA7aD04MDA-/https://media.zenfs.com/en/ap.org/6a4fa0f11a42672a5003c6b66deae28f',
   'publishedAt': '2026-03-21T04:01:52Z',
   'content': 'During her first year of college, Elisabeth Bradley was inspired to try weightlifting after she followed a woman tracking her fitness transformation on social media, one barbell at a time.\r\nThen, Bra… [+5065 chars]'},
  {'source': {'id': None, 'name': 'BBC News'},
   'author': None,
   'title': 'Are UK students at risk of more deadly meningitis outbreaks?',
   'description': 'The worst seems to be over, but questions remain about why this happened and whether it could happen again.',
   'url': 'https://www.bbc.com/news/articles/c93eqvxydzqo',
   'urlToImage': 'https://ichef.bbci.co.uk/news/1024/branded_news/d7c8/live/632d9f00-2a3a-11f1-8e06-4f542a88d870.jpg',
   'publishedAt': '2026-03-28T00:15:07Z',
   'content': 'The Health Secretary, Wes Streeting, has asked independent experts in the Joint Committee on Vaccination and Immunisation (JCVI) to look again at the decision not to vaccinate teenagers. There have b… [+110 chars]'},
  {'source': {'id': None, 'name': 'Eatingwell.com'},
   'author': 'Roxana Ehsani, M.S., RD, CSSD, LDN',
   'title': '4 Habits You Need to Break to Help Slow Aging, According to Doctors',
   'description': 'These daily behaviors may be working against your internal clock.',
   'url': 'https://www.eatingwell.com/habits-to-break-to-help-slow-aging-11928666',
   'urlToImage': 'https://s.yimg.com/ny/api/res/1.2/xb7dheBYXY_KDF1Z07lJFA--/YXBwaWQ9aGlnaGxhbmRlcjt3PTEyMDA7aD04MTA-/https://media.zenfs.com/en/eating_well_articles_946/e7afae6767a9a4f865d1d64ec914c251',
   'publishedAt': '2026-03-22T05:30:00Z',
   'content': 'Reviewed by Dietitian Lisa Valente, M.S., RD\r\nCredit: Getty Images. EatingWell Design.\r\nKey Points\r\n<ul><li>Habits like sitting all day and not getting enough sleep can impact your health as you age.… [+7372 chars]'},
  {'source': {'id': None, 'name': 'NPR'},
   'author': 'Sarah Boden',
   'title': "Influencers push 'parasite cleanses' but doctors say to steer clear",
   'description': "Some people online believe many of us have dangerous parasites in our gut and need to flush them out with herbal supplements. Here's what doctors say about the trend.",
   'url': 'https://www.npr.org/2026/03/16/nx-s1-5745200/parasite-cleanse-safety-science',
   'urlToImage': 'https://npr.brightspotcdn.com/dims3/default/strip/false/crop/3413x1920+43+0/resize/1400/quality/85/format/jpeg/?url=http%3A%2F%2Fnpr-brightspot.s3.amazonaws.com%2F15%2Ff1%2F4d78689f47f892459c73c93c4fe8%2Fparasites-final.jpg',
   'publishedAt': '2026-03-16T09:00:00Z',
   'content': 'Some wellness influencers are very worried about parasites.\r\nIn online posts and videos, they suggest the organisms can be blamed for a host of symptoms bloating, insomnia, food cravings, teeth grind… [+6693 chars]'},
  {'source': {'id': None, 'name': 'NPR'},
   'author': 'Gabrielle Emanuel',
   'title': "Cuba sends doctors on medical missions. The U.S. isn't a fan",
   'description': "It's a major source of revenue for the island. And it's controversial. Now countries are sending Cuban doctors home in response to pressure from the Trump administration.",
   'url': 'https://www.npr.org/2026/03/24/nx-s1-5746626/cuba-doctors-mission-blockade',
   'urlToImage': 'https://npr.brightspotcdn.com/dims3/default/strip/false/crop/5541x3117+0+285/resize/1400/quality/85/format/jpeg/?url=http%3A%2F%2Fnpr-brightspot.s3.amazonaws.com%2F31%2F02%2Ff6a8959743a6a1091fe71ffcbdc0%2Fcuba-doctors-2036327921.jpg',
   'publishedAt': '2026-03-24T19:59:57Z',
   'content': "Is it a praiseworthy humanitarian effort or an affront to human rights?\r\nThat's the debate swirling around a Cuban program that sends tens of thousands of doctors and other medical professionals abro… [+7145 chars]"},
  {'source': {'id': 'business-insider', 'name': 'Business Insider'},
   'author': 'Laura Italiano',
   'title': "Ex-CEO of Abercrombie & Fitch was recorded on prison tape saying doctors 'better find me incompetent'",
   'description': 'The prison recording emerged during a three-day competency hearing over the ability of Michael Jefferies to stand trial for sex trafficking.',
   'url': 'https://www.businessinsider.com/abercrombie-fitch-ceo-prison-call-doctors-better-find-me-incompetent-2026-3',
   'urlToImage': 'https://i.insider.com/69c2dd9ae98a37a4841f328e?width=1200&format=jpeg',
   'publishedAt': '2026-03-24T18:59:25Z',
   'content': 'Former Abercrombie & Fitch CEO Michael Jeffries leaves a Long Island courthouse after a 2024 hearing in his sex trafficking case.Spencer Platt/Getty Images\r\n<ul><li>Lawyers for Michael Jeffries say h… [+4759 chars]'},
  {'source': {'id': None, 'name': 'CNET'},
   'author': 'Giselle Castro-Sloboda',
   'title': 'Amazon Expands Health AI Access for Virtual Health Care',
   'description': "If you're an Amazon member with health questions, this chatbot may have answers for you.",
   'url': 'https://www.cnet.com/tech/amazon-expands-health-ai-access-for-amazon-users-looking-to-receive-virtual-healthcare/',
   'urlToImage': 'https://www.cnet.com/a/img/resize/d843c6634832c93ab606f2dc173155c246a06e36/hub/2026/03/11/829f6bae-50a2-460e-bc27-bf612ed3573d/meet-health-ai.jpg?auto=webp&fit=crop&height=675&width=1200',
   'publishedAt': '2026-03-11T23:12:01Z',
   'content': 'Amazon is expanding access to its\xa0health care virtual assistant, Health AI, the company said on Tuesday. This feature was originally available only to One Medical members, but it will now be availabl… [+2898 chars]'},
  {'source': {'id': None, 'name': 'Womansworld.com'},
   'author': 'Cailey Griffin',
   'title': 'New Cholesterol Guidelines Are Here: Doctors Share the Biggest Changes',
   'description': "Here's some exciting news for your heart: The rules around cholesterol just got simpler, smarter and more personalized with an earlier start on primary...",
   'url': 'https://www.womansworld.com/wellness/heart-health/new-cholesterol-guidelines-are-here-see-the-biggest-changes',
   'urlToImage': 'https://s.yimg.com/os/en/woman_s_world_418/6090b9a33ad58158cd86f137b7d55804',
   'publishedAt': '2026-03-27T23:30:49Z',
   'content': "Here's some exciting news for your heart: The rules around cholesterol just got simpler, smarter and more personalized with an earlier start on primary prevention. On March 13, the American College o… [+5016 chars]"},
  {'source': {'id': None, 'name': 'Prevention.com'},
   'author': 'Alyssa Sybertz',
   'title': 'Dermatologists Reveal the Number-1 Sign of Skin Cancer—and It’s Sneaky',
   'description': 'Doctors reveal the number-one sign of skin cancer across every type, plus why early detection is so important to getting potentially life-saving treatment.',
   'url': 'https://www.prevention.com/health/a70966202/top-sign-of-skin-cancer/',
   'urlToImage': 'https://s.yimg.com/ny/api/res/1.2/Z97x53Pa6tFT9FhNN7dohg--/YXBwaWQ9aGlnaGxhbmRlcjt3PTEyMDA7aD04MDA-/https://media.zenfs.com/en/hearst_prevention_66/0d7dfc1e143be7d16838de2681847120',
   'publishedAt': '2026-04-09T12:30:00Z',
   'content': 'There are few things we love more than the feel of the hot sun warming our faces, except remembering to slather on sunscreen before heading out into that cloudless day. But even if youre doing your b… [+2551 chars]'},
  {'source': {'id': 'the-verge', 'name': 'The Verge'},
   'author': 'Robert Hart',
   'title': 'It’s not easy to get depression-detecting AI through the FDA',
   'description': "For the past seven years, the California-based startup Kintsugi has been developing AI designed to detect signs of depression and anxiety from a person's speech. But after failing to secure FDA clearance in time, the company is shutting down and releasing mos…",
   'url': 'https://www.theverge.com/ai-artificial-intelligence/905864/depression-detecting-ai-kintsugi-clinical-ai-startup-shut-down',
   'urlToImage': 'https://platform.theverge.com/wp-content/uploads/sites/2/2025/09/STK_414_AI_CHATBOT_R2_CVirginia_D.jpg?quality=90&strip=all&crop=0%2C10.732984293194%2C100%2C78.534031413613&w=1200',
   'publishedAt': '2026-04-02T15:33:23Z',
   'content': '<ul><li></li><li></li><li></li></ul>\r\nInstead, a mental health startup shut down and open-sourced its tech.\r\nInstead, a mental health startup shut down and open-sourced its tech.\r\nby\r\nRobert HartClos… [+7567 chars]'},
  {'source': {'id': 'the-verge', 'name': 'The Verge'},
   'author': 'Gaby Del Valle',
   'title': 'The $100,000 fee for H-1Bs is causing all sorts of problems',
   'description': "Last fall, President Donald Trump's executive order raising the fee for H-1B visas to $100,000 - like many of his immigration policies - led to near-immediate chaos. Thousands of workers who had flown overseas to renew their visas ended up stranded abroad. De…",
   'url': 'https://www.theverge.com/policy/894537/h1b-fee-increase-trump-teacher-shortage-tech-workers',
   'urlToImage': 'https://platform.theverge.com/wp-content/uploads/sites/2/2026/03/268403_The_100000_fee_for_H-1Bs_six_months_later_CVirginia2.jpg?quality=90&strip=all&crop=0%2C10.732984293194%2C100%2C78.534031413613&w=1200',
   'publishedAt': '2026-03-13T19:50:06Z',
   'content': '<ul><li></li><li></li><li></li></ul>\r\nUnlike Big Tech, rural schools and hospitals that rely on immigrant workers cant absorb the high cost of H-1B visas.\r\nUnlike Big Tech, rural schools and hospital… [+10582 chars]'},
  {'source': {'id': None, 'name': 'Parade'},
   'author': 'Emily Laurence',
   'title': 'Getting COVID Again Is More Dangerous Than Most People Realize—Here’s What To Know',
   'description': 'Doctors share why it’s still important to take the virus seriously.',
   'url': 'https://parade.com/health/dangers-of-getting-covid-again-according-to-infectious-disease-expert',
   'urlToImage': 'https://s.yimg.com/lo/mysterio/api/C71430DCC96EE0A18EC62D63CAAFBFEAFB0AB3B3B5AECDB9836B84B7DF3A8451/subgraphmysterio/resizefill_w1200_h675;quality_80;format_webp/https:%2F%2Fmedia.zenfs.com%2Fen%2Fparade_250%2Fda04ac760f0b6ba59d2c2e944c0c92a2',
   'publishedAt': '2026-03-25T13:25:00Z',
   'content': 'The pandemic days of hoarding toilet paper and celebrating birthdays over Zoom seem like a lifetime ago. While in many ways, life has long felt back to normal, its important to acknowledge the millio… [+6174 chars]'},
  {'source': {'id': None, 'name': 'The Atlantic'},
   'author': 'Katherine J. Wu',
   'title': 'HHS Is Exiling Top Officials to the Indian Health Service',
   'description': 'The Indian Health Service needs more clinical workers. The federal health officials being transferred to the agency don’t fit that bill.',
   'url': 'https://www.theatlantic.com/health/2026/03/hhs-exiling-top-officials-indian-health-service/686637/',
   'urlToImage': 'https://cdn.theatlantic.com/thumbor/rDMH-bgQmmicGud-9BPFWmOis2I=/0x64:2995x1624/1200x625/media/img/mt/2026/03/2026_03_31_HHS_Finally_Reassigns_Top_Officials_to_Jobs_Previewed_a_Year_Ago/original.jpg',
   'publishedAt': '2026-03-31T22:17:58Z',
   'content': 'Last week, the Department of Health and Human Services finally followed through on a plan it first outlined for several of its top officials nearly a year ago: It reassigned them to positions in the … [+9306 chars]'},
  {'source': {'id': None, 'name': 'Gizmodo.com'},
   'author': 'Matt Novak',
   'title': 'RFK Jr. Will Take on Joe Rogan for Podcaster Supremacy',
   'description': '"This isn\'t going to be about politics," Kennedy insisted about his new podcast.',
   'url': 'https://gizmodo.com/rfk-jr-will-take-on-joe-rogan-for-podcaster-supremacy-2000744221',
   'urlToImage': 'https://gizmodo.com/app/uploads/2026/04/GettyImages-2258947361-1200x675.jpg',
   'publishedAt': '2026-04-08T21:40:02Z',
   'content': 'Robert F. Kennedy Jr. is launching a new podcast, according to a teaser video the Health Secretary posted to X on Wednesday. In many ways, it feels like Kennedy’s final form: the anti-vaxx podcaster.… [+3107 chars]'},
  {'source': {'id': None, 'name': 'Eatingwell.com'},
   'author': 'Cheyenne Buckingham',
   'title': '6 Things You Should Do After 5 P.M. to Support Healthy Aging, According to Experts',
   'description': 'Aging is a privilege—support your health in later years with these expert-backed tips.',
   'url': 'https://www.eatingwell.com/things-to-do-after-5-pm-for-healthy-aging-11899371',
   'urlToImage': 'https://s.yimg.com/ny/api/res/1.2/IXxOywWpSveZtBJRrauUAA--/YXBwaWQ9aGlnaGxhbmRlcjt3PTEyMDA7aD04MTA-/https://media.zenfs.com/en/eating_well_articles_946/a09fcbe2a077242e1fc9390ab6c63ab9',
   'publishedAt': '2026-03-13T21:30:00Z',
   'content': 'Reviewed by Dietitian Sarah Pflugradt, Ph.D., RDN, CSCS\r\nCredit: Getty Images. EatingWell design.\r\nKey Points\r\n<ul><li>Developing healthy habits after 5 p.m. can help you sleep better and benefit the… [+6975 chars]'},
  {'source': {'id': None, 'name': 'Yahoo Entertainment'},
   'author': 'Rachel Uda, Health and Business Editor',
   'title': 'What the New Cholesterol Guidelines Mean for Your Health',

In [9]:
df = pd.DataFrame(all_articles['articles'])
df

,source,author,title,description,url,urlToImage,publishedAt,content
0,"{'id': None, 'name': 'Gizmodo.com'}",Matthew Phelan,"Some of the Most Hyped Gym Supplements Are Fake, Unregulated, or Both","Worse, a new survey of 375 sports medicine experts has uncovered that some of most popular and sketchiest products aren't even on their radar yet.",https://gizmodo.com/some-of-the-most-hyped-gym-supplements-are-fake-unregulated-or-both-2000739118,https://gizmodo.com/app/uploads/2026/03/multivitamin-1200x675.jpg,2026-03-27T19:05:43Z,"Doctors are only now starting to catch up on the weird, rapidly growing, and wildly unregulated world of underground bodybuilding supplements. Even with surging media attention on the rise of dubious… [+4820 chars]"
1,"{'id': None, 'name': 'Gizmodo.com'}",Ed Cara,Should You Be Taking Peptides?,"From GLP-1s to anti-aging cocktails, peptides are being widely marketed as wellness boosters. Here's what experts say you should know before you buy in.",https://gizmodo.com/should-you-be-taking-peptides-2000732422,https://gizmodo.com/app/uploads/2026/03/peptides-pipette-dropper-Giz-Asks-1200x675.jpg,2026-03-12T14:00:01Z,“Peptides” has fast become one of the biggest buzzwords in the wellness world. And they’re likely to get even more public attention in the coming months and years.\r\nPeptides are simple chains of two … [+11438 chars]
2,"{'id': None, 'name': 'Gizmodo.com'}",Ed Cara,"In Medical First, a Single Therapy Knocked Out 3 Autoimmune Diseases at Once","CAR T-cell therapy could help tackle the most severe cases that haven't responded to other treatments, her doctors say. \n\nALT DEK: 14 months later, the woman still doesn't need any treatments for her conditions.",https://gizmodo.com/in-medical-first-a-single-therapy-knocked-out-3-autoimmune-diseases-at-once-2000744222,https://gizmodo.com/app/uploads/2026/04/B-cell-antibodies-1200x675.jpg,2026-04-09T15:00:25Z,"In recent years, CAR T-cell therapy has become a revolutionary, if risky, treatment for some late-stage cancers. Yet CAR T may also have another life as a near-miraculous intervention for certain imm… [+4476 chars]"
3,"{'id': 'the-verge', 'name': 'The Verge'}",Victoria Song,How the Apple Watch defined modern health tech,"This is Optimizer, a weekly newsletter sent every Friday from Verge senior reviewer Victoria Song that dissects and discusses the latest gizmos and potions that swear they're going to change your life. Opt in for Optimizer here. You can trace the state of hea…",https://www.theverge.com/column/906391/apple-watch-optimizer-apple-50-health-tech-wearables,https://platform.theverge.com/wp-content/uploads/sites/2/2026/04/268248_APPLE_50_APPLE_WATCH_CVirginia.jpg?quality=90&strip=all&crop=0%2C10.732984293194%2C100%2C78.534031413613&w=1200,2026-04-03T12:52:14Z,"<ul><li></li><li></li><li></li></ul>\r\nDigital health screeners werent a thing until the Apple Watch. Its shaped how we think about wearables ever since.\r\nby\r\nVictoria SongClose\r\nSenior Reviewer, Wear… [+12217 chars]"
4,"{'id': 'business-insider', 'name': 'Business Insider'}",Jack Newsham,"Medvi, the AI-powered telehealth company, is fueled by ads from doctors who don't appear to exist",Medvi's marketing has included seemingly fake doctors and prompted lawsuits.,https://www.businessinsider.com/medvi-ai-weight-loss-millions-ai-advertising-legal-compliance-challenges-2026-4,https://i.insider.com/69d0328ae762ed6cfe44a3fb?width=1200&format=jpeg,2026-04-06T23:14:50Z,RICCARDO MILANI/Hans Lucas/AFP via Getty Images\r\n<ul><li>The New York Times reported that telehealth startup Medvi has over $1 billion in projected sales.</li><li>Founder Matthew Gallagher used AI to… [+7064 chars]
...,...,...,...,...,...,...,...,...
91,"{'id': None, 'name': 'Parade'}",Alexa Mellardo,Cardiologists Reveal How One Morning Habit Harms Your Heart Health,We're ALL guilty of this one.,https://parade.com/health/morning-habit-could-be-aging-your-heart-according-to-cardiologists,https://s.yimg.com/ny/api/res/1.2/48oMHqrKjttoBY9RDvk07w--/YXBwaWQ9aGlnaGxhbmRlcjt3PTEyMDA7aD02NzU-/https://media.zenfs.com/en/parade_250/5c4957c2ee391d3ca3b218458adc6abb,2026-03-26T14:50:00Z,"A healthy heart truly serves as the foundation of a happy, fulfilling life. After all, this vital organ carries a tremendous amount of responsibility. Each day, your heart pumps oxygen-rich blood, ho… [+7214 chars]"
92,"{'id': None, 'name': 'NPR'}",Kat McGowan,'What if I die first?' Making a plan is key for family caregivers. Here's how,"People who care for an adult child, partner or sibling have to face the reality that their loved may outlive them. Planning ahead is key but it's not easy.",https://www.npr.org/2026/03/28/nx-s1-5764324/family-caregiver-future-planning-help,https://npr.brightspotcdn.com/dims3/default/strip/false/crop/2112x1188+0+0/resize/1400/quality/85/format/png/?url=http%3A%2F%2Fnpr-brightspot.s3.amazonaws.com%2F90%2Fd5%2F056f23c248cb81f0847000cf867f%2Fnew-normal-min.png,2026-03-28T10:00:00Z,Noreen Vance 's beloved sister Angela has severe Down syndrome and needs help with daily life. Their mother cared for her for decades but refused to confront the possibility that she might die before… [+5143 chars]
93,"{'id': None, 'name': 'Yahoo Entertainment'}",Noah Jampol,Trail camera captures footage of 'one of the rarest carnivores on the planet' for first time in decades: 'Extremely difficult to find',"""This is one of our most favorite detections.""",https://www.yahoo.com/news/articles/trail-camera-captures-footage-one-100000993.html,https://s.yimg.com/ny/api/res/1.2/Jzr3nP8ZkrzzTMeCjUdQ0g--/YXBwaWQ9aGlnaGxhbmRlcjt3PTEyMDA7aD02NzU7Y2Y9d2VicA--/https://media.zenfs.com/en/the_cool_down_737/98f0cfba2e264294dee825ae98f20824,2026-03-19T10:00:00Z,"Not since the heydays of doo-wop and Elvis had the Sierra Nevada red fox been spotted in the Lake Tahoe Basin. That is, until now.\r\nThe California Department of Fish and Wildlife released trail foota… [+1971 chars]"
94,"{'id': None, 'name': 'Yahoo Entertainment'}",Rachel Grumman Bender,"Eat kimchi, sleep 11 minutes longer and try 'postage stamp vacuuming' — plus 7 more health tips to help you have a great week",Health hacks for the week ahead — including the brain-boosting benefits of making a home-cooked meal at least once a week.,https://health.yahoo.com/article/eat-kimchi-sleep-11-minutes-longer-and-try-postage-stamp-vacuuming--plus-7-more-health-tips-to-help-you-have-a-great-week-090055171.html,https://s.yimg.com/ny/api/res/1.2/f9N2e8nSTMuqzvoHsPxCPw--/YXBwaWQ9aGlnaGxhbmRlcjt3PTEyMDA7aD02NzU-/https://s.yimg.com/os/creatr-uploaded-images/2026-03/1179a1a0-2a20-11f1-8faf-f7c7726e7f4a,2026-03-29T09:00:55Z,"Making home-cooked meals can help reduce your risk of dementia. (Photo illustration: Yahoo News; photo: Getty Images)\r\nHi, Yahoo readers! My name is Rachel Grumman Bender, and Im here with your weekl… [+8518 chars]"
95,"{'id': None, 'name': 'Women's Health'}",Korin Miller,HMPV Cases are Rising — And You’ve Likely Already Been Infected Before. Here’s What to Know,"Cases of human metapneumovirus are on the rise across the country. Here's what this virus is, plus how to protect yourself.",https://www.womenshealthmag.com/health/a70734600/human-metapneumovirus-rising-cases/,https://s.yimg.com/ny/api/res/1.2/xIsSYru87yYE25BvTqu.Rw--/YXBwaWQ9aGlnaGxhbmRlcjt3PTEyMDA7aD02ODY-/https://media.zenfs.com/en/hearst_womens_health_52/fa64f5abb8d06cc66895c51f6a9c54fb,2026-03-14T11:00:00Z,"Cases of a virus with no vaccine and no specific treatment are popping up across the country. Its called human metapneumovirus, or HMPV, and it's on the rise nationwide, according to data from the Na… [+4366 chars]"

In [10]:
df = df.rename(columns={
    "source": "Source Meta Data",
    "author": "Source",
    "publishedAt": "Date",
    "url": "URL",
    "urlToImage": "Image URL"
})

df["Query Domain"] = QUERY_CONFIGS[list_num]["query_domain"]

df

,Source Meta Data,Source,title,description,URL,Image URL,Date,content,Query Domain
0,"{'id': None, 'name': 'Gizmodo.com'}",Matthew Phelan,"Some of the Most Hyped Gym Supplements Are Fake, Unregulated, or Both","Worse, a new survey of 375 sports medicine experts has uncovered that some of most popular and sketchiest products aren't even on their radar yet.",https://gizmodo.com/some-of-the-most-hyped-gym-supplements-are-fake-unregulated-or-both-2000739118,https://gizmodo.com/app/uploads/2026/03/multivitamin-1200x675.jpg,2026-03-27T19:05:43Z,"Doctors are only now starting to catch up on the weird, rapidly growing, and wildly unregulated world of underground bodybuilding supplements. Even with surging media attention on the rise of dubious… [+4820 chars]",health
1,"{'id': None, 'name': 'Gizmodo.com'}",Ed Cara,Should You Be Taking Peptides?,"From GLP-1s to anti-aging cocktails, peptides are being widely marketed as wellness boosters. Here's what experts say you should know before you buy in.",https://gizmodo.com/should-you-be-taking-peptides-2000732422,https://gizmodo.com/app/uploads/2026/03/peptides-pipette-dropper-Giz-Asks-1200x675.jpg,2026-03-12T14:00:01Z,“Peptides” has fast become one of the biggest buzzwords in the wellness world. And they’re likely to get even more public attention in the coming months and years.\r\nPeptides are simple chains of two … [+11438 chars],health
2,"{'id': None, 'name': 'Gizmodo.com'}",Ed Cara,"In Medical First, a Single Therapy Knocked Out 3 Autoimmune Diseases at Once","CAR T-cell therapy could help tackle the most severe cases that haven't responded to other treatments, her doctors say. \n\nALT DEK: 14 months later, the woman still doesn't need any treatments for her conditions.",https://gizmodo.com/in-medical-first-a-single-therapy-knocked-out-3-autoimmune-diseases-at-once-2000744222,https://gizmodo.com/app/uploads/2026/04/B-cell-antibodies-1200x675.jpg,2026-04-09T15:00:25Z,"In recent years, CAR T-cell therapy has become a revolutionary, if risky, treatment for some late-stage cancers. Yet CAR T may also have another life as a near-miraculous intervention for certain imm… [+4476 chars]",health
3,"{'id': 'the-verge', 'name': 'The Verge'}",Victoria Song,How the Apple Watch defined modern health tech,"This is Optimizer, a weekly newsletter sent every Friday from Verge senior reviewer Victoria Song that dissects and discusses the latest gizmos and potions that swear they're going to change your life. Opt in for Optimizer here. You can trace the state of hea…",https://www.theverge.com/column/906391/apple-watch-optimizer-apple-50-health-tech-wearables,https://platform.theverge.com/wp-content/uploads/sites/2/2026/04/268248_APPLE_50_APPLE_WATCH_CVirginia.jpg?quality=90&strip=all&crop=0%2C10.732984293194%2C100%2C78.534031413613&w=1200,2026-04-03T12:52:14Z,"<ul><li></li><li></li><li></li></ul>\r\nDigital health screeners werent a thing until the Apple Watch. Its shaped how we think about wearables ever since.\r\nby\r\nVictoria SongClose\r\nSenior Reviewer, Wear… [+12217 chars]",health
4,"{'id': 'business-insider', 'name': 'Business Insider'}",Jack Newsham,"Medvi, the AI-powered telehealth company, is fueled by ads from doctors who don't appear to exist",Medvi's marketing has included seemingly fake doctors and prompted lawsuits.,https://www.businessinsider.com/medvi-ai-weight-loss-millions-ai-advertising-legal-compliance-challenges-2026-4,https://i.insider.com/69d0328ae762ed6cfe44a3fb?width=1200&format=jpeg,2026-04-06T23:14:50Z,RICCARDO MILANI/Hans Lucas/AFP via Getty Images\r\n<ul><li>The New York Times reported that telehealth startup Medvi has over $1 billion in projected sales.</li><li>Founder Matthew Gallagher used AI to… [+7064 chars],health
...,...,...,...,...,...,...,...,...,...
91,"{'id': None, 'name': 'Parade'}",Alexa Mellardo,Cardiologists Reveal How One Morning Habit Harms Your Heart Health,We're ALL guilty of this one.,https://parade.com/health/morning-habit-could-be-aging-your-heart-according-to-cardiologists,https://s.yimg.com/ny/api/res/1.2/48oMHqrKjttoBY9RDvk07w--/YXBwaWQ9aGlnaGxhbmRlcjt3PTEyMDA7aD02NzU-/https://media.zenfs.com/en/parade_250/5c4957c2ee391d3ca3b218458adc6abb,2026-03-26T14:50:00Z,"A healthy heart truly serves as the foundation of a happy, fulfilling life. After all, this vital organ carries a tremendous amount of responsibility. Each day, your heart pumps oxygen-rich blood, ho… [+7214 chars]",health
92,"{'id': None, 'name': 'NPR'}",Kat McGowan,'What if I die first?' Making a plan is key for family caregivers. Here's how,"People who care for an adult child, partner or sibling have to face the reality that their loved may outlive them. Planning ahead is key but it's not easy.",https://www.npr.org/2026/03/28/nx-s1-5764324/family-caregiver-future-planning-help,https://npr.brightspotcdn.com/dims3/default/strip/false/crop/2112x1188+0+0/resize/1400/quality/85/format/png/?url=http%3A%2F%2Fnpr-brightspot.s3.amazonaws.com%2F90%2Fd5%2F056f23c248cb81f0847000cf867f%2Fnew-normal-min.png,2026-03-28T10:00:00Z,Noreen Vance 's beloved sister Angela has severe Down syndrome and needs help with daily life. Their mother cared for her for decades but refused to confront the possibility that she might die before… [+5143 chars],health
93,"{'id': None, 'name': 'Yahoo Entertainment'}",Noah Jampol,Trail camera captures footage of 'one of the rarest carnivores on the planet' for first time in decades: 'Extremely difficult to find',"""This is one of our most favorite detections.""",https://www.yahoo.com/news/articles/trail-camera-captures-footage-one-100000993.html,https://s.yimg.com/ny/api/res/1.2/Jzr3nP8ZkrzzTMeCjUdQ0g--/YXBwaWQ9aGlnaGxhbmRlcjt3PTEyMDA7aD02NzU7Y2Y9d2VicA--/https://media.zenfs.com/en/the_cool_down_737/98f0cfba2e264294dee825ae98f20824,2026-03-19T10:00:00Z,"Not since the heydays of doo-wop and Elvis had the Sierra Nevada red fox been spotted in the Lake Tahoe Basin. That is, until now.\r\nThe California Department of Fish and Wildlife released trail foota… [+1971 chars]",health
94,"{'id': None, 'name': 'Yahoo Entertainment'}",Rachel Grumman Bender,"Eat kimchi, sleep 11 minutes longer and try 'postage stamp vacuuming' — plus 7 more health tips to help you have a great week",Health hacks for the week ahead — including the brain-boosting benefits of making a home-cooked meal at least once a week.,https://health.yahoo.com/article/eat-kimchi-sleep-11-minutes-longer-and-try-postage-stamp-vacuuming--plus-7-more-health-tips-to-help-you-have-a-great-week-090055171.html,https://s.yimg.com/ny/api/res/1.2/f9N2e8nSTMuqzvoHsPxCPw--/YXBwaWQ9aGlnaGxhbmRlcjt3PTEyMDA7aD02NzU-/https://s.yimg.com/os/creatr-uploaded-images/2026-03/1179a1a0-2a20-11f1-8faf-f7c7726e7f4a,2026-03-29T09:00:55Z,"Making home-cooked meals can help reduce your risk of dementia. (Photo illustration: Yahoo News; photo: Getty Images)\r\nHi, Yahoo readers! My name is Rachel Grumman Bender, and Im here with your weekl… [+8518 chars]",health
95,"{'id': None, 'name': 'Women's Health'}",Korin Miller,HMPV Cases are Rising — And You’ve Likely Already Been Infected Before. Here’s What to Know,"Cases of human metapneumovirus are on the rise across the country. Here's what this virus is, plus how to protect yourself.",https://www.womenshealthmag.com/health/a70734600/human-metapneumovirus-rising-cases/,https://s.yimg.com/ny/api/res/1.2/xIsSYru87yYE25BvTqu.Rw--/YXBwaWQ9aGlnaGxhbmRlcjt3PTEyMDA7aD02ODY-/https://media.zenfs.com/en/hearst_womens_health_52/fa64f5abb8d06cc66895c51f6a9c54fb,2026-03-14T11:00:00Z,"Cases of a virus with no vaccine and no specific treatment are popping up across the country. Its called human metapneumovirus, or HMPV, and it's on the rise nationwide, according to data from the Na… [+4366 chars]",health

In [11]:
TRUNC_PATTERN = re.compile(r"(\u2026|\.\.\.)\s*\[\+\d+\s+chars\]")

def clean_base_sentence(text: str) -> str:
    if not isinstance(text, str):
        return text

    # ✅ REMOVE NewsAPI truncation marker (ONLY in cleaned version)
    text = TRUNC_PATTERN.sub("", text)

    # Decode HTML entities
    text = html.unescape(text)

    # Remove UL/LI tags
    text = re.sub(r"</?ul>", "", text)
    text = re.sub(r"</?li>", " ", text)

    # Normalize whitespace
    text = re.sub(r"[\r\n]+", " ", text)
    text = re.sub(r"\s+", " ", text)

    return text.strip()

In [12]:
def build_prediction_dataframe(df):
    df = df.reset_index(drop=True).copy()
    df["article_id"] = df.index

    prediction_keywords = [
        "expected", "forecast", "forecasted", "forecasting",
        "forecast estimate", "forecasted outcome", "projected",
        "projection", "predict", "predicted", "estimate",
        "expectation", "anticipation", "prognosis",
        "speculation", "foretelling", "prophecy", "guess"
    ]

    pattern = r"\b(" + "|".join(map(re.escape, prediction_keywords)) + r")\b"

    df["prediction_visible"] = (
        (
            df["title"].fillna("") +
            df["description"].fillna("") +
            df["content"].fillna("")
        )
        .str.lower()
        .str.contains(pattern, regex=True)
    ).astype(int)

    parts = []
    for field, order in [("title", 0), ("description", 1), ("content", 2)]:
        tmp = df.copy()
        tmp["Base Sentence (raw)"] = tmp[field]   # ✅ RAW PRESERVED
        tmp["Source_Field"] = field
        tmp["field_order"] = order
        parts.append(tmp)

    long_df = pd.concat(parts, ignore_index=True)

    # ✅ CLEANED COLUMN (used downstream)
    long_df["Base Sentence"] = long_df["Base Sentence (raw)"].apply(clean_base_sentence)

    # ✅ Sentence splitting uses CLEAN text
    sfe = SpacyFeatureExtraction(long_df, "Base Sentence")
    long_df = sfe.split_into_sentences()

    # ✅ Label per sentence
    long_df["Sentence Label"] = (
        long_df["Base Sentence"]
        .str.lower()
        .str.contains(pattern, regex=True)
        .astype(int)
    )

    long_df["Human Annotation"] = ""
    long_df["Human Reasoning"] = ""

    priority_cols = [
        "Base Sentence",
        "Base Sentence (raw)",
        "Sentence Label",
        "Human Annotation",
        "Human Reasoning",
        "Source",
        "Date"
    ]

    priority_cols = [c for c in priority_cols if c in long_df.columns]
    remaining_cols = [c for c in long_df.columns if c not in priority_cols]

    return long_df[priority_cols + remaining_cols]

In [13]:
final_df = build_prediction_dataframe(df)
final_df.head(3)

/var/folders/78/9z0b45fx1xqbwxh8vk97lcfh0000gn/T/ipykernel_43161/543514960.py:22: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  .str.contains(pattern, regex=True)
/var/folders/78/9z0b45fx1xqbwxh8vk97lcfh0000gn/T/ipykernel_43161/543514960.py:46: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  .str.contains(pattern, regex=True)

,Base Sentence,Base Sentence (raw),Sentence Label,Human Annotation,Human Reasoning,Source,Date,Source Meta Data,title,description,URL,Image URL,content,Query Domain,article_id,prediction_visible,Source_Field,field_order
0,"Some of the Most Hyped Gym Supplements Are Fake, Unregulated, or Both","Some of the Most Hyped Gym Supplements Are Fake, Unregulated, or Both",0,,,Matthew Phelan,2026-03-27T19:05:43Z,"{'id': None, 'name': 'Gizmodo.com'}","Some of the Most Hyped Gym Supplements Are Fake, Unregulated, or Both","Worse, a new survey of 375 sports medicine experts has uncovered that some of most popular and sketchiest products aren't even on their radar yet.",https://gizmodo.com/some-of-the-most-hyped-gym-supplements-are-fake-unregulated-or-both-2000739118,https://gizmodo.com/app/uploads/2026/03/multivitamin-1200x675.jpg,"Doctors are only now starting to catch up on the weird, rapidly growing, and wildly unregulated world of underground bodybuilding supplements. Even with surging media attention on the rise of dubious… [+4820 chars]",health,0,0,title,0
1,Should You Be Taking Peptides?,Should You Be Taking Peptides?,0,,,Ed Cara,2026-03-12T14:00:01Z,"{'id': None, 'name': 'Gizmodo.com'}",Should You Be Taking Peptides?,"From GLP-1s to anti-aging cocktails, peptides are being widely marketed as wellness boosters. Here's what experts say you should know before you buy in.",https://gizmodo.com/should-you-be-taking-peptides-2000732422,https://gizmodo.com/app/uploads/2026/03/peptides-pipette-dropper-Giz-Asks-1200x675.jpg,“Peptides” has fast become one of the biggest buzzwords in the wellness world. And they’re likely to get even more public attention in the coming months and years.\r\nPeptides are simple chains of two … [+11438 chars],health,1,0,title,0
2,"In Medical First, a Single Therapy Knocked Out 3 Autoimmune Diseases at Once","In Medical First, a Single Therapy Knocked Out 3 Autoimmune Diseases at Once",0,,,Ed Cara,2026-04-09T15:00:25Z,"{'id': None, 'name': 'Gizmodo.com'}","In Medical First, a Single Therapy Knocked Out 3 Autoimmune Diseases at Once","CAR T-cell therapy could help tackle the most severe cases that haven't responded to other treatments, her doctors say. \n\nALT DEK: 14 months later, the woman still doesn't need any treatments for her conditions.",https://gizmodo.com/in-medical-first-a-single-therapy-knocked-out-3-autoimmune-diseases-at-once-2000744222,https://gizmodo.com/app/uploads/2026/04/B-cell-antibodies-1200x675.jpg,"In recent years, CAR T-cell therapy has become a revolutionary, if risky, treatment for some late-stage cancers. Yet CAR T may also have another life as a near-miraculous intervention for certain imm… [+4476 chars]",health,2,0,title,0

In [14]:
predictions_df = final_df[final_df["Sentence Label"] == 1]
predictions_df.head(3)

,Base Sentence,Base Sentence (raw),Sentence Label,Human Annotation,Human Reasoning,Source,Date,Source Meta Data,title,description,URL,Image URL,content,Query Domain,article_id,prediction_visible,Source_Field,field_order
263,RICCARDO MILANI/Hans Lucas/AFP via Getty Images The New York Times reported that telehealth startup Medvi has over $1 billion in projected sales.,RICCARDO MILANI/Hans Lucas/AFP via Getty Images\r\n<ul><li>The New York Times reported that telehealth startup Medvi has over $1 billion in projected sales.</li><li>Founder Matthew Gallagher used AI to… [+7064 chars],1,,,Jack Newsham,2026-04-06T23:14:50Z,"{'id': 'business-insider', 'name': 'Business Insider'}","Medvi, the AI-powered telehealth company, is fueled by ads from doctors who don't appear to exist",Medvi's marketing has included seemingly fake doctors and prompted lawsuits.,https://www.businessinsider.com/medvi-ai-weight-loss-millions-ai-advertising-legal-compliance-challenges-2026-4,https://i.insider.com/69d0328ae762ed6cfe44a3fb?width=1200&format=jpeg,RICCARDO MILANI/Hans Lucas/AFP via Getty Images\r\n<ul><li>The New York Times reported that telehealth startup Medvi has over $1 billion in projected sales.</li><li>Founder Matthew Gallagher used AI to… [+7064 chars],health,4,1,content,2
378,"Online sports betting is more popular than ever, with Americans expected to legally wager billions of dollars on this year's March Madness basketball tournament.","Online sports betting is more popular than ever, with Americans expected to legally wager billions of dollars on this year's March Madness basketball tournament. But a growing body of evidence reveal… [+5473 chars]",1,,,Alana Wise,2026-04-04T09:15:00Z,"{'id': None, 'name': 'NPR'}","When legal sports betting surges, so do Americans' financial problems","As online betting has grown in popularity, a new report from the New York Federal Reserve builds on the troubling link between legal sports wagering and financial health.",https://www.npr.org/2026/04/04/nx-s1-5773354/legal-sports-betting-research-credit-bankruptcy,https://npr.brightspotcdn.com/dims3/default/strip/false/crop/5037x2833+0+262/resize/1400/quality/85/format/jpeg/?url=http%3A%2F%2Fnpr-brightspot.s3.amazonaws.com%2F1d%2F75%2F55a395ee403e89e2c4c282794138%2Fap26022534309429.jpg,"Online sports betting is more popular than ever, with Americans expected to legally wager billions of dollars on this year's March Madness basketball tournament. But a growing body of evidence reveal… [+5473 chars]",health,58,1,content,2

In [15]:
predictions_df["Base Sentence"] = predictions_df["Base Sentence"].apply(clean_base_sentence)
predictions_df.head(3)

,Base Sentence,Base Sentence (raw),Sentence Label,Human Annotation,Human Reasoning,Source,Date,Source Meta Data,title,description,URL,Image URL,content,Query Domain,article_id,prediction_visible,Source_Field,field_order
263,RICCARDO MILANI/Hans Lucas/AFP via Getty Images The New York Times reported that telehealth startup Medvi has over $1 billion in projected sales.,RICCARDO MILANI/Hans Lucas/AFP via Getty Images\r\n<ul><li>The New York Times reported that telehealth startup Medvi has over $1 billion in projected sales.</li><li>Founder Matthew Gallagher used AI to… [+7064 chars],1,,,Jack Newsham,2026-04-06T23:14:50Z,"{'id': 'business-insider', 'name': 'Business Insider'}","Medvi, the AI-powered telehealth company, is fueled by ads from doctors who don't appear to exist",Medvi's marketing has included seemingly fake doctors and prompted lawsuits.,https://www.businessinsider.com/medvi-ai-weight-loss-millions-ai-advertising-legal-compliance-challenges-2026-4,https://i.insider.com/69d0328ae762ed6cfe44a3fb?width=1200&format=jpeg,RICCARDO MILANI/Hans Lucas/AFP via Getty Images\r\n<ul><li>The New York Times reported that telehealth startup Medvi has over $1 billion in projected sales.</li><li>Founder Matthew Gallagher used AI to… [+7064 chars],health,4,1,content,2
378,"Online sports betting is more popular than ever, with Americans expected to legally wager billions of dollars on this year's March Madness basketball tournament.","Online sports betting is more popular than ever, with Americans expected to legally wager billions of dollars on this year's March Madness basketball tournament. But a growing body of evidence reveal… [+5473 chars]",1,,,Alana Wise,2026-04-04T09:15:00Z,"{'id': None, 'name': 'NPR'}","When legal sports betting surges, so do Americans' financial problems","As online betting has grown in popularity, a new report from the New York Federal Reserve builds on the troubling link between legal sports wagering and financial health.",https://www.npr.org/2026/04/04/nx-s1-5773354/legal-sports-betting-research-credit-bankruptcy,https://npr.brightspotcdn.com/dims3/default/strip/false/crop/5037x2833+0+262/resize/1400/quality/85/format/jpeg/?url=http%3A%2F%2Fnpr-brightspot.s3.amazonaws.com%2F1d%2F75%2F55a395ee403e89e2c4c282794138%2Fap26022534309429.jpg,"Online sports betting is more popular than ever, with Americans expected to legally wager billions of dollars on this year's March Madness basketball tournament. But a growing body of evidence reveal… [+5473 chars]",health,58,1,content,2

In [16]:
predictions_df

,Base Sentence,Base Sentence (raw),Sentence Label,Human Annotation,Human Reasoning,Source,Date,Source Meta Data,title,description,URL,Image URL,content,Query Domain,article_id,prediction_visible,Source_Field,field_order
263,RICCARDO MILANI/Hans Lucas/AFP via Getty Images The New York Times reported that telehealth startup Medvi has over $1 billion in projected sales.,RICCARDO MILANI/Hans Lucas/AFP via Getty Images\r\n<ul><li>The New York Times reported that telehealth startup Medvi has over $1 billion in projected sales.</li><li>Founder Matthew Gallagher used AI to… [+7064 chars],1,,,Jack Newsham,2026-04-06T23:14:50Z,"{'id': 'business-insider', 'name': 'Business Insider'}","Medvi, the AI-powered telehealth company, is fueled by ads from doctors who don't appear to exist",Medvi's marketing has included seemingly fake doctors and prompted lawsuits.,https://www.businessinsider.com/medvi-ai-weight-loss-millions-ai-advertising-legal-compliance-challenges-2026-4,https://i.insider.com/69d0328ae762ed6cfe44a3fb?width=1200&format=jpeg,RICCARDO MILANI/Hans Lucas/AFP via Getty Images\r\n<ul><li>The New York Times reported that telehealth startup Medvi has over $1 billion in projected sales.</li><li>Founder Matthew Gallagher used AI to… [+7064 chars],health,4,1,content,2
378,"Online sports betting is more popular than ever, with Americans expected to legally wager billions of dollars on this year's March Madness basketball tournament.","Online sports betting is more popular than ever, with Americans expected to legally wager billions of dollars on this year's March Madness basketball tournament. But a growing body of evidence reveal… [+5473 chars]",1,,,Alana Wise,2026-04-04T09:15:00Z,"{'id': None, 'name': 'NPR'}","When legal sports betting surges, so do Americans' financial problems","As online betting has grown in popularity, a new report from the New York Federal Reserve builds on the troubling link between legal sports wagering and financial health.",https://www.npr.org/2026/04/04/nx-s1-5773354/legal-sports-betting-research-credit-bankruptcy,https://npr.brightspotcdn.com/dims3/default/strip/false/crop/5037x2833+0+262/resize/1400/quality/85/format/jpeg/?url=http%3A%2F%2Fnpr-brightspot.s3.amazonaws.com%2F1d%2F75%2F55a395ee403e89e2c4c282794138%2Fap26022534309429.jpg,"Online sports betting is more popular than ever, with Americans expected to legally wager billions of dollars on this year's March Madness basketball tournament. But a growing body of evidence reveal… [+5473 chars]",health,58,1,content,2

In [17]:
len(predictions_df)

2

In [ ]:
def build_query_package(
    *,
    query_string: str,
    query_domain: str, 
    start_date: str,
    end_date: str,
    df,
    final_df,
    predictions_df,
    language: str = "en",
    sort_by: str = "relevancy",
    page_size: int = None
):
    """
    Builds a query-aligned package and a deterministic filename prefix.
    """

    # -------------------------
    # Prefix from query
    # -------------------------
    base_prefix = (
        query_string.lower()
        .replace(" or ", "_")
        .replace(" and ", "_")
        .replace(" ", "_")
    )
    base_prefix = re.sub(r"[^a-z0-9_]", "", base_prefix)
    base_prefix = re.sub(r"_+", "_", base_prefix).strip("_")

    prefix = f"{base_prefix}_{start_date}_to_{end_date}"

    # -------------------------
    # Query metadata
    # -------------------------
    query_meta = {
        "query": query_string,
        "query_domain": query_domain,
        "language": language,
        "from_date": start_date,
        "to_date": end_date,
        "sort_by": sort_by,
        "page_size": page_size,
        "timestamp_utc": datetime.utcnow().isoformat()
    }

    # -------------------------
    # Full package
    # -------------------------
    package = {
        "query_meta": query_meta,
        "counts": {
            "num_raw_articles": len(df),
            "num_sentences": len(final_df),
            "num_potential_predictions": len(predictions_df)
        },
        "raw_articles": df.to_dict(orient="records"),
        "processed_sentences": final_df.to_dict(orient="records"),
        "potential_predictions": predictions_df.to_dict(orient="records")
    }

    return prefix, package

In [ ]:
if len(predictions_df) >= 1: 
    prefix, query_package = build_query_package(
        query_string=QUERY_CONFIGS[list_num]["query"],
        query_domain=QUERY_CONFIGS[list_num]["query_domain"],
        start_date=start_date,
        end_date=end_date,
        df=df,
        final_df=final_df,
        predictions_df=predictions_df,
        page_size=7
    )

In [ ]:
base_data_path = DataProcessing.load_base_data_path(notebook_dir)
save_path = os.path.join(base_data_path, 'news_api', 'annotators')

if len(predictions_df) >= 1: 
    DataProcessing.save_to_file(
        data=predictions_df,
        path=save_path,
        prefix=f"{prefix}_predictions",
        save_file_type="csv"
    )

In [ ]:
if len(predictions_df) >= 1: 
    DataProcessing.save_to_file(
        data=query_package,
        path=save_path,
        prefix=f"{prefix}_full",
        save_file_type="json"
    )