## Data Acquisition: News API

In [1]:
import os
import sys

import pandas as pd

from newsapi import NewsApiClient
from dotenv import load_dotenv
load_dotenv()

# Get the current working directory of the notebook
notebook_dir = os.getcwd()
# Add the parent directory to the system path
sys.path.append(os.path.join(notebook_dir, '../'))

from data_processing import DataProcessing

In [2]:
pd.set_option('max_colwidth', 800)
# pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [3]:
api_key = os.getenv('NEWS_API_KEY')

In [4]:
# 2026-02-28 to today

In [5]:
newsapi = NewsApiClient(api_key=api_key)

# # /v2/top-headlines
# # top_headlines = newsapi.get_top_headlines(q='bitcoin',
# #                                           sources='bbc-news,the-verge',
# #                                           category='business',
# #                                           language='en',
# #                                           country='us')

# # /v2/everything
# all_articles = newsapi.get_everything(q='bitcoin',
#                                       sources='bbc-news,the-verge',
#                                       domains='bbc.co.uk,techcrunch.com',
#                                       from_param='2026-02-29',
#                                       to='2026-03-28',
#                                       language='en',
#                                       sort_by='relevancy',
#                                       page=2)

# # /v2/top-headlines/sources
# sources = newsapi.get_sources()
# sources

In [6]:
all_articles = newsapi.get_everything(
    # q='forecast OR predict OR expected OR likely OR outlook OR "is expected to" OR "will likely" OR "set to" OR "projected to"',
    q=' Tesla OR SAE Level 4 autonomy',
    language='en',
    from_param='2026-03-21',
    to='2026-03-28',
    sort_by='relevancy',
    page_size=100
)

all_articles

{'status': 'ok',
 'totalResults': 48,
 'articles': [{'source': {'id': None, 'name': 'Fast Company'},
   'author': 'Victor Dey',
   'title': 'The most innovative manufacturing companies for 2026',
   'description': 'Manufacturing rarely announces its reinventions dramatically. Change arrives instead through pressure on energy, labor, and supply chains. Over the past year, those pressures have converged to drive a broad reconsideration of production intelligence. Across s…',
   'url': 'https://www.fastcompany.com/91497254/manufacturing-most-innovative-companies-2026',
   'urlToImage': 'https://images.fastcompany.com/image/upload/f_webp,q_auto,c_fit/wp-cms-2/2026/03/p-1b-2026-MIC-sectors-manufacturing.jpg',
   'publishedAt': '2026-03-24T11:00:00Z',
   'content': 'Manufacturing rarely announces its reinventions dramatically. Change arrives instead through pressure on energy, labor, and supply chains. Over the past year, those pressures have converged to drive … [+2852 chars]'},
  {'source': {'id': None, 'name': 'The Indian Express'},
   'author': 'Rajib Dasgupta, Kamini Walia',
   'title': 'For public-health reform, fix urban governance',
   'description': 'Urban public health crises are often framed narrowly in terms of hospital shortages and workforce gaps. Less visible, but arguably more consequential, are failures in everyday urban systems.',
   'url': 'https://indianexpress.com/article/opinion/columns/for-public-health-reform-fix-urban-governance-10595709/',
   'urlToImage': 'https://images.indianexpress.com/2026/03/urbanisation_20260322194612.jpg',
   'publishedAt': '2026-03-23T01:00:04Z',
   'content': 'The Union cabinet recently approved the launch of the Urban Challenge Fund (UCF), worth Rs 4 lakh crore. The Centre will provide an assistance of Rs 1 lakh crore, and at least 50 per cent of the cost… [+3863 chars]'},
  {'source': {'id': None, 'name': 'Composio.dev'},
   'author': 'Sunil Kumar Dash',
   'title': 'OpenClaw Is a Security Nightmare Dressed Up as a Daydream',
   'description': 'Composio content pages powered by our CMS, including tutorials, product updates, and guides.',
   'url': 'https://composio.dev/content/openclaw-security-and-vulnerabilities',
   'urlToImage': 'https://framerusercontent.com/images/H9WhU9hmMWK1TcazYTRy6t5owos.png',
   'publishedAt': '2026-03-22T17:35:28Z',
   'content': 'Back in 2023, the internet was buzzing about AutoGPT and BabyAGI. It was just after GPT-4 had arrived. Everyone was talking about autonomous agents taking jobs, how they can, and I remember how scare… [+27266 chars]'},
  {'source': {'id': None, 'name': 'Nvidia.com'},
   'author': 'Lachlan Dowling',
   'title': 'How Centralized Radar Processing on NVIDIA DRIVE Enables Safer, Smarter Level 4 Autonomy',
   'description': "In the current state of automotive radar, machine learning engineers can't work with camera-equivalent raw RGB images. Instead, they work with the output of...",
   'url': 'https://developer.nvidia.com/blog/how-centralized-radar-processing-on-nvidia-drive-enables-safer-smarter-level-4-autonomy/',
   'urlToImage': 'https://developer-blogs.nvidia.com/wp-content/uploads/2026/03/Feature-1024x576.gif',
   'publishedAt': '2026-03-25T15:58:59Z',
   'content': 'In the current state of automotive radar, machine learning engineers can’t work with camera-equivalent raw RGB images. Instead, they work with the output of radar constant false alarm rate (CFAR), wh… [+12682 chars]'},
  {'source': {'id': None, 'name': 'Radaronline.com'},
   'author': 'Aaron Tinney',
   'title': "EXCLUSIVE: Britney Spears 'Haunted by PTSD' Over Conservatorship as Pop Singer Faces Being Put Back Under Family's Control in Wake of DUI Arrest",
   'description': 'Britney Spears is said to be in fear of losing control again after a DUI arrest.',
   'url': 'https://radaronline.com/p/britney-spears-ptsd-conservatorship-dui-fears/',
   'urlToImage': 'https://media.radaronline.com/brand-img/-Ip2vRpze/1200x628/britney-spears-ptsd-conservatorship-dui-fears-pp-1774027327724.jpg',
   'publishedAt': '2026-03-21T22:00:00Z',
   'content': 'Britney Spears is said to be "haunted" by fears of losing her freedom again after her recent DUI arrest, with insiders claiming the pop star is grappling with severe anxiety that could reopen the doo… [+3230 chars]'},
  {'source': {'id': None, 'name': 'GlobeNewswire'},
   'author': 'SNS Insider pvt ltd',
   'title': 'Software Defined Vehicles Market Projected to Reach USD 4,663.54 Billion by 2035, Owing to EV Adoption and Software-Defined Automotive Platforms | Research by SNS Insider',
   'description': 'The Software Defined Vehicles Market is expanding rapidly as automakers adopt OTA updates, AI-driven systems, and connected vehicle platforms, with the U.S. segment growing from USD 109.86 billion in 2025 to USD 1,838.25 billion by 2035. The Software Defined …',
   'url': 'https://www.globenewswire.com/news-release/2026/03/23/3260196/0/en/Software-Defined-Vehicles-Market-Projected-to-Reach-USD-4-663-54-Billion-by-2035-Owing-to-EV-Adoption-and-Software-Defined-Automotive-Platforms-Research-by-SNS-Insider.html',
   'urlToImage': 'https://ml.globenewswire.com/Resource/Download/d6272c2e-d204-41b8-b545-a6e2e24f85c2',
   'publishedAt': '2026-03-23T10:14:00Z',
   'content': 'Austin, March 23, 2026 (GLOBE NEWSWIRE) -- The\xa0Software Defined Vehicles Market\xa0size\xa0was estimated\xa0at USD 278.35 billion in 2025 and is expected to reach USD 4,663.54 billion by 2035, growing at a CA… [+8225 chars]'},
  {'source': {'id': None, 'name': "Paul Tan's Automotive News"},
   'author': 'Jonathan Lee',
   'title': '2026 Xpeng X9 EV facelift in Thailand – REEV looks, new 537 PS AWD, 615 km WLTP range, 542 kW DCFC',
   'description': 'Another year, another “facelift” for the Xpeng X9, which went on sale in Thailand last week – just two weeks after it was launched in China. This time, the changes, seen at the ongoing Bangkok International Motor Show (BIMS), are much more substantial, albeit…',
   'url': 'https://paultan.org/2026/03/27/2026-xpeng-x9-ev-facelift-in-thailand-reev-looks-new-537-ps-awd-615-km-wltp-range-542-kw-dcfc/',
   'urlToImage': 'https://paultan.org/image/2026/03/2026-BIMS-Xpeng-X9-1-1200x801.jpg',
   'publishedAt': '2026-03-27T09:28:15Z',
   'content': 'Another year, another “facelift” for the Xpeng X9, which went on sale in Thailand last week just two weeks after it was launched in China. This time, the changes, seen at the ongoing Bangkok Internat… [+3823 chars]'},
  {'source': {'id': None, 'name': 'Ieee.org'},
   'author': 'Tereza Pultarova',
   'title': 'The Coming Drone-War Inflection in Ukraine',
   'description': 'WHEN KYIV-BORN ENGINEER Yaroslav Azhnyuk thinks about the future, his mind conjures up dystopian images. He talks about “swarms of autonomous drones carrying other autonomous drones to protect them against autonomous drones, which are trying to intercept them…',
   'url': 'https://spectrum.ieee.org/autonomous-drone-warfare',
   'urlToImage': 'https://spectrum.ieee.org/media-library/image.jpg?id=65327392&width=1200&height=600&coordinates=0%2C15%2C0%2C15',
   'publishedAt': '2026-03-24T13:00:05Z',
   'content': 'WHENKYIV-BORNENGINEER Yaroslav Azhnyuk thinks about the future, his mind conjures up dystopian images. He talks about swarms of autonomous drones carrying other autonomous drones to protect them agai… [+24029 chars]'},
  {'source': {'id': None, 'name': 'Bradenkelley.com'},
   'author': 'Braden Kelley',
   'title': 'Neo-Feudalism and Innovation Impact',
   'description': 'A System Designed to Concentrate Power – or Accelerate Breakthroughs? LAST UPDATED: March 27, 2026 at 4:55 PM by Braden Kelley and Art Inteligencia The Return of Lords and Serfs — But This Time It’s Digital For decades, we’ve told ourselves a reassuring story…',
   'url': 'https://bradenkelley.com/2026/03/neo-feudalism-and-innovation-impact/',
   'urlToImage': None,
   'publishedAt': '2026-03-28T00:57:48Z',
   'content': 'A System Designed to Concentrate Power – or Accelerate Breakthroughs?\r\nLAST UPDATED: March 27, 2026 at 4:55 PM\r\nby Braden Kelley and Art Inteligencia\r\nThe Return of Lords and Serfs But This Time Its … [+20133 chars]'},
  {'source': {'id': None, 'name': 'Geeky Gadgets'},
   'author': 'Julian Horsey',
   'title': 'The 5 Stages of AI: What Comes After ChatGPT?',
   'description': 'Artificial intelligence is advancing through five distinct stages, each representing a fantastic leap in capability and impact. Parker Prompts explores these stages, starting with the foundational role of large language models (LLMs) like ChatGPT and Gemini, …',
   'url': 'https://www.geeky-gadgets.com/five-stages-ai/',
   'urlToImage': 'https://www.geeky-gadgets.com/wp-content/uploads/2026/03/stage-2-agentic-ai-assistant-tasks.jpg',
   'publishedAt': '2026-03-27T08:45:52Z',
   'content': 'Artificial intelligence is advancing through five distinct stages, each representing a fantastic leap in capability and impact. Parker Prompts explores these stages, starting with the foundational ro… [+8392 chars]'},
  {'source': {'id': None, 'name': 'Okfn.org'},
   'author': 'Bianca Kramer',
   'title': 'Open Data Day essay #4: ‘Open access and open data alone are not enough’',
   'description': 'The Barcelona Declaration on Open Research Information was launched in 2024 as an initiative to encourage research institutions and research funders to actively contribute to the open availability of research information.\nThe post Open Data Day essay #4: ‘Ope…',
   'url': 'https://blog.okfn.org/2026/03/24/open-data-day-essay-4-open-access-and-open-data-alone-are-not-enough/',
   'urlToImage': 'https://blog.okfn.org/wp-content/uploads/2026/03/1.png',
   'publishedAt': '2026-03-24T19:39:37Z',
   'content': 'This text is part of a series of essays dedicated to Open Data Day, organised by Open State Foundation and Open Nederland. The Open Knowledge Foundation is proud to be a publishing partner.\r\nOpen acc… [+7850 chars]'},
  {'source': {'id': None, 'name': 'The Indian Express'},
   'author': 'Priya Kumari Shukla',
   'title': 'UPSC Key: Iran peace plan, CAPF Bill and Finance Bill',
   'description': 'Why is India’s updated Nationally Determined Contributions relevant to the UPSC exam? What is the significance of topics such as the BRICS, Women’s Reservation Act, and the Transgender Persons (Protection of Rights) Amendment Bill, 2026 on both the preliminar…',
   'url': 'https://indianexpress.com/article/upsc-current-affairs/upsc-key-iran-peace-plan-capf-bill-and-finance-bill-10602999/',
   'urlToImage': 'https://images.indianexpress.com/2026/03/UPSC-Key-26th-March-2026.jpg',
   'publishedAt': '2026-03-26T13:20:23Z',
   'content': 'Preliminary Examination: Current events of national and international importance.Mains Examination:\xa0General Studies II: Bilateral, regional and global groupings and agreements involving India and/or … [+37635 chars]'},
  {'source': {'id': None, 'name': 'mindbodygreen.com'},
   'author': 'https://www.mindbodygreen.com/wc/dr-perpetua-neo',
   'title': "I'm Clinical Psychologist: Here's How I Actually Take Care Of My Mental Health",
   'description': 'Clients often ask me, as a clinical psychologist, how <em>I</em> actually care for my mental health.',
   'url': 'https://www.mindbodygreen.com/articles/im-psychologist-and-this-is-how-i-take-care-of-my-mental-health',
   'urlToImage': 'https://mindbodygreen-res.cloudinary.com/image/upload/c_fill,w_2000,h_1200,g_auto,fl_lossy,f_jpg/org/1773240851781_cwhsazit1l7.jpg',
   'publishedAt': '2026-03-27T10:08:00Z',
   'content': "Clients often ask me, as a clinical psychologist, how I actually care for my mental health. Sure, I have my coaches and therapists, I take supplements and make sure to get my steps in, And yes, I'll … [+21431 chars]"},
  {'source': {'id': None, 'name': 'Saastr.com'},
   'author': 'Jason Lemkin',
   'title': 'You Can’t Train an AI Agent and Then Just … Go Away. We Did, It Fell Off The Rails. And We Didn’t Even Know.',
   'description': 'We have an AI agent that we use all the time.\xa0 One of our now almost 30.\xa0 It’s a good one, people really like it, and importantly, it’s not directly connected to revenue.\xa0 So we made a biggish mistake.\xa0 We sort of ignored it once it worked and was dialed in. …',
   'url': 'https://www.saastr.com/you-cant-train-an-ai-agent-and-then-just-go-away-we-did-and-it-fell-off-the-rails/',
   'urlToImage': 'https://i0.wp.com/www.saastr.com/wp-content/uploads/2026/03/Action-Movie-Text-scaled.jpg?fit=1000%2C565&quality=70&ssl=1',
   'publishedAt': '2026-03-24T14:10:15Z',
   'content': 'We have an AI agent that we use all the time.\xa0 One of our now almost 30.\xa0 It’s a good one, people really like it, and importantly, it’s not directly connected to revenue.\xa0 So we made a biggish mistak… [+9609 chars]'},
  {'source': {'id': None, 'name': 'BusinessLine'},
   'author': 'PTI',
   'title': 'Over half of countries have banned phones in schools: UNESCO',
   'description': 'UNESCO reports that over half of countries have banned phones in schools to combat cyberbullying and improve attention in classrooms.',
   'url': 'https://www.thehindubusinessline.com/news/over-half-of-countries-have-banned-phones-in-schools-unesco/article70771814.ece',
   'urlToImage': 'https://bl-i.thgim.com/public/incoming/qy7quf/article70771825.ece/alternates/LANDSCAPE_1200/BL07_Think_Smartphone.jpg',
   'publishedAt': '2026-03-22T07:59:51Z',
   'content': "More than half of the countries have banned phones in schools amid mounting concerns about declining attention in classrooms and cyberbullying, according to the UNSECO's Global Education Monitoring (… [+3882 chars]"},
  {'source': {'id': None, 'name': 'Whatjapanthinks.com'},
   'author': 'Ken Y-N',
   'title': 'Hoshimachi Suisei’s New Studio: A Defining Moment for an Idol, Artist, and Visionary',
   'description': 'Hoshimachi Suisei has always occupied a rare space in the digital entertainment landscape. She isn’t just a VTuber or idol; she’s a performer, musician, and creative force who has forged her own path long before global audiences fully recognized her impact. N…',
   'url': 'https://whatjapanthinks.com/hoshimachi-suiseis-new-studio/',
   'urlToImage': 'https://whatjapanthinks.com/wp-content/uploads/2026/03/Hoshimachi-Suiseis-New-Studio.webp',
   'publishedAt': '2026-03-23T06:37:16Z',
   'content': 'Hoshimachi Suisei has always occupied a rare space in the digital entertainment landscape. She isnt just a VTuber or idol; shes a performer, musician, and creative force who has forged her own path l… [+6287 chars]'},
  {'source': {'id': None, 'name': 'Europa.eu'},
   'author': 'European Central Bank',
   'title': 'Luis de Guindos: Navigating turbulence: challenges for Europe and the path ahead',
   'description': 'The European Central Bank (ECB) is the central bank of the European Union countries which have adopted the euro. Our main task is to maintain price stability in the euro area and so preserve the purchasing power of the single currency.',
   'url': 'https://www.ecb.europa.eu//press/key/date/2026/html/ecb.sp260326~cbb4721baf.en.html',
   'urlToImage': 'https://www.ecb.europa.eu/press/key/shared/img/socialmedia/social-default.jpg?0dbb2de262f4f1fcaeae410be132177a',
   'publishedAt': '2026-03-26T09:00:00Z',
   'content': 'Speech by Luis de Guindos, Vice-President of the ECB, at the Ragnar Nurkse Memorial Lecture organised by Eesti Pank\r\nTallinn, 26 March 2026\r\nIntroduction\r\nIt is a privilege to be here in Tallinn to d… [+11915 chars]'},
  {'source': {'id': None, 'name': 'Uxpin.com'},
   'author': 'Andrew Martin',
   'title': 'How to build UI using GPT-4.1 + Custom Design Systems – Use UXPin Merge!',
   'description': 'Generate production-ready React UI components from prompts using GPT-4.1 and sync them to your design system with UXPin Merge.\nThe post How to build UI using GPT-4.1 + Custom Design Systems – Use UXPin Merge! appeared first on Studio by UXPin.',
   'url': 'https://www.uxpin.com/studio/blog/build-ui-gpt-4-1-custom-design-systems-uxpin-merge/',
   'urlToImage': 'https://studio.uxpincdn.com/studio/wp-content/uploads/2026/03/image_75fcbd81dd136b1694d9c0ef493cff5b.jpeg.webp',
   'publishedAt': '2026-03-26T09:38:05Z',
   'content': 'Building user interfaces just got faster and easier. By combining GPT-4.1‘s ability to generate React components from text prompts with UXPin Merge‘s support for design systems, you can create produc… [+19470 chars]'},
  {'source': {'id': None, 'name': 'Fair Observer'},
   'author': 'Thomas Greminger',
   'title': 'The Agency of Middle Powers in a Fragmented and Polarized World',
   'description': 'Middle powers face both challenges and opportunities. If the international system fractures further, it will not be because the great powers disagree. They have always disagreed on some level. It will fracture instead, because the space between them collapses…',
   'url': 'https://www.fairobserver.com/economics/the-agency-of-middle-powers-in-a-fragmented-and-polarized-world/',
   'urlToImage': 'https://www.fairobserver.com/wp-content/uploads/2026/03/business-partnership.jpg',
   'publishedAt': '2026-03-27T14:24:54Z',
   'content': 'Middle powers face both challenges and opportunities. If the international system fractures further, it will not be because the great powers disagree. They have always disagreed on some level. It wil… [+14775 chars]'},
  {'source': {'id': None, 'name': 'InfoQ.com'},
   'author': 'Anurag Kale',
   'title': 'Presentation: Data Mesh in Action: A Journey From Ideation to Implementation',
   'description': 'Anurag Kale discusses the transition from centralized data bottlenecks to a decentralized Data Mesh architecture at Horse Powertrain. He explains the four pillars - domain ownership, data as a product, self-serve platforms, and federated governance - to empow…',
   'url': 'https://www.infoq.com/presentations/data-mesh-horse-powertrain/',
   'urlToImage': 'https://res.infoq.com/presentations/data-mesh-horse-powertrain/en/card_header_image/anurag-kale-twitter-card-1773151647473.jpg',
   'publishedAt': '2026-03-23T11:43:00Z',
   'content': "Transcript\r\nAnurag Kale: I would just like to quickly understand, how many of you here are data professionals? You're working with data somehow? Software engineers? Architects? Product people? Today … [+41789 chars]"},
  {'source': {'id': None, 'name': 'GlobeNewswire'},
   'author': 'Focal',
   'title': "Focal Named to Fast Company's List of the World's Most Innovative Companies of 2026",
   'description': "Focal Named to Fast Company's List of the World's Most Innovative Companies of 2026...",
   'url': 'https://www.globenewswire.com/news-release/2026/03/24/3261081/0/en/Focal-Named-to-Fast-Company-s-List-of-the-World-s-Most-Innovative-Companies-of-2026.html',
   'urlToImage': 'https://ml.globenewswire.com/Resource/Download/4e5a591f-b331-49c2-942c-dfe124ab8dc1',
   'publishedAt': '2026-03-24T11:10:00Z',
   'content': "SAN FRANCISCO, March 24, 2026 (GLOBE NEWSWIRE) -- Focal, an AI-enabled robotic heating company and the creator of the world's first autonomous personal comfort platform, today announced it has earned… [+5480 chars]"},
  {'source': {'id': None, 'name': 'Livemint'},
   'author': 'Jocelyn Fernandes',
   'title': 'Must shift AI from adoption to transformation: Deloitte says Indian firms lag behind global peers in expertise',
   'description': "Deloitte's survey reveals a significant shift is needed for companies to meaningfully integrate AI into operations. It also noted that while Indian firms are top of the list in AI adoption, there is a capability gap compared to peers.&nbsp;",
   'url': 'https://www.livemint.com/companies/news/ai-shift-adoption-transformation-deloitte-state-of-ai-in-enterprise-report-says-indian-firms-lag-global-peers-expertise-11774170839704.html',

In [7]:
all_articles.keys()

dict_keys(['status', 'totalResults', 'articles'])

In [8]:
len(all_articles['articles']), all_articles['articles']

(48,
 [{'source': {'id': None, 'name': 'Fast Company'},
   'author': 'Victor Dey',
   'title': 'The most innovative manufacturing companies for 2026',
   'description': 'Manufacturing rarely announces its reinventions dramatically. Change arrives instead through pressure on energy, labor, and supply chains. Over the past year, those pressures have converged to drive a broad reconsideration of production intelligence. Across s…',
   'url': 'https://www.fastcompany.com/91497254/manufacturing-most-innovative-companies-2026',
   'urlToImage': 'https://images.fastcompany.com/image/upload/f_webp,q_auto,c_fit/wp-cms-2/2026/03/p-1b-2026-MIC-sectors-manufacturing.jpg',
   'publishedAt': '2026-03-24T11:00:00Z',
   'content': 'Manufacturing rarely announces its reinventions dramatically. Change arrives instead through pressure on energy, labor, and supply chains. Over the past year, those pressures have converged to drive … [+2852 chars]'},
  {'source': {'id': None, 'name': 'The Indian Express'},
   'author': 'Rajib Dasgupta, Kamini Walia',
   'title': 'For public-health reform, fix urban governance',
   'description': 'Urban public health crises are often framed narrowly in terms of hospital shortages and workforce gaps. Less visible, but arguably more consequential, are failures in everyday urban systems.',
   'url': 'https://indianexpress.com/article/opinion/columns/for-public-health-reform-fix-urban-governance-10595709/',
   'urlToImage': 'https://images.indianexpress.com/2026/03/urbanisation_20260322194612.jpg',
   'publishedAt': '2026-03-23T01:00:04Z',
   'content': 'The Union cabinet recently approved the launch of the Urban Challenge Fund (UCF), worth Rs 4 lakh crore. The Centre will provide an assistance of Rs 1 lakh crore, and at least 50 per cent of the cost… [+3863 chars]'},
  {'source': {'id': None, 'name': 'Composio.dev'},
   'author': 'Sunil Kumar Dash',
   'title': 'OpenClaw Is a Security Nightmare Dressed Up as a Daydream',
   'description': 'Composio content pages powered by our CMS, including tutorials, product updates, and guides.',
   'url': 'https://composio.dev/content/openclaw-security-and-vulnerabilities',
   'urlToImage': 'https://framerusercontent.com/images/H9WhU9hmMWK1TcazYTRy6t5owos.png',
   'publishedAt': '2026-03-22T17:35:28Z',
   'content': 'Back in 2023, the internet was buzzing about AutoGPT and BabyAGI. It was just after GPT-4 had arrived. Everyone was talking about autonomous agents taking jobs, how they can, and I remember how scare… [+27266 chars]'},
  {'source': {'id': None, 'name': 'Nvidia.com'},
   'author': 'Lachlan Dowling',
   'title': 'How Centralized Radar Processing on NVIDIA DRIVE Enables Safer, Smarter Level 4 Autonomy',
   'description': "In the current state of automotive radar, machine learning engineers can't work with camera-equivalent raw RGB images. Instead, they work with the output of...",
   'url': 'https://developer.nvidia.com/blog/how-centralized-radar-processing-on-nvidia-drive-enables-safer-smarter-level-4-autonomy/',
   'urlToImage': 'https://developer-blogs.nvidia.com/wp-content/uploads/2026/03/Feature-1024x576.gif',
   'publishedAt': '2026-03-25T15:58:59Z',
   'content': 'In the current state of automotive radar, machine learning engineers can’t work with camera-equivalent raw RGB images. Instead, they work with the output of radar constant false alarm rate (CFAR), wh… [+12682 chars]'},
  {'source': {'id': None, 'name': 'Radaronline.com'},
   'author': 'Aaron Tinney',
   'title': "EXCLUSIVE: Britney Spears 'Haunted by PTSD' Over Conservatorship as Pop Singer Faces Being Put Back Under Family's Control in Wake of DUI Arrest",
   'description': 'Britney Spears is said to be in fear of losing control again after a DUI arrest.',
   'url': 'https://radaronline.com/p/britney-spears-ptsd-conservatorship-dui-fears/',
   'urlToImage': 'https://media.radaronline.com/brand-img/-Ip2vRpze/1200x628/britney-spears-ptsd-conservatorship-dui-fears-pp-1774027327724.jpg',
   'publishedAt': '2026-03-21T22:00:00Z',
   'content': 'Britney Spears is said to be "haunted" by fears of losing her freedom again after her recent DUI arrest, with insiders claiming the pop star is grappling with severe anxiety that could reopen the doo… [+3230 chars]'},
  {'source': {'id': None, 'name': 'GlobeNewswire'},
   'author': 'SNS Insider pvt ltd',
   'title': 'Software Defined Vehicles Market Projected to Reach USD 4,663.54 Billion by 2035, Owing to EV Adoption and Software-Defined Automotive Platforms | Research by SNS Insider',
   'description': 'The Software Defined Vehicles Market is expanding rapidly as automakers adopt OTA updates, AI-driven systems, and connected vehicle platforms, with the U.S. segment growing from USD 109.86 billion in 2025 to USD 1,838.25 billion by 2035. The Software Defined …',
   'url': 'https://www.globenewswire.com/news-release/2026/03/23/3260196/0/en/Software-Defined-Vehicles-Market-Projected-to-Reach-USD-4-663-54-Billion-by-2035-Owing-to-EV-Adoption-and-Software-Defined-Automotive-Platforms-Research-by-SNS-Insider.html',
   'urlToImage': 'https://ml.globenewswire.com/Resource/Download/d6272c2e-d204-41b8-b545-a6e2e24f85c2',
   'publishedAt': '2026-03-23T10:14:00Z',
   'content': 'Austin, March 23, 2026 (GLOBE NEWSWIRE) -- The\xa0Software Defined Vehicles Market\xa0size\xa0was estimated\xa0at USD 278.35 billion in 2025 and is expected to reach USD 4,663.54 billion by 2035, growing at a CA… [+8225 chars]'},
  {'source': {'id': None, 'name': "Paul Tan's Automotive News"},
   'author': 'Jonathan Lee',
   'title': '2026 Xpeng X9 EV facelift in Thailand – REEV looks, new 537 PS AWD, 615 km WLTP range, 542 kW DCFC',
   'description': 'Another year, another “facelift” for the Xpeng X9, which went on sale in Thailand last week – just two weeks after it was launched in China. This time, the changes, seen at the ongoing Bangkok International Motor Show (BIMS), are much more substantial, albeit…',
   'url': 'https://paultan.org/2026/03/27/2026-xpeng-x9-ev-facelift-in-thailand-reev-looks-new-537-ps-awd-615-km-wltp-range-542-kw-dcfc/',
   'urlToImage': 'https://paultan.org/image/2026/03/2026-BIMS-Xpeng-X9-1-1200x801.jpg',
   'publishedAt': '2026-03-27T09:28:15Z',
   'content': 'Another year, another “facelift” for the Xpeng X9, which went on sale in Thailand last week just two weeks after it was launched in China. This time, the changes, seen at the ongoing Bangkok Internat… [+3823 chars]'},
  {'source': {'id': None, 'name': 'Ieee.org'},
   'author': 'Tereza Pultarova',
   'title': 'The Coming Drone-War Inflection in Ukraine',
   'description': 'WHEN KYIV-BORN ENGINEER Yaroslav Azhnyuk thinks about the future, his mind conjures up dystopian images. He talks about “swarms of autonomous drones carrying other autonomous drones to protect them against autonomous drones, which are trying to intercept them…',
   'url': 'https://spectrum.ieee.org/autonomous-drone-warfare',
   'urlToImage': 'https://spectrum.ieee.org/media-library/image.jpg?id=65327392&width=1200&height=600&coordinates=0%2C15%2C0%2C15',
   'publishedAt': '2026-03-24T13:00:05Z',
   'content': 'WHENKYIV-BORNENGINEER Yaroslav Azhnyuk thinks about the future, his mind conjures up dystopian images. He talks about swarms of autonomous drones carrying other autonomous drones to protect them agai… [+24029 chars]'},
  {'source': {'id': None, 'name': 'Bradenkelley.com'},
   'author': 'Braden Kelley',
   'title': 'Neo-Feudalism and Innovation Impact',
   'description': 'A System Designed to Concentrate Power – or Accelerate Breakthroughs? LAST UPDATED: March 27, 2026 at 4:55 PM by Braden Kelley and Art Inteligencia The Return of Lords and Serfs — But This Time It’s Digital For decades, we’ve told ourselves a reassuring story…',
   'url': 'https://bradenkelley.com/2026/03/neo-feudalism-and-innovation-impact/',
   'urlToImage': None,
   'publishedAt': '2026-03-28T00:57:48Z',
   'content': 'A System Designed to Concentrate Power – or Accelerate Breakthroughs?\r\nLAST UPDATED: March 27, 2026 at 4:55 PM\r\nby Braden Kelley and Art Inteligencia\r\nThe Return of Lords and Serfs But This Time Its … [+20133 chars]'},
  {'source': {'id': None, 'name': 'Geeky Gadgets'},
   'author': 'Julian Horsey',
   'title': 'The 5 Stages of AI: What Comes After ChatGPT?',
   'description': 'Artificial intelligence is advancing through five distinct stages, each representing a fantastic leap in capability and impact. Parker Prompts explores these stages, starting with the foundational role of large language models (LLMs) like ChatGPT and Gemini, …',
   'url': 'https://www.geeky-gadgets.com/five-stages-ai/',
   'urlToImage': 'https://www.geeky-gadgets.com/wp-content/uploads/2026/03/stage-2-agentic-ai-assistant-tasks.jpg',
   'publishedAt': '2026-03-27T08:45:52Z',
   'content': 'Artificial intelligence is advancing through five distinct stages, each representing a fantastic leap in capability and impact. Parker Prompts explores these stages, starting with the foundational ro… [+8392 chars]'},
  {'source': {'id': None, 'name': 'Okfn.org'},
   'author': 'Bianca Kramer',
   'title': 'Open Data Day essay #4: ‘Open access and open data alone are not enough’',
   'description': 'The Barcelona Declaration on Open Research Information was launched in 2024 as an initiative to encourage research institutions and research funders to actively contribute to the open availability of research information.\nThe post Open Data Day essay #4: ‘Ope…',
   'url': 'https://blog.okfn.org/2026/03/24/open-data-day-essay-4-open-access-and-open-data-alone-are-not-enough/',
   'urlToImage': 'https://blog.okfn.org/wp-content/uploads/2026/03/1.png',
   'publishedAt': '2026-03-24T19:39:37Z',
   'content': 'This text is part of a series of essays dedicated to Open Data Day, organised by Open State Foundation and Open Nederland. The Open Knowledge Foundation is proud to be a publishing partner.\r\nOpen acc… [+7850 chars]'},
  {'source': {'id': None, 'name': 'The Indian Express'},
   'author': 'Priya Kumari Shukla',
   'title': 'UPSC Key: Iran peace plan, CAPF Bill and Finance Bill',
   'description': 'Why is India’s updated Nationally Determined Contributions relevant to the UPSC exam? What is the significance of topics such as the BRICS, Women’s Reservation Act, and the Transgender Persons (Protection of Rights) Amendment Bill, 2026 on both the preliminar…',
   'url': 'https://indianexpress.com/article/upsc-current-affairs/upsc-key-iran-peace-plan-capf-bill-and-finance-bill-10602999/',
   'urlToImage': 'https://images.indianexpress.com/2026/03/UPSC-Key-26th-March-2026.jpg',
   'publishedAt': '2026-03-26T13:20:23Z',
   'content': 'Preliminary Examination: Current events of national and international importance.Mains Examination:\xa0General Studies II: Bilateral, regional and global groupings and agreements involving India and/or … [+37635 chars]'},
  {'source': {'id': None, 'name': 'mindbodygreen.com'},
   'author': 'https://www.mindbodygreen.com/wc/dr-perpetua-neo',
   'title': "I'm Clinical Psychologist: Here's How I Actually Take Care Of My Mental Health",
   'description': 'Clients often ask me, as a clinical psychologist, how <em>I</em> actually care for my mental health.',
   'url': 'https://www.mindbodygreen.com/articles/im-psychologist-and-this-is-how-i-take-care-of-my-mental-health',
   'urlToImage': 'https://mindbodygreen-res.cloudinary.com/image/upload/c_fill,w_2000,h_1200,g_auto,fl_lossy,f_jpg/org/1773240851781_cwhsazit1l7.jpg',
   'publishedAt': '2026-03-27T10:08:00Z',
   'content': "Clients often ask me, as a clinical psychologist, how I actually care for my mental health. Sure, I have my coaches and therapists, I take supplements and make sure to get my steps in, And yes, I'll … [+21431 chars]"},
  {'source': {'id': None, 'name': 'Saastr.com'},
   'author': 'Jason Lemkin',
   'title': 'You Can’t Train an AI Agent and Then Just … Go Away. We Did, It Fell Off The Rails. And We Didn’t Even Know.',
   'description': 'We have an AI agent that we use all the time.\xa0 One of our now almost 30.\xa0 It’s a good one, people really like it, and importantly, it’s not directly connected to revenue.\xa0 So we made a biggish mistake.\xa0 We sort of ignored it once it worked and was dialed in. …',
   'url': 'https://www.saastr.com/you-cant-train-an-ai-agent-and-then-just-go-away-we-did-and-it-fell-off-the-rails/',
   'urlToImage': 'https://i0.wp.com/www.saastr.com/wp-content/uploads/2026/03/Action-Movie-Text-scaled.jpg?fit=1000%2C565&quality=70&ssl=1',
   'publishedAt': '2026-03-24T14:10:15Z',
   'content': 'We have an AI agent that we use all the time.\xa0 One of our now almost 30.\xa0 It’s a good one, people really like it, and importantly, it’s not directly connected to revenue.\xa0 So we made a biggish mistak… [+9609 chars]'},
  {'source': {'id': None, 'name': 'BusinessLine'},
   'author': 'PTI',
   'title': 'Over half of countries have banned phones in schools: UNESCO',
   'description': 'UNESCO reports that over half of countries have banned phones in schools to combat cyberbullying and improve attention in classrooms.',
   'url': 'https://www.thehindubusinessline.com/news/over-half-of-countries-have-banned-phones-in-schools-unesco/article70771814.ece',
   'urlToImage': 'https://bl-i.thgim.com/public/incoming/qy7quf/article70771825.ece/alternates/LANDSCAPE_1200/BL07_Think_Smartphone.jpg',
   'publishedAt': '2026-03-22T07:59:51Z',
   'content': "More than half of the countries have banned phones in schools amid mounting concerns about declining attention in classrooms and cyberbullying, according to the UNSECO's Global Education Monitoring (… [+3882 chars]"},
  {'source': {'id': None, 'name': 'Whatjapanthinks.com'},
   'author': 'Ken Y-N',
   'title': 'Hoshimachi Suisei’s New Studio: A Defining Moment for an Idol, Artist, and Visionary',
   'description': 'Hoshimachi Suisei has always occupied a rare space in the digital entertainment landscape. She isn’t just a VTuber or idol; she’s a performer, musician, and creative force who has forged her own path long before global audiences fully recognized her impact. N…',
   'url': 'https://whatjapanthinks.com/hoshimachi-suiseis-new-studio/',
   'urlToImage': 'https://whatjapanthinks.com/wp-content/uploads/2026/03/Hoshimachi-Suiseis-New-Studio.webp',
   'publishedAt': '2026-03-23T06:37:16Z',
   'content': 'Hoshimachi Suisei has always occupied a rare space in the digital entertainment landscape. She isnt just a VTuber or idol; shes a performer, musician, and creative force who has forged her own path l… [+6287 chars]'},
  {'source': {'id': None, 'name': 'Europa.eu'},
   'author': 'European Central Bank',
   'title': 'Luis de Guindos: Navigating turbulence: challenges for Europe and the path ahead',
   'description': 'The European Central Bank (ECB) is the central bank of the European Union countries which have adopted the euro. Our main task is to maintain price stability in the euro area and so preserve the purchasing power of the single currency.',
   'url': 'https://www.ecb.europa.eu//press/key/date/2026/html/ecb.sp260326~cbb4721baf.en.html',
   'urlToImage': 'https://www.ecb.europa.eu/press/key/shared/img/socialmedia/social-default.jpg?0dbb2de262f4f1fcaeae410be132177a',
   'publishedAt': '2026-03-26T09:00:00Z',
   'content': 'Speech by Luis de Guindos, Vice-President of the ECB, at the Ragnar Nurkse Memorial Lecture organised by Eesti Pank\r\nTallinn, 26 March 2026\r\nIntroduction\r\nIt is a privilege to be here in Tallinn to d… [+11915 chars]'},
  {'source': {'id': None, 'name': 'Uxpin.com'},
   'author': 'Andrew Martin',
   'title': 'How to build UI using GPT-4.1 + Custom Design Systems – Use UXPin Merge!',
   'description': 'Generate production-ready React UI components from prompts using GPT-4.1 and sync them to your design system with UXPin Merge.\nThe post How to build UI using GPT-4.1 + Custom Design Systems – Use UXPin Merge! appeared first on Studio by UXPin.',
   'url': 'https://www.uxpin.com/studio/blog/build-ui-gpt-4-1-custom-design-systems-uxpin-merge/',
   'urlToImage': 'https://studio.uxpincdn.com/studio/wp-content/uploads/2026/03/image_75fcbd81dd136b1694d9c0ef493cff5b.jpeg.webp',
   'publishedAt': '2026-03-26T09:38:05Z',
   'content': 'Building user interfaces just got faster and easier. By combining GPT-4.1‘s ability to generate React components from text prompts with UXPin Merge‘s support for design systems, you can create produc… [+19470 chars]'},
  {'source': {'id': None, 'name': 'Fair Observer'},
   'author': 'Thomas Greminger',
   'title': 'The Agency of Middle Powers in a Fragmented and Polarized World',
   'description': 'Middle powers face both challenges and opportunities. If the international system fractures further, it will not be because the great powers disagree. They have always disagreed on some level. It will fracture instead, because the space between them collapses…',
   'url': 'https://www.fairobserver.com/economics/the-agency-of-middle-powers-in-a-fragmented-and-polarized-world/',
   'urlToImage': 'https://www.fairobserver.com/wp-content/uploads/2026/03/business-partnership.jpg',
   'publishedAt': '2026-03-27T14:24:54Z',
   'content': 'Middle powers face both challenges and opportunities. If the international system fractures further, it will not be because the great powers disagree. They have always disagreed on some level. It wil… [+14775 chars]'},
  {'source': {'id': None, 'name': 'InfoQ.com'},
   'author': 'Anurag Kale',
   'title': 'Presentation: Data Mesh in Action: A Journey From Ideation to Implementation',
   'description': 'Anurag Kale discusses the transition from centralized data bottlenecks to a decentralized Data Mesh architecture at Horse Powertrain. He explains the four pillars - domain ownership, data as a product, self-serve platforms, and federated governance - to empow…',
   'url': 'https://www.infoq.com/presentations/data-mesh-horse-powertrain/',
   'urlToImage': 'https://res.infoq.com/presentations/data-mesh-horse-powertrain/en/card_header_image/anurag-kale-twitter-card-1773151647473.jpg',
   'publishedAt': '2026-03-23T11:43:00Z',
   'content': "Transcript\r\nAnurag Kale: I would just like to quickly understand, how many of you here are data professionals? You're working with data somehow? Software engineers? Architects? Product people? Today … [+41789 chars]"},
  {'source': {'id': None, 'name': 'GlobeNewswire'},
   'author': 'Focal',
   'title': "Focal Named to Fast Company's List of the World's Most Innovative Companies of 2026",
   'description': "Focal Named to Fast Company's List of the World's Most Innovative Companies of 2026...",
   'url': 'https://www.globenewswire.com/news-release/2026/03/24/3261081/0/en/Focal-Named-to-Fast-Company-s-List-of-the-World-s-Most-Innovative-Companies-of-2026.html',
   'urlToImage': 'https://ml.globenewswire.com/Resource/Download/4e5a591f-b331-49c2-942c-dfe124ab8dc1',
   'publishedAt': '2026-03-24T11:10:00Z',
   'content': "SAN FRANCISCO, March 24, 2026 (GLOBE NEWSWIRE) -- Focal, an AI-enabled robotic heating company and the creator of the world's first autonomous personal comfort platform, today announced it has earned… [+5480 chars]"},
  {'source': {'id': None, 'name': 'Livemint'},
   'author': 'Jocelyn Fernandes',
   'title': 'Must shift AI from adoption to transformation: Deloitte says Indian firms lag behind global peers in expertise',
   'description': "Deloitte's survey reveals a significant shift is needed for companies to meaningfully integrate AI into operations. It also noted that while Indian firms are top of the list in AI adoption, there is a capability gap compared to peers.&nbsp;",
   'url': 'https://www.livemint.com/companies/news/ai-shift-adoption-transformation-deloitte-state-of-ai-in-enterprise-report-says-indian-firms-lag-global-peers-expertise-11774170839704.html',

In [9]:
pd.DataFrame(all_articles['articles'])

,source,author,title,description,url,urlToImage,publishedAt,content
0,"{'id': None, 'name': 'Fast Company'}",Victor Dey,The most innovative manufacturing companies for 2026,"Manufacturing rarely announces its reinventions dramatically. Change arrives instead through pressure on energy, labor, and supply chains. Over the past year, those pressures have converged to drive a broad reconsideration of production intelligence. Across s…",https://www.fastcompany.com/91497254/manufacturing-most-innovative-companies-2026,"https://images.fastcompany.com/image/upload/f_webp,q_auto,c_fit/wp-cms-2/2026/03/p-1b-2026-MIC-sectors-manufacturing.jpg",2026-03-24T11:00:00Z,"Manufacturing rarely announces its reinventions dramatically. Change arrives instead through pressure on energy, labor, and supply chains. Over the past year, those pressures have converged to drive … [+2852 chars]"
1,"{'id': None, 'name': 'The Indian Express'}","Rajib Dasgupta, Kamini Walia","For public-health reform, fix urban governance","Urban public health crises are often framed narrowly in terms of hospital shortages and workforce gaps. Less visible, but arguably more consequential, are failures in everyday urban systems.",https://indianexpress.com/article/opinion/columns/for-public-health-reform-fix-urban-governance-10595709/,https://images.indianexpress.com/2026/03/urbanisation_20260322194612.jpg,2026-03-23T01:00:04Z,"The Union cabinet recently approved the launch of the Urban Challenge Fund (UCF), worth Rs 4 lakh crore. The Centre will provide an assistance of Rs 1 lakh crore, and at least 50 per cent of the cost… [+3863 chars]"
2,"{'id': None, 'name': 'Composio.dev'}",Sunil Kumar Dash,OpenClaw Is a Security Nightmare Dressed Up as a Daydream,"Composio content pages powered by our CMS, including tutorials, product updates, and guides.",https://composio.dev/content/openclaw-security-and-vulnerabilities,https://framerusercontent.com/images/H9WhU9hmMWK1TcazYTRy6t5owos.png,2026-03-22T17:35:28Z,"Back in 2023, the internet was buzzing about AutoGPT and BabyAGI. It was just after GPT-4 had arrived. Everyone was talking about autonomous agents taking jobs, how they can, and I remember how scare… [+27266 chars]"
3,"{'id': None, 'name': 'Nvidia.com'}",Lachlan Dowling,"How Centralized Radar Processing on NVIDIA DRIVE Enables Safer, Smarter Level 4 Autonomy","In the current state of automotive radar, machine learning engineers can't work with camera-equivalent raw RGB images. Instead, they work with the output of...",https://developer.nvidia.com/blog/how-centralized-radar-processing-on-nvidia-drive-enables-safer-smarter-level-4-autonomy/,https://developer-blogs.nvidia.com/wp-content/uploads/2026/03/Feature-1024x576.gif,2026-03-25T15:58:59Z,"In the current state of automotive radar, machine learning engineers can’t work with camera-equivalent raw RGB images. Instead, they work with the output of radar constant false alarm rate (CFAR), wh… [+12682 chars]"
4,"{'id': None, 'name': 'Radaronline.com'}",Aaron Tinney,EXCLUSIVE: Britney Spears 'Haunted by PTSD' Over Conservatorship as Pop Singer Faces Being Put Back Under Family's Control in Wake of DUI Arrest,Britney Spears is said to be in fear of losing control again after a DUI arrest.,https://radaronline.com/p/britney-spears-ptsd-conservatorship-dui-fears/,https://media.radaronline.com/brand-img/-Ip2vRpze/1200x628/britney-spears-ptsd-conservatorship-dui-fears-pp-1774027327724.jpg,2026-03-21T22:00:00Z,"Britney Spears is said to be ""haunted"" by fears of losing her freedom again after her recent DUI arrest, with insiders claiming the pop star is grappling with severe anxiety that could reopen the doo… [+3230 chars]"
5,"{'id': None, 'name': 'GlobeNewswire'}",SNS Insider pvt ltd,"Software Defined Vehicles Market Projected to Reach USD 4,663.54 Billion by 2035, Owing to EV Adoption and Software-Defined Automotive Platforms | Research by SNS Insider","The Software Defined Vehicles Market is expanding rapidly as automakers adopt OTA updates, AI-driven systems, and connected vehicle platforms, with the U.S. segment growing from USD 109.86 billion in 2025 to USD 1,838.25 billion by 2035. The Software Defined …",https://www.globenewswire.com/news-release/2026/03/23/3260196/0/en/Software-Defined-Vehicles-Market-Projected-to-Reach-USD-4-663-54-Billion-by-2035-Owing-to-EV-Adoption-and-Software-Defined-Automotive-Platforms-Research-by-SNS-Insider.html,https://ml.globenewswire.com/Resource/Download/d6272c2e-d204-41b8-b545-a6e2e24f85c2,2026-03-23T10:14:00Z,"Austin, March 23, 2026 (GLOBE NEWSWIRE) -- The Software Defined Vehicles Market size was estimated at USD 278.35 billion in 2025 and is expected to reach USD 4,663.54 billion by 2035, growing at a CA… [+8225 chars]"
6,"{'id': None, 'name': 'Paul Tan's Automotive News'}",Jonathan Lee,"2026 Xpeng X9 EV facelift in Thailand – REEV looks, new 537 PS AWD, 615 km WLTP range, 542 kW DCFC","Another year, another “facelift” for the Xpeng X9, which went on sale in Thailand last week – just two weeks after it was launched in China. This time, the changes, seen at the ongoing Bangkok International Motor Show (BIMS), are much more substantial, albeit…",https://paultan.org/2026/03/27/2026-xpeng-x9-ev-facelift-in-thailand-reev-looks-new-537-ps-awd-615-km-wltp-range-542-kw-dcfc/,https://paultan.org/image/2026/03/2026-BIMS-Xpeng-X9-1-1200x801.jpg,2026-03-27T09:28:15Z,"Another year, another “facelift” for the Xpeng X9, which went on sale in Thailand last week just two weeks after it was launched in China. This time, the changes, seen at the ongoing Bangkok Internat… [+3823 chars]"
7,"{'id': None, 'name': 'Ieee.org'}",Tereza Pultarova,The Coming Drone-War Inflection in Ukraine,"WHEN KYIV-BORN ENGINEER Yaroslav Azhnyuk thinks about the future, his mind conjures up dystopian images. He talks about “swarms of autonomous drones carrying other autonomous drones to protect them against autonomous drones, which are trying to intercept them…",https://spectrum.ieee.org/autonomous-drone-warfare,https://spectrum.ieee.org/media-library/image.jpg?id=65327392&width=1200&height=600&coordinates=0%2C15%2C0%2C15,2026-03-24T13:00:05Z,"WHENKYIV-BORNENGINEER Yaroslav Azhnyuk thinks about the future, his mind conjures up dystopian images. He talks about swarms of autonomous drones carrying other autonomous drones to protect them agai… [+24029 chars]"
8,"{'id': None, 'name': 'Bradenkelley.com'}",Braden Kelley,Neo-Feudalism and Innovation Impact,"A System Designed to Concentrate Power – or Accelerate Breakthroughs? LAST UPDATED: March 27, 2026 at 4:55 PM by Braden Kelley and Art Inteligencia The Return of Lords and Serfs — But This Time It’s Digital For decades, we’ve told ourselves a reassuring story…",https://bradenkelley.com/2026/03/neo-feudalism-and-innovation-impact/,NaN,2026-03-28T00:57:48Z,"A System Designed to Concentrate Power – or Accelerate Breakthroughs?\r\nLAST UPDATED: March 27, 2026 at 4:55 PM\r\nby Braden Kelley and Art Inteligencia\r\nThe Return of Lords and Serfs But This Time Its … [+20133 chars]"
9,"{'id': None, 'name': 'Geeky Gadgets'}",Julian Horsey,The 5 Stages of AI: What Comes After ChatGPT?,"Artificial intelligence is advancing through five distinct stages, each representing a fantastic leap in capability and impact. Parker Prompts explores these stages, starting with the foundational role of large language models (LLMs) like ChatGPT and Gemini, …",https://www.geeky-gadgets.com/five-stages-ai/,https://www.geeky-gadgets.com/wp-content/uploads/2026/03/stage-2-agentic-ai-assistant-tasks.jpg,2026-03-27T08:45:52Z,"Artificial intelligence is advancing through five distinct stages, each representing a fantastic leap in capability and impact. Parker Prompts explores these stages, starting with the foundational ro… [+8392 chars]"
10,"{'id': None, 'name': 'Okfn.org'}",Bianca Kramer,Open Data Day essay #4: ‘Open access and open data alone are not enough’,The Barcelona Declaration on Open Research Information was launched in 2024 as an initiative to encourage research institutions and research funders to actively contribute to the open availability of research information.\nThe post Open Data Day essay #4: ‘Ope…,https://blog.okfn.org/2026/03/24/open-data-day-essay-4-open-access-and-open-data-alone-are-not-enough/,https://blog.okfn.org/wp-content/uploads/2026/03/1.png,2026-03-24T19:39:37Z,"This text is part of a series of essays dedicated to Open Data Day, organised by Open State Foundation and Open Nederland. The Open Knowledge Foundation is proud to be a publishing partner.\r\nOpen acc… [+7850 chars]"
11,"{'id': None, 'name': 'The Indian Express'}",Priya Kumari Shukla,"UPSC Key: Iran peace plan, CAPF Bill and Finance Bill","Why is India’s updated Nationally Determined Contributions relevant to the UPSC exam? What is the significance of topics such as the BRICS, Women’s Reservation Act, and the Transgender Persons (Protection of Rights) Amendment Bill, 2026 on both the preliminar…",https://indianexpress.com/article/upsc-current-affairs/upsc-key-iran-peace-plan-capf-bill-and-finance-bill-10602999/,https://images.indianexpress.com/2026/03/UPSC-Key-26th-March-2026.jpg,2026-03-26T13:20:23Z,"Preliminary Examination: Current events of national and international importance.Mains Examination: General Studies II: Bilateral, regional and global groupings and agreements involving India and/or … [+37635 chars]"
12,"{'id': None, 'name': 'mindbodygreen.com'}",https://www.mindbodygreen.com/wc/dr-perpetua-neo,I'm Clinical Psychologist: Here's How I Actually Take Care Of My Mental Health,"Clients often ask me, as a clinical psychologist, how <em>I</em> actually care for my mental health.",https://www.mindbodygreen.com/articles/im-psychologist-and-this-is-how-i-take-care-of-my-mental-health,"https://mindbodygreen-res.cloudinary.com/image/upload/c_fill,w_2000,h_1200,g_auto,fl_lossy,f_jpg/org/1773240851781_cwhsazit1l7.jpg",2026-03-27T10:08:00Z,"Clients often ask me, as a clinical psychologist, how I actually care for my mental health. Sure, I have my coaches and therapists, I take supplements and make sure to get my steps in, And yes, I'll … [+21431 chars]"
13,"{'id': None, 'name': 'Saastr.com'}",Jason Lemkin,"You Can’t Train an AI Agent and Then Just … Go Away. We Did, It Fell Off The Rails. And We Didn’t Even Know.","We have an AI agent that we use all the time. One of our now almost 30. It’s a good one, people really like it, and importantly, it’s not directly connected to revenue. So we made a biggish mistake. We sort of ignored it once it worked and was dialed in. …",https://www.saastr.com/you-cant-train-an-ai-agent-and-then-just-go-away-we-did-and-it-fell-off-the-rails/,https://i0.wp.com/www.saastr.com/wp-content/uploads/2026/03/Action-Movie-Text-scaled.jpg?fit=1000%2C565&quality=70&ssl=1,2026-03-24T14:10:15Z,"We have an AI agent that we use all the time. One of our now almost 30. It’s a good one, people really like it, and importantly, it’s not directly connected to revenue. So we made a biggish mistak… [+9609 chars]"
14,"{'id': None, 'name': 'BusinessLine'}",PTI,Over half of countries have banned phones in schools: UNESCO,UNESCO reports that over half of countries have banned phones in schools to combat cyberbullying and improve attention in classrooms.,https://www.thehindubusinessline.com/news/over-half-of-countries-have-banned-phones-in-schools-unesco/article70771814.ece,https://bl-i.thgim.com/public/incoming/qy7quf/article70771825.ece/alternates/LANDSCAPE_1200/BL07_Think_Smartphone.jpg,2026-03-22T07:59:51Z,"More than half of the countries have banned phones in schools amid mounting concerns about declining attention in classrooms and cyberbullying, according to the UNSECO's Global Education Monitoring (… [+3882 chars]"
15,"{'id': None, 'name': 'Whatjapanthinks.com'}",Ken Y-N,"Hoshimachi Suisei’s New Studio: A Defining Moment for an Idol, Artist, and Visionary","Hoshimachi Suisei has always occupied a rare space in the digital entertainment landscape. She isn’t just a VTuber or idol; she’s a performer, musician, and creative force who has forged her own path long before global audiences fully recognized her impact. N…",https://whatjapanthinks.com/hoshimachi-suiseis-new-studio/,https://whatjapanthinks.com/wp-content/uploads/2026/03/Hoshimachi-Suiseis-New-Studio.webp,2026-03-23T06:37:16Z,"Hoshimachi Suisei has always occupied a rare space in the digital entertainment landscape. She isnt just a VTuber or idol; shes a performer, musician, and creative force who has forged her own path l… [+6287 chars]"
16,"{'id': None, 'name': 'Europa.eu'}",European Central Bank,Luis de Guindos: Navigating turbulence: challenges for Europe and the path ahead,The European Central Bank (ECB) is the central bank of the European Union countries which have adopted the euro. Our main task is to maintain price stability in the euro area and so preserve the purchasing power of the single currency.,https://www.ecb.europa.eu//press/key/date/2026/html/ecb.sp260326~cbb4721baf.en.html,https://www.ecb.europa.eu/press/key/shared/img/socialmedia/social-default.jpg?0dbb2de262f4f1fcaeae410be132177a,2026-03-26T09:00:00Z,"Speech by Luis de Guindos, Vice-President of the ECB, at the Ragnar Nurkse Memorial Lecture organised by Eesti Pank\r\nTallinn, 26 March 2026\r\nIntroduction\r\nIt is a privilege to be here in Tallinn to d… [+11915 chars]"
17,"{'id': None, 'name': 'Uxpin.com'}",Andrew Martin,How to build UI using GPT-4.1 + Custom Design Systems – Use UXPin Merge!,Generate production-ready React UI components from prompts using GPT-4.1 and sync them to your design system with UXPin Merge.\nThe post How to build UI using GPT-4.1 + Custom Design Systems – Use UXPin Merge! appeared first on Studio by UXPin.,https://www.uxpin.com/studio/blog/build-ui-gpt-4-1-custom-design-systems-uxpin-merge/,https://studio.uxpincdn.com/studio/wp-content/uploads/2026/03/image_75fcbd81dd136b1694d9c0ef493cff5b.jpeg.webp,2026-03-26T09:38:05Z,"Building user interfaces just got faster and easier. By combining GPT-4.1‘s ability to generate React components from text prompts with UXPin Merge‘s support for design systems, you can create produc… [+19470 chars]"
18,"{'id': None, 'name': 'Fair Observer'}",Thomas Greminger,The Agency of Middle Powers in a Fragmented and Polarized World,"Middle powers face both challenges and opportunities. If the international system fractures further, it will not be because the great powers disagree. They have always disagreed on some level. It will fracture instead, because the space between them collapses…",https://www.fairobserver.com/economics/the-agency-of-middle-powers-in-a-fragmented-and-polarized-world/,https://www.fairobserver.com/wp-content/uploads/2026/03/business-partnership.jpg,2026-03-27T14:24:54Z,"Middle powers face both challenges and opportunities. If the international system fractures further, it will not be because the great powers disagree. They have always disagreed on some level. It wil… [+14775 chars]"
19,"{'id': None, 'name': 'InfoQ.com'}",Anurag Kale,Presentation: Data Mesh in Action: A Journey From Ideation to Implementation,"Anurag Kale discusses the transition from centralized data bottlenecks to a decentralized Data Mesh architecture at Horse Powertrain. He explains the four pillars - domain ownership, data as a product, self-serve platforms, and federated governance - to empow…",https://www.infoq.com/presentations/data-mesh-horse-powertrain/,https://res.infoq.com/presentations/data-mesh-horse-powertrain/en/card_header_image/anurag-kale-twitter-card-1773151647473.jpg,2026-03-23T11:43:00Z,"Transcript\r\nAnurag Kale: I would just like to quickly understand, how many of you here are data professionals? You're working with data somehow? Software engineers? Architects? Product people? Today … [+41789 chars]"
20,"{'id': None, 'name': 'GlobeNewswire'}",Focal,Focal Named to Fast Company's List of the World's Most Innovative Companies of 2026,Focal Named to Fast Company's List of the World's Most Innovative Companies of 2026...,https://www.globenewswire.com/news-release/2026/03/24/3261081/0/en/Focal-Named-to-Fast-Company-s-List-of-the-World-s-Most-Innovative-Companies-of-2026.html,https://ml.globenewswire.com/Resource/Download/4e5a591f-b331-49c2-942c-dfe124ab8dc1,2026-03-24T11:10:00Z,"SAN FRANCISCO, March 24, 2026 (GLOBE NEWSWIRE) -- Focal, an AI-enabled robotic heating company and the creator of the world's first autonomous personal comfort platform, today announced it has earned… [+5480 chars]"
21,"{'id': None, 'name': 'Livemint'}",Jocelyn Fernandes,Must shift AI from adoption to transformation: Deloitte says Indian firms lag behind global peers in expertise,"Deloitte's survey reveals a significant shift is needed for companies to meaningfully integrate AI into operations. It also noted that while Indian firms are top of the list in AI adoption, there is a capability gap compared to peers.&nbsp;",https://www.livemint.com/companies/news/ai-shift-adoption-transformation-deloitte-state-of-ai-in-enterprise-report-says-indian-firms-lag-global-peers-expertise-11774170839704.html,https://www.livemint.com/lm-img/img/2026/03/22/1600x900/logo/AI_adoption_challenges_India_behind_peers_tech_1774176643607_1774176643731.jpg,2026-03-22T11:19:35Z,Deloittes latest State of AI in the Enterprise survey for 2026 captured insights showing that today's business leaders face an unprecedented challenge: moving beyond pilots to truly integrating AI in… [+10308 chars]
22,"{'id': None, 'name': 'Microsoft.com'}",Stephen Toub - MSFT,Ten Months with Copilot Coding Agent in dotnet/runtime,"After ten months using GitHub Copilot Coding Agent (CCA) in dotnet/runtime, the .NET team shares data-driven lessons on cloud-AI-assisted development.\nThe post Ten Months with Copilot Coding Agent in dotnet/runtime appeared first on .NET Blog.",https://devblogs.microsoft.com/dotnet/ten-months-with-cca-in-dotnet-runtime/,https://devblogs.microsoft.com/dotnet/wp-content/uploads/sites/10/2026/03/cca-featured-image.webp,2026-03-23T14:55:00Z,"When GitHub’s Copilot Coding Agent (CCA) first became available in May 2025, the promise of cloud-based AI coding agents was generating enormous excitement, and equal skepticism. So we began an exper… [+98037 chars]"
23,"{'id': None, 'name': 'SiliconANGLE News'}",David Vellante and David Floyer,"The agentic AI gap: Vendors sprint, enterprises crawl",The geopolitical dislocations ripping through the stock market and are filtering down to information technology budgets in the form of increased uncertainty. It seems that every quarter of budget optimism is followed with some external event that causes organ…,https://siliconangle.com/2026/03/28/agentic-ai-gap-vendors-sprint-enterprises-crawl/,https://d15shllkswkct0.cloudfront.net/wp-content/blogs.dir/1/files/2026/03/Gemini_Generated_Image_sqae07sqae07sqae-2048x1143.png,2026-03-28T17:34:46Z,The geopolitical dislocations ripping through the stock market and are filtering down to information technology budgets in the form of increased uncertainty.\r\nIt seems that every quarter of budget op… [+20130 chars]
24,"{'id': None, 'name': 'New York Post'}",Perri Ormont Blumberg,Inside Palm Beach’s billion dollar international superyacht show,'Tis the season to deck the hulls with bows of jolly.,https://nypost.com/2026/03/25/lifestyle/what-to-see-and-do-at-the-palm-beach-international-boat-show/,https://nypost.com/wp-content/uploads/sites/2/2026/03/newspress-collage-95j703jh1-1774368078877.jpg?quality=75&strip=all&1774353732&w=1200,2026-03-25T14:30:00Z,"The Palm Beach International Boat Show is bobbing back to Flagler Drive with hundreds of vessels plucked from around the world on display, from pint-sized inflatables to nearly 300-foot superyachts.\r… [+12590 chars]"

In [10]:
contents = []
for all_articles_idx in range(len(all_articles['articles'])):
    # article = all_articles[all_articles_idx]
    content = all_articles['articles'][all_articles_idx]['content']
    contents.append(content)

In [11]:
all_articles_df = pd.DataFrame(contents)
all_articles_df

                                                                                                                                                                                                                                0
0          Manufacturing rarely announces its reinventions dramatically. Change arrives instead through pressure on energy, labor, and supply chains. Over the past year, those pressures have converged to drive … [+2852 chars]
1          The Union cabinet recently approved the launch of the Urban Challenge Fund (UCF), worth Rs 4 lakh crore. The Centre will provide an assistance of Rs 1 lakh crore, and at least 50 per cent of the cost… [+3863 chars]
2         Back in 2023, the internet was buzzing about AutoGPT and BabyAGI. It was just after GPT-4 had arrived. Everyone was talking about autonomous agents taking jobs, how they can, and I remember how scare… [+27266 chars]
3         In the current state of automotive radar, machine learning engineers can’t work with camera-equivalent raw RGB images. Instead, they work with the output of radar constant false alarm rate (CFAR), wh… [+12682 chars]
4          Britney Spears is said to be "haunted" by fears of losing her freedom again after her recent DUI arrest, with insiders claiming the pop star is grappling with severe anxiety that could reopen the doo… [+3230 chars]
5          Austin, March 23, 2026 (GLOBE NEWSWIRE) -- The Software Defined Vehicles Market size was estimated at USD 278.35 billion in 2025 and is expected to reach USD 4,663.54 billion by 2035, growing at a CA… [+8225 chars]
6          Another year, another “facelift” for the Xpeng X9, which went on sale in Thailand last week just two weeks after it was launched in China. This time, the changes, seen at the ongoing Bangkok Internat… [+3823 chars]
7         WHENKYIV-BORNENGINEER Yaroslav Azhnyuk thinks about the future, his mind conjures up dystopian images. He talks about swarms of autonomous drones carrying other autonomous drones to protect them agai… [+24029 chars]
8   A System Designed to Concentrate Power – or Accelerate Breakthroughs?\r\nLAST UPDATED: March 27, 2026 at 4:55 PM\r\nby Braden Kelley and Art Inteligencia\r\nThe Return of Lords and Serfs But This Time Its … [+20133 chars]
9          Artificial intelligence is advancing through five distinct stages, each representing a fantastic leap in capability and impact. Parker Prompts explores these stages, starting with the foundational ro… [+8392 chars]
10       This text is part of a series of essays dedicated to Open Data Day, organised by Open State Foundation and Open Nederland. The Open Knowledge Foundation is proud to be a publishing partner.\r\nOpen acc… [+7850 chars]
11        Preliminary Examination: Current events of national and international importance.Mains Examination: General Studies II: Bilateral, regional and global groupings and agreements involving India and/or … [+37635 chars]
12        Clients often ask me, as a clinical psychologist, how I actually care for my mental health. Sure, I have my coaches and therapists, I take supplements and make sure to get my steps in, And yes, I'll … [+21431 chars]
13         We have an AI agent that we use all the time.  One of our now almost 30.  It’s a good one, people really like it, and importantly, it’s not directly connected to revenue.  So we made a biggish mistak… [+9609 chars]
14         More than half of the countries have banned phones in schools amid mounting concerns about declining attention in classrooms and cyberbullying, according to the UNSECO's Global Education Monitoring (… [+3882 chars]
15         Hoshimachi Suisei has always occupied a rare space in the digital entertainment landscape. She isnt just a VTuber or idol; shes a performer, musician, and creative force who has forged her own path l… [+6287 chars]
16  Speech by Luis de Guindos, Vice-President of the ECB, at the Ragnar Nurkse Memorial Lecture organised by Eesti Pank\r\nTallinn, 26 March 2026\r\nIntroduction\r\nIt is a privilege to be here in Tallinn to d… [+11915 chars]
17        Building user interfaces just got faster and easier. By combining GPT-4.1‘s ability to generate React components from text prompts with UXPin Merge‘s support for design systems, you can create produc… [+19470 chars]
18        Middle powers face both challenges and opportunities. If the international system fractures further, it will not be because the great powers disagree. They have always disagreed on some level. It wil… [+14775 chars]
19      Transcript\r\nAnurag Kale: I would just like to quickly understand, how many of you here are data professionals? You're working with data somehow? Software engineers? Architects? Product people? Today … [+41789 chars]
20         SAN FRANCISCO, March 24, 2026 (GLOBE NEWSWIRE) -- Focal, an AI-enabled robotic heating company and the creator of the world's first autonomous personal comfort platform, today announced it has earned… [+5480 chars]
21        Deloittes latest State of AI in the Enterprise survey for 2026 captured insights showing that today's business leaders face an unprecedented challenge: moving beyond pilots to truly integrating AI in… [+10308 chars]
22        When GitHub’s Copilot Coding Agent (CCA) first became available in May 2025, the promise of cloud-based AI coding agents was generating enormous excitement, and equal skepticism. So we began an exper… [+98037 chars]
23      The geopolitical dislocations ripping through the stock market and are filtering down to information technology budgets in the form of increased uncertainty.\r\nIt seems that every quarter of budget op… [+20130 chars]
24       The Palm Beach International Boat Show is bobbing back to Flagler Drive with hundreds of vessels plucked from around the world on display, from pint-sized inflatables to nearly 300-foot superyachts.\r… [+12590 chars]
25      What Is Claude Code, and Why Should You Care?\r\nClaude Code is Anthropic's terminal-native agentic coding tool not a chat window, not a code-completion plugin, but a full autonomous coding agent that … [+18985 chars]
26     Normative Common-Good Layer with Governance Metrics, Personhood Extension and Ethical Guardrails for GenesisAeon\r\nDOI: 10.5281/zenodo.19201980 | Zenodo Record: https://zenodo.org/records/19201980\r\nOv… [+4461 chars]
27         Video Friday is your weekly selection of awesome robotics videos, collected by your friends at IEEE Spectrum robotics. We also post a weekly calendar of upcoming robotics events for the next few mont… [+5636 chars]
28     March 19, 2026 08:30 | HVC- 210\r\n“House Permanent Select Committee on Intelligence Chairman Rick Crawford (AR-01) announced an open full Committee hearing for Thursday, March 19, to examine the annua… [+230630 chars]
29        Every organization has at least one system that everyone dreads touching. It works. Technically. But nobody can confidently explain what it does or why it does it that way. Making changes takes longe… [+11512 chars]
30         Levels of AGI are a way to describe how close an AI system is to broad, human-like intelligence. A widely used framework from Google DeepMind breaks progress into levels based on how strong a system … [+6023 chars]
31       A German respondent in Anthropics recent study said it plainly: AI should be cleaning windows and emptying the dishwasher so I can paint and write poetry. Right now its exactly the other way around.\r… [+18679 chars]
32       For Level 4 autonomy to be a reality, cars may look like mobile data centers with massive demands for memory \r\n<ul><li>Today’s Level 2 driver-assist systems still require full attention at all times.… [+2508 chars]
33      Abstract\r\nLearner agency (LA), a students ability to take ownership of their learning and make purposeful decisions, is increasingly recognized as a critical competency in preparing adaptable healthc… [+55133 chars]
34    Citation: Ma X (2026) Optimizing online teaching effectiveness in elementary education: Exploring multifaceted pathways based fsQCA analysis. PLoS One 21(3):\r\n e0345463.\r\nhttps://doi.org/10.1371/jour… [+60045 chars]
35      Abstract\r\nAs populations age, long-term care policies must balance individual preferences with financial constraints. The prevailing aging in place policy in France assumes that citizens overwhelming… [+59371 chars]
36    Abstract\r\nBackground\r\nQuilombola communities in the Brazilian Amazon face persistent social and territorial inequities that shape health outcomes and access to care. Geographic isolation, limited tra… [+50001 chars]
37      Abstract\r\nThis study evaluated the effectiveness of an app-supported training model versus conventional physical education (PE) on college students basic athletic abilities and described exercise mot… [+46151 chars]
38        Citation: Bartolomeu L, Basualdo N, Rolón F, Rubinstein A, Volij C, Simon M, et al. (2026) Examining womens choice between home and institutional births: Insights from the Salud Mesoamérica Initiativ… [+35209 chars]
39      Introduction\r\nCancer remains a significant public health challenge globally, with low- and middle-income countries (LMICs) experiencing a disproportionate burden [13]. LMICs often lack adequate healt… [+39113 chars]
40        Citation: Zheng G, Wang Y, Du J (2026) A dual-path framework for enhancing student engagement and learning outcomes in sports education: Integrating technology acceptance, self-regulation, and self-e… [+44689 chars]
41        <ul><li>The advent of GenAI has dramatically increased the pace at which code can be produced, making it difficult for traditional oversight patterns to keep pace.</li><li>Waiting for human oversight… [+22125 chars]
42      We attended Intels first-ever Pro Day media event this week in New York City, and, as the name always promises, it was all business.\r\nSpecifically, enhancements and revisions to Intel's well-known, l… [+11910 chars]
43    Citation: Alenezi IN, Mersal FA, Elbilgahy AA (2026) Postgraduate students perceptions of artificial intelligence integration in research: A cross-sectional study. PLoS One 21(3):\r\n e0345726.\r\nhttps:… [+52412 chars]
44    Abstract\r\nBackground\r\nCoronary heart disease is the leading cause of global mortality, imposing significant health and economic burdens. Cardiac rehabilitation, including physical activity, can reduc… [+48040 chars]
45      We attended Intels first-ever Pro Day media event this week in New York City, and, as the name always promises, it was all business.\r\nSpecifically, enhancements and revisions to Intel's well-known, l… [+11910 chars]
46       Written by Marc Harris, Head of Insight and Impact, NHS Horizons\r\nAcross four regional learning events in October and November 2025, nearly 1,000 people came together through the National Neighbourho… [+4945 chars]
47        This benchmark measures how well large language models perform in adversarial, multi-turn debates across a wide range of propositions. Strong performance is not just about producing a polished first … [+26157 chars]