# Discover Bad Samples

Datasets: synthetic financial_phrasebank chronicle2050 timebank yt news_api mf_climate clients_rivals_rouges forecast_bench

In [3]:
import os
import sys

import pandas as pd

# Get the current working directory of the notebook
notebook_dir = os.getcwd()
# Add the parent directory to the system path
sys.path.append(os.path.join(notebook_dir, '../'))

# import log_files
from data_processing import DataProcessing

In [4]:
base_data_path = DataProcessing.load_base_data_path(notebook_dir)
data_path = os.path.join(base_data_path, 'combined_datasets/eacl_2026_results/eacl_2026_results.csv')
df = DataProcessing.load_from_file(data_path)
df

/Users/detraviousjamaribrinkley/Documents/Development/research_labs/uf_ds/predictions/notebook_experiments/../data_processing.py:783: DtypeWarning: Columns (2,3,4,8,9,11,12,14,15,18,20,21,26,27,28,29,30,31,32,33,34,35,36,37,38,39,42,44,45,51,52,53,54,55) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path, sep=sep, encoding=encoding, **kwargs)

,Base Sentence,Ground Truth,Domain,Model Name,API Name,Batch ID,Temperature,Top P,Generated At,Prompt Used,...,temp,precip,humidity,windspeed,label,Source Theory,Empirical Support,meta_data,forecast_due_date,question_set
0,"Sebastian, a financial analyst forecasts that ...",1.0,finance,llama-3.1-8b-instant,GROQ_CLOUD,1.0,0.1,1.0,2026-02-28,"A prediction <p> = (<p_s>, <p_t>, <p_d>, <p_o>...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"On August 22, 2024, Goldman Sachs speculates t...",1.0,finance,llama-3.1-8b-instant,GROQ_CLOUD,1.0,0.1,1.0,2026-02-28,"A prediction <p> = (<p_s>, <p_t>, <p_d>, <p_o>...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"Citigroup predicts on September 15, 2026, the ...",1.0,finance,llama-3.1-8b-instant,GROQ_CLOUD,1.0,0.1,1.0,2026-02-28,"A prediction <p> = (<p_s>, <p_t>, <p_d>, <p_o>...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"According to Morgan Stanley, the projected rev...",1.0,finance,llama-3.1-8b-instant,GROQ_CLOUD,1.0,0.1,1.0,2026-02-28,"A prediction <p> = (<p_s>, <p_t>, <p_d>, <p_o>...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"In 2029 Q4, David envisions that the dividend ...",1.0,finance,llama-3.1-8b-instant,GROQ_CLOUD,1.0,0.1,1.0,2026-02-28,"A prediction <p> = (<p_s>, <p_t>, <p_d>, <p_o>...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26444,Will FFIV's market close price on 2025-01-17 b...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"{'id': 'FFIV', 'source': 'yfinance', 'question...",2024-07-21,2024-07-21-human.json
26445,Will FFIV's market close price on 2025-07-21 b...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"{'id': 'FFIV', 'source': 'yfinance', 'question...",2024-07-21,2024-07-21-human.json
26446,Will FFIV's market close price on 2027-07-21 b...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"{'id': 'FFIV', 'source': 'yfinance', 'question...",2024-07-21,2024-07-21-human.json
26447,Will FFIV's market close price on 2029-07-20 b...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"{'id': 'FFIV', 'source': 'yfinance', 'question...",2024-07-21,2024-07-21-human.json
26448,Will FFIV's market close price on 2034-07-19 b...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"{'id': 'FFIV', 'source': 'yfinance', 'question...",2024-07-21,2024-07-21-human.json

In [8]:
filt_null = (df['Base Sentence'].isnull() == True)
df[filt_null]

,Base Sentence,Ground Truth,Domain,Model Name,API Name,Batch ID,Temperature,Top P,Generated At,Prompt Used,...,temp,precip,humidity,windspeed,label,Source Theory,Empirical Support,meta_data,forecast_due_date,question_set
1560,NaN,1.0,sport,llama-3.1-8b-instant,GROQ_CLOUD,2.0,0.8,1.0,2026-03-03,"A prediction <p> = (<p_s>, <p_t>, <p_d>, <p_o>...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1561,NaN,1.0,sport,llama-3.1-8b-instant,GROQ_CLOUD,2.0,0.8,1.0,2026-03-03,"A prediction <p> = (<p_s>, <p_t>, <p_d>, <p_o>...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1562,NaN,1.0,sport,llama-3.1-8b-instant,GROQ_CLOUD,2.0,0.8,1.0,2026-03-03,"A prediction <p> = (<p_s>, <p_t>, <p_d>, <p_o>...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1563,NaN,1.0,sport,llama-3.1-8b-instant,GROQ_CLOUD,2.0,0.8,1.0,2026-03-03,"A prediction <p> = (<p_s>, <p_t>, <p_d>, <p_o>...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1564,NaN,1.0,sport,llama-3.1-8b-instant,GROQ_CLOUD,2.0,0.8,1.0,2026-03-03,"A prediction <p> = (<p_s>, <p_t>, <p_d>, <p_o>...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1565,NaN,1.0,sport,llama-3.1-8b-instant,GROQ_CLOUD,2.0,0.8,1.0,2026-03-03,"A prediction <p> = (<p_s>, <p_t>, <p_d>, <p_o>...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4123,NaN,1.0,sport,llama-3.1-8b-instant,GROQ_CLOUD,0.0,0.8,1.0,NaN,"A prediction <p> = (<p_s>, <p_t>, <p_d>, <p_o>...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4124,NaN,1.0,sport,llama-3.1-8b-instant,GROQ_CLOUD,0.0,0.8,1.0,NaN,"A prediction <p> = (<p_s>, <p_t>, <p_d>, <p_o>...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4125,NaN,1.0,sport,llama-3.1-8b-instant,GROQ_CLOUD,0.0,0.8,1.0,NaN,"A prediction <p> = (<p_s>, <p_t>, <p_d>, <p_o>...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4126,NaN,1.0,sport,llama-3.1-8b-instant,GROQ_CLOUD,0.0,0.8,1.0,NaN,"A prediction <p> = (<p_s>, <p_t>, <p_d>, <p_o>...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4127,NaN,1.0,sport,llama-3.1-8b-instant,GROQ_CLOUD,0.0,0.8,1.0,NaN,"A prediction <p> = (<p_s>, <p_t>, <p_d>, <p_o>...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4128,NaN,1.0,sport,llama-3.1-8b-instant,GROQ_CLOUD,0.0,0.8,1.0,NaN,"A prediction <p> = (<p_s>, <p_t>, <p_d>, <p_o>...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4483,NaN,1.0,sport,llama-3.1-8b-instant,GROQ_CLOUD,2.0,0.9,1.0,NaN,"A prediction <p> = (<p_s>, <p_t>, <p_d>, <p_o>...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4484,NaN,1.0,sport,llama-3.1-8b-instant,GROQ_CLOUD,2.0,0.9,1.0,NaN,"A prediction <p> = (<p_s>, <p_t>, <p_d>, <p_o>...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4485,NaN,1.0,sport,llama-3.1-8b-instant,GROQ_CLOUD,2.0,0.9,1.0,NaN,"A prediction <p> = (<p_s>, <p_t>, <p_d>, <p_o>...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4486,NaN,1.0,sport,llama-3.1-8b-instant,GROQ_CLOUD,2.0,0.9,1.0,NaN,"A prediction <p> = (<p_s>, <p_t>, <p_d>, <p_o>...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4487,NaN,1.0,sport,llama-3.1-8b-instant,GROQ_CLOUD,2.0,0.9,1.0,NaN,"A prediction <p> = (<p_s>, <p_t>, <p_d>, <p_o>...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4488,NaN,1.0,sport,llama-3.1-8b-instant,GROQ_CLOUD,2.0,0.9,1.0,NaN,"A prediction <p> = (<p_s>, <p_t>, <p_d>, <p_o>...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4566,NaN,1.0,miscellaneous,llama-3.1-8b-instant,GROQ_CLOUD,0.0,1.0,1.0,NaN,"A prediction <p> = (<p_s>, <p_t>, <p_d>, <p_o>...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4567,NaN,1.0,miscellaneous,llama-3.1-8b-instant,GROQ_CLOUD,0.0,1.0,1.0,NaN,"A prediction <p> = (<p_s>, <p_t>, <p_d>, <p_o>...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4568,NaN,1.0,miscellaneous,llama-3.1-8b-instant,GROQ_CLOUD,0.0,1.0,1.0,NaN,"A prediction <p> = (<p_s>, <p_t>, <p_d>, <p_o>...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4569,NaN,1.0,miscellaneous,llama-3.1-8b-instant,GROQ_CLOUD,0.0,1.0,1.0,NaN,"A prediction <p> = (<p_s>, <p_t>, <p_d>, <p_o>...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4570,NaN,1.0,miscellaneous,llama-3.1-8b-instant,GROQ_CLOUD,0.0,1.0,1.0,NaN,"A prediction <p> = (<p_s>, <p_t>, <p_d>, <p_o>...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4571,NaN,1.0,miscellaneous,llama-3.1-8b-instant,GROQ_CLOUD,0.0,1.0,1.0,NaN,"A prediction <p> = (<p_s>, <p_t>, <p_d>, <p_o>...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
df.drop(df[filt_null], inplace=True)
df

KeyError: "['Base Sentence', 'Ground Truth', 'Domain', 'Model Name', 'API Name', 'Batch ID', 'Temperature', 'Top P', 'Generated At', 'Prompt Used', 'Template Number', 'Prediction Date', 'Template Text', 'Dataset Name', 'Sentiment', 'maya_label', 'Sentence Label', 'Author Type', 'File Name', 'Human Annotation', 'Human Reasoning', 'Unnamed: 0', 'llama-3.1-8b-instant', 'llama-3.3-70b-versatile', 'openai/gpt-oss-120b', 'Majority Vote Label', 'Video ID', 'Base Sentence (raw)', 'Source', 'Date', 'Source Meta Data', 'title', 'description', 'URL', 'Image URL', 'content', 'Query Domain', 'query_string', 'query_slug', 'source_cache_file', 'article_id', 'prediction_visible', 'Source_Field', 'field_order', 'quality_batch_id', 'date', 'temp', 'precip', 'humidity', 'windspeed', 'label', 'Source Theory', 'Empirical Support', 'meta_data', 'forecast_due_date', 'question_set'] not found in axis"