# Climate Forecasts

1. DATASETS: [Hugging Face: Howard Tsai | All](https://huggingface.co/Howard881010)
2. DATASETS: [Hugging Face: Howard Tsai | Climate-1 Day](https://huggingface.co/datasets/Howard881010/climate-1day)

In [1]:
import os, sys

import pandas as pd

# Get the current working directory of the notebook
notebook_dir = os.getcwd()
# Add the parent directory to the system path
sys.path.append(os.path.join(notebook_dir, '../'))

from data_processing import DataProcessing
from feature_extraction import SpacyFeatureExtraction

In [2]:
pd.set_option('max_colwidth', 800)

In [3]:
base_data_path = DataProcessing.load_base_data_path(notebook_dir)
climate_dataset = os.path.join(base_data_path, 'others/', 'paper_mf/paper_mf_repo/data/climate/climate_2014_2023_final.csv')

In [4]:
df = DataProcessing.load_from_file(climate_dataset)
df

,date,temp,precip,humidity,windspeed,text
0,2014-01-01,37.9,0.000,57.4,10.0,"Arctic air is expected to invade the upper Midwest, Great Lakes, Ohio Valley, and Northeast, bringing some of the coldest temperatures in recent memory. Significant cold outbreaks on January 3-4 and 5-8 could result in temperatures 20-30 degrees Fahrenheit below normal. Lows in New England may reach -10s to -20s, and areas in eastern Montana, Minnesota, and Wisconsin may experience lows at or below -20F. Colder locations could drop to -30s or -40s Fahrenheit. Moderate upslope snow is anticipated across east-facing slopes from Montana to Northeast Wyoming. The coldest day is projected around January 8, with temperatures below freezing in a large section of the northern United States, potentially marking the coldest air masses since 1993/1994.\n\nPrecipitation is expected from a frontal ..."
1,2014-01-02,35.9,0.161,82.0,11.3,"Frigid air will sweep into the Midwest, Great Lakes, Ohio Valley, Northeast, and Mid-Atlantic early next week. A deep vortex will lead to significant temperature drops of -10 to -20 degrees across much of the central and eastern U.S., with the Ohio Valley potentially seeing temperatures nearly 40 degrees below normal by Monday. Heavy snow is anticipated northwest of a surface low tracking from the Lower Mississippi Valley to Interior New England, accompanied by strong winds, particularly across the Great Lakes. A strong Arctic front will move across the Appalachians on Sunday. By mid-week, temperatures should begin to moderate in the eastern half of the nation. Increasing moisture will bring rounds of precipitation to the Pacific Northwest, Intermountain West, and Great Basin as initia..."
2,2014-01-03,22.4,0.015,54.1,30.5,"Another arctic plunge is expected for the northeast quarter of the US Monday and Tuesday, leading to temperatures 20 to 40 degrees Fahrenheit below normal. A deep upper-level system over eastern Canada will influence this frigid air, while a fresh north Pacific flow will bring cooler and unsettled weather to the Great Lakes and northeast. Light to moderate precipitation is forecasted across the west, with potential localized enhancement along the coast. As the week progresses, precipitation is expected to increase from the southern plains into the Ohio and Tennessee valleys, with rain in the south transitioning to snow/mix further north. The forecast maintains good continuity despite some discrepancies between models regarding the impacts of cold advection associated with the arctic in..."
3,2014-01-04,25.4,0.000,52.6,13.3,"20°F-40°F below normal temperatures are expected in the northeastern quarter of the U.S. for January 7-11, 2014, with Indiana, Ohio, and western Pennsylvania experiencing temperatures 20°F+ below normal. An arctic blast will affect these regions, while the southeast and mid-Atlantic areas will also experience lower temperatures. The forecast incorporates a blend of GFS and GEFS solutions, with a notable phase of energy in the northern stream beyond day 4."
4,2014-01-05,37.1,0.041,78.7,11.0,"Temperatures are expected to approach normal values, with possibilities of being above normal. A progressive weather pattern will dominate the lower 48 states. Significant precipitation and strong winds are anticipated for the Pacific Northwest due to cyclogenesis off the Oregon/Washington coast. In the Midwest and Plains, a system originating from the South Central Rockies will bring rain through the Ohio Valley, influenced by a surface ridge in the Northeast and Mid-Atlantic. Mid-level warm advection will contribute to this precipitation. The GFS model shows discrepancies in predicted conditions in the Mid-Missouri Valley, while Gulf of Mexico moisture is expected to affect the Southern Plains and Lower-to-Mid Missouri Valley. A cutoff low over the Rio Grande Valley will also enhance..."
...,...,...,...,...,...,...
3617,2023-11-27,43.0,0.004,62.0,20.4,"Moderate to heavy rainfall is expected from Thursday, impacting the South, Southeast, and Mid-Mississippi Valley, particularly the eastern Texas Gulf Coast and western Louisiana where flash flooding is a concern. An upper-level shortwave will move from the Southwest to the Northeast this weekend, bringing unsettled weather. The Gulf Coast and Southeast will experience potentially heavy rainfall, with a marginal risk of excessive rainfall. The interior West will remain cooler than normal under reinforced troughing, while daytime highs in the Northern Plains, Midwest, and East could trend 5-10 degrees above average by the weekend. Precipitation will increase in the West, primarily along the Washington/Oregon coast and Cascades, with lighter amounts inland. The Western U.S. may return to ..."
3618,2023-11-28,35.7,0.001,42.2,25.0,"Wet pattern expected for the Northwest, with heavy snow threats inland from the Cascades and north-central Intermountain West/Rockies. From December 1 to December 5, 2023, widespread moderate to heavy rainfall is anticipated, particularly in the Gulf Coast and Southeast, with a marginal risk of excessive rainfall due to anomalous moisture and instability. High uncertainty in precipitation forecasts, especially across the east-central U.S. Precipitation is expected to increase in the West starting Thursday, leading to heaviest precipitation on the Washington/Oregon coast and Cascades from Sunday into Monday, along with accumulating snow in higher elevations. Stronger cyclogenesis may lead to larger-scale precipitation next week, impacting the Northeast as well."
3619,2023-11-29,32.9,0.000,41.8,10.1,"Multi-day wet pattern expected for the Northwest, with heavy snow threats from the Cascades to the north-central Intermountain West/Rockies. Active weather pattern continues through the weekend into next week, with systems moving from the interior West to the East Coast Saturday-Monday and ridging developing behind. An Atmospheric River may impact the West Coast this weekend, bringing ongoing precipitation and potential excessive rainfall in far northwest CA/southwest OR. Expect heavy snows and gusty winds in higher elevations of the Cascades and northern Sierras. Rainfall threat increases along the Oregon coast and western slopes of the Cascades, with another system bringing rain/mountain snow primarily to Washington state early next week. Moderate to heavy rainfall is likely for the ..."
3620,2023-11-30,42.1,0.000,51.4,10.5,"Heavy rain and inland heavy snow threats are expected in the Northwest due to a series of atmospheric rivers, with heavy snow threats also affecting the Northeast. An active weather pattern will bring heavy precipitation mainly across the Northwest and Northeast. In Washington and Oregon, heavy rainfall is anticipated, while the northern Intermountain West and Rockies could see significant snowfall. \n\nTemperatures in the Northern and Central Plains will be well above normal, reaching 15 to 25 degrees above average by Wednesday and Thursday. A strong ridge building over the West will influence these temperatures. Precipitation from atmospheric rivers will continue into next week, but with uncertainty in timing and volume.\n\nCoastal areas may experience modest rainfall, while the risk..."
3621,2023-12-01,45.6,0.123,73.4,10.7,"Heavy rain is expected in the Pacific Northwest due to multiple atmospheric river events from December 4 to December 8, 2023, possibly leading to flooding and rising river levels. Well above average temperatures, potentially 20-30 degrees higher than early December averages, are forecast for the Intermountain West and Plains, with record highs possible on Wednesday and Thursday. Snow showers may accompany a departing storm system in the Upper Midwest transitioning toward the Ohio Valley. A broad upper trough will bring active weather in the eastern U.S., with near seasonal temperatures expected, while a zonal flow pattern is anticipated by the end of the week. In the Northwest, 3-6 inch rainfall totals are likely, with a slight risk of flooding especially in the Cascades due to snow me..."

In [5]:
sfe = SpacyFeatureExtraction(df, 'text')
sfe

In [6]:
df = sfe.split_into_sentences(sentence_col_name='sentence')
df

Splitting into sentences: 100%|██████████| 3622/3622 [01:25<00:00, 42.50it/s]

,date,temp,precip,humidity,windspeed,text,sentence
0,2014-01-01,37.9,0.000,57.4,10.0,"Arctic air is expected to invade the upper Midwest, Great Lakes, Ohio Valley, and Northeast, bringing some of the coldest temperatures in recent memory. Significant cold outbreaks on January 3-4 and 5-8 could result in temperatures 20-30 degrees Fahrenheit below normal. Lows in New England may reach -10s to -20s, and areas in eastern Montana, Minnesota, and Wisconsin may experience lows at or below -20F. Colder locations could drop to -30s or -40s Fahrenheit. Moderate upslope snow is anticipated across east-facing slopes from Montana to Northeast Wyoming. The coldest day is projected around January 8, with temperatures below freezing in a large section of the northern United States, potentially marking the coldest air masses since 1993/1994.\n\nPrecipitation is expected from a frontal ...","Arctic air is expected to invade the upper Midwest, Great Lakes, Ohio Valley, and Northeast, bringing some of the coldest temperatures in recent memory."
1,2014-01-01,37.9,0.000,57.4,10.0,"Arctic air is expected to invade the upper Midwest, Great Lakes, Ohio Valley, and Northeast, bringing some of the coldest temperatures in recent memory. Significant cold outbreaks on January 3-4 and 5-8 could result in temperatures 20-30 degrees Fahrenheit below normal. Lows in New England may reach -10s to -20s, and areas in eastern Montana, Minnesota, and Wisconsin may experience lows at or below -20F. Colder locations could drop to -30s or -40s Fahrenheit. Moderate upslope snow is anticipated across east-facing slopes from Montana to Northeast Wyoming. The coldest day is projected around January 8, with temperatures below freezing in a large section of the northern United States, potentially marking the coldest air masses since 1993/1994.\n\nPrecipitation is expected from a frontal ...",Significant cold outbreaks on January 3-4 and 5-8 could result in temperatures 20-30 degrees Fahrenheit below normal.
2,2014-01-01,37.9,0.000,57.4,10.0,"Arctic air is expected to invade the upper Midwest, Great Lakes, Ohio Valley, and Northeast, bringing some of the coldest temperatures in recent memory. Significant cold outbreaks on January 3-4 and 5-8 could result in temperatures 20-30 degrees Fahrenheit below normal. Lows in New England may reach -10s to -20s, and areas in eastern Montana, Minnesota, and Wisconsin may experience lows at or below -20F. Colder locations could drop to -30s or -40s Fahrenheit. Moderate upslope snow is anticipated across east-facing slopes from Montana to Northeast Wyoming. The coldest day is projected around January 8, with temperatures below freezing in a large section of the northern United States, potentially marking the coldest air masses since 1993/1994.\n\nPrecipitation is expected from a frontal ...","Lows in New England may reach -10s to -20s, and areas in eastern Montana, Minnesota, and Wisconsin may experience lows at or below -20F. Colder locations could drop to -30s or -40s Fahrenheit."
3,2014-01-01,37.9,0.000,57.4,10.0,"Arctic air is expected to invade the upper Midwest, Great Lakes, Ohio Valley, and Northeast, bringing some of the coldest temperatures in recent memory. Significant cold outbreaks on January 3-4 and 5-8 could result in temperatures 20-30 degrees Fahrenheit below normal. Lows in New England may reach -10s to -20s, and areas in eastern Montana, Minnesota, and Wisconsin may experience lows at or below -20F. Colder locations could drop to -30s or -40s Fahrenheit. Moderate upslope snow is anticipated across east-facing slopes from Montana to Northeast Wyoming. The coldest day is projected around January 8, with temperatures below freezing in a large section of the northern United States, potentially marking the coldest air masses since 1993/1994.\n\nPrecipitation is expected from a frontal ...",Moderate upslope snow is anticipated across east-facing slopes from Montana to Northeast Wyoming.
4,2014-01-01,37.9,0.000,57.4,10.0,"Arctic air is expected to invade the upper Midwest, Great Lakes, Ohio Valley, and Northeast, bringing some of the coldest temperatures in recent memory. Significant cold outbreaks on January 3-4 and 5-8 could result in temperatures 20-30 degrees Fahrenheit below normal. Lows in New England may reach -10s to -20s, and areas in eastern Montana, Minnesota, and Wisconsin may experience lows at or below -20F. Colder locations could drop to -30s or -40s Fahrenheit. Moderate upslope snow is anticipated across east-facing slopes from Montana to Northeast Wyoming. The coldest day is projected around January 8, with temperatures below freezing in a large section of the northern United States, potentially marking the coldest air masses since 1993/1994.\n\nPrecipitation is expected from a frontal ...","The coldest day is projected around January 8, with temperatures below freezing in a large section of the northern United States, potentially marking the coldest air masses since 1993/1994."
...,...,...,...,...,...,...,...
25783,2023-12-01,45.6,0.123,73.4,10.7,"Heavy rain is expected in the Pacific Northwest due to multiple atmospheric river events from December 4 to December 8, 2023, possibly leading to flooding and rising river levels. Well above average temperatures, potentially 20-30 degrees higher than early December averages, are forecast for the Intermountain West and Plains, with record highs possible on Wednesday and Thursday. Snow showers may accompany a departing storm system in the Upper Midwest transitioning toward the Ohio Valley. A broad upper trough will bring active weather in the eastern U.S., with near seasonal temperatures expected, while a zonal flow pattern is anticipated by the end of the week. In the Northwest, 3-6 inch rainfall totals are likely, with a slight risk of flooding especially in the Cascades due to snow me...",Snow showers may accompany a departing storm system in the Upper Midwest transitioning toward the Ohio Valley.
25784,2023-12-01,45.6,0.123,73.4,10.7,"Heavy rain is expected in the Pacific Northwest due to multiple atmospheric river events from December 4 to December 8, 2023, possibly leading to flooding and rising river levels. Well above average temperatures, potentially 20-30 degrees higher than early December averages, are forecast for the Intermountain West and Plains, with record highs possible on Wednesday and Thursday. Snow showers may accompany a departing storm system in the Upper Midwest transitioning toward the Ohio Valley. A broad upper trough will bring active weather in the eastern U.S., with near seasonal temperatures expected, while a zonal flow pattern is anticipated by the end of the week. In the Northwest, 3-6 inch rainfall totals are likely, with a slight risk of flooding especially in the Cascades due to snow me...","A broad upper trough will bring active weather in the eastern U.S., with near seasonal temperatures expected, while a zonal flow pattern is anticipated by the end of the week."
25785,2023-12-01,45.6,0.123,73.4,10.7,"Heavy rain is expected in the Pacific Northwest due to multiple atmospheric river events from December 4 to December 8, 2023, possibly leading to flooding and rising river levels. Well above average temperatures, potentially 20-30 degrees higher than early December averages, are forecast for the Intermountain West and Plains, with record highs possible on Wednesday and Thursday. Snow showers may accompany a departing storm system in the Upper Midwest transitioning toward the Ohio Valley. A broad upper trough will bring active weather in the eastern U.S., with near seasonal temperatures expected, while a zonal flow pattern is anticipated by the end of the week. In the Northwest, 3-6 inch rainfall totals are likely, with a slight risk of flooding especially in the Cascades due to snow me...","In the Northwest, 3-6 inch rainfall totals are likely, with a slight risk of flooding especially in the Cascades due to snow melt."
25786,2023-12-01,45.6,0.123,73.4,10.7,"Heavy rain is expected in the Pacific Northwest due to multiple atmospheric river events from December 4 to December 8, 2023, possibly leading to flooding and rising river levels. Well above average temperatures, potentially 20-30 degrees higher than early December averages, are forecast for the Intermountain West and Plains, with record highs possible on Wednesday and Thursday. Snow showers may accompany a departing storm system in the Upper Midwest transitioning toward the Ohio Valley. A broad upper trough will bring active weather in the eastern U.S., with near seasonal temperatures expected, while a zonal flow pattern is anticipated by the end of the week. In the Northwest, 3-6 inch rainfall totals are likely, with a slight risk of flooding especially in the Cascades due to snow me...","Additionally, moderately heavy snow is expected in the northern Rockies and New England."
25787,2023-12-01,45.6,0.123,73.4,10.7,"Heavy rain is expected in the Pacific Northwest due to multiple atmospheric river events from December 4 to December 8, 2023, possibly leading to flooding and rising river levels. Well above average temperatures, potentially 20-30 degrees higher than early December averages, are forecast for the Intermountain West and Plains, with record highs possible on Wednesday and Thursday. Snow showers may accompany a departing storm system in the Upper Midwest transitioning toward the Ohio Valley. A broad upper trough will bring active weather in the eastern U.S., with near seasonal temperatures expected, while a zonal flow pattern is anticipated by the end of the week. In the Northwest, 3-6 inch rainfall totals are likely, with a slight risk of flooding especially in the Cascades due to snow me...",Winter weather impacts are also possible in the central Appalachians as low-pressure systems pass through.

In [17]:
df['label'] = 1
df

,date,temp,precip,humidity,windspeed,text,clean sentence,label
0,2014-01-01,37.9,0.000,57.4,10.0,"Arctic air is expected to invade the upper Midwest, Great Lakes, Ohio Valley, and Northeast, bringing some of the coldest temperatures in recent memory. Significant cold outbreaks on January 3-4 and 5-8 could result in temperatures 20-30 degrees Fahrenheit below normal. Lows in New England may reach -10s to -20s, and areas in eastern Montana, Minnesota, and Wisconsin may experience lows at or below -20F. Colder locations could drop to -30s or -40s Fahrenheit. Moderate upslope snow is anticipated across east-facing slopes from Montana to Northeast Wyoming. The coldest day is projected around January 8, with temperatures below freezing in a large section of the northern United States, potentially marking the coldest air masses since 1993/1994.\n\nPrecipitation is expected from a frontal ...","Arctic air is expected to invade the upper Midwest, Great Lakes, Ohio Valley, and Northeast, bringing some of the coldest temperatures in recent memory.",1
1,2014-01-01,37.9,0.000,57.4,10.0,"Arctic air is expected to invade the upper Midwest, Great Lakes, Ohio Valley, and Northeast, bringing some of the coldest temperatures in recent memory. Significant cold outbreaks on January 3-4 and 5-8 could result in temperatures 20-30 degrees Fahrenheit below normal. Lows in New England may reach -10s to -20s, and areas in eastern Montana, Minnesota, and Wisconsin may experience lows at or below -20F. Colder locations could drop to -30s or -40s Fahrenheit. Moderate upslope snow is anticipated across east-facing slopes from Montana to Northeast Wyoming. The coldest day is projected around January 8, with temperatures below freezing in a large section of the northern United States, potentially marking the coldest air masses since 1993/1994.\n\nPrecipitation is expected from a frontal ...",Significant cold outbreaks on January 3-4 and 5-8 could result in temperatures 20-30 degrees Fahrenheit below normal.,1
2,2014-01-01,37.9,0.000,57.4,10.0,"Arctic air is expected to invade the upper Midwest, Great Lakes, Ohio Valley, and Northeast, bringing some of the coldest temperatures in recent memory. Significant cold outbreaks on January 3-4 and 5-8 could result in temperatures 20-30 degrees Fahrenheit below normal. Lows in New England may reach -10s to -20s, and areas in eastern Montana, Minnesota, and Wisconsin may experience lows at or below -20F. Colder locations could drop to -30s or -40s Fahrenheit. Moderate upslope snow is anticipated across east-facing slopes from Montana to Northeast Wyoming. The coldest day is projected around January 8, with temperatures below freezing in a large section of the northern United States, potentially marking the coldest air masses since 1993/1994.\n\nPrecipitation is expected from a frontal ...","Lows in New England may reach -10s to -20s, and areas in eastern Montana, Minnesota, and Wisconsin may experience lows at or below -20F. Colder locations could drop to -30s or -40s Fahrenheit.",1
3,2014-01-01,37.9,0.000,57.4,10.0,"Arctic air is expected to invade the upper Midwest, Great Lakes, Ohio Valley, and Northeast, bringing some of the coldest temperatures in recent memory. Significant cold outbreaks on January 3-4 and 5-8 could result in temperatures 20-30 degrees Fahrenheit below normal. Lows in New England may reach -10s to -20s, and areas in eastern Montana, Minnesota, and Wisconsin may experience lows at or below -20F. Colder locations could drop to -30s or -40s Fahrenheit. Moderate upslope snow is anticipated across east-facing slopes from Montana to Northeast Wyoming. The coldest day is projected around January 8, with temperatures below freezing in a large section of the northern United States, potentially marking the coldest air masses since 1993/1994.\n\nPrecipitation is expected from a frontal ...",Moderate upslope snow is anticipated across east-facing slopes from Montana to Northeast Wyoming.,1
4,2014-01-01,37.9,0.000,57.4,10.0,"Arctic air is expected to invade the upper Midwest, Great Lakes, Ohio Valley, and Northeast, bringing some of the coldest temperatures in recent memory. Significant cold outbreaks on January 3-4 and 5-8 could result in temperatures 20-30 degrees Fahrenheit below normal. Lows in New England may reach -10s to -20s, and areas in eastern Montana, Minnesota, and Wisconsin may experience lows at or below -20F. Colder locations could drop to -30s or -40s Fahrenheit. Moderate upslope snow is anticipated across east-facing slopes from Montana to Northeast Wyoming. The coldest day is projected around January 8, with temperatures below freezing in a large section of the northern United States, potentially marking the coldest air masses since 1993/1994.\n\nPrecipitation is expected from a frontal ...","The coldest day is projected around January 8, with temperatures below freezing in a large section of the northern United States, potentially marking the coldest air masses since 1993/1994.",1
...,...,...,...,...,...,...,...,...
25783,2023-12-01,45.6,0.123,73.4,10.7,"Heavy rain is expected in the Pacific Northwest due to multiple atmospheric river events from December 4 to December 8, 2023, possibly leading to flooding and rising river levels. Well above average temperatures, potentially 20-30 degrees higher than early December averages, are forecast for the Intermountain West and Plains, with record highs possible on Wednesday and Thursday. Snow showers may accompany a departing storm system in the Upper Midwest transitioning toward the Ohio Valley. A broad upper trough will bring active weather in the eastern U.S., with near seasonal temperatures expected, while a zonal flow pattern is anticipated by the end of the week. In the Northwest, 3-6 inch rainfall totals are likely, with a slight risk of flooding especially in the Cascades due to snow me...",Snow showers may accompany a departing storm system in the Upper Midwest transitioning toward the Ohio Valley.,1
25784,2023-12-01,45.6,0.123,73.4,10.7,"Heavy rain is expected in the Pacific Northwest due to multiple atmospheric river events from December 4 to December 8, 2023, possibly leading to flooding and rising river levels. Well above average temperatures, potentially 20-30 degrees higher than early December averages, are forecast for the Intermountain West and Plains, with record highs possible on Wednesday and Thursday. Snow showers may accompany a departing storm system in the Upper Midwest transitioning toward the Ohio Valley. A broad upper trough will bring active weather in the eastern U.S., with near seasonal temperatures expected, while a zonal flow pattern is anticipated by the end of the week. In the Northwest, 3-6 inch rainfall totals are likely, with a slight risk of flooding especially in the Cascades due to snow me...","A broad upper trough will bring active weather in the eastern U.S., with near seasonal temperatures expected, while a zonal flow pattern is anticipated by the end of the week.",1
25785,2023-12-01,45.6,0.123,73.4,10.7,"Heavy rain is expected in the Pacific Northwest due to multiple atmospheric river events from December 4 to December 8, 2023, possibly leading to flooding and rising river levels. Well above average temperatures, potentially 20-30 degrees higher than early December averages, are forecast for the Intermountain West and Plains, with record highs possible on Wednesday and Thursday. Snow showers may accompany a departing storm system in the Upper Midwest transitioning toward the Ohio Valley. A broad upper trough will bring active weather in the eastern U.S., with near seasonal temperatures expected, while a zonal flow pattern is anticipated by the end of the week. In the Northwest, 3-6 inch rainfall totals are likely, with a slight risk of flooding especially in the Cascades due to snow me...","In the Northwest, 3-6 inch rainfall totals are likely, with a slight risk of flooding especially in the Cascades due to snow melt.",1
25786,2023-12-01,45.6,0.123,73.4,10.7,"Heavy rain is expected in the Pacific Northwest due to multiple atmospheric river events from December 4 to December 8, 2023, possibly leading to flooding and rising river levels. Well above average temperatures, potentially 20-30 degrees higher than early December averages, are forecast for the Intermountain West and Plains, with record highs possible on Wednesday and Thursday. Snow showers may accompany a departing storm system in the Upper Midwest transitioning toward the Ohio Valley. A broad upper trough will bring active weather in the eastern U.S., with near seasonal temperatures expected, while a zonal flow pattern is anticipated by the end of the week. In the Northwest, 3-6 inch rainfall totals are likely, with a slight risk of flooding especially in the Cascades due to snow me...","Additionally, moderately heavy snow is expected in the northern Rockies and New England.",1
25787,2023-12-01,45.6,0.123,73.4,10.7,"Heavy rain is expected in the Pacific Northwest due to multiple atmospheric river events from December 4 to December 8, 2023, possibly leading to flooding and rising river levels. Well above average temperatures, potentially 20-30 degrees higher than early December averages, are forecast for the Intermountain West and Plains, with record highs possible on Wednesday and Thursday. Snow showers may accompany a departing storm system in the Upper Midwest transitioning toward the Ohio Valley. A broad upper trough will bring active weather in the eastern U.S., with near seasonal temperatures expected, while a zonal flow pattern is anticipated by the end of the week. In the Northwest, 3-6 inch rainfall totals are likely, with a slight risk of flooding especially in the Cascades due to snow me...",Winter weather impacts are also possible in the central Appalachians as low-pressure systems pass through.,1

In [19]:
save_path = os.path.join(base_data_path, 'paper_mf', 'data', 'climate_forecasts')
DataProcessing.save_to_file(df, save_path, 'climate_forecasts', save_file_type='.csv')

Using file number: 1
Saving CSV file to: /Users/detraviousjamaribrinkley/Documents/Development/research_labs/uf_ds/predictions/notebook_experiments/../data/paper_mf/data/climate_forecasts/climate_forecasts-v1.csv

In [4]:
DataProcessing.load_mf_climate_dataset(notebook_dir)

============================================================
LOAD MF CLIMATE DATASET
============================================================
Loading from: /Users/detraviousjamaribrinkley/Documents/Development/research_labs/uf_ds/predictions/notebook_experiments/../data/paper_mf/data/climate_forecasts/climate_forecasts-v1.csv
Loaded shape: (25788, 8)
✓ Dropped 1 rows without labels
Filtered shape (predictions only): (25787, 8)
Columns: ['Base Sentence', 'Ground Truth', 'date', 'temp', 'precip', 'humidity', 'windspeed', 'text']

Ground Truth distribution:
Ground Truth
1    25787
Name: count, dtype: int64

Preview:
                                                                                                                                                                                      Base Sentence  \
0                                          Arctic air is expected to invade the upper Midwest, Great Lakes, Ohio Valley, and Northeast, bringing some of the coldest temperatures in recent memory.
1                                                                             Significant cold outbreaks on January 3-4 and 5-8 could result in temperatures 20-30 degrees Fahrenheit below normal.
2  Lows in New England may reach -10s to -20s, and areas in eastern Montana, Minnesota, and Wisconsin may experience lows at or below -20F. Colder locations could drop to -30s or -40s Fahrenheit.

   Ground Truth        date  temp  precip  humidity  windspeed  \
0             1  2014-01-01  37.9     0.0      57.4       10.0
1             1  2014-01-01  37.9     0.0      57.4       10.0
2             1  2014-01-01  37.9     0.0      57.4       10.0

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              text  \
0  Arctic air is expected to invade the upper Midwest, Great Lakes, Ohio Valley, and Northeast, bringing some of the coldest temperatures in recent memory. Significant cold outbreaks on January 3-4 and 5-8 could result in temperatures 20-30 degrees Fahrenheit below normal. Lows in New England may reach -10s to -20s, and areas in eastern Montana, Minnesota, and Wisconsin may experience lows at or below -20F. Colder locations could drop to -30s or -40s Fahrenheit. Moderate upslope snow is anticipated across east-facing slopes from Montana to Northeast Wyoming. The coldest day is projected around January 8, with temperatures below freezing in a large section of the northern United States, potentially marking the coldest air masses since 1993/1994.\n\nPrecipitation is expected from a frontal ...
1  Arctic air is expected to invade the upper Midwest, Great Lakes, Ohio Valley, and Northeast, bringing some of the coldest temperatures in recent memory. Significant cold outbreaks on January 3-4 and 5-8 could result in temperatures 20-30 degrees Fahrenheit below normal. Lows in New England may reach -10s to -20s, and areas in eastern Montana, Minnesota, and Wisconsin may experience lows at or below -20F. Colder locations could drop to -30s or -40s Fahrenheit. Moderate upslope snow is anticipated across east-facing slopes from Montana to Northeast Wyoming. The coldest day is projected around January 8, with temperatures below freezing in a large section of the northern United States, potentially marking the coldest air masses since 1993/1994.\n\nPrecipitation is expected from a frontal ...
2  Arctic air is expected to invade the upper Midwest, Great Lakes, Ohio Valley, and Northeast, bringing some of the coldest temperatures in recent memory. Significant cold outbreaks on January 3-4 and 5-8 could result in temperatures 20-30 degrees Fahrenheit below normal. Lows in New England may reach -10s to -20s, and areas in eastern Montana, Minnesota, and Wisconsin may experience lows at or below -20F. Colder locations could drop to -30s or -40s Fahrenheit. Moderate upslope snow is anticipated across east-facing slopes from Montana to Northeast Wyoming. The coldest day is projected around January 8, with temperatures below freezing in a large section of the northern United States, potentially marking the coldest air masses since 1993/1994.\n\nPrecipitation is expected from a frontal ...

            Dataset Name
0  mf_climate-imbalanced
1  mf_climate-imbalanced
2  mf_climate-imbalanced

,Base Sentence,Ground Truth,date,temp,precip,humidity,windspeed,text,Dataset Name
0,"Arctic air is expected to invade the upper Midwest, Great Lakes, Ohio Valley, and Northeast, bringing some of the coldest temperatures in recent memory.",1,2014-01-01,37.9,0.000,57.4,10.0,"Arctic air is expected to invade the upper Midwest, Great Lakes, Ohio Valley, and Northeast, bringing some of the coldest temperatures in recent memory. Significant cold outbreaks on January 3-4 and 5-8 could result in temperatures 20-30 degrees Fahrenheit below normal. Lows in New England may reach -10s to -20s, and areas in eastern Montana, Minnesota, and Wisconsin may experience lows at or below -20F. Colder locations could drop to -30s or -40s Fahrenheit. Moderate upslope snow is anticipated across east-facing slopes from Montana to Northeast Wyoming. The coldest day is projected around January 8, with temperatures below freezing in a large section of the northern United States, potentially marking the coldest air masses since 1993/1994.\n\nPrecipitation is expected from a frontal ...",mf_climate-imbalanced
1,Significant cold outbreaks on January 3-4 and 5-8 could result in temperatures 20-30 degrees Fahrenheit below normal.,1,2014-01-01,37.9,0.000,57.4,10.0,"Arctic air is expected to invade the upper Midwest, Great Lakes, Ohio Valley, and Northeast, bringing some of the coldest temperatures in recent memory. Significant cold outbreaks on January 3-4 and 5-8 could result in temperatures 20-30 degrees Fahrenheit below normal. Lows in New England may reach -10s to -20s, and areas in eastern Montana, Minnesota, and Wisconsin may experience lows at or below -20F. Colder locations could drop to -30s or -40s Fahrenheit. Moderate upslope snow is anticipated across east-facing slopes from Montana to Northeast Wyoming. The coldest day is projected around January 8, with temperatures below freezing in a large section of the northern United States, potentially marking the coldest air masses since 1993/1994.\n\nPrecipitation is expected from a frontal ...",mf_climate-imbalanced
2,"Lows in New England may reach -10s to -20s, and areas in eastern Montana, Minnesota, and Wisconsin may experience lows at or below -20F. Colder locations could drop to -30s or -40s Fahrenheit.",1,2014-01-01,37.9,0.000,57.4,10.0,"Arctic air is expected to invade the upper Midwest, Great Lakes, Ohio Valley, and Northeast, bringing some of the coldest temperatures in recent memory. Significant cold outbreaks on January 3-4 and 5-8 could result in temperatures 20-30 degrees Fahrenheit below normal. Lows in New England may reach -10s to -20s, and areas in eastern Montana, Minnesota, and Wisconsin may experience lows at or below -20F. Colder locations could drop to -30s or -40s Fahrenheit. Moderate upslope snow is anticipated across east-facing slopes from Montana to Northeast Wyoming. The coldest day is projected around January 8, with temperatures below freezing in a large section of the northern United States, potentially marking the coldest air masses since 1993/1994.\n\nPrecipitation is expected from a frontal ...",mf_climate-imbalanced
3,Moderate upslope snow is anticipated across east-facing slopes from Montana to Northeast Wyoming.,1,2014-01-01,37.9,0.000,57.4,10.0,"Arctic air is expected to invade the upper Midwest, Great Lakes, Ohio Valley, and Northeast, bringing some of the coldest temperatures in recent memory. Significant cold outbreaks on January 3-4 and 5-8 could result in temperatures 20-30 degrees Fahrenheit below normal. Lows in New England may reach -10s to -20s, and areas in eastern Montana, Minnesota, and Wisconsin may experience lows at or below -20F. Colder locations could drop to -30s or -40s Fahrenheit. Moderate upslope snow is anticipated across east-facing slopes from Montana to Northeast Wyoming. The coldest day is projected around January 8, with temperatures below freezing in a large section of the northern United States, potentially marking the coldest air masses since 1993/1994.\n\nPrecipitation is expected from a frontal ...",mf_climate-imbalanced
4,"The coldest day is projected around January 8, with temperatures below freezing in a large section of the northern United States, potentially marking the coldest air masses since 1993/1994.",1,2014-01-01,37.9,0.000,57.4,10.0,"Arctic air is expected to invade the upper Midwest, Great Lakes, Ohio Valley, and Northeast, bringing some of the coldest temperatures in recent memory. Significant cold outbreaks on January 3-4 and 5-8 could result in temperatures 20-30 degrees Fahrenheit below normal. Lows in New England may reach -10s to -20s, and areas in eastern Montana, Minnesota, and Wisconsin may experience lows at or below -20F. Colder locations could drop to -30s or -40s Fahrenheit. Moderate upslope snow is anticipated across east-facing slopes from Montana to Northeast Wyoming. The coldest day is projected around January 8, with temperatures below freezing in a large section of the northern United States, potentially marking the coldest air masses since 1993/1994.\n\nPrecipitation is expected from a frontal ...",mf_climate-imbalanced
...,...,...,...,...,...,...,...,...,...
25783,Snow showers may accompany a departing storm system in the Upper Midwest transitioning toward the Ohio Valley.,1,2023-12-01,45.6,0.123,73.4,10.7,"Heavy rain is expected in the Pacific Northwest due to multiple atmospheric river events from December 4 to December 8, 2023, possibly leading to flooding and rising river levels. Well above average temperatures, potentially 20-30 degrees higher than early December averages, are forecast for the Intermountain West and Plains, with record highs possible on Wednesday and Thursday. Snow showers may accompany a departing storm system in the Upper Midwest transitioning toward the Ohio Valley. A broad upper trough will bring active weather in the eastern U.S., with near seasonal temperatures expected, while a zonal flow pattern is anticipated by the end of the week. In the Northwest, 3-6 inch rainfall totals are likely, with a slight risk of flooding especially in the Cascades due to snow me...",mf_climate-imbalanced
25784,"A broad upper trough will bring active weather in the eastern U.S., with near seasonal temperatures expected, while a zonal flow pattern is anticipated by the end of the week.",1,2023-12-01,45.6,0.123,73.4,10.7,"Heavy rain is expected in the Pacific Northwest due to multiple atmospheric river events from December 4 to December 8, 2023, possibly leading to flooding and rising river levels. Well above average temperatures, potentially 20-30 degrees higher than early December averages, are forecast for the Intermountain West and Plains, with record highs possible on Wednesday and Thursday. Snow showers may accompany a departing storm system in the Upper Midwest transitioning toward the Ohio Valley. A broad upper trough will bring active weather in the eastern U.S., with near seasonal temperatures expected, while a zonal flow pattern is anticipated by the end of the week. In the Northwest, 3-6 inch rainfall totals are likely, with a slight risk of flooding especially in the Cascades due to snow me...",mf_climate-imbalanced
25785,"In the Northwest, 3-6 inch rainfall totals are likely, with a slight risk of flooding especially in the Cascades due to snow melt.",1,2023-12-01,45.6,0.123,73.4,10.7,"Heavy rain is expected in the Pacific Northwest due to multiple atmospheric river events from December 4 to December 8, 2023, possibly leading to flooding and rising river levels. Well above average temperatures, potentially 20-30 degrees higher than early December averages, are forecast for the Intermountain West and Plains, with record highs possible on Wednesday and Thursday. Snow showers may accompany a departing storm system in the Upper Midwest transitioning toward the Ohio Valley. A broad upper trough will bring active weather in the eastern U.S., with near seasonal temperatures expected, while a zonal flow pattern is anticipated by the end of the week. In the Northwest, 3-6 inch rainfall totals are likely, with a slight risk of flooding especially in the Cascades due to snow me...",mf_climate-imbalanced
25786,"Additionally, moderately heavy snow is expected in the northern Rockies and New England.",1,2023-12-01,45.6,0.123,73.4,10.7,"Heavy rain is expected in the Pacific Northwest due to multiple atmospheric river events from December 4 to December 8, 2023, possibly leading to flooding and rising river levels. Well above average temperatures, potentially 20-30 degrees higher than early December averages, are forecast for the Intermountain West and Plains, with record highs possible on Wednesday and Thursday. Snow showers may accompany a departing storm system in the Upper Midwest transitioning toward the Ohio Valley. A broad upper trough will bring active weather in the eastern U.S., with near seasonal temperatures expected, while a zonal flow pattern is anticipated by the end of the week. In the Northwest, 3-6 inch rainfall totals are likely, with a slight risk of flooding especially in the Cascades due to snow me...",mf_climate-imbalanced
25787,Winter weather impacts are also possible in the central Appalachians as low-pressure systems pass through.,1,2023-12-01,45.6,0.123,73.4,10.7,"Heavy rain is expected in the Pacific Northwest due to multiple atmospheric river events from December 4 to December 8, 2023, possibly leading to flooding and rising river levels. Well above average temperatures, potentially 20-30 degrees higher than early December averages, are forecast for the Intermountain West and Plains, with record highs possible on Wednesday and Thursday. Snow showers may accompany a departing storm system in the Upper Midwest transitioning toward the Ohio Valley. A broad upper trough will bring active weather in the eastern U.S., with near seasonal temperatures expected, while a zonal flow pattern is anticipated by the end of the week. In the Northwest, 3-6 inch rainfall totals are likely, with a slight risk of flooding especially in the Cascades due to snow me...",mf_climate-imbalanced

## Check bad sentences

In [7]:
df[
    df["sentence"].str.contains(r"°F", regex=True, na=False)
][["sentence"]].head(10)

                                                                                                                                                                                                                                                                                                                                                                                    sentence
7                                                                                                                                                                                                                                                                              The Gold Coast of Florida will remain slightly above normal, with temperatures struggling to drop below 60°F.
22                                                                                                                                                                               20°F-40°F below normal temperatures are expected in the northeastern quarter of the U.S. for January 7-11, 2014, with Indiana, Ohio, and western Pennsylvania experiencing temperatures 20°F+ below normal.
60                                                                                                                                                                                                                                                                              Florida will cool off from Wednesday into Friday, with temperatures dropping approximately 6°F below normal.
61                                                                                                                                                                                                                   Most of the country will experience temperatures around 15°F above normal, though the northern tier will see a return to milder conditions due to modified Pacific air.
64                                                                                                                                                                           Models indicate a warm and dry pattern in the western U.S. due to a ridge, with daytime highs in CA, NV, and OR potentially 15-20°F above normal, and 20-30°F above normal in the northern plains on Wednesday.
65                                                                                                                                                                                                                                                                                                              The central plains may see highs 10-20°F above normal Wednesday to Thursday.
67                                                                                                                                                                                                                        Minimum temperatures near freezing are expected around the central Gulf Coast by next Saturday, with no significant drops below normal (10-15°F below normal max).
74                                                                                                                                                                                                                                                                                       Above-normal temperatures are expected in the West, with anomalies reaching +15-20°F in some areas.
77                                                                                                                                                                Northern-Central Plains will see temperatures 20-25°F above normal midweek, while the Mississippi Valley may experience temperatures 5-15°F below normal later in the week, before warming trends return over the weekend.
106  The medium range forecast from January 20 to January 24, 2014, will feature strong ridging over western Canada and longwave troughing in the eastern U.S. Above-normal high temperatures are expected west of the continental divide, while central, eastern, and southeastern states will see below-normal temperatures (10-20°F below climatological averages) due to an Arctic push.

In [10]:
# Return sentences that likely indicate bad sentence splits
bad_sentences = df[
    # Starts with dangling symbols or units (but not valid numbers)
    df["sentence"].str.match(r"^(°F|\+F|F\+|[^\w\d])", na=False)
    |
    # Ends mid temperature or numeric range expression
    df["sentence"].str.contains(r"(°F[-+]$|\d-\s*$)", regex=True, na=False)
]

bad_sentences[["sentence"]]

/var/folders/78/9z0b45fx1xqbwxh8vk97lcfh0000gn/T/ipykernel_88735/3534759063.py:7: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  df["sentence"].str.contains(r"(°F[-+]$|\d-\s*$)", regex=True, na=False)

                                                                                                                                                                                                                                                                                              sentence
5205                                                                                                                                            **Weather Forecast (April 4-8, 2016)**\n\nRecord warmth expected in the western U.S., while the eastern U.S. will experience record cold and snowfall.
8228                                                                                                                                           - Widespread precipitation expected on Monday from the Northern Rockies and East Central MT, as well as isolated storms from MN/WI to the TX Panhandle.
8874                                                                                                                                    **Forecast Period (Sept 16 - Sept 20, 2017):**  \n- **Temperature:** Below average highs (10-20 degrees) across OR, northern CA, NV, and the northern Rockies.
8879   **Additional Notes:**  \n- Hurricane Jose remains offshore, with uncertainty regarding its track and influence on the eastern U.S. \n- Model discrepancies continue regarding the behavior of the mid-level trough and hurricane dynamics, affecting precipitation forecasts across the plains.
9039                                                                                                                                    - Central Rockies: Highs at least 20°F below normal early week, moderating to near normal later on.\n- West Coast/Northern Rockies: Highs 5-15°F below normal.
12946                                             - Severe weather across the Southeast, Mid-Atlantic, and Lower Mississippi Valley (April 14).\n- Flooding concerns in the Middle and Upper Mississippi Valleys, Great Lakes, and Northern Plains, with significant flooding expected in prone areas.
12947                                                                                                                                                                      - Much below normal temperatures in the Southern Rockies, Central Rockies, Southern Plains, and Central Plains on April 14.
21352                                                                                                                                                                                                                                                                             **Forecast Summary**

In [11]:
bad_sentences

,date,temp,precip,humidity,windspeed,text,sentence
5205,2016-04-01,71.9,0.052,67.7,21.4,"**Weather Forecast (April 4-8, 2016)**\n\nRecord warmth expected in the western U.S., while the eastern U.S. will experience record cold and snowfall. A ridge will build in the northern Rockies, leading to a milder pattern in the west, with temperatures likely 10-25 degrees above average. Conversely, a significant cold front will bring temperatures to the teens and single digits in the northeast, 10-25 degrees below average, especially on Wednesday. Snow is forecasted along the I-90/88/86 corridor, with high pressure following the system leading to colder conditions.\n\nPrecipitation is expected in the northeast on Monday and again later in the week as systems move through the Great Lakes. Late next week, an increase in rain and snow is likely due to moisture from the Atlantic. Meanwhi...","**Weather Forecast (April 4-8, 2016)**\n\nRecord warmth expected in the western U.S., while the eastern U.S. will experience record cold and snowfall."
8228,2017-06-08,65.4,0.000,63.2,12.0,"Well below average temperatures are expected in the West, with a core of 10-15 degrees below average across the West Coast and Northern Rockies. The Upper Midwest will experience a negative temperature anomaly due to a closed low system moving from CA/NV to the Northern Rockies. The Northeast will see summer-like conditions with above average temperatures, potentially reaching 10-15 degrees above normal, and possible record highs from IA/MN/WI on Sunday and major cities from DC to NYC/BOS on Monday and Tuesday. \n\nPrecipitation will be widespread: \n- Scattered showers and storms will occur from the Interior Northwest to the Upper Mississippi Valley/Great Lakes on Sunday.\n- Enhanced sea breeze convection with heavy rain along the East Central Gulf Coast. \n- Widespread precipitation ...","- Widespread precipitation expected on Monday from the Northern Rockies and East Central MT, as well as isolated storms from MN/WI to the TX Panhandle."
8874,2017-09-13,72.0,0.044,85.8,10.8,"**Forecast Period (Sept 16 - Sept 20, 2017):** \n- **Temperature:** Below average highs (10-20 degrees) across OR, northern CA, NV, and the northern Rockies. Above average temperatures across central/southern plains to Great Lakes/Northeast with highs averaging 10 degrees above normal in KS, OK, IA, MO, IL, WI, and parts of the eastern Great Lakes. Early November-like conditions in MT, WY, and ID with Saturday highs in the 40s, then moderating into Monday, before another cold wave arrives Tuesday and Wednesday.\n \n- **Precipitation:** Highest chances from the central/northern Rockies to the upper Midwest associated with a surface low. Significant QPF expected along the WA/OR coast and the Cascades, as well as in the Northern Inter-Mountain West. High elevation snow possible in the C...","**Forecast Period (Sept 16 - Sept 20, 2017):** \n- **Temperature:** Below average highs (10-20 degrees) across OR, northern CA, NV, and the northern Rockies."
8879,2017-09-13,72.0,0.044,85.8,10.8,"**Forecast Period (Sept 16 - Sept 20, 2017):** \n- **Temperature:** Below average highs (10-20 degrees) across OR, northern CA, NV, and the northern Rockies. Above average temperatures across central/southern plains to Great Lakes/Northeast with highs averaging 10 degrees above normal in KS, OK, IA, MO, IL, WI, and parts of the eastern Great Lakes. Early November-like conditions in MT, WY, and ID with Saturday highs in the 40s, then moderating into Monday, before another cold wave arrives Tuesday and Wednesday.\n \n- **Precipitation:** Highest chances from the central/northern Rockies to the upper Midwest associated with a surface low. Significant QPF expected along the WA/OR coast and the Cascades, as well as in the Northern Inter-Mountain West. High elevation snow possible in the C...","**Additional Notes:** \n- Hurricane Jose remains offshore, with uncertainty regarding its track and influence on the eastern U.S. \n- Model discrepancies continue regarding the behavior of the mid-level trough and hurricane dynamics, affecting precipitation forecasts across the plains."
9039,2017-10-06,72.7,0.000,72.7,10.1,"Guidance indicates a consistent large-scale flow with a ridge building over and south of the southern tier states and mean troughing over the west coast. Tropical cyclone Nate is expected to weaken as it makes landfall along the central Gulf Coast and accelerates northeastward. \n\nFrom Monday to Wednesday, warm temperatures are predicted in the eastern U.S. with highs 10-15°F above normal and minimum temperatures 15-20°F above normal. Cooler conditions will develop later in the week, returning to seasonal levels. Some early week precipitation in the central Rockies could be in the form of snow. \n\nIn the western states, cooling trends with highs 5-15°F below normal anticipated as an upper trough settles over the region. Precipitation will gradually increase, particularly over the Ca...","- Central Rockies: Highs at least 20°F below normal early week, moderating to near normal later on.\n- West Coast/Northern Rockies: Highs 5-15°F below normal."
12946,2019-04-11,55.6,0.000,52.8,17.6,"Heavy rainfall and flooding threats from two major spring storms are expected from the mid-lower Mississippi Valley to the Ohio Valley this weekend and into midweek. There is potential for excessive rainfall and flash flooding due to deep moisture (1.5+ standard deviations above normal) being pulled in from the Gulf of Mexico. Severe weather risks are present in the South as a potent low pressure system tracks northeast, potentially bringing snow/ice to northern New England. A trailing cold front will result in additional rains and convection across various regions, particularly affecting the West Coast on Sunday. Cyclogenesis in the Plains is likely to enhance rainfall as Gulf moisture returns, with areas previously impacted expected to see repeat heavy rain and severe weather threats...","- Severe weather across the Southeast, Mid-Atlantic, and Lower Mississippi Valley (April 14).\n- Flooding concerns in the Middle and Upper Mississippi Valleys, Great Lakes, and Northern Plains, with significant flooding expected in prone areas."
12947,2019-04-11,55.6,0.000,52.8,17.6,"Heavy rainfall and flooding threats from two major spring storms are expected from the mid-lower Mississippi Valley to the Ohio Valley this weekend and into midweek. There is potential for excessive rainfall and flash flooding due to deep moisture (1.5+ standard deviations above normal) being pulled in from the Gulf of Mexico. Severe weather risks are present in the South as a potent low pressure system tracks northeast, potentially bringing snow/ice to northern New England. A trailing cold front will result in additional rains and convection across various regions, particularly affecting the West Coast on Sunday. Cyclogenesis in the Plains is likely to enhance rainfall as Gulf moisture returns, with areas previously impacted expected to see repeat heavy rain and severe weather threats...","- Much below normal temperatures in the Southern Rockies, Central Rockies, Southern Plains, and Central Plains on April 14."
21352,2022-05-13,67.4,0.144,84.4,12.3,"**Forecast Summary** \nRecord-breaking heat is expected across the south-central U.S. next week, particularly in Texas and Louisiana, with highs 15-25°F above normal. Unseasonably hot weather will also affect the southern tier, while cooling temperatures and precipitation dominate the Pacific Northwest due to upper troughing. Showers and thunderstorms are anticipated along fronts in the East, especially on Monday, with potential heavy rainfall and localized flooding in New England. There are concerns of heavy rain across the Upper Mississippi and Tennessee Valleys midweek due to multiple weather systems. Snow levels will initially be high but are expected to decrease as the week progresses. The forecast indicates two rainfall regimes east of the Rockies with uncertainty regarding amou...",**Forecast Summary**

In [12]:
import re

def normalize_forecast_text(text: str) -> str:
    if not isinstance(text, str):
        return text

    # Remove markdown bold/italics
    text = re.sub(r"\*\*(.*?)\*\*", r"\1", text)

    # Remove standalone headers (lines with no sentence punctuation)
    text = re.sub(
        r"(?m)^(?:[A-Z][A-Za-z\s]+(?:\([^)]+\))?:)\s*$",
        "",
        text
    )

    # Convert bullet points to sentences
    text = re.sub(r"(?m)^-\s+", "", text)

    # Collapse excessive newlines
    text = re.sub(r"\n{2,}", " ", text)

    return text.strip()

In [14]:
df["text"] = df["text"].apply(normalize_forecast_text)
df = sfe.split_into_sentences(sentence_col_name='clean sentence')
df

Splitting into sentences: 100%|██████████| 3622/3622 [01:22<00:00, 43.65it/s]

,date,temp,precip,humidity,windspeed,text,clean sentence
0,2014-01-01,37.9,0.000,57.4,10.0,"Arctic air is expected to invade the upper Midwest, Great Lakes, Ohio Valley, and Northeast, bringing some of the coldest temperatures in recent memory. Significant cold outbreaks on January 3-4 and 5-8 could result in temperatures 20-30 degrees Fahrenheit below normal. Lows in New England may reach -10s to -20s, and areas in eastern Montana, Minnesota, and Wisconsin may experience lows at or below -20F. Colder locations could drop to -30s or -40s Fahrenheit. Moderate upslope snow is anticipated across east-facing slopes from Montana to Northeast Wyoming. The coldest day is projected around January 8, with temperatures below freezing in a large section of the northern United States, potentially marking the coldest air masses since 1993/1994.\n\nPrecipitation is expected from a frontal ...","Arctic air is expected to invade the upper Midwest, Great Lakes, Ohio Valley, and Northeast, bringing some of the coldest temperatures in recent memory."
1,2014-01-01,37.9,0.000,57.4,10.0,"Arctic air is expected to invade the upper Midwest, Great Lakes, Ohio Valley, and Northeast, bringing some of the coldest temperatures in recent memory. Significant cold outbreaks on January 3-4 and 5-8 could result in temperatures 20-30 degrees Fahrenheit below normal. Lows in New England may reach -10s to -20s, and areas in eastern Montana, Minnesota, and Wisconsin may experience lows at or below -20F. Colder locations could drop to -30s or -40s Fahrenheit. Moderate upslope snow is anticipated across east-facing slopes from Montana to Northeast Wyoming. The coldest day is projected around January 8, with temperatures below freezing in a large section of the northern United States, potentially marking the coldest air masses since 1993/1994.\n\nPrecipitation is expected from a frontal ...",Significant cold outbreaks on January 3-4 and 5-8 could result in temperatures 20-30 degrees Fahrenheit below normal.
2,2014-01-01,37.9,0.000,57.4,10.0,"Arctic air is expected to invade the upper Midwest, Great Lakes, Ohio Valley, and Northeast, bringing some of the coldest temperatures in recent memory. Significant cold outbreaks on January 3-4 and 5-8 could result in temperatures 20-30 degrees Fahrenheit below normal. Lows in New England may reach -10s to -20s, and areas in eastern Montana, Minnesota, and Wisconsin may experience lows at or below -20F. Colder locations could drop to -30s or -40s Fahrenheit. Moderate upslope snow is anticipated across east-facing slopes from Montana to Northeast Wyoming. The coldest day is projected around January 8, with temperatures below freezing in a large section of the northern United States, potentially marking the coldest air masses since 1993/1994.\n\nPrecipitation is expected from a frontal ...","Lows in New England may reach -10s to -20s, and areas in eastern Montana, Minnesota, and Wisconsin may experience lows at or below -20F. Colder locations could drop to -30s or -40s Fahrenheit."
3,2014-01-01,37.9,0.000,57.4,10.0,"Arctic air is expected to invade the upper Midwest, Great Lakes, Ohio Valley, and Northeast, bringing some of the coldest temperatures in recent memory. Significant cold outbreaks on January 3-4 and 5-8 could result in temperatures 20-30 degrees Fahrenheit below normal. Lows in New England may reach -10s to -20s, and areas in eastern Montana, Minnesota, and Wisconsin may experience lows at or below -20F. Colder locations could drop to -30s or -40s Fahrenheit. Moderate upslope snow is anticipated across east-facing slopes from Montana to Northeast Wyoming. The coldest day is projected around January 8, with temperatures below freezing in a large section of the northern United States, potentially marking the coldest air masses since 1993/1994.\n\nPrecipitation is expected from a frontal ...",Moderate upslope snow is anticipated across east-facing slopes from Montana to Northeast Wyoming.
4,2014-01-01,37.9,0.000,57.4,10.0,"Arctic air is expected to invade the upper Midwest, Great Lakes, Ohio Valley, and Northeast, bringing some of the coldest temperatures in recent memory. Significant cold outbreaks on January 3-4 and 5-8 could result in temperatures 20-30 degrees Fahrenheit below normal. Lows in New England may reach -10s to -20s, and areas in eastern Montana, Minnesota, and Wisconsin may experience lows at or below -20F. Colder locations could drop to -30s or -40s Fahrenheit. Moderate upslope snow is anticipated across east-facing slopes from Montana to Northeast Wyoming. The coldest day is projected around January 8, with temperatures below freezing in a large section of the northern United States, potentially marking the coldest air masses since 1993/1994.\n\nPrecipitation is expected from a frontal ...","The coldest day is projected around January 8, with temperatures below freezing in a large section of the northern United States, potentially marking the coldest air masses since 1993/1994."
...,...,...,...,...,...,...,...
25783,2023-12-01,45.6,0.123,73.4,10.7,"Heavy rain is expected in the Pacific Northwest due to multiple atmospheric river events from December 4 to December 8, 2023, possibly leading to flooding and rising river levels. Well above average temperatures, potentially 20-30 degrees higher than early December averages, are forecast for the Intermountain West and Plains, with record highs possible on Wednesday and Thursday. Snow showers may accompany a departing storm system in the Upper Midwest transitioning toward the Ohio Valley. A broad upper trough will bring active weather in the eastern U.S., with near seasonal temperatures expected, while a zonal flow pattern is anticipated by the end of the week. In the Northwest, 3-6 inch rainfall totals are likely, with a slight risk of flooding especially in the Cascades due to snow me...",Snow showers may accompany a departing storm system in the Upper Midwest transitioning toward the Ohio Valley.
25784,2023-12-01,45.6,0.123,73.4,10.7,"Heavy rain is expected in the Pacific Northwest due to multiple atmospheric river events from December 4 to December 8, 2023, possibly leading to flooding and rising river levels. Well above average temperatures, potentially 20-30 degrees higher than early December averages, are forecast for the Intermountain West and Plains, with record highs possible on Wednesday and Thursday. Snow showers may accompany a departing storm system in the Upper Midwest transitioning toward the Ohio Valley. A broad upper trough will bring active weather in the eastern U.S., with near seasonal temperatures expected, while a zonal flow pattern is anticipated by the end of the week. In the Northwest, 3-6 inch rainfall totals are likely, with a slight risk of flooding especially in the Cascades due to snow me...","A broad upper trough will bring active weather in the eastern U.S., with near seasonal temperatures expected, while a zonal flow pattern is anticipated by the end of the week."
25785,2023-12-01,45.6,0.123,73.4,10.7,"Heavy rain is expected in the Pacific Northwest due to multiple atmospheric river events from December 4 to December 8, 2023, possibly leading to flooding and rising river levels. Well above average temperatures, potentially 20-30 degrees higher than early December averages, are forecast for the Intermountain West and Plains, with record highs possible on Wednesday and Thursday. Snow showers may accompany a departing storm system in the Upper Midwest transitioning toward the Ohio Valley. A broad upper trough will bring active weather in the eastern U.S., with near seasonal temperatures expected, while a zonal flow pattern is anticipated by the end of the week. In the Northwest, 3-6 inch rainfall totals are likely, with a slight risk of flooding especially in the Cascades due to snow me...","In the Northwest, 3-6 inch rainfall totals are likely, with a slight risk of flooding especially in the Cascades due to snow melt."
25786,2023-12-01,45.6,0.123,73.4,10.7,"Heavy rain is expected in the Pacific Northwest due to multiple atmospheric river events from December 4 to December 8, 2023, possibly leading to flooding and rising river levels. Well above average temperatures, potentially 20-30 degrees higher than early December averages, are forecast for the Intermountain West and Plains, with record highs possible on Wednesday and Thursday. Snow showers may accompany a departing storm system in the Upper Midwest transitioning toward the Ohio Valley. A broad upper trough will bring active weather in the eastern U.S., with near seasonal temperatures expected, while a zonal flow pattern is anticipated by the end of the week. In the Northwest, 3-6 inch rainfall totals are likely, with a slight risk of flooding especially in the Cascades due to snow me...","Additionally, moderately heavy snow is expected in the northern Rockies and New England."
25787,2023-12-01,45.6,0.123,73.4,10.7,"Heavy rain is expected in the Pacific Northwest due to multiple atmospheric river events from December 4 to December 8, 2023, possibly leading to flooding and rising river levels. Well above average temperatures, potentially 20-30 degrees higher than early December averages, are forecast for the Intermountain West and Plains, with record highs possible on Wednesday and Thursday. Snow showers may accompany a departing storm system in the Upper Midwest transitioning toward the Ohio Valley. A broad upper trough will bring active weather in the eastern U.S., with near seasonal temperatures expected, while a zonal flow pattern is anticipated by the end of the week. In the Northwest, 3-6 inch rainfall totals are likely, with a slight risk of flooding especially in the Cascades due to snow me...",Winter weather impacts are also possible in the central Appalachians as low-pressure systems pass through.

In [15]:
# Return sentences that likely indicate bad sentence splits
bad_sentences = df[
    # Starts with dangling symbols or units (but not valid numbers)
    df["clean sentence"].str.match(r"^(°F|\+F|F\+|[^\w\d])", na=False)
    |
    # Ends mid temperature or numeric range expression
    df["clean sentence"].str.contains(r"(°F[-+]$|\d-\s*$)", regex=True, na=False)
]

bad_sentences[["clean sentence"]]

/var/folders/78/9z0b45fx1xqbwxh8vk97lcfh0000gn/T/ipykernel_88735/2647854979.py:7: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  df["clean sentence"].str.contains(r"(°F[-+]$|\d-\s*$)", regex=True, na=False)

                                                                                                                                                                                                                                                                                        clean sentence
5205                                                                                                                                            **Weather Forecast (April 4-8, 2016)**\n\nRecord warmth expected in the western U.S., while the eastern U.S. will experience record cold and snowfall.
8228                                                                                                                                           - Widespread precipitation expected on Monday from the Northern Rockies and East Central MT, as well as isolated storms from MN/WI to the TX Panhandle.
8874                                                                                                                                    **Forecast Period (Sept 16 - Sept 20, 2017):**  \n- **Temperature:** Below average highs (10-20 degrees) across OR, northern CA, NV, and the northern Rockies.
8879   **Additional Notes:**  \n- Hurricane Jose remains offshore, with uncertainty regarding its track and influence on the eastern U.S. \n- Model discrepancies continue regarding the behavior of the mid-level trough and hurricane dynamics, affecting precipitation forecasts across the plains.
9039                                                                                                                                    - Central Rockies: Highs at least 20°F below normal early week, moderating to near normal later on.\n- West Coast/Northern Rockies: Highs 5-15°F below normal.
12946                                             - Severe weather across the Southeast, Mid-Atlantic, and Lower Mississippi Valley (April 14).\n- Flooding concerns in the Middle and Upper Mississippi Valleys, Great Lakes, and Northern Plains, with significant flooding expected in prone areas.
12947                                                                                                                                                                      - Much below normal temperatures in the Southern Rockies, Central Rockies, Southern Plains, and Central Plains on April 14.
21352                                                                                                                                                                                                                                                                             **Forecast Summary**

In [16]:
bad_sentences

,date,temp,precip,humidity,windspeed,text,clean sentence
5205,2016-04-01,71.9,0.052,67.7,21.4,"**Weather Forecast (April 4-8, 2016)**\n\nRecord warmth expected in the western U.S., while the eastern U.S. will experience record cold and snowfall. A ridge will build in the northern Rockies, leading to a milder pattern in the west, with temperatures likely 10-25 degrees above average. Conversely, a significant cold front will bring temperatures to the teens and single digits in the northeast, 10-25 degrees below average, especially on Wednesday. Snow is forecasted along the I-90/88/86 corridor, with high pressure following the system leading to colder conditions.\n\nPrecipitation is expected in the northeast on Monday and again later in the week as systems move through the Great Lakes. Late next week, an increase in rain and snow is likely due to moisture from the Atlantic. Meanwhi...","**Weather Forecast (April 4-8, 2016)**\n\nRecord warmth expected in the western U.S., while the eastern U.S. will experience record cold and snowfall."
8228,2017-06-08,65.4,0.000,63.2,12.0,"Well below average temperatures are expected in the West, with a core of 10-15 degrees below average across the West Coast and Northern Rockies. The Upper Midwest will experience a negative temperature anomaly due to a closed low system moving from CA/NV to the Northern Rockies. The Northeast will see summer-like conditions with above average temperatures, potentially reaching 10-15 degrees above normal, and possible record highs from IA/MN/WI on Sunday and major cities from DC to NYC/BOS on Monday and Tuesday. \n\nPrecipitation will be widespread: \n- Scattered showers and storms will occur from the Interior Northwest to the Upper Mississippi Valley/Great Lakes on Sunday.\n- Enhanced sea breeze convection with heavy rain along the East Central Gulf Coast. \n- Widespread precipitation ...","- Widespread precipitation expected on Monday from the Northern Rockies and East Central MT, as well as isolated storms from MN/WI to the TX Panhandle."
8874,2017-09-13,72.0,0.044,85.8,10.8,"**Forecast Period (Sept 16 - Sept 20, 2017):** \n- **Temperature:** Below average highs (10-20 degrees) across OR, northern CA, NV, and the northern Rockies. Above average temperatures across central/southern plains to Great Lakes/Northeast with highs averaging 10 degrees above normal in KS, OK, IA, MO, IL, WI, and parts of the eastern Great Lakes. Early November-like conditions in MT, WY, and ID with Saturday highs in the 40s, then moderating into Monday, before another cold wave arrives Tuesday and Wednesday.\n \n- **Precipitation:** Highest chances from the central/northern Rockies to the upper Midwest associated with a surface low. Significant QPF expected along the WA/OR coast and the Cascades, as well as in the Northern Inter-Mountain West. High elevation snow possible in the C...","**Forecast Period (Sept 16 - Sept 20, 2017):** \n- **Temperature:** Below average highs (10-20 degrees) across OR, northern CA, NV, and the northern Rockies."
8879,2017-09-13,72.0,0.044,85.8,10.8,"**Forecast Period (Sept 16 - Sept 20, 2017):** \n- **Temperature:** Below average highs (10-20 degrees) across OR, northern CA, NV, and the northern Rockies. Above average temperatures across central/southern plains to Great Lakes/Northeast with highs averaging 10 degrees above normal in KS, OK, IA, MO, IL, WI, and parts of the eastern Great Lakes. Early November-like conditions in MT, WY, and ID with Saturday highs in the 40s, then moderating into Monday, before another cold wave arrives Tuesday and Wednesday.\n \n- **Precipitation:** Highest chances from the central/northern Rockies to the upper Midwest associated with a surface low. Significant QPF expected along the WA/OR coast and the Cascades, as well as in the Northern Inter-Mountain West. High elevation snow possible in the C...","**Additional Notes:** \n- Hurricane Jose remains offshore, with uncertainty regarding its track and influence on the eastern U.S. \n- Model discrepancies continue regarding the behavior of the mid-level trough and hurricane dynamics, affecting precipitation forecasts across the plains."
9039,2017-10-06,72.7,0.000,72.7,10.1,"Guidance indicates a consistent large-scale flow with a ridge building over and south of the southern tier states and mean troughing over the west coast. Tropical cyclone Nate is expected to weaken as it makes landfall along the central Gulf Coast and accelerates northeastward. \n\nFrom Monday to Wednesday, warm temperatures are predicted in the eastern U.S. with highs 10-15°F above normal and minimum temperatures 15-20°F above normal. Cooler conditions will develop later in the week, returning to seasonal levels. Some early week precipitation in the central Rockies could be in the form of snow. \n\nIn the western states, cooling trends with highs 5-15°F below normal anticipated as an upper trough settles over the region. Precipitation will gradually increase, particularly over the Ca...","- Central Rockies: Highs at least 20°F below normal early week, moderating to near normal later on.\n- West Coast/Northern Rockies: Highs 5-15°F below normal."
12946,2019-04-11,55.6,0.000,52.8,17.6,"Heavy rainfall and flooding threats from two major spring storms are expected from the mid-lower Mississippi Valley to the Ohio Valley this weekend and into midweek. There is potential for excessive rainfall and flash flooding due to deep moisture (1.5+ standard deviations above normal) being pulled in from the Gulf of Mexico. Severe weather risks are present in the South as a potent low pressure system tracks northeast, potentially bringing snow/ice to northern New England. A trailing cold front will result in additional rains and convection across various regions, particularly affecting the West Coast on Sunday. Cyclogenesis in the Plains is likely to enhance rainfall as Gulf moisture returns, with areas previously impacted expected to see repeat heavy rain and severe weather threats...","- Severe weather across the Southeast, Mid-Atlantic, and Lower Mississippi Valley (April 14).\n- Flooding concerns in the Middle and Upper Mississippi Valleys, Great Lakes, and Northern Plains, with significant flooding expected in prone areas."
12947,2019-04-11,55.6,0.000,52.8,17.6,"Heavy rainfall and flooding threats from two major spring storms are expected from the mid-lower Mississippi Valley to the Ohio Valley this weekend and into midweek. There is potential for excessive rainfall and flash flooding due to deep moisture (1.5+ standard deviations above normal) being pulled in from the Gulf of Mexico. Severe weather risks are present in the South as a potent low pressure system tracks northeast, potentially bringing snow/ice to northern New England. A trailing cold front will result in additional rains and convection across various regions, particularly affecting the West Coast on Sunday. Cyclogenesis in the Plains is likely to enhance rainfall as Gulf moisture returns, with areas previously impacted expected to see repeat heavy rain and severe weather threats...","- Much below normal temperatures in the Southern Rockies, Central Rockies, Southern Plains, and Central Plains on April 14."
21352,2022-05-13,67.4,0.144,84.4,12.3,"**Forecast Summary** \nRecord-breaking heat is expected across the south-central U.S. next week, particularly in Texas and Louisiana, with highs 15-25°F above normal. Unseasonably hot weather will also affect the southern tier, while cooling temperatures and precipitation dominate the Pacific Northwest due to upper troughing. Showers and thunderstorms are anticipated along fronts in the East, especially on Monday, with potential heavy rainfall and localized flooding in New England. There are concerns of heavy rain across the Upper Mississippi and Tennessee Valleys midweek due to multiple weather systems. Snow levels will initially be high but are expected to decrease as the week progresses. The forecast indicates two rainfall regimes east of the Rockies with uncertainty regarding amou...",**Forecast Summary**