# Explore Datasets

In [1]:
import os
import sys

import pandas as pd

notebook_dir = os.getcwd()

sys.path.append(os.path.join(notebook_dir, '../'))

from data_processing import DataProcessing
from feature_extraction import SpacyFeatureExtraction

In [2]:
pd.set_option('max_colwidth', 800)
# pd.set_option('display.max_columns', None)
# pd.set_option('display.max_columns', 40)
# pd.set_option('display.max_rows', None)

## Load Data

In [3]:
dataset_path = os.path.join(notebook_dir, '../data/combined_datasets/july_2026_results/july_2026_results.csv')
df = DataProcessing.load_from_file(dataset_path)
df

,Base Sentence,Ground Truth,Dataset Name
0,"Sebastian, a financial analyst forecasts that the stock price at Apple will decrease in 2027 Q3.",1,synthetic
1,"On August 22, 2024, Goldman Sachs speculates that the operating cash flow at Amazon will likely increase.",1,synthetic
2,"Citigroup predicts on September 15, 2026, the S&P 500 index could climb moderately.",1,synthetic
3,"According to Morgan Stanley, the projected revenue at Alphabet Inc. should fall in Q2 2028.",1,synthetic
4,"In 2029 Q4, David envisions that the dividend yield in Microsoft could stay stable.",1,synthetic
...,...,...,...
26193,Will FFIV's market close price on 2025-01-17 be higher than its market close price on 2024-07-21?\n\nStock splits and reverse splits will be accounted for in resolving this question. Forecasts on questions about companies that have been delisted (through mergers or bankruptcy) will resolve to their final close price.,1,forecast_bench
26194,Will FFIV's market close price on 2025-07-21 be higher than its market close price on 2024-07-21?\n\nStock splits and reverse splits will be accounted for in resolving this question. Forecasts on questions about companies that have been delisted (through mergers or bankruptcy) will resolve to their final close price.,1,forecast_bench
26195,Will FFIV's market close price on 2027-07-21 be higher than its market close price on 2024-07-21?\n\nStock splits and reverse splits will be accounted for in resolving this question. Forecasts on questions about companies that have been delisted (through mergers or bankruptcy) will resolve to their final close price.,1,forecast_bench
26196,Will FFIV's market close price on 2029-07-20 be higher than its market close price on 2024-07-21?\n\nStock splits and reverse splits will be accounted for in resolving this question. Forecasts on questions about companies that have been delisted (through mergers or bankruptcy) will resolve to their final close price.,1,forecast_bench
26197,Will FFIV's market close price on 2034-07-19 be higher than its market close price on 2024-07-21?\n\nStock splits and reverse splits will be accounted for in resolving this question. Forecasts on questions about companies that have been delisted (through mergers or bankruptcy) will resolve to their final close price.,1,forecast_bench

In [4]:
filt_gt = (df['Ground Truth'] == 1)
df = df[filt_gt]
df

,Base Sentence,Ground Truth,Dataset Name
0,"Sebastian, a financial analyst forecasts that the stock price at Apple will decrease in 2027 Q3.",1,synthetic
1,"On August 22, 2024, Goldman Sachs speculates that the operating cash flow at Amazon will likely increase.",1,synthetic
2,"Citigroup predicts on September 15, 2026, the S&P 500 index could climb moderately.",1,synthetic
3,"According to Morgan Stanley, the projected revenue at Alphabet Inc. should fall in Q2 2028.",1,synthetic
4,"In 2029 Q4, David envisions that the dividend yield in Microsoft could stay stable.",1,synthetic
...,...,...,...
26193,Will FFIV's market close price on 2025-01-17 be higher than its market close price on 2024-07-21?\n\nStock splits and reverse splits will be accounted for in resolving this question. Forecasts on questions about companies that have been delisted (through mergers or bankruptcy) will resolve to their final close price.,1,forecast_bench
26194,Will FFIV's market close price on 2025-07-21 be higher than its market close price on 2024-07-21?\n\nStock splits and reverse splits will be accounted for in resolving this question. Forecasts on questions about companies that have been delisted (through mergers or bankruptcy) will resolve to their final close price.,1,forecast_bench
26195,Will FFIV's market close price on 2027-07-21 be higher than its market close price on 2024-07-21?\n\nStock splits and reverse splits will be accounted for in resolving this question. Forecasts on questions about companies that have been delisted (through mergers or bankruptcy) will resolve to their final close price.,1,forecast_bench
26196,Will FFIV's market close price on 2029-07-20 be higher than its market close price on 2024-07-21?\n\nStock splits and reverse splits will be accounted for in resolving this question. Forecasts on questions about companies that have been delisted (through mergers or bankruptcy) will resolve to their final close price.,1,forecast_bench
26197,Will FFIV's market close price on 2034-07-19 be higher than its market close price on 2024-07-21?\n\nStock splits and reverse splits will be accounted for in resolving this question. Forecasts on questions about companies that have been delisted (through mergers or bankruptcy) will resolve to their final close price.,1,forecast_bench

## Search Data using Keywords

In [5]:
import pandas as pd

ex_df = pd.DataFrame({
    'name': ['sireesha', 'priyank', 'ojaswi', 'gnanesh'],
    'subjects': ['java is good', 'networks', 'c', 'c#']
})

words = ['java', 'c']

pattern = '|'.join(words)
result = ex_df[ex_df['subjects'].str.contains(pattern, na=False)]

print(result)

       name      subjects
0  sireesha  java is good
2    ojaswi             c
3   gnanesh            c#

In [32]:
# words = ['predicts', 'will']
# words = ['predict', 'forecasts', 'expects', 'projects']
words = ['predicted', 'forecasted', 'expected', 'projected', 'anticipated']
pattern = '|'.join(words)
print(pattern)

predicted|forecasted|expected|projected|anticipated

In [33]:
filt_word = (df['Base Sentence'].str.contains(pattern, na=False) == True)
filt_word_df = df[filt_word]
filt_word_df

,Base Sentence,Ground Truth,Dataset Name
21254,"The scalability of automated solutions makes them ideal for large-scale deployments, further driving their adoption in smart city projects.As urbanization continues to accelerate, the demand for intelligent infrastructure is expected to grow, creating significant opportunities for the Lighting Control System Market.",1,news_api

In [34]:
filt_word_df.groupby(['Dataset Name']).size()

Dataset Name
news_api    1
dtype: int64

In [28]:
filt_word_df.groupby(['Dataset Name']).first()

,Base Sentence,Ground Truth
Dataset Name,,
news_api,"The scalability of automated solutions makes them ideal for large-scale deployments, further driving their adoption in smart city projects.As urbanization continues to accelerate, the demand for intelligent infrastructure is expected to grow, creating significant opportunities for the Lighting Control System Market.",1

## Extract POS

In [29]:
df = filt_word_df[filt_word_df['Dataset Name'] == 'news_api']
df

,Base Sentence,Ground Truth,Dataset Name
21254,"The scalability of automated solutions makes them ideal for large-scale deployments, further driving their adoption in smart city projects.As urbanization continues to accelerate, the demand for intelligent infrastructure is expected to grow, creating significant opportunities for the Lighting Control System Market.",1,news_api

In [30]:
sfe = SpacyFeatureExtraction(df, 'Base Sentence')
disable_components = []
pos_df = sfe.extract_pos_features(disable_components)
pos_df

==================================================
EXTRACTING POS FEATURES
==================================================

Extracting POS Features: 100%|██████████| 1/1 [00:00<00:00, 87.90doc/s]

==================================================
DONE EXTRACTING POS FEATURES
==================================================

,Sentence,Term,Lemma,POS Label,Detailed POS Label,Dependency,Shape,Is Alpha,Stop Word,Unique POS Label,...,Definite,Degree,SubCat,Animacy,Acc,Gen,Loc,Ins,Parat,Prep
0,"The scalability of automated solutions makes them ideal for large-scale deployments, further driving their adoption in smart city projects.As urbanization continues to accelerate, the demand for intelligent infrastructure is expected to grow, creating significant opportunities for the Lighting Control System Market.",The,the,DET,DT,det,Xxx,True,True,DET_1,...,[Def],,,,,,,,,
1,"The scalability of automated solutions makes them ideal for large-scale deployments, further driving their adoption in smart city projects.As urbanization continues to accelerate, the demand for intelligent infrastructure is expected to grow, creating significant opportunities for the Lighting Control System Market.",scalability,scalability,NOUN,NN,nsubj,xxxx,True,False,NOUN_1,...,,,,,,,,,,
2,"The scalability of automated solutions makes them ideal for large-scale deployments, further driving their adoption in smart city projects.As urbanization continues to accelerate, the demand for intelligent infrastructure is expected to grow, creating significant opportunities for the Lighting Control System Market.",of,of,ADP,IN,prep,xx,True,True,ADP_1,...,,,,,,,,,,
3,"The scalability of automated solutions makes them ideal for large-scale deployments, further driving their adoption in smart city projects.As urbanization continues to accelerate, the demand for intelligent infrastructure is expected to grow, creating significant opportunities for the Lighting Control System Market.",automated,automate,VERB,VBN,amod,xxxx,True,False,VERB_1,...,,,,,,,,,,
4,"The scalability of automated solutions makes them ideal for large-scale deployments, further driving their adoption in smart city projects.As urbanization continues to accelerate, the demand for intelligent infrastructure is expected to grow, creating significant opportunities for the Lighting Control System Market.",solutions,solution,NOUN,NNS,pobj,xxxx,True,False,NOUN_2,...,,,,,,,,,,
5,"The scalability of automated solutions makes them ideal for large-scale deployments, further driving their adoption in smart city projects.As urbanization continues to accelerate, the demand for intelligent infrastructure is expected to grow, creating significant opportunities for the Lighting Control System Market.",makes,make,VERB,VBZ,ROOT,xxxx,True,False,VERB_2,...,,,,,,,,,,
6,"The scalability of automated solutions makes them ideal for large-scale deployments, further driving their adoption in smart city projects.As urbanization continues to accelerate, the demand for intelligent infrastructure is expected to grow, creating significant opportunities for the Lighting Control System Market.",them,they,PRON,PRP,nsubj,xxxx,True,True,PRON_1,...,,,,,,,,,,
7,"The scalability of automated solutions makes them ideal for large-scale deployments, further driving their adoption in smart city projects.As urbanization continues to accelerate, the demand for intelligent infrastructure is expected to grow, creating significant opportunities for the Lighting Control System Market.",ideal,ideal,ADJ,JJ,ccomp,xxxx,True,False,ADJ_1,...,,[Pos],,,,,,,,
8,"The scalability of automated solutions makes them ideal for large-scale deployments, further driving their adoption in smart city projects.As urbanization continues to accelerate, the demand for intelligent infrastructure is expected to grow, creating significant opportunities for the Lighting Control System Market.",for,for,ADP,IN,prep,xxx,True,True,ADP_2,...,,,,,,,,,,
9,"The scalability of automated solutions makes them ideal for large-scale deployments, further driving their adoption in smart city projects.As urbanization continues to accelerate, the demand for intelligent infrastructure is expected to grow, creating significant opportunities for the Lighting Control System Market.",large,large,ADJ,JJ,amod,xxxx,True,False,ADJ_2,...,,[Pos],,,,,,,,
10,"The scalability of automated solutions makes them ideal for large-scale deployments, further driving their adoption in smart city projects.As urbanization continues to accelerate, the demand for intelligent infrastructure is expected to grow, creating significant opportunities for the Lighting Control System Market.",-,-,PUNCT,HYPH,punct,-,False,False,PUNCT_1,...,,,,,,,,,,
11,"The scalability of automated solutions makes them ideal for large-scale deployments, further driving their adoption in smart city projects.As urbanization continues to accelerate, the demand for intelligent infrastructure is expected to grow, creating significant opportunities for the Lighting Control System Market.",scale,scale,NOUN,NN,compound,xxxx,True,False,NOUN_3,...,,,,,,,,,,
12,"The scalability of automated solutions makes them ideal for large-scale deployments, further driving their adoption in smart city projects.As urbanization continues to accelerate, the demand for intelligent infrastructure is expected to grow, creating significant opportunities for the Lighting Control System Market.",deployments,deployment,NOUN,NNS,pobj,xxxx,True,False,NOUN_4,...,,,,,,,,,,
13,"The scalability of automated solutions makes them ideal for large-scale deployments, further driving their adoption in smart city projects.As urbanization continues to accelerate, the demand for intelligent infrastructure is expected to grow, creating significant opportunities for the Lighting Control System Market.",",",",",PUNCT,",",punct,",",False,False,PUNCT_2,...,,,,,,,,,,
14,"The scalability of automated solutions makes them ideal for large-scale deployments, further driving their adoption in smart city projects.As urbanization continues to accelerate, the demand for intelligent infrastructure is expected to grow, creating significant opportunities for the Lighting Control System Market.",further,far,ADV,RB,advmod,xxxx,True,True,ADV_1,...,,,,,,,,,,
15,"The scalability of automated solutions makes them ideal for large-scale deployments, further driving their adoption in smart city projects.As urbanization continues to accelerate, the demand for intelligent infrastructure is expected to grow, creating significant opportunities for the Lighting Control System Market.",driving,drive,VERB,VBG,advcl,xxxx,True,False,VERB_3,...,,,,,,,,,,
16,"The scalability of automated solutions makes them ideal for large-scale deployments, further driving their adoption in smart city projects.As urbanization continues to accelerate, the demand for intelligent infrastructure is expected to grow, creating significant opportunities for the Lighting Control System Market.",their,their,PRON,PRP$,poss,xxxx,True,True,PRON_2,...,,,,,,,,,,
17,"The scalability of automated solutions makes them ideal for large-scale deployments, further driving their adoption in smart city projects.As urbanization continues to accelerate, the demand for intelligent infrastructure is expected to grow, creating significant opportunities for the Lighting Control System Market.",adoption,adoption,NOUN,NN,dobj,xxxx,True,False,NOUN_5,...,,,,,,,,,,
18,"The scalability of automated solutions makes them ideal for large-scale deployments, further driving their adoption in smart city projects.As urbanization continues to accelerate, the demand for intelligent infrastructure is expected to grow, creating significant opportunities for the Lighting Control System Market.",in,in,ADP,IN,prep,xx,True,True,ADP_3,...,,,,,,,,,,
19,"The scalability of automated solutions makes them ideal for large-scale deployments, further driving their adoption in smart city projects.As urbanization continues to accelerate, the demand for intelligent infrastructure is expected to grow, creating significant opportunities for the Lighting Control System Market.",smart,smart,ADJ,JJ,amod,xxxx,True,False,ADJ_3,...,,[Pos],,,,,,,,
20,"The scalability of automated solutions makes them ideal for large-scale deployments, further driving their adoption in smart city projects.As urbanization continues to accelerate, the demand for intelligent infrastructure is expected to grow, creating significant opportunities for the Lighting Control System Market.",city,city,NOUN,NN,compound,xxxx,True,False,NOUN_6,...,,,,,,,,,,
21,"The scalability of automated solutions makes them ideal for large-scale deployments, further driving their adoption in smart city projects.As urbanization continues to accelerate, the demand for intelligent infrastructure is expected to grow, creating significant opportunities for the Lighting Control System Market.",projects,project,NOUN,NNS,pobj,xxxx,True,False,NOUN_7,...,,,,,,,,,,
22,"The scalability of automated solutions makes them ideal for large-scale deployments, further driving their adoption in smart city projects.As urbanization continues to accelerate, the demand for intelligent infrastructure is expected to grow, creating significant opportunities for the Lighting Control System Market.",.,.,PUNCT,.,punct,.,False,False,PUNCT_3,...,,,,,,,,,,
23,"The scalability of automated solutions makes them ideal for large-scale deployments, further driving their adoption in smart city projects.As urbanization continues to accelerate, the demand for intelligent infrastructure is expected to grow, creating significant opportunities for the Lighting Control System Market.",As,as,SCONJ,IN,mark,Xx,True,True,SCONJ_1,...,,,,,,,,,,
24,"The scalability of automated solutions makes them ideal for large-scale deployments, further driving their adoption in smart city projects.As urbanization continues to accelerate, the demand for intelligent infrastructure is expected to grow, creating significant opportunities for the Lighting Control System Market.",urbanization,urbanization,NOUN,NN,nsubj,xxxx,True,False,NOUN_8,...,,,,,,,,,,
25,"The scalability of automated solutions makes them ideal for large-scale deployments, further driving their adoption in smart city projects.As urbanization continues to accelerate, the demand for intelligent infrastructure is expected to grow, creating significant opportunities for the Lighting Control System Market.",continues,continue,VERB,VBZ,advcl,xxxx,True,False,VERB_4,...,,,,,,,,,,
26,"The scalability of automated solutions makes them ideal for large-scale deployments, further driving their adoption in smart city projects.As urbanization continues to accelerate, the demand for intelligent infrastructure is expected to grow, creating significant opportunities for the Lighting Control System Market.",to,to,PART,TO,aux,xx,True,True,PART_1,...,,,,,,,,,,
27,"The scalability of automated solutions makes them ideal for large-scale deployments, further driving their adoption in smart city projects.As urbanization continues to accelerate, the demand for intelligent infrastructure is expected to grow, creating significant opportunities for the Lighting Control System Market.",accelerate,accelerate,VERB,VB,xcomp,xxxx,True,False,VERB_5,...,,,,,,,,,,
28,"The scalability of automated solutions makes them ideal for large-scale deployments, further driving their adoption in smart city projects.As urbanization continues to accelerate, the demand for intelligent infrastructure is expected to grow, creating significant opportunities for the Lighting Control System Market.",",",",",PUNCT,",",punct,",",False,False,PUNCT_4,...,,,,,,,,,,
29,"The scalability of automated solutions makes them ideal for large-scale deployments, further driving their adoption in smart city projects.As urbanization continues to accelerate, the demand for intelligent infrastructure is expected to grow, creating significant opportunities for the Lighting Control System Market.",the,the,DET,DT,det,xxx,True,True,DET_2,...,[Def],,,,,,,,,
30,"The scalability of automated solutions makes them ideal for large-scale deployments, further driving their adoption in smart city projects.As urbanization continues to accelerate, the demand for intelligent infrastructure is expected to grow, creating significant opportunities for the Lighting Control System Market.",demand,demand,NOUN,NN,nsubjpass,xxxx,True,False,NOUN_9,...,,,,,,,,,,
31,"The scalability of automated solutions makes them ideal for large-scale deployments, further driving their adoption in smart city projects.As urbanization continues to accelerate, the demand for intelligent infrastructure is expected to grow, creating significant opportunities for the Lighting Control System Market.",for,for,ADP,IN,prep,xxx,True,True,ADP_4,...,,,,,,,,,,
32,"The scalability of automated solutions makes them ideal for large-scale deployments, further driving their adoption in smart city projects.As urbanization continues to accelerate, the demand for intelligent infrastructure is expected to grow, creating significant opportunities for the Lighting Control System Market.",intelligent,intelligent,ADJ,JJ,amod,xxxx,True,False,ADJ_4,...,,[Pos],,,,,,,,
33,"The scalability of automated solutions makes them ideal for large-scale deployments, further driving their adoption in smart city projects.As urbanization continues to accelerate, the demand for intelligent infrastructure is expected to grow, creating significant opportunities for the Lighting Control System Market.",infrastructure,infrastructure,NOUN,NN,pobj,xxxx,True,False,NOUN_10,...,,,,,,,,,,
34,"The scalability of automated solutions makes them ideal for large-scale deployments, further driving their adoption in smart city projects.As urbanization continues to accelerate, the demand for intelligent infrastructure is expected to grow, creating significant opportunities for the Lighting Control System Market.",is,be,AUX,VBZ,auxpass,xx,True,True,AUX_1,...,,,,,,,,,,
35,"The scalability of automated solutions makes them ideal for large-scale deployments, further driving their adoption in smart city projects.As urbanization continues to accelerate, the demand for intelligent infrastructure is expected to grow, creating significant opportunities for the Lighting Control System Market.",expected,expect,VERB,VBN,ROOT,xxxx,True,False,VERB_6,...,,,,,,,,,,
36,"The scalability of automated solutions makes them ideal for large-scale deployments, further driving their adoption in smart city projects.As urbanization continues to accelerate, the demand for intelligent infrastructure is expected to grow, creating significant opportunities for the Lighting Control System Market.",to,to,PART,TO,aux,xx,True,True,PART_2,...,,,,,,,,,,
37,"The scalability of automated solutions makes them ideal for large-scale deployments, further driving their adoption in smart city projects.As urbanization continues to accelerate, the demand for intelligent infrastructure is expected to grow, creating significant opportunities for the Lighting Control System Market.",grow,grow,VERB,VB,xcomp,xxxx,True,False,VERB_7,...,,,,,,,,,,
38,"The scalability of automated solutions makes them ideal for large-scale deployments, further driving their adoption in smart city projects.As urbanization continues to accelerate, the demand for intelligent infrastructure is expected to grow, creating significant opportunities for the Lighting Control System Market.",",",",",PUNCT,",",punct,",",False,False,PUNCT_5,...,,,,,,,,,,
39,"The scalability of automated solutions makes them ideal for large-scale deployments, further driving their adoption in smart city projects.As urbanization continues to accelerate, the demand for intelligent infrastructure is expected to grow, creating significant opportunities for the Lighting Control System Market.",creating,create,VERB,VBG,advcl,xxxx,True,False,VERB_8,...,,,,,,,,,,
40,"The scalability of automated solutions makes them ideal for large-scale deployments, further driving their adoption in smart city projects.As urbanization continues to accelerate, the demand for intelligent infrastructure is expected to grow, creating significant opportunities for the Lighting Control System Market.",significant,significant,ADJ,JJ,amod,xxxx,True,False,ADJ_5,...,,[Pos],,,,,,,,
41,"The scalability of automated solutions makes them ideal for large-scale deployments, further driving their adoption in smart city projects.As urbanization continues to accelerate, the demand for intelligent infrastructure is expected to grow, creating significant opportunities for the Lighting Control System Market.",opportunities,opportunity,NOUN,NNS,dobj,xxxx,True,False,NOUN_11,...,,,,,,,,,,
42,"The scalability of automated solutions makes them ideal for large-scale deployments, further driving their adoption in smart city projects.As urbanization continues to accelerate, the demand for intelligent infrastructure is expected to grow, creating significant opportunities for the Lighting Control System Market.",for,for,ADP,IN,prep,xxx,True,True,ADP_5,...,,,,,,,,,,
43,"The scalability of automated solutions makes them ideal for large-scale deployments, further driving their adoption in smart city projects.As urbanization continues to accelerate, the demand for intelligent infrastructure is expected to grow, creating significant opportunities for the Lighting Control System Market.",the,the,DET,DT,det,xxx,True,True,DET_3,...,[Def],,,,,,,,,
44,"The scalability of automated solutions makes them ideal for large-scale deployments, further driving their adoption in smart city projects.As urbanization continues to accelerate, the demand for intelligent infrastructure is expected to grow, creating significant opportunities for the Lighting Control System Market.",Lighting,Lighting,PROPN,NNP,compound,Xxxxx,True,False,PROPN_1,...,,,,,,,,,,
45,"The scalability of automated solutions makes them ideal for large-scale deployments, further driving their adoption in smart city projects.As urbanization continues to accelerate, the demand for intelligent infrastructure is expected to grow, creating significant opportunities for the Lighting Control System Market.",Control,Control,PROPN,NNP,compound,Xxxxx,True,False,PROPN_2,...,,,,,,,,,,
46,"The scalability of automated solutions makes them ideal for large-scale deployments, further driving their adoption in smart city projects.As urbanization continues to accelerate, the demand for intelligent infrastructure is expected to grow, creating significant opportunities for the Lighting Control System Market.",System,System,PROPN,NNP,compound,Xxxxx,True,False,PROPN_3,...,,,,,,,,,,
47,"The scalability of automated solutions makes them ideal for large-scale deployments, further driving their adoption in smart city projects.As urbanization continues to accelerate, the demand for intelligent infrastructure is expected to grow, creating significant opportunities for the Lighting Control System Market.",Market,Market,PROPN,NNP,pobj,Xxxxx,True,False,PROPN_4,...,,,,,,,,,,
48,"The scalability of automated solutions makes them ideal for large-scale deployments, further driving their adoption in smart city projects.As urbanization continues to accelerate, the demand for intelligent infrastructure is expected to grow, creating significant opportunities for the Lighting Control System Market.",.,.,PUNCT,.,punct,.,False,False,PUNCT_6,...,,,,,,,,,,
49,,,,,,,,False,,,...,,,,,,,,,,

In [31]:
filt_col = (pos_df['POS Label'] == 'VERB') == True
pos_df[filt_col]

,Sentence,Term,Lemma,POS Label,Detailed POS Label,Dependency,Shape,Is Alpha,Stop Word,Unique POS Label,...,Definite,Degree,SubCat,Animacy,Acc,Gen,Loc,Ins,Parat,Prep
3,"The scalability of automated solutions makes them ideal for large-scale deployments, further driving their adoption in smart city projects.As urbanization continues to accelerate, the demand for intelligent infrastructure is expected to grow, creating significant opportunities for the Lighting Control System Market.",automated,automate,VERB,VBN,amod,xxxx,True,False,VERB_1,...,,,,,,,,,,
5,"The scalability of automated solutions makes them ideal for large-scale deployments, further driving their adoption in smart city projects.As urbanization continues to accelerate, the demand for intelligent infrastructure is expected to grow, creating significant opportunities for the Lighting Control System Market.",makes,make,VERB,VBZ,ROOT,xxxx,True,False,VERB_2,...,,,,,,,,,,
15,"The scalability of automated solutions makes them ideal for large-scale deployments, further driving their adoption in smart city projects.As urbanization continues to accelerate, the demand for intelligent infrastructure is expected to grow, creating significant opportunities for the Lighting Control System Market.",driving,drive,VERB,VBG,advcl,xxxx,True,False,VERB_3,...,,,,,,,,,,
25,"The scalability of automated solutions makes them ideal for large-scale deployments, further driving their adoption in smart city projects.As urbanization continues to accelerate, the demand for intelligent infrastructure is expected to grow, creating significant opportunities for the Lighting Control System Market.",continues,continue,VERB,VBZ,advcl,xxxx,True,False,VERB_4,...,,,,,,,,,,
27,"The scalability of automated solutions makes them ideal for large-scale deployments, further driving their adoption in smart city projects.As urbanization continues to accelerate, the demand for intelligent infrastructure is expected to grow, creating significant opportunities for the Lighting Control System Market.",accelerate,accelerate,VERB,VB,xcomp,xxxx,True,False,VERB_5,...,,,,,,,,,,
35,"The scalability of automated solutions makes them ideal for large-scale deployments, further driving their adoption in smart city projects.As urbanization continues to accelerate, the demand for intelligent infrastructure is expected to grow, creating significant opportunities for the Lighting Control System Market.",expected,expect,VERB,VBN,ROOT,xxxx,True,False,VERB_6,...,,,,,,,,,,
37,"The scalability of automated solutions makes them ideal for large-scale deployments, further driving their adoption in smart city projects.As urbanization continues to accelerate, the demand for intelligent infrastructure is expected to grow, creating significant opportunities for the Lighting Control System Market.",grow,grow,VERB,VB,xcomp,xxxx,True,False,VERB_7,...,,,,,,,,,,
39,"The scalability of automated solutions makes them ideal for large-scale deployments, further driving their adoption in smart city projects.As urbanization continues to accelerate, the demand for intelligent infrastructure is expected to grow, creating significant opportunities for the Lighting Control System Market.",creating,create,VERB,VBG,advcl,xxxx,True,False,VERB_8,...,,,,,,,,,,