# Climate Forecasts

1. DATASETS: [Hugging Face: Howard Tsai | All](https://huggingface.co/Howard881010)
2. DATASETS: [Hugging Face: Howard Tsai | Climate-1 Day](https://huggingface.co/datasets/Howard881010/climate-1day)
3. REPO: [Multimodal_Forecasting](https://github.com/Rose-STL-Lab/Multimodal_Forecasting/tree/main)
    - Get data from here.

In [1]:
import os, sys

import pandas as pd

# Get the current working directory of the notebook
notebook_dir = os.getcwd()
# Add the parent directory to the system path
sys.path.append(os.path.join(notebook_dir, '../'))

from data_processing import DataProcessing
from feature_extraction import SpacyFeatureExtraction

In [2]:
pd.set_option('max_colwidth', 800)

In [3]:
base_data_path = DataProcessing.load_base_data_path(notebook_dir)
# climate_dataset = os.path.join(base_data_path, 'others/', 'paper_mf/paper_mf_repo/data/climate/climate_2014_2023_final.csv')
# climate_dataset = os.path.join(base_data_path, 'others/', 'paper_mf/paper_mf_repo/data/climate/climate_2014_2023_final.csv')
climate_dataset = os.path.join(base_data_path, 'multimodal_forecast/climate_forecasts/climate_2014_2023_final.csv')

In [4]:
df = DataProcessing.load_from_file(climate_dataset)
df

,date,temp,precip,humidity,windspeed,text
0,2014-01-01,37.9,0.000,57.4,10.0,"Arctic air is expected to invade the upper Midwest, Great Lakes, Ohio Valley, and Northeast, bringing some of the coldest temperatures in recent memory. Significant cold outbreaks on January 3-4 and 5-8 could result in temperatures 20-30 degrees Fahrenheit below normal. Lows in New England may reach -10s to -20s, and areas in eastern Montana, Minnesota, and Wisconsin may experience lows at or below -20F. Colder locations could drop to -30s or -40s Fahrenheit. Moderate upslope snow is anticipated across east-facing slopes from Montana to Northeast Wyoming. The coldest day is projected around January 8, with temperatures below freezing in a large section of the northern United States, potentially marking the coldest air masses since 1993/1994.\n\nPrecipitation is expected from a frontal ..."
1,2014-01-02,35.9,0.161,82.0,11.3,"Frigid air will sweep into the Midwest, Great Lakes, Ohio Valley, Northeast, and Mid-Atlantic early next week. A deep vortex will lead to significant temperature drops of -10 to -20 degrees across much of the central and eastern U.S., with the Ohio Valley potentially seeing temperatures nearly 40 degrees below normal by Monday. Heavy snow is anticipated northwest of a surface low tracking from the Lower Mississippi Valley to Interior New England, accompanied by strong winds, particularly across the Great Lakes. A strong Arctic front will move across the Appalachians on Sunday. By mid-week, temperatures should begin to moderate in the eastern half of the nation. Increasing moisture will bring rounds of precipitation to the Pacific Northwest, Intermountain West, and Great Basin as initia..."
2,2014-01-03,22.4,0.015,54.1,30.5,"Another arctic plunge is expected for the northeast quarter of the US Monday and Tuesday, leading to temperatures 20 to 40 degrees Fahrenheit below normal. A deep upper-level system over eastern Canada will influence this frigid air, while a fresh north Pacific flow will bring cooler and unsettled weather to the Great Lakes and northeast. Light to moderate precipitation is forecasted across the west, with potential localized enhancement along the coast. As the week progresses, precipitation is expected to increase from the southern plains into the Ohio and Tennessee valleys, with rain in the south transitioning to snow/mix further north. The forecast maintains good continuity despite some discrepancies between models regarding the impacts of cold advection associated with the arctic in..."
3,2014-01-04,25.4,0.000,52.6,13.3,"20°F-40°F below normal temperatures are expected in the northeastern quarter of the U.S. for January 7-11, 2014, with Indiana, Ohio, and western Pennsylvania experiencing temperatures 20°F+ below normal. An arctic blast will affect these regions, while the southeast and mid-Atlantic areas will also experience lower temperatures. The forecast incorporates a blend of GFS and GEFS solutions, with a notable phase of energy in the northern stream beyond day 4."
4,2014-01-05,37.1,0.041,78.7,11.0,"Temperatures are expected to approach normal values, with possibilities of being above normal. A progressive weather pattern will dominate the lower 48 states. Significant precipitation and strong winds are anticipated for the Pacific Northwest due to cyclogenesis off the Oregon/Washington coast. In the Midwest and Plains, a system originating from the South Central Rockies will bring rain through the Ohio Valley, influenced by a surface ridge in the Northeast and Mid-Atlantic. Mid-level warm advection will contribute to this precipitation. The GFS model shows discrepancies in predicted conditions in the Mid-Missouri Valley, while Gulf of Mexico moisture is expected to affect the Southern Plains and Lower-to-Mid Missouri Valley. A cutoff low over the Rio Grande Valley will also enhance..."
...,...,...,...,...,...,...
3617,2023-11-27,43.0,0.004,62.0,20.4,"Moderate to heavy rainfall is expected from Thursday, impacting the South, Southeast, and Mid-Mississippi Valley, particularly the eastern Texas Gulf Coast and western Louisiana where flash flooding is a concern. An upper-level shortwave will move from the Southwest to the Northeast this weekend, bringing unsettled weather. The Gulf Coast and Southeast will experience potentially heavy rainfall, with a marginal risk of excessive rainfall. The interior West will remain cooler than normal under reinforced troughing, while daytime highs in the Northern Plains, Midwest, and East could trend 5-10 degrees above average by the weekend. Precipitation will increase in the West, primarily along the Washington/Oregon coast and Cascades, with lighter amounts inland. The Western U.S. may return to ..."
3618,2023-11-28,35.7,0.001,42.2,25.0,"Wet pattern expected for the Northwest, with heavy snow threats inland from the Cascades and north-central Intermountain West/Rockies. From December 1 to December 5, 2023, widespread moderate to heavy rainfall is anticipated, particularly in the Gulf Coast and Southeast, with a marginal risk of excessive rainfall due to anomalous moisture and instability. High uncertainty in precipitation forecasts, especially across the east-central U.S. Precipitation is expected to increase in the West starting Thursday, leading to heaviest precipitation on the Washington/Oregon coast and Cascades from Sunday into Monday, along with accumulating snow in higher elevations. Stronger cyclogenesis may lead to larger-scale precipitation next week, impacting the Northeast as well."
3619,2023-11-29,32.9,0.000,41.8,10.1,"Multi-day wet pattern expected for the Northwest, with heavy snow threats from the Cascades to the north-central Intermountain West/Rockies. Active weather pattern continues through the weekend into next week, with systems moving from the interior West to the East Coast Saturday-Monday and ridging developing behind. An Atmospheric River may impact the West Coast this weekend, bringing ongoing precipitation and potential excessive rainfall in far northwest CA/southwest OR. Expect heavy snows and gusty winds in higher elevations of the Cascades and northern Sierras. Rainfall threat increases along the Oregon coast and western slopes of the Cascades, with another system bringing rain/mountain snow primarily to Washington state early next week. Moderate to heavy rainfall is likely for the ..."
3620,2023-11-30,42.1,0.000,51.4,10.5,"Heavy rain and inland heavy snow threats are expected in the Northwest due to a series of atmospheric rivers, with heavy snow threats also affecting the Northeast. An active weather pattern will bring heavy precipitation mainly across the Northwest and Northeast. In Washington and Oregon, heavy rainfall is anticipated, while the northern Intermountain West and Rockies could see significant snowfall. \n\nTemperatures in the Northern and Central Plains will be well above normal, reaching 15 to 25 degrees above average by Wednesday and Thursday. A strong ridge building over the West will influence these temperatures. Precipitation from atmospheric rivers will continue into next week, but with uncertainty in timing and volume.\n\nCoastal areas may experience modest rainfall, while the risk..."
3621,2023-12-01,45.6,0.123,73.4,10.7,"Heavy rain is expected in the Pacific Northwest due to multiple atmospheric river events from December 4 to December 8, 2023, possibly leading to flooding and rising river levels. Well above average temperatures, potentially 20-30 degrees higher than early December averages, are forecast for the Intermountain West and Plains, with record highs possible on Wednesday and Thursday. Snow showers may accompany a departing storm system in the Upper Midwest transitioning toward the Ohio Valley. A broad upper trough will bring active weather in the eastern U.S., with near seasonal temperatures expected, while a zonal flow pattern is anticipated by the end of the week. In the Northwest, 3-6 inch rainfall totals are likely, with a slight risk of flooding especially in the Cascades due to snow me..."

In [5]:
df['text'][0] = "Arctic air is expected to invade the upper Midwest, Great Lakes, Ohio Valley, and Northeast, bringing some of the coldest temperatures in recent memory. Significant cold outbreaks on January 3-4 and 5-8 could result in temperatures 20-30 degrees Fahrenheit below normal Lows in New England may reach -10s to -20s, and areas in eastern Montana, Minnesota, and Wisconsin may experience lows at or below -20F? Colder locations could drop to -30s or -40s Fahrenheit?"

df

/var/folders/78/9z0b45fx1xqbwxh8vk97lcfh0000gn/T/ipykernel_76613/329919925.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['text'][0] = "Arctic air is expected to invade the upper Midwest, Great Lakes, Ohio Valley, and Northeast, bringing some of the coldest temperatures in recent memory. Significant cold outbreaks on January 3-4 and 5-8 could result in temperatures 20-30 degrees Fahrenheit below normal Lows in New England may reach -10s to -20s, and areas in eastern Montana, Minnesota, and Wisconsin may experience lows at or below -20F? Colder locations could drop to -30s or -40s Fahrenheit?"
/var/folders/78/9z0b45fx1xqbwxh8vk97lcfh0000gn/T/ipykernel_76613/329919925.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['text'][0] = "Arctic air is expected to invade the upper Midwest, Great Lakes, Ohio Valley, and Northeast, bringing some of the coldest temperatures in recent memory. Significant cold outbreaks on January 3-4 and 5-8 could result in temperatures 20-30 degrees Fahrenheit below normal Lows in New England may reach -10s to -20s, and areas in eastern Montana, Minnesota, and Wisconsin may experience lows at or below -20F? Colder locations could drop to -30s or -40s Fahrenheit?"

,date,temp,precip,humidity,windspeed,text
0,2014-01-01,37.9,0.000,57.4,10.0,"Arctic air is expected to invade the upper Midwest, Great Lakes, Ohio Valley, and Northeast, bringing some of the coldest temperatures in recent memory. Significant cold outbreaks on January 3-4 and 5-8 could result in temperatures 20-30 degrees Fahrenheit below normal Lows in New England may reach -10s to -20s, and areas in eastern Montana, Minnesota, and Wisconsin may experience lows at or below -20F? Colder locations could drop to -30s or -40s Fahrenheit?"
1,2014-01-02,35.9,0.161,82.0,11.3,"Frigid air will sweep into the Midwest, Great Lakes, Ohio Valley, Northeast, and Mid-Atlantic early next week. A deep vortex will lead to significant temperature drops of -10 to -20 degrees across much of the central and eastern U.S., with the Ohio Valley potentially seeing temperatures nearly 40 degrees below normal by Monday. Heavy snow is anticipated northwest of a surface low tracking from the Lower Mississippi Valley to Interior New England, accompanied by strong winds, particularly across the Great Lakes. A strong Arctic front will move across the Appalachians on Sunday. By mid-week, temperatures should begin to moderate in the eastern half of the nation. Increasing moisture will bring rounds of precipitation to the Pacific Northwest, Intermountain West, and Great Basin as initia..."
2,2014-01-03,22.4,0.015,54.1,30.5,"Another arctic plunge is expected for the northeast quarter of the US Monday and Tuesday, leading to temperatures 20 to 40 degrees Fahrenheit below normal. A deep upper-level system over eastern Canada will influence this frigid air, while a fresh north Pacific flow will bring cooler and unsettled weather to the Great Lakes and northeast. Light to moderate precipitation is forecasted across the west, with potential localized enhancement along the coast. As the week progresses, precipitation is expected to increase from the southern plains into the Ohio and Tennessee valleys, with rain in the south transitioning to snow/mix further north. The forecast maintains good continuity despite some discrepancies between models regarding the impacts of cold advection associated with the arctic in..."
3,2014-01-04,25.4,0.000,52.6,13.3,"20°F-40°F below normal temperatures are expected in the northeastern quarter of the U.S. for January 7-11, 2014, with Indiana, Ohio, and western Pennsylvania experiencing temperatures 20°F+ below normal. An arctic blast will affect these regions, while the southeast and mid-Atlantic areas will also experience lower temperatures. The forecast incorporates a blend of GFS and GEFS solutions, with a notable phase of energy in the northern stream beyond day 4."
4,2014-01-05,37.1,0.041,78.7,11.0,"Temperatures are expected to approach normal values, with possibilities of being above normal. A progressive weather pattern will dominate the lower 48 states. Significant precipitation and strong winds are anticipated for the Pacific Northwest due to cyclogenesis off the Oregon/Washington coast. In the Midwest and Plains, a system originating from the South Central Rockies will bring rain through the Ohio Valley, influenced by a surface ridge in the Northeast and Mid-Atlantic. Mid-level warm advection will contribute to this precipitation. The GFS model shows discrepancies in predicted conditions in the Mid-Missouri Valley, while Gulf of Mexico moisture is expected to affect the Southern Plains and Lower-to-Mid Missouri Valley. A cutoff low over the Rio Grande Valley will also enhance..."
...,...,...,...,...,...,...
3617,2023-11-27,43.0,0.004,62.0,20.4,"Moderate to heavy rainfall is expected from Thursday, impacting the South, Southeast, and Mid-Mississippi Valley, particularly the eastern Texas Gulf Coast and western Louisiana where flash flooding is a concern. An upper-level shortwave will move from the Southwest to the Northeast this weekend, bringing unsettled weather. The Gulf Coast and Southeast will experience potentially heavy rainfall, with a marginal risk of excessive rainfall. The interior West will remain cooler than normal under reinforced troughing, while daytime highs in the Northern Plains, Midwest, and East could trend 5-10 degrees above average by the weekend. Precipitation will increase in the West, primarily along the Washington/Oregon coast and Cascades, with lighter amounts inland. The Western U.S. may return to ..."
3618,2023-11-28,35.7,0.001,42.2,25.0,"Wet pattern expected for the Northwest, with heavy snow threats inland from the Cascades and north-central Intermountain West/Rockies. From December 1 to December 5, 2023, widespread moderate to heavy rainfall is anticipated, particularly in the Gulf Coast and Southeast, with a marginal risk of excessive rainfall due to anomalous moisture and instability. High uncertainty in precipitation forecasts, especially across the east-central U.S. Precipitation is expected to increase in the West starting Thursday, leading to heaviest precipitation on the Washington/Oregon coast and Cascades from Sunday into Monday, along with accumulating snow in higher elevations. Stronger cyclogenesis may lead to larger-scale precipitation next week, impacting the Northeast as well."
3619,2023-11-29,32.9,0.000,41.8,10.1,"Multi-day wet pattern expected for the Northwest, with heavy snow threats from the Cascades to the north-central Intermountain West/Rockies. Active weather pattern continues through the weekend into next week, with systems moving from the interior West to the East Coast Saturday-Monday and ridging developing behind. An Atmospheric River may impact the West Coast this weekend, bringing ongoing precipitation and potential excessive rainfall in far northwest CA/southwest OR. Expect heavy snows and gusty winds in higher elevations of the Cascades and northern Sierras. Rainfall threat increases along the Oregon coast and western slopes of the Cascades, with another system bringing rain/mountain snow primarily to Washington state early next week. Moderate to heavy rainfall is likely for the ..."
3620,2023-11-30,42.1,0.000,51.4,10.5,"Heavy rain and inland heavy snow threats are expected in the Northwest due to a series of atmospheric rivers, with heavy snow threats also affecting the Northeast. An active weather pattern will bring heavy precipitation mainly across the Northwest and Northeast. In Washington and Oregon, heavy rainfall is anticipated, while the northern Intermountain West and Rockies could see significant snowfall. \n\nTemperatures in the Northern and Central Plains will be well above normal, reaching 15 to 25 degrees above average by Wednesday and Thursday. A strong ridge building over the West will influence these temperatures. Precipitation from atmospheric rivers will continue into next week, but with uncertainty in timing and volume.\n\nCoastal areas may experience modest rainfall, while the risk..."
3621,2023-12-01,45.6,0.123,73.4,10.7,"Heavy rain is expected in the Pacific Northwest due to multiple atmospheric river events from December 4 to December 8, 2023, possibly leading to flooding and rising river levels. Well above average temperatures, potentially 20-30 degrees higher than early December averages, are forecast for the Intermountain West and Plains, with record highs possible on Wednesday and Thursday. Snow showers may accompany a departing storm system in the Upper Midwest transitioning toward the Ohio Valley. A broad upper trough will bring active weather in the eastern U.S., with near seasonal temperatures expected, while a zonal flow pattern is anticipated by the end of the week. In the Northwest, 3-6 inch rainfall totals are likely, with a slight risk of flooding especially in the Cascades due to snow me..."

In [6]:
sfe = SpacyFeatureExtraction(df, 'text')
sfe

In [7]:
# df = sfe.split_into_sentences(sentence_col_name='sentence')
# df

In [8]:
df['label'] = 1
df

,date,temp,precip,humidity,windspeed,text,label
0,2014-01-01,37.9,0.000,57.4,10.0,"Arctic air is expected to invade the upper Midwest, Great Lakes, Ohio Valley, and Northeast, bringing some of the coldest temperatures in recent memory. Significant cold outbreaks on January 3-4 and 5-8 could result in temperatures 20-30 degrees Fahrenheit below normal Lows in New England may reach -10s to -20s, and areas in eastern Montana, Minnesota, and Wisconsin may experience lows at or below -20F? Colder locations could drop to -30s or -40s Fahrenheit?",1
1,2014-01-02,35.9,0.161,82.0,11.3,"Frigid air will sweep into the Midwest, Great Lakes, Ohio Valley, Northeast, and Mid-Atlantic early next week. A deep vortex will lead to significant temperature drops of -10 to -20 degrees across much of the central and eastern U.S., with the Ohio Valley potentially seeing temperatures nearly 40 degrees below normal by Monday. Heavy snow is anticipated northwest of a surface low tracking from the Lower Mississippi Valley to Interior New England, accompanied by strong winds, particularly across the Great Lakes. A strong Arctic front will move across the Appalachians on Sunday. By mid-week, temperatures should begin to moderate in the eastern half of the nation. Increasing moisture will bring rounds of precipitation to the Pacific Northwest, Intermountain West, and Great Basin as initia...",1
2,2014-01-03,22.4,0.015,54.1,30.5,"Another arctic plunge is expected for the northeast quarter of the US Monday and Tuesday, leading to temperatures 20 to 40 degrees Fahrenheit below normal. A deep upper-level system over eastern Canada will influence this frigid air, while a fresh north Pacific flow will bring cooler and unsettled weather to the Great Lakes and northeast. Light to moderate precipitation is forecasted across the west, with potential localized enhancement along the coast. As the week progresses, precipitation is expected to increase from the southern plains into the Ohio and Tennessee valleys, with rain in the south transitioning to snow/mix further north. The forecast maintains good continuity despite some discrepancies between models regarding the impacts of cold advection associated with the arctic in...",1
3,2014-01-04,25.4,0.000,52.6,13.3,"20°F-40°F below normal temperatures are expected in the northeastern quarter of the U.S. for January 7-11, 2014, with Indiana, Ohio, and western Pennsylvania experiencing temperatures 20°F+ below normal. An arctic blast will affect these regions, while the southeast and mid-Atlantic areas will also experience lower temperatures. The forecast incorporates a blend of GFS and GEFS solutions, with a notable phase of energy in the northern stream beyond day 4.",1
4,2014-01-05,37.1,0.041,78.7,11.0,"Temperatures are expected to approach normal values, with possibilities of being above normal. A progressive weather pattern will dominate the lower 48 states. Significant precipitation and strong winds are anticipated for the Pacific Northwest due to cyclogenesis off the Oregon/Washington coast. In the Midwest and Plains, a system originating from the South Central Rockies will bring rain through the Ohio Valley, influenced by a surface ridge in the Northeast and Mid-Atlantic. Mid-level warm advection will contribute to this precipitation. The GFS model shows discrepancies in predicted conditions in the Mid-Missouri Valley, while Gulf of Mexico moisture is expected to affect the Southern Plains and Lower-to-Mid Missouri Valley. A cutoff low over the Rio Grande Valley will also enhance...",1
...,...,...,...,...,...,...,...
3617,2023-11-27,43.0,0.004,62.0,20.4,"Moderate to heavy rainfall is expected from Thursday, impacting the South, Southeast, and Mid-Mississippi Valley, particularly the eastern Texas Gulf Coast and western Louisiana where flash flooding is a concern. An upper-level shortwave will move from the Southwest to the Northeast this weekend, bringing unsettled weather. The Gulf Coast and Southeast will experience potentially heavy rainfall, with a marginal risk of excessive rainfall. The interior West will remain cooler than normal under reinforced troughing, while daytime highs in the Northern Plains, Midwest, and East could trend 5-10 degrees above average by the weekend. Precipitation will increase in the West, primarily along the Washington/Oregon coast and Cascades, with lighter amounts inland. The Western U.S. may return to ...",1
3618,2023-11-28,35.7,0.001,42.2,25.0,"Wet pattern expected for the Northwest, with heavy snow threats inland from the Cascades and north-central Intermountain West/Rockies. From December 1 to December 5, 2023, widespread moderate to heavy rainfall is anticipated, particularly in the Gulf Coast and Southeast, with a marginal risk of excessive rainfall due to anomalous moisture and instability. High uncertainty in precipitation forecasts, especially across the east-central U.S. Precipitation is expected to increase in the West starting Thursday, leading to heaviest precipitation on the Washington/Oregon coast and Cascades from Sunday into Monday, along with accumulating snow in higher elevations. Stronger cyclogenesis may lead to larger-scale precipitation next week, impacting the Northeast as well.",1
3619,2023-11-29,32.9,0.000,41.8,10.1,"Multi-day wet pattern expected for the Northwest, with heavy snow threats from the Cascades to the north-central Intermountain West/Rockies. Active weather pattern continues through the weekend into next week, with systems moving from the interior West to the East Coast Saturday-Monday and ridging developing behind. An Atmospheric River may impact the West Coast this weekend, bringing ongoing precipitation and potential excessive rainfall in far northwest CA/southwest OR. Expect heavy snows and gusty winds in higher elevations of the Cascades and northern Sierras. Rainfall threat increases along the Oregon coast and western slopes of the Cascades, with another system bringing rain/mountain snow primarily to Washington state early next week. Moderate to heavy rainfall is likely for the ...",1
3620,2023-11-30,42.1,0.000,51.4,10.5,"Heavy rain and inland heavy snow threats are expected in the Northwest due to a series of atmospheric rivers, with heavy snow threats also affecting the Northeast. An active weather pattern will bring heavy precipitation mainly across the Northwest and Northeast. In Washington and Oregon, heavy rainfall is anticipated, while the northern Intermountain West and Rockies could see significant snowfall. \n\nTemperatures in the Northern and Central Plains will be well above normal, reaching 15 to 25 degrees above average by Wednesday and Thursday. A strong ridge building over the West will influence these temperatures. Precipitation from atmospheric rivers will continue into next week, but with uncertainty in timing and volume.\n\nCoastal areas may experience modest rainfall, while the risk...",1
3621,2023-12-01,45.6,0.123,73.4,10.7,"Heavy rain is expected in the Pacific Northwest due to multiple atmospheric river events from December 4 to December 8, 2023, possibly leading to flooding and rising river levels. Well above average temperatures, potentially 20-30 degrees higher than early December averages, are forecast for the Intermountain West and Plains, with record highs possible on Wednesday and Thursday. Snow showers may accompany a departing storm system in the Upper Midwest transitioning toward the Ohio Valley. A broad upper trough will bring active weather in the eastern U.S., with near seasonal temperatures expected, while a zonal flow pattern is anticipated by the end of the week. In the Northwest, 3-6 inch rainfall totals are likely, with a slight risk of flooding especially in the Cascades due to snow me...",1

In [9]:
save_path = os.path.join(base_data_path, 'multimodal_forecast', 'climate_forecasts')
DataProcessing.save_to_file(df, save_path, 'climate_forecasts', save_file_type='.csv')

Using file number: 4
Saving CSV file to: /Users/detraviousjamaribrinkley/Documents/Development/research_labs/uf_ds/predictions/notebook_experiments/../data/multimodal_forecast/climate_forecasts/climate_forecasts-v4.csv

> NEED TO DROP BAD SENTENCES, THEN RESAVE

In [10]:
# DataProcessing.load_mf_climate_dataset(notebook_dir)

## Check bad sentences

In [11]:
df[
    df["text"].str.contains(r"°F", regex=True, na=False)
][["text"]].head(10)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               text
3                                                                                                                                                                                                                                                                                                                                                       20°F-40°F below normal temperatures are expected in the northeastern quarter of the U.S. for January 7-11, 2014, with Indiana, Ohio, and western Pennsylvania experiencing temperatures 20°F+ below normal. An arctic blast will affect these regions, while the southeast and mid-Atlantic areas will also experience lower temperatures. The forecast incorporates a blend of GFS and GEFS solutions, with a notable phase of energy in the northern stream beyond day 4.
9                                                                                                                            Florida will cool off from Wednesday into Friday, with temperatures dropping approximately 6°F below normal. Most of the country will experience temperatures around 15°F above normal, though the northern tier will see a return to milder conditions due to modified Pacific air. Heavy rainfall is expected across northern Florida into the Southeast and possibly the Mid-Atlantic on Monday and Tuesday, with snow anticipated across the Great Lakes during the same period. The Pacific Northwest will dry out under an amplified ridge, while the region east of the Rockies remains impacted by a strong polar vortex and shortwave disturbances, leading to varied precipitation patterns.
10  Models indicate a warm and dry pattern in the western U.S. due to a ridge, with daytime highs in CA, NV, and OR potentially 15-20°F above normal, and 20-30°F above normal in the northern plains on Wednesday. The central plains may see highs 10-20°F above normal Wednesday to Thursday. A modest amount of moisture may reach the Pacific Northwest by Friday night. Minimum temperatures near freezing are expected around the central Gulf Coast by next Saturday, with no significant drops below normal (10-15°F below normal max). Precipitation includes a departing system on Tuesday bringing snow and potential rain/mix in the Midwest. A deep system is forecast to reach Lake Superior by Thursday, sparking another area of snow in the Great Lakes, with possible lake-effect activity thereafter, though...
11  The medium-range forecast indicates a large ridge over the West Coast and a trough over Eastern North America, with some uncertainty regarding features within the trough and energy approaching the West Coast by Saturday. Expect varied impacts in the East from shortwave energy by Thursday, affecting surface conditions along and offshore the East Coast. A weather system will move into the Upper Great Lakes, likely forming a transient surface wave in the Western Atlantic that is expected to weaken. Precipitation will be below average across the lower 48, with light to moderate snow in the Northern Plains, Great Lakes, and Northeast. Above-normal temperatures are expected in the West, with anomalies reaching +15-20°F in some areas. Light precipitation is possible on the West Coast, particu...
16  The medium range forecast from January 20 to January 24, 2014, will feature strong ridging over western Canada and longwave troughing in the eastern U.S. Above-normal high temperatures are expected west of the continental divide, while central, eastern, and southeastern states will see below-normal temperatures (10-20°F below climatological averages) due to an Arctic push. There is less potential for eastern coastal storms than previously indicated. Temperatures in parts of the southeast and southern plains are projected to rebound modestly by the end of the week. Light wintry precipitation may occur along a storm track influenced by mid-level warm advection, but overall precipitation amounts will be minimal, rarely exceeding 1/10th of an inch. Humidity levels will be low, with precipi...
17  A highly-amplified ridge/trough pattern will persist, with embedded shortwaves affecting the weather. A blend of ECMWF and GFS models suggests a possible quick intrusion of northern stream energy into Minnesota late Thursday. A weak closed low will approach the CA/OR border late Wednesday into early Thursday under the northern ridge. A cold blast of Arctic air will move through the Upper Midwest and Great Lakes, with temperatures forecasted to be 10-20°F below climatological average in the eastern half of the CONUS. Higher probabilities of wintry precipitation are expected in the Great Lakes, Appalachians, and Northeast, with light mid-level warm advection processes limited to storm tracks from the Northern Plains through the Midwest to the Ohio Valley. Offshore cyclogenesis is favored...
23  Cold conditions are expected across eastern North America due to a persistent trough. A cold front will move through the east coast on Monday, bringing colder high pressure to the southeast over the following days. Precipitation is likely along the cold front, particularly on Day 3, with increased potential for wintry precipitation in the Southeast and Southern Mid-Atlantic as a surface low develops around Wednesday/Thursday. Many areas may experience temperatures 15-30°F below normal, with records possibly being broken. In the western U.S., temperatures are forecasted to be 5-20°F above normal through Wednesday, decreasing as the week progresses. Lake effect snow is expected downwind from the Great Lakes, and light moisture may return to the western Gulf Coast and Lower Mississippi Va...
24  Models indicate a transition from a highly amplified weather pattern to lower heights in the West and rising heights in the East, with a ridge forming over the Eastern Pacific near 140W by late next week. Extremely cold temperatures are expected in the Eastern CONUS on Tuesday and Wednesday, with minimum/maximum temperatures 15-30°F below normal, potentially setting daily record lows. Temperatures will moderate thereafter, although northern and eastern areas may remain somewhat below normal. The southern half of the Western U.S. may experience record highs of 10-20°F above normal through Thursday, trending cooler afterward. Light to moderate precipitation is anticipated mainly in northern areas, with a chance for wintry precipitation in the Southeastern/Southern Mid-Atlantic region mid...
33  A broad mean trough will affect the CONUS, with a shortwave upper low expected in the northwest on Thursday. Interaction with northern stream flow will influence surface evolution and precipitation types. A mid-level system is anticipated to reach the southern Rockies by Saturday and move through the eastern CONUS thereafter. Current models suggest reasonable forecasts for days 3-5, while an intermediate track is preferred for days 6-7 based on the 06Z GEFS and 00Z ECMWF means. Post-system, a flatter flow aloft will allow increased moisture to impact the central-northern west coast. \n\nModels show good agreement on initial energy over the northwest, while some discrepancies exist in speed and phasing as it shifts southeast. The GFS indicates a slower, more suppressed surface system mo...
35  Milder weather pattern expected across the central U.S. as the lower 48 states transition to a Pacific-influenced flow, bringing much-needed precipitation. A coastal storm forming on the Atlantic Seaboard will impact areas from the Piedmont to New England. Moderate to heavy rain is forecasted for northern and coastal California, with several inches expected along the coast and in the Mendocino Range. A broad cyclonic flow from the southern Gulf of Alaska will enhance rain events. Light to modest precipitation anticipated in the Southeast this weekend, though its spread and amounts are uncertain. Canadian high pressure will usher in much colder air (10-20°F below climo) following the exiting system, affecting the central plains and bringing a brief cooling in Florida. Additional precipi...

In [12]:
# Return sentences that likely indicate bad sentence splits
bad_sentences = df[
    # Starts with dangling symbols or units (but not valid numbers)
    df["text"].str.match(r"^(°F|\+F|F\+|[^\w\d])", na=False)
    |
    # Ends mid temperature or numeric range expression
    df["text"].str.contains(r"(°F[-+]$|\d-\s*$)", regex=True, na=False)
]

bad_sentences[["text"]]

/var/folders/78/9z0b45fx1xqbwxh8vk97lcfh0000gn/T/ipykernel_76613/2355735893.py:7: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  df["text"].str.contains(r"(°F[-+]$|\d-\s*$)", regex=True, na=False)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 text
821   **Weather Forecast (April 4-8, 2016)**\n\nRecord warmth expected in the western U.S., while the eastern U.S. will experience record cold and snowfall. A ridge will build in the northern Rockies, leading to a milder pattern in the west, with temperatures likely 10-25 degrees above average. Conversely, a significant cold front will bring temperatures to the teens and single digits in the northeast, 10-25 degrees below average, especially on Wednesday. Snow is forecasted along the I-90/88/86 corridor, with high pressure following the system leading to colder conditions.\n\nPrecipitation is expected in the northeast on Monday and again later in the week as systems move through the Great Lakes. Late next week, an increase in rain and snow is likely due to moisture from the Atlantic. Meanwhi...
1351  **Forecast Period (Sept 16 - Sept 20, 2017):**  \n- **Temperature:** Below average highs (10-20 degrees) across OR, northern CA, NV, and the northern Rockies. Above average temperatures across central/southern plains to Great Lakes/Northeast with highs averaging 10 degrees above normal in KS, OK, IA, MO, IL, WI, and parts of the eastern Great Lakes. Early November-like conditions in MT, WY, and ID with Saturday highs in the 40s, then moderating into Monday, before another cold wave arrives Tuesday and Wednesday.\n  \n- **Precipitation:** Highest chances from the central/northern Rockies to the upper Midwest associated with a surface low. Significant QPF expected along the WA/OR coast and the Cascades, as well as in the Northern Inter-Mountain West. High elevation snow possible in the C...
2907  \nFrom December 20 to December 24, 2021, expect multiple days of precipitation across the West Coast, particularly in northern and central California, driven by an amplified trough over the eastern Pacific. The southern two-thirds of the central and southern Plains will experience well above normal temperatures, with highs potentially exceeding 20°F above the norm, while the extreme northern Plains will see below normal temperatures, especially on Monday with highs 10-15°F below normal in Montana and North Dakota. Light to moderate rainfall will spread from the Gulf Coast into the Southeast, with uncertainties in intensity and extent. A significant moisture plume will contribute to heavy rainfall at lower elevations, with the potential for local flooding and heavy snow in mountainous a...
3054  **Forecast Summary**  \nRecord-breaking heat is expected across the south-central U.S. next week, particularly in Texas and Louisiana, with highs 15-25°F above normal. Unseasonably hot weather will also affect the southern tier, while cooling temperatures and precipitation dominate the Pacific Northwest due to upper troughing. Showers and thunderstorms are anticipated along fronts in the East, especially on Monday, with potential heavy rainfall and localized flooding in New England. There are concerns of heavy rain across the Upper Mississippi and Tennessee Valleys midweek due to multiple weather systems. Snow levels will initially be high but are expected to decrease as the week progresses. The forecast indicates two rainfall regimes east of the Rockies with uncertainty regarding amou...
3361  \nCalifornia will experience heavy rain and snow due to an incoming strong storm, with the potential for flooding. An Atmospheric River event is expected starting Tuesday, enhancing precipitation rates.\nMuch below average temperatures will affect the southern tier of the central and eastern U.S., with highs in Texas 15-30 degrees below normal. Morning lows will be around freezing across much of the South.\nShowers and thunderstorms will impact southeastern U.S., especially southern Florida, with possible light snow in the Southern High Plains.\nHeavy rain expected in the Midwest and Plains on Mar 23, with a risk of severe weather, including locally heavy rainfall.\nHeavy snowfall forecasted for the Rockies and parts of the Great Basin on Mar 21-22, with potential flooding in areas rec...

## Drop these, then save

In [13]:
# Create a boolean mask for the bad rows
bad_mask = (
    df["text"].str.match(r"^(°F|\+F|F\+|[^\w\d])", na=False) |
    df["text"].str.contains(r"(°F[-+]$|\d-\s*$)", regex=True, na=False)
)

# Keep the good rows
df = df[~bad_mask]          # or df = df.loc[~bad_mask]
df

/var/folders/78/9z0b45fx1xqbwxh8vk97lcfh0000gn/T/ipykernel_76613/3195584957.py:4: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  df["text"].str.contains(r"(°F[-+]$|\d-\s*$)", regex=True, na=False)

,date,temp,precip,humidity,windspeed,text,label
0,2014-01-01,37.9,0.000,57.4,10.0,"Arctic air is expected to invade the upper Midwest, Great Lakes, Ohio Valley, and Northeast, bringing some of the coldest temperatures in recent memory. Significant cold outbreaks on January 3-4 and 5-8 could result in temperatures 20-30 degrees Fahrenheit below normal Lows in New England may reach -10s to -20s, and areas in eastern Montana, Minnesota, and Wisconsin may experience lows at or below -20F? Colder locations could drop to -30s or -40s Fahrenheit?",1
1,2014-01-02,35.9,0.161,82.0,11.3,"Frigid air will sweep into the Midwest, Great Lakes, Ohio Valley, Northeast, and Mid-Atlantic early next week. A deep vortex will lead to significant temperature drops of -10 to -20 degrees across much of the central and eastern U.S., with the Ohio Valley potentially seeing temperatures nearly 40 degrees below normal by Monday. Heavy snow is anticipated northwest of a surface low tracking from the Lower Mississippi Valley to Interior New England, accompanied by strong winds, particularly across the Great Lakes. A strong Arctic front will move across the Appalachians on Sunday. By mid-week, temperatures should begin to moderate in the eastern half of the nation. Increasing moisture will bring rounds of precipitation to the Pacific Northwest, Intermountain West, and Great Basin as initia...",1
2,2014-01-03,22.4,0.015,54.1,30.5,"Another arctic plunge is expected for the northeast quarter of the US Monday and Tuesday, leading to temperatures 20 to 40 degrees Fahrenheit below normal. A deep upper-level system over eastern Canada will influence this frigid air, while a fresh north Pacific flow will bring cooler and unsettled weather to the Great Lakes and northeast. Light to moderate precipitation is forecasted across the west, with potential localized enhancement along the coast. As the week progresses, precipitation is expected to increase from the southern plains into the Ohio and Tennessee valleys, with rain in the south transitioning to snow/mix further north. The forecast maintains good continuity despite some discrepancies between models regarding the impacts of cold advection associated with the arctic in...",1
3,2014-01-04,25.4,0.000,52.6,13.3,"20°F-40°F below normal temperatures are expected in the northeastern quarter of the U.S. for January 7-11, 2014, with Indiana, Ohio, and western Pennsylvania experiencing temperatures 20°F+ below normal. An arctic blast will affect these regions, while the southeast and mid-Atlantic areas will also experience lower temperatures. The forecast incorporates a blend of GFS and GEFS solutions, with a notable phase of energy in the northern stream beyond day 4.",1
4,2014-01-05,37.1,0.041,78.7,11.0,"Temperatures are expected to approach normal values, with possibilities of being above normal. A progressive weather pattern will dominate the lower 48 states. Significant precipitation and strong winds are anticipated for the Pacific Northwest due to cyclogenesis off the Oregon/Washington coast. In the Midwest and Plains, a system originating from the South Central Rockies will bring rain through the Ohio Valley, influenced by a surface ridge in the Northeast and Mid-Atlantic. Mid-level warm advection will contribute to this precipitation. The GFS model shows discrepancies in predicted conditions in the Mid-Missouri Valley, while Gulf of Mexico moisture is expected to affect the Southern Plains and Lower-to-Mid Missouri Valley. A cutoff low over the Rio Grande Valley will also enhance...",1
...,...,...,...,...,...,...,...
3617,2023-11-27,43.0,0.004,62.0,20.4,"Moderate to heavy rainfall is expected from Thursday, impacting the South, Southeast, and Mid-Mississippi Valley, particularly the eastern Texas Gulf Coast and western Louisiana where flash flooding is a concern. An upper-level shortwave will move from the Southwest to the Northeast this weekend, bringing unsettled weather. The Gulf Coast and Southeast will experience potentially heavy rainfall, with a marginal risk of excessive rainfall. The interior West will remain cooler than normal under reinforced troughing, while daytime highs in the Northern Plains, Midwest, and East could trend 5-10 degrees above average by the weekend. Precipitation will increase in the West, primarily along the Washington/Oregon coast and Cascades, with lighter amounts inland. The Western U.S. may return to ...",1
3618,2023-11-28,35.7,0.001,42.2,25.0,"Wet pattern expected for the Northwest, with heavy snow threats inland from the Cascades and north-central Intermountain West/Rockies. From December 1 to December 5, 2023, widespread moderate to heavy rainfall is anticipated, particularly in the Gulf Coast and Southeast, with a marginal risk of excessive rainfall due to anomalous moisture and instability. High uncertainty in precipitation forecasts, especially across the east-central U.S. Precipitation is expected to increase in the West starting Thursday, leading to heaviest precipitation on the Washington/Oregon coast and Cascades from Sunday into Monday, along with accumulating snow in higher elevations. Stronger cyclogenesis may lead to larger-scale precipitation next week, impacting the Northeast as well.",1
3619,2023-11-29,32.9,0.000,41.8,10.1,"Multi-day wet pattern expected for the Northwest, with heavy snow threats from the Cascades to the north-central Intermountain West/Rockies. Active weather pattern continues through the weekend into next week, with systems moving from the interior West to the East Coast Saturday-Monday and ridging developing behind. An Atmospheric River may impact the West Coast this weekend, bringing ongoing precipitation and potential excessive rainfall in far northwest CA/southwest OR. Expect heavy snows and gusty winds in higher elevations of the Cascades and northern Sierras. Rainfall threat increases along the Oregon coast and western slopes of the Cascades, with another system bringing rain/mountain snow primarily to Washington state early next week. Moderate to heavy rainfall is likely for the ...",1
3620,2023-11-30,42.1,0.000,51.4,10.5,"Heavy rain and inland heavy snow threats are expected in the Northwest due to a series of atmospheric rivers, with heavy snow threats also affecting the Northeast. An active weather pattern will bring heavy precipitation mainly across the Northwest and Northeast. In Washington and Oregon, heavy rainfall is anticipated, while the northern Intermountain West and Rockies could see significant snowfall. \n\nTemperatures in the Northern and Central Plains will be well above normal, reaching 15 to 25 degrees above average by Wednesday and Thursday. A strong ridge building over the West will influence these temperatures. Precipitation from atmospheric rivers will continue into next week, but with uncertainty in timing and volume.\n\nCoastal areas may experience modest rainfall, while the risk...",1
3621,2023-12-01,45.6,0.123,73.4,10.7,"Heavy rain is expected in the Pacific Northwest due to multiple atmospheric river events from December 4 to December 8, 2023, possibly leading to flooding and rising river levels. Well above average temperatures, potentially 20-30 degrees higher than early December averages, are forecast for the Intermountain West and Plains, with record highs possible on Wednesday and Thursday. Snow showers may accompany a departing storm system in the Upper Midwest transitioning toward the Ohio Valley. A broad upper trough will bring active weather in the eastern U.S., with near seasonal temperatures expected, while a zonal flow pattern is anticipated by the end of the week. In the Northwest, 3-6 inch rainfall totals are likely, with a slight risk of flooding especially in the Cascades due to snow me...",1

In [14]:
save_path = os.path.join(base_data_path, 'multimodal_forecast', 'climate_forecasts')
DataProcessing.save_to_file(df, save_path, 'climate_forecasts', include_version=True, save_file_type='.csv')

Using file number: 5
Saving CSV file to: /Users/detraviousjamaribrinkley/Documents/Development/research_labs/uf_ds/predictions/notebook_experiments/../data/multimodal_forecast/climate_forecasts/climate_forecasts-v5.csv

In [ ]:
sfe = SpacyFeatureExtraction(df, 'text')
sfe

In [ ]:
sfe.sentence_embeddings_extraction(attach_to_df=True)

In [ ]:
df = sfe.split_into_sentences(sentence_col_name='sentence')
df

In [ ]:
df[
    df["text"].str.contains(r"°F", regex=True, na=False)
][["text"]]

In [ ]:
# Return sentences that likely indicate bad sentence splits
bad_sentences = df[
    # Starts with dangling symbols or units (but not valid numbers)
    df["text"].str.match(r"^(°F|\+F|F\+|[^\w\d])", na=False)
    |
    # Ends mid temperature or numeric range expression
    df["text"].str.contains(r"(°F[-+]$|\d-\s*$)", regex=True, na=False)
]

bad_sentences[["text"]]

In [ ]:
import re

def normalize_forecast_text(text: str) -> str:
    if not isinstance(text, str):
        return text

    # Remove markdown bold/italics
    text = re.sub(r"\*\*(.*?)\*\*", r"\1", text)

    # Remove standalone headers (lines with no sentence punctuation)
    text = re.sub(
        r"(?m)^(?:[A-Z][A-Za-z\s]+(?:\([^)]+\))?:)\s*$",
        "",
        text
    )

    # Convert bullet points to sentences
    text = re.sub(r"(?m)^-\s+", "", text)

    # Collapse excessive newlines
    text = re.sub(r"\n{2,}", " ", text)

    return text.strip()

In [ ]:
df["text"] = df["text"].apply(normalize_forecast_text)
df = sfe.split_into_sentences(sentence_col_name='clean sentence')
df

In [ ]:
# Return sentences that likely indicate bad sentence splits
bad_sentences = df[
    # Starts with dangling symbols or units (but not valid numbers)
    df["clean sentence"].str.match(r"^(°F|\+F|F\+|[^\w\d])", na=False)
    |
    # Ends mid temperature or numeric range expression
    df["clean sentence"].str.contains(r"(°F[-+]$|\d-\s*$)", regex=True, na=False)
]

bad_sentences[["clean sentence"]]

In [ ]:
bad_sentences