# Climate Forecasts

1. DATASETS: [Hugging Face: Howard Tsai | All](https://huggingface.co/Howard881010)
2. DATASETS: [Hugging Face: Howard Tsai | Climate-1 Day](https://huggingface.co/datasets/Howard881010/climate-1day)
3. REPO: [Multimodal_Forecasting](https://github.com/Rose-STL-Lab/Multimodal_Forecasting/tree/main)
    - Get data from here.

In [1]:
import os, sys

import pandas as pd

# Get the current working directory of the notebook
notebook_dir = os.getcwd()
# Add the parent directory to the system path
sys.path.append(os.path.join(notebook_dir, '../'))

from data_processing import DataProcessing
from feature_extraction import SpacyFeatureExtraction

In [2]:
pd.set_option('max_colwidth', 800)

In [3]:
base_data_path = DataProcessing.load_base_data_path(notebook_dir)
dataset_path = os.path.join(base_data_path, 'forecast_bench/2024-07-21-human.json')

In [4]:
df = DataProcessing.load_from_file(dataset_path, file_type='json')
df

,forecast_due_date,question_set,questions
0,2024-07-21,2024-07-21-human.json,"{'id': 'TPkEjiNb1wVCIGFnPcDD', 'source': 'manifold', 'question': 'Will the average global temperature in 2024 exceed 2023?', 'resolution_criteria': 'Resolves to the outcome of the question found at https://manifold.markets/SteveRabin/will-the-average-global-temperature.', 'background': '2023 is trending to be the hottest year on record.', 'market_info_open_datetime': '2023-10-13T17:44:30+00:00', 'market_info_close_datetime': '2025-01-01T04:59:00+00:00', 'market_info_resolution_criteria': 'N/A', 'url': 'https://manifold.markets/SteveRabin/will-the-average-global-temperature', 'freeze_datetime': '2024-07-12T00:00:00+00:00', 'freeze_datetime_value': '0.7565624485542961', 'freeze_datetime_value_explanation': 'The market value.', 'source_intro': 'We would like you to predict the outcome of ..."
1,2024-07-21,2024-07-21-human.json,"{'id': 'KCFbp1TH0RYN4j5zYdmh', 'source': 'manifold', 'question': 'Will any event of the Paris 2024 Olympic Games be postponed or cancelled due to the water quality of the Seine?', 'resolution_criteria': 'Resolves to the outcome of the question found at https://manifold.markets/Pob/will-any-event-of-the-paris-2024-ol.', 'background': 'It also counts as YES if an event is moved to a venue other than the Seine river ahead of time because of water quality concerns. Background: Seine River events scrapped again, renewing doubts over Paris Olympics plan Paris Olympics promises Seine clean-up after pollution spoils triathlon | Financial Times', 'market_info_open_datetime': '2023-08-25T19:59:35+00:00', 'market_info_close_datetime': '2024-08-11T21:59:00+00:00', 'market_info_resolution_criter..."
2,2024-07-21,2024-07-21-human.json,"{'id': 'q6wJThcy6TJnQKrbjALm', 'source': 'manifold', 'question': 'Will the majority of new cars sold be electric vehicles by the end of 2030?', 'resolution_criteria': 'Resolves to the outcome of the question found at https://manifold.markets/TobiasSowaaed/will-the-majority-of-new-cars-sold-c4d566afc8c7.', 'background': 'Majority is 50%+ and it's worldwide marketshare', 'market_info_open_datetime': '2023-09-01T23:59:55+00:00', 'market_info_close_datetime': '2030-12-31T22:59:00+00:00', 'market_info_resolution_criteria': 'N/A', 'url': 'https://manifold.markets/TobiasSowaaed/will-the-majority-of-new-cars-sold-c4d566afc8c7', 'freeze_datetime': '2024-07-12T00:00:00+00:00', 'freeze_datetime_value': '0.6912524093033491', 'freeze_datetime_value_explanation': 'The market value.', 'source_intro':..."
3,2024-07-21,2024-07-21-human.json,"{'id': 'cLxfTH5GDfmqeNJwClVF', 'source': 'manifold', 'question': 'Will the majority of new cars sold worldwide be electric before the end of 2030?', 'resolution_criteria': 'Resolves to the outcome of the question found at https://manifold.markets/kian_spire/will-the-majority-of-new-cars-sold.', 'background': 'This question will resolve as YES if more than 50% of new cars sold worldwide in the year 2030 are electric. The source for determining the percentage of electric cars sold will be the International Energy Agency (IEA) annual report on electric vehicles. The report will be released in 2031 and will provide data on the percentage of electric cars sold in 2030. This question does not include hybrid cars, only fully electric cars. The question does not consider any potential chang..."
4,2024-07-21,2024-07-21-human.json,"{'id': 'ygVTjZRGDZvp0EQJ1L53', 'source': 'manifold', 'question': 'Will sports betting be legal in California and Texas by 2030?', 'resolution_criteria': 'Resolves to the outcome of the question found at https://manifold.markets/10thOfficial/will-sports-betting-be-legal-in-cal.', 'background': 'Must be able to place both an in-person and online sports bet legally in each state on January 1, 2030.', 'market_info_open_datetime': '2024-01-05T22:00:15+00:00', 'market_info_close_datetime': '2030-01-01T04:59:00+00:00', 'market_info_resolution_criteria': 'N/A', 'url': 'https://manifold.markets/10thOfficial/will-sports-betting-be-legal-in-cal', 'freeze_datetime': '2024-07-12T00:00:00+00:00', 'freeze_datetime_value': '0.805330724795234', 'freeze_datetime_value_explanation': 'The market value.', ..."
...,...,...,...
195,2024-07-21,2024-07-21-human.json,"{'id': 'HUM', 'source': 'yfinance', 'question': 'Will HUM's market close price on {resolution_date} be higher than its market close price on {forecast_due_date}? Stock splits and reverse splits will be accounted for in resolving this question. Forecasts on questions about companies that have been delisted (through mergers or bankruptcy) will resolve to their final close price.', 'resolution_criteria': 'Resolves to the market close price at https://finance.yahoo.com/quote/HUM for the resolution date. If the resolution date coincides with a day the market is closed (weekend, holiday, etc.) the previous market close price is used.', 'background': 'Humana Inc., together with its subsidiaries, provides medical and specialty insurance products in the United States. It operates through two s..."
196,2024-07-21,2024-07-21-human.json,"{'id': 'CBRE', 'source': 'yfinance', 'question': 'Will CBRE's market close price on {resolution_date} be higher than its market close price on {forecast_due_date}? Stock splits and reverse splits will be accounted for in resolving this question. Forecasts on questions about companies that have been delisted (through mergers or bankruptcy) will resolve to their final close price.', 'resolution_criteria': 'Resolves to the market close price at https://finance.yahoo.com/quote/CBRE for the resolution date. If the resolution date coincides with a day the market is closed (weekend, holiday, etc.) the previous market close price is used.', 'background': 'CBRE Group, Inc. operates as a commercial real estate services and investment company in the United States, the United Kingdom, and interna..."
197,2024-07-21,2024-07-21-human.json,"{'id': 'TPR', 'source': 'yfinance', 'question': 'Will TPR's market close price on {resolution_date} be higher than its market close price on {forecast_due_date}? Stock splits and reverse splits will be accounted for in resolving this question. Forecasts on questions about companies that have been delisted (through mergers or bankruptcy) will resolve to their final close price.', 'resolution_criteria': 'Resolves to the market close price at https://finance.yahoo.com/quote/TPR for the resolution date. If the resolution date coincides with a day the market is closed (weekend, holiday, etc.) the previous market close price is used.', 'background': 'Tapestry, Inc. provides luxury accessories and branded lifestyle products in the United States, Japan, Greater China, and internationally. The..."
198,2024-07-21,2024-07-21-human.json,"{'id': 'CCL', 'source': 'yfinance', 'question': 'Will CCL's market close price on {resolution_date} be higher than its market close price on {forecast_due_date}? Stock splits and reverse splits will be accounted for in resolving this question. Forecasts on questions about companies that have been delisted (through mergers or bankruptcy) will resolve to their final close price.', 'resolution_criteria': 'Resolves to the market close price at https://finance.yahoo.com/quote/CCL for the resolution date. If the resolution date coincides with a day the market is closed (weekend, holiday, etc.) the previous market close price is used.', 'background': 'Carnival Corporation & plc engages in the provision of leisure travel services in North America, Australia, Europe, Asia, and internationally...."
199,2024-07-21,2024-07-21-human.json,"{'id': 'FFIV', 'source': 'yfinance', 'question': 'Will FFIV's market close price on {resolution_date} be higher than its market close price on {forecast_due_date}? Stock splits and reverse splits will be accounted for in resolving this question. Forecasts on questions about companies that have been delisted (through mergers or bankruptcy) will resolve to their final close price.', 'resolution_criteria': 'Resolves to the market close price at https://finance.yahoo.com/quote/FFIV for the resolution date. If the resolution date coincides with a day the market is closed (weekend, holiday, etc.) the previous market close price is used.', 'background': 'F5, Inc. provides multi-cloud application security and delivery solutions in the United States, Europe, the Middle East, Africa, and the As..."

In [39]:
result = []

for idx, row in df.iterrows():
    forecast_due = row["forecast_due_date"]
    # Skip the whole row if the forecast date is “N/A”
    if forecast_due == "N/A":
        continue

    # Build a base meta dict that will be copied for each variant
    base_meta = {
        "meta_data": row["questions"],
        "forecast_due_date": forecast_due,
        "question_set": row["question_set"],
    }

    question = row["questions"]["question"]

    # Determine if we need to duplicate the row per resolution date
    if "{resolution_date}" in question:
        for rd in row["questions"]["resolution_dates"]:
            q = question.replace("{forecast_due_date}", forecast_due).replace(
                "{resolution_date}", rd
            )
            result.append(
                {**base_meta, "question": q}
            )
    else:
        # No resolution placeholder – just replace the forecast placeholder
        question = question.replace("{forecast_due_date}", forecast_due)
        result.append(
            {**base_meta, "question": question}
        )

# The list `result` now holds all the expanded question / meta‑data pairs
questions_and_meta_data = result

In [40]:
pd.DataFrame(questions_and_meta_data)

,meta_data,forecast_due_date,question_set,question
0,"{'id': 'TPkEjiNb1wVCIGFnPcDD', 'source': 'manifold', 'question': 'Will the average global temperature in 2024 exceed 2023?', 'resolution_criteria': 'Resolves to the outcome of the question found at https://manifold.markets/SteveRabin/will-the-average-global-temperature.', 'background': '2023 is trending to be the hottest year on record.', 'market_info_open_datetime': '2023-10-13T17:44:30+00:00', 'market_info_close_datetime': '2025-01-01T04:59:00+00:00', 'market_info_resolution_criteria': 'N/A', 'url': 'https://manifold.markets/SteveRabin/will-the-average-global-temperature', 'freeze_datetime': '2024-07-12T00:00:00+00:00', 'freeze_datetime_value': '0.7565624485542961', 'freeze_datetime_value_explanation': 'The market value.', 'source_intro': 'We would like you to predict the outcome of ...",2024-07-21,2024-07-21-human.json,Will the average global temperature in 2024 exceed 2023?
1,"{'id': 'KCFbp1TH0RYN4j5zYdmh', 'source': 'manifold', 'question': 'Will any event of the Paris 2024 Olympic Games be postponed or cancelled due to the water quality of the Seine?', 'resolution_criteria': 'Resolves to the outcome of the question found at https://manifold.markets/Pob/will-any-event-of-the-paris-2024-ol.', 'background': 'It also counts as YES if an event is moved to a venue other than the Seine river ahead of time because of water quality concerns. Background: Seine River events scrapped again, renewing doubts over Paris Olympics plan Paris Olympics promises Seine clean-up after pollution spoils triathlon | Financial Times', 'market_info_open_datetime': '2023-08-25T19:59:35+00:00', 'market_info_close_datetime': '2024-08-11T21:59:00+00:00', 'market_info_resolution_criter...",2024-07-21,2024-07-21-human.json,Will any event of the Paris 2024 Olympic Games be postponed or cancelled due to the water quality of the Seine?
2,"{'id': 'q6wJThcy6TJnQKrbjALm', 'source': 'manifold', 'question': 'Will the majority of new cars sold be electric vehicles by the end of 2030?', 'resolution_criteria': 'Resolves to the outcome of the question found at https://manifold.markets/TobiasSowaaed/will-the-majority-of-new-cars-sold-c4d566afc8c7.', 'background': 'Majority is 50%+ and it's worldwide marketshare', 'market_info_open_datetime': '2023-09-01T23:59:55+00:00', 'market_info_close_datetime': '2030-12-31T22:59:00+00:00', 'market_info_resolution_criteria': 'N/A', 'url': 'https://manifold.markets/TobiasSowaaed/will-the-majority-of-new-cars-sold-c4d566afc8c7', 'freeze_datetime': '2024-07-12T00:00:00+00:00', 'freeze_datetime_value': '0.6912524093033491', 'freeze_datetime_value_explanation': 'The market value.', 'source_intro':...",2024-07-21,2024-07-21-human.json,Will the majority of new cars sold be electric vehicles by the end of 2030?
3,"{'id': 'cLxfTH5GDfmqeNJwClVF', 'source': 'manifold', 'question': 'Will the majority of new cars sold worldwide be electric before the end of 2030?', 'resolution_criteria': 'Resolves to the outcome of the question found at https://manifold.markets/kian_spire/will-the-majority-of-new-cars-sold.', 'background': 'This question will resolve as YES if more than 50% of new cars sold worldwide in the year 2030 are electric. The source for determining the percentage of electric cars sold will be the International Energy Agency (IEA) annual report on electric vehicles. The report will be released in 2031 and will provide data on the percentage of electric cars sold in 2030. This question does not include hybrid cars, only fully electric cars. The question does not consider any potential chang...",2024-07-21,2024-07-21-human.json,Will the majority of new cars sold worldwide be electric before the end of 2030?
4,"{'id': 'ygVTjZRGDZvp0EQJ1L53', 'source': 'manifold', 'question': 'Will sports betting be legal in California and Texas by 2030?', 'resolution_criteria': 'Resolves to the outcome of the question found at https://manifold.markets/10thOfficial/will-sports-betting-be-legal-in-cal.', 'background': 'Must be able to place both an in-person and online sports bet legally in each state on January 1, 2030.', 'market_info_open_datetime': '2024-01-05T22:00:15+00:00', 'market_info_close_datetime': '2030-01-01T04:59:00+00:00', 'market_info_resolution_criteria': 'N/A', 'url': 'https://manifold.markets/10thOfficial/will-sports-betting-be-legal-in-cal', 'freeze_datetime': '2024-07-12T00:00:00+00:00', 'freeze_datetime_value': '0.805330724795234', 'freeze_datetime_value_explanation': 'The market value.', ...",2024-07-21,2024-07-21-human.json,Will sports betting be legal in California and Texas by 2030?
...,...,...,...,...
963,"{'id': 'FFIV', 'source': 'yfinance', 'question': 'Will FFIV's market close price on {resolution_date} be higher than its market close price on {forecast_due_date}? Stock splits and reverse splits will be accounted for in resolving this question. Forecasts on questions about companies that have been delisted (through mergers or bankruptcy) will resolve to their final close price.', 'resolution_criteria': 'Resolves to the market close price at https://finance.yahoo.com/quote/FFIV for the resolution date. If the resolution date coincides with a day the market is closed (weekend, holiday, etc.) the previous market close price is used.', 'background': 'F5, Inc. provides multi-cloud application security and delivery solutions in the United States, Europe, the Middle East, Africa, and the As...",2024-07-21,2024-07-21-human.json,Will FFIV's market close price on 2025-01-17 be higher than its market close price on 2024-07-21?\n\nStock splits and reverse splits will be accounted for in resolving this question. Forecasts on questions about companies that have been delisted (through mergers or bankruptcy) will resolve to their final close price.
964,"{'id': 'FFIV', 'source': 'yfinance', 'question': 'Will FFIV's market close price on {resolution_date} be higher than its market close price on {forecast_due_date}? Stock splits and reverse splits will be accounted for in resolving this question. Forecasts on questions about companies that have been delisted (through mergers or bankruptcy) will resolve to their final close price.', 'resolution_criteria': 'Resolves to the market close price at https://finance.yahoo.com/quote/FFIV for the resolution date. If the resolution date coincides with a day the market is closed (weekend, holiday, etc.) the previous market close price is used.', 'background': 'F5, Inc. provides multi-cloud application security and delivery solutions in the United States, Europe, the Middle East, Africa, and the As...",2024-07-21,2024-07-21-human.json,Will FFIV's market close price on 2025-07-21 be higher than its market close price on 2024-07-21?\n\nStock splits and reverse splits will be accounted for in resolving this question. Forecasts on questions about companies that have been delisted (through mergers or bankruptcy) will resolve to their final close price.
965,"{'id': 'FFIV', 'source': 'yfinance', 'question': 'Will FFIV's market close price on {resolution_date} be higher than its market close price on {forecast_due_date}? Stock splits and reverse splits will be accounted for in resolving this question. Forecasts on questions about companies that have been delisted (through mergers or bankruptcy) will resolve to their final close price.', 'resolution_criteria': 'Resolves to the market close price at https://finance.yahoo.com/quote/FFIV for the resolution date. If the resolution date coincides with a day the market is closed (weekend, holiday, etc.) the previous market close price is used.', 'background': 'F5, Inc. provides multi-cloud application security and delivery solutions in the United States, Europe, the Middle East, Africa, and the As...",2024-07-21,2024-07-21-human.json,Will FFIV's market close price on 2027-07-21 be higher than its market close price on 2024-07-21?\n\nStock splits and reverse splits will be accounted for in resolving this question. Forecasts on questions about companies that have been delisted (through mergers or bankruptcy) will resolve to their final close price.
966,"{'id': 'FFIV', 'source': 'yfinance', 'question': 'Will FFIV's market close price on {resolution_date} be higher than its market close price on {forecast_due_date}? Stock splits and reverse splits will be accounted for in resolving this question. Forecasts on questions about companies that have been delisted (through mergers or bankruptcy) will resolve to their final close price.', 'resolution_criteria': 'Resolves to the market close price at https://finance.yahoo.com/quote/FFIV for the resolution date. If the resolution date coincides with a day the market is closed (weekend, holiday, etc.) the previous market close price is used.', 'background': 'F5, Inc. provides multi-cloud application security and delivery solutions in the United States, Europe, the Middle East, Africa, and the As...",2024-07-21,2024-07-21-human.json,Will FFIV's market close price on 2029-07-20 be higher than its market close price on 2024-07-21?\n\nStock splits and reverse splits will be accounted for in resolving this question. Forecasts on questions about companies that have been delisted (through mergers or bankruptcy) will resolve to their final close price.
967,"{'id': 'FFIV', 'source': 'yfinance', 'question': 'Will FFIV's market close price on {resolution_date} be higher than its market close price on {forecast_due_date}? Stock splits and reverse splits will be accounted for in resolving this question. Forecasts on questions about companies that have been delisted (through mergers or bankruptcy) will resolve to their final close price.', 'resolution_criteria': 'Resolves to the market close price at https://finance.yahoo.com/quote/FFIV for the resolution date. If the resolution date coincides with a day the market is closed (weekend, holiday, etc.) the previous market close price is used.', 'background': 'F5, Inc. provides multi-cloud application security and delivery solutions in the United States, Europe, the Middle East, Africa, and the As...",2024-07-21,2024-07-21-human.json,Will FFIV's market close price on 2034-07-19 be higher than its market close price on 2024-07-21?\n\nStock splits and reverse splits will be accounted for in resolving this question. Forecasts on questions about companies that have been delisted (through mergers or bankruptcy) will resolve to their final close price.

Will HUM's market close price on {resolution_date} be higher than its market close price on {forecast_due_date}?\n\nStock splits and reverse splits will be accounted for in resolving this question. Forecasts on questions about companies that have been delisted (through mergers or bankruptcy) will resolve to their final close price.

In [37]:
questions_and_meta_data = []

for idx, row in df.iterrows():
    forecast_due_date = row['forecast_due_date']
    question_set = row['question_set']
    question = row['questions']['question']
    resolution_dates = row['questions']['resolution_dates']
    print(resolution_dates)

    print(question)


    if 'forecast_due_date' in question or 'resolution_date' in question:

        resolution_date_questions = []
        for resolution_date in resolution_dates:
            question = question.replace("{resolution_date}", resolution_date)
            question_and_meta_data = {
            'question': question
        }

    else:
        question_and_meta_data = {
            'question': question
        }

        question_and_meta_data = {
            'meta_data': row['questions'],
            'forecast_due_date': forecast_due_date,
            'question_set': question_set
        }
    questions_and_meta_data.append(question_and_meta_data)

questions_and_meta_data

N/A
Will the average global temperature in 2024 exceed 2023?
N/A
Will any event of the Paris 2024 Olympic Games be postponed or cancelled due to the water quality of the Seine?
N/A
Will the majority of new cars sold be electric vehicles by the end of 2030?
N/A
Will the majority of new cars sold worldwide be electric before the end of 2030?
N/A
Will sports betting be legal in California and Texas by 2030?
N/A
👍👎 Manifold Leadership Approval Rating [Market Index]
N/A
Will Rafael Nadal win another Grand Slam before his retirement?
N/A
[2024 Formula 1 Season] Will Oscar Piastri or Daniel Ricciardo win a race?
N/A
Will Ding Liren repeat as World Chess Champion?
N/A
Will Lionel Messi retire before the end of 2024?
N/A
Will Rational Animations' video about Manifold Markets reach 200k views by the end of 2024?
N/A
Will over 70% of Manifold users think that Elon Musk does not deserve 100 billion dollars?
N/A
Will the U.S. win the gold medal in the Men's Basketball at the 2024 Summer Olympics in Paris?
N/A
Will England win the 2026 FIFA World Cup?
N/A
[2024 Formula 1 Season] Will Sergio Perez finish 2nd or higher in the Drivers Championship?
N/A
Will a video game be played in the Olympics as an official event by the end of 2030?
N/A
Will Doors of Stone, the third book of the Kingkiller Chronicle by Patrick Rothfuss, be released before 2025?
N/A
Will Taylor Swift release Reputation (Taylor's Version) before the end of 2024?
N/A
Will an artificial intelligence system play a major artistic role in the 2024 Olympic opening ceremonies?
N/A
Instant deepfakes of anyone (doing anything) by the end of 2027?
N/A
Will Apple’s next iPhone (2024) include an on-device LLM “ChatBot”?
N/A
Will Kamala Harris be the Democratic Nominee for President in 2024?
N/A
Will the OpenAI board fire Sam Altman again in 2024?
N/A
Will Russia start a second mobilization wave before 2025, according to the Institute for the Study of War?
N/A
Will an infrastructure disaster costing >$1B in a G20 country be widely attributed to an AI cyberattack before 2025?
N/A
Will the FDA or EMA withdraw approval of Semaglutide for the treatment of obesity by 2027?
N/A
Ragnarök Question Series: If a global catastrophe occurs, will it be due to naturally occuring pandemics?
N/A
Will an AI system solve one of the remaining Millennium Prize Problems before July 2025?
N/A
Will Threads support ActivityPub before 2025?
N/A
Will there be a tsunami that kills at least 50,000 people before 2030?
N/A
Will Elon Musk be the richest person in the world on December 31, 2025?
N/A
Will Bryan Caplan win his bet that India's average fertility rate for 2032 & 2033  will be < 2.0?
N/A
Will Robert Caro's fifth and final volume of his Lyndon Johnson biography be published during his lifetime?
N/A
Will George R. R. Martin publish the sixth novel in "A Song of Ice and Fire" before Patrick Rothfuss publishes the third novel in "The Kingkiller Chronicle"?
N/A
Will GB News be broadcasting in 2025?
N/A
Will USA top the Olympic Medal Table at Paris 2024?
N/A
Will Andy Carlile's 7:10 BTG Nürburgring Nordschleife motorcycle laptime be beaten before 2030?
N/A
By December 31st, 2028, will it be considered best practice in clinical psychology to incorporate AI tools in the diagnostic process?
N/A
Will wheat be successfully de-allergenized by 2030?
N/A
Will a mission to land a spacecraft on Europa launch by 2030?
N/A
Will Waltine Nauta receive a more severe sentence than Donald Trump in "United States v. Donald J. Trump and Waltine Nauta"?
N/A
Will a politician claim they lost a major election due to a "deepfake" image, video, or audio recording in a G20 country before 2025?
N/A
Will an AI be able to reliably construct bug-free code of more than 10,000 lines before 2030?
N/A
Will OpenAI offer ChatGPT in China before 2026?
N/A
Will the US and the EU (or one of its member states) cut diplomatic ties before 2051?
N/A
Will Scotland leave the United Kingdom before 2025?
N/A
Will a North American testing center (OTIC) issue an O-RAN Certificate between 1 April 2024 and 31 March 2025?
N/A
Will at least five more exoplanets be found to be potentially habitable between 1 February 2024 and 31 December 2024?
N/A
Will Iraq return its ambassador to Iran in the next month?
N/A
Will Iran agree to limit uranium enrichment to 5% or less in the next 6 months?
N/A
Will the Lebanese parliament elect a president in the next six months?
N/A
Will Ali Khamenei flee Iran or cease to be Supreme Leader in the next year?
N/A
Will Myanmar hold national elections before 1 July 2025?
N/A
Will Nicolás Maduro be president of Venezuela on 11 January 2025?
N/A
Will there be an attack on an Iranian nuclear- or offensive missile-related facility in the next 6 months?
N/A
Will Israel declare war on Hezbollah in the next 6 months?
N/A
Will Israel declare war on Hezbollah in the next 12 months?
N/A
Will there be an agreed-upon pause in the conflict between Israel and Hamas that starts before 1 December 2024 and lasts at least 30 days?
N/A
By 31 December 2024, will uranium enriched to 90% or more be discovered in an Iranian facility, according to the IAEA?
N/A
Will Iran be impacted by a cyberattack targeting critical infrastructure between 27 February 2024 and 1 March 2025?
N/A
Will any listed Muslim-majority country sign an agreement establishing or normalizing diplomatic relations with Israel in the next six months?
N/A
Will a JCPOA participant country begin the process of imposing “snapback” sanctions on Iran by 31 December 2024?
N/A
Will Vladimir Putin cease to be the president of the Russian Federation before 1 July 2025?
N/A
Will Israel and Saudi Arabia publicly acknowledge that they are resuming the normalization process in the next six months?
N/A
In the next six months, will the Global Protest Tracker record an anti-government protest in Iran with 10,000 or more participants lasting at least a week?
N/A
Will Iran be at war with another country in the next year?
N/A
Will the Houthi movement and Yemen reach a ceasefire that is in effect on 31 December 2024 and lasts at least six months?
N/A
Will a collaboration between Huawei and the O-RAN Alliance be announced before 1 October 2025?
N/A
Will 2024 be the hottest year on record?
N/A
Will there be between 16 and 20 named storms during Atlantic Hurricane Season?
N/A
Will there be more than 25 named storms during Atlantic Hurricane Season?
N/A
Will there be between 21 and 25 named storms during Atlantic Hurricane Season?
N/A
Will there be less than 16 named storms during Atlantic Hurricane Season?
N/A
Will Belichick head coach the Eagles in the 2024-25 NFL season?
N/A
Will Belichick head coach another team in the 2024-25 NFL season?
N/A
Will four SpaceX Starship launches successfully reach outer space in 2024?
N/A
Tesla Robotaxi unveiling delayed?
N/A
[Single Market] Will Joe Biden win the U.S. 2024 Democratic presidential nomination?
N/A
Will Hillary Clinton win the 2024 US Presidential Election?
N/A
Will a candidate from another party win Washington DC Presidential Election?
N/A
[Single Market] Will Joe Rogan win the U.S. 2024 Republican presidential nomination?
N/A
James Norton announced as next James Bond?
N/A
Damson Idris announced as next James Bond?
N/A
No Eigenlayer token launch in 2024?
N/A
GPT-5 announced in Q4 2024?
N/A
Will Satoshi Nakamoto's identity not be proven in 2024?
N/A
Will POPCAT reach $1b first?
N/A
Will another cat memecoin reach $1b first?
N/A
Will a Democrat win Vermont Governor Election?
N/A
Will a candidate from another party win Massachusetts Presidential Election?
['2024-07-28', '2024-08-20', '2024-10-19', '2025-01-17', '2025-07-21', '2027-07-21', '2029-07-20', '2034-07-19']
Will there be more than ten times as many fatalities in Niue for the 30 days before {resolution_date} compared to one plus the 30-day average of fatalities over the 360 days preceding {forecast_due_date}?

e.g. If the forecast due date is 2024-01-01 and we have the following data:
Date,fatalities
2023-11-11,1
2023-10-10,2
to calculate one plus the 30-day average of fatalities over the preceding 360 days, we’d have: 1+(1+2)/12=1.25.

In this example, for the question to resolve positively, 13 (10 x 1.25) or more fatalities would need to occur in the 30 days leading up to the resolution.
['2024-07-28', '2024-08-20', '2024-10-19', '2025-01-17', '2025-07-21', '2027-07-21', '2029-07-20', '2034-07-19']
Will there be more 'Strategic developments' in Bosnia and Herzegovina for the 30 days before {resolution_date} compared to the 30-day average of 'Strategic developments' over the 360 days preceding {forecast_due_date}?

e.g. If the forecast due date is 2024-01-01 and we have the following data:
Date,'Strategic developments'
2023-11-11,1
2023-10-10,2
to calculate the 30-day average of 'Strategic developments' over the preceding 360 days, we’d have: (1+2)/12=0.25.

In this example, for the question to resolve positively, 1 or more 'Strategic developments' would need to occur in the 30 days leading up to the resolution.
['2024-07-28', '2024-08-20', '2024-10-19', '2025-01-17', '2025-07-21', '2027-07-21', '2029-07-20', '2034-07-19']
Will there be more than ten times as many 'Violence against civilians' in Montenegro for the 30 days before {resolution_date} compared to one plus the 30-day average of 'Violence against civilians' over the 360 days preceding {forecast_due_date}?

e.g. If the forecast due date is 2024-01-01 and we have the following data:
Date,'Violence against civilians'
2023-11-11,1
2023-10-10,2
to calculate one plus the 30-day average of 'Violence against civilians' over the preceding 360 days, we’d have: 1+(1+2)/12=1.25.

In this example, for the question to resolve positively, 13 (10 x 1.25) or more 'Violence against civilians' would need to occur in the 30 days leading up to the resolution.
['2024-07-28', '2024-08-20', '2024-10-19', '2025-01-17', '2025-07-21', '2027-07-21', '2029-07-20', '2034-07-19']
Will there be more than ten times as many 'Protests' in China for the 30 days before {resolution_date} compared to one plus the 30-day average of 'Protests' over the 360 days preceding {forecast_due_date}?

e.g. If the forecast due date is 2024-01-01 and we have the following data:
Date,'Protests'
2023-11-11,1
2023-10-10,2
to calculate one plus the 30-day average of 'Protests' over the preceding 360 days, we’d have: 1+(1+2)/12=1.25.

In this example, for the question to resolve positively, 13 (10 x 1.25) or more 'Protests' would need to occur in the 30 days leading up to the resolution.
['2024-07-28', '2024-08-20', '2024-10-19', '2025-01-17', '2025-07-21', '2027-07-21', '2029-07-20', '2034-07-19']
Will there be more than ten times as many 'Protests' in Bahrain for the 30 days before {resolution_date} compared to one plus the 30-day average of 'Protests' over the 360 days preceding {forecast_due_date}?

e.g. If the forecast due date is 2024-01-01 and we have the following data:
Date,'Protests'
2023-11-11,1
2023-10-10,2
to calculate one plus the 30-day average of 'Protests' over the preceding 360 days, we’d have: 1+(1+2)/12=1.25.

In this example, for the question to resolve positively, 13 (10 x 1.25) or more 'Protests' would need to occur in the 30 days leading up to the resolution.
['2024-07-28', '2024-08-20', '2024-10-19', '2025-01-17', '2025-07-21', '2027-07-21', '2029-07-20', '2034-07-19']
Will there be more 'Riots' in Poland for the 30 days before {resolution_date} compared to the 30-day average of 'Riots' over the 360 days preceding {forecast_due_date}?

e.g. If the forecast due date is 2024-01-01 and we have the following data:
Date,'Riots'
2023-11-11,1
2023-10-10,2
to calculate the 30-day average of 'Riots' over the preceding 360 days, we’d have: (1+2)/12=0.25.

In this example, for the question to resolve positively, 1 or more 'Riots' would need to occur in the 30 days leading up to the resolution.
['2024-07-28', '2024-08-20', '2024-10-19', '2025-01-17', '2025-07-21', '2027-07-21', '2029-07-20', '2034-07-19']
Will there be more than ten times as many 'Violence against civilians' in Afghanistan for the 30 days before {resolution_date} compared to one plus the 30-day average of 'Violence against civilians' over the 360 days preceding {forecast_due_date}?

e.g. If the forecast due date is 2024-01-01 and we have the following data:
Date,'Violence against civilians'
2023-11-11,1
2023-10-10,2
to calculate one plus the 30-day average of 'Violence against civilians' over the preceding 360 days, we’d have: 1+(1+2)/12=1.25.

In this example, for the question to resolve positively, 13 (10 x 1.25) or more 'Violence against civilians' would need to occur in the 30 days leading up to the resolution.
['2024-07-28', '2024-08-20', '2024-10-19', '2025-01-17', '2025-07-21', '2027-07-21', '2029-07-20', '2034-07-19']
Will there be more 'Explosions/Remote violence' in Norway for the 30 days before {resolution_date} compared to the 30-day average of 'Explosions/Remote violence' over the 360 days preceding {forecast_due_date}?

e.g. If the forecast due date is 2024-01-01 and we have the following data:
Date,'Explosions/Remote violence'
2023-11-11,1
2023-10-10,2
to calculate the 30-day average of 'Explosions/Remote violence' over the preceding 360 days, we’d have: (1+2)/12=0.25.

In this example, for the question to resolve positively, 1 or more 'Explosions/Remote violence' would need to occur in the 30 days leading up to the resolution.
['2024-07-28', '2024-08-20', '2024-10-19', '2025-01-17', '2025-07-21', '2027-07-21', '2029-07-20', '2034-07-19']
Will there be more than ten times as many 'Strategic developments' in Wallis and Futuna for the 30 days before {resolution_date} compared to one plus the 30-day average of 'Strategic developments' over the 360 days preceding {forecast_due_date}?

e.g. If the forecast due date is 2024-01-01 and we have the following data:
Date,'Strategic developments'
2023-11-11,1
2023-10-10,2
to calculate one plus the 30-day average of 'Strategic developments' over the preceding 360 days, we’d have: 1+(1+2)/12=1.25.

In this example, for the question to resolve positively, 13 (10 x 1.25) or more 'Strategic developments' would need to occur in the 30 days leading up to the resolution.
['2024-07-28', '2024-08-20', '2024-10-19', '2025-01-17', '2025-07-21', '2027-07-21', '2029-07-20', '2034-07-19']
Will there be more than ten times as many 'Battles' in Caribbean Netherlands for the 30 days before {resolution_date} compared to one plus the 30-day average of 'Battles' over the 360 days preceding {forecast_due_date}?

e.g. If the forecast due date is 2024-01-01 and we have the following data:
Date,'Battles'
2023-11-11,1
2023-10-10,2
to calculate one plus the 30-day average of 'Battles' over the preceding 360 days, we’d have: 1+(1+2)/12=1.25.

In this example, for the question to resolve positively, 13 (10 x 1.25) or more 'Battles' would need to occur in the 30 days leading up to the resolution.
['2024-07-28', '2024-08-20', '2024-10-19', '2025-01-17', '2025-07-21', '2027-07-21', '2029-07-20', '2034-07-19']
Will there be more than ten times as many 'Battles' in Iraq for the 30 days before {resolution_date} compared to one plus the 30-day average of 'Battles' over the 360 days preceding {forecast_due_date}?

e.g. If the forecast due date is 2024-01-01 and we have the following data:
Date,'Battles'
2023-11-11,1
2023-10-10,2
to calculate one plus the 30-day average of 'Battles' over the preceding 360 days, we’d have: 1+(1+2)/12=1.25.

In this example, for the question to resolve positively, 13 (10 x 1.25) or more 'Battles' would need to occur in the 30 days leading up to the resolution.
['2024-07-28', '2024-08-20', '2024-10-19', '2025-01-17', '2025-07-21', '2027-07-21', '2029-07-20', '2034-07-19']
Will there be more than ten times as many 'Strategic developments' in Uzbekistan for the 30 days before {resolution_date} compared to one plus the 30-day average of 'Strategic developments' over the 360 days preceding {forecast_due_date}?

e.g. If the forecast due date is 2024-01-01 and we have the following data:
Date,'Strategic developments'
2023-11-11,1
2023-10-10,2
to calculate one plus the 30-day average of 'Strategic developments' over the preceding 360 days, we’d have: 1+(1+2)/12=1.25.

In this example, for the question to resolve positively, 13 (10 x 1.25) or more 'Strategic developments' would need to occur in the 30 days leading up to the resolution.
['2024-07-28', '2024-08-20', '2024-10-19', '2025-01-17', '2025-07-21', '2027-07-21', '2029-07-20', '2034-07-19']
Will there be more 'Battles' in Laos for the 30 days before {resolution_date} compared to the 30-day average of 'Battles' over the 360 days preceding {forecast_due_date}?

e.g. If the forecast due date is 2024-01-01 and we have the following data:
Date,'Battles'
2023-11-11,1
2023-10-10,2
to calculate the 30-day average of 'Battles' over the preceding 360 days, we’d have: (1+2)/12=0.25.

In this example, for the question to resolve positively, 1 or more 'Battles' would need to occur in the 30 days leading up to the resolution.
['2024-07-28', '2024-08-20', '2024-10-19', '2025-01-17', '2025-07-21', '2027-07-21', '2029-07-20', '2034-07-19']
Will there be more than ten times as many fatalities in Ivory Coast for the 30 days before {resolution_date} compared to one plus the 30-day average of fatalities over the 360 days preceding {forecast_due_date}?

e.g. If the forecast due date is 2024-01-01 and we have the following data:
Date,fatalities
2023-11-11,1
2023-10-10,2
to calculate one plus the 30-day average of fatalities over the preceding 360 days, we’d have: 1+(1+2)/12=1.25.

In this example, for the question to resolve positively, 13 (10 x 1.25) or more fatalities would need to occur in the 30 days leading up to the resolution.
['2024-07-28', '2024-08-20', '2024-10-19', '2025-01-17', '2025-07-21', '2027-07-21', '2029-07-20', '2034-07-19']
Will there be more 'Strategic developments' in Angola for the 30 days before {resolution_date} compared to the 30-day average of 'Strategic developments' over the 360 days preceding {forecast_due_date}?

e.g. If the forecast due date is 2024-01-01 and we have the following data:
Date,'Strategic developments'
2023-11-11,1
2023-10-10,2
to calculate the 30-day average of 'Strategic developments' over the preceding 360 days, we’d have: (1+2)/12=0.25.

In this example, for the question to resolve positively, 1 or more 'Strategic developments' would need to occur in the 30 days leading up to the resolution.
['2024-07-28', '2024-08-20', '2024-10-19', '2025-01-17', '2025-07-21', '2027-07-21', '2029-07-20', '2034-07-19']
Will there be more than ten times as many 'Battles' in Andorra for the 30 days before {resolution_date} compared to one plus the 30-day average of 'Battles' over the 360 days preceding {forecast_due_date}?

e.g. If the forecast due date is 2024-01-01 and we have the following data:
Date,'Battles'
2023-11-11,1
2023-10-10,2
to calculate one plus the 30-day average of 'Battles' over the preceding 360 days, we’d have: 1+(1+2)/12=1.25.

In this example, for the question to resolve positively, 13 (10 x 1.25) or more 'Battles' would need to occur in the 30 days leading up to the resolution.
['2024-07-28', '2024-08-20', '2024-10-19', '2025-01-17', '2025-07-21', '2027-07-21', '2029-07-20', '2034-07-19']
Will there be more 'Violence against civilians' in Guadeloupe for the 30 days before {resolution_date} compared to the 30-day average of 'Violence against civilians' over the 360 days preceding {forecast_due_date}?

e.g. If the forecast due date is 2024-01-01 and we have the following data:
Date,'Violence against civilians'
2023-11-11,1
2023-10-10,2
to calculate the 30-day average of 'Violence against civilians' over the preceding 360 days, we’d have: (1+2)/12=0.25.

In this example, for the question to resolve positively, 1 or more 'Violence against civilians' would need to occur in the 30 days leading up to the resolution.

[{'meta_data': {'id': 'TPkEjiNb1wVCIGFnPcDD',
   'source': 'manifold',
   'question': 'Will the average global temperature in 2024 exceed 2023?',
   'resolution_criteria': 'Resolves to the outcome of the question found at https://manifold.markets/SteveRabin/will-the-average-global-temperature.',
   'background': '2023 is trending to be the hottest year on record.',
   'market_info_open_datetime': '2023-10-13T17:44:30+00:00',
   'market_info_close_datetime': '2025-01-01T04:59:00+00:00',
   'market_info_resolution_criteria': 'N/A',
   'url': 'https://manifold.markets/SteveRabin/will-the-average-global-temperature',
   'freeze_datetime': '2024-07-12T00:00:00+00:00',
   'freeze_datetime_value': '0.7565624485542961',
   'freeze_datetime_value_explanation': 'The market value.',
   'source_intro': "We would like you to predict the outcome of a prediction market. A prediction market, in this context, is the aggregate of predictions submitted by users on the website Manifold. You're going to predict the probability that the market will resolve as 'Yes'.",
   'combination_of': 'N/A',
   'resolution_dates': 'N/A'},
  'forecast_due_date': '2024-07-21',
  'question_set': '2024-07-21-human.json'},
 {'meta_data': {'id': 'KCFbp1TH0RYN4j5zYdmh',
   'source': 'manifold',
   'question': 'Will any event of the Paris 2024 Olympic Games be postponed or cancelled due to the water quality of the Seine?',
   'resolution_criteria': 'Resolves to the outcome of the question found at https://manifold.markets/Pob/will-any-event-of-the-paris-2024-ol.',
   'background': 'It also counts as YES if an event is moved to a venue other than the Seine river ahead of time because of water quality concerns.\n\nBackground:\n\nSeine River events scrapped again, renewing doubts over Paris Olympics plan\n\nParis Olympics promises Seine clean-up after pollution spoils triathlon | Financial Times',
   'market_info_open_datetime': '2023-08-25T19:59:35+00:00',
   'market_info_close_datetime': '2024-08-11T21:59:00+00:00',
   'market_info_resolution_criteria': 'N/A',
   'url': 'https://manifold.markets/Pob/will-any-event-of-the-paris-2024-ol',
   'freeze_datetime': '2024-07-12T00:00:00+00:00',
   'freeze_datetime_value': '0.6458942140911571',
   'freeze_datetime_value_explanation': 'The market value.',
   'source_intro': "We would like you to predict the outcome of a prediction market. A prediction market, in this context, is the aggregate of predictions submitted by users on the website Manifold. You're going to predict the probability that the market will resolve as 'Yes'.",
   'combination_of': 'N/A',
   'resolution_dates': 'N/A'},
  'forecast_due_date': '2024-07-21',
  'question_set': '2024-07-21-human.json'},
 {'meta_data': {'id': 'q6wJThcy6TJnQKrbjALm',
   'source': 'manifold',
   'question': 'Will the majority of new cars sold be electric vehicles by the end of 2030?',
   'resolution_criteria': 'Resolves to the outcome of the question found at https://manifold.markets/TobiasSowaaed/will-the-majority-of-new-cars-sold-c4d566afc8c7.',
   'background': "Majority is 50%+ and it's worldwide marketshare",
   'market_info_open_datetime': '2023-09-01T23:59:55+00:00',
   'market_info_close_datetime': '2030-12-31T22:59:00+00:00',
   'market_info_resolution_criteria': 'N/A',
   'url': 'https://manifold.markets/TobiasSowaaed/will-the-majority-of-new-cars-sold-c4d566afc8c7',
   'freeze_datetime': '2024-07-12T00:00:00+00:00',
   'freeze_datetime_value': '0.6912524093033491',
   'freeze_datetime_value_explanation': 'The market value.',
   'source_intro': "We would like you to predict the outcome of a prediction market. A prediction market, in this context, is the aggregate of predictions submitted by users on the website Manifold. You're going to predict the probability that the market will resolve as 'Yes'.",
   'combination_of': 'N/A',
   'resolution_dates': 'N/A'},
  'forecast_due_date': '2024-07-21',
  'question_set': '2024-07-21-human.json'},
 {'meta_data': {'id': 'cLxfTH5GDfmqeNJwClVF',
   'source': 'manifold',
   'question': 'Will the majority of new cars sold worldwide be electric before the end of 2030?',
   'resolution_criteria': 'Resolves to the outcome of the question found at https://manifold.markets/kian_spire/will-the-majority-of-new-cars-sold.',
   'background': 'This question will resolve as YES if more than 50% of new cars sold worldwide in the year 2030 are electric. \n\nThe source for determining the percentage of electric cars sold will be the International Energy Agency (IEA) annual report on electric vehicles. The report will be released in 2031 and will provide data on the percentage of electric cars sold in 2030. This question does not include hybrid cars, only fully electric cars.\n\nThe question does not consider any potential changes in regulations or government policies that may affect the sales of electric cars.\n\nThis question does not consider any potential changes in consumer behavior or technology development that may affect the sales of electric cars.',
   'market_info_open_datetime': '2023-04-21T20:36:16+00:00',
   'market_info_close_datetime': '2030-12-31T22:59:00+00:00',
   'market_info_resolution_criteria': 'N/A',
   'url': 'https://manifold.markets/kian_spire/will-the-majority-of-new-cars-sold',
   'freeze_datetime': '2024-07-12T00:00:00+00:00',
   'freeze_datetime_value': '0.659999999999999',
   'freeze_datetime_value_explanation': 'The market value.',
   'source_intro': "We would like you to predict the outcome of a prediction market. A prediction market, in this context, is the aggregate of predictions submitted by users on the website Manifold. You're going to predict the probability that the market will resolve as 'Yes'.",
   'combination_of': 'N/A',
   'resolution_dates': 'N/A'},
  'forecast_due_date': '2024-07-21',
  'question_set': '2024-07-21-human.json'},
 {'meta_data': {'id': 'ygVTjZRGDZvp0EQJ1L53',
   'source': 'manifold',
   'question': 'Will sports betting be legal in California and Texas by 2030?',
   'resolution_criteria': 'Resolves to the outcome of the question found at https://manifold.markets/10thOfficial/will-sports-betting-be-legal-in-cal.',
   'background': 'Must be able to place both an in-person and online sports bet legally in each state on January 1, 2030.',
   'market_info_open_datetime': '2024-01-05T22:00:15+00:00',
   'market_info_close_datetime': '2030-01-01T04:59:00+00:00',
   'market_info_resolution_criteria': 'N/A',
   'url': 'https://manifold.markets/10thOfficial/will-sports-betting-be-legal-in-cal',
   'freeze_datetime': '2024-07-12T00:00:00+00:00',
   'freeze_datetime_value': '0.805330724795234',
   'freeze_datetime_value_explanation': 'The market value.',
   'source_intro': "We would like you to predict the outcome of a prediction market. A prediction market, in this context, is the aggregate of predictions submitted by users on the website Manifold. You're going to predict the probability that the market will resolve as 'Yes'.",
   'combination_of': 'N/A',
   'resolution_dates': 'N/A'},
  'forecast_due_date': '2024-07-21',
  'question_set': '2024-07-21-human.json'},
 {'meta_data': {'id': 'yfyPBZNkCMZiffCyICSj',
   'source': 'manifold',
   'question': '👍👎 Manifold Leadership Approval Rating [Market Index]',
   'resolution_criteria': 'Resolves to the outcome of the question found at https://manifold.markets/strutheo/manifold-leadership-approval-rating.',
   'background': "Use mana to let the team know what you think about how they're running the website. 100% means everyone is happy with the direction Manifold is going and the team behind it, and 0% means something has probably gone tragically wrong. \n\nDoes not impact profit rankings\n\nPermanently open market, will not resolve.\n\nOther Approval Ratings:\n\n@/strutheo/what-will-manifolds-approval-rating \n\n@/strutheo/what-will-manifolds-approval-rating-69a6850abbfb \n\n@/strutheo/what-will-manifolds-approval-rating-d7689b01293f \n\n@/strutheo/what-will-manifolds-approval-rating-da311ac4ea95 ",
   'market_info_open_datetime': '2024-01-11T05:36:02+00:00',
   'market_info_close_datetime': '2525-01-01T05:00:00+00:00',
   'market_info_resolution_criteria': 'N/A',
   'url': 'https://manifold.markets/strutheo/manifold-leadership-approval-rating',
   'freeze_datetime': '2024-07-12T00:00:00+00:00',
   'freeze_datetime_value': '0.37336912312159404',
   'freeze_datetime_value_explanation': 'The market value.',
   'source_intro': "We would like you to predict the outcome of a prediction market. A prediction market, in this context, is the aggregate of predictions submitted by users on the website Manifold. You're going to predict the probability that the market will resolve as 'Yes'.",
   'combination_of': 'N/A',
   'resolution_dates': 'N/A'},
  'forecast_due_date': '2024-07-21',
  'question_set': '2024-07-21-human.json'},
 {'meta_data': {'id': 'lFx5LHHUTgHnQPquiOMs',
   'source': 'manifold',
   'question': 'Will Rafael Nadal win another Grand Slam before his retirement?',
   'resolution_criteria': 'Resolves to the outcome of the question found at https://manifold.markets/_deleted_/will-rafael-nadal-win-another-grand.',
   'background': 'Start date: Feb 7, end date: Rafa retires.\n\nWill he win a GS again? \n\nI hope he does. Will update the close date if required.\n\nIf Rafa retires and comes out of retirement to win a GS, that doesnt count.',
   'market_info_open_datetime': '2023-02-07T05:46:17+00:00',
   'market_info_close_datetime': '2024-12-01T18:29:00+00:00',
   'market_info_resolution_criteria': 'N/A',
   'url': 'https://manifold.markets/_deleted_/will-rafael-nadal-win-another-grand',
   'freeze_datetime': '2024-07-12T00:00:00+00:00',
   'freeze_datetime_value': '0.05936166927615501',
   'freeze_datetime_value_explanation': 'The market value.',
   'source_intro': "We would like you to predict the outcome of a prediction market. A prediction market, in this context, is the aggregate of predictions submitted by users on the website Manifold. You're going to predict the probability that the market will resolve as 'Yes'.",
   'combination_of': 'N/A',
   'resolution_dates': 'N/A'},
  'forecast_due_date': '2024-07-21',
  'question_set': '2024-07-21-human.json'},
 {'meta_data': {'id': 'YulPWDHFTUkekmrO3v4J',
   'source': 'manifold',
   'question': '[2024 Formula 1 Season] Will Oscar Piastri or Daniel Ricciardo win a race?',
   'resolution_criteria': 'Resolves to the outcome of the question found at https://manifold.markets/Arch1e/2024-formula-1-season-will-oscar-pi.',
   'background': '[THIS IS FOR THE 2024 SEASON]\n\nResolves YES if either Oscar Piastri or Daniel Ricciardo win a race during the 2024 season, not including sprints.\n\nThis includes victories from promotions due to penalties. For example if Max Verstappen won a race, but was disqualified or otherwise penalised down the finishing order, so that either Oscar Piastri or Daniel Ricciardo is promoted to 1st, the market would resolve YES.',
   'market_info_open_datetime': '2023-11-23T16:43:40+00:00',
   'market_info_close_datetime': '2024-12-09T23:59:00+00:00',
   'market_info_resolution_criteria': 'N/A',
   'url': 'https://manifold.markets/Arch1e/2024-formula-1-season-will-oscar-pi',
   'freeze_datetime': '2024-07-12T00:00:00+00:00',
   'freeze_datetime_value': '0.39330923026596104',
   'freeze_datetime_value_explanation': 'The market value.',
   'source_intro': "We would like you to predict the outcome of a prediction market. A prediction market, in this context, is the aggregate of predictions submitted by users on the website Manifold. You're going to predict the probability that the market will resolve as 'Yes'.",
   'combination_of': 'N/A',
   'resolution_dates': 'N/A'},
  'forecast_due_date': '2024-07-21',
  'question_set': '2024-07-21-human.json'},
 {'meta_data': {'id': 'iPG19DGNrWEkbUBjfk6L',
   'source': 'manifold',
   'question': 'Will Ding Liren repeat as World Chess Champion?',
   'resolution_criteria': 'Resolves to the outcome of the question found at https://manifold.markets/AlexLiesman/will-ding-liren-repeat-as-world-che.',
   'background': 'Yes if he successfully defends his title\n\nNo if he does not',
   'market_info_open_datetime': '2023-04-30T15:51:51+00:00',
   'market_info_close_datetime': '2025-05-02T03:59:00+00:00',
   'market_info_resolution_criteria': 'N/A',
   'url': 'https://manifold.markets/AlexLiesman/will-ding-liren-repeat-as-world-che',
   'freeze_datetime': '2024-07-12T00:00:00+00:00',
   'freeze_datetime_value': '0.23113899627783702',
   'freeze_datetime_value_explanation': 'The market value.',
   'source_intro': "We would like you to predict the outcome of a prediction market. A prediction market, in this context, is the aggregate of predictions submitted by users on the website Manifold. You're going to predict the probability that the market will resolve as 'Yes'.",
   'combination_of': 'N/A',
   'resolution_dates': 'N/A'},
  'forecast_due_date': '2024-07-21',
  'question_set': '2024-07-21-human.json'},
 {'meta_data': {'id': '2ZLAoe3EAFVhcFAXXfPp',
   'source': 'manifold',
   'question': 'Will Lionel Messi retire before the end of 2024?',
   'resolution_criteria': 'Resolves to the outcome of the question found at https://manifold.markets/AmmonLam/will-lionel-messi-retire-before-the-e18f65f54b65.',
   'background': 'Argentina skipper Lionel Messi denied rumours of his retirement post the World Cup win against France, saying he wishes to keep playing for his country.\n\n(https://sportstar.thehindu.com/football/fifa-world-cup/news/messi-argentina-no-plan-to-retire-arg-vs-fra-world-cup-final-qatar-wc-2022/article66279720.ece#:~:text=for%20his%20country.-,Argentina%20skipper%20Lionel%20Messi%20denied%20rumours%20of%20his%20retirement%20post,TyC%20Sports%20after%20the%20match.)',
   'market_info_open_datetime': '2022-12-19T18:26:39+00:00',
   'market_info_close_datetime': '2025-01-01T04:59:00+00:00',
   'market_info_resolution_criteria': 'N/A',
   'url': 'https://manifold.markets/AmmonLam/will-lionel-messi-retire-before-the-e18f65f54b65',
   'freeze_datetime': '2024-07-12T00:00:00+00:00',
   'freeze_datetime_value': '0.150783373650064',
   'freeze_datetime_value_explanation': 'The market value.',
   'source_intro': "We would like you to predict the outcome of a prediction market. A prediction market, in this context, is the aggregate of predictions submitted by users on the website Manifold. You're going to predict the probability that the market will resolve as 'Yes'.",
   'combination_of': 'N/A',
   'resolution_dates': 'N/A'},
  'forecast_due_date': '2024-07-21',
  'question_set': '2024-07-21-human.json'},
 {'meta_data': {'id': 'taYZcNp99aWqZLI2nq9v',
   'source': 'manifold',
   'question': "Will Rational Animations' video about Manifold Markets reach 200k views by the end of 2024?",
   'resolution_criteria': 'Resolves to the outcome of the question found at https://manifold.markets/Writer/will-rational-animations-second-vid.',
   'background': "Here's the video: https://youtu.be/DB5TfX7eaVY",
   'market_info_open_datetime': '2023-07-15T14:13:41+00:00',
   'market_info_close_datetime': '2024-12-31T22:59:00+00:00',
   'market_info_resolution_criteria': 'N/A',
   'url': 'https://manifold.markets/Writer/will-rational-animations-second-vid',
   'freeze_datetime': '2024-07-12T00:00:00+00:00',
   'freeze_datetime_value': '0.08449267461328801',
   'freeze_datetime_value_explanation': 'The market value.',
   'source_intro': "We would like you to predict the outcome of a prediction market. A prediction market, in this context, is the aggregate of predictions submitted by users on the website Manifold. You're going to predict the probability that the market will resolve as 'Yes'.",
   'combination_of': 'N/A',
   'resolution_dates': 'N/A'},
  'forecast_due_date': '2024-07-21',
  'question_set': '2024-07-21-human.json'},
 {'meta_data': {'id': '0yVJeShTMcm0FA8UrcCL',
   'source': 'manifold',
   'question': 'Will over 70% of Manifold users think that Elon Musk does not deserve 100 billion dollars?',
   'resolution_criteria': 'Resolves to the outcome of the question found at https://manifold.markets/AmmonLam/will-over-70-of-manifold-users-thin.',
   'background': 'Resolves according to this poll\n\n(https://manifold.markets/embed/KeenenWatts/does-elon-musk-deserve-100-billion)\nTake the total vote on "No", divided by the total number of voters on the market, to compute the % voted on "No".\n\nMarket Resolves Yes if the % voted on "No" is larger than 70% at the end of 2024',
   'market_info_open_datetime': '2024-02-28T21:04:17+00:00',
   'market_info_close_datetime': '2025-01-01T04:59:00+00:00',
   'market_info_resolution_criteria': 'N/A',
   'url': 'https://manifold.markets/AmmonLam/will-over-70-of-manifold-users-thin',
   'freeze_datetime': '2024-07-12T00:00:00+00:00',
   'freeze_datetime_value': '0.582435851164092',
   'freeze_datetime_value_explanation': 'The market value.',
   'source_intro': "We would like you to predict the outcome of a prediction market. A prediction market, in this context, is the aggregate of predictions submitted by users on the website Manifold. You're going to predict the probability that the market will resolve as 'Yes'.",
   'combination_of': 'N/A',
   'resolution_dates': 'N/A'},
  'forecast_due_date': '2024-07-21',
  'question_set': '2024-07-21-human.json'},
 {'meta_data': {'id': 'VB1RhUVlnNfhclAh4LvR',
   'source': 'manifold',
   'question': "Will the U.S. win the gold medal in the Men's Basketball at the 2024 Summer Olympics in Paris?",
   'resolution_criteria': 'Resolves to the outcome of the question found at https://manifold.markets/Tripping/will-the-us-win-the-gold-medal-in-t.',
   'background': 'Not the 3x3 basketball, the regular basketball. ',
   'market_info_open_datetime': '2023-03-16T10:46:01+00:00',
   'market_info_close_datetime': '2024-08-13T13:30:00+00:00',
   'market_info_resolution_criteria': 'N/A',
   'url': 'https://manifold.markets/Tripping/will-the-us-win-the-gold-medal-in-t',
   'freeze_datetime': '2024-07-12T00:00:00+00:00',
   'freeze_datetime_value': '0.8794534364540151',
   'freeze_datetime_value_explanation': 'The market value.',
   'source_intro': "We would like you to predict the outcome of a prediction market. A prediction market, in this context, is the aggregate of predictions submitted by users on the website Manifold. You're going to predict the probability that the market will resolve as 'Yes'.",
   'combination_of': 'N/A',
   'resolution_dates': 'N/A'},
  'forecast_due_date': '2024-07-21',
  'question_set': '2024-07-21-human.json'},
 {'meta_data': {'id': 'QHFQmCmz8HplpN2QQnl2',
   'source': 'manifold',
   'question': 'Will England win the 2026 FIFA World Cup?',
   'resolution_criteria': 'Resolves to the outcome of the question found at https://manifold.markets/UniversalFC/will-england-win-the-2026-fifa-worl.',
   'background': '',
   'market_info_open_datetime': '2023-08-06T14:25:16+00:00',
   'market_info_close_datetime': '2026-07-20T03:59:00+00:00',
   'market_info_resolution_criteria': 'N/A',
   'url': 'https://manifold.markets/UniversalFC/will-england-win-the-2026-fifa-worl',
   'freeze_datetime': '2024-07-12T00:00:00+00:00',
   'freeze_datetime_value': '0.10466896746962401',
   'freeze_datetime_value_explanation': 'The market value.',
   'source_intro': "We would like you to predict the outcome of a prediction market. A prediction market, in this context, is the aggregate of predictions submitted by users on the website Manifold. You're going to predict the probability that the market will resolve as 'Yes'.",
   'combination_of': 'N/A',
   'resolution_dates': 'N/A'},
  'forecast_due_date': '2024-07-21',
  'question_set': '2024-07-21-human.json'},
 {'meta_data': {'id': '0m2HGw8Pd4ZTIgga0Pzv',
   'source': 'manifold',
   'question': '[2024 Formula 1 Season] Will Sergio Perez finish 2nd or higher in the Drivers Championship?',

In [38]:
pd.DataFrame(questions_and_meta_data)

,meta_data,forecast_due_date,question_set,question
0,"{'id': 'TPkEjiNb1wVCIGFnPcDD', 'source': 'manifold', 'question': 'Will the average global temperature in 2024 exceed 2023?', 'resolution_criteria': 'Resolves to the outcome of the question found at https://manifold.markets/SteveRabin/will-the-average-global-temperature.', 'background': '2023 is trending to be the hottest year on record.', 'market_info_open_datetime': '2023-10-13T17:44:30+00:00', 'market_info_close_datetime': '2025-01-01T04:59:00+00:00', 'market_info_resolution_criteria': 'N/A', 'url': 'https://manifold.markets/SteveRabin/will-the-average-global-temperature', 'freeze_datetime': '2024-07-12T00:00:00+00:00', 'freeze_datetime_value': '0.7565624485542961', 'freeze_datetime_value_explanation': 'The market value.', 'source_intro': 'We would like you to predict the outcome of ...",2024-07-21,2024-07-21-human.json,NaN
1,"{'id': 'KCFbp1TH0RYN4j5zYdmh', 'source': 'manifold', 'question': 'Will any event of the Paris 2024 Olympic Games be postponed or cancelled due to the water quality of the Seine?', 'resolution_criteria': 'Resolves to the outcome of the question found at https://manifold.markets/Pob/will-any-event-of-the-paris-2024-ol.', 'background': 'It also counts as YES if an event is moved to a venue other than the Seine river ahead of time because of water quality concerns. Background: Seine River events scrapped again, renewing doubts over Paris Olympics plan Paris Olympics promises Seine clean-up after pollution spoils triathlon | Financial Times', 'market_info_open_datetime': '2023-08-25T19:59:35+00:00', 'market_info_close_datetime': '2024-08-11T21:59:00+00:00', 'market_info_resolution_criter...",2024-07-21,2024-07-21-human.json,NaN
2,"{'id': 'q6wJThcy6TJnQKrbjALm', 'source': 'manifold', 'question': 'Will the majority of new cars sold be electric vehicles by the end of 2030?', 'resolution_criteria': 'Resolves to the outcome of the question found at https://manifold.markets/TobiasSowaaed/will-the-majority-of-new-cars-sold-c4d566afc8c7.', 'background': 'Majority is 50%+ and it's worldwide marketshare', 'market_info_open_datetime': '2023-09-01T23:59:55+00:00', 'market_info_close_datetime': '2030-12-31T22:59:00+00:00', 'market_info_resolution_criteria': 'N/A', 'url': 'https://manifold.markets/TobiasSowaaed/will-the-majority-of-new-cars-sold-c4d566afc8c7', 'freeze_datetime': '2024-07-12T00:00:00+00:00', 'freeze_datetime_value': '0.6912524093033491', 'freeze_datetime_value_explanation': 'The market value.', 'source_intro':...",2024-07-21,2024-07-21-human.json,NaN
3,"{'id': 'cLxfTH5GDfmqeNJwClVF', 'source': 'manifold', 'question': 'Will the majority of new cars sold worldwide be electric before the end of 2030?', 'resolution_criteria': 'Resolves to the outcome of the question found at https://manifold.markets/kian_spire/will-the-majority-of-new-cars-sold.', 'background': 'This question will resolve as YES if more than 50% of new cars sold worldwide in the year 2030 are electric. The source for determining the percentage of electric cars sold will be the International Energy Agency (IEA) annual report on electric vehicles. The report will be released in 2031 and will provide data on the percentage of electric cars sold in 2030. This question does not include hybrid cars, only fully electric cars. The question does not consider any potential chang...",2024-07-21,2024-07-21-human.json,NaN
4,"{'id': 'ygVTjZRGDZvp0EQJ1L53', 'source': 'manifold', 'question': 'Will sports betting be legal in California and Texas by 2030?', 'resolution_criteria': 'Resolves to the outcome of the question found at https://manifold.markets/10thOfficial/will-sports-betting-be-legal-in-cal.', 'background': 'Must be able to place both an in-person and online sports bet legally in each state on January 1, 2030.', 'market_info_open_datetime': '2024-01-05T22:00:15+00:00', 'market_info_close_datetime': '2030-01-01T04:59:00+00:00', 'market_info_resolution_criteria': 'N/A', 'url': 'https://manifold.markets/10thOfficial/will-sports-betting-be-legal-in-cal', 'freeze_datetime': '2024-07-12T00:00:00+00:00', 'freeze_datetime_value': '0.805330724795234', 'freeze_datetime_value_explanation': 'The market value.', ...",2024-07-21,2024-07-21-human.json,NaN
...,...,...,...,...
195,NaN,NaN,NaN,Will HUM's market close price on 2024-07-28 be higher than its market close price on {forecast_due_date}?\n\nStock splits and reverse splits will be accounted for in resolving this question. Forecasts on questions about companies that have been delisted (through mergers or bankruptcy) will resolve to their final close price.
196,NaN,NaN,NaN,Will CBRE's market close price on 2024-07-28 be higher than its market close price on {forecast_due_date}?\n\nStock splits and reverse splits will be accounted for in resolving this question. Forecasts on questions about companies that have been delisted (through mergers or bankruptcy) will resolve to their final close price.
197,NaN,NaN,NaN,Will TPR's market close price on 2024-07-28 be higher than its market close price on {forecast_due_date}?\n\nStock splits and reverse splits will be accounted for in resolving this question. Forecasts on questions about companies that have been delisted (through mergers or bankruptcy) will resolve to their final close price.
198,NaN,NaN,NaN,Will CCL's market close price on 2024-07-28 be higher than its market close price on {forecast_due_date}?\n\nStock splits and reverse splits will be accounted for in resolving this question. Forecasts on questions about companies that have been delisted (through mergers or bankruptcy) will resolve to their final close price.
199,NaN,NaN,NaN,Will FFIV's market close price on 2024-07-28 be higher than its market close price on {forecast_due_date}?\n\nStock splits and reverse splits will be accounted for in resolving this question. Forecasts on questions about companies that have been delisted (through mergers or bankruptcy) will resolve to their final close price.