# Explore Datasets

In [1]:
import os
import sys

import pandas as pd

notebook_dir = os.getcwd()

sys.path.append(os.path.join(notebook_dir, '../'))

from data_processing import DataProcessing
from feature_extraction import SpacyFeatureExtraction

In [2]:
pd.set_option('max_colwidth', 800)
# pd.set_option('display.max_columns', None)
# pd.set_option('display.max_columns', 40)
# pd.set_option('display.max_rows', None)

## Load Data

In [3]:
# dataset_path = os.path.join(notebook_dir, '../data/combined_datasets/july_2026_results/july_2026_results.csv')

dataset_path = os.path.join(notebook_dir, '../data/combined_datasets/naacl_2026_submission/naacl_2026_submission.csv')
df = DataProcessing.load_from_file(dataset_path)
df

,Base Sentence,Ground Truth,Dataset Name
0,"Sebastian, a financial analyst forecasts that the stock price at Apple will decrease in 2027 Q3.",1,synthetic
1,"On August 22, 2024, Goldman Sachs speculates that the operating cash flow at Amazon will likely increase.",1,synthetic
2,"Citigroup predicts on September 15, 2026, the S&P 500 index could climb moderately.",1,synthetic
3,"According to Morgan Stanley, the projected revenue at Alphabet Inc. should fall in Q2 2028.",1,synthetic
4,"In 2029 Q4, David envisions that the dividend yield in Microsoft could stay stable.",1,synthetic
...,...,...,...
26193,Will FFIV's market close price on 2025-01-17 be higher than its market close price on 2024-07-21?\n\nStock splits and reverse splits will be accounted for in resolving this question. Forecasts on questions about companies that have been delisted (through mergers or bankruptcy) will resolve to their final close price.,1,forecast_bench
26194,Will FFIV's market close price on 2025-07-21 be higher than its market close price on 2024-07-21?\n\nStock splits and reverse splits will be accounted for in resolving this question. Forecasts on questions about companies that have been delisted (through mergers or bankruptcy) will resolve to their final close price.,1,forecast_bench
26195,Will FFIV's market close price on 2027-07-21 be higher than its market close price on 2024-07-21?\n\nStock splits and reverse splits will be accounted for in resolving this question. Forecasts on questions about companies that have been delisted (through mergers or bankruptcy) will resolve to their final close price.,1,forecast_bench
26196,Will FFIV's market close price on 2029-07-20 be higher than its market close price on 2024-07-21?\n\nStock splits and reverse splits will be accounted for in resolving this question. Forecasts on questions about companies that have been delisted (through mergers or bankruptcy) will resolve to their final close price.,1,forecast_bench
26197,Will FFIV's market close price on 2034-07-19 be higher than its market close price on 2024-07-21?\n\nStock splits and reverse splits will be accounted for in resolving this question. Forecasts on questions about companies that have been delisted (through mergers or bankruptcy) will resolve to their final close price.,1,forecast_bench

In [17]:
filt_sent = df['Base Sentence'] == "These pandemic products are a window into what we went through this year."
df[filt_sent]

Empty DataFrame
Columns: [Base Sentence, Ground Truth, Dataset Name]
Index: []

In [4]:
filt_gt = (df['Ground Truth'] == 1)
df = df[filt_gt]
df

,Base Sentence,Ground Truth,Dataset Name
0,"Sebastian, a financial analyst forecasts that the stock price at Apple will decrease in 2027 Q3.",1,synthetic
1,"On August 22, 2024, Goldman Sachs speculates that the operating cash flow at Amazon will likely increase.",1,synthetic
2,"Citigroup predicts on September 15, 2026, the S&P 500 index could climb moderately.",1,synthetic
3,"According to Morgan Stanley, the projected revenue at Alphabet Inc. should fall in Q2 2028.",1,synthetic
4,"In 2029 Q4, David envisions that the dividend yield in Microsoft could stay stable.",1,synthetic
...,...,...,...
26193,Will FFIV's market close price on 2025-01-17 be higher than its market close price on 2024-07-21?\n\nStock splits and reverse splits will be accounted for in resolving this question. Forecasts on questions about companies that have been delisted (through mergers or bankruptcy) will resolve to their final close price.,1,forecast_bench
26194,Will FFIV's market close price on 2025-07-21 be higher than its market close price on 2024-07-21?\n\nStock splits and reverse splits will be accounted for in resolving this question. Forecasts on questions about companies that have been delisted (through mergers or bankruptcy) will resolve to their final close price.,1,forecast_bench
26195,Will FFIV's market close price on 2027-07-21 be higher than its market close price on 2024-07-21?\n\nStock splits and reverse splits will be accounted for in resolving this question. Forecasts on questions about companies that have been delisted (through mergers or bankruptcy) will resolve to their final close price.,1,forecast_bench
26196,Will FFIV's market close price on 2029-07-20 be higher than its market close price on 2024-07-21?\n\nStock splits and reverse splits will be accounted for in resolving this question. Forecasts on questions about companies that have been delisted (through mergers or bankruptcy) will resolve to their final close price.,1,forecast_bench
26197,Will FFIV's market close price on 2034-07-19 be higher than its market close price on 2024-07-21?\n\nStock splits and reverse splits will be accounted for in resolving this question. Forecasts on questions about companies that have been delisted (through mergers or bankruptcy) will resolve to their final close price.,1,forecast_bench

In [16]:
filt_sent = df['Base Sentence'] == "These pandemic products are a window into what we went through this year."
df[filt_sent]

Empty DataFrame
Columns: [Base Sentence, Ground Truth, Dataset Name]
Index: []

## Search Data using Keywords

In [5]:
import pandas as pd

ex_df = pd.DataFrame({
    'name': ['sireesha', 'priyank', 'ojaswi', 'gnanesh'],
    'subjects': ['java is good', 'networks', 'c', 'c#']
})

words = ['java', 'c']

pattern = '|'.join(words)
result = ex_df[ex_df['subjects'].str.contains(pattern, na=False)]

print(result)

       name      subjects
0  sireesha  java is good
2    ojaswi             c
3   gnanesh            c#

In [6]:
# words = ['predicts', 'will']
# words = ['predict', 'forecasts', 'expects', 'projects']
words = ['predict', 'forecasts', 'expects', 'projects', 'predicted', 'forecasted', 'expected', 'projected', 'anticipated', 'speculates', 'envisions']
pattern = '|'.join(words)
print(pattern)

predict|forecasts|expects|projects|predicted|forecasted|expected|projected|anticipated|speculates|envisions

In [7]:
filt_word = (df['Base Sentence'].str.contains(pattern, na=False) == False)
filt_word_df = df[filt_word]
filt_word_df

,Base Sentence,Ground Truth,Dataset Name
5,"Google stock price will decrease in December 2026, according to Marcus.",1,synthetic
9,"According to Wells Fargo, the net profit margin at ExxonMobil would fall in 21 August 2024.",1,synthetic
11,"Apple stock price should stay the same in 21 Aug 2024, according to Bank of America.",1,synthetic
15,"According to the Centers for Disease Control and Prevention, the average blood pressure levels at the state level would fall in Q2 2030.",1,synthetic
17,"Vitamin D levels among office workers should stay same in 2028, according to Dr. Jane Thompson study.",1,synthetic
...,...,...,...
26193,Will FFIV's market close price on 2025-01-17 be higher than its market close price on 2024-07-21?\n\nStock splits and reverse splits will be accounted for in resolving this question. Forecasts on questions about companies that have been delisted (through mergers or bankruptcy) will resolve to their final close price.,1,forecast_bench
26194,Will FFIV's market close price on 2025-07-21 be higher than its market close price on 2024-07-21?\n\nStock splits and reverse splits will be accounted for in resolving this question. Forecasts on questions about companies that have been delisted (through mergers or bankruptcy) will resolve to their final close price.,1,forecast_bench
26195,Will FFIV's market close price on 2027-07-21 be higher than its market close price on 2024-07-21?\n\nStock splits and reverse splits will be accounted for in resolving this question. Forecasts on questions about companies that have been delisted (through mergers or bankruptcy) will resolve to their final close price.,1,forecast_bench
26196,Will FFIV's market close price on 2029-07-20 be higher than its market close price on 2024-07-21?\n\nStock splits and reverse splits will be accounted for in resolving this question. Forecasts on questions about companies that have been delisted (through mergers or bankruptcy) will resolve to their final close price.,1,forecast_bench
26197,Will FFIV's market close price on 2034-07-19 be higher than its market close price on 2024-07-21?\n\nStock splits and reverse splits will be accounted for in resolving this question. Forecasts on questions about companies that have been delisted (through mergers or bankruptcy) will resolve to their final close price.,1,forecast_bench

In [8]:
filt_word_df.groupby(['Dataset Name']).size()

Dataset Name
chronicle2050             957
clients_rivals_rouges       6
financial_phrasebank      329
forecast_bench            961
mf_climate                105
news_api                  375
synthetic                1505
timebank                  491
yt                        988
dtype: int64

## Extract POS

In [9]:
df = filt_word_df[filt_word_df['Dataset Name'] == 'yt']
df

,Base Sentence,Ground Truth,Dataset Name
20077,"And Barcelona is going to beat Boto Glimt in a game, once again, that is going to be much tighter than people think.",1,yt
20078,"And enter the minute of the goal scored in the final, which I think will be 23rd minute.",1,yt
20079,"And if they play like that away against Liverpool, Liverpool will make them pay.",1,yt
20080,"And in the final, I think we'll see a goal two minutes into the match.",1,yt
20081,And the champion for me will be Bayern Munich.,1,yt
...,...,...,...
21079,So here's favored by three and a half to six and a half point in the Super Bowl.,1,yt
21080,"So, personally, I mean, I don't want to go out on a limb, but I'm going to go, you know, 33-13.",1,yt
21081,"Sports Rage, Gabe Berenzi says the Seattle Seahawks win.",1,yt
21082,The Seattle Seahawks are going to do their thing.,1,yt
21083,We've got a 23-point win over there for Connor and a four-point win for the Patriots by Ty.,1,yt

In [10]:
df = filt_word_df[filt_word_df['Dataset Name'] == 'news_api']
df

,Base Sentence,Ground Truth,Dataset Name
21084,"Otherwise, they could risk seeing his value drop further if he takes another step back in 2026.",1,news_api
21085,"Tucker might never be well-rounded enough to be an NFL starter, but his high-effort pass rush can earn him a subpackage role.",1,news_api
21086,His pass-catching ability and contributions as a kick returner could help separate him at the back end of an NFL running back depth chart.,1,news_api
21087,"He's started a significant amount of games, with 60 in 63 appearances, so his value could increase as he continues to adjust to the league and to the team.",1,news_api
21088,His injury history is a serious concern heading into the NFL Draft and could lead teams to pass on him.,1,news_api
...,...,...,...
21601,Municipalities could only increase their budget by either 3% or the Midwest Consumer Price Index.,1,news_api
21602,It comes after the Ohio Redistricting Commission adopted a new congressional map that could boost Republican chances in districts currently held by Democratic Reps. Greg Landsman in Cincinnati and Marcy Kaptur near Toledo.Dates to KnowApril 6: Deadline to register to vote in Primary ElectionMay 5: Primary ElectionOct.,1,news_api
21603,"Notably, DeSantis has urged lawmakers to anticipate a judicial ruling from the U.S. Supreme Court, potentially on Friday, that could upend decades of precedent on interpretation of the Voting Rights Act of 1965.",1,news_api
21604,"""Florida's first hyperscale data center could be thwarted by new water rule"" via Romy Ellenbogen and Emily L. Mahoney of the Tampa Bay Times -- A real estate developer's plan to build Florida's first hyperscale data center -- taking up more than 1,300 acres of land in Polk County -- is humming along despite misgivings by some locals.",1,news_api
21606,"""Leon schools face $30 million deficit without sales tax extension"" via Alaijah Cross of the Tallahassee Democrat -- If Leon County voters don't approve the school district's half-penny sales tax extension which covers construction, maintenance and transportation, the district could be looking at a deficit of about $30 million next school year.",1,news_api

In [11]:
import re

# modal verbs
modal_words = [
    'will', 'would', 'may', 'might', 'could',
    'should', 'shall', 'must', 'can'
]

# predictive / forward-looking terms
predictive_words = [
    'predict', 'predicts', 'predicted', 'predicting',
    'forecast', 'forecasts', 'forecasted', 'forecasting',
    'expect', 'expects', 'expected', 'expecting',
    'project', 'projects', 'projected', 'projecting',
    'anticipate', 'anticipates', 'anticipated', 'anticipating',
    'speculate', 'speculates', 'speculated', 'speculating',
    'envision', 'envisions', 'envisioned', 'envisioning',
    'likely', 'probable', 'probably'
]

exclude_words = modal_words + predictive_words

pattern = r'\b(?:' + '|'.join(map(re.escape, exclude_words)) + r')\b'

tolsa_m = df[df['Ground Truth'] == 1]

no_modal_no_predictive = tolsa_m[
    ~tolsa_m['Base Sentence']
      .str.contains(pattern, case=False, na=False, regex=True)
]

print(no_modal_no_predictive.shape)
display(no_modal_no_predictive[['Base Sentence']].head(20))

(11, 3)

                                                                                                                                                                                                      Base Sentence
21101                                                                                 Positional value and some questions about his experience in pass coverage make Trotter unlikely to become a first round pick.
21137                                           It is unlikely to be able to win an election again without reclaiming parts of its old heartland in the cities, since that is where most Australians live and vote.
21289                                                                                               But legislators are unlikely to pass a stand-alone bill for or against AI, as they remain divided on the issue.
21367                                                                                                                       If generative AI halves the time needed for a task, staff are unlikely to gain leisure.
21420  Shaheed enters his age-28 season yet to deliver a top-35 fantasy campaign, and he's unlikely to get there this season while also focusing on special teams and working in Seattle's low-pass-volume offense.
21452                                       There's a chance we see more two-tight-end sets in Tampa Bay with coordinator Zac Robinson's offense coming to town and the loss of receiver Mike Evans in free agency.
21459                                       There's a chance we see more two-tight-end sets in Tampa Bay with coordinator Zac Robinson's offense coming to town and the loss of receiver Mike Evans in free agency.
21460                                       There's a chance we see more two-tight-end sets in Tampa Bay with coordinator Zac Robinson's offense coming to town and the loss of receiver Mike Evans in free agency.
21472                                         There's a chance we see more two-tight-end sets in Tampa Bay with coordinator Zac Robinson's offense coming to town and the loss of receiverMike Evansin free agency.
21564            One is that if they fail to win an outright majority, the election winners are unlikely to seek cooperation with any of the other four formations considered certain to enter the next parliament.
21578                                                         She has a chance to avenge her loss to Democrat Brian Nathan and has already filed to run in the general election for Senate District 14 in November.

In [12]:
print(tolsa_m.shape)
print(no_modal_no_predictive.shape)

(375, 3)
(11, 3)

In [13]:
sfe = SpacyFeatureExtraction(df, 'Base Sentence')
disable_components = []
pos_df = sfe.extract_pos_features(disable_components)
pos_df

==================================================
EXTRACTING POS FEATURES
==================================================

Extracting POS Features: 100%|██████████| 375/375 [00:01<00:00, 206.90doc/s]

==================================================
DONE EXTRACTING POS FEATURES
==================================================

,Sentence,Term,Lemma,POS Label,Detailed POS Label,Dependency,Shape,Is Alpha,Stop Word,Unique POS Label,...,Definite,Degree,SubCat,Animacy,Acc,Gen,Loc,Ins,Parat,Prep
0,"Otherwise, they could risk seeing his value drop further if he takes another step back in 2026.",Otherwise,otherwise,ADV,RB,advmod,Xxxxx,True,True,ADV_1,...,,,,,,,,,,
1,"Otherwise, they could risk seeing his value drop further if he takes another step back in 2026.",",",",",PUNCT,",",punct,",",False,False,PUNCT_1,...,,,,,,,,,,
2,"Otherwise, they could risk seeing his value drop further if he takes another step back in 2026.",they,they,PRON,PRP,nsubj,xxxx,True,True,PRON_1,...,,,,,,,,,,
3,"Otherwise, they could risk seeing his value drop further if he takes another step back in 2026.",could,could,AUX,MD,aux,xxxx,True,True,AUX_1,...,,,,,,,,,,
4,"Otherwise, they could risk seeing his value drop further if he takes another step back in 2026.",risk,risk,VERB,VB,ROOT,xxxx,True,False,VERB_1,...,,,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13035,"""Leon schools face $30 million deficit without sales tax extension"" via Alaijah Cross of the Tallahassee Democrat -- If Leon County voters don't approve the school district's half-penny sales tax extension which covers construction, maintenance and transportation, the district could be looking at a deficit of about $30 million next school year.",next,next,ADJ,JJ,amod,xxxx,True,True,ADJ_877,...,,[Pos],,,,,,,,
13036,"""Leon schools face $30 million deficit without sales tax extension"" via Alaijah Cross of the Tallahassee Democrat -- If Leon County voters don't approve the school district's half-penny sales tax extension which covers construction, maintenance and transportation, the district could be looking at a deficit of about $30 million next school year.",school,school,NOUN,NN,compound,xxxx,True,False,NOUN_2462,...,,,,,,,,,,
13037,"""Leon schools face $30 million deficit without sales tax extension"" via Alaijah Cross of the Tallahassee Democrat -- If Leon County voters don't approve the school district's half-penny sales tax extension which covers construction, maintenance and transportation, the district could be looking at a deficit of about $30 million next school year.",year,year,NOUN,NN,npadvmod,xxxx,True,False,NOUN_2463,...,,,,,,,,,,
13038,"""Leon schools face $30 million deficit without sales tax extension"" via Alaijah Cross of the Tallahassee Democrat -- If Leon County voters don't approve the school district's half-penny sales tax extension which covers construction, maintenance and transportation, the district could be looking at a deficit of about $30 million next school year.",.,.,PUNCT,.,punct,.,False,False,PUNCT_1240,...,,,,,,,,,,
13039,,,,,,,,False,,,...,,,,,,,,,,

In [14]:
filt_col = (pos_df['POS Label'] == 'VERB') == True
pos_df[filt_col]

,Sentence,Term,Lemma,POS Label,Detailed POS Label,Dependency,Shape,Is Alpha,Stop Word,Unique POS Label,...,Definite,Degree,SubCat,Animacy,Acc,Gen,Loc,Ins,Parat,Prep
4,"Otherwise, they could risk seeing his value drop further if he takes another step back in 2026.",risk,risk,VERB,VB,ROOT,xxxx,True,False,VERB_1,...,,,,,,,,,,
5,"Otherwise, they could risk seeing his value drop further if he takes another step back in 2026.",seeing,see,VERB,VBG,xcomp,xxxx,True,False,VERB_2,...,,,,,,,,,,
8,"Otherwise, they could risk seeing his value drop further if he takes another step back in 2026.",drop,drop,VERB,VB,ccomp,xxxx,True,False,VERB_3,...,,,,,,,,,,
12,"Otherwise, they could risk seeing his value drop further if he takes another step back in 2026.",takes,take,VERB,VBZ,advcl,xxxx,True,False,VERB_4,...,,,,,,,,,,
42,"Tucker might never be well-rounded enough to be an NFL starter, but his high-effort pass rush can earn him a subpackage role.",earn,earn,VERB,VB,conj,xxxx,True,False,VERB_5,...,,,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12967,"""Florida's first hyperscale data center could be thwarted by new water rule"" via Romy Ellenbogen and Emily L. Mahoney of the Tampa Bay Times -- A real estate developer's plan to build Florida's first hyperscale data center -- taking up more than 1,300 acres of land in Polk County -- is humming along despite misgivings by some locals.",humming,hum,VERB,VBG,ROOT,xxxx,True,False,VERB_1383,...,,,,,,,,,,
12979,"""Leon schools face $30 million deficit without sales tax extension"" via Alaijah Cross of the Tallahassee Democrat -- If Leon County voters don't approve the school district's half-penny sales tax extension which covers construction, maintenance and transportation, the district could be looking at a deficit of about $30 million next school year.",face,face,VERB,VBP,ccomp,xxxx,True,False,VERB_1384,...,,,,,,,,,,
13003,"""Leon schools face $30 million deficit without sales tax extension"" via Alaijah Cross of the Tallahassee Democrat -- If Leon County voters don't approve the school district's half-penny sales tax extension which covers construction, maintenance and transportation, the district could be looking at a deficit of about $30 million next school year.",approve,approve,VERB,VB,advcl,xxxx,True,False,VERB_1385,...,,,,,,,,,,
13015,"""Leon schools face $30 million deficit without sales tax extension"" via Alaijah Cross of the Tallahassee Democrat -- If Leon County voters don't approve the school district's half-penny sales tax extension which covers construction, maintenance and transportation, the district could be looking at a deficit of about $30 million next school year.",covers,cover,VERB,VBZ,relcl,xxxx,True,False,VERB_1386,...,,,,,,,,,,
13026,"""Leon schools face $30 million deficit without sales tax extension"" via Alaijah Cross of the Tallahassee Democrat -- If Leon County voters don't approve the school district's half-penny sales tax extension which covers construction, maintenance and transportation, the district could be looking at a deficit of about $30 million next school year.",looking,look,VERB,VBG,ROOT,xxxx,True,False,VERB_1387,...,,,,,,,,,,

Empty DataFrame
Columns: [Base Sentence, Ground Truth, Dataset Name]
Index: []

In [ ]:
if "These pandemic products are a window into what we went through  this year." in list(df['Base Sentence']):
    print(True)