# Climate Forecasts

1. DATASETS: [Hugging Face: Howard Tsai | All](https://huggingface.co/Howard881010)
2. DATASETS: [Hugging Face: Howard Tsai | Climate-1 Day](https://huggingface.co/datasets/Howard881010/climate-1day)
3. REPO: [Multimodal_Forecasting](https://github.com/Rose-STL-Lab/Multimodal_Forecasting/tree/main)
    - Get data from here.

In [1]:
import os, sys

import pandas as pd

# Get the current working directory of the notebook
notebook_dir = os.getcwd()
# Add the parent directory to the system path
sys.path.append(os.path.join(notebook_dir, '../'))

from data_processing import DataProcessing
from feature_extraction import SpacyFeatureExtraction

In [2]:
pd.set_option('max_colwidth', 800)

In [17]:
base_data_path = DataProcessing.load_base_data_path(notebook_dir)
# climate_dataset = os.path.join(base_data_path, 'others/', 'paper_mf/paper_mf_repo/data/climate/climate_2014_2023_final.csv')
# climate_dataset = os.path.join(base_data_path, 'others/', 'paper_mf/paper_mf_repo/data/climate/climate_2014_2023_final.csv')
climate_dataset = os.path.join(base_data_path, 'paper_mf/data/climate_forecasts/climate_2014_2023_final.csv')

In [18]:
df = DataProcessing.load_from_file(climate_dataset)
df

,date,temp,precip,humidity,windspeed,text
0,2014-01-01,37.9,0.000,57.4,10.0,"Arctic air is expected to invade the upper Midwest, Great Lakes, Ohio Valley, and Northeast, bringing some of the coldest temperatures in recent memory. Significant cold outbreaks on January 3-4 and 5-8 could result in temperatures 20-30 degrees Fahrenheit below normal. Lows in New England may reach -10s to -20s, and areas in eastern Montana, Minnesota, and Wisconsin may experience lows at or below -20F. Colder locations could drop to -30s or -40s Fahrenheit. Moderate upslope snow is anticipated across east-facing slopes from Montana to Northeast Wyoming. The coldest day is projected around January 8, with temperatures below freezing in a large section of the northern United States, potentially marking the coldest air masses since 1993/1994.\n\nPrecipitation is expected from a frontal ..."
1,2014-01-02,35.9,0.161,82.0,11.3,"Frigid air will sweep into the Midwest, Great Lakes, Ohio Valley, Northeast, and Mid-Atlantic early next week. A deep vortex will lead to significant temperature drops of -10 to -20 degrees across much of the central and eastern U.S., with the Ohio Valley potentially seeing temperatures nearly 40 degrees below normal by Monday. Heavy snow is anticipated northwest of a surface low tracking from the Lower Mississippi Valley to Interior New England, accompanied by strong winds, particularly across the Great Lakes. A strong Arctic front will move across the Appalachians on Sunday. By mid-week, temperatures should begin to moderate in the eastern half of the nation. Increasing moisture will bring rounds of precipitation to the Pacific Northwest, Intermountain West, and Great Basin as initia..."
2,2014-01-03,22.4,0.015,54.1,30.5,"Another arctic plunge is expected for the northeast quarter of the US Monday and Tuesday, leading to temperatures 20 to 40 degrees Fahrenheit below normal. A deep upper-level system over eastern Canada will influence this frigid air, while a fresh north Pacific flow will bring cooler and unsettled weather to the Great Lakes and northeast. Light to moderate precipitation is forecasted across the west, with potential localized enhancement along the coast. As the week progresses, precipitation is expected to increase from the southern plains into the Ohio and Tennessee valleys, with rain in the south transitioning to snow/mix further north. The forecast maintains good continuity despite some discrepancies between models regarding the impacts of cold advection associated with the arctic in..."
3,2014-01-04,25.4,0.000,52.6,13.3,"20°F-40°F below normal temperatures are expected in the northeastern quarter of the U.S. for January 7-11, 2014, with Indiana, Ohio, and western Pennsylvania experiencing temperatures 20°F+ below normal. An arctic blast will affect these regions, while the southeast and mid-Atlantic areas will also experience lower temperatures. The forecast incorporates a blend of GFS and GEFS solutions, with a notable phase of energy in the northern stream beyond day 4."
4,2014-01-05,37.1,0.041,78.7,11.0,"Temperatures are expected to approach normal values, with possibilities of being above normal. A progressive weather pattern will dominate the lower 48 states. Significant precipitation and strong winds are anticipated for the Pacific Northwest due to cyclogenesis off the Oregon/Washington coast. In the Midwest and Plains, a system originating from the South Central Rockies will bring rain through the Ohio Valley, influenced by a surface ridge in the Northeast and Mid-Atlantic. Mid-level warm advection will contribute to this precipitation. The GFS model shows discrepancies in predicted conditions in the Mid-Missouri Valley, while Gulf of Mexico moisture is expected to affect the Southern Plains and Lower-to-Mid Missouri Valley. A cutoff low over the Rio Grande Valley will also enhance..."
...,...,...,...,...,...,...
3617,2023-11-27,43.0,0.004,62.0,20.4,"Moderate to heavy rainfall is expected from Thursday, impacting the South, Southeast, and Mid-Mississippi Valley, particularly the eastern Texas Gulf Coast and western Louisiana where flash flooding is a concern. An upper-level shortwave will move from the Southwest to the Northeast this weekend, bringing unsettled weather. The Gulf Coast and Southeast will experience potentially heavy rainfall, with a marginal risk of excessive rainfall. The interior West will remain cooler than normal under reinforced troughing, while daytime highs in the Northern Plains, Midwest, and East could trend 5-10 degrees above average by the weekend. Precipitation will increase in the West, primarily along the Washington/Oregon coast and Cascades, with lighter amounts inland. The Western U.S. may return to ..."
3618,2023-11-28,35.7,0.001,42.2,25.0,"Wet pattern expected for the Northwest, with heavy snow threats inland from the Cascades and north-central Intermountain West/Rockies. From December 1 to December 5, 2023, widespread moderate to heavy rainfall is anticipated, particularly in the Gulf Coast and Southeast, with a marginal risk of excessive rainfall due to anomalous moisture and instability. High uncertainty in precipitation forecasts, especially across the east-central U.S. Precipitation is expected to increase in the West starting Thursday, leading to heaviest precipitation on the Washington/Oregon coast and Cascades from Sunday into Monday, along with accumulating snow in higher elevations. Stronger cyclogenesis may lead to larger-scale precipitation next week, impacting the Northeast as well."
3619,2023-11-29,32.9,0.000,41.8,10.1,"Multi-day wet pattern expected for the Northwest, with heavy snow threats from the Cascades to the north-central Intermountain West/Rockies. Active weather pattern continues through the weekend into next week, with systems moving from the interior West to the East Coast Saturday-Monday and ridging developing behind. An Atmospheric River may impact the West Coast this weekend, bringing ongoing precipitation and potential excessive rainfall in far northwest CA/southwest OR. Expect heavy snows and gusty winds in higher elevations of the Cascades and northern Sierras. Rainfall threat increases along the Oregon coast and western slopes of the Cascades, with another system bringing rain/mountain snow primarily to Washington state early next week. Moderate to heavy rainfall is likely for the ..."
3620,2023-11-30,42.1,0.000,51.4,10.5,"Heavy rain and inland heavy snow threats are expected in the Northwest due to a series of atmospheric rivers, with heavy snow threats also affecting the Northeast. An active weather pattern will bring heavy precipitation mainly across the Northwest and Northeast. In Washington and Oregon, heavy rainfall is anticipated, while the northern Intermountain West and Rockies could see significant snowfall. \n\nTemperatures in the Northern and Central Plains will be well above normal, reaching 15 to 25 degrees above average by Wednesday and Thursday. A strong ridge building over the West will influence these temperatures. Precipitation from atmospheric rivers will continue into next week, but with uncertainty in timing and volume.\n\nCoastal areas may experience modest rainfall, while the risk..."
3621,2023-12-01,45.6,0.123,73.4,10.7,"Heavy rain is expected in the Pacific Northwest due to multiple atmospheric river events from December 4 to December 8, 2023, possibly leading to flooding and rising river levels. Well above average temperatures, potentially 20-30 degrees higher than early December averages, are forecast for the Intermountain West and Plains, with record highs possible on Wednesday and Thursday. Snow showers may accompany a departing storm system in the Upper Midwest transitioning toward the Ohio Valley. A broad upper trough will bring active weather in the eastern U.S., with near seasonal temperatures expected, while a zonal flow pattern is anticipated by the end of the week. In the Northwest, 3-6 inch rainfall totals are likely, with a slight risk of flooding especially in the Cascades due to snow me..."

In [12]:
df['text'][0] = "Arctic air is expected to invade the upper Midwest, Great Lakes, Ohio Valley, and Northeast, bringing some of the coldest temperatures in recent memory. Significant cold outbreaks on January 3-4 and 5-8 could result in temperatures 20-30 degrees Fahrenheit below normal Lows in New England may reach -10s to -20s, and areas in eastern Montana, Minnesota, and Wisconsin may experience lows at or below -20F? Colder locations could drop to -30s or -40s Fahrenheit?"

df

/var/folders/78/9z0b45fx1xqbwxh8vk97lcfh0000gn/T/ipykernel_77369/329919925.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['text'][0] = "Arctic air is expected to invade the upper Midwest, Great Lakes, Ohio Valley, and Northeast, bringing some of the coldest temperatures in recent memory. Significant cold outbreaks on January 3-4 and 5-8 could result in temperatures 20-30 degrees Fahrenheit below normal Lows in New England may reach -10s to -20s, and areas in eastern Montana, Minnesota, and Wisconsin may experience lows at or below -20F? Colder locations could drop to -30s or -40s Fahrenheit?"
/var/folders/78/9z0b45fx1xqbwxh8vk97lcfh0000gn/T/ipykernel_77369/329919925.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['text'][0] = "Arctic air is expected to invade the upper Midwest, Great Lakes, Ohio Valley, and Northeast, bringing some of the coldest temperatures in recent memory. Significant cold outbreaks on January 3-4 and 5-8 could result in temperatures 20-30 degrees Fahrenheit below normal Lows in New England may reach -10s to -20s, and areas in eastern Montana, Minnesota, and Wisconsin may experience lows at or below -20F? Colder locations could drop to -30s or -40s Fahrenheit?"

,date,temp,precip,humidity,windspeed,text
0,2014-01-01,37.9,0.000,57.4,10.0,"Arctic air is expected to invade the upper Midwest, Great Lakes, Ohio Valley, and Northeast, bringing some of the coldest temperatures in recent memory. Significant cold outbreaks on January 3-4 and 5-8 could result in temperatures 20-30 degrees Fahrenheit below normal Lows in New England may reach -10s to -20s, and areas in eastern Montana, Minnesota, and Wisconsin may experience lows at or below -20F? Colder locations could drop to -30s or -40s Fahrenheit?"
1,2014-01-02,35.9,0.161,82.0,11.3,"Frigid air will sweep into the Midwest, Great Lakes, Ohio Valley, Northeast, and Mid-Atlantic early next week. A deep vortex will lead to significant temperature drops of -10 to -20 degrees across much of the central and eastern U.S., with the Ohio Valley potentially seeing temperatures nearly 40 degrees below normal by Monday. Heavy snow is anticipated northwest of a surface low tracking from the Lower Mississippi Valley to Interior New England, accompanied by strong winds, particularly across the Great Lakes. A strong Arctic front will move across the Appalachians on Sunday. By mid-week, temperatures should begin to moderate in the eastern half of the nation. Increasing moisture will bring rounds of precipitation to the Pacific Northwest, Intermountain West, and Great Basin as initia..."
2,2014-01-03,22.4,0.015,54.1,30.5,"Another arctic plunge is expected for the northeast quarter of the US Monday and Tuesday, leading to temperatures 20 to 40 degrees Fahrenheit below normal. A deep upper-level system over eastern Canada will influence this frigid air, while a fresh north Pacific flow will bring cooler and unsettled weather to the Great Lakes and northeast. Light to moderate precipitation is forecasted across the west, with potential localized enhancement along the coast. As the week progresses, precipitation is expected to increase from the southern plains into the Ohio and Tennessee valleys, with rain in the south transitioning to snow/mix further north. The forecast maintains good continuity despite some discrepancies between models regarding the impacts of cold advection associated with the arctic in..."
3,2014-01-04,25.4,0.000,52.6,13.3,"20°F-40°F below normal temperatures are expected in the northeastern quarter of the U.S. for January 7-11, 2014, with Indiana, Ohio, and western Pennsylvania experiencing temperatures 20°F+ below normal. An arctic blast will affect these regions, while the southeast and mid-Atlantic areas will also experience lower temperatures. The forecast incorporates a blend of GFS and GEFS solutions, with a notable phase of energy in the northern stream beyond day 4."
4,2014-01-05,37.1,0.041,78.7,11.0,"Temperatures are expected to approach normal values, with possibilities of being above normal. A progressive weather pattern will dominate the lower 48 states. Significant precipitation and strong winds are anticipated for the Pacific Northwest due to cyclogenesis off the Oregon/Washington coast. In the Midwest and Plains, a system originating from the South Central Rockies will bring rain through the Ohio Valley, influenced by a surface ridge in the Northeast and Mid-Atlantic. Mid-level warm advection will contribute to this precipitation. The GFS model shows discrepancies in predicted conditions in the Mid-Missouri Valley, while Gulf of Mexico moisture is expected to affect the Southern Plains and Lower-to-Mid Missouri Valley. A cutoff low over the Rio Grande Valley will also enhance..."
...,...,...,...,...,...,...
3617,2023-11-27,43.0,0.004,62.0,20.4,"Moderate to heavy rainfall is expected from Thursday, impacting the South, Southeast, and Mid-Mississippi Valley, particularly the eastern Texas Gulf Coast and western Louisiana where flash flooding is a concern. An upper-level shortwave will move from the Southwest to the Northeast this weekend, bringing unsettled weather. The Gulf Coast and Southeast will experience potentially heavy rainfall, with a marginal risk of excessive rainfall. The interior West will remain cooler than normal under reinforced troughing, while daytime highs in the Northern Plains, Midwest, and East could trend 5-10 degrees above average by the weekend. Precipitation will increase in the West, primarily along the Washington/Oregon coast and Cascades, with lighter amounts inland. The Western U.S. may return to ..."
3618,2023-11-28,35.7,0.001,42.2,25.0,"Wet pattern expected for the Northwest, with heavy snow threats inland from the Cascades and north-central Intermountain West/Rockies. From December 1 to December 5, 2023, widespread moderate to heavy rainfall is anticipated, particularly in the Gulf Coast and Southeast, with a marginal risk of excessive rainfall due to anomalous moisture and instability. High uncertainty in precipitation forecasts, especially across the east-central U.S. Precipitation is expected to increase in the West starting Thursday, leading to heaviest precipitation on the Washington/Oregon coast and Cascades from Sunday into Monday, along with accumulating snow in higher elevations. Stronger cyclogenesis may lead to larger-scale precipitation next week, impacting the Northeast as well."
3619,2023-11-29,32.9,0.000,41.8,10.1,"Multi-day wet pattern expected for the Northwest, with heavy snow threats from the Cascades to the north-central Intermountain West/Rockies. Active weather pattern continues through the weekend into next week, with systems moving from the interior West to the East Coast Saturday-Monday and ridging developing behind. An Atmospheric River may impact the West Coast this weekend, bringing ongoing precipitation and potential excessive rainfall in far northwest CA/southwest OR. Expect heavy snows and gusty winds in higher elevations of the Cascades and northern Sierras. Rainfall threat increases along the Oregon coast and western slopes of the Cascades, with another system bringing rain/mountain snow primarily to Washington state early next week. Moderate to heavy rainfall is likely for the ..."
3620,2023-11-30,42.1,0.000,51.4,10.5,"Heavy rain and inland heavy snow threats are expected in the Northwest due to a series of atmospheric rivers, with heavy snow threats also affecting the Northeast. An active weather pattern will bring heavy precipitation mainly across the Northwest and Northeast. In Washington and Oregon, heavy rainfall is anticipated, while the northern Intermountain West and Rockies could see significant snowfall. \n\nTemperatures in the Northern and Central Plains will be well above normal, reaching 15 to 25 degrees above average by Wednesday and Thursday. A strong ridge building over the West will influence these temperatures. Precipitation from atmospheric rivers will continue into next week, but with uncertainty in timing and volume.\n\nCoastal areas may experience modest rainfall, while the risk..."
3621,2023-12-01,45.6,0.123,73.4,10.7,"Heavy rain is expected in the Pacific Northwest due to multiple atmospheric river events from December 4 to December 8, 2023, possibly leading to flooding and rising river levels. Well above average temperatures, potentially 20-30 degrees higher than early December averages, are forecast for the Intermountain West and Plains, with record highs possible on Wednesday and Thursday. Snow showers may accompany a departing storm system in the Upper Midwest transitioning toward the Ohio Valley. A broad upper trough will bring active weather in the eastern U.S., with near seasonal temperatures expected, while a zonal flow pattern is anticipated by the end of the week. In the Northwest, 3-6 inch rainfall totals are likely, with a slight risk of flooding especially in the Cascades due to snow me..."

In [13]:
sfe = SpacyFeatureExtraction(df, 'text')
sfe

In [14]:
df = sfe.split_into_sentences(sentence_col_name='sentence')
df

Splitting into sentences:   0%|          | 5/3622 [00:00<01:20, 45.17it/s]

DOC: Arctic air is expected to invade the upper Midwest, Great Lakes, Ohio Valley, and Northeast, bringing some of the coldest temperatures in recent memory. Significant cold outbreaks on January 3-4 and 5-8 could result in temperatures 20-30 degrees Fahrenheit below normal Lows in New England may reach -10s to -20s, and areas in eastern Montana, Minnesota, and Wisconsin may experience lows at or below -20F? Colder locations could drop to -30s or -40s Fahrenheit?

DOC.SENTS: <_cython_3_2_4.generator object at 0x1521fb370>

>>>SENT: Arctic air is expected to invade the upper Midwest, Great Lakes, Ohio Valley, and Northeast, bringing some of the coldest temperatures in recent memory.
DOC: Arctic air is expected to invade the upper Midwest, Great Lakes, Ohio Valley, and Northeast, bringing some of the coldest temperatures in recent memory. Significant cold outbreaks on January 3-4 and 5-8 could result in temperatures 20-30 degrees Fahrenheit below normal Lows in New England may reach -10s to -20s, and areas in eastern Montana, Minnesota, and Wisconsin may experience lows at or below -20F? Colder locations could drop to -30s or -40s Fahrenheit?

DOC.SENTS: <_cython_3_2_4.generator object at 0x1521fb370>

>>>SENT: Significant cold outbreaks on January 3-4 and 5-8 could result in temperatures 20-30 degrees Fahrenheit below normal Lows in New England may reach -10s to -20s, and areas in eastern Montana, Minnesota, and Wisconsin may experience lows at or below -20F?
DOC: Arctic air is expected to invade the upper Midwest, Great Lakes, Ohio Valley, and Northeast, bringing some of the coldest temperatures in recent memory. Significant cold outbreaks on January 3-4 and 5-8 could result in temperatures 20-30 degrees Fahrenheit below normal Lows in New England may reach -10s to -20s, and areas in eastern Montana, Minnesota, and Wisconsin may experience lows at or below -20F? Colder locations could drop to -30s or -40s Fahrenheit?

DOC.SENTS: <_cython_3_2_4.generator object at 0x1521fb370>

>>>SENT: Colder locations could drop to -30s or -40s Fahrenheit?
DOC: Frigid air will sweep into the Midwest, Great Lakes, Ohio Valley, Northeast, and Mid-Atlantic early next week. A deep vortex will lead to significant temperature drops of -10 to -20 degrees across much of the central and eastern U.S., with the Ohio Valley potentially seeing temperatures nearly 40 degrees below normal by Monday. Heavy snow is anticipated northwest of a surface low tracking from the Lower Mississippi Valley to Interior New England, accompanied by strong winds, particularly across the Great Lakes. A strong Arctic front will move across the Appalachians on Sunday. By mid-week, temperatures should begin to moderate in the eastern half of the nation. Increasing moisture will bring rounds of precipitation to the Pacific Northwest, Intermountain West, and Great Basin as initially dry conditions shift to wetter patterns.

DOC.SENTS: <_cython_3_2_4.generator object at 0x1521fb370>

>>>SENT: Frigid air will sweep into the Midwest, Great Lakes, Ohio Valley, Northeast, and Mid-Atlantic early next week.
DOC: Frigid air will sweep into the Midwest, Great Lakes, Ohio Valley, Northeast, and Mid-Atlantic early next week. A deep vortex will lead to significant temperature drops of -10 to -20 degrees across much of the central and eastern U.S., with the Ohio Valley potentially seeing temperatures nearly 40 degrees below normal by Monday. Heavy snow is anticipated northwest of a surface low tracking from the Lower Mississippi Valley to Interior New England, accompanied by strong winds, particularly across the Great Lakes. A strong Arctic front will move across the Appalachians on Sunday. By mid-week, temperatures should begin to moderate in the eastern half of the nation. Increasing moisture will bring rounds of precipitation to the Pacific Northwest, Intermountain West, and Great Basin as initially dry conditions shift to wetter patterns.

DOC.SENTS: <_cython_3_2_4.generator object at 0x1521fb370>

>>>SENT: A deep vortex will lead to significant temperature drops of -10 to -20 degrees across much of the central and eastern U.S., with the Ohio Valley potentially seeing temperatures nearly 40 degrees below normal by Monday.
DOC: Frigid air will sweep into the Midwest, Great Lakes, Ohio Valley, Northeast, and Mid-Atlantic early next week. A deep vortex will lead to significant temperature drops of -10 to -20 degrees across much of the central and eastern U.S., with the Ohio Valley potentially seeing temperatures nearly 40 degrees below normal by Monday. Heavy snow is anticipated northwest of a surface low tracking from the Lower Mississippi Valley to Interior New England, accompanied by strong winds, particularly across the Great Lakes. A strong Arctic front will move across the Appalachians on Sunday. By mid-week, temperatures should begin to moderate in the eastern half of the nation. Increasing moisture will bring rounds of precipitation to the Pacific Northwest, Intermountain West, and Great Basin as initially dry conditions shift to wetter patterns.

DOC.SENTS: <_cython_3_2_4.generator object at 0x1521fb370>

>>>SENT: Heavy snow is anticipated northwest of a surface low tracking from the Lower Mississippi Valley to Interior New England, accompanied by strong winds, particularly across the Great Lakes.
DOC: Frigid air will sweep into the Midwest, Great Lakes, Ohio Valley, Northeast, and Mid-Atlantic early next week. A deep vortex will lead to significant temperature drops of -10 to -20 degrees across much of the central and eastern U.S., with the Ohio Valley potentially seeing temperatures nearly 40 degrees below normal by Monday. Heavy snow is anticipated northwest of a surface low tracking from the Lower Mississippi Valley to Interior New England, accompanied by strong winds, particularly across the Great Lakes. A strong Arctic front will move across the Appalachians on Sunday. By mid-week, temperatures should begin to moderate in the eastern half of the nation. Increasing moisture will bring rounds of precipitation to the Pacific Northwest, Intermountain West, and Great Basin as initially dry conditions shift to wetter patterns.

DOC.SENTS: <_cython_3_2_4.generator object at 0x1521fb370>

>>>SENT: A strong Arctic front will move across the Appalachians on Sunday.

Splitting into sentences:   8%|▊         | 273/3622 [00:06<01:15, 44.59it/s]

KeyboardInterrupt:

In [ ]:
df['label'] = 1
df

In [ ]:
save_path = os.path.join(base_data_path, 'paper_mf', 'data', 'climate_forecasts')
DataProcessing.save_to_file(df, save_path, 'climate_forecasts', save_file_type='.csv')

In [ ]:
DataProcessing.load_mf_climate_dataset(notebook_dir)

## Check bad sentences

In [ ]:
df[
    df["sentence"].str.contains(r"°F", regex=True, na=False)
][["sentence"]].head(10)

In [ ]:
# Return sentences that likely indicate bad sentence splits
bad_sentences = df[
    # Starts with dangling symbols or units (but not valid numbers)
    df["sentence"].str.match(r"^(°F|\+F|F\+|[^\w\d])", na=False)
    |
    # Ends mid temperature or numeric range expression
    df["sentence"].str.contains(r"(°F[-+]$|\d-\s*$)", regex=True, na=False)
]

bad_sentences[["sentence"]]

In [ ]:
bad_sentences

In [ ]:
import re

def normalize_forecast_text(text: str) -> str:
    if not isinstance(text, str):
        return text

    # Remove markdown bold/italics
    text = re.sub(r"\*\*(.*?)\*\*", r"\1", text)

    # Remove standalone headers (lines with no sentence punctuation)
    text = re.sub(
        r"(?m)^(?:[A-Z][A-Za-z\s]+(?:\([^)]+\))?:)\s*$",
        "",
        text
    )

    # Convert bullet points to sentences
    text = re.sub(r"(?m)^-\s+", "", text)

    # Collapse excessive newlines
    text = re.sub(r"\n{2,}", " ", text)

    return text.strip()

In [ ]:
df["text"] = df["text"].apply(normalize_forecast_text)
df = sfe.split_into_sentences(sentence_col_name='clean sentence')
df

In [ ]:
# Return sentences that likely indicate bad sentence splits
bad_sentences = df[
    # Starts with dangling symbols or units (but not valid numbers)
    df["clean sentence"].str.match(r"^(°F|\+F|F\+|[^\w\d])", na=False)
    |
    # Ends mid temperature or numeric range expression
    df["clean sentence"].str.contains(r"(°F[-+]$|\d-\s*$)", regex=True, na=False)
]

bad_sentences[["clean sentence"]]

In [ ]:
bad_sentences