> Can reference `script_experiments/extract_prediction_properties.py` as all updates are there now.

---

# Sequence Labelling: Pediction Sentence

- Sequence: Pediction Sentence
- Labels: Prediction Properties

Tasks
1. Update the prompt from zero-shot to few-show
2. How can we measure the output/labels from the LLMs?
    1. Could use multiple LLMs and perform majority vote for the labels
3. Perform on various datasets
    1. Synthetic data (which is below)
    2. Real datasets
        1.  financial_phrasebank
        2. chronicle2050

> `prediction_classification_experiments-v2/ml_classifiers.ipynb` and `prediction_classification_experiments-v2/llm_classifiers.ipynb` because classify sentences as prediction/non-prediction

In [2]:
import os
import sys
import pprint

import pandas as pd

from tqdm import tqdm

notebook_dir = os.getcwd()

sys.path.append(os.path.join(notebook_dir, '../'))

from data_processing import DataProcessing
from prediction_properties import PredictionProperties
from text_generation_models import TextGenerationModelFactory
from vector_stores import ChromaVectorStore, VectorStoreDirector

In [3]:
pd.set_option('max_colwidth', 800)
# pd.set_option('display.max_columns', None)
# pd.set_option('display.max_rows', None)

## Load Data

- Request data

In [6]:
base_data_path = os.path.join(notebook_dir, '../data')

In [3]:
# combine_data_path = os.path.join(base_data_path, 'combined_datasets')
# model_results_path = os.path.join(combine_data_path, 'ml_classifiers-v1.csv')
# df = DataProcessing.load_from_file(model_results_path, 'csv', sep=',')
# df.head(3)

In [4]:
# save_chronicle2050_vs_majority_vote_path = os.path.join(base_data_path, 'chronicle2050')
# DataProcessing.save_to_file(diff_labels_df, save_chronicle2050_vs_majority_vote_path, 'chronicle2050-diff_vs_majority_vote', '.csv')

In [5]:
chronicle2050_data_path = os.path.join(base_data_path, 'chronicle2050')
chronicle2050_vs_majority_vote_path = os.path.join(chronicle2050_data_path, 'chronicle2050-diff_vs_majority_vote-v1.csv')
df = DataProcessing.load_from_file(chronicle2050_vs_majority_vote_path, 'csv', sep=',')
df

,sentence,label,majority vote,sentence embedding,cluster
0,"By January 1st, 2037, Tesla will have been the...",1,0,[-4.69374172e-02 1.84888348e-01 -1.93335768e-...,1
1,Private Nonfarm business productivity growth w...,1,0,[-9.73114073e-02 2.70783365e-01 2.02017017e-...,1
2,No Republican will be President of the USA bef...,1,0,[ 2.90547162e-02 1.90217629e-01 6.58295751e-...,0
3,The market capitalization of Berkshire Hathawa...,1,0,[-5.81037253e-02 2.09591284e-01 9.17413309e-...,0
4,"Over a ten-year period commencing on July 1, 2...",1,0,[-1.03356980e-01 1.44637421e-01 -4.59992839e-...,1
...,...,...,...,...,...
2734,"Youth Sports Market 2023 Share, Growth, Segmen...",0,1,[-3.33087146e-02 4.32247132e-01 7.01236585e-...,1
2735,But will the end result appear the same?,0,1,[ 2.52095629e-02 1.34403348e-01 -1.70240343e-...,1
2736,"In this article, we will explore the unique ro...",0,1,[ 8.71468484e-02 1.95162952e-01 -5.56851402e-...,1
2737,Ultron's rumored return in Armor Wars would be...,0,1,[-3.02092684e-03 1.02326840e-01 4.89601493e-...,0
2738,Let's hope it doesn't decide to take over the ...,0,1,[ 3.08428220e-02 1.90806672e-01 -1.32161409e-...,0

## Majority Vote (Prediction)

### Majority Vote

- Be care with doing this on real data. Some examples in `data/combined_datasets/ml_classifiers-v1.csv` have true labels of 0 and MV is 1.

In [6]:
# model_results_df = df.drop(columns=['Author Type', 'Embedding', 'Normalized Embeddings'])
# model_results_df.head(3)

In [7]:
# model_results_df['Majority Vote'] = model_results_df.iloc[:, 2:].mode(axis=1)
# model_results_df.head(3)

### Filter for Prediction (=1)

In [8]:
# filt_prediction = (model_results_df['Sentence Label'] == 1) & (model_results_df['Majority Vote'] == 1)
# predictions_df = model_results_df[filt_prediction]
# predictions_df.shape

In [9]:
# predictions_df.head(7)

## LLM for Relation Extraction

### Prompts

In [10]:
prediction_base_prompt = DataProcessing.load_prediction_properties()
prediction_base_prompt

' A prediction <p> = (<p_s>, <p_t>, <p_d>, <p_o>), where it consists of the following four properties:\n\n            1. <p_s>\n                - Defined as: \n                    - Source entity that states the <p>\n                - Characteristics:\n                    - A person with either: a name only, profile name only, geneder only, domain specific title only or any combination of these.\n                    - An associated organization\n                    - Named entity: Person, organization\n                    - Part of speech: Noun\n\n            2. <p_t>\n                - Defined as: \n                    - Target entity that the <p> is about\n                - Characteristics:\n                    - Same and <p_s>\n                    \n            3. <p_d>\n                - Defined as: \n                    - Date when the <p> is made\n                    - Date when the <p> is expected to come to fruition\n                - Characteristics:\n                    - Forecast can range from a second to anytime in the future.\n                    - Could answer the question: "How far out is the <p> from today?"\n                    - Any format\n                    - Must be made before it is expected to come to fruition\n                    - Named entity: Date, cardinal?\n                    - Part of speech: vary\n\n            4. <p_o>\n                - Defined as:\n                    - Outcome\n                - Characteristics:\n                    - Relevant or misc details such as a quantifiable metric, slope, attribute of interest\n                    - From Pegah at USC: Value at an instant, statistical function minimum, changes over interval, second order effect comparison, recurrent pattern\n                    - Named entity: vary\n                    - Part of speech: vary\n\n\n        '

In [11]:
# role_prompt = "Role: You are a lingust that specializes in identifying properties within a prediction statement."
# task_prompt = "Your task is label the prediction properties within"

In [12]:
system_identity_prompt = "You are a lingustic expert that specializes in identifying properties within a prediction statement."
# prediction_requirements = PredictionProperties.get_requirements()
task = """For each word within the sentence "label" as either a "no_label": 0, "source": 1, "target": 2, "date": 3, "outcome": 4. IMPORTANT: Keep multi-word entities together as single items in the list."""
sentence_label_format_output = """

Respond ONLY with valid JSON in this exact format: {0: [word_from_sentence]}, {1: [word_from_sentence]}, {2: [word_from_sentence]}, {3: [word_from_sentence]}, {4: [word_from_sentence]}, where key is int ranging from 0 to 4 and the value is the words_from_sentence, split by a comma/all placed into a list, so {int: [word_from_sentence_1, word_from_sentence_2, ..., word_from_sentence_W]}. For 2 and 3, some words may be a prefix or a position or tile before/after 2 or 3. Be sure to take that into account.

Do NOT reason or provide anything other than the aforementioned. Also, stop responding in reverse format {word_from_sentence: 0}, {word_from_sentence: 1}, {word_from_sentence: 2}, {word_from_sentence: 3}, {word_from_sentence: 4} or in any other format.

Respond ONLY with valid JSON in this exact format: {0: [word_from_sentence]}, {1: [word_from_sentence]}, {2: [word_from_sentence]}, {3: [word_from_sentence]}, {4: [word_from_sentence]}, where key is int ranging from 0 to 4 and the value is the words_from_sentence, split by a comma/all placed into a list, so {int: [word_from_sentence_1, word_from_sentence_2, ..., word_from_sentence_W]}.
"""

In [13]:
prediction_properties = PredictionProperties.get_prediction_properties()
prediction_properties_base_prompt = f"""{system_identity_prompt} For each prediction, the format is based on: 
    
    {prediction_properties}

"""
prediction_properties_base_prompt

'You are a lingustic expert that specializes in identifying properties within a prediction statement. For each prediction, the format is based on: \n\n     A prediction <p> = (<p_s>, <p_t>, <p_d>, <p_o>), where it consists of the following four properties:\n\n            1. <p_s>\n                - Defined as: \n                    - Source entity that states the <p>\n                - Characteristics:\n                    - A person with either: a name only, profile name only, geneder only, domain specific title only or any combination of these.\n                    - An associated organization\n                    - Named entity: Person, organization\n                    - Part of speech: Noun\n\n            2. <p_t>\n                - Defined as: \n                    - Target entity that the <p> is about\n                - Characteristics:\n                    - Same and <p_s>\n                    \n            3. <p_d>\n                - Defined as: \n                    - Date when the <p> is made\n                    - Date when the <p> is expected to come to fruition\n                - Characteristics:\n                    - Forecast can range from a second to anytime in the future.\n                    - Could answer the question: "How far out is the <p> from today?"\n                    - Any format\n                    - Must be made before it is expected to come to fruition\n                    - Named entity: Date, cardinal?\n                    - Part of speech: vary\n\n            4. <p_o>\n                - Defined as:\n                    - Outcome\n                - Characteristics:\n                    - Relevant or misc details such as a quantifiable metric, slope, attribute of interest\n                    - From Pegah at USC: Value at an instant, statistical function minimum, changes over interval, second order effect comparison, recurrent pattern\n                    - Named entity: vary\n                    - Part of speech: vary\n\n\n        \n\n'

### Models

In [14]:
tgmf = TextGenerationModelFactory()

# Option 1: Specific models
# models = tgmf.create_instances(['llama-3.1-8b-instant', 'llama-3.3-70b-versatile', 'llama-3.3-70b-instruct', 'openai/gpt-oss-20b'])
models = tgmf.create_instances(['openai/gpt-oss-120b'])

# Option 2: All Groq models
# models = tgmf.create_instances(tgmf.get_groq_model_names())

# Option 3: All NaviGator models
# models = tgmf.create_instances(tgmf.get_navigator_model_names())

# Option 4: All available models
# models = tgmf.create_instances()

# Option 5: Mix and match
# custom_models = ['llama-3.1-70b-instruct', 'mistral-small-3.1', 'llama-3.1-8b-instant']
# models = tgmf.create_instances(custom_models)
models

### Prompt Models

In [15]:
def llm_certifier(idx, sentence_to_classify: str, base_prompt: str, model, task, format_output: str):
    
      prompt = f"""{base_prompt}
      
      Sentence to extract the prediction properties: '{sentence_to_classify}'

      {task}
      
      {format_output}
      """
      if idx < 2:
            print(f"\tPrompt: {prompt}")
      input_prompt = model.user(prompt)
      raw_text_llm_generation = model.chat_completion([input_prompt])
      # print(f"Raw response: {raw_text_llm_generation}")      
      return raw_text_llm_generation

In [16]:
# subset_predictions_df = predictions_df.iloc[:33, :]
# subset_predictions_df.head(3)

In [17]:
results = []
# len(predictions_df)
# for idx, row in tqdm(predictions_df.iterrows(), total=len(predictions_df), desc="Processing"):
for idx, row in tqdm(df.iterrows(), total=len(df), desc="Processing"):
    text = row['sentence']
    # print(f"{idx} --- Sentence: {text}")
    for model in models:
        # print(model.__name__())
        raw_response = llm_certifier(idx, text, prediction_properties_base_prompt, model, task, sentence_label_format_output)
        result = (text, raw_response, model.__name__())
        results.append(result)

        if idx < 3:
            # print(f"{idx} --- Sentence: {text}")
            print(f"\n--- Result {idx} ---")
            pprint.pprint(result, width=120)
    
    # print()

Processing:   0%|          | 0/2739 [00:00<?, ?it/s]

	Prompt: You are a lingustic expert that specializes in identifying properties within a prediction statement. For each prediction, the format is based on:

     A prediction <p> = (<p_s>, <p_t>, <p_d>, <p_o>), where it consists of the following four properties:

            1. <p_s>
                - Defined as:
                    - Source entity that states the <p>
                - Characteristics:
                    - A person with either: a name only, profile name only, geneder only, domain specific title only or any combination of these.
                    - An associated organization
                    - Named entity: Person, organization
                    - Part of speech: Noun

            2. <p_t>
                - Defined as:
                    - Target entity that the <p> is about
                - Characteristics:
                    - Same and <p_s>

            3. <p_d>
                - Defined as:
                    - Date when the <p> is made
                    - Date when the <p> is expected to come to fruition
                - Characteristics:
                    - Forecast can range from a second to anytime in the future.
                    - Could answer the question: "How far out is the <p> from today?"
                    - Any format
                    - Must be made before it is expected to come to fruition
                    - Named entity: Date, cardinal?
                    - Part of speech: vary

            4. <p_o>
                - Defined as:
                    - Outcome
                - Characteristics:
                    - Relevant or misc details such as a quantifiable metric, slope, attribute of interest
                    - From Pegah at USC: Value at an instant, statistical function minimum, changes over interval, second order effect comparison, recurrent pattern
                    - Named entity: vary
                    - Part of speech: vary






      Sentence to extract the prediction properties: 'By January 1st, 2037, Tesla will have been the first company with 1 million vehicles that are capable of SAE Level 4 autonomy on over 90% of public roads in the contiguous United States, with human-level safety or better, and this capability will be usable by the general public commercially.'

      For each word within the sentence "label" as either a "no_label": 0, "source": 1, "target": 2, "date": 3, "outcome": 4. IMPORTANT: Keep multi-word entities together as single items in the list.



Respond ONLY with valid JSON in this exact format: {0: [word_from_sentence]}, {1: [word_from_sentence]}, {2: [word_from_sentence]}, {3: [word_from_sentence]}, {4: [word_from_sentence]}, where key is int ranging from 0 to 4 and the value is the words_from_sentence, split by a comma/all placed into a list, so {int: [word_from_sentence_1, word_from_sentence_2, ..., word_from_sentence_W]}. For 2 and 3, some words may be a prefix or a position or tile before/after 2 or 3. Be sure to take that into account.

Do NOT reason or provide anything other than the aforementioned. Also, stop responding in reverse format {word_from_sentence: 0}, {word_from_sentence: 1}, {word_from_sentence: 2}, {word_from_sentence: 3}, {word_from_sentence: 4} or in any other format.

Respond ONLY with valid JSON in this exact format: {0: [word_from_sentence]}, {1: [word_from_sentence]}, {2: [word_from_sentence]}, {3: [word_from_sentence]}, {4: [word_from_sentence]}, where key is int ranging from 0 to 4 and the value is the words_from_sentence, split by a comma/all placed into a list, so {int: [word_from_sentence_1, word_from_sentence_2, ..., word_from_sentence_W]}.

Processing:   0%|          | 1/2739 [00:03<2:55:38,  3.85s/it]

--- Result 0 ---
('By January 1st, 2037, Tesla will have been the first company with 1 million vehicles that are capable of SAE Level 4 '
 'autonomy on over 90% of public roads in the contiguous United States, with human-level safety or better, and this '
 'capability will be usable by the general public commercially.',
 '{0: ["By"], 1: [], 2: ["Tesla"], 3: ["January 1st, 2037"], 4: ["will", "have", "been", "the first company", "with", '
 '"1 million vehicles", "that", "are", "capable", "of", "SAE Level 4 autonomy", "on", "over", "90% of public roads", '
 '"in", "the", "contiguous United States", "with", "human-level safety", "or", "better", "and", "this capability", '
 '"will", "be", "usable", "by", "the", "general public", "commercially"]}',
 'openai/gpt-oss-120b')
	Prompt: You are a lingustic expert that specializes in identifying properties within a prediction statement. For each prediction, the format is based on:

     A prediction <p> = (<p_s>, <p_t>, <p_d>, <p_o>), where it consists of the following four properties:

            1. <p_s>
                - Defined as:
                    - Source entity that states the <p>
                - Characteristics:
                    - A person with either: a name only, profile name only, geneder only, domain specific title only or any combination of these.
                    - An associated organization
                    - Named entity: Person, organization
                    - Part of speech: Noun

            2. <p_t>
                - Defined as:
                    - Target entity that the <p> is about
                - Characteristics:
                    - Same and <p_s>

            3. <p_d>
                - Defined as:
                    - Date when the <p> is made
                    - Date when the <p> is expected to come to fruition
                - Characteristics:
                    - Forecast can range from a second to anytime in the future.
                    - Could answer the question: "How far out is the <p> from today?"
                    - Any format
                    - Must be made before it is expected to come to fruition
                    - Named entity: Date, cardinal?
                    - Part of speech: vary

            4. <p_o>
                - Defined as:
                    - Outcome
                - Characteristics:
                    - Relevant or misc details such as a quantifiable metric, slope, attribute of interest
                    - From Pegah at USC: Value at an instant, statistical function minimum, changes over interval, second order effect comparison, recurrent pattern
                    - Named entity: vary
                    - Part of speech: vary






      Sentence to extract the prediction properties: 'Private Nonfarm business productivity growth will average over 1.8 percent per year from the first quarter (Q1) of 2020 to the last quarter of 2029 (Q4).'

      For each word within the sentence "label" as either a "no_label": 0, "source": 1, "target": 2, "date": 3, "outcome": 4. IMPORTANT: Keep multi-word entities together as single items in the list.



Respond ONLY with valid JSON in this exact format: {0: [word_from_sentence]}, {1: [word_from_sentence]}, {2: [word_from_sentence]}, {3: [word_from_sentence]}, {4: [word_from_sentence]}, where key is int ranging from 0 to 4 and the value is the words_from_sentence, split by a comma/all placed into a list, so {int: [word_from_sentence_1, word_from_sentence_2, ..., word_from_sentence_W]}. For 2 and 3, some words may be a prefix or a position or tile before/after 2 or 3. Be sure to take that into account.

Do NOT reason or provide anything other than the aforementioned. Also, stop responding in reverse format {word_from_sentence: 0}, {word_from_sentence: 1}, {word_from_sentence: 2}, {word_from_sentence: 3}, {word_from_sentence: 4} or in any other format.

Respond ONLY with valid JSON in this exact format: {0: [word_from_sentence]}, {1: [word_from_sentence]}, {2: [word_from_sentence]}, {3: [word_from_sentence]}, {4: [word_from_sentence]}, where key is int ranging from 0 to 4 and the value is the words_from_sentence, split by a comma/all placed into a list, so {int: [word_from_sentence_1, word_from_sentence_2, ..., word_from_sentence_W]}.

Processing:   0%|          | 2/2739 [00:07<2:46:28,  3.65s/it]

--- Result 1 ---
('Private Nonfarm business productivity growth will average over 1.8 percent per year from the first quarter (Q1) of '
 '2020 to the last quarter of 2029 (Q4).',
 '{0: ["will", "from", "to", "the", "of", "the", "of", "the"], 1: [], 2: ["Private Nonfarm business productivity '
 'growth"], 3: ["first quarter (Q1) of 2020", "last quarter of 2029 (Q4)"], 4: ["average over 1.8 percent per year"]}',
 'openai/gpt-oss-120b')

Processing:   0%|          | 3/2739 [00:10<2:36:33,  3.43s/it]

--- Result 2 ---
('No Republican will be President of the USA before December 30, 2039.',
 '{0: ["will", "be", "before"], 1: [], 2: ["President of the USA"], 3: ["December 30, 2039"], 4: ["No Republican"]}',
 'openai/gpt-oss-120b')

Processing:   3%|▎         | 87/2739 [22:57<11:40:01, 15.84s/it]

APIConnectionError: Connection error.

In [18]:
results

[('By January 1st, 2037, Tesla will have been the first company with 1 million vehicles that are capable of SAE Level 4 autonomy on over 90% of public roads in the contiguous United States, with human-level safety or better, and this capability will be usable by the general public commercially.',
  '{0: ["By"], 1: [], 2: ["Tesla"], 3: ["January 1st, 2037"], 4: ["will", "have", "been", "the first company", "with", "1 million vehicles", "that", "are", "capable", "of", "SAE Level 4 autonomy", "on", "over", "90% of public roads", "in", "the", "contiguous United States", "with", "human-level safety", "or", "better", "and", "this capability", "will", "be", "usable", "by", "the", "general public", "commercially"]}',
  'openai/gpt-oss-120b'),
 ('Private Nonfarm business productivity growth will average over 1.8 percent per year from the first quarter (Q1) of 2020 to the last quarter of 2029 (Q4).',
  '{0: ["will", "from", "to", "the", "of", "the", "of", "the"], 1: [], 2: ["Private Nonfarm business productivity growth"], 3: ["first quarter (Q1) of 2020", "last quarter of 2029 (Q4)"], 4: ["average over 1.8 percent per year"]}',
  'openai/gpt-oss-120b'),
 ('No Republican will be President of the USA before December 30, 2039.',
  '{0: ["will", "be", "before"], 1: [], 2: ["President of the USA"], 3: ["December 30, 2039"], 4: ["No Republican"]}',
  'openai/gpt-oss-120b'),
 ("The market capitalization of Berkshire Hathaway will be greater than Tesla on Warren Buffett's 100th birthday.",
  '{0: ["The", "market", "capitalization", "of", "will", "be", "on"], 1: [], 2: ["Berkshire Hathaway", "Tesla"], 3: ["Warren Buffett\'s 100th birthday"], 4: ["greater than"]}',
  'openai/gpt-oss-120b'),
 ('Over a ten-year period commencing on July 1, 2020, and ending on June 30, 2030, a portfolio of index funds invested broadly in US and International equities will outperform a portfolio managed by a sophisticated individual investor selecting stocks and funds.',
  '{0: ["Over", "a", "commencing", "on", "and", "ending", "on"], 1: [], 2: ["a portfolio of index funds invested broadly in US and International equities", "a portfolio managed by a sophisticated individual investor selecting stocks and funds"], 3: ["ten-year period", "July 1, 2020", "June 30, 2030"], 4: ["will outperform"]}',
  'openai/gpt-oss-120b'),
 ('The Equal Rights Amendment to the U.S. Constitution will be passed by the end of 2023.',
  '{"0": [], "1": [], "2": ["The Equal Rights Amendment to the U.S. Constitution"], "3": ["by the end of 2023"], "4": ["will be passed"]}',
  'openai/gpt-oss-120b'),
 ('There will be at least one 2022 FIFA World Cup match which will have more people watching live via virtual reality than people watching it in person.',
  '{0: ["There","will","be","at","least","one","which","will","have"], 1: [], 2: ["2022 FIFA World Cup match"], 3: [], 4: ["more people watching live via virtual reality than people watching it in person"]}',
  'openai/gpt-oss-120b'),
 ('The annual rate of US labor productivity growth for the year 02025, as measured by the U.S. Bureau of Labor Statistics, will be 2 percent or above.',
  '{0: ["The", "for", "as", "measured", "by", "the", "will", "be"], 1: ["U.S. Bureau of Labor Statistics"], 2: ["annual rate of US labor productivity growth"], 3: ["the year 02025"], 4: ["2 percent or above"]}',
  'openai/gpt-oss-120b'),
 ('Clinicians and neuroscientists will develop well validated brain-activity measurement technologies establishing with a high degree of certainty whether individual human subjects, such as anesthetized and neurological patients, are, at that moment, conscious.',
  '{0: ["will", "develop", "establishing", "with", "a", "high", "degree", "of", "certainty", "whether", "are", "conscious"], 1: ["Clinicians and neuroscientists"], 2: ["individual human subjects, such as anesthetized and neurological patients"], 3: ["at that moment"], 4: ["well validated brain-activity measurement technologies"]}',
  'openai/gpt-oss-120b'),
 ('“The\u200b \u200bUS\u200b \u200bunemployment\u200b \u200brate,\u200b \u200bas\u200b \u200bdetermined\u200b \u200bby\u200b \u200bthe\u200b \u200bBureau\u200b \u200bof\u200b \u200bLabor\u200b \u200bStatistics,\u200b \u200bwill be lower\u200b \u200bthan\u200b \u200b8\u200b \u200bpercent\u200b \u200bfor\u200b \u200bthe\u200b \u200byear\u200b \u200b2035,\u200b \u200bunless\u200b \u200bthe\u200b \u200bThe\u200b \u200bNational\u200b \u200bBureau\u200b \u200bof Economic\u200b \u200bResearch\u200b \u200bdetermines\u200b \u200bthat\u200b \u200bany\u200b \u200bquarter\u200b \u200bin\u200b \u200b2035\u200b \u200bwas\u200b \u200bin\u200b \u200ba\u200b \u200brecession,\u200b \u200bin which\u200b \u200bcase\u200b \u200bthe\u200b \u200breference\u200b \u200byear\u200b \u200bwill\u200b \u200bbe\u200b \u200bthe\u200b \u200b12\u200b \u200bmonths\u200b \u200bprior\u200b \u200bto\u200b \u200bthe\u200b \u200bbeginning\u200b \u200bof\u200b \u200bthe recession.”',
  '{\n  "0": ["The", "as", "determined", "by", "the", "will", "be", "for", "the", "year", "unless", "the", "determines", "that", "any", "quarter", "in", "was", "in", "a", "recession", "in", "which", "case", "the", "reference", "year", "will", "be", "the"],\n  "1": ["Bureau of Labor Statistics", "National Bureau of Economic Research"],\n  "2": ["US unemployment rate"],\n  "3": ["2035", "2035"],\n  "4": ["lower than 8 percent", "12 months prior to the beginning of the recession"]\n}',
  'openai/gpt-oss-120b'),
 ('On or before December 31, 2029, Berkshire Hathaway A shares (BRK.A), shall trade at no less than one million dollars ($1,000,000) per A equivalent share',
  '{\n  "0": [],\n  "1": [],\n  "2": ["Berkshire Hathaway A shares (BRK.A)"],\n  "3": ["On or before December 31, 2029"],\n  "4": ["shall trade at no less than one million dollars ($1,000,000) per A equivalent share"]\n}',
  'openai/gpt-oss-120b'),
 ('The amount of geologically-derived crude oil consumed by the United States in 2035 will be greater than the amount consumed in 2015.',
  '{0: ["will", "be", "than", "the", "amount", "consumed", "in"], 1: [], 2: ["the amount of geologically-derived crude oil consumed by the United States"], 3: ["2035", "2015"], 4: ["greater"]}',
  'openai/gpt-oss-120b'),
 ('Trips may be point to point outside of the city center with no requirement for any passenger to take over manual control of the vehicle.',
  '{0: [], 1: [], 2: ["Trips"], 3: [], 4: ["may be point to point outside of the city center with no requirement for any passenger to take over manual control of the vehicle"]}',
  'openai/gpt-oss-120b'),
 ('During the 500 years between 02015 and 02515, the Farsight Fund will return much less than what it has historically.',
  '{0: ["During", "the", "between", "and", "the", "will", "than", "what", "it", "has", "historically"], 1: ["Farsight Fund"], 2: ["Farsight Fund"], 3: ["02015", "02515", "500 years"], 4: ["return", "much less"]}',
  'openai/gpt-oss-120b'),
 ('The June, 2025 Labor Force Participation Rate and unemployment rate, reported by the U.S. Bureau of Labor Statistics, will be, respectively above 60 percent and below 7.5 percent.',
  '{0: ["The", "and", "reported", "by", "the", "will", "be,", "respectively", "and"], 1: ["U.S. Bureau of Labor Statistics"], 2: ["Labor Force Participation Rate", "unemployment rate"], 3: ["June, 2025"], 4: ["above 60 percent", "below 7.5 percent"]}',
  'openai/gpt-oss-120b'),
 ('The original URL for this prediction (www.longbets.org/601) will no longer be available in eleven years.',
  '{0: ["The", "for", "this", "prediction", "will", "in"], 1: [], 2: ["original URL", "(www.longbets.org/601)"], 3: ["eleven years"], 4: ["no longer be available"]}',
  'openai/gpt-oss-120b'),
 ('By the end of the year 2020, a professional sports team that is part of either the National Football League, the National Basketball Association, Major League Baseball, the National Hockey League, or Major League Soccer will integrate and have a woman as a team member/player.',
  '{0: ["By", "the", "end", "of", "the", "a", "that", "is", "part", "of", "either", "the", "the", "the", "or", "will"], 1: [], 2: ["professional sports team", "National Football League", "National Basketball Association", "Major League Baseball", "National Hockey League", "Major League Soccer"], 3: ["the end of the year 2020"], 4: ["integrate and have a woman as a team member/player"]}',
  'openai/gpt-oss-120b'),
 ('By 2018 the Euro (€) will not be the legal currency of France, Italy and Germany.',
  '{0: ["will"], 1: [], 2: ["the Euro (€)"], 3: ["By 2018"], 4: ["not be the legal currency of France, Italy and Germany"]}',
  'openai/gpt-oss-120b'),
 ('Over a ten-year period commencing on January 1, 2008, and ending on December 31, 2017, the S&P 500 will outperform a portfolio of funds of hedge funds, when performance is measured on a basis net of fees, costs and expenses.',
  '{0: ["Over", "a", "ten-year", "period", "commencing", "on", "and", "ending", "on", "the", "will", "a", "of", "of", "when", "performance", "is", "measured", "on", "a", "basis"], 1: [], 2: ["S&P 500"], 3: ["January 1, 2008", "December 31, 2017"], 4: ["outperform a portfolio of funds of hedge funds", "net of fees, costs and expenses"]}',
  'openai/gpt-oss-120b'),
 ('In 2108, an independent, sentient artificial intelligence will exist as a corporation, both providing its services as well as making all financial and strategic decisions.',
  '{\n  "0": ["In", "an", "will"],\n  "1": [],\n  "2": ["independent, sentient artificial intelligence"],\n  "3": ["2108"],\n  "4": ["exist as a corporation, both providing its services as well as making all financial and strategic decisions"]\n}',
  'openai/gpt-oss-120b'),
 ('The U.S Department of Transportation Bureau of Transportation Statistics (www.bts.gov) will report a lower number of total highway vehicle miles traveled in 2010 than in 2005.',
  '{0: ["will", "report", "a", "in", "than", "in"], 1: ["The U.S Department of Transportation Bureau of Transportation Statistics (www.bts.gov)"], 2: ["total highway vehicle miles traveled"], 3: ["2010", "2005"], 4: ["lower number"]}',
  'openai/gpt-oss-120b'),
 ('By 2025, the states will have voted on at least one constitutional amendment to cede US federal power to a global government.',
  '{\n  "0": ["will", "have", "voted", "on"],\n  "1": [],\n  "2": ["the states"],\n  "3": ["By 2025"],\n  "4": ["at least one constitutional amendment to cede US federal power to a global government"]\n}',
  'openai/gpt-oss-120b'),
 ('Over the next ten years, we will make measurable global progress in all five areas of the human condition: food, access to clean water, health, education, and the price of energy.',
  '{0: [Over, the, will, make, in, all, five, areas, of, the, human, condition:, and], 1: [we], 2: [next ten years], 3: [], 4: [measurable global progress], 5: [food, access to clean water, health, education, the price of energy]}',
  'openai/gpt-oss-120b'),
 ('By 02060 the total population of humans on earth will be less than it is today.',
  '{0: [], 1: [], 2: ["the total population of humans on earth"], 3: ["By 02060"], 4: ["will be less than it is today"]}',
  'openai/gpt-oss-120b'),
 ('The annual average cost between 2003 and Dec 31 2005 of the total retail price (commercial and residential) per Kilowatthour of electricity in the United States will rise as calculated by the U.S. Departmentof Energy in chained (inflation-adjusted) U.S. dollars.',
  '{0: ["The", "between", "and", "of", "the", "total", "retail", "price", "(commercial", "and", "residential)", "per", "Kilowatthour", "of", "electricity", "in", "the", "United", "States", "will", "as", "calculated", "by", "the", "in", "chained", "(inflation-adjusted)", "U.S.", "dollars"], 1: ["U.S. Departmentof Energy"], 2: ["annual average cost"], 3: ["2003", "Dec 31 2005"], 4: ["rise"]}',
  'openai/gpt-oss-120b'),
 ('Evidence of extraterrestrial intelligence within the solar system will be confirmed before evidence from several light-years away.',
  '{0: ["Evidence","of","extraterrestrial","intelligence","within","the","solar","system","will","be","confirmed","before","evidence","from","several","light-years","away"], 1: [], 2: [], 3: [], 4: []}',
  'openai/gpt-oss-120b'),
 ('The first discovery of extraterrestrial life will be someplace other than on a planet or on a satellite of a planet.',
  '{0: ["will","be"], 1: [], 2: ["The first discovery of extraterrestrial life"], 3: [], 4: ["someplace other than on a planet or on a satellite of a planet"]}',
  'openai/gpt-oss-120b'),
 ('By 2020, no one will have won a Nobel Prize for work on superstring theory, membrane theory, or some other unified theory describing all the forces of nature.',
  '{0: [], 1: [], 2: ["Nobel Prize"], 3: ["By 2020"], 4: ["no one will have won", "for work on", "superstring theory", "membrane theory", "or some other unified theory describing all the forces of nature"]}',
  'openai/gpt-oss-120b'),
 ('A bioterror or bioerror will lead to one million casualties in a single event within a six month period starting no later than Dec 31 02020.',
  '{0: ["A", "bioterror", "or", "bioerror", "will", "lead", "to", "in", "a", "single", "event", "within", "a", "six", "month", "period", "starting", "no", "later", "than"], 1: [], 2: [], 3: ["Dec 31 02020"], 4: ["one million casualties"]}',
  'openai/gpt-oss-120b'),
 ("The US men's soccer team will win the World Cup before the Red Sox win the World Series.",
  "{0: [will, before], 1: [The US men's soccer team], 2: [the Red Sox], 3: [], 4: [win the World Cup, win the World Series]}",
  'openai/gpt-oss-120b'),
 ('The universe will eventually stop expanding.',
  '{0: ["will", "eventually"], 1: [], 2: ["The universe"], 3: [], 4: ["stop expanding"]}',
  'openai/gpt-oss-120b'),
 ('By 2012, the Wall Street Journal and the New York Times will have referred to Russia as "the world leader in software development" or words to that effect.',
  '{0: ["By", "and", "will", "have", "referred", "to", "as"], 1: ["the Wall Street Journal", "the New York Times"], 2: ["Russia"], 3: ["2012"], 4: ["the world leader in software development", "or words to that effect"]}',
  'openai/gpt-oss-120b'),
 ('By 2030, commercial passengers will routinely fly in pilotless planes.',
  '{"0": ["will", "routinely"], "1": [], "2": ["commercial passengers"], "3": ["By 2030"], "4": ["fly in pilotless planes"]}',
  'openai/gpt-oss-120b'),
 ('A profitable video-on-demand service aimed at consumers will offer 10,000 titles to 5 million subscribers by 2010.',
  '{"0": ["will", "offer", "to", "by"], "1": ["A profitable video-on-demand service aimed at consumers"], "2": ["5 million subscribers"], "3": ["2010"], "4": ["10,000 titles"]}',
  'openai/gpt-oss-120b'),
 ("In a Google search of five keywords or phrases representing the top five news stories of 2007, weblogs will rank higher than the New York Times' Web site.",
  '{0: ["In", "a", "search", "of", "five", "keywords", "or", "phrases", "representing", "the", "top", "five", "news", "stories", "of", "will", "than", "the", "New York Times\' Web site"], 1: ["Google"], 2: ["weblogs"], 3: ["2007"], 4: ["rank higher"]}',
  'openai/gpt-oss-120b'),
 ('By 2029 no computer - or "machine intelligence" - will have passed the Turing Test.',
  '{0: ["By", "no", "will", "have", "the"], 1: [], 2: ["computer", "machine intelligence"], 3: ["2029"], 4: ["passed the Turing Test"]}',
  'openai/gpt-oss-120b'),
 ('World peace by October 30, 2150',
  '{0: ["by"], 1: [], 2: ["World peace"], 3: ["October 30, 2150"], 4: []}',
  'openai/gpt-oss-120b'),
 ('The market share of new electric light duty vehicles (per the US EIA definition) sold in the US will exceed 17% (>17% EV + PHEV market share) by the end of 2030.',
  '{0: ["The", "will", "by"], 1: [], 2: ["market share of new electric light duty vehicles (per the US EIA definition) sold in the US"], 3: ["end of 2030"], 4: ["exceed 17% (>17% EV + PHEV market share)"]}',
  'openai/gpt-oss-120b'),
 ('By 2043 there will be archaeological discoveries demonstrating equal or greater architectural advancement to the monuments at Göbekli Tepe, dating from before 11,000 BC.',
  '{0: ["there", "will be", "demonstrating"], 1: [], 2: ["archaeological discoveries"], 3: ["By 2043"], 4: ["equal or greater architectural advancement", "to the monuments at Göbekli Tepe", "dating from before 11,000 BC"]}',
  'openai/gpt-oss-120b'),
 ('It will come to light that the United States Federal Government has control of a significant portion of Bitcoin.',
  '{0: [It, will, come, to, light, that, the, has, of, a, significant, portion, of], 1: [United States Federal Government], 2: [Bitcoin], 3: [], 4: [control]}',
  'openai/gpt-oss-120b'),
 ('Before Jan 1 2028, a text on the NY Times Bestsellers list will be generated through AI / machine learning process.',
  '{0: ["Before", "a", "will", "be"], 1: [], 2: ["text on the NY Times Bestsellers list"], 3: ["Jan 1 2028"], 4: ["generated through AI / machine learning process"]}',
  'openai/gpt-oss-120b'),
 ('Authorship may be through a pen-name with non-human authorship revealed after listing is achieved.',
  '{0: ["may","be","through","a","pen-name","with","non-human","revealed","after","listing","is","achieved"], 1: [], 2: ["Authorship","authorship"], 3: [], 4: []}',
  'openai/gpt-oss-120b'),
 ('by 2035 there will be at least one public protest of more than 100 people in a G7 county against the switching off of a machine or software program on the grounds that it is sentient and has a right to live.',
  '{0: [], 1: [], 2: [], 3: ["by 2035"], 4: ["at least one public protest", "more than 100 people", "G7 county", "there", "will", "be", "of", "against", "the", "switching", "off", "of", "a", "machine", "or", "software", "program", "on", "the", "grounds", "that", "it", "is", "sentient", "and", "has", "a", "right", "to", "live."]}',
  'openai/gpt-oss-120b'),
 ('Poland will synchronize its first nuclear power plant BEFORE Germany exits coal power.',
  '{0: ["will", "synchronize", "its", "BEFORE"], 1: ["Poland"], 2: ["Germany"], 3: [], 4: ["first nuclear power plant", "exits coal power"]}',
  'openai/gpt-oss-120b'),
 ('Humanity will encounter super intelligent fully cybernetic extraterrestrial species before encountering super intelligent biological species.',
  '{"0": ["will", "before"], "1": ["Humanity"], "2": ["super intelligent fully cybernetic extraterrestrial species", "super intelligent biological species"], "3": [], "4": ["encounter", "encountering"]}',
  'openai/gpt-oss-120b'),
 ('Sam Bankman-Fried will be charged with a crime for his actions at FTX/Alameda.',
  '{"0": ["will", "be", "for", "his", "actions", "at"], "1": ["Sam Bankman-Fried"], "2": ["FTX/Alameda"], "3": [], "4": ["charged with a crime"]}',
  'openai/gpt-oss-120b'),
 ('The NEOM THE LINE building will not be completed as currently envisaged.',
  '{0: [], 1: [], 2: ["The NEOM THE LINE building"], 3: [], 4: ["will not be completed as currently envisaged"]}',
  'openai/gpt-oss-120b'),
 ('The SETI Institute will not announce the detection of a signal from an extraterrestrial civilization (that is, a signal that is unambiguously non-natural and does not originate from Earth) within the next 20 years.',
  '{0: ["of", "(that", "is,", "a", "signal", "that", "is", "unambiguously", "non-natural", "and", "does", "not", "originate", "from", "Earth)"], 1: ["The SETI Institute"], 2: ["a signal from an extraterrestrial civilization"], 3: ["within the next 20 years"], 4: ["will not announce the detection"]}',
  'openai/gpt-oss-120b'),
 ('From August 25, 2022 to the last trading day of August 2032, Alphabet stock will outperform Fundsmith hedge fund.',
  '{0: ["From", "to", "will"], 1: [], 2: ["Alphabet stock"], 3: ["August 25, 2022", "the last trading day of August 2032"], 4: ["outperform Fundsmith hedge fund"]}',
  'openai/gpt-oss-120b'),
 ('The US Bureau of Labor Statistics will report more than 4,951,360 jobs in the transport and warehousing sector for July 2030.',

In [19]:
column_names = ["Prediction Sentence", "Raw Response", "Model Name"]
results_df = pd.DataFrame(results, columns=column_names)
results_df

,Prediction Sentence,Raw Response,Model Name
0,"By January 1st, 2037, Tesla will have been the...","{0: [""By""], 1: [], 2: [""Tesla""], 3: [""January ...",openai/gpt-oss-120b
1,Private Nonfarm business productivity growth w...,"{0: [""will"", ""from"", ""to"", ""the"", ""of"", ""the"",...",openai/gpt-oss-120b
2,No Republican will be President of the USA bef...,"{0: [""will"", ""be"", ""before""], 1: [], 2: [""Pres...",openai/gpt-oss-120b
3,The market capitalization of Berkshire Hathawa...,"{0: [""The"", ""market"", ""capitalization"", ""of"", ...",openai/gpt-oss-120b
4,"Over a ten-year period commencing on July 1, 2...","{0: [""Over"", ""a"", ""commencing"", ""on"", ""and"", ""...",openai/gpt-oss-120b
...,...,...,...
82,A top Shakespearean editor or scholar will agr...,"{0: [""will"", ""agree"", ""that""], 1: [""A top Shak...",openai/gpt-oss-120b
83,"By 2030, more than 10 million people will be u...","{0: [""will"", ""be"", ""using"", ""wherein"", ""the"", ...",openai/gpt-oss-120b
84,"By January first, 2024, the price of Bitcoin, ...","{0: [""By"", ""the"", ""as"", ""quoted"", ""in"", ""the"",...",openai/gpt-oss-120b
85,"By 1 March 2023, a territorial coup will be at...","{0: [""By"", ""a"", ""territorial"", ""coup"", ""will"",...",openai/gpt-oss-120b
86,"At the end of 2030, there will be more mRNA-ba...","{\n ""0"": [""At"", ""the""],\n ""1"": [],\n ""2"": [...",openai/gpt-oss-120b

In [20]:
import ast, re
from typing import Any, Dict, List, Union

def parse_json_response_2(raw_response: Union[str, bytes, bytearray]) -> Dict[int, List[Any]]:
    """
    Parse a string that looks like a Python literal into a dictionary.
    Normalizes string keys to integer keys.
    Handles both quoted and unquoted list items.
    
    Args:
        raw_response: The raw string (or bytes/bytearray) containing Python-like literals.
    
    Returns:
        A dictionary with integer keys mapped to lists.
    
    Raises:
        ValueError: If the input cannot be parsed into the expected structure.
    """
    # Normalize input
    print(f"RAW: {raw_response}")
    if isinstance(raw_response, (bytes, bytearray)):
        raw_response = raw_response.decode("utf-8", errors="replace")
    if not isinstance(raw_response, str):
        raise ValueError(f"Expected str/bytes, got {type(raw_response).__name__}")
    
    text = raw_response.strip()
    
    # Fix unquoted list items: [word1, word2] -> ["word1", "word2"]
    def quote_unquoted_items(match):
        """Add quotes to unquoted words in lists."""
        content = match.group(1)
        # Split by comma, strip whitespace, and add quotes if not already quoted
        items = []
        for item in content.split(','):
            item = item.strip()
            if item and not (item.startswith('"') or item.startswith("'")):
                items.append(f'"{item}"')
            else:
                items.append(item)
        return '[' + ', '.join(items) + ']'
    
    # Apply the fix to all lists in the text
    text = re.sub(r'\[([^\[\]]+)\]', quote_unquoted_items, text)
    
    # Try to safely evaluate using ast.literal_eval
    try:
        obj = ast.literal_eval(text)
    except (SyntaxError, ValueError) as e:
        raise ValueError(f"Unable to parse input as Python literal: {e}\nProcessed text: {text}")
    
    # Ensure we have a dict
    if not isinstance(obj, dict):
        raise ValueError(f"Expected dict, got {type(obj).__name__}")
    
    # Normalize keys to integers
    normalized = {}
    for key, value in obj.items():
        try:
            int_key = int(key)
            normalized[int_key] = value
        except (ValueError, TypeError):
            # Keep non-convertible keys as-is (shouldn't happen with your format)
            normalized[key] = value
    
    return normalized

In [4]:
for idx, row in results_df.iterrows():
    raw_response = row['Raw Response']
    
    try:
        # Parse the raw JSON response
        cleaned_response = parse_json_response_2(raw_response)
        print(f"   CLEANED: {cleaned_response}")
        
        # Store as comma-separated strings
        results_df.at[idx, 'No Property'] = ', '.join(cleaned_response.get(0, []))
        results_df.at[idx, 'Source'] = ', '.join(cleaned_response.get(1, []))
        results_df.at[idx, 'Target'] = ', '.join(cleaned_response.get(2, []))
        results_df.at[idx, 'Date'] = ', '.join(cleaned_response.get(3, []))
        results_df.at[idx, 'Outcome'] = ', '.join(cleaned_response.get(4, []))
    except ValueError as e:
        print(f"   ERROR at index {idx}: {e}")
        # Set empty values for failed parses
        for col in ['No Property', 'Source', 'Target', 'Date', 'Outcome']:
            results_df.at[idx, col] = ''

results_df

NameError: name 'results_df' is not defined

In [22]:
extract_prediction_properties_path = "extract_prediction_properties/"
extract_prediction_properties_full_path = os.path.join(base_data_path, extract_prediction_properties_path)
DataProcessing.save_to_file(results_df, extract_prediction_properties_full_path, 'extracted_pps', 'csv')

Using file number: 3
Saving CSV file to: /Users/detraviousjamaribrinkley/Documents/Development/research_labs/uf_ds/predictions/notebook_experiments/../data/extract_prediction_properties/extracted_pps-v3.csv

> `notebook_experiments/load_vector_store.ipynb` because we want to use the properties extracted to search the vector store.

or

> `notebook_experiments/entity_resolution-source_target.ipynb` because we want to see predictions by source.

In [9]:
extract_prediction_properties_path = "extract_prediction_properties/extracted_pps-v3.csv"
extract_prediction_properties_full_path = os.path.join(base_data_path, extract_prediction_properties_path)
DataProcessing.load_from_file(extract_prediction_properties_full_path, 'csv', ',')

,Prediction Sentence,Raw Response,Model Name,No Property,Source,Target,Date,Outcome
0,"By January 1st, 2037, Tesla will have been the first company with 1 million vehicles that are capable of SAE Level 4 autonomy on over 90% of public roads in the contiguous United States, with human-level safety or better, and this capability will be usable by the general public commercially.","{0: [""By""], 1: [], 2: [""Tesla""], 3: [""January 1st, 2037""], 4: [""will"", ""have"", ""been"", ""the first company"", ""with"", ""1 million vehicles"", ""that"", ""are"", ""capable"", ""of"", ""SAE Level 4 autonomy"", ""on"", ""over"", ""90% of public roads"", ""in"", ""the"", ""contiguous United States"", ""with"", ""human-level safety"", ""or"", ""better"", ""and"", ""this capability"", ""will"", ""be"", ""usable"", ""by"", ""the"", ""general public"", ""commercially""]}",openai/gpt-oss-120b,NaN,NaN,NaN,NaN,NaN
1,Private Nonfarm business productivity growth will average over 1.8 percent per year from the first quarter (Q1) of 2020 to the last quarter of 2029 (Q4).,"{0: [""will"", ""from"", ""to"", ""the"", ""of"", ""the"", ""of"", ""the""], 1: [], 2: [""Private Nonfarm business productivity growth""], 3: [""first quarter (Q1) of 2020"", ""last quarter of 2029 (Q4)""], 4: [""average over 1.8 percent per year""]}",openai/gpt-oss-120b,"will, from, to, the, of, the, of, the",NaN,Private Nonfarm business productivity growth,"first quarter (Q1) of 2020, last quarter of 2029 (Q4)",average over 1.8 percent per year
2,"No Republican will be President of the USA before December 30, 2039.","{0: [""will"", ""be"", ""before""], 1: [], 2: [""President of the USA""], 3: [""December 30, 2039""], 4: [""No Republican""]}",openai/gpt-oss-120b,NaN,NaN,NaN,NaN,NaN
3,The market capitalization of Berkshire Hathaway will be greater than Tesla on Warren Buffett's 100th birthday.,"{0: [""The"", ""market"", ""capitalization"", ""of"", ""will"", ""be"", ""on""], 1: [], 2: [""Berkshire Hathaway"", ""Tesla""], 3: [""Warren Buffett's 100th birthday""], 4: [""greater than""]}",openai/gpt-oss-120b,"The, market, capitalization, of, will, be, on",NaN,"Berkshire Hathaway, Tesla",Warren Buffett's 100th birthday,greater than
4,"Over a ten-year period commencing on July 1, 2020, and ending on June 30, 2030, a portfolio of index funds invested broadly in US and International equities will outperform a portfolio managed by a sophisticated individual investor selecting stocks and funds.","{0: [""Over"", ""a"", ""commencing"", ""on"", ""and"", ""ending"", ""on""], 1: [], 2: [""a portfolio of index funds invested broadly in US and International equities"", ""a portfolio managed by a sophisticated individual investor selecting stocks and funds""], 3: [""ten-year period"", ""July 1, 2020"", ""June 30, 2030""], 4: [""will outperform""]}",openai/gpt-oss-120b,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
82,"A top Shakespearean editor or scholar will agree that Sir Thomas North is a reasonable candidate for authorship of at least one of Shakespeare’s source plays (including ""Arden of Faversham."")","{0: [""will"", ""agree"", ""that""], 1: [""A top Shakespearean editor or scholar""], 2: [""Sir Thomas North""], 3: [], 4: [""reasonable candidate for authorship of at least one of Shakespeare’s source plays (including \""Arden of Faversham.\"")""]}",openai/gpt-oss-120b,"will, agree, that",A top Shakespearean editor or scholar,Sir Thomas North,NaN,"reasonable candidate for authorship of at least one of Shakespeare’s source plays (including ""Arden of Faversham."")"
83,"By 2030, more than 10 million people will be using social networks wherein the content is store on servers or other storage that the user owns, with the network merely aggregating the content and providing a feed.","{0: [""will"", ""be"", ""using"", ""wherein"", ""the"", ""content"", ""is"", ""store"", ""on"", ""servers"", ""or"", ""other"", ""storage"", ""that"", ""the"", ""user"", ""owns"", ""with"", ""the"", ""network"", ""merely"", ""aggregating"", ""the"", ""content"", ""and"", ""providing"", ""a"", ""feed""], 1: [], 2: [""social networks""], 3: [""By 2030""], 4: [""more than 10 million people""]}",openai/gpt-oss-120b,"will, be, using, wherein, the, content, is, store, on, servers, or, other, storage, that, the, user, owns, with, the, network, merely, aggregating, the, content, and, providing, a, feed",NaN,social networks,By 2030,more than 10 million people
84,"By January first, 2024, the price of Bitcoin, as quoted in the Wall Street Journal, will be below 2500 USD.","{0: [""By"", ""the"", ""as"", ""quoted"", ""in"", ""the"", ""will"", ""be"", ""Wall Street Journal""], 1: [], 2: [""price of Bitcoin""], 3: [""January first, 2024""], 4: [""below 2500 USD""]}",openai/gpt-oss-120b,NaN,NaN,NaN,NaN,NaN
85,"By 1 March 2023, a territorial coup will be attempted by Boko Haram quasi-agents in the South of Nigeria, such that land rights of Southern Nigerians will be overwhelmed and the Fulani people will look to settle in the area.","{0: [""By"", ""a"", ""territorial"", ""coup"", ""will"", ""be"", ""attempted"", ""by"", ""in"", ""the"", ""South"", ""of"", ""Nigeria,"", ""such"", ""that"", ""and""], 1: [""Boko Haram quasi-agents""], 2: [""land rights of Southern Nigerians""], 3: [""1 March 2023""], 4: [""will be overwhelmed"", ""the Fulani people will look to settle in the area""]}",openai/gpt-oss-120b,"By, a, territorial, coup, will, be, attempted, by, in, the, South, of, Nigeria, , such, that, and",Boko Haram quasi-agents,land rights of Southern Nigerians,1 March 2023,"will be overwhelmed, the Fulani people will look to settle in the area"
86,"At the end of 2030, there will be more mRNA-based mAbs in clinical trials than those of protein-based mAbs.","{\n ""0"": [""At"", ""the""],\n ""1"": [],\n ""2"": [""mRNA-based mAbs""],\n ""3"": [""end of 2030""],\n ""4"": [""more mRNA-based mAbs in clinical trials than those of protein-based mAbs""]\n}",openai/gpt-oss-120b,"At, the",NaN,mRNA-based mAbs,end of 2030,more mRNA-based mAbs in clinical trials than those of protein-based mAbs