# Finetune BERT using TOLSA-M Data

In [1]:
import os
import sys
import torch
import random
import argparse

import numpy as np
import pandas as pd

from datasets import Dataset
from functools import partial
from datetime import datetime

from sklearn.model_selection import train_test_split

from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    DataCollatorWithPadding,
    Trainer,
    TrainingArguments,
    set_seed,
)

notebook_dir = os.getcwd()

sys.path.append(os.path.join(notebook_dir, '../'))

from metrics import EvaluationMetric
from data_processing import DataProcessing
from data_visualizing import DataVisualizing

In [2]:
pd.set_option('max_colwidth', 800)

## Notebook Configurations

In [3]:
dataset = '../data/combined_datasets/naacl_2026_submission/naacl_2026_submission.csv'
save_path = '../data/classification_results/naacl_2026_submission'
text_column = 'Base Sentence'
label_column = 'Ground Truth'
# model_name = 'bert-base-cased'
model_name = 'bert-large-cased'
seed = 300
val_size = 0.2
test_size = 0.2

max_length = 512 # Tokenization; in paper, can say this is static instead of dynamic (if we set accroding to each batch); need a lot so we can process mf climate
epochs = 1 # Number of full passes through the training dataset.
learning_rate = 2e-5
weight_decay = 0.01 # Regularization applied to model weights during optimization.
train_batch_size = 16 # Number of sentences processed together in each training batch.
eval_batch_size = 32 # Number of sentences processed together during validation or testing.
logging_steps = 25 # Print training loss and related information every N training steps.
finetuned_model_name = 'tolsa-bert'

# Use mixed-precision floating-point computation only when a GPU is available.
use_fp16 = torch.cuda.is_available()

base_data_path = DataProcessing.load_base_data_path(notebook_dir)

print(f"Base data path: {base_data_path}")
print(f"Dataset: {dataset}")
print(f"Model: {model_name}")
print(f"Seed: {seed}")

Base data path: /Users/detraviousjamaribrinkley/Documents/Development/research_labs/uf_ds/predictions/notebook_experiments/../data
Dataset: ../data/combined_datasets/naacl_2026_submission/naacl_2026_submission.csv
Model: bert-large-cased
Seed: 300

In [4]:
def set_all_seeds(seed):
    """Set random seeds for reproducible splits and BERT fine-tuning."""
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    set_seed(seed)

In [5]:
set_all_seeds(seed)

In [6]:
def resolve_path(base_data_path, file_path):  
    """Return an absolute path for either absolute or data-relative input."""  
    if os.path.isabs(file_path):  
        return file_path  
    return os.path.join(base_data_path, file_path)

## Experiment Setup

In [7]:
current_date = datetime.now().strftime("%Y-%m-%d")
dataset_filename = os.path.basename(dataset)
print(f"\nDataset filename: {dataset_filename}")

dataset_base = os.path.splitext(dataset_filename)[0]
print(f"Dataset base: {dataset_base}")

experiment_name = f"{dataset_base}_{current_date}"
print(f"Experiment name: {experiment_name}")

output_dir = os.path.join(
    save_path,
    experiment_name,
    f"seed{seed}",
    "in_domain",
    model_name,
)

print(f"Output directory: {output_dir}")
os.makedirs(output_dir, exist_ok=True)

Dataset filename: naacl_2026_submission.csv
Dataset base: naacl_2026_submission
Experiment name: naacl_2026_submission_2026-09-25
Output directory: ../data/classification_results/naacl_2026_submission/naacl_2026_submission_2026-09-25/seed300/in_domain/bert-large-cased

## Data: Load + Transform Labels

In [8]:
def load_dataset(base_data_path, dataset_path, text_column, label_column):  
    """Load, validate, and clean a sentence-classification dataset."""  
    print("\n" + "=" * 40)
    print("LOAD DATASET")
    print("=" * 40)
  
    data_path = resolve_path(base_data_path, dataset_path)  
    print(f"Dataset path: {data_path}")  
  
    # Uses your custom DataProcessing class to load the file
    df = DataProcessing.load_from_file(data_path, "csv", sep=",")

    df = df.sample(n=40, random_state=140).reset_index(drop=True)
  
    required_columns = [text_column, label_column]  
    missing_columns = [column for column in required_columns if column not in df.columns]  
  
    if missing_columns:  
        raise ValueError(  
            f"Required columns are missing: {missing_columns}\n"  
            f"Available columns: {list(df.columns)}"  
        )  
  
    original_count = len(df)  
  
    # Remove missing text and missing labels.  
    df = df.dropna(subset=[text_column, label_column]).copy()  
  
    # Ensure all text values are strings.  
    df[text_column] = df[text_column].astype(str).str.strip()  
  
    # Remove blank sentences.  
    df = df[df[text_column] != ""].copy()  
  
    # Standardize labels as strings before creating integer label IDs.  
    df[label_column] = df[label_column].astype(str).str.strip()  
  
    print(f"Original rows: {original_count}")  
    print(f"Usable rows:   {len(df)}")  
    print(f"Shape:         {df.shape}")  
  
    print("\nClass distribution:")  
    print(df[label_column].value_counts())  
  
    print(f"\nPreview:\n{df[[text_column, label_column]].head(5)}\n")  
  
    return df.reset_index(drop=True)

In [9]:
df = load_dataset(
    base_data_path=base_data_path,
    dataset_path=dataset,
    text_column=text_column,
    label_column=label_column,
)

========================================
LOAD DATASET
========================================
Dataset path: /Users/detraviousjamaribrinkley/Documents/Development/research_labs/uf_ds/predictions/notebook_experiments/../data/../data/combined_datasets/naacl_2026_submission/naacl_2026_submission.csv
Original rows: 40
Usable rows:   40
Shape:         (40, 3)

Class distribution:
Ground Truth
0    23
1    17
Name: count, dtype: int64

Preview:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     Base Sentence  \
0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   The goal average at Manchester City should stay the same in 2024-08-28, according to Analyst Sophia Rodriguez.
1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        And I think that trio now with Desmond Bain as well, like there is a world, I think, where they battle for even a one or a two seed if everything clicks.
2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Elisa will expand the use of this technology provided the pilot proves successful .
3                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Total public spending is close to 45 per cent of GDP, significantly above pre-pandemic norms, while the tax burden is already at a post-war high and projected to rise further.
4  A major shift in the upper-level pattern is expected, leading to increased precipitation as an amplified trough moves across the U.S. Expect mostly dry conditions on Thursday, with light lake effect rain/snow in the Great Lakes and isolated rain showers in South Florida. A substantial increase in precipitation is anticipated from Friday into early next week; higher elevation snow and lower elevation rain are likely in the Pacific Northwest and the Rockies. The GFS predicts heavier rains for southern Texas, while the ECMWF keeps southern Plains dry. Temperatures will be below normal by 10-20Â°F across the Plains to the Southeast, with lows potentially in the 30s, possibly setting records. Warm conditions will persist in the Northwest with high temperatures challenging daily records. As ...

  Ground Truth
0            1
1            1
2            1
3            1
4            1

In [10]:
df

,Base Sentence,Ground Truth,Dataset Name
0,"The goal average at Manchester City should stay the same in 2024-08-28, according to Analyst Sophia Rodriguez.",1,synthetic
1,"And I think that trio now with Desmond Bain as well, like there is a world, I think, where they battle for even a one or a two seed if everything clicks.",1,yt
2,Elisa will expand the use of this technology provided the pilot proves successful .,1,financial_phrasebank
3,"Total public spending is close to 45 per cent of GDP, significantly above pre-pandemic norms, while the tax burden is already at a post-war high and projected to rise further.",1,news_api
4,"A major shift in the upper-level pattern is expected, leading to increased precipitation as an amplified trough moves across the U.S. Expect mostly dry conditions on Thursday, with light lake effect rain/snow in the Great Lakes and isolated rain showers in South Florida. A substantial increase in precipitation is anticipated from Friday into early next week; higher elevation snow and lower elevation rain are likely in the Pacific Northwest and the Rockies. The GFS predicts heavier rains for southern Texas, while the ECMWF keeps southern Plains dry. Temperatures will be below normal by 10-20Â°F across the Plains to the Southeast, with lows potentially in the 30s, possibly setting records. Warm conditions will persist in the Northwest with high temperatures challenging daily records. As ...",1,mf_climate
5,"Some of the most recent technology deliveries include refinery technology to Anrak Aluminium , an iron ore pelletizing plant to Tata Steel and iron ore sintering plants to Bhushan Steel .",0,financial_phrasebank
6,Metso estimates the need for personnel reductions to amount to 25 people .,1,financial_phrasebank
7,"A warming trend is expected across most of the continental United States (CONUS) by the end of the week into next weekend, with temperatures trending above average, particularly near the Canadian border and the Gulf Coast. Rainfall will be modest to locally heavy, spreading from the Lower Mississippi Valley northeastward from Thursday to Sunday, alongside repetitive precipitation in the Pacific Northwest due to multiple systems. A low pressure system is predicted to move northeastward towards the Midwest, weakening by day 6, while a second low pressure system is expected to develop off the Mid-Atlantic coast and track northward by day 7. The Northwest Gulf Coast may experience modest rainfall totals, with some areas potentially seeing locally heavy amounts. In the Northwest, snow level...",1,mf_climate
8,Maybe it would have athletes skiing on fake snow down parched slopes.,0,chronicle2050
9,"When Judge Ketanji Brown Jackson’s Supreme Court nomination reaches the Senate floor soon, every Republican who votes against her confirmation will be complicit in the abuse that the Republican members of the Judiciary Committee heaped on her.",0,chronicle2050
10,"On 02/27/2027, Dr. Liam Chen speculates that the graduation rate at Harvard University will likely increase.",1,synthetic
11,"In Finland , Alma Media will focus on quality and developing chain operations .",0,financial_phrasebank
12,"On 08/21/2024, Meteorologist Emily Chen speculates that the temperature at New York will likely increase.",1,synthetic
13,"They do have a higher ceiling, in my opinion, than Chicago, Washington, and Brooklyn, but I don't think they're going to make the play-in.",1,yt
14,"Kai Tulonen , Chief Technology Officer , SysOpen Digia says : `` Mobility Business Suite represents a significant milestone in the company 's offering to the telecommunications industry .",0,financial_phrasebank
15,"The company said production volumes so far indicate the circuit is capable of the targeted output rate of 60,000 tonnes per day , or 22 million tonnes a year .",0,financial_phrasebank
16,"( ADP News ) - Feb 4 , 2009 - Finnish broadband data communication systems and solutions company Teleste Oyj ( HEL : TLT1V ) said today its net profit decreased to EUR 5.5 million ( USD 7.2 m ) for 2008 from EUR 9.4 million for 200",0,financial_phrasebank
17,"On August 25, 2025, Dr. Patel speculates that the average physical activity levels among college students will increase.",1,synthetic
18,"We bring a new , committed leadership and business and strategic know-how to the company that we buy .",0,financial_phrasebank
19,prognosticators confidently declaring how the draft’s top prospects will fare as pros and which teams will select them.,0,chronicle2050
20,WSJ891102-0166 = 891102 891102-0166.,0,timebank
21,"I'm getting out,'"" says Kurt Brouwer of Brouwer amp Janachowski, a San Francisco investment adviser.",0,timebank
22,"Heavy precipitation is expected for California, particularly on Monday and Tuesday, as a deep southern stream trough moves inland. This will bring soaking rain and heavy high elevation snow, with effects spilling over into the Sierras and northern Rockies. Arctic air is re-establishing across the northern tier of the U.S. There is uncertainty regarding the timing of the West Coast precipitation, with the forecast closely following ensemble means, especially the ECMWF ensemble mean. Recent model runs indicate a colder forecast compared to previous milder predictions as the northern stream becomes more dominant over the central and eastern U.S. Despite favorable conditions for California precipitation, additional storms are needed for effective drought relief, as current measures show th...",1,mf_climate
23,"PCS Digital Guatemala has been using Tecnomen 's prepaid system in Telgua fixed networks as well as code division multiple access , or CDMA , and global system for mobile communication , or GSM , since 2003 .",0,financial_phrasebank
24,"Currently, Avon, based in Santa Monica, Calif., has 3.3 million common shares outstanding.",0,timebank
25,This curve in the path is when I found out who the murderer is; that oak tree is the one I stared at after I hit pause and contemplated some tiny morsel of life wisdom.,0,chronicle2050
26,Thank you for being a Times subscriber.,0,chronicle2050
27,Professor Sofia Rodriguez forecasts that the graduation rate at the University of California will drop in 2025.,1,synthetic
28,"Stormy pattern with multiple hazards expected across the nation from March 8-12. A lead system will bring widespread moisture and potential snow/ice threats to the east-central and eastern states, with heavy snowfall of 1 to 2 feet likely in the central and northern Rockies. Widespread rain and thunderstorms developing from eastern Texas to the southern Appalachians, leading to flooding issues, as moist Gulf air surges northward ahead of a strong cold front. Heavy precipitation expected in the Northeast on March 10, and in the lower and mid-Mississippi Valley and Tennessee and Ohio Valleys on March 8-9. Additional heavy rain forecasted in the Central and Southern Plains on March 12, and heavy snow in the Central Plains and Great Lakes region on March 9-10. Risk of severe weather, inclu...",1,mf_climate
29,The American Heart Association forecasts that the heart disease rates at local hospitals potentially decrease in Q4 of 2028.,1,synthetic
30,"The newest technology may be impressive, but sometimes simpler solutions are more effective.",0,chronicle2050
31,"Dr. Ryan Thompson predicts on Aug 21, 2024, the humidity at New York City may rise.",1,synthetic
32,He confirmed his view on July 6 .,0,financial_phrasebank
33,"About a decade ago, companies in the United States began offering pregnant women noninvasive prenatal testing for chromosomal abnormalities in a fetus, mainly to detect Down syndrome.",0,chronicle2050
34,"In 2007 , Marimekko has also opened concept stores in Yokohama and Nagoya , central Japan , in Silver Spring in metropolitan Washington DC , USA , in Graz , central Austria , and in Aalborg , northern Denmark .",0,financial_phrasebank
35,The company confirmed its estimate for lower revenue for the whole 2009 than the year-ago EUR93 .9 m as given in the interim report on 5 August 2009 .,0,financial_phrasebank
36,"Post-tropical cyclone Hermine is expected to linger off the mid-Atlantic/Northeast coast, while a stalled front will bring active weather to the central/northern plains and Midwest. The cyclone's movement will be slow, remaining off the coast for several days. A large-scale trough will persist across the western U.S., moving east slowly, with low-amplitude waves impacting the northwestern U.S. and eventually the plains. Model predictions suggest significant variations regarding a low-pressure system west of Central America, which may bring tropical moisture to the Baja California region and potentially the southwestern U.S. by days 5-7. Heavy rainfall and strong winds are expected along the mid-Atlantic/Northeast coast due to Hermine, with the possibility of coastal flooding. The centr...",1,mf_climate
37,Uponor has initiated actions to attempt to recover the cost of the replacement program from the supplier of the clamps as well as its insurance company .,0,financial_phrasebank
38,"Citigroup observed that the operating income at Microsoft had remained stable from February 14, 2023, to February 14, 2024.",0,synthetic
39,"@ A Wall Street Journal News Roundup 10/30/89 WALL STREET JOURNAL (J) FREST CANDA EUROP JAPAN COMMODITY NEWS, FARM PRODUCTS (CMD) STOCK MARKET, OFFERINGS (STK) PRECIOUS METALS, STONES, GOLD, SILVER (PCS)",0,timebank

In [11]:
def create_label_mapping(df, label_column):
    """Create BERT-compatible integer IDs for exactly two labels."""
    unique_labels = sorted(df[label_column].unique().tolist())

    if len(unique_labels) != 2:
        raise ValueError(
            "This pipeline currently supports binary classification only. "
            f"Found {len(unique_labels)} labels: {unique_labels}"
        )

    label_to_id = {
        label: index
        for index, label in enumerate(unique_labels)
    }

    id_to_label = {
        index: label
        for label, index in label_to_id.items()
    }

    print("\nLabel mapping:")
    for label, label_id in label_to_id.items():
        print(f"  {label_id} -> {label}")

    return label_to_id, id_to_label

In [12]:
label_to_id, id_to_label = create_label_mapping(
    df=df,
    label_column=label_column,
)
label_to_id, id_to_label

Label mapping:
  0 -> 0
  1 -> 1

({'0': 0, '1': 1}, {0: '0', 1: '1'})

In [13]:
num_labels = len(label_to_id)

if num_labels < 2:
    raise ValueError(
        "Sentence classification requires at least two unique labels."
    )

In [14]:
label_id_column = "_label_id"
df[label_id_column] = df[label_column].map(label_to_id).astype(int)

print(f"Usable rows:   {len(df)}")
print(f"Shape:         {df.shape}")  

print("\nClass distribution:")  
print(df[label_id_column].value_counts())  

df[[text_column, label_id_column]].head(5)

Usable rows:   40
Shape:         (40, 4)

Class distribution:
_label_id
0    23
1    17
Name: count, dtype: int64

,Base Sentence,_label_id
0,"The goal average at Manchester City should stay the same in 2024-08-28, according to Analyst Sophia Rodriguez.",1
1,"And I think that trio now with Desmond Bain as well, like there is a world, I think, where they battle for even a one or a two seed if everything clicks.",1
2,Elisa will expand the use of this technology provided the pilot proves successful .,1
3,"Total public spending is close to 45 per cent of GDP, significantly above pre-pandemic norms, while the tax burden is already at a post-war high and projected to rise further.",1
4,"A major shift in the upper-level pattern is expected, leading to increased precipitation as an amplified trough moves across the U.S. Expect mostly dry conditions on Thursday, with light lake effect rain/snow in the Great Lakes and isolated rain showers in South Florida. A substantial increase in precipitation is anticipated from Friday into early next week; higher elevation snow and lower elevation rain are likely in the Pacific Northwest and the Rockies. The GFS predicts heavier rains for southern Texas, while the ECMWF keeps southern Plains dry. Temperatures will be below normal by 10-20Â°F across the Plains to the Southeast, with lows potentially in the 30s, possibly setting records. Warm conditions will persist in the Northwest with high temperatures challenging daily records. As ...",1

## Data Splits: Create and Save Train/Val/Test

In [15]:
def split_dataset(df, label_id_column, test_size, val_size, seed):
    """Create stratified train, validation, and optional test data splits."""
    print("\n" + "=" * 40)
    print("CREATE DATA SPLITS")
    print("=" * 40)

    if not 0 <= test_size < 1:
        raise ValueError("test_size must be at least 0 and less than 1.")

    if not 0 < val_size < 1:
        raise ValueError("val_size must be greater than 0 and less than 1.")

    if test_size > 0:
        train_val_df, test_df = train_test_split(
            df,
            test_size=test_size,
            random_state=seed,
            stratify=df[label_id_column],
        )

        adjusted_val_size = val_size / (1 - test_size)
    else:
        train_val_df = df.copy()
        test_df = None
        adjusted_val_size = val_size

    train_df, val_df = train_test_split(
        train_val_df,
        test_size=adjusted_val_size,
        random_state=seed,
        stratify=train_val_df[label_id_column],
    )

    train_df = train_df.reset_index(drop=True)
    val_df = val_df.reset_index(drop=True)

    if test_df is not None:
        test_df = test_df.reset_index(drop=True)

    print(f"Train size: {len(train_df)}")
    print(f"Validation size: {len(val_df)}")
    print(f"Test size: {len(test_df) if test_df is not None else 0}")

    return train_df, val_df, test_df

In [16]:
train_df, val_df, test_df = split_dataset(
    df=df,
    label_id_column=label_id_column,
    test_size=test_size,
    val_size=val_size,
    seed=seed,
)

========================================
CREATE DATA SPLITS
========================================
Train size: 24
Validation size: 8
Test size: 8

In [17]:
def save_data_splits(train_df, val_df, test_df, output_dir):
    """Save the exact train, validation, and test splits used."""
    split_dir = os.path.join(output_dir, "data_splits")
    os.makedirs(split_dir, exist_ok=True)

    DataProcessing.save_to_file(
        train_df,
        path=split_dir,
        prefix="x_y_train_set",
        save_file_type="csv",
        include_version=False,
    )

    DataProcessing.save_to_file(
        val_df,
        path=split_dir,
        prefix="x_y_val_set",
        save_file_type="csv",
        include_version=False,
    )

    if test_df is not None:
        DataProcessing.save_to_file(
            test_df,
            path=split_dir,
            prefix="x_y_test_set",
            save_file_type="csv",
            include_version=False,
        )

    print(f"✓ Saved data splits to: {split_dir}")

In [18]:
save_data_splits(
    train_df=train_df,
    val_df=val_df,
    test_df=test_df,
    output_dir=output_dir,
)

Saving CSV file to: ../data/classification_results/naacl_2026_submission/naacl_2026_submission_2026-09-25/seed300/in_domain/bert-large-cased/data_splits/x_y_train_set.csv
Saving CSV file to: ../data/classification_results/naacl_2026_submission/naacl_2026_submission_2026-09-25/seed300/in_domain/bert-large-cased/data_splits/x_y_val_set.csv
Saving CSV file to: ../data/classification_results/naacl_2026_submission/naacl_2026_submission_2026-09-25/seed300/in_domain/bert-large-cased/data_splits/x_y_test_set.csv
✓ Saved data splits to: ../data/classification_results/naacl_2026_submission/naacl_2026_submission_2026-09-25/seed300/in_domain/bert-large-cased/data_splits

## HF Preparation Dataset for Tokenization

In [19]:
def dataframe_to_hf_dataset(df, text_column, label_id_column):
    """Convert a pandas DataFrame to a Hugging Face Dataset."""
    hf_df = df[[text_column, label_id_column]].copy()
    hf_df = hf_df.rename(columns={label_id_column: "labels"})

    return Dataset.from_pandas(hf_df, preserve_index=False)

In [20]:
train_dataset = dataframe_to_hf_dataset(
    train_df,
    text_column=text_column,
    label_id_column=label_id_column,
)

if val_df is not None:
    val_dataset = dataframe_to_hf_dataset(
        val_df,
        text_column=text_column,
        label_id_column=label_id_column
    )

if test_df is not None:
    test_dataset = dataframe_to_hf_dataset(
        test_df,
        text_column=text_column,
        label_id_column=label_id_column
    )

## BERT: Tokenize + Finetune

### Tokenize

In [21]:
def tokenize_batch(examples, tokenizer, text_column, max_length):
    """Tokenize a batch of sentences using a pretrained tokenizer.
    Apply truncation and maximum sequence length constraints.
    Return tokenized model inputs (e.g., input IDs and attention masks).
    """
    return tokenizer(
        examples[text_column],
        truncation=True,
        max_length=max_length,
    )

In [22]:
def tokenize_dataset(
    dataset, 
    tokenizer, 
    text_column, 
    max_length, 
    split_name="dataset", 
    original_df=None, 
    label_column=None, 
    show_examples=False
):
    """Tokenize all sentences in a Hugging Face dataset.
    Apply preprocessing and convert text into BERT-compatible inputs.
    Optionally display tokenization examples for inspection.
    """
    # Use functools.partial to pass the extra arguments without nesting
    tokenized_dataset = dataset.map(
        partial(
            tokenize_batch, 
            tokenizer=tokenizer, 
            text_column=text_column, 
            max_length=max_length
        ),
        batched=True,
        remove_columns=[text_column],
    )

    # Print tokenized count
    print(f"✓ Tokenized {split_name} sentences: {len(tokenized_dataset)}")

    # Print mini-example if requested
    if show_examples and original_df is not None and label_column is not None:
        print("\n" + "=" * 40)
        print(f"TOKENIZATION MINI EXAMPLE — 3 {split_name} samples")
        print("=" * 40)

        # Ensure we don't try to print more examples than exist
        num_examples = min(3, len(tokenized_dataset))
        
        for i in range(num_examples):
            example = tokenized_dataset[i]
            original_text = original_df.iloc[i][text_column]
            label = original_df.iloc[i][label_column]

            tokens = tokenizer.convert_ids_to_tokens(example["input_ids"])
            num_real_tokens = sum(example["attention_mask"])
            num_pad_tokens = len(example["attention_mask"]) - num_real_tokens

            print(f"\n--- Example {i + 1} ---")
            print(f"  Original sentence : {original_text}")
            print(f"  Label ID          : {label}")
            print(f"  Tokens            : {tokens[:num_real_tokens]}")
            print(f"  input_ids         : {example['input_ids'][:num_real_tokens]}")
            print(f"  attention_mask    : {example['attention_mask'][:num_real_tokens]} "
                  f"(+ {num_pad_tokens} zeros for padding)")
            print(f"  Total length      : {len(example['input_ids'])} (max_length={max_length})")

    return tokenized_dataset

In [23]:
tokenizer = AutoTokenizer.from_pretrained(model_name)

tokenized_train_dataset = tokenize_dataset(
    dataset=train_dataset,
    tokenizer=tokenizer,
    text_column=text_column,
    max_length=max_length,
    split_name="training",
    original_df=train_df,
    label_column=label_id_column,
    show_examples=True  # This triggers the mini-example printout
)

if val_df is not None and val_dataset:
    tokenized_val_dataset = tokenize_dataset(
        dataset=val_dataset,
        tokenizer=tokenizer,
        text_column=text_column,
        max_length=max_length,
        split_name="validation"
    )
else:
    tokenized_val_dataset = None
    print("✓ Tokenized validation sentences: 0")

if test_df is not None and test_dataset:
    tokenized_test_dataset = tokenize_dataset(
        dataset=test_dataset,
        tokenizer=tokenizer,
        text_column=text_column,
        max_length=max_length,
        split_name="test"
    )
else:
    tokenized_test_dataset = None
    print("✓ Tokenized test sentences:       0")

tokenized_train_dataset, tokenized_val_dataset, tokenized_test_dataset

tokenizer_config.json:   0%|          | 0.00/49.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/762 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

Map:   0%|          | 0/24 [00:00<?, ? examples/s]

✓ Tokenized training sentences: 24

========================================
TOKENIZATION MINI EXAMPLE — 3 training samples
========================================

--- Example 1 ---
  Original sentence : When Judge Ketanji Brown Jackson’s Supreme Court nomination reaches the Senate floor soon, every Republican who votes against her confirmation will be complicit in the abuse that the Republican members of the Judiciary Committee heaped on her.
  Label ID          : 0
  Tokens            : ['[CLS]', 'When', 'Judge', 'Ke', '##tan', '##ji', 'Brown', 'Jackson', '’', 's', 'Supreme', 'Court', 'nomination', 'reaches', 'the', 'Senate', 'floor', 'soon', ',', 'every', 'Republican', 'who', 'votes', 'against', 'her', 'confirmation', 'will', 'be', 'com', '##p', '##licit', 'in', 'the', 'abuse', 'that', 'the', 'Republican', 'members', 'of', 'the', 'Judiciary', 'Committee', 'heap', '##ed', 'on', 'her', '.', '[SEP]']
  input_ids         : [101, 1332, 5274, 26835, 5108, 3454, 2671, 3160, 787, 188, 3732, 2031, 6294, 5965, 1103, 3279, 1837, 1770, 117, 1451, 3215, 1150, 3667, 1222, 1123, 15468, 1209, 1129, 3254, 1643, 18726, 1107, 1103, 6704, 1115, 1103, 3215, 1484, 1104, 1103, 25932, 2341, 19943, 1174, 1113, 1123, 119, 102]
  attention_mask    : [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1] (+ 0 zeros for padding)
  Total length      : 48 (max_length=512)

--- Example 2 ---
  Original sentence : Some of the most recent technology deliveries include refinery technology to Anrak Aluminium , an iron ore pelletizing plant to Tata Steel and iron ore sintering plants to Bhushan Steel .
  Label ID          : 0
  Tokens            : ['[CLS]', 'Some', 'of', 'the', 'most', 'recent', 'technology', 'deliver', '##ies', 'include', 're', '##finery', 'technology', 'to', 'An', '##rak', 'Al', '##umi', '##nium', ',', 'an', 'iron', 'ore', 'p', '##elle', '##ti', '##zing', 'plant', 'to', 'Ta', '##ta', 'Steel', 'and', 'iron', 'ore', 'sin', '##tering', 'plants', 'to', 'B', '##hus', '##han', 'Steel', '.', '[SEP]']
  input_ids         : [101, 1789, 1104, 1103, 1211, 2793, 2815, 7852, 1905, 1511, 1231, 23011, 2815, 1106, 1760, 16971, 2586, 14088, 14553, 117, 1126, 3926, 12327, 185, 11682, 3121, 6185, 2582, 1106, 22515, 1777, 8180, 1105, 3926, 12327, 11850, 9930, 3546, 1106, 139, 8827, 3822, 8180, 119, 102]
  attention_mask    : [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1] (+ 0 zeros for padding)
  Total length      : 45 (max_length=512)

--- Example 3 ---
  Original sentence : Total public spending is close to 45 per cent of GDP, significantly above pre-pandemic norms, while the tax burden is already at a post-war high and projected to rise further.
  Label ID          : 1
  Tokens            : ['[CLS]', 'Total', 'public', 'spending', 'is', 'close', 'to', '45', 'per', 'cent', 'of', 'GDP', ',', 'significantly', 'above', 'pre', '-', 'pan', '##de', '##mic', 'norms', ',', 'while', 'the', 'tax', 'burden', 'is', 'already', 'at', 'a', 'post', '-', 'war', 'high', 'and', 'projected', 'to', 'rise', 'further', '.', '[SEP]']
  input_ids         : [101, 8653, 1470, 5369, 1110, 1601, 1106, 2532, 1679, 9848, 1104, 14781, 117, 5409, 1807, 3073, 118, 13316, 2007, 7257, 19600, 117, 1229, 1103, 3641, 11904, 1110, 1640, 1120, 170, 2112, 118, 1594, 1344, 1105, 11479, 1106, 3606, 1748, 119, 102]
  attention_mask    : [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1] (+ 0 zeros for padding)
  Total length      : 41 (max_length=512)

Map:   0%|          | 0/8 [00:00<?, ? examples/s]

✓ Tokenized validation sentences: 8

Map:   0%|          | 0/8 [00:00<?, ? examples/s]

✓ Tokenized test sentences: 8

(Dataset({
     features: ['labels', 'input_ids', 'token_type_ids', 'attention_mask'],
     num_rows: 24
 }),
 Dataset({
     features: ['labels', 'input_ids', 'token_type_ids', 'attention_mask'],
     num_rows: 8
 }),
 Dataset({
     features: ['labels', 'input_ids', 'token_type_ids', 'attention_mask'],
     num_rows: 8
 }))

### Finetune

#### Step 1: Load Pretrained BERT

From the D2L tutorial [1]: BERT is pretrained on BookCorpus + English Wikipedia (800M + 2.5B words) using MLM and NSP tasks.

Here we are **not pretraining**. We load pretrained BERT weights and attach a new binary classification head on top.

The warning *"Some weights not initialized"* is expected. It refers to `classifier.weight` and `classifier.bias`, which are randomly initialized and learned during fine-tuning.

From the Hugging Face tutorial: this is called **transfer learning**.

The model configuration includes:

- `num_labels=2`: binary classification
- `label2id`: mapping from original labels to integer IDs
- `id2label`: reverse mapping from integer IDs to original labels

The printed parameter counts show:

- **Total parameters**: all pretrained BERT parameters plus the new classification-head parameters
- **Trainable parameters**: parameters updated during fine-tuning

In [24]:
def load_pretrained_bert_classifier(model_name, label_to_id, id_to_label):
    """Load pretrained BERT and add a randomly initialized binary classifier."""
    print(f"\n[1/5] Loading pretrained BERT checkpoint: {model_name}")
    print("      num_labels  : 2 (binary classification)")
    print(f"      label2id    : {label_to_id}")
    print(f"      id2label    : {id_to_label}")

    model = AutoModelForSequenceClassification.from_pretrained(
        model_name,
        num_labels=2,
        label2id=label_to_id,
        id2label=id_to_label,
    )

    total_params = sum(parameter.numel() for parameter in model.parameters())
    trainable_params = sum(
        parameter.numel()
        for parameter in model.parameters()
        if parameter.requires_grad
    )

    print(f"      Total parameters     : {total_params:,}")
    print(f"      Trainable parameters : {trainable_params:,}")

    return model

In [25]:
model = load_pretrained_bert_classifier(model_name, label_to_id, id_to_label)
model

[1/5] Loading pretrained BERT checkpoint: bert-large-cased
      num_labels  : 2 (binary classification)
      label2id    : {'0': 0, '1': 1}
      id2label    : {0: '0', 1: '1'}

model.safetensors:   0%|          | 0.00/1.34G [00:00<?, ?B/s]

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-large-cased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

      Total parameters     : 333,581,314
      Trainable parameters : 333,581,314

BertForSequenceClassification(
  (bert): BertModel(
    (embeddings): BertEmbeddings(
      (word_embeddings): Embedding(28996, 1024, padding_idx=0)
      (position_embeddings): Embedding(512, 1024)
      (token_type_embeddings): Embedding(2, 1024)
      (LayerNorm): LayerNorm((1024,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): BertEncoder(
      (layer): ModuleList(
        (0-23): 24 x BertLayer(
          (attention): BertAttention(
            (self): BertSdpaSelfAttention(
              (query): Linear(in_features=1024, out_features=1024, bias=True)
              (key): Linear(in_features=1024, out_features=1024, bias=True)
              (value): Linear(in_features=1024, out_features=1024, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=1024, out_features=1024, bias=True)
              (LayerNorm): LayerNorm((1024,), eps=1e-12, elementwise_affine=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
          )
          (intermediate): BertIntermediate(
            (dense): Linear(in_features=1024, out_features=4096, bias=True)
            (intermediate_act_fn): GELUActivation()
          )
          (output): BertOutput(
            (dense): Linear(in_features=4096, out_features=1024, bias=True)
            (LayerNorm): LayerNorm((1024,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
    )
    (pooler): BertPooler(
      (dense): Linear(in_features=1024, out_features=1024, bias=True)
      (activation): Tanh()
    )
  )
  (dropout): Dropout(p=0.1, inplace=False)
  (classifier): Linear(in_features=1024, out_features=2, bias=True)
)

#### Step 2: Configure Training Arguments

From the Hugging Face tutorial: `TrainingArguments` controls **how** the `Trainer` fine-tunes the model, including the learning rate, batch sizes, epochs, evaluation frequency, checkpoint saving, and logging.

From D2L [1]: BERT uses Adam optimization with weight decay.

| Argument | Meaning |
|---|---|
| `output_dir` | Location for intermediate training checkpoints |
| `learning_rate` | Step size used to update BERT parameters and the new classification head |
| `per_device_train_batch_size` | Number of training sentences processed together per device |
| `per_device_eval_batch_size` | Number of validation sentences processed together per device |
| `num_train_epochs` | Number of complete passes through the training dataset |
| `weight_decay` | Regularization penalty applied to model weights |
| `eval_strategy="epoch"` | Evaluate after every complete pass through the training data |
| `save_strategy="epoch"` | Save a checkpoint after every epoch |
| `logging_strategy="steps"` | Print training information every specified number of training steps |
| `logging_steps` | Number of training steps between log outputs |
| `save_total_limit=1` | Keep only one checkpoint on disk |
| `fp16` | Use mixed-precision computation when a CUDA GPU is available |
| `report_to=[]` | Do not send logs to external tracking services |
| `seed` | Random seed for reproducibility |

In [26]:
def configure_finetuning_arguments(
    output_dir,
    learning_rate,
    train_batch_size,
    eval_batch_size,
    epochs,
    weight_decay,
    logging_steps,
    seed,
):
    """Configure Hugging Face settings for BERT fine-tuning."""
    checkpoint_dir = os.path.join(output_dir, "training_checkpoints")
    use_fp16 = torch.cuda.is_available()

    print("\n[2/5] Configuring TrainingArguments")
    print(f"      Output dir          : {checkpoint_dir}")
    print(f"      Learning rate       : {learning_rate}")
    print(f"      Train batch size    : {train_batch_size}")
    print(f"      Eval batch size     : {eval_batch_size}")
    print(f"      Epochs              : {epochs}")
    print(f"      Weight decay        : {weight_decay}")
    print("      Eval strategy       : epoch")
    print("      Save strategy       : epoch")
    print(f"      Logging steps       : {logging_steps}")
    print("      Save total limit    : 1")
    print(f"      FP16               : {use_fp16}")
    print(f"      Seed                : {seed}")

    training_args = TrainingArguments(
        output_dir=checkpoint_dir,
        learning_rate=learning_rate,
        per_device_train_batch_size=train_batch_size,
        per_device_eval_batch_size=eval_batch_size,
        num_train_epochs=epochs,
        weight_decay=weight_decay,
        eval_strategy="epoch",
        save_strategy="epoch",
        logging_strategy="steps",
        logging_steps=logging_steps,
        save_total_limit=1,
        fp16=use_fp16,
        report_to=[],
        seed=seed,
    )

    return training_args

In [27]:
training_args = configure_finetuning_arguments(
    output_dir,
    learning_rate,
    train_batch_size,
    eval_batch_size,
    epochs,
    weight_decay,
    logging_steps,
    seed
)

training_args

[2/5] Configuring TrainingArguments
      Output dir          : ../data/classification_results/naacl_2026_submission/naacl_2026_submission_2026-09-25/seed300/in_domain/bert-large-cased/training_checkpoints
      Learning rate       : 2e-05
      Train batch size    : 16
      Eval batch size     : 32
      Epochs              : 1
      Weight decay        : 0.01
      Eval strategy       : epoch
      Save strategy       : epoch
      Logging steps       : 25
      Save total limit    : 1
      FP16               : False
      Seed                : 300

TrainingArguments(
_n_gpu=1,
accelerator_config={'split_batches': False, 'dispatch_batches': None, 'even_batches': True, 'use_seedable_sampler': True, 'non_blocking': False, 'gradient_accumulation_kwargs': None, 'use_configured_state': False},
adafactor=False,
adam_beta1=0.9,
adam_beta2=0.999,
adam_epsilon=1e-08,
auto_find_batch_size=False,
average_tokens_across_devices=False,
batch_eval_metrics=False,
bf16=False,
bf16_full_eval=False,
data_seed=None,
dataloader_drop_last=False,
dataloader_num_workers=0,
dataloader_persistent_workers=False,
dataloader_pin_memory=True,
dataloader_prefetch_factor=None,
ddp_backend=None,
ddp_broadcast_buffers=None,
ddp_bucket_cap_mb=None,
ddp_find_unused_parameters=None,
ddp_timeout=1800,
debug=[],
deepspeed=None,
disable_tqdm=False,
do_eval=True,
do_predict=False,
do_train=False,
eval_accumulation_steps=None,
eval_delay=0,
eval_do_concat_batches=True,
eval_on_start=False,
eval_steps=None,
eval_strategy=IntervalStrategy.EPOCH,
eval_use_gather_object=False,
fp16=False,
fp16_backend=auto,
fp16_full_eval=False,
fp16_opt_level=O1,
fsdp=[],
fsdp_config={'min_num_params': 0, 'xla': False, 'xla_fsdp_v2': False, 'xla_fsdp_grad_ckpt': False},
fsdp_min_num_params=0,
fsdp_transformer_layer_cls_to_wrap=None,
full_determinism=False,
gradient_accumulation_steps=1,
gradient_checkpointing=False,
gradient_checkpointing_kwargs=None,
greater_is_better=None,
group_by_length=False,
half_precision_backend=auto,
hub_always_push=False,
hub_model_id=None,
hub_private_repo=None,
hub_revision=None,
hub_strategy=HubStrategy.EVERY_SAVE,
hub_token=<HUB_TOKEN>,
ignore_data_skip=False,
include_for_metrics=[],
include_inputs_for_metrics=False,
include_num_input_tokens_seen=False,
include_tokens_per_second=False,
jit_mode_eval=False,
label_names=None,
label_smoothing_factor=0.0,
learning_rate=2e-05,
length_column_name=length,
liger_kernel_config=None,
load_best_model_at_end=False,
local_rank=0,
log_level=passive,
log_level_replica=warning,
log_on_each_node=True,
logging_dir=../data/classification_results/naacl_2026_submission/naacl_2026_submission_2026-09-25/seed300/in_domain/bert-large-cased/training_checkpoints/runs/Sep25_15-16-48_Detraviouss-MacBook-Pro.local,
logging_first_step=False,
logging_nan_inf_filter=True,
logging_steps=25,
logging_strategy=IntervalStrategy.STEPS,
lr_scheduler_kwargs={},
lr_scheduler_type=SchedulerType.LINEAR,
max_grad_norm=1.0,
max_steps=-1,
metric_for_best_model=None,
mp_parameters=,
neftune_noise_alpha=None,
no_cuda=False,
num_train_epochs=1,
optim=OptimizerNames.ADAMW_TORCH,
optim_args=None,
optim_target_modules=None,
output_dir=../data/classification_results/naacl_2026_submission/naacl_2026_submission_2026-09-25/seed300/in_domain/bert-large-cased/training_checkpoints,
overwrite_output_dir=False,
past_index=-1,
per_device_eval_batch_size=32,
per_device_train_batch_size=16,
prediction_loss_only=False,
push_to_hub=False,
push_to_hub_model_id=None,
push_to_hub_organization=None,
push_to_hub_token=<PUSH_TO_HUB_TOKEN>,
ray_scope=last,
remove_unused_columns=True,
report_to=[],
restore_callback_states_from_checkpoint=False,
resume_from_checkpoint=None,
run_name=../data/classification_results/naacl_2026_submission/naacl_2026_submission_2026-09-25/seed300/in_domain/bert-large-cased/training_checkpoints,
save_on_each_node=False,
save_only_model=False,
save_safetensors=True,
save_steps=500,
save_strategy=SaveStrategy.EPOCH,
save_total_limit=1,
seed=300,
skip_memory_metrics=True,
tf32=None,
torch_compile=False,
torch_compile_backend=None,
torch_compile_mode=None,
torch_empty_cache_steps=None,
torchdynamo=None,
tpu_metrics_debug=False,
tpu_num_cores=None,
use_cpu=False,
use_ipex=False,
use_legacy_prediction_loop=False,
use_liger_kernel=False,
use_mps_device=False,
warmup_ratio=0.0,
warmup_steps=0,
weight_decay=0.01,
)

#### Step 3: Build the Hugging Face x BERT Metrics + Trainer

From the Hugging Face tutorial: `Trainer` combines the model, training configuration, tokenized datasets, padding logic, and metric function into one training object.

`DataCollatorWithPadding` dynamically pads every batch to the length of the longest sentence in that specific batch. This is more efficient than padding every sentence in the dataset to `max_length`.

`compute_metrics` tells `Trainer` to call `EvaluationMetric` after each evaluation cycle to calculate:

- Accuracy
- Precision
- Recall
- F1 Score

The `Trainer` receives:

| Input | Purpose |
|---|---|
| `model` | Pretrained BERT plus the binary classification head |
| `args` | `TrainingArguments` configuration |
| `train_dataset` | Tokenized training sentences and labels |
| `eval_dataset` | Tokenized validation sentences and labels |
| `tokenizer` | The tokenizer matched to the BERT checkpoint |
| `data_collator` | Dynamic batch-padding mechanism |
| `compute_metrics` | Function that computes validation classification metrics |

In [28]:
def bert_trainer_metrics(eval_pred):
    """Compute validation metrics from Hugging Face model outputs."""
    logits, y_true = eval_pred
    # logits: raw output scores for each class, shape (N, 2).
    # y_true: ground-truth label IDs from the validation dataset, shape (N,).
    y_pred = np.argmax(logits, axis=-1)

    return EvaluationMetric.custom_evaluation_metrics(
        y_true=y_true,
        y_prediction=y_pred,
    )

In [29]:
def build_bert_trainer(
    model,
    training_args,
    train_dataset,
    val_dataset,
    tokenizer,
):
    """Combine model, datasets, tokenizer, metrics, and configuration."""
    print("\n[3/5] Building Trainer")
    print(f"      Train examples      : {len(train_dataset)}")
    print(f"      Validation examples : {len(val_dataset)}")
    print("      Data collator       : dynamic batch padding")
    print("      Compute metrics     : Accuracy, Precision, Recall, F1 Score")

    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=train_dataset,
        eval_dataset=val_dataset,
        tokenizer=tokenizer,
        data_collator=DataCollatorWithPadding(tokenizer=tokenizer),
        compute_metrics=bert_trainer_metrics,
    )

    return trainer

In [30]:
trainer = build_bert_trainer(model,
    training_args,
    tokenized_train_dataset,
    tokenized_val_dataset,
    tokenizer
)

trainer

/var/folders/78/9z0b45fx1xqbwxh8vk97lcfh0000gn/T/ipykernel_63382/2044725375.py:15: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[3/5] Building Trainer
      Train examples      : 24
      Validation examples : 8
      Data collator       : dynamic batch padding
      Compute metrics     : Accuracy, Precision, Recall, F1 Score

#### Step 4: Finetune BERT


From D2L [1]: fine-tuning updates **all** pretrained Transformer encoder parameters while simultaneously training the newly added classification head.

The `[CLS]` token representation flows into the classification head. During BERT pretraining, the `[CLS]` representation is used by the NSP classifier because self-attention allows it to encode information from the complete BERT input sequence [1]. For this downstream sentence-classification task, the pretrained model’s sequence-level representation is used to predict the binary class.

During training, the Hugging Face `Trainer` prints information every `logging_steps` steps:

| Training Log | Meaning |
|---|---|
| `loss` | Cross-entropy loss on the current training batch |
| `grad_norm` | Gradient magnitude; very large spikes can indicate instability |
| `learning_rate` | Current learning-rate value; typically decays toward zero |
| `epoch` | Fractional progress through training; e.g., `1.5` means halfway through epoch 2 |

At the end of every epoch, the trainer prints validation metrics:

| Evaluation Log | Meaning |
|---|---|
| `eval_loss` | Cross-entropy loss on validation data |
| `eval_Accuracy` | Proportion of correct validation predictions |
| `eval_Precision` | Proportion of positive predictions that were correct |
| `eval_Recall` | Proportion of actual positive examples correctly found |
| `eval_F1 Score` | Harmonic mean of precision and recall |

In [31]:
def run_bert_finetuning(trainer, logging_steps):
    """Run supervised fine-tuning on the labeled training sentences."""
    print("\n[4/5] Starting fine-tuning...")
    print(f"      Logging frequency   : every {logging_steps} steps")
    print("      Training logs       : loss, grad_norm, learning_rate, epoch")
    print("      Validation logs     : eval_loss, Accuracy, Precision, Recall, F1 Score")

    trainer.train()

    return trainer

In [32]:
print("train_dataset columns:", train_dataset.column_names)
print("tokenized_train_dataset columns:", tokenized_train_dataset.column_names)
print("tokenized train example:", tokenized_train_dataset[0])

train_dataset columns: ['Base Sentence', 'labels']
tokenized_train_dataset columns: ['labels', 'input_ids', 'token_type_ids', 'attention_mask']
tokenized train example: {'labels': 0, 'input_ids': [101, 1332, 5274, 26835, 5108, 3454, 2671, 3160, 787, 188, 3732, 2031, 6294, 5965, 1103, 3279, 1837, 1770, 117, 1451, 3215, 1150, 3667, 1222, 1123, 15468, 1209, 1129, 3254, 1643, 18726, 1107, 1103, 6704, 1115, 1103, 3215, 1484, 1104, 1103, 25932, 2341, 19943, 1174, 1113, 1123, 119, 102], 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

In [33]:
trainer = run_bert_finetuning(trainer, logging_steps)
trainer

[4/5] Starting fine-tuning...
      Logging frequency   : every 25 steps
      Training logs       : loss, grad_norm, learning_rate, epoch
      Validation logs     : eval_loss, Accuracy, Precision, Recall, F1 Score

/Users/detraviousjamaribrinkley/Documents/Development/research_labs/uf_ds/predictions/.venv_predictions/lib/python3.11/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

/Users/detraviousjamaribrinkley/Documents/Development/research_labs/uf_ds/predictions/.venv_predictions/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

#### Step 5: Save the Finetuned Model and Tokenizer

The fine-tuned BERT model and its matching tokenizer are saved in `final_model`.

This saves the model weights, model configuration, classifier head, tokenizer vocabulary, and tokenizer configuration. The saved model can later be loaded for inference without retraining.

In [34]:
def save_finetuned_bert(finetuned_model_name, trainer, tokenizer, output_dir):
    """Save the fine-tuned model weights, configuration, and tokenizer."""
    final_model_dir = os.path.join(output_dir, finetuned_model_name)

    trainer.save_model(final_model_dir)
    tokenizer.save_pretrained(final_model_dir)

    print("\n[5/5] Fine-tuning complete.")
    print(f"      ✓ Saved fine-tuned BERT model to : {final_model_dir}")
    print(f"      ✓ Saved tokenizer to             : {final_model_dir}")

    return final_model_dir

In [35]:
finetuned_bert_saved = save_finetuned_bert(finetuned_model_name, trainer, tokenizer, output_dir)

[5/5] Fine-tuning complete.
      ✓ Saved fine-tuned BERT model to : ../data/classification_results/naacl_2026_submission/naacl_2026_submission_2026-09-25/seed300/in_domain/bert-large-cased/tolsa-bert
      ✓ Saved tokenizer to             : ../data/classification_results/naacl_2026_submission/naacl_2026_submission_2026-09-25/seed300/in_domain/bert-large-cased/tolsa-bert

## Evaluation: Validation + Test Sets

### Helper Functions

In [36]:
def get_finetuned_bert_predictions(trainer, tokenized_dataset):
    """Generate BERT predicted labels and probability vectors."""

    print("\n" + "=" * 40)
    print("BERT PREDICTIONS")
    print("=" * 40)

    prediction_output = trainer.predict(tokenized_dataset)

    logits = prediction_output.predictions
    shifted_logits = logits - np.max(logits, axis=1, keepdims=True)
    exp_logits = np.exp(shifted_logits)
    probabilities = exp_logits / np.sum(exp_logits, axis=1, keepdims=True)
    y_pred = np.argmax(probabilities, axis=1)

    print(f"Number of BERT predictions : {len(y_pred)}")
    print(f"First 5 predicted labels   : {y_pred[:5]}")
    print(f"Probability matrix shape   : {probabilities.shape}")
    print(f"First probability vector   : {probabilities[0]}")

    return y_pred, probabilities

In [37]:
def evaluate_bert_predictions(
    y_true,
    y_pred,
    probabilities,
    split_name,
    seed,
    save_path,
    model_name,
):
    """
    Evaluate BERT predictions and save unified metrics and visualizations.

    Parameters
    ----------
    y_true : np.ndarray
        Ground-truth label IDs.
    y_pred : np.ndarray
        Predicted label IDs.
    probabilities : np.ndarray
        Softmax probability matrix, shape (N, 2).
    split_name : str
        Split identifier, e.g. 'validation' or 'test'.
    seed : int
        Random seed used in the experiment.
    save_path : str
        Directory path to save visualizations and metrics.
    model_name : str
        Name used for saving files and labeling outputs.

    Returns
    -------
    tuple
        (metrics_df, confusion_matrix, eval_report)
    """

    print("\n" + "=" * 40)
    print(f"EVALUATE BERT: {split_name.upper()}")
    print("=" * 40)

    # ============================================================
    # CLASSIFICATION REPORT
    # ============================================================
    eval_report = EvaluationMetric.eval_classification_report(
        y_true,
        y_pred,
    )

    # ============================================================
    # CONFUSION MATRIX
    # ============================================================
    cm, tn, fp, fn, tp = EvaluationMetric.get_confusion_matrix(
        y_true,
        y_pred,
        by_category=True,
    )

    print(f"Confusion Matrix:\n{cm}\n")
    print(f"TN: {tn}, FP: {fp}, FN: {fn}, TP: {tp}\n")

    save_visualizations_path = os.path.join(save_path, "visualizations")
    DataVisualizing.confusion_matrix(
        model_name,
        cm,
        save_visualizations_path,
        include_version=False,
    )
    print(f"✓ Saved confusion matrix: confusion_matrix_{model_name}.png\n")

    # ============================================================
    # AUC SCORES + CURVES
    # ============================================================
    positive_class_probabilities = probabilities[:, 1]

    roc_auc_score = EvaluationMetric.get_roc_auc(
        y_true,
        positive_class_probabilities,
    )
    print(f"ROC-AUC Score: {roc_auc_score:.4f}\n")

    # DataVisualizing.roc_curve(
    #     model_name,
    #     None,
    #     positive_class_probabilities,
    #     y_true,
    #     save_visualizations_path,
    #     include_version=False,
    # )
    # print(f"✓ Saved ROC-CURVE: roc_curve_{model_name}.png\n")

    pr_auc_score = EvaluationMetric.get_pr_auc(
        y_true,
        positive_class_probabilities,
    )
    print(f"PR-AUC Score: {pr_auc_score:.4f}\n")

    # DataVisualizing.pr_curve(
    #     model_name,
    #     None,
    #     positive_class_probabilities,
    #     y_true,
    #     save_visualizations_path,
    #     include_version=False,
    # )
    # print(f"✓ Saved PR-CURVE: pr_curve_{model_name}.png\n")

    # ============================================================
    # BUILD METRICS ROW
    # ============================================================
    metrics_df = pd.DataFrame([{
        "seed":               seed,
        "model":              model_name,
        "split":              split_name,
        # No training phase for inference-only evaluation
        "train_accuracy":     None,
        "val_accuracy":       None,
        "test_accuracy":      eval_report.get("accuracy", None),
        "precision_class_0":  eval_report.get("0", {}).get("precision", None),
        "precision_class_1":  eval_report.get("1", {}).get("precision", None),
        "recall_class_0":     eval_report.get("0", {}).get("recall", None),
        "recall_class_1":     eval_report.get("1", {}).get("recall", None),
        "f1_class_0":         eval_report.get("0", {}).get("f1-score", None),
        "f1_class_1":         eval_report.get("1", {}).get("f1-score", None),
        "tn":                 tn,
        "fp":                 fp,
        "fn":                 fn,
        "tp":                 tp,
        "roc_auc":            roc_auc_score,
        "pr_auc":             pr_auc_score,
    }])

    print("\n" + "=" * 40)
    print(f"METRICS SUMMARY WITH SEED {seed}")
    print("=" * 40)
    print(metrics_df)
    print()

    return metrics_df, cm, eval_report

In [38]:
def create_bert_results_dataframe(source_df, y_pred, probabilities, id_to_label):
    """Attach BERT predictions and probabilities to source data."""

    print("\n" + "=" * 40)
    print("CREATE BERT RESULTS DATAFRAME")
    print("=" * 40)

    results_df = source_df.copy()

    if "Ground Truth" in results_df.columns:
        results_df["Ground Truth"] = results_df["Ground Truth"].astype(int)

    results_df["BERT Predicted Label ID"] = y_pred
    results_df["BERT Predicted Label"] = [id_to_label[pred] for pred in y_pred]
    results_df["BERT Probability Class 0"] = probabilities[:, 0]
    results_df["BERT Probability Class 1"] = probabilities[:, 1]

    print(f"✓ Added BERT Predicted Label ID")
    print(f"✓ Added BERT Predicted Label")
    print(f"✓ Added BERT Probability Class 0")
    print(f"✓ Added BERT Probability Class 1")
    print(f"\nFinal shape: {results_df.shape}")
    print(f"\nPreview:\n{results_df.head(3)}\n")

    return results_df

In [39]:
def create_confusion_matrix_dataframe(cm, id_to_label):
    """Add readable actual and predicted labels to the confusion matrix."""

    return pd.DataFrame(
        cm,
        index=[f"Actual: {id_to_label[0]}", f"Actual: {id_to_label[1]}"],
        columns=[f"Predicted: {id_to_label[0]}", f"Predicted: {id_to_label[1]}"],
    )

### Validation + Test

In [40]:
def evaluate_and_save_bert_results(
    trainer,
    tokenized_dataset,
    original_df,
    label_id_column,
    id_to_label,
    split_name,
    seed,
    output_dir,
    model_name,
    csv_prefix="bert_predictions",
):
    """Run full BERT prediction and evaluation pipeline and save results to disk."""

    print("\n" + "=" * 40)
    print(f"BERT EVALUATE AND SAVE: {split_name.upper()}")
    print("=" * 40)

    # ============================================================
    # CREATE SPLIT OUTPUT DIRECTORY
    # ============================================================
    split_dir = os.path.join(output_dir, split_name)
    os.makedirs(split_dir, exist_ok=True)
    print(f"✓ Output directory: {split_dir}")

    # ============================================================
    # PREDICTIONS
    # ============================================================
    y_pred, probabilities = get_finetuned_bert_predictions(
        trainer=trainer,
        tokenized_dataset=tokenized_dataset,
    )

    # ============================================================
    # GROUND TRUTH
    # ============================================================
    y_true = original_df[label_id_column].to_numpy()

    print(f"\nNumber of ground-truth labels : {len(y_true)}")
    print(f"First 5 ground-truth labels   : {y_true[:5]}")

    # ============================================================
    # SAVE PREDICTIONS DATAFRAME (with readable labels + probabilities)
    # ============================================================
    predictions_df = create_bert_results_dataframe(
        source_df=original_df,
        y_pred=y_pred,
        probabilities=probabilities,
        id_to_label=id_to_label,
    )

    DataProcessing.save_to_file(
        predictions_df,
        path=split_dir,
        prefix=csv_prefix,
        save_file_type="csv",
        include_version=False,
    )
    print(f"✓ Saved predictions CSV to: {os.path.join(split_dir, f'{csv_prefix}.csv')}")

    # ============================================================
    # EVALUATE AND SAVE METRICS
    # ============================================================
    metrics_df, cm, eval_report = evaluate_bert_predictions(
        y_true=y_true,
        y_pred=y_pred,
        probabilities=probabilities,
        split_name=split_name,
        seed=seed,
        save_path=split_dir,
        model_name=model_name,
    )

    DataProcessing.save_to_file(
        metrics_df,
        path=split_dir,
        prefix="bert_metrics_summary",
        save_file_type="csv",
        include_version=False,
    )
    print(f"✓ Saved metrics summary to: {os.path.join(split_dir, 'bert_metrics_summary.csv')}")

    # ============================================================
    # SAVE READABLE CONFUSION MATRIX
    # ============================================================
    confusion_matrix_df = create_confusion_matrix_dataframe(
        cm=cm,
        id_to_label=id_to_label,
    )

    print(f"\nConfusion Matrix:\n{confusion_matrix_df}\n")

    DataProcessing.save_to_file(
        confusion_matrix_df,
        path=split_dir,
        prefix="bert_confusion_matrix",
        save_file_type="csv",
        include_version=False,
    )
    print(f"✓ Saved confusion matrix to: {os.path.join(split_dir, 'bert_confusion_matrix.csv')}")

    return metrics_df, cm, eval_report

In [41]:
val_metrics_df, val_cm, val_report = evaluate_and_save_bert_results(
    trainer=trainer,
    tokenized_dataset=tokenized_val_dataset,
    original_df=val_df,
    label_id_column=label_id_column,
    id_to_label=id_to_label,
    split_name="validation",
    seed=seed,
    output_dir=output_dir,
    model_name=finetuned_model_name,
    csv_prefix="bert_predictions_val",
)

test_metrics_df, test_cm, test_report = evaluate_and_save_bert_results(
    trainer=trainer,
    tokenized_dataset=tokenized_test_dataset,
    original_df=test_df,
    label_id_column=label_id_column,
    id_to_label=id_to_label,
    split_name="test",
    seed=seed,
    output_dir=output_dir,
    model_name=finetuned_model_name,
    csv_prefix="bert_predictions_test",
)

========================================
BERT EVALUATE AND SAVE: VALIDATION
========================================
✓ Output directory: ../data/classification_results/naacl_2026_submission/naacl_2026_submission_2026-09-25/seed300/in_domain/bert-large-cased/validation

========================================
BERT PREDICTIONS
========================================

/Users/detraviousjamaribrinkley/Documents/Development/research_labs/uf_ds/predictions/.venv_predictions/lib/python3.11/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

/Users/detraviousjamaribrinkley/Documents/Development/research_labs/uf_ds/predictions/.venv_predictions/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

Number of BERT predictions : 8
First 5 predicted labels   : [0 0 0 0 0]
Probability matrix shape   : (8, 2)
First probability vector   : [0.6175927  0.38240737]

Number of ground-truth labels : 8
First 5 ground-truth labels   : [1 1 0 0 0]

========================================
CREATE BERT RESULTS DATAFRAME
========================================
✓ Added BERT Predicted Label ID
✓ Added BERT Predicted Label
✓ Added BERT Probability Class 0
✓ Added BERT Probability Class 1

Final shape: (8, 8)

Preview:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     Base Sentence  \
0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   The goal average at Manchester City should stay the same in 2024-08-28, according to Analyst Sophia Rodriguez.
1  A warming trend is expected across most of the continental United States (CONUS) by the end of the week into next weekend, with temperatures trending above average, particularly near the Canadian border and the Gulf Coast. Rainfall will be modest to locally heavy, spreading from the Lower Mississippi Valley northeastward from Thursday to Sunday, alongside repetitive precipitation in the Pacific Northwest due to multiple systems. A low pressure system is predicted to move northeastward towards the Midwest, weakening by day 6, while a second low pressure system is expected to develop off the Mid-Atlantic coast and track northward by day 7. The Northwest Gulf Coast may experience modest rainfall totals, with some areas potentially seeing locally heavy amounts. In the Northwest, snow level...
2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       Currently, Avon, based in Santa Monica, Calif., has 3.3 million common shares outstanding.

   Ground Truth Dataset Name  _label_id  BERT Predicted Label ID  \
0             1    synthetic          1                        0
1             1   mf_climate          1                        0
2             0     timebank          0                        0

  BERT Predicted Label  BERT Probability Class 0  BERT Probability Class 1
0                    0                  0.617593                  0.382407
1                    0                  0.643949                  0.356052
2                    0                  0.605271                  0.394729

Saving CSV file to: ../data/classification_results/naacl_2026_submission/naacl_2026_submission_2026-09-25/seed300/in_domain/bert-large-cased/validation/bert_predictions_val.csv

/Users/detraviousjamaribrinkley/Documents/Development/research_labs/uf_ds/predictions/.venv_predictions/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/detraviousjamaribrinkley/Documents/Development/research_labs/uf_ds/predictions/.venv_predictions/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/detraviousjamaribrinkley/Documents/Development/research_labs/uf_ds/predictions/.venv_predictions/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/detraviousjamaribrinkley/Documents/Development/research_labs/uf_ds/predictions/.venv_predictions/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/detraviousjamaribrinkley/Documents/Development/research_labs/uf_ds/predictions/.venv_predictions/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/detraviousjamaribrinkley/Documents/Development/research_labs/uf_ds/predictions/.venv_predictions/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/detraviousjamaribrinkley/Documents/Development/research_labs/uf_ds/predictions/.venv_predictions/lib/python3.11/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

✓ Saved predictions CSV to: ../data/classification_results/naacl_2026_submission/naacl_2026_submission_2026-09-25/seed300/in_domain/bert-large-cased/validation/bert_predictions_val.csv

========================================
EVALUATE BERT: VALIDATION
========================================
              precision    recall  f1-score   support

           0       0.50      1.00      0.67         4
           1       0.00      0.00      0.00         4

    accuracy                           0.50         8
   macro avg       0.25      0.50      0.33         8
weighted avg       0.25      0.50      0.33         8

Confusion Matrix:
[[4 0]
 [4 0]]

TN: 4, FP: 0, FN: 4, TP: 0

Saving PNG file to: ../data/classification_results/naacl_2026_submission/naacl_2026_submission_2026-09-25/seed300/in_domain/bert-large-cased/validation/visualizations/confusion_matrix_tolsa-bert.png
✓ Saved confusion matrix: confusion_matrix_tolsa-bert.png

ROC-AUC Score: 0.2500

PR-AUC Score: 0.4571


========================================
METRICS SUMMARY WITH SEED 300
========================================
   seed       model       split train_accuracy val_accuracy  test_accuracy  \
0   300  tolsa-bert  validation           None         None            0.5

   precision_class_0  precision_class_1  recall_class_0  recall_class_1  \
0                0.5                0.0             1.0             0.0

   f1_class_0  f1_class_1  tn  fp  fn  tp  roc_auc    pr_auc
0    0.666667         0.0   4   0   4   0     0.25  0.457143

Saving CSV file to: ../data/classification_results/naacl_2026_submission/naacl_2026_submission_2026-09-25/seed300/in_domain/bert-large-cased/validation/bert_metrics_summary.csv
✓ Saved metrics summary to: ../data/classification_results/naacl_2026_submission/naacl_2026_submission_2026-09-25/seed300/in_domain/bert-large-cased/validation/bert_metrics_summary.csv

Confusion Matrix:
           Predicted: 0  Predicted: 1
Actual: 0             4             0
Actual: 1             4             0

Saving CSV file to: ../data/classification_results/naacl_2026_submission/naacl_2026_submission_2026-09-25/seed300/in_domain/bert-large-cased/validation/bert_confusion_matrix.csv
✓ Saved confusion matrix to: ../data/classification_results/naacl_2026_submission/naacl_2026_submission_2026-09-25/seed300/in_domain/bert-large-cased/validation/bert_confusion_matrix.csv

========================================
BERT EVALUATE AND SAVE: TEST
========================================
✓ Output directory: ../data/classification_results/naacl_2026_submission/naacl_2026_submission_2026-09-25/seed300/in_domain/bert-large-cased/test

========================================
BERT PREDICTIONS
========================================

/Users/detraviousjamaribrinkley/Documents/Development/research_labs/uf_ds/predictions/.venv_predictions/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

Number of BERT predictions : 8
First 5 predicted labels   : [0 0 0 0 0]
Probability matrix shape   : (8, 2)
First probability vector   : [0.61284393 0.3871561 ]

Number of ground-truth labels : 8
First 5 ground-truth labels   : [0 0 1 1 0]

========================================
CREATE BERT RESULTS DATAFRAME
========================================
✓ Added BERT Predicted Label ID
✓ Added BERT Predicted Label
✓ Added BERT Probability Class 0
✓ Added BERT Probability Class 1

Final shape: (8, 8)

Preview:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     Base Sentence  \
0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Uponor has initiated actions to attempt to recover the cost of the replacement program from the supplier of the clamps as well as its insurance company .
1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Maybe it would have athletes skiing on fake snow down parched slopes.
2  A major shift in the upper-level pattern is expected, leading to increased precipitation as an amplified trough moves across the U.S. Expect mostly dry conditions on Thursday, with light lake effect rain/snow in the Great Lakes and isolated rain showers in South Florida. A substantial increase in precipitation is anticipated from Friday into early next week; higher elevation snow and lower elevation rain are likely in the Pacific Northwest and the Rockies. The GFS predicts heavier rains for southern Texas, while the ECMWF keeps southern Plains dry. Temperatures will be below normal by 10-20Â°F across the Plains to the Southeast, with lows potentially in the 30s, possibly setting records. Warm conditions will persist in the Northwest with high temperatures challenging daily records. As ...

   Ground Truth          Dataset Name  _label_id  BERT Predicted Label ID  \
0             0  financial_phrasebank          0                        0
1             0         chronicle2050          0                        0
2             1            mf_climate          1                        0

  BERT Predicted Label  BERT Probability Class 0  BERT Probability Class 1
0                    0                  0.612844                  0.387156
1                    0                  0.563679                  0.436321
2                    0                  0.667413                  0.332587

Saving CSV file to: ../data/classification_results/naacl_2026_submission/naacl_2026_submission_2026-09-25/seed300/in_domain/bert-large-cased/test/bert_predictions_test.csv
✓ Saved predictions CSV to: ../data/classification_results/naacl_2026_submission/naacl_2026_submission_2026-09-25/seed300/in_domain/bert-large-cased/test/bert_predictions_test.csv

========================================
EVALUATE BERT: TEST
========================================
              precision    recall  f1-score   support

           0       0.62      1.00      0.77         5
           1       0.00      0.00      0.00         3

    accuracy                           0.62         8
   macro avg       0.31      0.50      0.38         8
weighted avg       0.39      0.62      0.48         8

Confusion Matrix:
[[5 0]
 [3 0]]

TN: 5, FP: 0, FN: 3, TP: 0

Saving PNG file to: ../data/classification_results/naacl_2026_submission/naacl_2026_submission_2026-09-25/seed300/in_domain/bert-large-cased/test/visualizations/confusion_matrix_tolsa-bert.png
✓ Saved confusion matrix: confusion_matrix_tolsa-bert.png

ROC-AUC Score: 0.5333

PR-AUC Score: 0.6250


========================================
METRICS SUMMARY WITH SEED 300
========================================
   seed       model split train_accuracy val_accuracy  test_accuracy  \
0   300  tolsa-bert  test           None         None          0.625

   precision_class_0  precision_class_1  recall_class_0  recall_class_1  \
0              0.625                0.0             1.0             0.0

   f1_class_0  f1_class_1  tn  fp  fn  tp   roc_auc  pr_auc
0    0.769231         0.0   5   0   3   0  0.533333   0.625

Saving CSV file to: ../data/classification_results/naacl_2026_submission/naacl_2026_submission_2026-09-25/seed300/in_domain/bert-large-cased/test/bert_metrics_summary.csv
✓ Saved metrics summary to: ../data/classification_results/naacl_2026_submission/naacl_2026_submission_2026-09-25/seed300/in_domain/bert-large-cased/test/bert_metrics_summary.csv

Confusion Matrix:
           Predicted: 0  Predicted: 1
Actual: 0             5             0
Actual: 1             3             0

Saving CSV file to: ../data/classification_results/naacl_2026_submission/naacl_2026_submission_2026-09-25/seed300/in_domain/bert-large-cased/test/bert_confusion_matrix.csv
✓ Saved confusion matrix to: ../data/classification_results/naacl_2026_submission/naacl_2026_submission_2026-09-25/seed300/in_domain/bert-large-cased/test/bert_confusion_matrix.csv

/Users/detraviousjamaribrinkley/Documents/Development/research_labs/uf_ds/predictions/.venv_predictions/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/detraviousjamaribrinkley/Documents/Development/research_labs/uf_ds/predictions/.venv_predictions/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/detraviousjamaribrinkley/Documents/Development/research_labs/uf_ds/predictions/.venv_predictions/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/detraviousjamaribrinkley/Documents/Development/research_labs/uf_ds/predictions/.venv_predictions/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/detraviousjamaribrinkley/Documents/Development/research_labs/uf_ds/predictions/.venv_predictions/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/detraviousjamaribrinkley/Documents/Development/research_labs/uf_ds/predictions/.venv_predictions/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

## Experiment Log

In [42]:
def create_bert_experiment_log(
    experiment_name,
    output_dir,
    dataset,
    text_column,
    label_column,
    model_name,
    finetuned_model_name,
    seed,
    val_size,
    test_size,
    epochs,
    learning_rate,
    weight_decay,
    train_batch_size,
    eval_batch_size,
    max_length,
    logging_steps,
    train_df,
    val_df,
    test_df,
    label_to_id,
):
    """Save a readable record of the BERT experiment configuration."""

    log_lines = [
        "=" * 40,
        "BERT SENTENCE CLASSIFICATION EXPERIMENT LOG",
        "=" * 40,
        f"Timestamp:              {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        f"Experiment:             {experiment_name}",
        f"Seed:                   {seed}",
        "",
        "--- Data ---",
        f"Dataset:                {dataset}",
        f"Text Column:            {text_column}",
        f"Label Column:           {label_column}",
        "",
        "--- Splits ---",
        f"Val Size:               {val_size}",
        f"Test Size:              {test_size}",
        f"Train Size:             {len(train_df)}",
        f"Validation Size:        {len(val_df) if val_df is not None else 'N/A'}",
        f"Test Size:              {len(test_df) if test_df is not None else 'N/A'}",
        "",
        "--- BERT Model ---",
        f"Pretrained Checkpoint:  {model_name}",
        f"Finetuned Model Name:   {finetuned_model_name}",
        f"Num Labels:             {len(label_to_id)}",
        "",
        "--- Training Arguments ---",
        f"Epochs:                 {epochs}",
        f"Learning Rate:          {learning_rate}",
        f"Weight Decay:           {weight_decay}",
        f"Train Batch Size:       {train_batch_size}",
        f"Eval Batch Size:        {eval_batch_size}",
        f"Max Token Length:       {max_length}",
        f"Logging Steps:          {logging_steps}",
        f"FP16:                   {torch.cuda.is_available()}",
        "",
        "--- Label Mapping ---",
    ]

    for label, label_id in label_to_id.items():
        log_lines.append(f"  {label_id} -> {label}")

    log_lines += [
        "",
        "--- Output ---",
        f"Output Directory:       {output_dir}",
        "=" * 40,
    ]

    log_dir = os.path.join(output_dir, "experiment_log")
    os.makedirs(log_dir, exist_ok=True)

    log_path = os.path.join(log_dir, "experiment_log.txt")

    with open(log_path, "w", encoding="utf-8") as f:
        f.write("\n".join(log_lines))

    print(f"✓ Experiment log saved to: {log_path}")

In [43]:
create_bert_experiment_log(
    experiment_name=experiment_name,
    output_dir=output_dir,
    dataset=dataset,
    text_column=text_column,
    label_column=label_column,
    model_name=model_name,
    finetuned_model_name=finetuned_model_name,
    seed=seed,
    val_size=val_size,
    test_size=test_size,
    epochs=epochs,
    learning_rate=learning_rate,
    weight_decay=weight_decay,
    train_batch_size=train_batch_size,
    eval_batch_size=eval_batch_size,
    max_length=max_length,
    logging_steps=logging_steps,
    train_df=train_df,
    val_df=val_df,
    test_df=test_df,
    label_to_id=label_to_id,
)

print("\n" + "=" * 40)
print("PIPELINE COMPLETE")
print("=" * 40)
print(f"Experiment:          {experiment_name}")
print(f"Pretrained model:    {model_name}")
print(f"Finetuned model:     {finetuned_model_name}")
print(f"Seed:                {seed}")
print(f"\n✓ All outputs saved to: {output_dir}\n")

✓ Experiment log saved to: ../data/classification_results/naacl_2026_submission/naacl_2026_submission_2026-09-25/seed300/in_domain/bert-large-cased/experiment_log/experiment_log.txt

========================================
PIPELINE COMPLETE
========================================
Experiment:          naacl_2026_submission_2026-09-25
Pretrained model:    bert-large-cased
Finetuned model:     tolsa-bert
Seed:                300

✓ All outputs saved to: ../data/classification_results/naacl_2026_submission/naacl_2026_submission_2026-09-25/seed300/in_domain/bert-large-cased