# Extract YouTube Transcripts

- **Tasks:**
    
    1. Find any YouTube clip where predictions exists. For ex, [Immediate 2025 NCAA tournament Final Four and championship picks](https://youtu.be/-rjnvL9LL3U?si=QMFJYAQ8Q85lTNCD). Below, we include all the videos we extract data from.
    2. Use the [`youtube-transcript-api`](https://pypi.org/project/youtube-transcript-api/) to retrieve the transcript.
    3. Extract the transcript snippets.
    4. Save the raw transcript snippets.

In [1]:
import os
import sys

import pandas as pd

from youtube_transcript_api import YouTubeTranscriptApi
from youtube_transcript_api._errors import NoTranscriptFound

# Get the current working directory of the notebook
notebook_dir = os.getcwd()
# Add the parent directory to the system path
sys.path.append(os.path.join(notebook_dir, '../'))

from data_processing import DataProcessing

In [2]:
pd.set_option('max_colwidth', 800)
# pd.set_option('display.max_columns', None)
# pd.set_option('display.max_rows', None)

## Preprocessing code

- Will use the below class and functions for both video transcripts.

---

1. `YouTubeTranscriptApi()` to fetch the YT transcripts.
2. `extract_data()` to transform data into Pandas DataFrame.

In [3]:
ytt_api = YouTubeTranscriptApi()

In [4]:
def extract_data(snippets) -> pd.DataFrame:
    """Extract the text, start time, and duration from the YT `FetchedTranscriptSnippet()`."""
    snippet_texts = []
    snippet_starts = []
    snippet_durations = []
    data = {}

    for snippets_idx in range(len(snippets)):
        snippet = snippets[snippets_idx]
        snippet_texts.append(snippet.text)
        snippet_starts.append(snippet.start)
        snippet_durations.append(snippet.duration)

    data['Text'] = snippet_texts
    data['Start Time'] = snippet_starts
    data['Duration'] = snippet_durations

    df = pd.DataFrame(data=data)
    return df

## Transcripts 

| # | Title | Link | Video ID |
|---|---|---|---|
| 1 | Immediate 2025 NCAA tournament Final Four and championship picks | https://www.youtube.com/watch?v=-rjnvL9LL3U | -rjnvL9LL3U 
| 2 | FULL PREVIEW & PICKS: Patriots vs. Seahawks Super Bowl LX 🏆 Who wins the Lombardi Trophy? \| NFL Live | https://www.youtube.com/watch?v=ZZN7BAYeOtc | ZZN7BAYeOtc |
| 3 | FIRST TAKE'S SUPER BOWL PICKS! The crew is going with... 😱 | https://www.youtube.com/watch?v=mBK8o5orBbE | mBK8o5orBbE |
| 4 | NFL Predictions and Picks For Super Bowl LX [Patriots vs Seahawks] - Best Bets ✅ | https://www.youtube.com/watch?v=LXPQrZV4Cfw | LXPQrZV4Cfw |
| 5 | Rich Eisen’s Pick to Win the Seahawks vs Patriots Super Bowl LX Is….? - The Rich Eisen Show | https://www.youtube.com/watch?v=fUmJAtFEGn8 | fUmJAtFEGn8 |
| 6 | The Pat McAfee Show's Picks For Super Bowl LX | https://www.youtube.com/watch?v=MTVAkVkkaz4 | MTVAkVkkaz4 |
| 7 | Super Bowl LX On-Site Preview: Picks, Predictions, Everything you need to know for Patriots-Seahawks | https://www.youtube.com/watch?v=Z0xP3GNpjkw | Z0xP3GNpjkw |

In [23]:
video_id = "-rjnvL9LL3U"
transcript_snippets = ytt_api.fetch(video_id)
transcript_snippets[:7]

[FetchedTranscriptSnippet(text='.', start=0.283, duration=1.248),
 FetchedTranscriptSnippet(text='THAT WILL BE A MONSTER GAME.', start=0.383, duration=5.879),
 FetchedTranscriptSnippet(text=">> LET'S HOPE EVERYBODY -- HELP", start=3.23, duration=8.195),
 FetchedTranscriptSnippet(text='EVERYBODY OUT MORE.', start=6.295, duration=9.744),
 FetchedTranscriptSnippet(text='THE 16 SEED HAS ONE TWO OF 24', start=11.458, duration=6.346),
 FetchedTranscriptSnippet(text='MEETINGS.', start=16.072, duration=4.864),
 FetchedTranscriptSnippet(text='ANALYTICS SAY ALL THE TOP THREE', start=17.837, duration=6.963)]

In [6]:
snippets_df = extract_data(transcript_snippets)
snippets_df

                                Text  Start Time  Duration
0                                  .       0.283     1.248
1       THAT WILL BE A MONSTER GAME.       0.383     5.879
2    >> LET'S HOPE EVERYBODY -- HELP       3.230     8.195
3                EVERYBODY OUT MORE.       6.295     9.744
4      THE 16 SEED HAS ONE TWO OF 24      11.458     6.346
5                          MEETINGS.      16.072     4.864
6    ANALYTICS SAY ALL THE TOP THREE      17.837     6.963
7                SEEDS WILL ADVANCE.      20.969     6.129
8   THE NINE SEED HAS WON TWO THIRDS      24.833     4.197
9     OF THE GAMES AGAINST THE EIGHT      27.131     2.566
10                             SEED.      29.063     3.481
11      YOU ALL HAD UCONN WINNING IT      31.595     3.348
12                        LAST YEAR.      32.577     5.264
13   WHO MAKES IT TO THE FINAL FOUR?      34.976     3.464
14       AND WHO CUTS DOWN THE NETS?      37.874     5.396
15     CLARK: I GET TO CHOOSE FIRST?      38.474     6.495
16       I WILL TAKE MICHIGAN STATE.      43.304     4.963
17      FLORIDA IS THE MOST COMPLETE      47.168     4.581
18                TEAM IN THE FIELD.      48.300     4.515
19         CLEMSON IS MY DARK HORSE.      51.782     3.098
20                  THEY ARE RUGGED.      52.848     3.131
21      THEY ALMOST GOT TO THE FINAL      54.913     2.499
22                   FOUR LAST YEAR.      56.012     3.798
23            AND THEN WE HAVE DUKE.      57.445     4.763
24        I AM TAKING CLEMSON IN SAN      59.843     6.978
25                          ANTONIO.      62.241     6.979
26  I AM GOING WITH THE GATORS AS MY      66.855     2.598
27                            CHAMP.      69.253     3.997
28   >> YOU ARE GETTING REALLY BOLD.      70.885     4.631
29          I AM A LITTLE LESS BOLD.      73.284     4.397
30         I HAD IOWA STATE HERE BUT      77.148     2.698
31  BECAUSE OF THE INJURY TO GILBERT      77.714     4.430
32         I WILL TAKE THE SPARTANS.      79.879     4.581
33   I WILL TAKE DUKE AND FLORIDA IN      82.561     2.798
34    THE FINAL AND THE BLUE DEVILS,      84.493     3.731
35     ASSUMING THAT COOPER FLAGG IS      85.393     3.431
36    HEALTHY, THEY ARE CUTTING DOWN      88.258     0.865
37                         THE NETS.      88.857     3.697
38                    >> HERE WE GO.      90.789     2.532
39   I LIKE AUBURN COMING OUT OF THE      92.721     2.632
40                            SOUTH.      93.354     2.965
41    I LIKE ST. JOHN LEADING OUT OF      95.719     2.765
42                         THE WEST.      96.352     3.714
43  DUKE IN THE EAST, HOUSTON IN THE      98.517     3.814
44                          MIDWEST.     100.099     3.431
45   IN MY CHAMPIONSHIP GAME, I HAVE     102.731     2.964
46     HOUSTON AND AUBURN AND I HAVE     103.563     4.664
47   THE AUBURN TIGERS FINISHING THE     105.729     3.031
48        SEASON AS NATIONAL CHAMPS.     108.260     3.132
49   ADAM: I THOUGHT HE WOULD GO BIG     108.793     2.932
50                             EAST.     111.425     3.264
51     >> THREE DIFFERENT CHAMPS FOR     112.957     1.899
52                               US.     114.723     3.015
53   ADAM: THE BIG EAST HAVE FIVE IN     114.889     5.514
54            THE TOURNAMENT FOR US.     117.771     3.065
55                  YOU MIXED IT UP.     120.436     3.597
56   >> HE LEARNED NOT TO GO WITH MY     120.869     3.331
57                             PICK.     124.067     1.415
58                    CLARK: YOU GUY     124.300     1.182

In [7]:
snippets_df['Video ID'] = video_id
snippets_df

                                Text  Start Time  Duration     Video ID
0                                  .       0.283     1.248  -rjnvL9LL3U
1       THAT WILL BE A MONSTER GAME.       0.383     5.879  -rjnvL9LL3U
2    >> LET'S HOPE EVERYBODY -- HELP       3.230     8.195  -rjnvL9LL3U
3                EVERYBODY OUT MORE.       6.295     9.744  -rjnvL9LL3U
4      THE 16 SEED HAS ONE TWO OF 24      11.458     6.346  -rjnvL9LL3U
5                          MEETINGS.      16.072     4.864  -rjnvL9LL3U
6    ANALYTICS SAY ALL THE TOP THREE      17.837     6.963  -rjnvL9LL3U
7                SEEDS WILL ADVANCE.      20.969     6.129  -rjnvL9LL3U
8   THE NINE SEED HAS WON TWO THIRDS      24.833     4.197  -rjnvL9LL3U
9     OF THE GAMES AGAINST THE EIGHT      27.131     2.566  -rjnvL9LL3U
10                             SEED.      29.063     3.481  -rjnvL9LL3U
11      YOU ALL HAD UCONN WINNING IT      31.595     3.348  -rjnvL9LL3U
12                        LAST YEAR.      32.577     5.264  -rjnvL9LL3U
13   WHO MAKES IT TO THE FINAL FOUR?      34.976     3.464  -rjnvL9LL3U
14       AND WHO CUTS DOWN THE NETS?      37.874     5.396  -rjnvL9LL3U
15     CLARK: I GET TO CHOOSE FIRST?      38.474     6.495  -rjnvL9LL3U
16       I WILL TAKE MICHIGAN STATE.      43.304     4.963  -rjnvL9LL3U
17      FLORIDA IS THE MOST COMPLETE      47.168     4.581  -rjnvL9LL3U
18                TEAM IN THE FIELD.      48.300     4.515  -rjnvL9LL3U
19         CLEMSON IS MY DARK HORSE.      51.782     3.098  -rjnvL9LL3U
20                  THEY ARE RUGGED.      52.848     3.131  -rjnvL9LL3U
21      THEY ALMOST GOT TO THE FINAL      54.913     2.499  -rjnvL9LL3U
22                   FOUR LAST YEAR.      56.012     3.798  -rjnvL9LL3U
23            AND THEN WE HAVE DUKE.      57.445     4.763  -rjnvL9LL3U
24        I AM TAKING CLEMSON IN SAN      59.843     6.978  -rjnvL9LL3U
25                          ANTONIO.      62.241     6.979  -rjnvL9LL3U
26  I AM GOING WITH THE GATORS AS MY      66.855     2.598  -rjnvL9LL3U
27                            CHAMP.      69.253     3.997  -rjnvL9LL3U
28   >> YOU ARE GETTING REALLY BOLD.      70.885     4.631  -rjnvL9LL3U
29          I AM A LITTLE LESS BOLD.      73.284     4.397  -rjnvL9LL3U
30         I HAD IOWA STATE HERE BUT      77.148     2.698  -rjnvL9LL3U
31  BECAUSE OF THE INJURY TO GILBERT      77.714     4.430  -rjnvL9LL3U
32         I WILL TAKE THE SPARTANS.      79.879     4.581  -rjnvL9LL3U
33   I WILL TAKE DUKE AND FLORIDA IN      82.561     2.798  -rjnvL9LL3U
34    THE FINAL AND THE BLUE DEVILS,      84.493     3.731  -rjnvL9LL3U
35     ASSUMING THAT COOPER FLAGG IS      85.393     3.431  -rjnvL9LL3U
36    HEALTHY, THEY ARE CUTTING DOWN      88.258     0.865  -rjnvL9LL3U
37                         THE NETS.      88.857     3.697  -rjnvL9LL3U
38                    >> HERE WE GO.      90.789     2.532  -rjnvL9LL3U
39   I LIKE AUBURN COMING OUT OF THE      92.721     2.632  -rjnvL9LL3U
40                            SOUTH.      93.354     2.965  -rjnvL9LL3U
41    I LIKE ST. JOHN LEADING OUT OF      95.719     2.765  -rjnvL9LL3U
42                         THE WEST.      96.352     3.714  -rjnvL9LL3U
43  DUKE IN THE EAST, HOUSTON IN THE      98.517     3.814  -rjnvL9LL3U
44                          MIDWEST.     100.099     3.431  -rjnvL9LL3U
45   IN MY CHAMPIONSHIP GAME, I HAVE     102.731     2.964  -rjnvL9LL3U
46     HOUSTON AND AUBURN AND I HAVE     103.563     4.664  -rjnvL9LL3U
47   THE AUBURN TIGERS FINISHING THE     105.729     3.031  -rjnvL9LL3U
48        SEASON AS NATIONAL CHAMPS.     108.260     3.132  -rjnvL9LL3U
49   ADAM: I THOUGHT HE WOULD GO BIG     108.793     2.932  -rjnvL9LL3U
50                             EAST.     111.425     3.264  -rjnvL9LL3U
51     >> THREE DIFFERENT CHAMPS FOR     112.957     1.899  -rjnvL9LL3U
52                               US.     114.723     3.015  -rjnvL9LL3U
53   ADAM: THE BIG EAST HAVE FIVE IN     114.889     5.514  -rjnvL9LL3U
54            THE TOURNAMENT FOR US.     117.771     3.065  -rjnvL9LL3U
55                  YOU MIXED IT UP.     120.436     3.597  -rjnvL9LL3U
56   >> HE LEARNED NOT TO GO WITH MY     120.869     3.331  -rjnvL9LL3U
57                             PICK.     124.067     1.415  -rjnvL9LL3U
58                    CLARK: YOU GUY     124.300     1.182  -rjnvL9LL3U

In [9]:
base_data_path = DataProcessing.load_base_data_path(notebook_dir=notebook_dir)
save_data_path = os.path.join(base_data_path, "yt", "raw_transcripts")
DataProcessing.save_to_file(snippets_df, path=save_data_path, prefix=f'{video_id}', save_file_type='csv', include_version=False)

Saving CSV file to: /Users/detraviousjamaribrinkley/Documents/Development/research_labs/uf_ds/predictions/prediction_acquition-youtube/../data/yt/raw_transcripts/-rjnvL9LL3U.csv

## Filtering English Auto Generated Transcripts

In [5]:
video_ids = ["-rjnvL9LL3U", "ZZN7BAYeOtc", "mBK8o5orBbE", "Z0xP3GNpjkw"]

results = {}

for vid in video_ids:
    transcript_list  = ytt_api.list(vid)
    for transcript in transcript_list :
        print({
            "id": vid,
            "language": transcript.language,
            "language_code": transcript.language_code,
            "is_generated": transcript.is_generated})

{'id': '-rjnvL9LL3U', 'language': 'English - DTVCC1', 'language_code': 'en', 'is_generated': False}
{'id': '-rjnvL9LL3U', 'language': 'English (auto-generated)', 'language_code': 'en', 'is_generated': True}
{'id': 'ZZN7BAYeOtc', 'language': 'English (auto-generated)', 'language_code': 'en', 'is_generated': True}
{'id': 'mBK8o5orBbE', 'language': 'English (auto-generated)', 'language_code': 'en', 'is_generated': True}
{'id': 'Z0xP3GNpjkw', 'language': 'English - DTVCC1', 'language_code': 'en', 'is_generated': False}
{'id': 'Z0xP3GNpjkw', 'language': 'Scots - CC1', 'language_code': 'sco', 'is_generated': False}
{'id': 'Z0xP3GNpjkw', 'language': 'English (auto-generated)', 'language_code': 'en', 'is_generated': True}

In [6]:
def fetch_en_auto_transcript_snippets(ytt_api, video_id: str):
    
    tl = ytt_api.list(video_id)
    
    for t in tl:
        if t.language == "English (auto-generated)" and t.language_code == "en" and t.is_generated:
            return t.fetch()
            
    for t in tl:
        if t.language_code == "en" and t.is_generated:
            return t.fetch()
    
    raise NoTranscriptFound(video_id)

In [31]:
video_id = "Z0xP3GNpjkw" #-rjnvL9LL3U ZZN7BAYeOtc mBK8o5orBbE LXPQrZV4Cfw fUmJAtFEGn8 MTVAkVkkaz4 Z0xP3GNpjkw
transcript_snippets = fetch_en_auto_transcript_snippets(ytt_api, video_id)
transcript_snippets[:7]

[FetchedTranscriptSnippet(text='Welcome to CBS Sports HQ presented by', start=2.24, duration=4.639),
 FetchedTranscriptSnippet(text='Hines. It has to be Hines and this has', start=4.48, duration=3.6),
 FetchedTranscriptSnippet(text="to be a good show because it's a Friday", start=6.879, duration=2.961),
 FetchedTranscriptSnippet(text="of Super Bowl week. I'm Jenny Dell. The", start=8.08, duration=3.679),
 FetchedTranscriptSnippet(text='Super Bowl, the day after tomorrow. We', start=9.84, duration=3.759),
 FetchedTranscriptSnippet(text="are almost there. We've made it. Let's", start=11.759, duration=3.04),
 FetchedTranscriptSnippet(text='get through this Friday afternoon', start=13.599, duration=3.431)]

In [32]:
snippets_df = extract_data(transcript_snippets)
snippets_df.head()

                                      Text  Start Time  Duration
0    Welcome to CBS Sports HQ presented by       2.240     4.639
1   Hines. It has to be Hines and this has       4.480     3.600
2  to be a good show because it's a Friday       6.879     2.961
3  of Super Bowl week. I'm Jenny Dell. The       8.080     3.679
4   Super Bowl, the day after tomorrow. We       9.840     3.759

In [33]:
snippets_df['Video ID'] = video_id
snippets_df.head()

                                      Text  Start Time  Duration     Video ID
0    Welcome to CBS Sports HQ presented by       2.240     4.639  Z0xP3GNpjkw
1   Hines. It has to be Hines and this has       4.480     3.600  Z0xP3GNpjkw
2  to be a good show because it's a Friday       6.879     2.961  Z0xP3GNpjkw
3  of Super Bowl week. I'm Jenny Dell. The       8.080     3.679  Z0xP3GNpjkw
4   Super Bowl, the day after tomorrow. We       9.840     3.759  Z0xP3GNpjkw

In [34]:
base_data_path = DataProcessing.load_base_data_path(notebook_dir=notebook_dir)
save_data_path = os.path.join(base_data_path, "yt", "raw_transcripts")
DataProcessing.save_to_file(snippets_df, path=save_data_path, prefix=f'{video_id}', save_file_type='csv', include_version=False)

Saving CSV file to: c:\Users\adria\OneDrive\Área de Trabalho\UF Data Studio\predictions\prediction_acquition-youtube\../data\yt\raw_transcripts\Z0xP3GNpjkw.csv