# Label YouTube Text as either Prediction or Non-Prediction

- **Tasks:**
    1. Load YouTube transcripts extracted from `1-extract_transcripts.ipynb`.
    4. Clean the data.
    5. Create prompt to identify predictions.
    6. Pass each row of text + prompt into the [UF NaviGator Toolkit](https://it.ufl.edu/ai/navigator-toolkit/) or [Groq](https://console.groq.com/home) LLMs.
    7. Perform majority vote (MV) across all LLMs.
    8. Filter by MV label = 1, hence prediction.
    9. Verify that the text is/is not a prediction and update accordingly.

In [1]:
import os
import sys

import re
from typing import List

import pandas as pd
import numpy as np

from tqdm import tqdm
from youtube_transcript_api import YouTubeTranscriptApi

# Get the current working directory of the notebook
notebook_dir = os.getcwd()
# Add the parent directory to the system path
sys.path.append(os.path.join(notebook_dir, '../'))
# from metrics import Metrics
# from feature_extraction import SpacyFeatureExtraction
from data_processing import DataProcessing
from text_generation_models import TextGenerationModelFactory, llm_classify_text

In [2]:
pd.set_option('max_colwidth', 800)
# pd.set_option('display.max_columns', None)
# pd.set_option('display.max_rows', None)

## Load Data

In [3]:
base_data_path = DataProcessing.load_base_data_path(notebook_dir)
yt_data_path = os.path.join(base_data_path, 'yt', 'whisper_transcripts', 'sports')
transcripts = os.listdir(yt_data_path)

In [4]:
transcripts

['-rjnvL9LL3U.csv',
 '6STv2GFNB6I.csv',
 'AoE8KFAXHSc.csv',
 'FPl-F2k_KtM.csv',
 'fUmJAtFEGn8.csv',
 'jCe-bY1nP7o.csv',
 'LXPQrZV4Cfw.csv',
 'mBK8o5orBbE.csv',
 'MTVAkVkkaz4.csv',
 'Z0xP3GNpjkw.csv',
 'ZZN7BAYeOtc.csv']

Choose the transcript video that you want to pass through the pipeline. 

Adjust the element from "transcripts" list to choose the right "Video ID".

In [5]:
transcript_path = os.path.join(yt_data_path, transcripts[3])

raw_transcripts_df = DataProcessing.load_from_file(path=transcript_path, file_type='csv')

raw_transcripts_df.head()

,Text,Start Time,Duration,Video ID
0,Hello and welcome to the Sharp 600 brought to you by Covers.com and presented by Bet365.,0.00,14.38,FPl-F2k_KtM
1,My name is Jason Logan. I will be your host here for the next 10 minutes as we take our first bites of Super Bowl 60 odds.,14.56,6.28,FPl-F2k_KtM
2,"And joining us for that dinner, for that snack time, is former odds maker, current professional bettor Todd Furman.",21.00,5.28,FPl-F2k_KtM
3,"Todd, happy bye week to you. The Seahawks, the Patriots get a little bit of a breather,",4.80,0.08,FPl-F2k_KtM
4,"a little bit of downtime this week, but I always found the bye was like my busiest time,",9.38,0.12,FPl-F2k_KtM

In [6]:
# dfs = []

# for transcript in tqdm(transcripts):
#     transcript_path = os.path.join(yt_data_path, transcript)
#     df = DataProcessing.load_from_file(path=transcript_path, file_type='csv')
#     dfs.append(df)

# raw_transcripts_df = DataProcessing.concat_dfs(dfs)
# raw_transcripts_df.head()

In [7]:
def clean_data(df) -> list[str]:
    """
    Split running text into sentence-like segments.
    Rules:
    - Split only where a period (.) or question mark (?) is immediately followed by
    whitespace. This avoids splitting decimals like ``4.5`` (digit after the dot,
    not a space).
    - Leading/trailing whitespace is stripped from each segment.
    - Empty segments are dropped.
    Caveat:
    - Abbreviations such as ``Mr. Smith`` still match ". " and may split incorrectly;
    handle those with a tokenizer or an allowlist if needed.
    Parameters
    ----------
    text : dataframe
        Full text to segment (e.g. one block of joined transcript lines).
    Returns
    -------
    list of str
        Non-empty strings, each intended as one sentence or clause.
    """

    text_joined = ' '.join(df.Text.to_list())
    raw_parts = re.split(r'(?<=[.?])\s+', text_joined)
    text_split = [p.strip() for p in raw_parts if p.strip()]

    return text_split

In [8]:
cleaned_transcripts = clean_data(raw_transcripts_df)
cleaned_transcripts

['Hello and welcome to the Sharp 600 brought to you by Covers.com and presented by Bet365.',
 'My name is Jason Logan.',
 'I will be your host here for the next 10 minutes as we take our first bites of Super Bowl 60 odds.',
 'And joining us for that dinner, for that snack time, is former odds maker, current professional bettor Todd Furman.',
 'Todd, happy bye week to you.',
 'The Seahawks, the Patriots get a little bit of a breather, a little bit of downtime this week, but I always found the bye was like my busiest time, at least in terms of what I need to do, the capping, the content, the planning, all these things, everything that we do at Covers for Super Bowl was very, very busy.',
 'For you as a pro better, what do these two weeks look like?',
 'The schedule has changed considerably from what it is during the bye week now versus what it would have been during the bye week 10 years ago.',
 "I mean, J-Lo, we had player props out at most of the prominent books, bet three, six, five, as well as early as Monday morning where you've been in the industry long enough.",
 'And this is going to make us sound really old.',
 "You didn't start to get player props until Friday, Saturday, Sunday, leading up to the big game in and of itself.",
 "So you kind of have to have rough projections, know which players that you've targeted.",
 'You want to jump on right away.',
 "And then you begin to dig into some of the X's and O's and try and figure out, okay, where can I add to those positions?",
 'Where can I find my biggest edges?',
 "and what have the odds makers not properly accounted for versus current form compared to season-long metrics where they'll heavily weight them towards a lot of individual player performances.",
 'Yeah, I was betting player props Sunday night.',
 'They were out Sunday night in a few books.',
 'And that was first crack.',
 'First crack that Sunday compared to first crack the Sunday before the Super Bowl a decade ago.',
 'Yeah, I remember the Thursday before the Super Bowl and all the props would come out.',
 'It was like that was the big thing.',
 'But, yeah, times, they are changing.',
 "Before we start the clock here on what's going to be the second last podcast of the season, I can't believe that, a simple ask.",
 "If you have been listening to us all season or if you're just finding us for the first time here ahead of Super Bowl, we ask that if you like what you're hearing, let us know.",
 'Let other people know.',
 'Rate and review the podcast on those pod platforms.',
 "If you're watching us on YouTube, like, subscribe to the Covers YouTube channel, and leave a comment.",
 'What are you betting in the big game?',
 "We'd like to know.",
 "all right todd let's have 600 super seconds on the clock all right let's break down the line here super bowl 60 the spread opens as low as three and a half but we see a quick move they forget about four they go four and a half that's where we see this right now we have seen five we have seen some five and a halves uh todd for me i mean this I look at this, this is the best spread that bookies could ask for right now because of all that wiggle room in the middle.",
 'What are you seeing from this spread?',
 'What do you like?',
 'What have you got down on early?',
 'You mentioned where the number opens at 3.5.',
 'The look-ahead number going into the championship Sunday, you see a couple of books stick to their guns.',
 "Then we did see some money come in on the favor, to your point, getting stuck in no man's land where books are going to have a ton of flexibility.",
 'The opportunity to move down to 4 if they see professional money most likely coming in on New England, or drift the number a lot further out in that 5-5.5 range if the public comes in on one side, or I guess I should say if the professionals decide they want to back the Seahawks.',
 "For me, the 6 was going to be my buy point on the dog, and it wasn't widely available, so I don't really have a true position on the side in this game early on.",
 'My number was 4.',
 "I want to dig into it a little bit, figure out if there's a matchup or two that I think one of these sides can exploit.",
 "My initial inclination was that if you're going to give me a good defense, that's going to have the opportunity to catch points in this particular spot.",
 "I'm typically going to gravitate towards that more often than not, but don't have a full position on this game yet.",
 "And J-Lo, I'm not quite sure the betting market is going to allow me an opportunity to get involved with the number that I've targeted.",
 'Yeah, for me, knowing what the look-ahead spread was, I knew we were going to see a money line on Seattle around 2-1 for that favorite.',
 "And that's where it came out, and that's where I took them right away.",
 "When it comes to four and four-and-a-half point favorites, I've kind of made it a rule for myself to say, you know what don't play the points just go with the money line i find that four to four and a half is it's been since kind of four became more of a key number since 2015 it's been kind of a no man's land where that four point favorite or the four and a half point favorite will win but not quite cover they're good enough to be favored by more than a field goal but not quite good enough to be favored by six and so for me i went to seattle straight out just i mean two games over the last two weeks the new england patriots win but don't cover they close a three and a half four point favorite against the denver broncos and the week before we see the chicago bears come up just short in the straight up category but find a way to cover as a three and a half four point underdog so i think that number is a lot more important than people give it credit for and to your point you're going to see a money line that may come down as well if you gravitate towards seattle closer to kickoff yeah i mean you're going to see oh we always see underdog money on the money line So there'll probably be some Patriots outright money showing up.",
 "Let's talk total here.",
 'Look ahead was 45, open 46 and a half.',
 "Now we're seeing 46 is 45 and a half.",
 'A clear weather game for the Patriots.',
 "I'm leaning towards over in this one.",
 'I want to know your thoughts.',
 'A weather game times two.',
 'I mean, played in a blizzard in the AFC championship game and played in freezing rain the week before against the Houston Texans.',
 "A game that snuck over, but it wasn't because of offensive execution from either of those two teams.",
 "It's always interesting to figure out how much a weather is suppressing a total.",
 'In a game like this, it appears the forecast in Santa Clara is going to be pretty good.',
 "Now, it is an outdoor venue, so we're not quite sure exactly what that track is going to look like.",
 "We've seen games played in domes typically offer a faster track for both these teams in the past.",
 'For me, 47 was kind of the number that I was looking for to make a case to go under.',
 "If I am going to get involved in a total, I'll probably gravitate a little bit more towards looking at that first half number.",
 'But wish I had stronger convictions right now because I do think you have suppressed totals there.',
 "But you also have a Seahawks offense that's going to be stepping up in class given the last three games, two against the 49ers, one against the Rams.",
 "I'm not sure either of those secondaries would be described as anything more than a bottom six unit.",
 'Yeah, I always look at under in the derivative market, specifically in that first quarter unders.',
 'Those tend to be lower scoring frames.',
 'Both teams a little jacked up.',
 'You got two quarterbacks a little tight on those throws.',
 'We see some miscues and things like that.',
 'So I do lean towards those unders in the first quarter.',
 "All right, we've still got a lot of time here before Super Bowl kickoff.",
 "Let's talk do's and don'ts for sports bettors.",
 "I'm going to start with a do.",
 "And I'm going to say do take advantage of the live in-game odds, especially when it comes to any early game anomalies.",
 'If the Patriots get up quick, but they do so on, say, a defensive score or a special team score, anything weird that happens early on, usually you can take an advantage of a market that will overcorrect to that, especially with everyone and their dog betting in this game and people chasing their bets.',
 'So any early game anomalies, look and see if you can find some buyback points in the in-game markets.',
 'Todd, you got a do for us in terms of Super Bowl betting?',
 "I do, but I want to piggyback what you said, and I think the other interesting angle that you can take, it's not just side total.",
 "It's live player props as well that get heavily impacted by game state.",
 'So I think there are a lot more opportunities now than there would have been when we had this discussion, say, five, seven, ten years ago in those particular live markets.',
 "Dues for me, I feel like I'm a man that is absolutely no fun to watch the game with.",
 'Do make a case to bet a lot of player performances to come in under their posted totals.',
 "I know it's not fun to root against anything happening during the course of a football game, You look at a lot of these markets that are set.",
 'People are going to gravitate towards rooting for things to happen.',
 "They're going to see low yardage totals with those third and fourth string wide receivers and tight ends and hope those players can come up with a catcher to do look to bet things under and do be willing to lay prices to be able to do so.",
 'And are we doing that on closer to kickoff, waiting for those odds to go up?',
 'Certain players, I would say yes.',
 'Other players, sometimes you have to jump a little bit sooner.',
 "but I would not be running to bet JSN under his receiving total until the 23rd hour let's put it that way all right well I've got a don't here and this is more of an etiquette thing if you're at a Super Bowl party if you're with a group and that group is maybe not of the betting guild don't constantly talk about your bets I'm someone that does this for for a job and I can't stand those people if you listen if you're with your buddies and it's the group ride parlay and this is your group chat that you're with you know party up go crazy have not go nuts but for god's sakes read the room and don't get down on everyone because you're losing some wager celebrate your wins you hit a 25 to 1 first touchdown winner celebrate it have fun if you lose on heads don't throw a fit don't bring everyone down keep your keep your betting excitement in check that that's my don't todd you got a don't for us you know one of my don'ts is don't be a superbowl grinch like me who typically watches the big game every year by himself given some of the immediate responsibilities that I have.",
 'I can control the temperature.',
 'I can control the alcohol intake and the food and everything else.',
 "But for me, it's don't chase some of those long shot prices with the majority of your bankroll.",
 "It's more than fine to get involved in some of those long shot markets.",
 "But at the same time, if anything, you're not getting the necessary value and upside for trying to look for some of those depth players to go over those laddering numbers that are out there or a variety of other markets.",
 "So don't just chase that plus money.",
 'Be judicious about how you allocate your bankroll.',
 'All right, time to talk Super Bowl MVP odds.',
 'Todd, who do you like to be the most valuable player Super Bowl 60?',
 "So J-Lo, normally you're gonna gravitate towards the starting quarterback of the team that you think is going to win the game, but what fun would that be in a game like this?",
 'I am going to take a skilled position player for a team that I think wins the game, and that would lead me to Ramondre Stevenson at 28 to one.',
 "look we've seen a Patriots running back get snubbed in the past that had 37 catches and like 900 receiving yards this is a chance for the world to right all of its wrongs and give Ramondre the hardware if he has two touchdowns and 75 all-purpose yards give me Ramondre Stevenson 28 to 1 all right I'll see your skill player and raise you a defensive player go on Demarcus Lawrence it only makes sense that a cowboy is going to get to the Super Bowl and show it almost last year I did uh but I'm happy for Tank but let's talk about this defense this is the reason why San Seattle is here This is the reason why they're favored.",
 'He is the most disruptive player on this team.',
 'Six sacks, 11 tackles for a loss, three forced fumbles, scooped up all of those in the regular season.',
 'Two sacks, three forced fumbles in the playoffs so far.',
 "The Patriots pass protection hasn't been great.",
 'I like Tank, MVP, plus 10,000.',
 'All right, two-minute drill time.',
 'Early bets here for Super Bowl 60.',
 "I'm going with Seattle receiver Raheed Shaheed, over 21.5 yards, receiving minus 110.",
 'since he came over at the trade deadline.',
 'Seattle has faced a lot of opponents that run zone.',
 'A lot of those defense runs zone exclusively.',
 'He is a much better receiver at man.',
 'And what does he face in the Patriots?',
 'He faces a defense that runs one of the highest rates of man.',
 "There's also someone that likes throwing against man, and that's Sam Darnold.",
 'So I think Shahid gets loose here.',
 'He could put this one away in one catch.',
 'Over 21 and a half yards receiving.',
 "Rashid Shahid still on my shit list because he didn't want to take contact over a half a rushing yard with the end around.",
 'decided he was going to dance around.',
 'And example number 758.',
 'I had it.',
 "Why you can't trust a Diva wide receiver as a ball carrier in the backfield.",
 "For me, I'm going to go to that Seattle Seahawks backfield though and take Kenneth Walker under his rushing total at 75 and a half.",
 'Look, Walker started out like a house on fire last week against the Rams.',
 'Eight carries early on in that game for 35 yards and then kind of petered out.',
 "11 carries the rest of the game and didn't show that big explosive potential even against the much maligned Rams run defense.",
 'Now he steps up in class against the Patriots run defense that is truly elite when Milton Williams is back in the full to anchor that defensive line.',
 'Seattle does love to run the football on early downs.',
 'I think they may have to go away from that approach.',
 "And even without Zach Charbonnet, I just don't see Kenneth Walker getting to mid-70s or higher.",
 'I have him projected J-Lo in the high 60s, under 75.5 for the bell cow back wearing Seahawks colors.',
 "All right, I'm going to go to the tight end for the Patriots.",
 'Hunter Henry over 36.5 yards, receiving minus 110.',
 "He's been taking some punishment, and now he faces a ferocious Seattle pass rush that can get pressure with just four.",
 "He's not going to have time for downfield plays to develop.",
 "He's going to have to hit those quick hits, and Hunter Henry has been that pressure release.",
 'We have seen Seattle give up a lot of targets, a lot of receptions, two tight ends.',
 'Projections for Henry, sit as high as 46.',
 'I like him to go over 36.5.',
 'Small flyer for me, a Seattle Seahawks receiver, not named Cooper Cup, not named Rasheed Sheed, not named Jackson Smith and Jigba.',
 'Jake Bobo, over a half a receiving yard at plus $1.15.',
 'Bobo had a catch in each of the last two games, 16 yards, 17 yards.',
 "I think he's a guy that may be targeted a couple times here.",
 'Just one catch, get us one yard, take me there at plus $1.15.',
 'All right, you got two weeks to scheme up some stuff.',
 'You got to get tricky sometimes and throw those guys in there.',
 'He did not have a touchdown in that NFC Championship game.',
 'Was he the guy that scored a touchdown in that one?',
 'No, he did have a touchdown there.',
 'Had one catch each of the last two games, 16 yards, 17 yards, and a TD.',
 "All I'm just looking for is a receiving yard here to get us across the finish line.",
 "Yeah, that's it.",
 "He's not asking for much, Bobo.",
 "Just, you know, that's it.",
 "That's it.",
 "I can't wait to see you freak out on Super Bowl Sunday when he doesn't get that.",
 'But remember the etiquette.',
 'Yeah.',
 'All right.',
 'A couple of targets.',
 'A couple of targets.',
 'A couple of drops.',
 'You know how this goes.',
 'I know exactly how it goes.',
 "It'll be all right.",
 'All right.',
 'That is it for our first Super Bowl pod.',
 'We will have another one next week.',
 'A big thanks to Chris behind the scenes.',
 'A big thank you to Todd for joining us once again.',
 "thanks to beth365 for the odds and of course thank you to you for tuning in and listening whether you've been with us all year or you're just finding us here ahead of the big game a reminder if you like what we're doing rate and review like and subscribe on youtube it just takes a matter of seconds uh but it means a lot to us so please do that when you can todd uh you thought you would get out of this podcast without some super bowl silliness but no because you know i mean i look not my first rodeo i know better that there's always something waiting behind door number three it's a basic one by this by this point in in super bowl betting this is a very common wager what color gatorade is going to get thrown on the winning coach here at the end of super bowl six i mean i feel like you're tipping your hand given what's in your cup uh when we recorded this video earlier today you claim that it's not blue gatorade that it's just a blue tinted cup but i'm gonna go with blue look we have a couple of teams wearing darker colors there that could play a role, I think blue is going to be my preferred way to go, mainly because, look, I'm a big fan of that particular flavor myself, so I like to use firsthand knowledge to get me across the finish line, more so than that fruit punch and water or anything else.",
 "So let's go with blue from the Gatorade color.",
 'See, I always used to lean towards water because I knew it was there, but then I got to remember, too, like this is a corporate marketing spot right here.',
 'And the last thing the Gatorade bigwigs want to see is water being thrown on the winning coach.',
 "I'm going to go lime slash green, you know, traditional Gatorade color.",
 'But I do have the Seahawks money line, so might as well tie it to the Gatorade color.',
 "That'll probably be on the sideline.",
 "And one more thing, Belichick, up for Hall of Fame, doesn't get in on the first time around.",
 'I mean, the virtue signaling, the holier-than-thou approach that comes from the NFL brass is just mind-boggling to me that these kind of things are allowed to happen.',
 "I know Bill Belichick's record without Tom Brady as a head coach is nothing to write home about, but this is a guy that has six Super Bowls on his resume as a head coach, two as a defensive coordinator.",
 "I mean, the guy has basically been in 25% of the big games that we've seen played since its inception in the late 60s.",
 'Bill Belichick deserves to be in, and I think this is just dumb.',
 "I know people point to Vince Lombardi and Joe Gibbs not getting in on their first ballot, but if you're going to keep Bill Belichick out on his first ballot, you know what this tells me, J-Lo?",
 "Tom Brady shouldn't get in on his first ballot either, because he apparently only accomplished as much as he did on the football field because of Deflategate and Spygate, the two things working against a surly Bill Belichick, who just happens to share my same alma mater.",
 'Yeah, this is, I mean, and then you have two guys coaching in the big game, Rabel and McDaniels from that Belichick coaching tree.',
 'It just, yeah.',
 'People got to take the feelings.',
 'Defies logic.',

In [9]:
len(cleaned_transcripts)

198

## Prompt LLM

### Create Prompt

In [10]:
prompt = """
Role:
    You are a text analyst.

Task:
    Determine whether the input text contains a prediction, projection, or forecast.

Definitions:
    - A prediction is a statement that asserts or implies a future outcome, result, or event.
    - It may include confidence, uncertainty, or probability.
    - It must go beyond describing current or past facts.

Instructions:
    1. Read the text carefully.
    2. Decide if a prediction/projection/forecast is present.
    3. Assign:
        - 1 if a prediction is present
        - 0 if no prediction is present

Output format (strict JSON):
    {
        "label": 0 or 1
    }
"""

### Initialize LLMs

In [11]:
tgmf = TextGenerationModelFactory()

# Option 3: All NaviGator models
# models = tgmf.create_instances(tgmf.get_navigator_model_names())
models = tgmf.create_instances(['llama-3.1-8b-instant', 'llama-3.3-70b-versatile', 'openai/gpt-oss-120b'])
models

{'llama-3.1-8b-instant': <text_generation_models.LlamaInstantTextGenerationModel at 0x1f9dddbb450>,
 'llama-3.3-70b-versatile': <text_generation_models.LlamaVersatileTextGenerationModel at 0x1f9dddbb3d0>,
 'openai/gpt-oss-120b': <text_generation_models.GptOss120bTextGenerationModel at 0x1f9dde7cd90>}

### Pass data + prompt into each LLM

In [12]:
results = []
PROMPT_TYPE = "zero-shot"   # change to "chain-of-thought" when needed

for cleaned_transcript_idx in range(len(cleaned_transcripts)):
    text = cleaned_transcripts[cleaned_transcript_idx]
    print(f"{cleaned_transcript_idx} --- Sentence: {text}")

    for model_name, model in models.items():
        raw_response, llm_label, llm_reasoning = llm_classify_text(
            data=text,
            base_prompt=prompt,
            prompt_type=PROMPT_TYPE,
            model=model
        )

        result = (
            text,
            raw_response,
            llm_label,
            llm_reasoning,
            model_name
        )
        results.append(result)

        if cleaned_transcript_idx < 3:
            if PROMPT_TYPE == "chain-of-thought":
                print(
                    f" Model: {model_name} "
                    f"| Label: {llm_label} "
                    f"| Reasoning: {llm_reasoning}"
                )
            else:
                print(
                    f" Model: {model_name} "
                    f"| Label: {llm_label}"
                )

0 --- Sentence: Hello and welcome to the Sharp 600 brought to you by Covers.com and presented by Bet365.
 Model: llama-3.1-8b-instant | Label: 0
 Model: llama-3.3-70b-versatile | Label: 0
 Model: openai/gpt-oss-120b | Label: 0
1 --- Sentence: My name is Jason Logan.
 Model: llama-3.1-8b-instant | Label: 0
 Model: llama-3.3-70b-versatile | Label: 0
 Model: openai/gpt-oss-120b | Label: 0
2 --- Sentence: I will be your host here for the next 10 minutes as we take our first bites of Super Bowl 60 odds.
 Model: llama-3.1-8b-instant | Label: 0
 Model: llama-3.3-70b-versatile | Label: 0
 Model: openai/gpt-oss-120b | Label: 0
3 --- Sentence: And joining us for that dinner, for that snack time, is former odds maker, current professional bettor Todd Furman.
4 --- Sentence: Todd, happy bye week to you.
5 --- Sentence: The Seahawks, the Patriots get a little bit of a breather, a little bit of downtime this week, but I always found the bye was like my busiest time, at least in terms of what I need to do, the capping, the content, the planning, all these things, everything that we do at Covers for Super Bowl was very, very busy.
6 --- Sentence: For you as a pro better, what do these two weeks look like?
7 --- Sentence: The schedule has changed considerably from what it is during the bye week now versus what it would have been during the bye week 10 years ago.
8 --- Sentence: I mean, J-Lo, we had player props out at most of the prominent books, bet three, six, five, as well as early as Monday morning where you've been in the industry long enough.
9 --- Sentence: And this is going to make us sound really old.
10 --- Sentence: You didn't start to get player props until Friday, Saturday, Sunday, leading up to the big game in and of itself.
11 --- Sentence: So you kind of have to have rough projections, know which players that you've targeted.
12 --- Sentence: You want to jump on right away.
13 --- Sentence: And then you begin to dig into some of the X's and O's and try and figure out, okay, where can I add to those positions?
14 --- Sentence: Where can I find my biggest edges?
15 --- Sentence: and what have the odds makers not properly accounted for versus current form compared to season-long metrics where they'll heavily weight them towards a lot of individual player performances.
16 --- Sentence: Yeah, I was betting player props Sunday night.
17 --- Sentence: They were out Sunday night in a few books.
18 --- Sentence: And that was first crack.
19 --- Sentence: First crack that Sunday compared to first crack the Sunday before the Super Bowl a decade ago.
20 --- Sentence: Yeah, I remember the Thursday before the Super Bowl and all the props would come out.
21 --- Sentence: It was like that was the big thing.
22 --- Sentence: But, yeah, times, they are changing.
23 --- Sentence: Before we start the clock here on what's going to be the second last podcast of the season, I can't believe that, a simple ask.
24 --- Sentence: If you have been listening to us all season or if you're just finding us for the first time here ahead of Super Bowl, we ask that if you like what you're hearing, let us know.
25 --- Sentence: Let other people know.
26 --- Sentence: Rate and review the podcast on those pod platforms.
27 --- Sentence: If you're watching us on YouTube, like, subscribe to the Covers YouTube channel, and leave a comment.
28 --- Sentence: What are you betting in the big game?
29 --- Sentence: We'd like to know.
30 --- Sentence: all right todd let's have 600 super seconds on the clock all right let's break down the line here super bowl 60 the spread opens as low as three and a half but we see a quick move they forget about four they go four and a half that's where we see this right now we have seen five we have seen some five and a halves uh todd for me i mean this I look at this, this is the best spread that bookies could ask for right now because of all that wiggle room in the middle.
31 --- Sentence: What are you seeing from this spread?
32 --- Sentence: What do you like?
33 --- Sentence: What have you got down on early?
34 --- Sentence: You mentioned where the number opens at 3.5.
35 --- Sentence: The look-ahead number going into the championship Sunday, you see a couple of books stick to their guns.
36 --- Sentence: Then we did see some money come in on the favor, to your point, getting stuck in no man's land where books are going to have a ton of flexibility.
37 --- Sentence: The opportunity to move down to 4 if they see professional money most likely coming in on New England, or drift the number a lot further out in that 5-5.5 range if the public comes in on one side, or I guess I should say if the professionals decide they want to back the Seahawks.
38 --- Sentence: For me, the 6 was going to be my buy point on the dog, and it wasn't widely available, so I don't really have a true position on the side in this game early on.
39 --- Sentence: My number was 4.
40 --- Sentence: I want to dig into it a little bit, figure out if there's a matchup or two that I think one of these sides can exploit.
41 --- Sentence: My initial inclination was that if you're going to give me a good defense, that's going to have the opportunity to catch points in this particular spot.
42 --- Sentence: I'm typically going to gravitate towards that more often than not, but don't have a full position on this game yet.
43 --- Sentence: And J-Lo, I'm not quite sure the betting market is going to allow me an opportunity to get involved with the number that I've targeted.
44 --- Sentence: Yeah, for me, knowing what the look-ahead spread was, I knew we were going to see a money line on Seattle around 2-1 for that favorite.
45 --- Sentence: And that's where it came out, and that's where I took them right away.
46 --- Sentence: When it comes to four and four-and-a-half point favorites, I've kind of made it a rule for myself to say, you know what don't play the points just go with the money line i find that four to four and a half is it's been since kind of four became more of a key number since 2015 it's been kind of a no man's land where that four point favorite or the four and a half point favorite will win but not quite cover they're good enough to be favored by more than a field goal but not quite good enough to be favored by six and so for me i went to seattle straight out just i mean two games over the last two weeks the new england patriots win but don't cover they close a three and a half four point favorite against the denver broncos and the week before we see the chicago bears come up just short in the straight up category but find a way to cover as a three and a half four point underdog so i think that number is a lot more important than people give it credit for and to your point you're going to see a money line that may come down as well if you gravitate towards seattle closer to kickoff yeah i mean you're going to see oh we always see underdog money on the money line So there'll probably be some Patriots outright money showing up.
47 --- Sentence: Let's talk total here.
48 --- Sentence: Look ahead was 45, open 46 and a half.
49 --- Sentence: Now we're seeing 46 is 45 and a half.
50 --- Sentence: A clear weather game for the Patriots.
51 --- Sentence: I'm leaning towards over in this one.
52 --- Sentence: I want to know your thoughts.
53 --- Sentence: A weather game times two.
54 --- Sentence: I mean, played in a blizzard in the AFC championship game and played in freezing rain the week before against the Houston Texans.
55 --- Sentence: A game that snuck over, but it wasn't because of offensive execution from either of those two teams.
56 --- Sentence: It's always interesting to figure out how much a weather is suppressing a total.
57 --- Sentence: In a game like this, it appears the forecast in Santa Clara is going to be pretty good.
58 --- Sentence: Now, it is an outdoor venue, so we're not quite sure exactly what that track is going to look like.
59 --- Sentence: We've seen games played in domes typically offer a faster track for both these teams in the past.
60 --- Sentence: For me, 47 was kind of the number that I was looking for to make a case to go under.
61 --- Sentence: If I am going to get involved in a total, I'll probably gravitate a little bit more towards looking at that first half number.
62 --- Sentence: But wish I had stronger convictions right now because I do think you have suppressed totals there.
63 --- Sentence: But you also have a Seahawks offense that's going to be stepping up in class given the last three games, two against the 49ers, one against the Rams.
64 --- Sentence: I'm not sure either of those secondaries would be described as anything more than a bottom six unit.
65 --- Sentence: Yeah, I always look at under in the derivative market, specifically in that first quarter unders.
66 --- Sentence: Those tend to be lower scoring frames.
67 --- Sentence: Both teams a little jacked up.
68 --- Sentence: You got two quarterbacks a little tight on those throws.
69 --- Sentence: We see some miscues and things like that.
70 --- Sentence: So I do lean towards those unders in the first quarter.
71 --- Sentence: All right, we've still got a lot of time here before Super Bowl kickoff.
72 --- Sentence: Let's talk do's and don'ts for sports bettors.
73 --- Sentence: I'm going to start with a do.
74 --- Sentence: And I'm going to say do take advantage of the live in-game odds, especially when it comes to any early game anomalies.
75 --- Sentence: If the Patriots get up quick, but they do so on, say, a defensive score or a special team score, anything weird that happens early on, usually you can take an advantage of a market that will overcorrect to that, especially with everyone and their dog betting in this game and people chasing their bets.
76 --- Sentence: So any early game anomalies, look and see if you can find some buyback points in the in-game markets.
77 --- Sentence: Todd, you got a do for us in terms of Super Bowl betting?
78 --- Sentence: I do, but I want to piggyback what you said, and I think the other interesting angle that you can take, it's not just side total.
79 --- Sentence: It's live player props as well that get heavily impacted by game state.
80 --- Sentence: So I think there are a lot more opportunities now than there would have been when we had this discussion, say, five, seven, ten years ago in those particular live markets.
81 --- Sentence: Dues for me, I feel like I'm a man that is absolutely no fun to watch the game with.
82 --- Sentence: Do make a case to bet a lot of player performances to come in under their posted totals.
83 --- Sentence: I know it's not fun to root against anything happening during the course of a football game, You look at a lot of these markets that are set.
84 --- Sentence: People are going to gravitate towards rooting for things to happen.
85 --- Sentence: They're going to see low yardage totals with those third and fourth string wide receivers and tight ends and hope those players can come up with a catcher to do look to bet things under and do be willing to lay prices to be able to do so.
86 --- Sentence: And are we doing that on closer to kickoff, waiting for those odds to go up?
87 --- Sentence: Certain players, I would say yes.
88 --- Sentence: Other players, sometimes you have to jump a little bit sooner.
89 --- Sentence: but I would not be running to bet JSN under his receiving total until the 23rd hour let's put it that way all right well I've got a don't here and this is more of an etiquette thing if you're at a Super Bowl party if you're with a group and that group is maybe not of the betting guild don't constantly talk about your bets I'm someone that does this for for a job and I can't stand those people if you listen if you're with your buddies and it's the group ride parlay and this is your group chat that you're with you know party up go crazy have not go nuts but for god's sakes read the room and don't get down on everyone because you're losing some wager celebrate your wins you hit a 25 to 1 first touchdown winner celebrate it have fun if you lose on heads don't throw a fit don't bring everyone down keep your keep your betting excitement in check that that's my don't todd you got a don't for us you know one of my don'ts is don't be a superbowl grinch like me who typically watches the big game every year by himself given some of the immediate responsibilities that I have.
90 --- Sentence: I can control the temperature.
91 --- Sentence: I can control the alcohol intake and the food and everything else.
92 --- Sentence: But for me, it's don't chase some of those long shot prices with the majority of your bankroll.
93 --- Sentence: It's more than fine to get involved in some of those long shot markets.
94 --- Sentence: But at the same time, if anything, you're not getting the necessary value and upside for trying to look for some of those depth players to go over those laddering numbers that are out there or a variety of other markets.
95 --- Sentence: So don't just chase that plus money.
96 --- Sentence: Be judicious about how you allocate your bankroll.
97 --- Sentence: All right, time to talk Super Bowl MVP odds.
98 --- Sentence: Todd, who do you like to be the most valuable player Super Bowl 60?
99 --- Sentence: So J-Lo, normally you're gonna gravitate towards the starting quarterback of the team that you think is going to win the game, but what fun would that be in a game like this?
100 --- Sentence: I am going to take a skilled position player for a team that I think wins the game, and that would lead me to Ramondre Stevenson at 28 to one.
101 --- Sentence: look we've seen a Patriots running back get snubbed in the past that had 37 catches and like 900 receiving yards this is a chance for the world to right all of its wrongs and give Ramondre the hardware if he has two touchdowns and 75 all-purpose yards give me Ramondre Stevenson 28 to 1 all right I'll see your skill player and raise you a defensive player go on Demarcus Lawrence it only makes sense that a cowboy is going to get to the Super Bowl and show it almost last year I did uh but I'm happy for Tank but let's talk about this defense this is the reason why San Seattle is here This is the reason why they're favored.
102 --- Sentence: He is the most disruptive player on this team.
103 --- Sentence: Six sacks, 11 tackles for a loss, three forced fumbles, scooped up all of those in the regular season.
104 --- Sentence: Two sacks, three forced fumbles in the playoffs so far.
105 --- Sentence: The Patriots pass protection hasn't been great.
106 --- Sentence: I like Tank, MVP, plus 10,000.
107 --- Sentence: All right, two-minute drill time.
108 --- Sentence: Early bets here for Super Bowl 60.
109 --- Sentence: I'm going with Seattle receiver Raheed Shaheed, over 21.5 yards, receiving minus 110.
110 --- Sentence: since he came over at the trade deadline.
111 --- Sentence: Seattle has faced a lot of opponents that run zone.
112 --- Sentence: A lot of those defense runs zone exclusively.
113 --- Sentence: He is a much better receiver at man.
114 --- Sentence: And what does he face in the Patriots?
115 --- Sentence: He faces a defense that runs one of the highest rates of man.
116 --- Sentence: There's also someone that likes throwing against man, and that's Sam Darnold.
117 --- Sentence: So I think Shahid gets loose here.
118 --- Sentence: He could put this one away in one catch.
119 --- Sentence: Over 21 and a half yards receiving.
120 --- Sentence: Rashid Shahid still on my shit list because he didn't want to take contact over a half a rushing yard with the end around.
121 --- Sentence: decided he was going to dance around.
122 --- Sentence: And example number 758.
123 --- Sentence: I had it.
124 --- Sentence: Why you can't trust a Diva wide receiver as a ball carrier in the backfield.
125 --- Sentence: For me, I'm going to go to that Seattle Seahawks backfield though and take Kenneth Walker under his rushing total at 75 and a half.
126 --- Sentence: Look, Walker started out like a house on fire last week against the Rams.
127 --- Sentence: Eight carries early on in that game for 35 yards and then kind of petered out.
128 --- Sentence: 11 carries the rest of the game and didn't show that big explosive potential even against the much maligned Rams run defense.
129 --- Sentence: Now he steps up in class against the Patriots run defense that is truly elite when Milton Williams is back in the full to anchor that defensive line.
130 --- Sentence: Seattle does love to run the football on early downs.
131 --- Sentence: I think they may have to go away from that approach.
132 --- Sentence: And even without Zach Charbonnet, I just don't see Kenneth Walker getting to mid-70s or higher.
133 --- Sentence: I have him projected J-Lo in the high 60s, under 75.5 for the bell cow back wearing Seahawks colors.
134 --- Sentence: All right, I'm going to go to the tight end for the Patriots.
135 --- Sentence: Hunter Henry over 36.5 yards, receiving minus 110.
136 --- Sentence: He's been taking some punishment, and now he faces a ferocious Seattle pass rush that can get pressure with just four.
137 --- Sentence: He's not going to have time for downfield plays to develop.
138 --- Sentence: He's going to have to hit those quick hits, and Hunter Henry has been that pressure release.
139 --- Sentence: We have seen Seattle give up a lot of targets, a lot of receptions, two tight ends.
140 --- Sentence: Projections for Henry, sit as high as 46.
141 --- Sentence: I like him to go over 36.5.
142 --- Sentence: Small flyer for me, a Seattle Seahawks receiver, not named Cooper Cup, not named Rasheed Sheed, not named Jackson Smith and Jigba.
143 --- Sentence: Jake Bobo, over a half a receiving yard at plus $1.15.
144 --- Sentence: Bobo had a catch in each of the last two games, 16 yards, 17 yards.
145 --- Sentence: I think he's a guy that may be targeted a couple times here.
146 --- Sentence: Just one catch, get us one yard, take me there at plus $1.15.
147 --- Sentence: All right, you got two weeks to scheme up some stuff.
148 --- Sentence: You got to get tricky sometimes and throw those guys in there.
149 --- Sentence: He did not have a touchdown in that NFC Championship game.
150 --- Sentence: Was he the guy that scored a touchdown in that one?
151 --- Sentence: No, he did have a touchdown there.
152 --- Sentence: Had one catch each of the last two games, 16 yards, 17 yards, and a TD.
153 --- Sentence: All I'm just looking for is a receiving yard here to get us across the finish line.
154 --- Sentence: Yeah, that's it.
155 --- Sentence: He's not asking for much, Bobo.
156 --- Sentence: Just, you know, that's it.
157 --- Sentence: That's it.
158 --- Sentence: I can't wait to see you freak out on Super Bowl Sunday when he doesn't get that.
159 --- Sentence: But remember the etiquette.
160 --- Sentence: Yeah.
161 --- Sentence: All right.
162 --- Sentence: A couple of targets.
163 --- Sentence: A couple of targets.
164 --- Sentence: A couple of drops.
165 --- Sentence: You know how this goes.
166 --- Sentence: I know exactly how it goes.
167 --- Sentence: It'll be all right.
168 --- Sentence: All right.
169 --- Sentence: That is it for our first Super Bowl pod.
170 --- Sentence: We will have another one next week.
171 --- Sentence: A big thanks to Chris behind the scenes.
172 --- Sentence: A big thank you to Todd for joining us once again.

> - DataFrame below will have the same sentence (in text column) for all three llms (in the llm_name), then next set of rows will be another sentences with same llms.
> - llm_label column: {0: non-prediction, 1: prediction}

In [13]:
results_with_llm_label_df = pd.DataFrame(
    results,
    columns=['text', 'raw_response', 'llm_label', 'llm_reasoning', 'llm_name']
)

# Ensure labels are valid integers (0/1), fallback to -1 if malformed
results_with_llm_label_df['llm_label'] = (
    pd.to_numeric(results_with_llm_label_df['llm_label'], errors='coerce')
      .fillna(-1)
      .astype(int)
)

# Normalize reasoning: keep only when present (chain-of-thought), else None
results_with_llm_label_df['llm_reasoning'] = (
    results_with_llm_label_df['llm_reasoning'].where(
        results_with_llm_label_df['llm_reasoning'].notna(),
        None
    )
)

results_with_llm_label_df.tail(6)

,text,raw_response,llm_label,llm_reasoning,llm_name
588,"We're going to talk, go even deeper on Super Bowl 60 odds, our best bets, our touchdown picks, all coming next Wednesday.","{""label"": 0}",0,None,llama-3.1-8b-instant
589,"We're going to talk, go even deeper on Super Bowl 60 odds, our best bets, our touchdown picks, all coming next Wednesday.","{""label"": 1}",1,None,llama-3.3-70b-versatile
590,"We're going to talk, go even deeper on Super Bowl 60 odds, our best bets, our touchdown picks, all coming next Wednesday.","{\n ""label"": 0\n}",0,None,openai/gpt-oss-120b
591,"And until then, I guess, enjoy whatever you're wagering on this weekend and best of luck with those bets.","{""label"": 0}",0,None,llama-3.1-8b-instant
592,"And until then, I guess, enjoy whatever you're wagering on this weekend and best of luck with those bets.","{""label"": 0}",0,None,llama-3.3-70b-versatile
593,"And until then, I guess, enjoy whatever you're wagering on this weekend and best of luck with those bets.","{""label"": 0}",0,None,openai/gpt-oss-120b

In [14]:
# Reshape to have llm names as column names
results_df = (
    results_with_llm_label_df
    .pivot_table(
        index='text',
        columns='llm_name',
        values='llm_label',
        aggfunc='first'   # one label per model per sentence
    )
    .reset_index()
    .rename(columns={'text': 'Base Sentence'})
)
results_df

llm_name,Base Sentence,llama-3.1-8b-instant,llama-3.3-70b-versatile,openai/gpt-oss-120b
0,11 carries the rest of the game and didn't show that big explosive potential even against the much maligned Rams run defense.,0,0,0
1,A big thank you to Todd for joining us once again.,0,0,0
2,A big thanks to Chris behind the scenes.,0,0,0
3,A clear weather game for the Patriots.,0,0,1
4,A couple of drops.,0,0,0
...,...,...,...,...
191,but I would not be running to bet JSN under his receiving total until the 23rd hour let's put it that way all right well I've got a don't here and this is more of an etiquette thing if you're at a Super Bowl party if you're with a group and that group is maybe not of the betting guild don't constantly talk about your bets I'm someone that does this for for a job and I can't stand those people if you listen if you're with your buddies and it's the group ride parlay and this is your group chat that you're with you know party up go crazy have not go nuts but for god's sakes read the room and don't get down on everyone because you're losing some wager celebrate your wins you hit a 25 to 1 first touchdown winner celebrate it have fun if you lose on heads don't throw a fit don't bring everyo...,0,0,0
192,decided he was going to dance around.,0,0,1
193,look we've seen a Patriots running back get snubbed in the past that had 37 catches and like 900 receiving yards this is a chance for the world to right all of its wrongs and give Ramondre the hardware if he has two touchdowns and 75 all-purpose yards give me Ramondre Stevenson 28 to 1 all right I'll see your skill player and raise you a defensive player go on Demarcus Lawrence it only makes sense that a cowboy is going to get to the Super Bowl and show it almost last year I did uh but I'm happy for Tank but let's talk about this defense this is the reason why San Seattle is here This is the reason why they're favored.,0,1,1
194,since he came over at the trade deadline.,0,0,0
195,thanks to beth365 for the odds and of course thank you to you for tuning in and listening whether you've been with us all year or you're just finding us here ahead of the big game a reminder if you like what we're doing rate and review like and subscribe on youtube it just takes a matter of seconds uh but it means a lot to us so please do that when you can todd uh you thought you would get out of this podcast without some super bowl silliness but no because you know i mean i look not my first rodeo i know better that there's always something waiting behind door number three it's a basic one by this by this point in in super bowl betting this is a very common wager what color gatorade is going to get thrown on the winning coach here at the end of super bowl six i mean i feel like you're...,0,1,1

### Majority Vote (across LLMs)

> - llm_label column: {0: non-prediction, 1: prediction}

In [15]:
results_df['Majority Vote Label'] = (
    results_df
    .iloc[:, 1:]               # exclude sentence column
    .mode(axis=1)[0]
    .astype(int)
)

results_df.head()

llm_name,Base Sentence,llama-3.1-8b-instant,llama-3.3-70b-versatile,openai/gpt-oss-120b,Majority Vote Label
0,11 carries the rest of the game and didn't show that big explosive potential even against the much maligned Rams run defense.,0,0,0,0
1,A big thank you to Todd for joining us once again.,0,0,0,0
2,A big thanks to Chris behind the scenes.,0,0,0,0
3,A clear weather game for the Patriots.,0,0,1,0
4,A couple of drops.,0,0,0,0

Add 'Human Annotation', 'Human Reasoning' columns to write human input, and 'Video ID' column to grab the video source from the respective sentence.

In [16]:
results_df[['Human Annotation', 'Human Reasoning']] = np.nan
final_results_df = pd.concat([results_df, raw_transcripts_df[['Video ID']]], axis=1)
final_results_df.head()

,Base Sentence,llama-3.1-8b-instant,llama-3.3-70b-versatile,openai/gpt-oss-120b,Majority Vote Label,Human Annotation,Human Reasoning,Video ID
0,11 carries the rest of the game and didn't show that big explosive potential even against the much maligned Rams run defense.,0.0,0.0,0.0,0.0,NaN,NaN,FPl-F2k_KtM
1,A big thank you to Todd for joining us once again.,0.0,0.0,0.0,0.0,NaN,NaN,FPl-F2k_KtM
2,A big thanks to Chris behind the scenes.,0.0,0.0,0.0,0.0,NaN,NaN,FPl-F2k_KtM
3,A clear weather game for the Patriots.,0.0,0.0,1.0,0.0,NaN,NaN,FPl-F2k_KtM
4,A couple of drops.,0.0,0.0,0.0,0.0,NaN,NaN,FPl-F2k_KtM

In [17]:
predictions = final_results_df[final_results_df['Majority Vote Label']==1]

In [18]:
predictions

,Base Sentence,llama-3.1-8b-instant,llama-3.3-70b-versatile,openai/gpt-oss-120b,Majority Vote Label,Human Annotation,Human Reasoning,Video ID
18,"And J-Lo, I'm not quite sure the betting market is going to allow me an opportunity to get involved with the number that I've targeted.",1.0,0.0,1.0,1.0,NaN,NaN,FPl-F2k_KtM
20,"And even without Zach Charbonnet, I just don't see Kenneth Walker getting to mid-70s or higher.",1.0,1.0,1.0,1.0,NaN,NaN,FPl-F2k_KtM
23,"And one more thing, Belichick, up for Hall of Fame, doesn't get in on the first time around.",1.0,1.0,1.0,1.0,NaN,NaN,FPl-F2k_KtM
41,"But you also have a Seahawks offense that's going to be stepping up in class given the last three games, two against the 49ers, one against the Rams.",1.0,1.0,1.0,1.0,NaN,NaN,FPl-F2k_KtM
45,Do make a case to bet a lot of player performances to come in under their posted totals.,1.0,1.0,1.0,1.0,NaN,NaN,FPl-F2k_KtM
47,Early bets here for Super Bowl 60.,1.0,1.0,0.0,1.0,NaN,NaN,FPl-F2k_KtM
51,"For me, I'm going to go to that Seattle Seahawks backfield though and take Kenneth Walker under his rushing total at 75 and a half.",1.0,1.0,1.0,1.0,NaN,NaN,FPl-F2k_KtM
55,He could put this one away in one catch.,0.0,1.0,1.0,1.0,NaN,NaN,FPl-F2k_KtM
63,He's not going to have time for downfield plays to develop.,1.0,1.0,1.0,1.0,NaN,NaN,FPl-F2k_KtM
65,"Hunter Henry over 36.5 yards, receiving minus 110.",1.0,1.0,1.0,1.0,NaN,NaN,FPl-F2k_KtM
66,"I am going to take a skilled position player for a team that I think wins the game, and that would lead me to Ramondre Stevenson at 28 to one.",1.0,1.0,1.0,1.0,NaN,NaN,FPl-F2k_KtM
69,I can't wait to see you freak out on Super Bowl Sunday when he doesn't get that.,0.0,1.0,1.0,1.0,NaN,NaN,FPl-F2k_KtM
73,"I have him projected J-Lo in the high 60s, under 75.5 for the bell cow back wearing Seahawks colors.",1.0,1.0,1.0,1.0,NaN,NaN,FPl-F2k_KtM
79,I like him to go over 36.5.,1.0,1.0,0.0,1.0,NaN,NaN,FPl-F2k_KtM
84,I think he's a guy that may be targeted a couple times here.,1.0,1.0,1.0,1.0,NaN,NaN,FPl-F2k_KtM
85,I think they may have to go away from that approach.,0.0,1.0,1.0,1.0,NaN,NaN,FPl-F2k_KtM
86,"I want to dig into it a little bit, figure out if there's a matchup or two that I think one of these sides can exploit.",0.0,1.0,1.0,1.0,NaN,NaN,FPl-F2k_KtM
90,I'm going to start with a do.,0.0,1.0,1.0,1.0,NaN,NaN,FPl-F2k_KtM
91,"I'm going with Seattle receiver Raheed Shaheed, over 21.5 yards, receiving minus 110.",1.0,1.0,1.0,1.0,NaN,NaN,FPl-F2k_KtM
92,I'm leaning towards over in this one.,1.0,1.0,1.0,1.0,NaN,NaN,FPl-F2k_KtM
95,"If I am going to get involved in a total, I'll probably gravitate a little bit more towards looking at that first half number.",1.0,1.0,1.0,1.0,NaN,NaN,FPl-F2k_KtM
96,"If the Patriots get up quick, but they do so on, say, a defensive score or a special team score, anything weird that happens early on, usually you can take an advantage of a market that will overcorrect to that, especially with everyone and their dog betting in this game and people chasing their bets.",1.0,1.0,1.0,1.0,NaN,NaN,FPl-F2k_KtM
99,"In a game like this, it appears the forecast in Santa Clara is going to be pretty good.",1.0,1.0,1.0,1.0,NaN,NaN,FPl-F2k_KtM
102,It'll be all right.,0.0,1.0,1.0,1.0,NaN,NaN,FPl-F2k_KtM
106,"Jake Bobo, over a half a receiving yard at plus $1.15.",0.0,1.0,1.0,1.0,NaN,NaN,FPl-F2k_KtM
115,"My initial inclination was that if you're going to give me a good defense, that's going to have the opportunity to catch points in this particular spot.",0.0,1.0,1.0,1.0,NaN,NaN,FPl-F2k_KtM
124,People are going to gravitate towards rooting for things to happen.,1.0,1.0,1.0,1.0,NaN,NaN,FPl-F2k_KtM
127,"Projections for Henry, sit as high as 46.",1.0,1.0,1.0,1.0,NaN,NaN,FPl-F2k_KtM
135,So I do lean towards those unders in the first quarter.,1.0,1.0,1.0,1.0,NaN,NaN,FPl-F2k_KtM
142,"So you kind of have to have rough projections, know which players that you've targeted.",1.0,1.0,0.0,1.0,NaN,NaN,FPl-F2k_KtM
144,That'll probably be on the sideline.,1.0,1.0,1.0,1.0,NaN,NaN,FPl-F2k_KtM
149,"The opportunity to move down to 4 if they see professional money most likely coming in on New England, or drift the number a lot further out in that 5-5.5 range if the public comes in on one side, or I guess I should say if the professionals decide they want to back the Seahawks.",1.0,1.0,1.0,1.0,NaN,NaN,FPl-F2k_KtM
154,They're going to see low yardage totals with those third and fourth string wide receivers and tight ends and hope those players can come up with a catcher to do look to bet things under and do be willing to lay prices to be able to do so.,1.0,1.0,1.0,1.0,NaN,NaN,FPl-F2k_KtM
164,We will have another one next week.,1.0,1.0,1.0,1.0,NaN,NaN,FPl-F2k_KtM
173,"When it comes to four and four-and-a-half point favorites, I've kind of made it a rule for myself to say, you know what don't play the points just go with the money line i find that four to four and a half is it's been since kind of four became more of a key number since 2015 it's been kind of a no man's land where that four point favorite or the four and a half point favorite will win but not quite cover they're good enough to be favored by more than a field goal but not quite good enough to be favored by six and so for me i went to seattle straight out just i mean two games over the last two weeks the new england patriots win but don't cover they close a three and a half four point favorite against the denver broncos and the week before we see the chicago bears come up just short in ...",0.0,1.0,1.0,1.0,NaN,NaN,FPl-F2k_KtM
179,"Yeah, for me, knowing what the look-ahead spread was, I knew we were going to see a money line on Seattle around 2-1 for that favorite.",1.0,1.0,1.0,1.0,NaN,NaN,FPl-F2k_KtM
190,and what have the odds makers not properly accounted for versus current form compared to season-long metrics where they'll heavily weight them towards a lot of individual player performances.,1.0,1.0,0.0,1.0,NaN,NaN,FPl-F2k_KtM
193,look we've seen a Patriots running back get snubbed in the past that had 37 catches and like 900 receiving yards this is a chance for the world to right all of its wrongs and give Ramondre the hardware if he has two touchdowns and 75 all-purpose yards give me Ramondre Stevenson 28 to 1 all right I'll see your skill player and raise you a defensive player go on Demarcus Lawrence it only makes sense that a cowboy is going to get to the Super Bowl and show it almost last year I did uh but I'm happy for Tank but let's talk about this defense this is the reason why San Seattle is here This is the reason why they're favored.,0.0,1.0,1.0,1.0,NaN,NaN,FPl-F2k_KtM
195,thanks to beth365 for the odds and of course thank you to you for tuning in and listening whether you've been with us all year or you're just finding us here ahead of the big game a reminder if you like what we're doing rate and review like and subscribe on youtube it just takes a matter of seconds uh but it means a lot to us so please do that when you can todd uh you thought you would get out of this podcast without some super bowl silliness but no because you know i mean i look not my first rodeo i know better that there's always something waiting behind door number three it's a basic one by this by this point in in super bowl betting this is a very common wager what color gatorade is going to get thrown on the winning coach here at the end of super bowl six i mean i feel like you're...,0.0,1.0,1.0,1.0,NaN,NaN,FPl-F2k_KtM

In [19]:
base_data_path = DataProcessing.load_base_data_path(notebook_dir=notebook_dir)
save_data_path = os.path.join(base_data_path, "yt", "majority_vote", "sports")
DataProcessing.save_to_file(predictions, path=save_data_path, prefix='batch_11', save_file_type='csv', include_version=False)

Saving CSV file to: c:\Users\adria\OneDrive\Área de Trabalho\UF Data Studio\predictions\prediction_acquition-youtube\../data\yt\majority_vote\sports\batch_11.csv